import React from "react";
import { createRoot } from "react-dom/client";
import { seoTranslations } from "../app/seo-translations";
import { seoTranslationCoverage } from "../app/seo-translation-coverage";
import "./style.css";

const languages = ["en","de","fr","es","it","nl","pl","sv","pt"] as const;
const names: Record<string,string> = {en:"English",de:"Deutsch",fr:"Français",es:"Español",it:"Italiano",nl:"Nederlands",pl:"Polski",sv:"Svenska",pt:"Português"};
const categoryUrls=["/shoes/","/hoodies-sweaters/","/t-shirts/","/jackets/","/pants-shorts/","/accessories/","/headwear/","/accessories/","/jersey/","/electronics/"];
const categories=["Shoes","Hoodies","T-Shirts","Jackets","Pants / Shorts","Bags","Headwear","Accessories","Jerseys","Electronics"];
const products=[
 ["Nike Phantom GX Elite AG-PRO","$40.48","/shoes/nike-phantom-gx-elite-ag-pro-271.html"],
 ["GCDS Logo Band Hoodie","$36.90","/hoodies-sweaters/gcds-logo-band-hoodiessweaters-40-styles-1523.html"],
 ["New Balance 550 Sneakers","$38.69","/shoes/new-balance-550-sneakers-13-styles-1753.html"],
 ["Ralph Lauren Polo Set","$20.54","/ShortSets/ralph-lauren-polo-short-sleeve-shirt-amp-shorts-set-5-styles-2008.html"]
];
const english = { title:"How to Use a PikoBuy Spreadsheet Without Buying Blind", intro:"A practical guide to product links, the two-payment process, warehouse photos, returns and international shipping.", quick:"A PikoBuy spreadsheet is useful for discovery, but it is not the final product record. Check the live item, warehouse photos, return window and shipping route before paying at each stage.", sections:[
 ["What PikoBuy actually does",["PikoBuy describes itself as a China purchasing and forwarding platform. Its official beginner guide says shoppers can find items on Taobao, Tmall, 1688, Weidian, Yupoo and other platforms. A shopper can paste a product link or keywords into PikoBuy to request purchasing service.","PikoBuy is not the original seller. It sits between the shopper, marketplace seller, China warehouse and international carrier. The seller controls the item and domestic dispatch, PikoBuy handles purchasing, warehouse processing and parcel submission, and a third-party carrier handles international transport."]],
 ["Where a PikoBuy spreadsheet fits",["A spreadsheet is a research index. It groups product links, images and price references, but does not freeze the seller’s stock, price, size choices or return rules.","Start with two or three comparable products. Record the exact colour, size, version and seller. Confirm specifications before ordering and save item information because a seller can edit or remove a listing."]],
 ["Check the live item before the first payment",["Confirm selected size, colour, quantity, model and included parts on the current item page. Use measurements rather than only S, M or L; for shoes check the size chart, and for electronics confirm model, plug and voltage.","The official flow separates product payment from international shipping. Actual purchase price applies and an out-of-stock order is refunded, so a spreadsheet price is a reference, not a guaranteed checkout total.","Domestic delivery, seller price changes and optional services can affect the amount before warehouse arrival. International shipping comes later; a cheap item can still be expensive if it is bulky, heavy or restricted."]],
 ["Use warehouse photos as evidence, not a guarantee",["PikoBuy says items are checked in, photographed and inspected for visible defects after they arrive at its warehouse. Minimal or reinforced packaging can be requested before parcel submission.","First check identity: product, colour, size label and quantity. Then check visible condition. Review shoe profile, heel, outsole, toe and stitching; check clothing measurements, seams, print, cuffs and labels; inspect bag proportions, hardware, zipper, lining and straps.","Photos cannot prove authenticity, fibre composition, durability, battery health, exact screen colour or a customs outcome. A useful spreadsheet does not call an item perfect or risk-free from a few images."]],
 ["Act quickly if the item is wrong",["The official returns page describes a 5-day, or 120-hour, window after an eligible item reaches In Warehouse status. The seller must support a return, the item must remain resalable and the request must be timely.","Custom goods, intimate apparel, food, second-hand products and some opened or sealed products may not qualify. New sneakers, cosmetics, electronics, cameras and collectibles also have packaging rules.","For an unconditional return, the published policy lists return shipping, the seller’s original shipping fee and an RMB 5 service fee. Wrong items or confirmed quality problems may be handled differently, but seller agreement matters.","Forwarded goods need extra care: PikoBuy says it does not provide after-sales service for goods a user forwards to the warehouse. Contact the sender or seller; PikoBuy can only help ship goods back."]],
 ["Estimate shipping before buying",["The estimator asks for destination, product type, weight, length, width and height. Weight alone is not enough: a large light parcel can be billed by volume, and routes differ in delivery time and billing method.","Shoe boxes, rigid bags, puffer jackets and protective packaging add volume. Batteries, liquids and sensitive goods can reduce route choices. Use current route data at parcel time because eligibility and prices can change.","Products from different sellers can be combined. Consolidation can reduce repeated base charges but a larger parcel is not automatically cheapest. Compare packed weight, dimensions, routes, insurance and content value."]],
 ["Understand tracking and delivery risk",["After warehouse review, choose a route, submit the parcel and pay international shipping. Tracking can become available within three days after dispatch; that is not a delivery promise.","Third-party providers carry parcels. Customs action, confiscation, damage, loss and peak-season delays remain possible risks. No spreadsheet can guarantee zero customs checks or a fixed arrival date for every country."]]
 ], checklist:["Match the spreadsheet image and name to the current item page.","Confirm colour, size, model, quantity and included parts.","Check current seller price, domestic delivery and stock.","Estimate weight and parcel dimensions before the first payment.","Save item and seller information.","At warehouse arrival, check identity before quality.","Use the return request quickly for an eligible wrong item.","Compare routes and billing methods before parcel payment.","Keep order, warehouse, return and tracking records until delivery."], final:["The best PikoBuy spreadsheet reduces search noise and tells you what to verify next. Use the live item page for the variant and price, warehouse photos for visible identity and condition, and current policies before deadlines or payments.","It remains a discovery tool, not a seller, inspector, carrier or guarantee."] };

function parse(){const parts=location.pathname.split("/").filter(Boolean);const lang=languages.includes(parts[0] as any)?parts.shift()!:"en";return {lang,path:parts.join("/")};}
function go(lang:string,path:string){location.href=`/${lang==="en"?"":lang+"/"}${path}`.replace(/\/{2,}/g,"/");}
function Header({lang,path}:{lang:string,path:string}){return <header><a className="brand" href="/"><img src="/pikobuy-logo.png"/> <span>PikoBuy Spreadsheet</span></a><nav>{[["","Home"],["categories","Categories"],["products","Products"],["guides","Guides"],["seo-articles","SEO Articles"],["faq","FAQ"]].map(([p,n])=><a key={p} href={`/${lang==="en"?"":lang+"/"}${p}`}>{n}</a>)}</nav><select aria-label="Language" value={lang} onChange={e=>go(e.target.value,path)}>{languages.map(x=><option key={x} value={x}>{names[x]}</option>)}</select></header>}
function Footer(){return <footer>Independent research for FindSpreadsheet · <a href="https://findspreadsheet.com/">FindSpreadsheet</a></footer>}
function Home(){return <><section className="hero"><p>INDEPENDENT PIKOBUY RESEARCH</p><h1>Find products with a clearer buying record.</h1><p>Compare links, current details, QC photos and parcel decisions before you order.</p><form action="https://findspreadsheet.com/search.html"><input name="keywords" placeholder="Search products"/><button>Search FindSpreadsheet</button></form></section><section><h2>Browse categories</h2><div className="grid">{categories.map((c,i)=><a className="card" href={`https://findspreadsheet.com${categoryUrls[i]}`} key={c}><b>{c}</b><span>Open matching products on FindSpreadsheet</span></a>)}</div></section><section><h2>SEO article</h2><a className="feature" href="/seo-articles/pikobuy-spreadsheet-research-guide">Read the complete PikoBuy spreadsheet research guide →</a></section></>}
function Seo({lang}:{lang:string}){const data=lang==="en"?english:seoTranslations[lang];const coverage=lang==="en"?[]:seoTranslationCoverage[lang];return <article><div className="article-top"><p>SEO ARTICLE · FACT-CHECKED</p><h1>{data.title}</h1><p>{data.intro}</p></div><div className="fact"><b>{data.quick}</b></div>{data.sections.map((s:any,i:number)=><section key={s[0]||s.title}><h2>{s[0]||s.title}</h2>{(s[1]||s.paragraphs).map((p:string)=><p key={p}>{p}</p>)}{coverage[i]&&<p>{coverage[i]}</p>}</section>)}<section><h2>Practical checklist</h2><ol>{data.checklist.map((x:string)=><li key={x}>{x}</li>)}</ol></section><section><h2>Final takeaway</h2>{data.final.map((x:string)=><p key={x}>{x}</p>)}</section></article>}
function Simple({path}:{path:string}){if(path==="categories")return <section><h1>Product categories</h1><div className="grid">{categories.map((c,i)=><a className="card" href={`https://findspreadsheet.com${categoryUrls[i]}`} key={c}>{c}</a>)}</div></section>;if(path==="products")return <section><h1>Featured products</h1><div className="grid">{products.map(p=><a className="card" href={`https://findspreadsheet.com${p[2]}`} key={p[0]}><b>{p[0]}</b><span>{p[1]} · View on FindSpreadsheet</span></a>)}</div></section>;if(path==="faq")return <section><h1>PikoBuy Spreadsheet FAQ</h1>{["Is this an official PikoBuy website? No. It is an independent FindSpreadsheet research resource.","Are product prices final? No. Check the live seller price, stock and later parcel cost.","What do QC photos show? They show visible details, not authenticity or customs guarantees.","How is shipping estimated? Destination, route, weight, volume and product restrictions all matter."].map(x=><p className="faq" key={x}>{x}</p>)}</section>;return <section><h1>{path==="guides"?"Buying guides":"SEO articles"}</h1><a className="feature" href="/seo-articles/pikobuy-spreadsheet-research-guide">How to use a PikoBuy spreadsheet without buying blind →</a></section>}
function App(){const {lang,path}=parse();return <><Header lang={lang} path={path}/><main>{path==="seo-articles/pikobuy-spreadsheet-research-guide"?<Seo lang={lang}/>:path?<Simple path={path}/>:<Home/>}</main><Footer/></>};createRoot(document.getElementById("root")!).render(<App/>);
