export const seoArticle = {
  reviewed: "Last reviewed: September 2026",
  title: "How to Use LoloBuy for Product Research: A Practical Order-to-Parcel Workflow",
  intro: "A careful LoloBuy order is not a single click. It is a series of decisions: identify the exact item, separate product research from warehouse inspection, and only then decide how to build an international parcel. This independent guide explains the public workflow LoloBuy displays on its homepage and turns it into a buyer-first checklist. It does not predict delivery dates, customs outcomes, product authenticity, or a final shipping price.",
  sections: [
    {heading:"1. Start with the workflow, not a promise", paragraphs:[
      "LoloBuy publicly presents an order flow built around product input, order payment, warehouse quality inspection and storage, followed by parcel submission and international shipping. That sequence matters because each stage answers a different question. A product page helps you decide whether an item is worth attempting to buy. A warehouse update helps you decide whether the received item matches the order. A parcel screen helps you decide which stored items should travel together. Treating those as one decision is where many buyers lose context.",
      "The practical benefit of a staged workflow is traceability. Keep the original product link, the selected option, the seller-facing title, and your size or colour choice together before you submit. When the warehouse image arrives later, you have something specific to compare it against. If the information is vague at the start, a later inspection image can be difficult to interpret. This is a research habit, not a promise that every listing or purchase will work out." ]},
    {heading:"2. Use the product input to capture the exact item", paragraphs:[
      "The LoloBuy homepage provides an input for a product link or product name and also shows an image-search option. Use that starting point to record the most precise version of the item you intend to order. A broad label such as “grey hoodie” is rarely enough. Note the variation, measurements, material description, seller images, and any listing notes that affect the order. If the page presents a size chart, compare it with an item you already own rather than relying on a single letter size.",
      "This is also the right time to separate what you can observe from what you cannot. Listing images and descriptions may help you compare an option; they are not an independent guarantee of construction, fit, stock, or authenticity. Keep a small order note with the product URL, variation, requested size and the questions you want the warehouse images to answer. That note creates a clean reference point when the order moves to storage." ]},
    {heading:"3. Understand what the order-payment step covers", paragraphs:[
      "LoloBuy’s public order-flow text describes paying for the product price and freight within mainland China. In plain language, that is the purchasing stage before an international parcel is submitted. It should not be confused with the later choice of an international shipping route. Buyers often plan a total budget too early by treating a product price as the final cost. A more cautious approach is to regard product payment, domestic movement to the warehouse, optional parcel choices, and international shipment as separate checkpoints.",
      "Before paying, read the item information again and save a record of the chosen option. A useful order note includes the item name, seller link, selected variation, quantity, and the reason you picked it. That does not create a return right or a price lock; it simply makes later comparison possible. If a detail is important enough to change your decision, write it down before the purchase stage rather than trying to reconstruct it from memory after the item reaches the warehouse." ]},
    {heading:"4. Treat warehouse inspection as evidence, not certification", paragraphs:[
      "The official homepage describes warehouse quality inspection, inspection pictures, and feedback when items arrive. Those materials are valuable because they show the received item in the warehouse context. Use them to compare observable details: colour, visible defects, logo placement if relevant to your order, obvious size-label differences, quantity, and whether the item broadly resembles the selected variation. Keep the original listing beside the inspection images and look for the specific details you identified earlier.",
      "Inspection photos still have limits. A photo may not prove internal construction, long-term durability, exact fabric composition, authenticity, or how an item will fit after wear. Lighting and angles can also change how colour appears. The sensible question is not “does this photo guarantee the item?” but “does this photo answer the checks that would make me keep, change, or remove the item?” If it does not, avoid inventing certainty from an incomplete image set." ]},
    {heading:"5. Use storage to slow down the decision", paragraphs:[
      "LoloBuy’s homepage currently states that it offers 180 days of free storage. The useful implication is that buyers can review stored orders before creating a parcel, rather than assuming every item must be shipped immediately. Storage terms can change, so confirm the current account or checkout information before relying on a date. The buyer-side advantage is time to collect inspection feedback, compare related purchases, and decide whether an item belongs in the same shipment as the others.",
      "Use that time deliberately. Label your stored items by purpose: essentials, seasonal items, fragile items, bulky items, or items awaiting a decision. This makes it easier to see whether a parcel combines products that need different handling. Storage is a window for better organisation, not a reason to stop checking the details that matter to your order." ]},
    {heading:"6. Build a parcel around trade-offs", paragraphs:[
      "The public LoloBuy flow says that you can select products stored in the warehouse and submit them as a single parcel. Consolidation can make an order easier to manage, but it also creates trade-offs. More items may mean a larger or heavier parcel; a bulky item can change the shipment profile; and packing one item with another does not remove destination-specific rules. Review the stored list before submission and remove uncertainty where you still can.",
      "A practical parcel review has three columns: what is inside, why it is included, and what evidence you have checked. Confirm quantities, selected variants, visible condition, and whether the parcel contains anything that needs extra attention. If your decision depends on a cost estimate or a route condition, wait for the information presented in the parcel process instead of importing a number from an old forum post. Parcel decisions are most reliable when they use the information attached to the current order." ]},
    {heading:"7. Read shipping routes as current options", paragraphs:[
      "LoloBuy’s homepage advertises “100 logistics routes.” That tells buyers that route selection is part of the service, not that every route will be available for every parcel or destination. A route can have its own restrictions, price calculation, tracking pattern, coverage, and handling rules. Availability may also depend on what is inside the parcel and the destination selected in the account. Use the live parcel screen as the decision point for current options.",
      "Do not turn a route list into a delivery guarantee. International movement can be affected by carrier operations, destination handling, customs processes, address quality, and changes in route rules. A responsible comparison is therefore about fit: does the currently displayed route accept the parcel, show a cost you understand, and match the level of tracking or handling you need? Record the route name and the checkout information shown at the time you submit. That is more useful than relying on generic claims about “fastest” or “safest” shipping." ]},
    {heading:"8. The final check is a decision record", paragraphs:[
      "Before submitting an international parcel, make one final record: the items included, observed inspection notes, declared destination, selected route, and the information shown by the current checkout. Then keep the parcel reference and later tracking updates in the same place. This habit is simple, but it protects the context that is most often lost when several orders are combined.",
      "The strongest LoloBuy workflow is therefore a research workflow. Search or paste a specific product reference, make the purchase decision from the listing, inspect the warehouse feedback against your own notes, and submit only the parcel you understand. That approach does not eliminate uncertainty. It gives you a clearer basis for every decision and avoids turning an agent-shopping process into an assumption-driven one." ]}
  ]
};

export type EditorialArticle = { reviewed:string; title:string; intro:string; sections:{heading:string;paragraphs:string[]}[] };

// The English original is intentionally long-form. The localized editions preserve the same
// evidence and cautions, rather than leaving an English article behind after a language switch.
export const localizedArticles: Record<string,EditorialArticle> = {
  nl:{reviewed:"FEITELIJK ONDERZOEK · SEPTEMBER 2026",title:"LoloBuy gebruiken voor productonderzoek: een praktische route van bestelling tot pakket",intro:"Een zorgvuldige LoloBuy-bestelling is geen enkele klik maar een reeks beslissingen: bepaal het exacte item, scheid productonderzoek van magazijncontrole en kies pas daarna hoe je een internationaal pakket samenstelt. Deze onafhankelijke gids legt de publieke workflow van LoloBuy uit als een controlelijst voor kopers. Hij voorspelt geen levertijden, douane-uitkomsten, productauthenticiteit of definitieve verzendprijs.",sections:[
    {heading:"1. Begin met het proces, niet met een belofte",paragraphs:["De openbare LoloBuy-homepage toont een route met productinvoer, betaling, kwaliteitscontrole en opslag in een magazijn, gevolgd door het indienen van een pakket en internationale verzending. Elke stap beantwoordt een andere vraag: is het product de moeite waard, komt het ontvangen artikel overeen met de keuze, en horen de opgeslagen items werkelijk samen in één pakket? Houd de oorspronkelijke link, variant en maat daarom bij elkaar."]},
    {heading:"2. Leg de exacte productkeuze vast",paragraphs:["De homepage toont invoer voor een productlink of productnaam en een optie voor zoeken op afbeelding. Gebruik dat als beginpunt, maar noteer ook variant, maten, materiaalomschrijving, verkopersfoto’s en relevante listingnotities. Een algemene omschrijving is niet genoeg om later te vergelijken. Listingbeelden en tekst helpen bij de keuze, maar zijn geen onafhankelijke garantie voor voorraad, pasvorm, constructie of authenticiteit."]},
    {heading:"3. Scheid productbetaling van internationale verzending",paragraphs:["LoloBuy beschrijft de betaling van productprijs en vracht binnen China als bestelstap vóór de internationale pakketkeuze. Behandel productbetaling, binnenlands vervoer, pakketopties en internationale verzending dus als afzonderlijke controles. Bewaar productnaam, link, gekozen optie, aantal en reden van je keuze voordat je betaalt. Dat creëert geen prijs- of retourgarantie, maar voorkomt dat belangrijke context later uit het geheugen moet worden gereconstrueerd."]},
    {heading:"4. Zie magazijncontrole als bewijs, niet als certificaat",paragraphs:["De publieke homepage noemt kwaliteitscontrole, inspectiefoto’s en feedback bij aankomst in het magazijn. Vergelijk die informatie met je eigen notitie: zichtbare kleur, aantallen, labels, duidelijke gebreken en overeenstemming met de gekozen variant. Foto’s kunnen echter geen interne constructie, duurzaamheid, exacte samenstelling, authenticiteit of uiteindelijke pasvorm bewijzen. Vraag dus welke zichtbare punten de foto daadwerkelijk beantwoordt, in plaats van zekerheid in een beperkte beeldset te lezen."]},
    {heading:"5. Gebruik opslag om rustiger te beslissen",paragraphs:["De homepage vermeldt momenteel 180 dagen gratis opslag; controleer de actuele voorwaarden in je account voordat je daarop vertrouwt. De waarde is tijd: verzamel feedback, vergelijk items en bepaal of verschillende producten dezelfde zending nodig hebben. Label opgeslagen items bijvoorbeeld als seizoensgebonden, breekbaar, volumineus of nog te beoordelen. Opslag is een kans om te organiseren, geen reden om productdetails niet meer te controleren."]},
    {heading:"6. Bouw een pakket rond afwegingen",paragraphs:["Volgens de publieke flow kunnen opgeslagen producten als één pakket worden ingediend. Samenvoegen kan overzicht geven, maar meer of grotere items kunnen het verzendprofiel veranderen en regels blijven afhankelijk van de bestemming. Maak vóór indiening een kleine lijst: wat zit erin, waarom gaat het mee, en welk bewijs heb je gezien? Bevestig aantallen, varianten en zichtbare conditie en gebruik actuele pakketinformatie in plaats van oude forumposts voor kosten of routevoorwaarden."]},
    {heading:"7. Lees verzendroutes als actuele opties",paragraphs:["LoloBuy adverteert op de homepage met 100 logistieke routes. Dat betekent dat routekeuze onderdeel is van de service, niet dat elke route voor elk pakket of land beschikbaar is. Beschikbaarheid, prijs, beperkingen, tracking en afhandeling kunnen afhangen van inhoud en bestemming. Gebruik het live pakketscherm als beslismoment. Een route is geen levertijd-, douane- of veiligheidsbelofte; noteer naam en getoonde gegevens op het moment van indienen."]},
    {heading:"8. Eindig met een beslisrecord",paragraphs:["Leg vóór internationale indiening vast welke items zijn opgenomen, welke inspectienotities je zag, welke bestemming is gekozen en welke route-informatie de checkout toonde. Bewaar daarna pakketreferentie en tracking bij dezelfde notitie. De sterkste workflow is een onderzoeksworkflow: zoek een specifiek product, beslis op basis van de listing, vergelijk magazijnfeedback met je eigen criteria en dien alleen een pakket in dat je begrijpt. Dat verwijdert onzekerheid niet, maar maakt elke keuze beter navolgbaar."]}
  ]},
  de:{reviewed:"FAKTENBASIERTE RECHERCHE · SEPTEMBER 2026",title:"LoloBuy für Produktrecherche nutzen: ein praktischer Ablauf von Bestellung bis Paket",intro:"Eine sorgfältige LoloBuy-Bestellung ist kein einzelner Klick, sondern eine Reihe von Entscheidungen: den genauen Artikel bestimmen, Produktrecherche von Lagerprüfung trennen und erst dann entscheiden, wie ein internationales Paket aufgebaut wird. Dieser unabhängige Leitfaden erklärt den öffentlichen LoloBuy-Ablauf als Checkliste für Käufer. Er sagt weder Lieferzeiten, Zollergebnisse, Produktechtheit noch einen endgültigen Versandpreis voraus.",sections:[
    {heading:"1. Mit dem Ablauf beginnen, nicht mit einem Versprechen",paragraphs:["Die öffentliche LoloBuy-Startseite zeigt Produktinput, Zahlung, Qualitätsprüfung und Lagerung sowie später Paketeinreichung und internationalen Versand. Jede Stufe beantwortet eine andere Frage: Ist der Artikel sinnvoll, entspricht der Lagereingang der Auswahl und gehören die gelagerten Artikel wirklich zusammen? Bewahre Link, Variante, Größe und Notizen deshalb von Anfang an gemeinsam auf."]},
    {heading:"2. Die genaue Produktauswahl dokumentieren",paragraphs:["Die Startseite bietet ein Feld für Produktlink oder -name und eine Bildsuche. Ergänze dies durch Variante, Maße, Materialbeschreibung, Verkäuferbilder und wichtige Hinweise der Produktseite. Eine allgemeine Bezeichnung reicht für einen späteren Vergleich nicht aus. Bilder und Beschreibungen können bei der Wahl helfen, sind aber keine unabhängige Garantie für Bestand, Passform, Verarbeitung oder Echtheit."]},
    {heading:"3. Produktzahlung und internationalen Versand trennen",paragraphs:["LoloBuy beschreibt die Zahlung von Produktpreis und Fracht innerhalb Festlandchinas als Bestellstufe vor der internationalen Paketwahl. Behandle Produktzahlung, Inlandstransport, Paketoptionen und internationale Sendung daher als getrennte Kontrollpunkte. Notiere Produktname, Link, Variante, Menge und Grund der Wahl vor der Zahlung. Das schafft keine Preis- oder Rückgabegarantie, bewahrt aber den später nötigen Vergleichskontext."]},
    {heading:"4. Lagerprüfung als Beleg, nicht als Zertifikat nutzen",paragraphs:["Die öffentliche Seite nennt Qualitätsprüfung, Prüfbilder und Rückmeldungen beim Wareneingang. Vergleiche sichtbare Farbe, Stückzahl, Labels, erkennbare Fehler und Variante mit deiner Bestellung. Fotos beweisen jedoch weder innere Verarbeitung, Haltbarkeit, genaue Zusammensetzung, Echtheit noch spätere Passform. Frage deshalb, welche deiner konkreten Prüfungen die Bilder beantworten, statt aus einer begrenzten Bildfolge Sicherheit abzuleiten."]},
    {heading:"5. Lagerung für eine ruhigere Entscheidung einsetzen",paragraphs:["Die Homepage nennt derzeit 180 Tage kostenlose Lagerung; bestätige aktuelle Bedingungen im Konto, bevor du dich darauf verlässt. Ihr praktischer Wert ist Zeit: Rückmeldungen sammeln, Artikel vergleichen und entscheiden, ob sie zusammen versendet werden sollen. Kennzeichne gelagerte Waren etwa als saisonal, zerbrechlich, sperrig oder noch offen. Lagerung hilft beim Ordnen, ersetzt aber keine sorgfältige Prüfung."]},
    {heading:"6. Ein Paket anhand von Abwägungen zusammenstellen",paragraphs:["Laut öffentlichem Ablauf können gelagerte Produkte als ein Paket eingereicht werden. Bündelung kann übersichtlicher sein, doch mehr oder sperrige Artikel können das Versandprofil verändern; Zielregeln bleiben bestehen. Erstelle vor dem Absenden eine Liste: Inhalt, Grund der Aufnahme und geprüfte Belege. Bestätige Menge, Variante und sichtbaren Zustand und nutze für Kosten oder Routenbedingungen die aktuellen Paketdaten statt alter Forenangaben."]},
    {heading:"7. Versandrouten als aktuelle Optionen lesen",paragraphs:["LoloBuy bewirbt auf der Startseite 100 Logistikrouten. Das macht Routenwahl zu einem Teil des Dienstes, bedeutet aber nicht, dass jede Route für jedes Paket oder Ziel verfügbar ist. Preis, Einschränkungen, Tracking und Bearbeitung können von Inhalt und Ziel abhängen. Entscheide anhand des aktuellen Paketbildschirms. Eine Route ist keine Zusage für Lieferdatum, Zoll oder Sicherheit; speichere ihren Namen und die angezeigten Angaben beim Einreichen."]},
    {heading:"8. Mit einem Entscheidungsprotokoll abschließen",paragraphs:["Halte vor der internationalen Einreichung enthaltene Artikel, sichtbare Prüfhinterweise, Ziel und die bei der Kasse angezeigten Routendaten fest. Bewahre anschließend Paketreferenz und Tracking zusammen auf. Der belastbarste Ablauf ist Recherche: ein konkretes Produkt suchen, anhand der Produktseite entscheiden, Lagerfeedback mit eigenen Kriterien vergleichen und nur ein verstandenes Paket absenden. Das beseitigt Unsicherheit nicht, erhält aber die Grundlage jeder Entscheidung."]}
  ]},
  fr:{reviewed:"RECHERCHE FACTUELLE · SEPTEMBRE 2026",title:"Utiliser LoloBuy pour la recherche produit : un parcours pratique de la commande au colis",intro:"Une commande LoloBuy réfléchie n’est pas un clic unique mais une suite de décisions : identifier l’article exact, séparer la recherche produit du contrôle d’entrepôt, puis seulement décider comment construire un colis international. Ce guide indépendant explique le parcours public de LoloBuy sous forme de liste de vérification pour l’acheteur. Il ne prédit ni délai de livraison, ni résultat douanier, ni authenticité, ni prix final d’expédition.",sections:[
    {heading:"1. Commencer par le parcours, pas par une promesse",paragraphs:["La page publique de LoloBuy présente une séquence : saisie de produit, paiement, contrôle qualité et stockage, puis soumission du colis et expédition internationale. Chaque phase répond à une question différente : le produit vaut-il l’essai, l’article reçu correspond-il au choix, et les articles stockés doivent-ils voyager ensemble ? Conservez dès le départ lien, variante, taille et notes dans le même dossier."]},
    {heading:"2. Consigner le choix produit exact",paragraphs:["La page d’accueil affiche un champ pour un lien ou un nom de produit et une recherche par image. Ajoutez variante, mesures, description de matière, visuels vendeur et remarques de la fiche. Un libellé vague ne permet pas une comparaison ultérieure. Images et descriptions aident à choisir, mais ne garantissent pas indépendamment stock, coupe, fabrication ou authenticité."]},
    {heading:"3. Distinguer paiement produit et expédition internationale",paragraphs:["LoloBuy décrit le paiement du prix produit et du fret en Chine continentale avant le choix du colis international. Traitez donc paiement, mouvement intérieur, options de colis et expédition comme des contrôles distincts. Notez nom, lien, option, quantité et raison du choix avant paiement. Cela ne crée ni prix bloqué ni droit de retour, mais évite de reconstruire plus tard les éléments importants de mémoire."]},
    {heading:"4. Lire le contrôle d’entrepôt comme une preuve, non une certification",paragraphs:["La page publique mentionne contrôle qualité, photos d’inspection et retour à l’arrivée. Comparez couleur visible, quantité, étiquettes, défauts évidents et variante avec vos notes. Des photos ne prouvent toutefois ni construction interne, ni durabilité, ni composition exacte, ni authenticité, ni ajustement final. Demandez-vous quels contrôles concrets les images répondent réellement, plutôt que d’y voir une certitude qu’elles ne peuvent fournir."]},
    {heading:"5. Employer le stockage pour décider avec calme",paragraphs:["La page indique actuellement 180 jours de stockage gratuit ; vérifiez les conditions du compte avant de vous y fier. L’intérêt pratique est le temps : recueillir des retours, comparer des articles et décider s’ils doivent figurer dans le même colis. Étiquetez-les, par exemple, saisonniers, fragiles, volumineux ou en attente. Le stockage aide à organiser ; il ne remplace pas l’examen des détails de commande."]},
    {heading:"6. Construire le colis autour de compromis",paragraphs:["Le parcours public dit que les produits stockés peuvent être soumis en un seul colis. Le regroupement peut simplifier le suivi, mais davantage d’articles ou un article encombrant peuvent modifier le profil d’envoi et les règles de destination restent applicables. Avant de soumettre, listez le contenu, la raison de l’inclusion et les preuves vues. Utilisez les données actuelles du colis, non un ancien message de forum, pour coûts ou conditions de route."]},
    {heading:"7. Lire les itinéraires comme des options actuelles",paragraphs:["LoloBuy annonce 100 itinéraires logistiques sur sa page d’accueil. Cela signale que le choix de route fait partie du service, non que chaque route convient à chaque colis ou pays. Disponibilité, prix, restrictions, suivi et traitement peuvent dépendre du contenu et de la destination. Décidez à partir de l’écran du colis en direct. Une route ne garantit ni délai, ni douane, ni résultat ; conservez son nom et les informations affichées."]},
    {heading:"8. Terminer par un relevé de décision",paragraphs:["Avant la soumission internationale, notez articles inclus, observations d’inspection, destination et informations de route affichées au paiement. Gardez ensuite référence de colis et suivi avec cette note. Le meilleur parcours reste un parcours de recherche : chercher une référence précise, décider depuis la fiche, comparer le retour d’entrepôt à ses propres critères et n’envoyer qu’un colis compris. L’incertitude demeure, mais chaque décision conserve sa base factuelle."]}
  ]},
  es:{reviewed:"INVESTIGACIÓN FACTUAL · SEPTIEMBRE DE 2026",title:"Cómo usar LoloBuy para investigar productos: una ruta práctica del pedido al paquete",intro:"Un pedido cuidadoso en LoloBuy no es un solo clic, sino una serie de decisiones: identifica el artículo exacto, separa la investigación del producto de la inspección del almacén y solo después decide cómo formar un paquete internacional. Esta guía independiente explica el flujo público de LoloBuy como una lista de control para compradores. No predice fechas de entrega, resultados de aduana, autenticidad del producto ni un precio final de envío.",sections:[
    {heading:"1. Empieza por el flujo, no por una promesa",paragraphs:["La página pública de LoloBuy muestra entrada de producto, pago, control de calidad y almacenamiento, seguidos por el envío del paquete y transporte internacional. Cada fase responde a una pregunta distinta: si el artículo merece intentarse, si lo recibido coincide con la elección y si los productos almacenados deben viajar juntos. Conserva desde el principio enlace, variante, talla y notas en un mismo registro."]},
    {heading:"2. Registra la elección exacta del producto",paragraphs:["La página de inicio muestra un campo para enlace o nombre de producto y una opción de búsqueda por imagen. Añade variante, medidas, descripción de material, imágenes del vendedor y notas relevantes. Una etiqueta general no sirve para comparar después. Las fotos y el texto ayudan a escoger, pero no garantizan de forma independiente existencias, ajuste, fabricación o autenticidad."]},
    {heading:"3. Separa el pago del producto del envío internacional",paragraphs:["LoloBuy describe el pago del producto y el flete dentro de China continental antes de elegir el paquete internacional. Trata pago, movimiento nacional, opciones de paquete y envío internacional como controles distintos. Antes de pagar guarda nombre, enlace, opción, cantidad y motivo de elección. No crea una garantía de precio o devolución, pero conserva el contexto que necesitarás cuando lleguen las imágenes del almacén."]},
    {heading:"4. Usa la inspección como evidencia, no como certificado",paragraphs:["La página pública menciona control de calidad, fotos de inspección y comentarios al llegar al almacén. Compara color visible, cantidad, etiquetas, defectos evidentes y variante con tu nota. Una foto no demuestra construcción interna, durabilidad, composición exacta, autenticidad ni ajuste final. La pregunta útil es qué comprobaciones concretas responde la imagen, no qué certeza adicional parece prometer."]},
    {heading:"5. Usa el almacenamiento para decidir con calma",paragraphs:["La página indica actualmente 180 días de almacenamiento gratuito; confirma la condición vigente en tu cuenta antes de depender de ella. Su valor práctico es disponer de tiempo para reunir comentarios, comparar artículos y decidir si deben ir en el mismo paquete. Marca los productos como estacionales, frágiles, voluminosos o pendientes. El almacenamiento ayuda a ordenar la decisión, pero no sustituye revisar los detalles importantes."]},
    {heading:"6. Construye el paquete con sus compensaciones",paragraphs:["El flujo público dice que se pueden seleccionar artículos almacenados y enviarlos como un solo paquete. Consolidar puede simplificar la gestión, pero más artículos o un objeto voluminoso pueden cambiar el perfil de envío y las reglas de destino siguen vigentes. Antes de enviar, lista qué va dentro, por qué se incluye y qué evidencia revisaste. Para coste o rutas usa la información actual del paquete, no cifras antiguas de un foro."]},
    {heading:"7. Lee las rutas como opciones actuales",paragraphs:["LoloBuy anuncia 100 rutas logísticas en su página. Eso indica que la ruta forma parte del servicio, no que todas estén disponibles para cada paquete o destino. Precio, restricciones, seguimiento y tratamiento pueden depender del contenido y país. Decide en la pantalla en vivo del paquete. Una ruta no es garantía de fecha, aduana o resultado; guarda el nombre y los datos mostrados al presentar el paquete."]},
    {heading:"8. Termina con un registro de decisión",paragraphs:["Antes del envío internacional, anota los artículos incluidos, observaciones de inspección, destino y datos de ruta vistos al pagar. Guarda después referencia y seguimiento junto a esa nota. El flujo más sólido es un flujo de investigación: busca un producto concreto, decide desde la ficha, compara la información del almacén con tus criterios y envía solo un paquete que comprendes. La incertidumbre no desaparece, pero cada decisión conserva su base."]}
  ]},
  it:{reviewed:"RICERCA FATTUALE · SETTEMBRE 2026",title:"Usare LoloBuy per la ricerca prodotto: un percorso pratico dall’ordine al pacco",intro:"Un ordine LoloBuy accurato non è un solo clic ma una serie di decisioni: identificare l’articolo esatto, separare la ricerca prodotto dal controllo del magazzino e decidere solo dopo come comporre un pacco internazionale. Questa guida indipendente spiega il flusso pubblico di LoloBuy come lista di controllo per l’acquirente. Non prevede date di consegna, esiti doganali, autenticità del prodotto o un prezzo finale di spedizione.",sections:[
    {heading:"1. Parti dal flusso, non da una promessa",paragraphs:["La homepage pubblica di LoloBuy mostra inserimento prodotto, pagamento, controllo qualità e deposito, poi invio del pacco e spedizione internazionale. Ogni fase risponde a una domanda diversa: vale la pena tentare l’acquisto, l’articolo arrivato corrisponde alla scelta, e gli articoli depositati devono davvero viaggiare insieme? Conserva link, variante, taglia e note nello stesso record fin dall’inizio."]},
    {heading:"2. Annota la scelta di prodotto esatta",paragraphs:["La homepage offre un campo per link o nome prodotto e la ricerca per immagine. Aggiungi variante, misure, descrizione del materiale, immagini del venditore e note della scheda. Un nome generico non basta per il confronto successivo. Foto e testo possono aiutare a scegliere, ma non costituiscono una garanzia indipendente di disponibilità, vestibilità, costruzione o autenticità."]},
    {heading:"3. Separa pagamento prodotto e spedizione internazionale",paragraphs:["LoloBuy descrive il pagamento di prodotto e trasporto nella Cina continentale prima della scelta del pacco internazionale. Tratta quindi pagamento, movimento interno, opzioni del pacco e spedizione come controlli distinti. Prima di pagare annota nome, link, opzione, quantità e motivo della scelta. Non crea un prezzo bloccato o un diritto di reso, ma preserva il contesto utile quando arrivano le informazioni dal magazzino."]},
    {heading:"4. Leggi il controllo di magazzino come evidenza, non certificazione",paragraphs:["La pagina pubblica cita controllo qualità, foto d’ispezione e feedback all’arrivo. Confronta colore visibile, quantità, etichette, difetti evidenti e variante con le tue note. Le foto non provano costruzione interna, durata, composizione esatta, autenticità o vestibilità finale. La domanda sensata è quali verifiche specifiche l’immagine risponde davvero, non quale certezza sembra aggiungere."]},
    {heading:"5. Usa il deposito per decidere con calma",paragraphs:["La homepage indica attualmente 180 giorni di deposito gratuito; conferma le condizioni nel tuo account prima di farvi affidamento. Il valore pratico è il tempo: raccogliere feedback, confrontare articoli e decidere se appartengono allo stesso pacco. Etichetta gli articoli come stagionali, fragili, ingombranti o da decidere. Il deposito aiuta a organizzare, ma non sostituisce il controllo dei dettagli rilevanti."]},
    {heading:"6. Crea il pacco intorno ai compromessi",paragraphs:["Il flusso pubblico afferma che prodotti depositati possono essere inviati in un solo pacco. Riunirli può semplificare la gestione, ma più articoli o uno ingombrante possono cambiarne il profilo e le regole della destinazione restano valide. Prima di inviare, elenca contenuto, motivo dell’inclusione e prove viste. Per costi o condizioni usa i dati attuali del pacco, non un vecchio messaggio di forum."]},
    {heading:"7. Considera le rotte come opzioni aggiornate",paragraphs:["LoloBuy pubblicizza 100 rotte logistiche in homepage. Significa che la scelta della rotta è parte del servizio, non che ogni rotta è disponibile per ogni pacco o paese. Prezzo, limiti, tracking e gestione possono dipendere da contenuto e destinazione. Decidi sulla schermata attuale del pacco. Una rotta non garantisce data, dogana o esito; salva nome e dati mostrati al momento della presentazione."]},
    {heading:"8. Chiudi con un record decisionale",paragraphs:["Prima dell’invio internazionale annota articoli inclusi, osservazioni d’ispezione, destinazione e dati della rotta mostrati al checkout. Conserva poi riferimento e tracking insieme alla nota. Il percorso più solido è di ricerca: cerca un prodotto specifico, decidi dalla scheda, confronta il feedback del magazzino con i tuoi criteri e invia solo un pacco che comprendi. L’incertezza rimane, ma ogni decisione mantiene la propria base."]}
  ]},
  pl:{reviewed:"BADANIE OPARTE NA FAKTACH · WRZESIEŃ 2026",title:"Jak używać LoloBuy do badania produktów: praktyczna droga od zamówienia do paczki",intro:"Starannie złożone zamówienie LoloBuy nie jest jednym kliknięciem, lecz serią decyzji: rozpoznaj dokładny produkt, oddziel badanie oferty od kontroli magazynowej i dopiero potem zdecyduj, jak zbudować paczkę międzynarodową. Ten niezależny przewodnik wyjaśnia publiczny proces LoloBuy jako listę kontrolną kupującego. Nie przewiduje terminu dostawy, wyniku odprawy, autentyczności produktu ani końcowej ceny wysyłki.",sections:[
    {heading:"1. Zacznij od procesu, nie od obietnicy",paragraphs:["Publiczna strona LoloBuy pokazuje wprowadzenie produktu, płatność, kontrolę jakości i magazynowanie, a następnie zgłoszenie paczki i transport międzynarodowy. Każdy etap odpowiada na inne pytanie: czy produkt jest wart zakupu, czy odebrany artykuł odpowiada wyborowi i czy przechowywane rzeczy powinny podróżować razem. Od początku trzymaj link, wariant, rozmiar i notatki w jednym miejscu."]},
    {heading:"2. Zapisz dokładny wybór produktu",paragraphs:["Strona główna ma pole na link lub nazwę produktu oraz wyszukiwanie obrazem. Dopisz wariant, wymiary, opis materiału, zdjęcia sprzedawcy i ważne notatki z oferty. Ogólna nazwa nie wystarczy do późniejszego porównania. Zdjęcia i opis pomagają wybrać, ale nie są niezależną gwarancją zapasu, dopasowania, wykonania ani autentyczności."]},
    {heading:"3. Oddziel płatność za produkt od wysyłki międzynarodowej",paragraphs:["LoloBuy opisuje płatność za produkt i fracht w Chinach kontynentalnych przed wyborem paczki międzynarodowej. Traktuj płatność, transport krajowy, opcje paczki i wysyłkę jako osobne kontrole. Przed płatnością zapisz nazwę, link, opcję, liczbę i powód wyboru. Nie tworzy to gwarancji ceny ani zwrotu, ale zachowuje kontekst potrzebny po otrzymaniu informacji z magazynu."]},
    {heading:"4. Traktuj kontrolę magazynową jako dowód, nie certyfikat",paragraphs:["Publiczna strona wymienia kontrolę jakości, zdjęcia inspekcyjne i informacje zwrotne po dotarciu towaru. Porównaj widoczny kolor, liczbę, etykiety, oczywiste wady i wariant ze swoją notatką. Zdjęcia nie dowodzą jednak wewnętrznej konstrukcji, trwałości, dokładnego składu, autentyczności ani późniejszego dopasowania. Pytaj, które konkretne kontrole obraz naprawdę rozstrzyga."]},
    {heading:"5. Wykorzystaj magazynowanie do spokojniejszej decyzji",paragraphs:["Strona podaje obecnie 180 dni darmowego magazynowania; przed poleganiem na tym potwierdź warunki w koncie. Wartością jest czas na zebranie informacji, porównanie produktów i decyzję, czy mają znaleźć się w jednej paczce. Oznacz je jako sezonowe, kruche, duże lub oczekujące na decyzję. Magazynowanie pomaga uporządkować sprawę, lecz nie zastępuje weryfikacji ważnych szczegółów."]},
    {heading:"6. Buduj paczkę wokół kompromisów",paragraphs:["Według publicznego procesu produkty w magazynie można zgłosić jako jedną paczkę. Łączenie ułatwia zarządzanie, ale więcej rzeczy lub przedmiot duży może zmienić profil przesyłki, a zasady celu nadal obowiązują. Przed zgłoszeniem wypisz zawartość, powód dołączenia i sprawdzone dowody. Dla kosztów i warunków tras użyj bieżącej informacji o paczce, a nie starego wpisu forum."]},
    {heading:"7. Czytaj trasy jako aktualne opcje",paragraphs:["LoloBuy reklamuje na stronie 100 tras logistycznych. Oznacza to, że wybór trasy jest częścią usługi, ale nie że każda trasa jest dostępna dla każdej paczki i kraju. Cena, ograniczenia, śledzenie i obsługa mogą zależeć od zawartości i celu. Decyduj na aktualnym ekranie paczki. Trasa nie jest gwarancją terminu, odprawy ani wyniku; zapisz jej nazwę i wyświetlone dane przy zgłoszeniu."]},
    {heading:"8. Zakończ zapisem decyzji",paragraphs:["Przed wysyłką międzynarodową zanotuj produkty w paczce, obserwacje z kontroli, kraj docelowy oraz dane trasy z kasy. Później przechowuj numer paczki i tracking obok tej notatki. Najlepszy proces jest procesem badawczym: znajdź konkretny produkt, podejmij decyzję na podstawie oferty, porównaj informacje z magazynu z własnymi kryteriami i wyślij tylko paczkę, którą rozumiesz. Niepewność pozostaje, lecz podstawa decyzji jest zachowana."]}
  ]},
  pt:{reviewed:"PESQUISA FACTUAL · SETEMBRO DE 2026",title:"Como usar a LoloBuy para pesquisar produtos: um percurso prático da encomenda ao pacote",intro:"Uma encomenda LoloBuy cuidadosa não é um único clique, mas uma série de decisões: identificar o artigo exato, separar a pesquisa do produto da inspeção no armazém e só depois decidir como compor um pacote internacional. Este guia independente explica o fluxo público da LoloBuy como uma lista de verificação para compradores. Não prevê datas de entrega, resultados aduaneiros, autenticidade do produto ou preço final de expedição.",sections:[
    {heading:"1. Comece pelo processo, não por uma promessa",paragraphs:["A página pública da LoloBuy mostra introdução de produto, pagamento, controlo de qualidade e armazenamento, seguidos por submissão de pacote e envio internacional. Cada etapa responde a uma pergunta: vale a pena tentar comprar, o artigo recebido corresponde à escolha e os artigos armazenados devem viajar juntos? Guarde desde o início link, variante, tamanho e notas no mesmo registo."]},
    {heading:"2. Registe a escolha exata do produto",paragraphs:["A página inicial mostra um campo para link ou nome de produto e pesquisa por imagem. Acrescente variante, medidas, descrição do material, imagens do vendedor e notas relevantes da listagem. Um nome genérico não chega para comparar mais tarde. Fotografias e descrição ajudam a escolher, mas não garantem de forma independente stock, ajuste, construção ou autenticidade."]},
    {heading:"3. Separe pagamento do produto e envio internacional",paragraphs:["A LoloBuy descreve o pagamento do produto e do frete na China continental antes da escolha do pacote internacional. Trate pagamento, movimento interno, opções de pacote e envio como verificações separadas. Antes de pagar registe nome, link, opção, quantidade e motivo da escolha. Isto não cria garantia de preço ou devolução, mas preserva o contexto necessário quando chegar informação do armazém."]},
    {heading:"4. Veja o controlo do armazém como evidência, não certificação",paragraphs:["A página pública refere controlo de qualidade, fotografias de inspeção e feedback à chegada. Compare cor visível, quantidade, etiquetas, defeitos óbvios e variante com a sua nota. Fotografias não provam construção interna, durabilidade, composição exata, autenticidade ou ajuste final. A pergunta útil é quais verificações concretas a imagem responde, não que certeza parece acrescentar."]},
    {heading:"5. Use o armazenamento para decidir com calma",paragraphs:["A página indica atualmente 180 dias de armazenamento gratuito; confirme as condições atuais na conta antes de depender delas. O valor prático é ter tempo para reunir feedback, comparar artigos e decidir se pertencem ao mesmo pacote. Marque artigos como sazonais, frágeis, volumosos ou pendentes. O armazenamento ajuda a organizar, mas não substitui a revisão de detalhes importantes."]},
    {heading:"6. Construa o pacote com os seus compromissos",paragraphs:["O fluxo público diz que produtos armazenados podem ser submetidos como um único pacote. Consolidar pode simplificar a gestão, mas mais artigos ou um item volumoso podem alterar o perfil do envio e as regras do destino mantêm-se. Antes de submeter, liste o conteúdo, motivo da inclusão e evidência verificada. Para custo ou condições de rota, use a informação atual do pacote e não um valor antigo de fórum."]},
    {heading:"7. Leia rotas de envio como opções atuais",paragraphs:["A LoloBuy anuncia 100 rotas logísticas na página inicial. Isto mostra que a escolha da rota faz parte do serviço, não que cada rota esteja disponível para todos os pacotes ou destinos. Preço, limitações, tracking e tratamento podem depender do conteúdo e destino. Decida no ecrã atual do pacote. Uma rota não garante data, alfândega ou resultado; guarde o nome e os dados apresentados na submissão."]},
    {heading:"8. Termine com um registo da decisão",paragraphs:["Antes da submissão internacional, anote artigos incluídos, observações da inspeção, destino e informação de rota apresentada no checkout. Guarde depois referência e tracking junto da mesma nota. O percurso mais sólido é de pesquisa: procure um produto específico, decida pela listagem, compare o feedback do armazém com os seus critérios e envie apenas um pacote que compreende. A incerteza não desaparece, mas a base de cada decisão permanece."]}
  ]},
  sv:{reviewed:"FAKTABASERAD RESEARCH · SEPTEMBER 2026",title:"Använd LoloBuy för produktresearch: ett praktiskt flöde från order till paket",intro:"En noggrann LoloBuy-order är inte ett enda klick utan en serie beslut: identifiera exakt vara, skilj produktresearch från lagerkontroll och avgör först därefter hur ett internationellt paket ska byggas. Denna oberoende guide förklarar LoloBuys offentliga flöde som en köparchecklista. Den förutsäger inte leveransdatum, tullutfall, produktäkthet eller slutligt fraktpris.",sections:[
    {heading:"1. Börja med flödet, inte ett löfte",paragraphs:["LoloBuys offentliga startsida visar produktinmatning, betalning, kvalitetskontroll och lagring, följt av paketinsändning och internationell frakt. Varje steg svarar på en annan fråga: är produkten värd försöket, motsvarar den mottagna varan valet och bör lagrade varor verkligen resa ihop? Spara länk, variant, storlek och anteckningar på samma ställe från början."]},
    {heading:"2. Dokumentera det exakta produktvalet",paragraphs:["Startsidan har fält för produktlänk eller produktnamn och bildsökning. Lägg till variant, mått, materialbeskrivning, säljarbilder och viktiga produktnotiser. Ett allmänt namn räcker inte för senare jämförelse. Bilder och text hjälper vid valet men är ingen oberoende garanti för lagerstatus, passform, tillverkning eller äkthet."]},
    {heading:"3. Skilj produktbetalning från internationell frakt",paragraphs:["LoloBuy beskriver betalning för produkt och frakt inom Fastlandskina före valet av internationellt paket. Behandla därför betalning, inrikes rörelse, paketalternativ och internationell frakt som olika kontrollpunkter. Spara namn, länk, val, antal och skäl före betalning. Det ger ingen pris- eller returgaranti, men bevarar det sammanhang som behövs när lagerinformation senare kommer."]},
    {heading:"4. Se lagerkontroll som bevis, inte certifikat",paragraphs:["Den offentliga sidan nämner kvalitetskontroll, inspektionsbilder och återkoppling när varor når lagret. Jämför synlig färg, antal, etiketter, tydliga fel och variant med dina anteckningar. Bilder bevisar dock inte inre konstruktion, hållbarhet, exakt sammansättning, äkthet eller slutlig passform. Fråga vilka av dina konkreta kontroller bilden faktiskt besvarar, inte vilken säkerhet den tycks lägga till."]},
    {heading:"5. Använd lagring för ett lugnare beslut",paragraphs:["Startsidan anger för närvarande 180 dagars gratis lagring; kontrollera aktuella villkor i kontot innan du förlitar dig på dem. Det praktiska värdet är tid att samla återkoppling, jämföra varor och avgöra om de ska ligga i samma paket. Märk saker som säsongsvaror, ömtåliga, skrymmande eller väntande. Lagring hjälper till att organisera men ersätter inte granskning av viktiga detaljer."]},
    {heading:"6. Bygg paketet kring avvägningar",paragraphs:["Det offentliga flödet säger att lagrade produkter kan skickas in som ett paket. Sammanläggning kan förenkla hanteringen, men fler eller skrymmande varor kan ändra fraktprofilen och destinationsreglerna gäller fortfarande. Före insändning: lista innehåll, skälet till att varje vara ingår och kontrollerade bevis. Använd aktuell paketinformation för kostnad och ruttvillkor, inte gamla foruminlägg."]},
    {heading:"7. Läs fraktrutter som aktuella alternativ",paragraphs:["LoloBuy annonserar 100 logistikrutter på startsidan. Det innebär att ruttval är del av tjänsten, inte att varje rutt finns för varje paket eller land. Pris, begränsningar, spårning och hantering kan bero på innehåll och destination. Avgör från den aktuella paketvyn. En rutt är ingen garanti för datum, tull eller utfall; spara namnet och uppgifterna som visas vid insändning."]},
    {heading:"8. Avsluta med ett beslutsunderlag",paragraphs:["Före internationell insändning: anteckna innehåll, synliga inspektionsnoteringar, destination och ruttinformation som visas i kassan. Spara sedan paketreferens och spårning tillsammans med samma anteckning. Det starkaste flödet är ett researchflöde: sök en specifik produkt, fatta beslut från listningen, jämför lageråterkoppling med egna kriterier och skicka bara ett paket du förstår. Osäkerheten finns kvar, men grunden för beslutet bevaras."]}
  ]}
};

// Kept as a separate second paragraph for each section so every translated edition
// follows the English article's full eight-section, sixteen-paragraph structure.
export const localizedArticleContinuations: Record<string,string[]> = {
  nl:[
    "Het voordeel van deze vaste volgorde is traceerbaarheid. Bewaar de verkopertitel, gekozen kleur of maat en je eigen vergelijkingspunten voordat een bestelling verdergaat. Wanneer later magazijnfoto’s verschijnen, kun je ze tegen een concrete referentie houden. Dit is een onderzoeksmethode en geen belofte dat iedere listing of bestelling goed afloopt.",
    "Maak ook onderscheid tussen wat je kunt zien en wat je niet kunt weten. Vergelijk een maattabel bij voorkeur met een eigen kledingstuk en schrijf vragen op die de magazijnbeelden later moeten beantwoorden. Een zorgvuldige notitie helpt je een detail terug te vinden zonder achteraf op herinnering te vertrouwen.",
    "Een voorzichtige begroting behandelt die controles afzonderlijk. Lees de iteminformatie opnieuw en bewaar de gekozen variatie en hoeveelheid. Als een detail je aankoopbeslissing beïnvloedt, leg het vóór de betaalstap vast. Dat maakt een later verschil zichtbaar, maar creëert geen recht op terugbetaling of vaste prijs.",
    "Let ook op de grenzen van een foto: licht en hoek kunnen kleur veranderen en een buitenaanzicht zegt weinig over slijtage na gebruik. De nuchtere vraag is of de beelden voldoende zijn voor jouw beslissing om een item te houden, te wijzigen of uit een pakket te halen. Vul ontbrekende informatie niet met aannames aan.",
    "Gebruik die periode bewust. Een eenvoudige indeling laat zien of producten een verschillende behandeling nodig hebben of juist logisch samen kunnen reizen. Controleer voorwaarden, prijzen en beschikbare keuzes altijd opnieuw op het actuele account- of pakketscherm; historische informatie is geen live bevestiging.",
    "Een goede pakketcontrole bevat daarom drie kolommen: inhoud, reden van opname en gecontroleerd bewijs. Bevestig aantallen, varianten en zichtbare conditie. Als je beslissing afhangt van een prijsraming of routebeperking, wacht dan op de informatie die bij het huidige pakket wordt getoond.",
    "Internationale beweging kan worden beïnvloed door vervoerder, adres, bestemming en douaneprocessen. Vergelijk dus niet op algemene claims als ‘snelste’ of ‘veiligste’, maar op wat nu wordt getoond: accepteert de route het pakket, begrijp je de kosten en past de tracking bij je behoefte? Bewaar de gekozen routegegevens.",
    "Zo blijft de keten helder: specifieke productreferentie, keuze uit de listing, vergelijking met magazijnfeedback en een bewust samengesteld pakket. Die werkwijze neemt onzekerheid niet weg en doet geen uitspraak over levertijd, douane, authenticiteit of uiteindelijke verzendprijs; zij maakt je beslissingen wel beter controleerbaar."
  ],
  de:[
    "Der Nutzen dieser festen Reihenfolge ist Nachvollziehbarkeit. Bewahre Verkäufertitel, gewählte Farbe oder Größe und eigene Vergleichspunkte auf, bevor die Bestellung weiterläuft. Wenn später Lagerbilder eintreffen, kannst du sie mit einer konkreten Referenz abgleichen. Das ist eine Recherchepraxis, keine Zusage für jede Produktseite oder Bestellung.",
    "Trenne außerdem Beobachtbares von Unbekanntem. Vergleiche eine Größentabelle möglichst mit einem eigenen Kleidungsstück und notiere Fragen, die die Lagerbilder später beantworten sollen. Eine sorgfältige Notiz hilft, wichtige Angaben wiederzufinden, statt sie nachträglich aus der Erinnerung zu rekonstruieren.",
    "Eine vorsichtige Budgetplanung behandelt diese Kontrollpunkte getrennt. Lies die Artikelangaben erneut und speichere Variation und Menge. Wenn ein Detail die Kaufentscheidung verändert, halte es vor dem Zahlungsabschnitt fest. Das macht spätere Unterschiede sichtbar, schafft aber weder Preisbindung noch Rückgaberecht.",
    "Beachte auch die Grenzen eines Fotos: Licht und Winkel verändern Farben, und eine Außenansicht sagt wenig über Nutzung oder Haltbarkeit aus. Die sachliche Frage lautet, ob die Bilder für deine Entscheidung reichen, einen Artikel zu behalten, zu ändern oder aus dem Paket zu nehmen. Ersetze fehlende Informationen nicht durch Annahmen.",
    "Nutze diese Zeit bewusst. Eine einfache Kennzeichnung zeigt, ob Waren unterschiedliche Behandlung brauchen oder sinnvoll zusammenpassen. Prüfe Bedingungen, Preise und verfügbare Optionen stets erneut im aktuellen Konto- oder Paketbildschirm; alte Angaben sind keine Live-Bestätigung.",
    "Eine gute Paketprüfung hat daher drei Spalten: Inhalt, Grund der Aufnahme und geprüfte Belege. Bestätige Menge, Variation und sichtbaren Zustand. Wenn eine Entscheidung von Kostenschätzung oder Routenbeschränkung abhängt, warte auf die Angaben, die für das aktuelle Paket angezeigt werden.",
    "Internationale Bewegung kann durch Carrier, Adresse, Ziel und Zollverfahren beeinflusst werden. Vergleiche daher nicht nach allgemeinen Aussagen wie ‘schnellste’ oder ‘sicherste’, sondern nach dem, was jetzt gezeigt wird: akzeptiert die Route das Paket, sind die Kosten verständlich und passt das Tracking? Bewahre die Routendaten auf.",
    "So bleibt die Kette klar: konkrete Produktreferenz, Entscheidung aus der Produktseite, Vergleich mit Lagerfeedback und ein bewusst zusammengestelltes Paket. Das beseitigt keine Unsicherheit und verspricht weder Lieferzeit, Zollresultat, Echtheit noch Endpreis; es macht die eigene Entscheidung jedoch nachvollziehbarer."
  ],
  fr:[
    "L’avantage de cet ordre est la traçabilité. Conservez le titre vendeur, la couleur ou taille choisie et vos points de comparaison avant que la commande avance. Lorsque les images d’entrepôt arrivent, vous disposez d’une référence précise. C’est une méthode de recherche, non une promesse que chaque fiche ou achat aboutira.",
    "Distinguez aussi ce qui est observable de ce qui ne l’est pas. Comparez une grille de tailles avec un vêtement que vous possédez et notez les questions auxquelles les photos devront répondre. Une note soignée permet de retrouver un détail important sans le reconstituer plus tard de mémoire.",
    "Un budget prudent traite ces contrôles séparément. Relisez la fiche et conservez variation et quantité sélectionnées. Si un détail peut changer votre décision, notez-le avant le paiement. Cela rend une différence ultérieure visible, mais ne crée ni prix garanti ni droit de retour.",
    "Gardez aussi les limites de la photo en tête : éclairage et angle peuvent modifier la couleur, et une vue extérieure n’établit pas l’usure future. La question utile est de savoir si les images suffisent pour garder, modifier ou retirer un article du colis. Ne remplacez pas les informations absentes par des suppositions.",
    "Utilisez ce temps délibérément. Un classement simple révèle quels produits demandent un traitement différent ou peuvent voyager ensemble. Vérifiez toujours à nouveau conditions, prix et options sur l’écran actuel du compte ou du colis ; une information ancienne n’est pas une confirmation en direct.",
    "Un bon contrôle de colis comprend donc trois colonnes : contenu, raison de l’inclusion et preuve vérifiée. Confirmez quantités, variantes et état visible. Si votre décision dépend d’une estimation de coût ou d’une règle de route, attendez les informations affichées pour le colis actuel.",
    "Le mouvement international peut dépendre du transporteur, de l’adresse, de la destination et des procédures douanières. Ne comparez pas sur des promesses générales de rapidité ou de sécurité : regardez plutôt si la route accepte le colis, affiche un coût compréhensible et offre le suivi nécessaire. Conservez ces données.",
    "La chaîne reste ainsi claire : référence précise, choix depuis la fiche, comparaison avec le retour d’entrepôt et colis compris avant soumission. Cette méthode ne supprime pas l’incertitude et ne promet ni délai, ni douane, ni authenticité, ni prix final ; elle conserve la base de chaque décision."
  ],
  es:[
    "La ventaja de este orden es la trazabilidad. Guarda el título del vendedor, color o talla elegidos y tus puntos de comparación antes de que el pedido avance. Cuando lleguen imágenes del almacén tendrás una referencia concreta. Es un método de investigación, no una promesa de que cada ficha o compra saldrá bien.",
    "Distingue también lo observable de lo desconocido. Compara la tabla de tallas con una prenda propia y anota las preguntas que las fotos del almacén deben responder. Una nota cuidadosa permite recuperar un dato importante sin reconstruirlo después de memoria.",
    "Un presupuesto prudente trata estos controles por separado. Lee de nuevo la ficha y guarda variante y cantidad. Si un detalle puede cambiar tu decisión, anótalo antes del pago. Esto hace visible una diferencia posterior, pero no crea un precio garantizado ni derecho de devolución.",
    "Ten presentes los límites de una foto: luz y ángulo pueden cambiar el color, y una vista exterior no prueba el desgaste futuro. La pregunta útil es si las imágenes bastan para conservar, modificar o quitar un artículo del paquete. No rellenes la información faltante con suposiciones.",
    "Usa ese tiempo de forma deliberada. Una clasificación sencilla muestra qué productos necesitan un tratamiento distinto o encajan juntos. Vuelve a revisar condiciones, precios y opciones en la pantalla actual de cuenta o paquete; la información histórica no confirma la situación en vivo.",
    "Una buena revisión del paquete tiene tres columnas: contenido, motivo de inclusión y evidencia comprobada. Confirma cantidades, variantes y condición visible. Si tu decisión depende de una estimación de coste o limitación de ruta, espera la información que muestra el paquete actual.",
    "El movimiento internacional puede verse afectado por transportista, dirección, destino y procesos aduaneros. No compares por afirmaciones generales de rapidez o seguridad: revisa si la ruta acepta el paquete, muestra un coste comprensible y ofrece el seguimiento que necesitas. Guarda los datos de la ruta elegida.",
    "Así la cadena queda clara: referencia específica, decisión desde la ficha, comparación con la información del almacén y paquete comprendido antes de enviarlo. El método no elimina incertidumbre ni promete fecha, aduanas, autenticidad o precio final; conserva la base de cada decisión."
  ],
  it:[
    "Il vantaggio di questo ordine è la tracciabilità. Conserva titolo del venditore, colore o taglia scelti e punti di confronto prima che l’ordine prosegua. Quando arrivano immagini dal magazzino hai un riferimento concreto. È una pratica di ricerca, non una promessa che ogni scheda o acquisto avrà buon esito.",
    "Distingui inoltre ciò che è osservabile da ciò che non è noto. Confronta la tabella taglie con un tuo capo e annota le domande a cui dovranno rispondere le immagini del magazzino. Una nota accurata permette di recuperare un dettaglio importante senza ricostruirlo più tardi a memoria.",
    "Un budget prudente tratta questi controlli separatamente. Rileggi la scheda e salva variante e quantità. Se un dettaglio può cambiare la scelta, annotalo prima del pagamento. Questo rende visibile una differenza successiva, ma non crea prezzo garantito né diritto di reso.",
    "Ricorda i limiti di una foto: luce e angolazione possono cambiare il colore e una vista esterna non dimostra l’usura futura. La domanda utile è se le immagini bastano per tenere, modificare o togliere un articolo dal pacco. Non colmare le informazioni mancanti con supposizioni.",
    "Usa quel tempo intenzionalmente. Una semplice etichetta mostra quali prodotti richiedono trattamenti diversi o possono viaggiare insieme. Ricontrolla sempre condizioni, prezzi e opzioni nella schermata attuale di account o pacco; un’informazione passata non è una conferma in tempo reale.",
    "Un buon controllo del pacco ha quindi tre colonne: contenuto, motivo dell’inclusione e prova verificata. Conferma quantità, varianti e condizione visibile. Se la scelta dipende da una stima di costo o da un limite di rotta, attendi le informazioni del pacco attuale.",
    "Il movimento internazionale può essere influenzato da vettore, indirizzo, destinazione e procedure doganali. Non confrontare slogan generici di velocità o sicurezza: verifica se la rotta accetta il pacco, mostra un costo comprensibile e offre il tracking necessario. Conserva i dati della rotta scelta.",
    "La catena resta così chiara: riferimento specifico, decisione dalla scheda, confronto con il feedback del magazzino e pacco compreso prima dell’invio. Il metodo non elimina l’incertezza né promette data, dogana, autenticità o prezzo finale; conserva però la base di ogni decisione."
  ],
  pl:[
    "Zaletą tej kolejności jest możliwość prześledzenia decyzji. Zapisz tytuł sprzedawcy, kolor lub rozmiar oraz własne punkty porównania, zanim zamówienie pójdzie dalej. Gdy pojawią się zdjęcia z magazynu, masz konkretny punkt odniesienia. To metoda badawcza, a nie obietnica powodzenia każdej oferty lub zakupu.",
    "Rozdziel również to, co można zaobserwować, od tego, czego nie wiadomo. Porównaj tabelę rozmiarów z własnym ubraniem i zapisz pytania, na które mają odpowiedzieć zdjęcia z magazynu. Staranna notatka pozwala odzyskać ważny szczegół bez późniejszego odtwarzania go z pamięci.",
    "Ostrożny budżet traktuje te kontrole osobno. Przeczytaj ponownie ofertę i zapisz wariant oraz liczbę sztuk. Jeżeli szczegół może zmienić decyzję, zanotuj go przed płatnością. Uwidacznia to późniejszą różnicę, ale nie tworzy gwarantowanej ceny ani prawa do zwrotu.",
    "Pamiętaj też o granicach fotografii: światło i kąt mogą zmienić kolor, a widok zewnętrzny nie dowodzi przyszłego zużycia. Użyteczne pytanie brzmi, czy obrazy wystarczą do zachowania, zmiany lub usunięcia artykułu z paczki. Nie wypełniaj brakujących informacji założeniami.",
    "Wykorzystaj ten czas świadomie. Proste oznaczenie pokaże, które produkty wymagają innego traktowania albo logicznie pasują do jednej paczki. Zawsze ponownie sprawdzaj warunki, ceny i opcje na aktualnym ekranie konta lub paczki; stara informacja nie jest potwierdzeniem na żywo.",
    "Dobra kontrola paczki ma trzy kolumny: zawartość, powód dołączenia i sprawdzony dowód. Potwierdź liczbę, warianty i widoczny stan. Jeśli decyzja zależy od szacunku kosztu lub ograniczenia trasy, poczekaj na dane pokazane dla aktualnej paczki.",
    "Ruch międzynarodowy może zależeć od przewoźnika, adresu, kraju docelowego i procedur celnych. Nie porównuj ogólnych haseł o szybkości lub bezpieczeństwie: sprawdź, czy trasa przyjmuje paczkę, pokazuje zrozumiały koszt i daje potrzebne śledzenie. Zapisz dane wybranej trasy.",
    "Łańcuch pozostaje wtedy jasny: konkretna referencja produktu, decyzja z oferty, porównanie z informacją magazynową i zrozumiana paczka przed zgłoszeniem. Metoda nie usuwa niepewności i nie obiecuje terminu, cła, autentyczności ani ceny końcowej; zachowuje jednak podstawę każdej decyzji."
  ],
  pt:[
    "A vantagem desta ordem é a rastreabilidade. Guarde o título do vendedor, cor ou tamanho escolhido e os seus pontos de comparação antes de a encomenda avançar. Quando chegarem imagens do armazém terá uma referência concreta. É uma prática de pesquisa, não uma promessa de que cada anúncio ou compra terá bom resultado.",
    "Separe também o que é observável do que é desconhecido. Compare a tabela de tamanhos com uma peça sua e anote perguntas a que as imagens do armazém devem responder. Uma nota cuidadosa permite recuperar um detalhe importante sem o reconstruir mais tarde de memória.",
    "Um orçamento prudente trata estas verificações em separado. Releia a página e guarde variante e quantidade. Se um detalhe pode mudar a decisão, registe-o antes do pagamento. Isto torna uma diferença posterior visível, mas não cria preço garantido nem direito de devolução.",
    "Tenha em conta os limites de uma fotografia: luz e ângulo podem alterar a cor, e uma vista exterior não prova o desgaste futuro. A pergunta útil é se as imagens bastam para manter, alterar ou retirar um artigo do pacote. Não preencha informação em falta com suposições.",
    "Use esse tempo de forma intencional. Uma classificação simples mostra quais produtos exigem tratamento diferente ou podem viajar juntos. Confirme sempre condições, preços e opções no ecrã atual de conta ou pacote; informação antiga não é confirmação em tempo real.",
    "Uma boa revisão do pacote tem três colunas: conteúdo, motivo da inclusão e prova verificada. Confirme quantidades, variantes e condição visível. Se a decisão depende de estimativa de custo ou limitação de rota, aguarde a informação mostrada para o pacote atual.",
    "O movimento internacional pode ser afetado por transportadora, morada, destino e processos aduaneiros. Não compare promessas gerais de rapidez ou segurança: veja se a rota aceita o pacote, mostra custo compreensível e disponibiliza o tracking necessário. Guarde os dados da rota escolhida.",
    "Assim a cadeia fica clara: referência específica, decisão pela página, comparação com feedback do armazém e pacote compreendido antes da submissão. O método não elimina incerteza nem promete data, alfândega, autenticidade ou preço final; preserva, porém, a base de cada decisão."
  ],
  sv:[
    "Fördelen med denna ordning är spårbarhet. Spara säljarens titel, vald färg eller storlek och dina jämförelsepunkter innan ordern går vidare. När lagerbilder senare kommer har du en konkret referens. Det är en researchmetod, inte ett löfte om att varje listning eller köp lyckas.",
    "Skilj också mellan det som går att observera och det som är okänt. Jämför storlekstabellen med ett eget plagg och skriv ner frågor som lagerbilderna senare ska besvara. En noggrann anteckning hjälper dig att hitta en viktig uppgift utan att i efterhand behöva återskapa den ur minnet.",
    "En försiktig budget behandlar dessa kontroller separat. Läs produktinformationen igen och spara variant och antal. Om en detalj kan ändra beslutet, anteckna den före betalningen. Det gör en senare skillnad synlig men skapar varken prisgaranti eller returrätt.",
    "Tänk även på bildens begränsningar: ljus och vinkel kan ändra färgintrycket, och en yttre vy bevisar inte framtida slitage. Den användbara frågan är om bilderna räcker för att behålla, ändra eller ta bort varan ur paketet. Fyll inte saknad information med antaganden.",
    "Använd tiden medvetet. En enkel märkning visar vilka varor som behöver olika hantering eller passar att resa tillsammans. Kontrollera alltid villkor, pris och val igen i den aktuella konto- eller paketvyn; äldre information är ingen bekräftelse i realtid.",
    "En bra paketkontroll har därför tre kolumner: innehåll, skäl till inkludering och kontrollerat underlag. Bekräfta antal, varianter och synligt skick. Om beslutet beror på kostnadsuppskattning eller ruttbegränsning, vänta på informationen som visas för det aktuella paketet.",
    "Internationell transport kan påverkas av transportör, adress, destination och tullprocesser. Jämför därför inte allmänna påståenden om snabbast eller säkrast, utan se om rutten accepterar paketet, visar en begriplig kostnad och ger den spårning du behöver. Spara ruttuppgifterna.",
    "Kedjan blir då tydlig: specifik produktreferens, beslut från listningen, jämförelse med lageråterkoppling och ett förstått paket före insändning. Metoden tar inte bort osäkerhet och lovar inte datum, tull, äkthet eller slutpris, men den bevarar grunden för varje beslut."
  ]
};

// Extra translated detail keeps each language edition at the same long-form reading depth.
// These lines extend the second paragraph of each matching section; they are not new claims.
export const localizedArticleDetailAdditions: Record<string,string[]> = {
  nl:[
    "Een vage start maakt een later inspectiebeeld moeilijk te beoordelen. Daarom moet je eigen notitie vóór aankoop precies genoeg zijn om een zichtbaar verschil te herkennen.",
    "Vermeld bijvoorbeeld welk label, welke kleurtoon, welk formaat of welke hoeveelheid je verwacht. Daarmee verandert een algemeen beeld in controleerbaar bewijs.",
    "Reken een productprijs nooit automatisch als eindbedrag. De actuele pakketstap is de plaats waar route en internationale kosten moeten worden beoordeeld.",
    "Controlefoto’s zijn vooral bruikbaar voor zichtbare kenmerken. Ze mogen niet worden gelezen als bevestiging van verborgen kwaliteit of van een uitkomst na levering.",
    "Bewaar alleen geen items uit gewoonte. Gebruik de beschikbare tijd om onzekerheden af te ronden voordat een pakket onnodig ingewikkeld wordt.",
    "Controleer ook of een breekbaar, groot of seizoensgebonden item de reden voor dezelfde verzending werkelijk ondersteunt. Eén pakket is een keuze, geen verplichting.",
    "Wat op een eerdere datum beschikbaar was, kan bij een nieuw pakket anders zijn. Alleen de huidige routeweergave hoort de definitieve keuze te sturen.",
    "Deze notities zijn geen vervanging voor de actuele servicevoorwaarden. Ze helpen uitsluitend de informatie die bij jouw eigen bestelling zichtbaar was, zorgvuldig te bewaren."
  ],
  de:[
    "Ein ungenauer Start macht ein späteres Prüfbild schwer bewertbar. Die eigene Notiz sollte vor dem Kauf daher präzise genug sein, um sichtbare Abweichungen zu erkennen.",
    "Halte etwa erwartetes Label, Farbton, Maß oder Menge fest. So wird aus einem allgemeinen Bild ein überprüfbarer Vergleichspunkt.",
    "Behandle den Produktpreis nie automatisch als Endbetrag. Die aktuelle Paketstufe ist der Ort, an dem Route und internationale Kosten bewertet werden müssen.",
    "Prüfbilder helfen vor allem bei sichtbaren Merkmalen. Sie dürfen nicht als Bestätigung verborgener Qualität oder eines Ergebnisses nach der Zustellung gelesen werden.",
    "Lagere Artikel nicht nur aus Gewohnheit. Nutze die verfügbare Zeit, um Unsicherheiten zu klären, bevor ein Paket unnötig komplex wird.",
    "Prüfe auch, ob ein zerbrechlicher, großer oder saisonaler Artikel den gemeinsamen Versand wirklich sinnvoll macht. Ein Paket ist eine Entscheidung, keine Pflicht.",
    "Was an einem früheren Datum verfügbar war, kann bei einem neuen Paket anders sein. Nur die aktuelle Routenansicht sollte die endgültige Wahl bestimmen.",
    "Diese Notizen ersetzen keine aktuellen Servicebedingungen. Sie helfen nur, die Informationen sorgfältig zu bewahren, die bei der eigenen Bestellung sichtbar waren."
  ],
  fr:[
    "Un départ imprécis rend une image d’inspection ultérieure difficile à évaluer. Votre note doit donc être assez précise avant l’achat pour reconnaître une différence visible.",
    "Indiquez par exemple l’étiquette, la nuance, la mesure ou la quantité attendue. Une image générale devient alors un point de comparaison vérifiable.",
    "Ne considérez jamais automatiquement le prix produit comme le coût final. L’étape actuelle du colis est celle où route et coût international doivent être évalués.",
    "Les photos d’inspection servent surtout aux caractéristiques visibles. Elles ne doivent pas être lues comme confirmation d’une qualité cachée ou d’un résultat après livraison.",
    "Ne gardez pas des articles en stockage par simple habitude. Utilisez le temps disponible pour résoudre les incertitudes avant qu’un colis devienne inutilement complexe.",
    "Vérifiez aussi si un article fragile, volumineux ou saisonnier justifie réellement le même envoi. Un seul colis est un choix, non une obligation.",
    "Ce qui était disponible à une date antérieure peut changer pour un nouveau colis. Seule l’affichage actuel de la route doit guider le choix final.",
    "Ces notes ne remplacent pas les conditions actuelles du service. Elles servent uniquement à conserver avec soin les informations visibles lors de votre propre commande."
  ],
  es:[
    "Un inicio impreciso hace difícil evaluar una foto de inspección posterior. Por eso tu nota debe ser lo bastante concreta antes de comprar para reconocer una diferencia visible.",
    "Anota, por ejemplo, etiqueta, tono de color, medida o cantidad esperada. Así una imagen general se convierte en un punto de comparación verificable.",
    "No trates el precio del producto como coste final de forma automática. La fase actual del paquete es donde deben evaluarse ruta y coste internacional.",
    "Las fotos de inspección sirven principalmente para rasgos visibles. No deben leerse como confirmación de calidad oculta ni de un resultado después de la entrega.",
    "No mantengas artículos almacenados por costumbre. Usa el tiempo disponible para resolver incertidumbres antes de que un paquete se vuelva innecesariamente complejo.",
    "Comprueba también si un artículo frágil, voluminoso o estacional realmente justifica el mismo envío. Un paquete es una decisión, no una obligación.",
    "Lo disponible en una fecha anterior puede cambiar para un paquete nuevo. Solo la vista actual de la ruta debe guiar la elección definitiva.",
    "Estas notas no sustituyen las condiciones actuales del servicio. Solo ayudan a conservar con cuidado la información visible en tu propio pedido."
  ],
  it:[
    "Un inizio impreciso rende difficile valutare una foto d’ispezione successiva. La nota deve quindi essere abbastanza concreta prima dell’acquisto da riconoscere una differenza visibile.",
    "Annota, per esempio, etichetta, tonalità, misura o quantità prevista. Così un’immagine generica diventa un punto di confronto verificabile.",
    "Non trattare automaticamente il prezzo del prodotto come costo finale. La fase attuale del pacco è quella in cui valutare rotta e costo internazionale.",
    "Le foto d’ispezione servono soprattutto per caratteristiche visibili. Non devono essere lette come conferma di qualità nascosta o di un risultato dopo la consegna.",
    "Non mantenere articoli in deposito per abitudine. Usa il tempo disponibile per risolvere incertezze prima che un pacco diventi inutilmente complesso.",
    "Controlla anche se un articolo fragile, ingombrante o stagionale giustifica davvero lo stesso invio. Un pacco è una scelta, non un obbligo.",
    "Ciò che era disponibile in una data precedente può cambiare per un nuovo pacco. Solo la visualizzazione attuale della rotta deve guidare la scelta finale.",
    "Queste note non sostituiscono le condizioni attuali del servizio. Aiutano solo a conservare con cura le informazioni visibili nel proprio ordine."
  ],
  pl:[
    "Nieprecyzyjny początek utrudnia ocenę późniejszego zdjęcia kontrolnego. Notatka przed zakupem powinna być więc wystarczająco konkretna, aby rozpoznać widoczną różnicę.",
    "Zapisz na przykład oczekiwaną etykietę, odcień, wymiar lub liczbę sztuk. Wtedy ogólny obraz staje się punktem porównania, który można sprawdzić.",
    "Nie traktuj automatycznie ceny produktu jako kosztu końcowego. Aktualny etap paczki to miejsce, w którym należy ocenić trasę i koszt międzynarodowy.",
    "Zdjęcia kontrolne służą przede wszystkim do widocznych cech. Nie należy odczytywać ich jako potwierdzenia ukrytej jakości ani wyniku po doręczeniu.",
    "Nie przechowuj artykułów tylko z przyzwyczajenia. Wykorzystaj dostępny czas, aby wyjaśnić niepewności, zanim paczka stanie się niepotrzebnie złożona.",
    "Sprawdź też, czy delikatny, duży lub sezonowy artykuł rzeczywiście uzasadnia wspólną wysyłkę. Jedna paczka to decyzja, nie obowiązek.",
    "To, co było dostępne wcześniej, może się zmienić dla nowej paczki. Tylko aktualny widok trasy powinien kierować ostatecznym wyborem.",
    "Te notatki nie zastępują aktualnych warunków usługi. Pomagają jedynie starannie zachować informacje widoczne przy własnym zamówieniu."
  ],
  pt:[
    "Um início impreciso torna difícil avaliar uma fotografia de inspeção posterior. A sua nota deve ser suficientemente concreta antes da compra para reconhecer uma diferença visível.",
    "Registe, por exemplo, etiqueta, tom de cor, medida ou quantidade esperada. Assim, uma imagem geral passa a ser um ponto de comparação verificável.",
    "Não trate automaticamente o preço do produto como custo final. A fase atual do pacote é onde devem ser avaliadas rota e custo internacional.",
    "As fotografias de inspeção servem sobretudo para características visíveis. Não devem ser lidas como confirmação de qualidade oculta ou de resultado após entrega.",
    "Não mantenha artigos em armazenamento por hábito. Use o tempo disponível para resolver incertezas antes de um pacote se tornar desnecessariamente complexo.",
    "Verifique também se um artigo frágil, volumoso ou sazonal justifica realmente o mesmo envio. Um pacote é uma decisão, não uma obrigação.",
    "O que estava disponível numa data anterior pode mudar para um novo pacote. Só a visualização atual da rota deve orientar a escolha final.",
    "Estas notas não substituem as condições atuais do serviço. Ajudam apenas a guardar cuidadosamente a informação visível na sua própria encomenda."
  ],
  sv:[
    "En oprecis start gör en senare inspektionsbild svår att bedöma. Din anteckning bör därför före köp vara tillräckligt konkret för att upptäcka en synlig skillnad.",
    "Notera till exempel förväntad etikett, färgton, mått eller antal. Då blir en allmän bild en jämförelsepunkt som går att kontrollera.",
    "Behandla inte automatiskt produktpriset som slutkostnad. Den aktuella paketfasen är platsen där rutt och internationell kostnad ska bedömas.",
    "Inspektionsbilder används främst för synliga egenskaper. De ska inte läsas som bekräftelse på dold kvalitet eller resultat efter leverans.",
    "Behåll inte lagrade varor av vana. Använd tiden för att reda ut osäkerheter innan ett paket blir onödigt komplext.",
    "Kontrollera också om en ömtålig, skrymmande eller säsongsbetonad vara verkligen motiverar samma sändning. Ett paket är ett val, inte ett krav.",
    "Det som fanns tillgängligt vid ett tidigare datum kan vara annorlunda för ett nytt paket. Endast den aktuella ruttvyn bör styra det slutliga valet.",
    "Dessa anteckningar ersätter inte aktuella tjänstevillkor. De hjälper bara till att noggrant bevara den information som syntes vid din egen order."
  ]
};

type FaqItem = { question:string; answer:string };

export const factualFaq: Record<string,FaqItem[]> = {
  en:[
    {question:"Is this the official LoloBuy website?",answer:"No. This is an independent research preview. For current account, route, payment and policy information, verify details on LoloBuy’s own service screens."},
    {question:"What can I enter on LoloBuy’s homepage?",answer:"The public homepage shows a field for a product link or product name and an option to search by image."},
    {question:"What does the public order flow show after payment?",answer:"LoloBuy describes payment for the product price and mainland-China freight, followed by warehouse quality inspection and storage."},
    {question:"Does warehouse inspection guarantee the item?",answer:"No. Inspection images and feedback are useful evidence for visible checks, but they do not guarantee authenticity, fit, durability, stock or a later delivery result."},
    {question:"Can stored items be submitted together?",answer:"LoloBuy states that buyers can select products stored in the warehouse and submit them as a single parcel."},
    {question:"Are shipping routes and delivery dates guaranteed?",answer:"No. The homepage advertises logistics routes, but availability, price, restrictions and delivery handling can vary by parcel and destination. Check the current parcel screen before submitting."}
  ],
  nl:[
    {question:"Is dit de officiële LoloBuy-website?",answer:"Nee. Dit is een onafhankelijke onderzoeks-preview. Controleer actuele account-, route-, betaal- en beleidsinformatie in de eigen schermen van LoloBuy."},
    {question:"Wat kan ik op de LoloBuy-homepage invoeren?",answer:"De openbare homepage toont een veld voor een productlink of productnaam en een optie om met een afbeelding te zoeken."},
    {question:"Wat toont de openbare bestelstroom na betaling?",answer:"LoloBuy beschrijft betaling van de productprijs en vracht binnen China, gevolgd door kwaliteitscontrole en opslag in het magazijn."},
    {question:"Garandeert magazijncontrole het artikel?",answer:"Nee. Controlefoto’s en feedback zijn bruikbaar voor zichtbare controles, maar garanderen geen authenticiteit, pasvorm, duurzaamheid, voorraad of latere levering."},
    {question:"Kunnen opgeslagen artikelen samen worden verstuurd?",answer:"LoloBuy vermeldt dat kopers in het magazijn opgeslagen producten kunnen selecteren en als één pakket kunnen indienen."},
    {question:"Zijn verzendroutes en levertijden gegarandeerd?",answer:"Nee. De homepage toont logistieke routes, maar beschikbaarheid, prijs, beperkingen en bezorging kunnen per pakket en bestemming verschillen."}
  ],
  de:[
    {question:"Ist dies die offizielle LoloBuy-Website?",answer:"Nein. Dies ist eine unabhängige Recherchevorschau. Aktuelle Konto-, Routen-, Zahlungs- und Richtlinieninformationen sollten in den eigenen LoloBuy-Ansichten geprüft werden."},
    {question:"Was kann ich auf der LoloBuy-Startseite eingeben?",answer:"Die öffentliche Startseite zeigt ein Feld für Produktlink oder Produktname sowie eine Bildsuche."},
    {question:"Was zeigt der öffentliche Bestellablauf nach der Zahlung?",answer:"LoloBuy beschreibt die Zahlung von Produktpreis und Fracht innerhalb Chinas, gefolgt von Lager-Qualitätsprüfung und Lagerung."},
    {question:"Garantiert die Lagerprüfung den Artikel?",answer:"Nein. Prüfbilder und Rückmeldungen helfen bei sichtbaren Kontrollen, garantieren aber weder Echtheit, Passform, Haltbarkeit, Bestand noch spätere Lieferung."},
    {question:"Können gelagerte Artikel zusammen versendet werden?",answer:"LoloBuy gibt an, dass Käufer im Lager befindliche Produkte auswählen und als ein Paket einreichen können."},
    {question:"Sind Versandrouten und Lieferzeiten garantiert?",answer:"Nein. Die Startseite nennt Logistikrouten; Verfügbarkeit, Preis, Einschränkungen und Zustellung können je Paket und Zielort variieren."}
  ],
  fr:[
    {question:"Est-ce le site officiel de LoloBuy ?",answer:"Non. Il s’agit d’un aperçu de recherche indépendant. Vérifiez les informations actuelles de compte, d’itinéraire, de paiement et de politique dans les écrans LoloBuy."},
    {question:"Que puis-je saisir sur la page d’accueil LoloBuy ?",answer:"La page publique affiche un champ pour un lien ou un nom de produit, ainsi qu’une option de recherche par image."},
    {question:"Que montre le parcours public après paiement ?",answer:"LoloBuy décrit le paiement du prix produit et du fret en Chine continentale, puis le contrôle qualité et le stockage en entrepôt."},
    {question:"Le contrôle en entrepôt garantit-il l’article ?",answer:"Non. Les photos et retours aident aux vérifications visibles, mais ne garantissent ni authenticité, ni taille, ni durabilité, ni stock, ni livraison ultérieure."},
    {question:"Les articles stockés peuvent-ils être envoyés ensemble ?",answer:"LoloBuy indique que les acheteurs peuvent sélectionner des produits stockés et les soumettre en un seul colis."},
    {question:"Les itinéraires et délais de livraison sont-ils garantis ?",answer:"Non. La page d’accueil présente des itinéraires logistiques, mais disponibilité, prix, restrictions et traitement varient selon le colis et la destination."}
  ],
  es:[
    {question:"¿Es este el sitio oficial de LoloBuy?",answer:"No. Es una vista previa de investigación independiente. Verifica la información actual de cuenta, ruta, pago y políticas en las pantallas de LoloBuy."},
    {question:"¿Qué puedo introducir en la página de inicio de LoloBuy?",answer:"La página pública muestra un campo para enlace o nombre de producto y una opción de búsqueda por imagen."},
    {question:"¿Qué muestra el flujo público después del pago?",answer:"LoloBuy describe el pago del precio del producto y el flete dentro de China continental, seguido de inspección de calidad y almacenamiento."},
    {question:"¿La inspección en almacén garantiza el artículo?",answer:"No. Las fotos y comentarios ayudan con comprobaciones visibles, pero no garantizan autenticidad, ajuste, durabilidad, existencias ni entrega posterior."},
    {question:"¿Pueden enviarse juntos los artículos almacenados?",answer:"LoloBuy indica que los compradores pueden seleccionar productos almacenados y enviarlos como un solo paquete."},
    {question:"¿Se garantizan las rutas y fechas de entrega?",answer:"No. La página muestra rutas logísticas, pero disponibilidad, precio, restricciones y gestión pueden variar según el paquete y el destino."}
  ],
  it:[
    {question:"Questo è il sito ufficiale di LoloBuy?",answer:"No. È un’anteprima di ricerca indipendente. Verifica le informazioni aggiornate su account, rotte, pagamenti e policy nelle schermate LoloBuy."},
    {question:"Cosa posso inserire nella home LoloBuy?",answer:"La pagina pubblica mostra un campo per link o nome del prodotto e un’opzione di ricerca per immagine."},
    {question:"Cosa mostra il flusso pubblico dopo il pagamento?",answer:"LoloBuy descrive il pagamento del prezzo prodotto e del trasporto nella Cina continentale, seguito da controllo qualità e deposito."},
    {question:"Il controllo in magazzino garantisce l’articolo?",answer:"No. Foto e riscontri aiutano le verifiche visibili, ma non garantiscono autenticità, vestibilità, durata, disponibilità o consegna successiva."},
    {question:"Gli articoli depositati possono essere spediti insieme?",answer:"LoloBuy indica che gli acquirenti possono selezionare prodotti in magazzino e inviarli come un unico pacco."},
    {question:"Rotte e date di consegna sono garantite?",answer:"No. La home mostra rotte logistiche, ma disponibilità, prezzo, limiti e gestione possono variare per pacco e destinazione."}
  ],
  pl:[
    {question:"Czy to jest oficjalna strona LoloBuy?",answer:"Nie. To niezależna wersja badawcza. Aktualne informacje o koncie, trasie, płatności i zasadach sprawdzaj w ekranach LoloBuy."},
    {question:"Co można wpisać na stronie głównej LoloBuy?",answer:"Publiczna strona pokazuje pole dla linku lub nazwy produktu oraz opcję wyszukiwania obrazem."},
    {question:"Co pokazuje publiczny proces po płatności?",answer:"LoloBuy opisuje płatność za produkt i fracht w Chinach kontynentalnych, a następnie kontrolę jakości i magazynowanie."},
    {question:"Czy kontrola magazynowa gwarantuje produkt?",answer:"Nie. Zdjęcia i informacje zwrotne pomagają w widocznych kontrolach, lecz nie gwarantują autentyczności, dopasowania, trwałości, zapasu ani późniejszej dostawy."},
    {question:"Czy przechowywane artykuły można wysłać razem?",answer:"LoloBuy podaje, że kupujący mogą wybrać produkty w magazynie i zgłosić je jako jedną paczkę."},
    {question:"Czy trasy i terminy dostawy są gwarantowane?",answer:"Nie. Strona pokazuje trasy logistyczne, lecz dostępność, cena, ograniczenia i obsługa zależą od paczki oraz kraju docelowego."}
  ],
  pt:[
    {question:"Este é o site oficial da LoloBuy?",answer:"Não. Esta é uma pré-visualização de pesquisa independente. Confirme informações atuais de conta, rota, pagamento e políticas nas telas da LoloBuy."},
    {question:"O que posso inserir na página inicial da LoloBuy?",answer:"A página pública mostra um campo para link ou nome do produto e uma opção de pesquisa por imagem."},
    {question:"O que mostra o fluxo público após o pagamento?",answer:"A LoloBuy descreve o pagamento do preço do produto e do frete na China continental, seguido de inspeção de qualidade e armazenamento."},
    {question:"A inspeção no armazém garante o artigo?",answer:"Não. Fotos e comentários ajudam em verificações visíveis, mas não garantem autenticidade, tamanho, durabilidade, stock ou entrega posterior."},
    {question:"Artigos armazenados podem ser enviados juntos?",answer:"A LoloBuy indica que compradores podem selecionar produtos no armazém e submetê-los como uma única encomenda."},
    {question:"Rotas e datas de entrega são garantidas?",answer:"Não. A página mostra rotas logísticas, mas disponibilidade, preço, restrições e tratamento variam por pacote e destino."}
  ],
  sv:[
    {question:"Är detta LoloBuys officiella webbplats?",answer:"Nej. Detta är en oberoende forskningsförhandsvisning. Kontrollera aktuella konto-, rutt-, betalnings- och policyuppgifter i LoloBuys egna vyer."},
    {question:"Vad kan jag ange på LoloBuys startsida?",answer:"Den offentliga startsidan visar ett fält för produktlänk eller produktnamn och ett alternativ för bildsökning."},
    {question:"Vad visar det offentliga flödet efter betalning?",answer:"LoloBuy beskriver betalning av produktpris och frakt inom Fastlandskina, följt av kvalitetskontroll och lagring."},
    {question:"Garanterar lagerkontrollen varan?",answer:"Nej. Bilder och återkoppling hjälper synliga kontroller men garanterar inte äkthet, passform, hållbarhet, lagerstatus eller senare leverans."},
    {question:"Kan lagrade artiklar skickas tillsammans?",answer:"LoloBuy anger att köpare kan välja lagrade produkter och skicka dem som ett enda paket."},
    {question:"Är fraktrutter och leveransdatum garanterade?",answer:"Nej. Startsidan visar logistikrutter, men tillgänglighet, pris, begränsningar och hantering varierar per paket och destination."}
  ]
};
