import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { PageHero, PageShell, SourceNote } from "../../../../components";
import { languages } from "../../../../data";
import { localeCopy } from "../../../../localeCopy";
import { localizedContent } from "../../../../localizedContent";
import { ResponsiveArticleSection } from "../../../../ResponsiveDetails";

export function generateStaticParams(){return languages.flatMap(language=>localizedContent.en.articles.map(article=>({lang:language.code,slug:article.slug})));}
export async function generateMetadata({params}:{params:Promise<{lang:string;slug:string}>}):Promise<Metadata>{const {lang,slug}=await params;const article=localizedContent[lang]?.articles.find(item=>item.slug===slug);const copy=localeCopy[lang];if(!article||!copy)return{};return{title:`${article.title} · ${copy.verifiedLabel}`,description:article.description,alternates:{canonical:`/languages/${lang}/articles/${slug}`,languages:Object.fromEntries([["x-default",`/articles/${slug}`],...languages.map(language=>[language.code,`/languages/${language.code}/articles/${slug}`])])},openGraph:{title:article.title,description:article.description,images:[]},twitter:{title:article.title,description:article.description,images:[]}}}

export default async function LocalizedArticleDetail({params}:{params:Promise<{lang:string;slug:string}>}){const {lang,slug}=await params;const language=languages.find(item=>item.code===lang);const copy=localeCopy[lang];const bundle=localizedContent[lang];const article=bundle?.articles.find(item=>item.slug===slug);if(!language||!copy||!bundle||!article)notFound();return <PageShell lang={lang}><div className="article-wrap"><PageHero lang={lang} eyebrow={`${language.name} · ${article.tag}`} title={article.title} intro={article.description}/><section className="localized-summary"><strong>{bundle.ui.translatedEdition}</strong><p>{language.intro}</p><p>{bundle.ui.preserved}</p></section><div className="article-layout"><article className="prose long-form"><p className="language-disclosure">{bundle.ui.translatedEdition}</p>{article.sections.map((section,index)=><ResponsiveArticleSection title={section.heading} key={`${index}-${section.heading}`}><h2>{section.heading}</h2>{section.paragraphs.map((paragraph,paragraphIndex)=><p key={paragraphIndex}>{paragraph}</p>)}{index===1&&<SourceNote lang={lang}>{bundle.ui.sourceNote}</SourceNote>}</ResponsiveArticleSection>)}</article><aside className="article-side"><strong>{copy.articlesTitle}</strong><ol><li>{copy.verifiedLabel}</li><li>{article.readTime}</li><li>{bundle.ui.checked}</li></ol><a href={`/languages/${lang}/articles`}>{bundle.ui.allArticles} →</a><a className="side-secondary" href={`/languages/${lang}/faq`}>{bundle.ui.allFaqs} →</a></aside></div></div></PageShell>}
