import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteHeader } from "@/app/components/SiteHeader";

const guides: Record<string, { label: string; title: string; intro: string; sections: { title: string; paragraphs: string[] }[] }> = {
  "pikobuy-beginner-guide": { label: "PikoBuy beginner guide · 2026", title: "From product link to parcel: the decisions that matter", intro: "A practical map of the agent-shopping workflow, based on the public process presented by PikoBuy and the product research available through FindSpreadsheet.", sections: [
    { title: "Start with the live product, not the spreadsheet label", paragraphs: ["A spreadsheet is a discovery layer. Its job is to help you narrow thousands of links into a shortlist. The live product page remains the place to confirm the selected size, colour, version, domestic delivery cost and current availability.", "Compare two or three genuinely similar products. More tabs do not automatically create a better decision; a useful shortlist records why each product is still being considered."] },
    { title: "Understand the two-payment workflow", paragraphs: ["Agent shopping normally separates the product order from international parcel shipping. The first payment covers the selected product and related domestic charges shown at checkout. After the product reaches the warehouse, the parcel stage calculates international shipping according to the destination, route and chargeable weight.", "Do not treat a low product price as the final landed cost. Bulky shoes, jackets and boxed goods can become expensive after volumetric weight is considered."] },
    { title: "Use the warehouse stage as a decision point", paragraphs: ["Warehouse photos can help confirm that the received item resembles the selected listing and reveal visible issues such as obvious damage, colour mismatch, print placement or missing components. They do not prove authenticity, material composition, long-term durability or perfect sizing.", "If the visible product does not match the order, consult the current platform support and after-sales rules before submitting the parcel. Time limits and seller eligibility can change."] },
    { title: "Choose the parcel only after checking the route", paragraphs: ["Compare the eligible routes for the actual destination and product type. Batteries, liquids, cosmetics and branded goods may face route restrictions. Review estimated delivery ranges as estimates rather than guaranteed arrival dates.", "After dispatch, follow the tracking shown in the parcel area and keep the order, warehouse and parcel records together until delivery is complete."] },
  ]},
  "pikobuy-qc-guide": { label: "Warehouse photo guide · 2026", title: "What QC photos can show — and what they cannot", intro: "A category-specific inspection checklist for spreadsheet shoppers who want to make better use of warehouse images without turning them into a false guarantee.", sections: [
    { title: "Check identity before quality", paragraphs: ["First confirm the basic order: product type, selected colour, visible size tag, quantity and major included parts. An image cannot help if it shows the wrong variant.", "Compare the warehouse photos with the seller listing you actually selected, not with unrelated marketing photography or another batch found on social media."] },
    { title: "Shoes and clothing need different evidence", paragraphs: ["For shoes, request or inspect clear side profiles, heel alignment, outsole, toe shape, panel stitching and the visible size label. A top-down image alone is rarely enough to judge shape.", "For hoodies and T-shirts, look at print position, collar or hood construction, seams, cuff shape, visible labels and measurements. Compare garment measurements with clothing that already fits rather than relying only on S, M or L."] },
    { title: "Bags, accessories and electronics", paragraphs: ["For bags, inspect overall proportions, hardware colour, zipper line, handle or strap attachment, lining and visible logo placement. Ask for a scale or measurement reference when dimensions affect the decision.", "For electronics, confirm the exact model, plug type, stated voltage, visible ports and included accessories. Photos cannot verify battery health, internal components, software compatibility or regulatory compliance."] },
    { title: "The honest limit of QC", paragraphs: ["Warehouse images document visible condition under a particular camera, angle and lighting setup. They cannot guarantee authenticity, hidden construction, exact colour on your screen, long-term performance, customs outcome or delivery condition.", "A trustworthy guide should describe these limits plainly. Avoid any spreadsheet claiming that a photo makes an item completely safe or risk-free."] },
  ]},
  "pikobuy-shipping-guide": { label: "Europe & North America · 2026", title: "Plan shipping before a cheap find becomes an expensive parcel", intro: "A decision guide for route eligibility, actual weight, volumetric weight and customs uncertainty when using a China shopping agent.", sections: [
    { title: "Shipping starts before checkout", paragraphs: ["The easiest time to control parcel cost is before buying. Check whether the product is bulky, boxed, fragile, liquid-filled or battery-powered. These characteristics can reduce the number of eligible routes or increase chargeable weight.", "Shoes without retail boxes usually occupy less space, while puffer jackets, rigid bags and large packaging can create more volume than their scale weight suggests."] },
    { title: "Actual weight versus volumetric weight", paragraphs: ["Carriers may charge according to the greater of actual weight and a volume-based calculation. The exact divisor and billing rules depend on the selected route, so use the current route estimator rather than a generic formula copied from an old guide.", "Rehearsal or pre-packing services, when currently offered, may provide a more useful packed measurement before final payment. Verify availability in the live platform interface."] },
    { title: "Compare routes by eligibility, not only price", paragraphs: ["A lower estimate is not useful if the route does not accept the product type or destination. Compare product restrictions, weight and dimension limits, tracking, insurance options, estimated delivery range and the rules for declaring parcel contents.", "Promotional shipping discounts can change. Confirm account eligibility, destination, route and expiry before treating a coupon as part of the final budget."] },
    { title: "Customs and delivery remain uncertain", paragraphs: ["International parcels may be inspected, delayed, taxed, returned or seized according to destination rules and parcel contents. No independent spreadsheet can promise tax-free or customs-free delivery.", "For Sweden and other EU destinations, consult current EU and national customs information before ordering. For the United States, Canada and the United Kingdom, use the relevant government customs source because thresholds and procedures can change."] },
  ]},
};

export default async function GuidePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const guide = guides[slug];
  if (!guide) notFound();
  return <main><SiteHeader /><article><div className="article-header"><Link className="back" href="/guides">← Back to guides</Link><p className="section-label">{guide.label}</p><h1>{guide.title}</h1><p>{guide.intro}</p></div><div className="article-layout"><aside className="article-aside">Independent research resource.<br/><br/>Platform features, prices, routes and policies can change. Recheck current information before payment.</aside><div className="article-body"><div className="fact-box"><p><strong>Source boundary:</strong> this guide explains the publicly visible PikoBuy agent workflow and adds independent product-research checks. It does not promise a result for any order.</p></div>{guide.sections.map(section => <section key={section.title}><h2>{section.title}</h2>{section.paragraphs.map(p => <p key={p}>{p}</p>)}</section>)}<div className="fact-box"><p>Next step: <a href="https://findspreadsheet.com/"><strong>open the FindSpreadsheet homepage →</strong></a></p></div></div></div></article></main>;
}
