"use client";

import { useState } from "react";
import { tr } from "@/content/i18n";

type Locale = { name:string; nav:string[]; badge:string; title:string; accent:string; intro:string; search:string; go:string; popular:string; cats:string; catsText:string; flow:string; steps:[string,string][]; qc:string; qcText:string; ship:string; shipText:string; guides:string; guidesText:string; faq:string; questions:[string,string][]; cta:string; ctaText:string; footer:string };

const locales: Record<string, Locale> = {
  en:{name:"English",nav:["Find products","How it works","QC checklist","Shipping","Guides","FAQ"],badge:"Independent buyer resource · Facts checked Aug 2026",title:"A clearer LoloBuy",accent:"spreadsheet for Europe",intro:"Search product ideas, compare the details that matter, and continue to matching results on FindSpreadsheet. No checkout, payments or invented stock claims here.",search:"Search products, styles or source links",go:"Search finds",popular:"Popular: sneakers · hoodies · bags · accessories",cats:"Start with a category",catsText:"Each category opens a focused FindSpreadsheet search, so you compare similar products instead of scrolling through a mixed list.",flow:"From a product idea to a safer shortlist",steps:[["Search & compare","Compare photos, measurements, source clues and price context."],["Review before paying","Recheck the live title, option, domestic delivery charge and seller page."],["Inspect warehouse QC","Zoom in on shape, colour, stitching, measurements and visible defects."],["Plan the parcel","Compare actual and volumetric weight, route restrictions, insurance and taxes."]],qc:"A practical QC checklist",qcText:"A photo is evidence only for what it clearly shows. A spreadsheet row is not proof of stock, seller reliability or final quality.",ship:"Shipping without guesswork",shipText:"International cost depends on destination, route, packed weight and parcel dimensions. Consider likely freight cost while building a shortlist.",guides:"Evidence-led buyer guides",guidesText:"Useful answers between finding an item and submitting a parcel.",faq:"Quick answers",questions:[["Is this the official LoloBuy website?","No. This independent site does not take payments, manage accounts or operate a warehouse."],["Are prices and stock guaranteed?","No. Recheck the live destination page, selected option, domestic delivery and availability."],["What does LoloBuy publicly confirm?","Its public homepage describes a China-warehouse flow, quality inspection feedback and global shipping. Live account terms still control each order."]],cta:"Browse the complete product database",ctaText:"Continue to FindSpreadsheet for current search results.",footer:"Independent guide · Not affiliated with LoloBuy · No checkout or payment collection"},
  de:{name:"Deutsch",nav:["Produkte finden","So funktioniert es","QC-Checkliste","Versand","Ratgeber","FAQ"],badge:"Unabhängige Kaufhilfe · Fakten geprüft Aug. 2026",title:"Eine klarere LoloBuy-",accent:"Tabelle für Europa",intro:"Suche Produktideen, vergleiche wichtige Details und öffne passende Ergebnisse bei FindSpreadsheet. Kein Checkout, keine Zahlungen und keine erfundenen Lagerangaben.",search:"Produkte, Stile oder Quelllinks suchen",go:"Produkte suchen",popular:"Beliebt: Sneaker · Hoodies · Taschen · Accessoires",cats:"Mit einer Kategorie beginnen",catsText:"Jede Kategorie öffnet eine gezielte FindSpreadsheet-Suche, damit du ähnliche Produkte vergleichst.",flow:"Von der Produktidee zur sicheren Auswahl",steps:[["Suchen und vergleichen","Vergleiche Fotos, Maße, Quellenhinweise und Preise."],["Vor der Zahlung prüfen","Prüfe Titel, Variante, Inlandsversand und Verkäuferseite erneut."],["Lager-QC prüfen","Kontrolliere Form, Farbe, Nähte, Maße und sichtbare Mängel."],["Paket planen","Vergleiche Gewicht, Volumen, Beschränkungen, Versicherung und Steuern."]],qc:"Praktische QC-Checkliste",qcText:"Ein Foto belegt nur, was klar sichtbar ist. Eine Tabellenzeile beweist weder Bestand noch Verkäuferzuverlässigkeit oder Endqualität.",ship:"Versand ohne Rätselraten",shipText:"Kosten hängen von Ziel, Route, Gewicht und Paketmaßen ab. Plane Frachtkosten bei der Auswahl ein.",guides:"Faktenbasierte Kaufratgeber",guidesText:"Hilfreiche Antworten zwischen Produktsuche und Paketaufgabe.",faq:"Kurze Antworten",questions:[["Ist dies die offizielle LoloBuy-Website?","Nein. Diese unabhängige Seite verarbeitet keine Zahlungen und betreibt weder Konten noch Lager."],["Sind Preise und Bestand garantiert?","Nein. Prüfe Zielseite, Variante, Inlandsversand und Verfügbarkeit erneut."],["Was bestätigt LoloBuy öffentlich?","Die öffentliche Startseite beschreibt China-Lager, Qualitätsprüfung und weltweiten Versand. Aktuelle Kontobedingungen gelten."]],cta:"Vollständige Produktdatenbank öffnen",ctaText:"Weiter zu aktuellen Ergebnissen auf FindSpreadsheet.",footer:"Unabhängiger Ratgeber · Nicht mit LoloBuy verbunden · Keine Zahlungsabwicklung"},
  fr:{name:"Français",nav:["Trouver des produits","Fonctionnement","Contrôle QC","Livraison","Guides","FAQ"],badge:"Ressource indépendante · Vérifiée en août 2026",title:"Un tableau LoloBuy",accent:"plus clair pour l’Europe",intro:"Recherchez des idées, comparez les détails importants puis consultez les résultats sur FindSpreadsheet. Aucun paiement ni stock inventé ici.",search:"Rechercher un produit, style ou lien",go:"Rechercher",popular:"Populaire : baskets · sweats · sacs · accessoires",cats:"Commencez par une catégorie",catsText:"Chaque catégorie ouvre une recherche FindSpreadsheet ciblée pour comparer des produits similaires.",flow:"De l’idée à une sélection plus sûre",steps:[["Chercher et comparer","Comparez photos, mesures, sources et contexte de prix."],["Vérifier avant de payer","Revérifiez titre, option, livraison locale et vendeur."],["Contrôler les photos QC","Examinez forme, couleur, coutures, mesures et défauts."],["Planifier le colis","Comparez poids réel et volumétrique, restrictions, assurance et taxes."]],qc:"Une liste QC pratique",qcText:"Une photo ne prouve que ce qu’elle montre clairement. Une ligne ne garantit ni stock, ni vendeur, ni qualité finale.",ship:"Expédition sans suppositions",shipText:"Le coût dépend de la destination, de la ligne, du poids emballé et des dimensions.",guides:"Guides fondés sur des faits",guidesText:"Des réponses utiles entre la découverte et l’envoi du colis.",faq:"Réponses rapides",questions:[["Est-ce le site officiel LoloBuy ?","Non. Ce site indépendant ne collecte aucun paiement et ne gère ni compte ni entrepôt."],["Prix et stock sont-ils garantis ?","Non. Revérifiez option, livraison locale et disponibilité."],["Que confirme publiquement LoloBuy ?","Sa page publique décrit un entrepôt en Chine, un contrôle qualité et une expédition mondiale. Les conditions en direct prévalent."]],cta:"Parcourir la base complète",ctaText:"Consultez les résultats actuels sur FindSpreadsheet.",footer:"Guide indépendant · Sans affiliation LoloBuy · Aucun paiement"},
  es:{name:"Español",nav:["Buscar productos","Cómo funciona","Lista QC","Envíos","Guías","FAQ"],badge:"Recurso independiente · Revisado ago. 2026",title:"Una hoja LoloBuy",accent:"más clara para Europa",intro:"Busca ideas, compara los detalles importantes y abre resultados en FindSpreadsheet. Sin pagos ni afirmaciones de stock inventadas.",search:"Buscar productos, estilos o enlaces",go:"Buscar",popular:"Popular: zapatillas · sudaderas · bolsos · accesorios",cats:"Empieza por una categoría",catsText:"Cada categoría abre una búsqueda específica en FindSpreadsheet para comparar productos similares.",flow:"De una idea a una lista más segura",steps:[["Buscar y comparar","Compara fotos, medidas, origen y contexto de precios."],["Revisar antes de pagar","Comprueba título, opción, envío nacional y vendedor."],["Revisar el QC","Amplía forma, color, costuras, medidas y defectos."],["Planificar el paquete","Compara peso real y volumétrico, restricciones, seguro e impuestos."]],qc:"Lista QC práctica",qcText:"Una foto solo demuestra lo que muestra. Una fila no garantiza stock, vendedor ni calidad final.",ship:"Envíos sin adivinar",shipText:"El coste depende del destino, ruta, peso embalado y dimensiones.",guides:"Guías basadas en hechos",guidesText:"Respuestas útiles desde el hallazgo hasta el envío del paquete.",faq:"Respuestas rápidas",questions:[["¿Es el sitio oficial de LoloBuy?","No. Es un sitio independiente que no cobra pagos ni gestiona cuentas o almacenes."],["¿Se garantizan precios y stock?","No. Revisa la página final, opción, envío nacional y disponibilidad."],["¿Qué confirma LoloBuy públicamente?","Su página pública describe almacén en China, inspección de calidad y envío global. Las condiciones en vivo prevalecen."]],cta:"Explorar la base completa",ctaText:"Continúa a los resultados actuales de FindSpreadsheet.",footer:"Guía independiente · Sin afiliación con LoloBuy · Sin pagos"},
  it:{name:"Italiano",nav:["Trova prodotti","Come funziona","Checklist QC","Spedizione","Guide","FAQ"],badge:"Risorsa indipendente · Verificata ago. 2026",title:"Un foglio LoloBuy",accent:"più chiaro per l’Europa",intro:"Cerca idee, confronta i dettagli importanti e apri i risultati su FindSpreadsheet. Nessun pagamento o dato di stock inventato.",search:"Cerca prodotti, stili o link",go:"Cerca",popular:"Popolari: sneaker · felpe · borse · accessori",cats:"Inizia da una categoria",catsText:"Ogni categoria apre una ricerca mirata su FindSpreadsheet per confrontare prodotti simili.",flow:"Dall’idea a una selezione più sicura",steps:[["Cerca e confronta","Confronta foto, misure, fonte e contesto del prezzo."],["Controlla prima di pagare","Ricontrolla titolo, variante, spedizione interna e venditore."],["Esamina il QC","Ingrandisci forma, colore, cuciture, misure e difetti."],["Pianifica il pacco","Confronta peso reale e volumetrico, restrizioni, assicurazione e tasse."]],qc:"Checklist QC pratica",qcText:"Una foto prova solo ciò che mostra. Una riga non garantisce stock, venditore o qualità finale.",ship:"Spedire senza ipotesi",shipText:"Il costo dipende da destinazione, linea, peso imballato e dimensioni.",guides:"Guide basate sui fatti",guidesText:"Risposte utili dalla scoperta all’invio del pacco.",faq:"Risposte rapide",questions:[["È il sito ufficiale LoloBuy?","No. È una guida indipendente senza pagamenti, account o magazzini."],["Prezzi e stock sono garantiti?","No. Ricontrolla pagina finale, variante, consegna interna e disponibilità."],["Cosa conferma pubblicamente LoloBuy?","La pagina pubblica descrive magazzino in Cina, controllo qualità e spedizione globale. Valgono i termini live."]],cta:"Esplora il database completo",ctaText:"Continua ai risultati correnti su FindSpreadsheet.",footer:"Guida indipendente · Non affiliata a LoloBuy · Nessun pagamento"},
  nl:{name:"Nederlands",nav:["Producten zoeken","Zo werkt het","QC-checklist","Verzending","Gidsen","FAQ"],badge:"Onafhankelijke koopgids · Gecheckt aug. 2026",title:"Een duidelijker LoloBuy-",accent:"overzicht voor Europa",intro:"Zoek productideeën, vergelijk belangrijke details en open resultaten op FindSpreadsheet. Geen betaling of verzonnen voorraadclaims.",search:"Zoek producten, stijlen of bronlinks",go:"Zoeken",popular:"Populair: sneakers · hoodies · tassen · accessoires",cats:"Begin met een categorie",catsText:"Elke categorie opent een gerichte FindSpreadsheet-zoekopdracht voor vergelijkbare producten.",flow:"Van idee naar een veiligere shortlist",steps:[["Zoeken en vergelijken","Vergelijk foto’s, maten, broninformatie en prijscontext."],["Controleren vóór betaling","Controleer titel, optie, lokale bezorging en verkoper."],["QC-foto’s bekijken","Zoom in op vorm, kleur, naden, maten en zichtbare fouten."],["Pakket plannen","Vergelijk echt en volumegewicht, beperkingen, verzekering en belastingen."]],qc:"Praktische QC-checklist",qcText:"Een foto bewijst alleen wat zichtbaar is. Een rij garandeert geen voorraad, verkoper of eindkwaliteit.",ship:"Verzenden zonder gokken",shipText:"Kosten hangen af van bestemming, route, verpakt gewicht en afmetingen.",guides:"Feitelijke koopgidsen",guidesText:"Nuttige antwoorden van productvondst tot pakketverzending.",faq:"Snelle antwoorden",questions:[["Is dit de officiële LoloBuy-site?","Nee. Deze onafhankelijke site verwerkt geen betalingen, accounts of magazijnen."],["Zijn prijzen en voorraad gegarandeerd?","Nee. Controleer eindpagina, optie, lokale bezorging en beschikbaarheid."],["Wat bevestigt LoloBuy publiekelijk?","De openbare homepage beschrijft een China-magazijn, kwaliteitscontrole en wereldwijde verzending. Live voorwaarden gelden."]],cta:"Bekijk de volledige database",ctaText:"Ga door naar actuele FindSpreadsheet-resultaten.",footer:"Onafhankelijke gids · Niet verbonden aan LoloBuy · Geen betalingen"},
  pl:{name:"Polski",nav:["Znajdź produkty","Jak to działa","Lista QC","Wysyłka","Poradniki","FAQ"],badge:"Niezależny poradnik · Fakty sprawdzone VIII 2026",title:"Czytelniejszy arkusz",accent:"LoloBuy dla Europy",intro:"Szukaj pomysłów, porównuj ważne szczegóły i przechodź do wyników w FindSpreadsheet. Bez płatności i zmyślonych informacji o magazynie.",search:"Szukaj produktów, stylów lub linków",go:"Szukaj",popular:"Popularne: sneakersy · bluzy · torby · akcesoria",cats:"Zacznij od kategorii",catsText:"Każda kategoria otwiera precyzyjne wyszukiwanie w FindSpreadsheet, aby porównywać podobne produkty.",flow:"Od pomysłu do bezpieczniejszej listy",steps:[["Szukaj i porównuj","Porównaj zdjęcia, wymiary, źródło i kontekst cenowy."],["Sprawdź przed płatnością","Sprawdź tytuł, wariant, dostawę krajową i sprzedawcę."],["Sprawdź zdjęcia QC","Powiększ kształt, kolor, szwy, wymiary i wady."],["Zaplanuj paczkę","Porównaj wagę rzeczywistą i objętościową, ograniczenia, ubezpieczenie i podatki."]],qc:"Praktyczna lista QC",qcText:"Zdjęcie potwierdza tylko to, co pokazuje. Wiersz nie gwarantuje stanu, sprzedawcy ani jakości.",ship:"Wysyłka bez zgadywania",shipText:"Koszt zależy od kraju, trasy, wagi paczki i wymiarów.",guides:"Poradniki oparte na faktach",guidesText:"Pomocne odpowiedzi od znalezienia produktu do nadania paczki.",faq:"Szybkie odpowiedzi",questions:[["Czy to oficjalna strona LoloBuy?","Nie. To niezależny serwis bez płatności, obsługi kont i magazynu."],["Czy ceny i stan są gwarantowane?","Nie. Sprawdź stronę docelową, wariant, dostawę krajową i dostępność."],["Co publicznie potwierdza LoloBuy?","Publiczna strona opisuje magazyn w Chinach, kontrolę jakości i wysyłkę globalną. Obowiązują aktualne warunki konta."]],cta:"Przeglądaj pełną bazę produktów",ctaText:"Przejdź do aktualnych wyników FindSpreadsheet.",footer:"Niezależny poradnik · Bez powiązania z LoloBuy · Bez płatności"},
  pt:{name:"Português",nav:["Encontrar produtos","Como funciona","Lista QC","Envio","Guias","FAQ"],badge:"Recurso independente · Revisto ago. 2026",title:"Uma folha LoloBuy",accent:"mais clara para a Europa",intro:"Pesquise ideias, compare detalhes importantes e abra resultados no FindSpreadsheet. Sem pagamentos nem alegações inventadas de stock.",search:"Pesquisar produtos, estilos ou links",go:"Pesquisar",popular:"Popular: sapatilhas · hoodies · malas · acessórios",cats:"Comece por uma categoria",catsText:"Cada categoria abre uma pesquisa focada no FindSpreadsheet para comparar produtos semelhantes.",flow:"Da ideia a uma lista mais segura",steps:[["Pesquisar e comparar","Compare fotos, medidas, origem e contexto do preço."],["Rever antes de pagar","Confirme título, opção, entrega doméstica e vendedor."],["Inspecionar QC","Amplie forma, cor, costuras, medidas e defeitos."],["Planear a encomenda","Compare peso real e volumétrico, restrições, seguro e impostos."]],qc:"Lista QC prática",qcText:"Uma foto só prova o que mostra. Uma linha não garante stock, vendedor ou qualidade final.",ship:"Envio sem adivinhações",shipText:"O custo depende do destino, rota, peso embalado e dimensões.",guides:"Guias baseados em factos",guidesText:"Respostas úteis desde a descoberta até ao envio da encomenda.",faq:"Respostas rápidas",questions:[["Este é o site oficial LoloBuy?","Não. É um site independente sem pagamentos, contas ou armazém."],["Preços e stock são garantidos?","Não. Reveja página final, opção, entrega doméstica e disponibilidade."],["O que a LoloBuy confirma publicamente?","A página pública descreve armazém na China, inspeção de qualidade e envio global. Valem os termos atuais."]],cta:"Explorar a base completa",ctaText:"Continue para os resultados atuais no FindSpreadsheet.",footer:"Guia independente · Sem afiliação LoloBuy · Sem pagamentos"},
  sv:{name:"Svenska",nav:["Hitta produkter","Så fungerar det","QC-checklista","Frakt","Guider","FAQ"],badge:"Oberoende köpguide · Kontrollerad aug. 2026",title:"Ett tydligare LoloBuy-",accent:"kalkylblad för Europa",intro:"Sök produktidéer, jämför viktiga detaljer och öppna resultat på FindSpreadsheet. Inga betalningar eller påhittade lageruppgifter.",search:"Sök produkter, stilar eller länkar",go:"Sök",popular:"Populärt: sneakers · hoodies · väskor · accessoarer",cats:"Börja med en kategori",catsText:"Varje kategori öppnar en riktad FindSpreadsheet-sökning för liknande produkter.",flow:"Från idé till säkrare urval",steps:[["Sök och jämför","Jämför bilder, mått, källa och prissammanhang."],["Kontrollera före betalning","Kontrollera titel, alternativ, inrikesfrakt och säljare."],["Granska QC-bilder","Zooma in form, färg, sömmar, mått och synliga fel."],["Planera paketet","Jämför verklig och volymvikt, begränsningar, försäkring och skatt."]],qc:"Praktisk QC-checklista",qcText:"En bild bevisar bara det den visar. En rad garanterar inte lager, säljare eller slutkvalitet.",ship:"Frakt utan gissningar",shipText:"Kostnaden beror på destination, linje, packad vikt och mått.",guides:"Faktabaserade köpguider",guidesText:"Hjälpsamma svar från produktfynd till paketfrakt.",faq:"Snabba svar",questions:[["Är detta LoloBuys officiella webbplats?","Nej. Den oberoende sidan hanterar inte betalningar, konton eller lager."],["Garanteras pris och lager?","Nej. Kontrollera slutsidan, alternativ, lokal leverans och tillgänglighet."],["Vad bekräftar LoloBuy offentligt?","Den offentliga sidan beskriver lager i Kina, kvalitetskontroll och global frakt. Aktuella villkor gäller."]],cta:"Utforska hela produktdatabasen",ctaText:"Fortsätt till aktuella resultat på FindSpreadsheet.",footer:"Oberoende guide · Inte ansluten till LoloBuy · Inga betalningar"}
};

const additions: Record<string, { nav:[string,string,string]; productTitle:string; productText:string; seoTitle:string; seoText:string; view:string; read:string; open:string }> = {
  en:{nav:["Home","Product details","SEO articles"],productTitle:"Featured product details",productText:"Open a real FindSpreadsheet detail page to review current images, item information and available purchase-platform links.",seoTitle:"SEO buyer articles",seoText:"Practical reading paths built around the questions buyers ask before choosing products and planning a parcel.",view:"View product details",read:"Read on FindSpreadsheet",open:"Open all products"},
  de:{nav:["Startseite","Produktdetails","SEO-Artikel"],productTitle:"Ausgewählte Produktdetails",productText:"Öffne eine echte FindSpreadsheet-Detailseite mit aktuellen Bildern, Artikeldaten und verfügbaren Plattformlinks.",seoTitle:"SEO-Kaufratgeber",seoText:"Praktische Themen für Produktauswahl, QC-Prüfung und Paketplanung.",view:"Produktdetails ansehen",read:"Auf FindSpreadsheet lesen",open:"Alle Produkte öffnen"},
  fr:{nav:["Accueil","Détails produits","Articles SEO"],productTitle:"Détails produits sélectionnés",productText:"Ouvrez une vraie fiche FindSpreadsheet pour consulter les images, informations et liens de plateformes disponibles.",seoTitle:"Articles SEO pour acheteurs",seoText:"Des sujets pratiques pour choisir un produit, contrôler le QC et planifier le colis.",view:"Voir le produit",read:"Lire sur FindSpreadsheet",open:"Voir tous les produits"},
  es:{nav:["Inicio","Detalles","Artículos SEO"],productTitle:"Detalles de productos destacados",productText:"Abre una ficha real de FindSpreadsheet para revisar imágenes, información y enlaces disponibles.",seoTitle:"Artículos SEO para compradores",seoText:"Temas prácticos sobre selección, control QC y planificación del paquete.",view:"Ver detalles",read:"Leer en FindSpreadsheet",open:"Abrir todos los productos"},
  it:{nav:["Home","Dettagli prodotti","Articoli SEO"],productTitle:"Dettagli dei prodotti in evidenza",productText:"Apri una pagina reale di FindSpreadsheet per controllare immagini, dati e link disponibili.",seoTitle:"Articoli SEO per acquirenti",seoText:"Letture pratiche per scelta, controllo QC e pianificazione del pacco.",view:"Vedi dettagli",read:"Leggi su FindSpreadsheet",open:"Apri tutti i prodotti"},
  nl:{nav:["Home","Productdetails","SEO-artikelen"],productTitle:"Uitgelichte productdetails",productText:"Open een echte FindSpreadsheet-detailpagina voor actuele afbeeldingen, informatie en beschikbare platformlinks.",seoTitle:"SEO-koopartikelen",seoText:"Praktische onderwerpen over kiezen, QC controleren en pakketten plannen.",view:"Bekijk details",read:"Lees op FindSpreadsheet",open:"Open alle producten"},
  pl:{nav:["Strona główna","Szczegóły produktów","Artykuły SEO"],productTitle:"Polecane szczegóły produktów",productText:"Otwórz prawdziwą stronę produktu FindSpreadsheet, aby sprawdzić zdjęcia, dane i dostępne linki platform.",seoTitle:"Artykuły SEO dla kupujących",seoText:"Praktyczne tematy dotyczące wyboru, kontroli QC i planowania paczki.",view:"Zobacz szczegóły",read:"Czytaj w FindSpreadsheet",open:"Otwórz wszystkie produkty"},
  pt:{nav:["Início","Detalhes","Artigos SEO"],productTitle:"Detalhes de produtos em destaque",productText:"Abra uma página real do FindSpreadsheet para rever imagens, informações e links disponíveis.",seoTitle:"Artigos SEO para compradores",seoText:"Leituras práticas sobre seleção, controlo QC e planeamento da encomenda.",view:"Ver detalhes",read:"Ler no FindSpreadsheet",open:"Abrir todos os produtos"},
  sv:{nav:["Hem","Produktdetaljer","SEO-artiklar"],productTitle:"Utvalda produktdetaljer",productText:"Öppna en riktig FindSpreadsheet-produktsida för bilder, information och tillgängliga plattformslänkar.",seoTitle:"SEO-artiklar för köpare",seoText:"Praktiska ämnen om produktval, QC-kontroll och paketplanering.",view:"Visa detaljer",read:"Läs på FindSpreadsheet",open:"Öppna alla produkter"}
};

const faqExtras: Record<string,[string,string][]> = {
  en:[["Does LoloBuy provide QC pictures?","Its public homepage advertises free quality-inspection pictures and says warehouse staff check visible defects, size and colour."],["How long is free warehouse storage?","Two current official pages conflict between 90 and 180 free-storage days. Use the countdown and price shown for the item in your live warehouse."],["Can items from different sellers be combined?","Yes. LoloBuy publicly says purchases from different sellers can arrive at its China warehouse and selected items may be submitted together as one parcel."],["Is international shipping included in the item payment?","No. The public workflow separates product price and mainland-China freight from the later international parcel payment."],["Does every buyer see the same shipping routes?","No. LoloBuy advertises around 100 logistics routes, but the options shown can depend on destination, product type, weight, dimensions and current restrictions."],["What is ShipCare?","It is an optional paid parcel-protection service. The August 2026 announcement lists loss, damage or partial loss, customs seizure and delivery delay coverages, depending on the line."],["What evidence is important after delivery?","For ShipCare damage or partial-loss claims, LoloBuy says a complete, unedited, continuous unboxing video is mandatory and the claim must be filed within three days of receipt."]],
  de:[["Stellt LoloBuy QC-Fotos bereit?","Die öffentliche Startseite wirbt mit kostenlosen Prüffotos und nennt Kontrollen auf sichtbare Mängel, Größe und Farbe."],["Wie lange ist die Lagerung kostenlos?","Zwei offizielle Seiten widersprechen sich mit 90 bzw. 180 Tagen. Maßgeblich sind Countdown und Preis im aktuellen Lagerkonto."],["Kann man Waren verschiedener Verkäufer bündeln?","Ja. Einkäufe können im China-Lager zusammengeführt und ausgewählte Artikel als ein Paket eingereicht werden."],["Ist der internationale Versand im Artikelpreis enthalten?","Nein. Warenpreis und Inlandsfracht werden vom späteren internationalen Paketversand getrennt."],["Sieht jeder dieselben Versandlinien?","Nein. LoloBuy nennt rund 100 Routen; Auswahl und Regeln hängen von Ziel, Ware, Gewicht und Abmessungen ab."],["Was ist ShipCare?","Ein optionaler kostenpflichtiger Paketschutz für Verlust, Schaden oder Teilverlust, Zollbeschlagnahme und Verzögerung – je nach Linie."],["Welche Nachweise sind nach Zustellung wichtig?","Für ShipCare-Schäden oder Teilverlust ist laut Ankündigung ein durchgehendes, unbearbeitetes Auspackvideo nötig; die Meldung muss binnen drei Tagen erfolgen."]],
  fr:[["LoloBuy fournit-il des photos QC ?","La page publique annonce des photos d’inspection gratuites et un contrôle des défauts visibles, de la taille et de la couleur."],["Combien de temps le stockage est-il gratuit ?","Deux pages officielles se contredisent entre 90 et 180 jours. Le compte à rebours et le prix affichés dans l’entrepôt font foi."],["Peut-on regrouper des articles de vendeurs différents ?","Oui. Les achats peuvent arriver à l’entrepôt chinois puis être sélectionnés dans un même colis."],["Le transport international est-il inclus dans le paiement du produit ?","Non. Le prix du produit et le transport intérieur précèdent le paiement du colis international."],["Tout le monde voit-il les mêmes lignes ?","Non. Environ 100 routes sont annoncées, mais les options dépendent du pays, du produit, du poids, du volume et des restrictions."],["Qu’est-ce que ShipCare ?","Une protection payante facultative couvrant selon la ligne la perte, les dommages, la saisie douanière et le retard."],["Quelle preuve conserver après livraison ?","Pour un dommage ou une perte partielle ShipCare, une vidéo continue et non montée du déballage est obligatoire, avec déclaration sous trois jours."]],
  es:[["¿LoloBuy ofrece fotos QC?","La página pública anuncia fotos de inspección gratuitas y revisión de defectos visibles, talla y color."],["¿Cuánto tiempo es gratuito el almacenamiento?","Dos páginas oficiales se contradicen entre 90 y 180 días. Usa la cuenta atrás y el precio que aparecen en tu almacén."],["¿Se pueden combinar artículos de distintos vendedores?","Sí. Las compras pueden llegar al almacén de China y los artículos seleccionados pueden enviarse en un solo paquete."],["¿El envío internacional está incluido en el pago del producto?","No. El precio y el envío nacional se separan del pago posterior del paquete internacional."],["¿Todos ven las mismas rutas?","No. LoloBuy anuncia unas 100 rutas, pero las opciones dependen del destino, producto, peso, volumen y restricciones."],["¿Qué es ShipCare?","Una protección opcional de pago para pérdida, daño o pérdida parcial, incautación aduanera y retraso, según la línea."],["¿Qué prueba conviene guardar?","Para daños o pérdida parcial con ShipCare se exige vídeo continuo y sin editar del desembalaje y reclamar en tres días."]],
  it:[["LoloBuy fornisce foto QC?","La pagina pubblica pubblicizza foto di controllo gratuite e verifiche di difetti visibili, taglia e colore."],["Per quanto tempo il deposito è gratuito?","Due pagine ufficiali indicano 90 e 180 giorni. Fa fede il conto alla rovescia e il prezzo mostrati nel magazzino live."],["Si possono unire articoli di venditori diversi?","Sì. Gli acquisti possono arrivare al magazzino cinese ed essere selezionati in un unico pacco."],["La spedizione internazionale è inclusa nel pagamento del prodotto?","No. Prezzo e trasporto interno sono separati dal successivo pagamento del pacco internazionale."],["Tutti vedono le stesse linee?","No. LoloBuy indica circa 100 rotte, ma le opzioni dipendono da destinazione, prodotto, peso, volume e restrizioni."],["Cos’è ShipCare?","Una protezione facoltativa a pagamento per perdita, danno o perdita parziale, sequestro doganale e ritardo, secondo la linea."],["Quale prova serve dopo la consegna?","Per danno o perdita parziale ShipCare serve un video continuo e non modificato dell’apertura e la richiesta va presentata entro tre giorni."]],
  nl:[["Levert LoloBuy QC-foto’s?","De openbare homepage vermeldt gratis inspectiefoto’s en controles op zichtbare gebreken, maat en kleur."],["Hoe lang is opslag gratis?","Twee officiële pagina’s spreken elkaar tegen met 90 en 180 dagen. Gebruik de teller en prijs in het actuele magazijnaccount."],["Kunnen artikelen van verschillende verkopers samen?","Ja. Aankopen kunnen in het Chinese magazijn aankomen en geselecteerde artikelen kunnen als één pakket worden ingediend."],["Zit internationale verzending in de artikelbetaling?","Nee. Productprijs en binnenlandse vracht staan los van de latere internationale pakketbetaling."],["Ziet iedereen dezelfde routes?","Nee. LoloBuy noemt ongeveer 100 routes; opties hangen af van bestemming, product, gewicht, formaat en beperkingen."],["Wat is ShipCare?","Een optionele betaalde bescherming voor verlies, schade of deelverlies, douane-inbeslagname en vertraging, afhankelijk van de route."],["Welk bewijs is belangrijk?","Voor ShipCare-schade of deelverlies is een volledige onbewerkte uitpakvideo vereist en moet binnen drie dagen worden geclaimd."]],
  pl:[["Czy LoloBuy udostępnia zdjęcia QC?","Publiczna strona reklamuje bezpłatne zdjęcia kontroli oraz sprawdzenie widocznych wad, rozmiaru i koloru."],["Jak długo magazyn jest bezpłatny?","Dwie oficjalne strony podają sprzecznie 90 i 180 dni. Wiążące są licznik i cena widoczne w magazynie na koncie."],["Czy można połączyć towary od różnych sprzedawców?","Tak. Zakupy mogą trafić do magazynu w Chinach, a wybrane produkty można wysłać jako jedną paczkę."],["Czy wysyłka międzynarodowa jest w cenie produktu?","Nie. Cena i transport krajowy są oddzielone od późniejszej opłaty za paczkę międzynarodową."],["Czy każdy widzi te same trasy?","Nie. LoloBuy podaje około 100 tras, ale opcje zależą od kraju, produktu, wagi, wymiarów i ograniczeń."],["Czym jest ShipCare?","Opcjonalną płatną ochroną od utraty, uszkodzenia lub częściowej utraty, zajęcia celnego i opóźnienia – zależnie od trasy."],["Jaki dowód zachować po dostawie?","Przy szkodzie lub częściowej utracie ShipCare wymagane jest ciągłe, nieedytowane nagranie otwierania i zgłoszenie w ciągu trzech dni."]],
  pt:[["A LoloBuy fornece fotos QC?","A página pública anuncia fotos de inspeção gratuitas e verificação de defeitos visíveis, tamanho e cor."],["Quanto tempo o armazenamento é gratuito?","Duas páginas oficiais divergem entre 90 e 180 dias. Use a contagem e o preço mostrados no armazém da conta."],["É possível juntar artigos de vendedores diferentes?","Sim. As compras podem chegar ao armazém chinês e os artigos escolhidos podem seguir num único pacote."],["O envio internacional está incluído no pagamento do produto?","Não. O preço e o frete doméstico são separados do pagamento posterior do pacote internacional."],["Todos veem as mesmas rotas?","Não. A LoloBuy anuncia cerca de 100 rotas, mas as opções dependem do destino, produto, peso, dimensões e restrições."],["O que é ShipCare?","Uma proteção opcional paga para perda, dano ou perda parcial, apreensão alfandegária e atraso, conforme a linha."],["Que prova guardar após a entrega?","Para dano ou perda parcial ShipCare é obrigatório vídeo contínuo e não editado da abertura e reclamar em três dias."]],
  sv:[["Ger LoloBuy QC-bilder?","Den offentliga startsidan annonserar gratis inspektionsbilder och kontroll av synliga fel, storlek och färg."],["Hur länge är lagring gratis?","Två officiella sidor motsäger varandra med 90 och 180 dagar. Använd nedräkningen och priset i det aktiva lagerkontot."],["Kan varor från olika säljare samfraktas?","Ja. Köp kan anlända till lagret i Kina och valda varor kan lämnas in som ett paket."],["Ingår internationell frakt i produktbetalningen?","Nej. Produktpris och inrikesfrakt är separata från den senare internationella paketbetalningen."],["Ser alla samma rutter?","Nej. LoloBuy anger omkring 100 rutter, men valen beror på land, produkt, vikt, mått och begränsningar."],["Vad är ShipCare?","Ett frivilligt betalt skydd för förlust, skada eller delförlust, tullbeslag och försening beroende på rutt."],["Vilket bevis behövs efter leverans?","För ShipCare-skada eller delförlust krävs en obruten, oredigerad uppackningsvideo och anmälan inom tre dagar."]]
};

const articleLabels: Record<string,string> = {en:"Read full article",de:"Vollständigen Artikel lesen",fr:"Lire l’article complet",es:"Leer el artículo completo",it:"Leggi l’articolo completo",nl:"Lees het volledige artikel",pl:"Przeczytaj cały artykuł",pt:"Ler o artigo completo",sv:"Läs hela artikeln"};

const cats = [
  ["Sneakers","Footwear","https://findspreadsheet.com/shoes/"],
  ["Hoodies","Sweatshirts","https://findspreadsheet.com/hoodies-sweaters/"],
  ["T-Shirts","Tops","https://findspreadsheet.com/t-shirts/"],
  ["Jackets","Outerwear","https://findspreadsheet.com/jackets/"],
  ["Pants","Bottoms","https://findspreadsheet.com/pants-shorts/"],
  ["Bags","Carry","https://findspreadsheet.com/search.html?keywords=bags"],
  ["Watches","Accessories","https://findspreadsheet.com/search.html?keywords=watches"],
  ["Jewelry","Details","https://findspreadsheet.com/search.html?keywords=jewelry"],
  ["Electronics","Tech","https://findspreadsheet.com/electronics/"],
  ["Home","Lifestyle","https://findspreadsheet.com/other-stuff/"]
];
const guides = [["QC photos: what to inspect before approval","Shape, measurements, colour, stitching and visible defects."],["Real weight vs volumetric weight","Why a light but bulky parcel can still cost more to ship."],["How to read a product row","Separate live listing facts from notes, estimates and old screenshots."]];
const guideDetails = [
  {id:"guide-qc-photos",title:"QC photos: a practical inspection order",intro:"Review the complete photo set before approving a warehouse item. Start with the overall shape, then compare the selected size and visible construction details.",points:["Confirm colour, silhouette and the selected variant","Compare measurements with the product page and your expected fit","Zoom in on seams, logos, hardware, soles and visible marks","Request another angle when a key area is hidden or unclear"]},
  {id:"guide-parcel-weight",title:"Real weight and volumetric weight explained",intro:"Carriers may charge for the space a parcel occupies instead of only its scale weight. Bulky shoes, jackets and protective packaging can therefore change the final estimate.",points:["Check packed dimensions as well as actual weight","Compare available routes for the destination country","Consider removing unnecessary packaging only when protection is not affected","Recheck restrictions, insurance and tax handling before submission"]},
  {id:"guide-product-row",title:"How to verify a product row",intro:"Treat every spreadsheet row as a discovery lead. The live destination page is the place to confirm the latest title, images, options, seller information and availability.",points:["Open the live product-detail page before making a decision","Match the item ID, selected option and displayed images","Separate verified listing facts from notes or estimates","Search again when a link is old, unavailable or no longer matches"]}
];
const products = [
  ["Balenciaga 3.0 shoes","Shoes","https://findspreadsheet.com/shoes/balenciaga-3-0-shoes-2831.html","01"],
  ["Valentino tees","T-Shirts","https://findspreadsheet.com/t-shirts/valentino-tees-2994.html","02"],
  ["The North Face Outdoorjacket","Jackets","https://findspreadsheet.com/jackets/the-north-face-outdoorjacket-2998.html","03"],
  ["Supreme Wallet","Accessories","https://findspreadsheet.com/accessories/supreme-wallet-2995.html","04"],
  ["Gallery Short","Pants / Shorts","https://findspreadsheet.com/pants-shorts/gallery-short-3003.html","05"]
];
const seoCards = [
  ["LoloBuy fees and budget guide","Product payment, China delivery, storage, chargeable weight and real-cost planning","/articles/lolobuy-fees-budget-guide"],
  ["How LoloBuy works for international buyers","Ordering, China warehouse intake, QC and parcel submission","/articles/how-lolobuy-works"],
  ["LoloBuy QC photo checklist","A practical inspection order for size, colour and visible defects","/articles/lolobuy-qc-photo-checklist"],
  ["LoloBuy shipping and ShipCare guide","Parcel weight, route checks, protection facts and claim evidence","/articles/lolobuy-shipping-guide"]
];

export default function SiteExperience({initialLang}:{initialLang:string}) {
  const [lang,setLang]=useState(locales[initialLang]?initialLang:"en");
  const [query,setQuery]=useState(""); const t=locales[lang]; const x=additions[lang]; const faqs=[...t.questions,...faqExtras[lang]];
  const find=(term:string)=>`https://findspreadsheet.com/search.html?keywords=${encodeURIComponent(term)}`;
  const page=(path:string)=>lang==="en"?path:`/${lang}${path==="/"?"":path}`;
  const selectLang=(value:string)=>{setLang(value); history.replaceState({},"",value==="en"?"/":`/${value}`); document.documentElement.lang=value;};
  return <main>
    <header className="topbar"><a className="brand logoBrand" href={page("/")}><img src="/lolobuy-logo.png" alt="LoloBuy"/></a><nav><a href={page("/")}>{x.nav[0]}</a><a href={page("/products")}>{t.nav[0]}</a><a href={page("/product-details")}>{x.nav[1]}</a><a href={page("/how-it-works")}>{t.nav[1]}</a><a href={page("/qc-checklist")}>{t.nav[2]}</a><a href={page("/guides")}>{t.nav[4]}</a><a href={page("/faq")}>{t.nav[5]}</a><a href={page("/articles")}>{x.nav[2]}</a></nav><select aria-label="Language" value={lang} onChange={e=>selectLang(e.target.value)}>{Object.entries(locales).map(([code,c])=><option key={code} value={code}>{c.name}</option>)}</select></header>
    <section className="hero" id="top"><div className="heroCopy"><p className="eyebrow"><span/>{t.badge}</p><h1>{t.title}<br/><em>{t.accent}</em></h1><p className="lede">{t.intro}</p><form className="search" onSubmit={e=>{e.preventDefault();location.href=find(query||"LoloBuy")}}><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search}/><button>{t.go} <b>↗</b></button></form><a className="databaseLink" href="https://findspreadsheet.com/">{tr(lang,"Browse product database")} <b>↗</b></a><p className="popular">{t.popular}</p><div className="stats"><span><b>9</b>{tr(lang,"languages")}</span><span><b>10</b>{tr(lang,"categories")}</span><span><b>✓</b>{tr(lang,"buyer checks")}</span></div></div><div className="heroVisual"><div><span>{tr(lang,"CURATED DISCOVERY")}</span><b>{tr(lang,"Compare first.")}<br/>{tr(lang,"Buy informed.")}</b></div></div></section>
    <section className="section" id="categories"><div className="sectionHead"><div><p className="kicker">01 · {tr(lang,"DIRECTORY")}</p><h2>{t.cats}</h2></div><p>{t.catsText}</p></div><div className="categoryGrid">{cats.map(([name,sub,url],i)=><a key={name} href={url} className="category"><span>{String(i+1).padStart(2,"0")}</span><div><b>{tr(lang,name)}</b><small>{tr(lang,sub)}</small></div><i>↗</i></a>)}</div></section>
    <section className="productSection section" id="product-details"><div className="sectionHead"><div><p className="kicker">02 · {tr(lang,"PRODUCT DETAILS")}</p><h2>{x.productTitle}</h2></div><p>{x.productText}</p></div><div className="productGrid">{products.map(([name,category,url,no])=><a href={url} className="productCard" key={name}><div className="productArt"><span>{no}</span><b>{tr(lang,category)}</b></div><small>{tr(lang,category)}</small><h3>{name}</h3><p>{x.view} <b>↗</b></p></a>)}</div><a className="allProducts" href="https://findspreadsheet.com/AllProducts/">{x.open} <b>↗</b></a></section>
    <section className="workflow section" id="workflow"><p className="kicker">03 · {tr(lang,"WORKFLOW")}</p><h2>{t.flow}</h2><div className="steps">{t.steps.map(([a,b],i)=><article key={a}><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></article>)}</div></section>
    <section className="split section"><article id="qc"><p className="kicker">04 · {tr(lang,"QUALITY CONTROL")}</p><h2>{t.qc}</h2><p>{t.qcText}</p><ul><li>{tr(lang,"Overall shape & colour")}</li><li>{tr(lang,"Measurements & selected size")}</li><li>{tr(lang,"Stitching, hardware & visible defects")}</li><li>{tr(lang,"Requested angles and packaging")}</li></ul></article><article id="shipping"><p className="kicker">05 · {tr(lang,"PARCEL PLANNING")}</p><h2>{t.ship}</h2><p>{t.shipText}</p><div className="weight"><span>{tr(lang,"Actual weight")}</span><b>vs</b><span>{tr(lang,"Volumetric size")}</span></div></article></section>
    <section className="section" id="guides"><div className="sectionHead"><div><p className="kicker">06 · {tr(lang,"LEARN")}</p><h2>{t.guides}</h2></div><p>{t.guidesText}</p></div><div className="guideGrid">{guides.map(([a,b],i)=><article key={a}><span>{tr(lang,"Guide")} 0{i+1}</span><h3>{tr(lang,a)}</h3><p>{tr(lang,b)}</p><a href={`#${guideDetails[i].id}`}>{tr(lang,"Read guide")} <b>↓</b></a></article>)}</div><div className="guideDetails">{guideDetails.map((guide,i)=><article id={guide.id} key={guide.id}><span>{tr(lang,"Guide")} 0{i+1}</span><div><h3>{tr(lang,guide.title)}</h3><p>{tr(lang,guide.intro)}</p><ul>{guide.points.map(point=><li key={point}>{tr(lang,point)}</li>)}</ul><a href="https://findspreadsheet.com/">{tr(lang,"Open the product database")} <b>↗</b></a></div></article>)}</div></section>
    <section className="faq section" id="faq"><p className="kicker">07 · {tr(lang,"FAQ")}</p><h2>{t.faq}</h2>{faqs.map(([q,a],i)=><details key={q} open={i===0}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</section>
    <section className="seoSection section" id="seo-articles"><div className="sectionHead"><div><p className="kicker">08 · {tr(lang,"SEO ARTICLES")}</p><h2>{x.seoTitle}</h2></div><p>{x.seoText}</p></div><div className="seoGrid">{seoCards.map(([title,desc,url],i)=><a href={page(url)} key={title}><span>0{i+1}</span><div><h3>{tr(lang,title)}</h3><p>{tr(lang,desc)}</p><b>{articleLabels[lang]} ↗</b></div></a>)}</div></section>
    <section className="cta"><div><p className="kicker">FINDSPREADSHEET.COM</p><h2>{t.cta}</h2><p>{t.ctaText}</p></div><a href="https://findspreadsheet.com/">{x.open} <span>↗</span></a></section>
    <footer><div className="brand footerLogo"><img src="/lolobuy-logo.png" alt="LoloBuy"/></div><p>{t.footer}</p><p>© 2026</p></footer>
  </main>
}
