import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { CategoryVisualGrid, PageShell } from "../../components";
import { languages, products } from "../../data";
import { localeCopy } from "../../localeCopy";
import { localizedContent } from "../../localizedContent";
import { localizedSiteContent } from "../../localizedSiteContent";
import { routeCopy } from "../../routeCopy";
import ResponsiveDetails from "../../ResponsiveDetails";
import SearchRedirect from "../../SearchRedirect";

export function generateStaticParams(){return languages.map(language=>({lang:language.code}));}
export async function generateMetadata({params}:{params:Promise<{lang:string}>}):Promise<Metadata>{const {lang}=await params;const language=languages.find(item=>item.code===lang);if(!language)return{};return{title:`${language.name} LoloBuy Research`,description:language.intro,alternates:{canonical:`/languages/${language.code}`,languages:Object.fromEntries([["x-default","/"],...languages.map(item=>[item.code,`/languages/${item.code}`])])}}}

export default async function LanguagePage({params}:{params:Promise<{lang:string}>}){
  const {lang}=await params;
  const language=languages.find(item=>item.code===lang);
  const copy=localeCopy[lang],labels=routeCopy[lang],site=localizedSiteContent[lang],content=localizedContent[lang];
  if(!language||!copy||!labels||!site||!content)notFound();
  const root=`/languages/${lang}`,home=site.text.home;
  const categoryNames=Object.fromEntries(site.categories.map(item=>[item.slug,item.name]));
  const productNames=Object.fromEntries(site.products.map(item=>[item.slug,item.name]));
  const localizedProducts=products.map(item=>({...item,...site.products.find(product=>product.slug===item.slug)}));
  const article=(slug:string)=>content.articles.find(item=>item.slug===slug)!;
  return <PageShell lang={lang}>
    <section className="hero"><div className="hero__copy"><p className="eyebrow">{language.name} · {labels.research}</p><h1>{language.title}</h1><p className="hero__lead">{language.intro}</p><SearchRedirect lang={lang} categoryNames={categoryNames} productNames={productNames}/><div className="hero__trust"><span>01 · {labels.verified}</span><span>02 · {home.usdReference}</span><span>03 · {labels.research}</span></div></div><div className="hero__panel"><div className="panel-head"><span>{labels.fullContent.toUpperCase()}</span><span className="live-dot">● {home.liveCheck.toUpperCase()}</span></div><div className="panel-grid"><a href={`${root}/guides`}><small>{labels.guides.toUpperCase()}</small><strong>{home.productWorkflow}</strong><p>{language.intro}</p></a><a href={`${root}/qc-guide`}><small>{labels.qc.toUpperCase()}</small><strong>{home.inspectionPhotos}</strong><p>{home.visibleEvidence}</p></a><a href={`${root}/shipping`}><small>{labels.shipping.toUpperCase()}</small><strong>{home.checkRoutes}</strong><p>{home.routeFactors}</p></a><a href={`${root}/articles`}><small>SEO</small><strong>{copy.articlesTitle}</strong><p>{copy.articlesIntro}</p></a></div><a className="panel-link" href={`${root}/sources`}>{labels.sources} <span>→</span></a></div></section>
    <section className="proof-strip"><span><b>✓</b> {home.factsAdvice}</span><span><b>✓</b> {home.recheck}</span><span><b>✓</b> {home.noPromises}</span><span><b>✓</b> {home.disclosure}</span></section>
    <section className="home-hubs"><a href={`${root}/categories`}><span>01 · {home.directory.toUpperCase()}</span><h2>{labels.categories}</h2><p>{home.categoryHub}</p><b>{labels.open} →</b></a><a href={`${root}/products`}><span>02 · {home.details.toUpperCase()}</span><h2>{labels.products}</h2><p>{home.productHub}</p><b>{labels.open} →</b></a><a href={`${root}/faq`}><span>03 · {home.answers.toUpperCase()}</span><h2>{copy.faqTitle}</h2><p>{copy.faqIntro}</p><b>{copy.read} →</b></a></section>
    <ResponsiveDetails number="01" title={labels.categories}><section className="section category-showcase"><div className="section-head"><div><p className="eyebrow">{language.cta}</p><h2>{labels.categories}</h2></div><p>{language.intro}</p></div><CategoryVisualGrid lang={lang}/></section></ResponsiveDetails>
    <ResponsiveDetails number="02" title={labels.products}><section className="section section--ink"><div className="section-head section-head--light"><div><p className="eyebrow">{labels.products}</p><h2>{home.usefulFinds}</h2></div><p>{home.priceContext}</p></div><div className="product-grid">{localizedProducts.map(product=><a className="product-card" href={`${root}/products/${product.slug}`} key={product.slug}><div className="product-card__image"><img src={product.image} alt={product.name}/><span>{labels.open.toUpperCase()} →</span></div><div className="product-card__body"><p>{product.category}</p><h3>{product.name}</h3><div><strong>{product.usd}</strong><small>{product.cny.replace(" reference price","")}</small></div></div></a>)}</div><a className="text-link text-link--light" href={`${root}/products`}>{labels.products} →</a></section></ResponsiveDetails>
    <ResponsiveDetails number="03" title={labels.guides}><section className="section workflow"><div className="section-head"><div><p className="eyebrow">{labels.fullContent}</p><h2>{home.workflowTitle}</h2></div><a className="text-link" href={`${root}/guides`}>{labels.guides} →</a></div><div className="steps"><article><span>01</span><h3>{home.findCompare}</h3><p>{home.findCompareText}</p><a href={`${root}/categories`}>{labels.categories} →</a></article><article><span>02</span><h3>{home.submitLink}</h3><p>{home.submitLinkText}</p><a href={`${root}/guides`}>{labels.guides} →</a></article><article><span>03</span><h3>{home.reviewQc}</h3><p>{home.reviewQcText}</p><a href={`${root}/qc-guide`}>{labels.qc} →</a></article><article><span>04</span><h3>{home.chooseShipping}</h3><p>{home.chooseShippingText}</p><a href={`${root}/shipping`}>{labels.shipping} →</a></article></div></section></ResponsiveDetails>
    <ResponsiveDetails number="04" title={labels.research}><section className="section country-section"><div className="country-copy"><p className="eyebrow">{labels.research}</p><h2>{language.title}</h2><p>{language.intro}</p><a className="text-link" href={`${root}/research`}>{labels.research} →</a></div><div className="country-board"><div className="country-board__head"><span>{home.priorityDestinations.toUpperCase()}</span><span>{home.regionSignal.toUpperCase()}</span></div><div className="country-chips">{site.hotCountries.map((country,index)=><span key={country}><b>{String(index+1).padStart(2,"0")}</b>{country}</span>)}</div><p>{home.regionNote}</p></div></section></ResponsiveDetails>
    <ResponsiveDetails number="05" title={labels.articles}><section className="section editorial"><div className="section-head"><div><p className="eyebrow">SEO</p><h2>{copy.articlesTitle}</h2></div><p>{copy.articlesIntro}</p></div><div className="editorial-grid"><a href={`${root}/articles/lolobuy-qc-photos-guide`}><span>01 · QC</span><h3>{article("lolobuy-qc-photos-guide").title}</h3><p>{home.longGuide}</p><b>{copy.read} →</b></a><a href={`${root}/articles/lolobuy-shipping-cost-guide`}><span>02 · {article("lolobuy-shipping-cost-guide").tag}</span><h3>{article("lolobuy-shipping-cost-guide").title}</h3><p>{home.shippingGuide}</p><b>{copy.read} →</b></a><a href={`${root}/articles/how-to-use-a-lolobuy-spreadsheet`}><span>03 · {article("how-to-use-a-lolobuy-spreadsheet").tag}</span><h3>{article("how-to-use-a-lolobuy-spreadsheet").title}</h3><p>{home.beginnerGuide}</p><b>{copy.read} →</b></a></div></section></ResponsiveDetails>
    <ResponsiveDetails number="06" title={labels.faq}><section className="faq section"><div><p className="eyebrow">FAQ</p><h2>{copy.faqTitle}</h2><p>{copy.faqIntro}</p><a className="text-link" href={`${root}/faq`}>{copy.read} →</a></div><div className="faq-list">{content.faqs.slice(0,4).map(faq=><a className="faq-card" href={`${root}/faq/${faq.slug}`} key={faq.slug}><div><h3>{faq.question}</h3><p>{faq.short}</p></div><span>→</span></a>)}</div></section></ResponsiveDetails>
    <section className="final-cta"><p>{labels.fullContent.toUpperCase()}</p><h2>{language.title}</h2><div><a href="https://findspreadsheet.com/AllProducts/" target="_blank" rel="noopener">FindSpreadsheet ↗</a><a href={`${root}/guides`}>{labels.guides} →</a></div></section>
  </PageShell>;
}
