if(!window.__USFANSSS_LANGUAGE_RENDERER__){
const categoryKeywords={Outerwear:'Jacket',Headwear:'Hats',Accessories:'Jewelry',Electronics:'Headphones'};
const searchUrl=q=>'https://findspreadsheet.com/search.html?keywords='+encodeURIComponent(categoryKeywords[q]||q)+'&channelid=2';
const current=location.pathname.split('/').pop()||'index.html';
const nav=[['index.html','Home'],['category.html','Categories'],['product-details.html','Product details'],['seo-articles.html','SEO articles'],['faq.html','FAQ'],['https://findspreadsheet.com','FindSpreadsheet database']];
const header=document.querySelector('#site-header');
if(header){header.innerHTML=`<header class="rail"><a class="logo" href="index.html" aria-label="USFANSSS home"><img src="usfans-logo.webp" alt="USFans"></a><div class="kicker">CURATED FASHION / 2026</div><nav>${nav.map(([u,l])=>`<a class="${current===u?'active':''}" href="${u}">${l}</a>`).join('')}</nav><div class="lang"><button id="lang">LANG / EN</button><div class="langs" id="langs"></div></div></header>`;const langs=[['EN','English'],['PL','Polski'],['IT','Italiano'],['ES','Español'],['DE','Deutsch'],['FR','Français'],['PT','Português'],['NL','Nederlands']],box=document.querySelector('#langs'),button=document.querySelector('#lang');box.innerHTML=langs.map(x=>`<button data-l="${x[0]}">${x[1]}</button>`).join('');button.onclick=()=>box.classList.toggle('open');box.onclick=e=>{if(e.target.dataset.l){button.textContent='LANG / '+e.target.dataset.l;box.classList.remove('open')}}}
const categories=[['👟','Sneakers'],['🧥','Outerwear'],['👕','T-Shirts'],['🧶','Hoodies'],['👖','Pants + Shorts'],['👜','Bags'],['⌚','Watches'],['🧢','Headwear'],['💍','Accessories'],['🎧','Electronics']];
const products=[['Sneakers','Trail Runner / orange trim','$48.97'],['Hoodies','Zip hoodie / black','$45.98'],['T-Shirts','Heavyweight tee / ivory','$42.40'],['Outerwear','Technical jacket / black','$90.48'],['Pants + Shorts','Utility cargo trousers','$58.60'],['Bags','Leather crossbody bag','$68.71'],['Watches','Steel watch / black dial','$168.71'],['Headwear','Classic black cap','$22.90'],['Accessories','Angular sunglasses','$31.85'],['Accessories','Silver link chain','$27.40'],['Electronics','Wireless headphones','$138.85'],['Bags','Compact technical backpack','$72.50']];
const grid=document.querySelector('#product-grid');if(grid)grid.innerHTML=products.map((p,i)=>`<a class="product" href="product.html?id=${i}"><div class="product-visual p${i}"></div><div class="product-copy"><small>${p[0].toUpperCase()} / CURATED</small><h2>${p[1]}</h2><div class="product-bottom"><span class="price">${p[2]} USD</span><span>VIEW DETAILS ↗</span></div></div></a>`).join('');
const categoryPage=document.querySelector('#category-page');if(categoryPage){const cat=new URLSearchParams(location.search).get('category')||'All categories';document.querySelector('#category-name').textContent=cat;document.querySelector('#category-copy').textContent=cat==='All categories'?'Choose a category to open its matching FindSpreadsheet result directly.':`Explore ${cat.toLowerCase()} through the main FindSpreadsheet database. Compare individual listings, selected options and available product references before making a choice.`;document.querySelector('#category-link').href=cat==='All categories'?'#category-grid':searchUrl(cat);const cg=document.querySelector('#category-grid');cg.innerHTML=categories.map(c=>`<a class="category-tile" href="${searchUrl(c[1])}"><span>FIND</span><i>${c[0]}</i><b>${c[1]}</b><small>Browse category →</small></a>`).join('')}
const productPage=document.querySelector('#product-page');if(productPage){const id=Math.max(0,Math.min(products.length-1,Number(new URLSearchParams(location.search).get('id'))||0)),p=products[id];document.querySelector('#product-image').className=`product-page-image p${id}`;document.querySelector('#product-category').textContent=p[0].toUpperCase()+' / CURATED';document.querySelector('#product-name').textContent=p[1];document.querySelector('#product-price').textContent=p[2]+' USD';document.querySelector('#product-link').href=searchUrl(p[0])}
}
