import { faqItems } from "./data";
import { getShippingCopy } from "./shipping-copy";

export type LocalizedContent = {
  researchSnapshot: string; faqTitle: string; faqIntro: string; allFaq: string;
  guide: string; researchBasis: string; scopeTitle: string; scopeText: string;
  open: string; close: string; factCheckedHelp: string; categories: readonly string[];
};

const en: LocalizedContent = {
  researchSnapshot: "Research snapshot", faqTitle: "PikoBuy FAQ", faqIntro: "Answers checked against PikoBuy's published guide and policies.", allFaq: "All FAQ answers",
  guide: "guide", researchBasis: "Research basis · reviewed 19 August 2026", scopeTitle: "Scope and limitations", scopeText: "These answers summarize published rules; eligibility, fees, routes and wording can change. Warehouse photos document visible condition but do not authenticate a product or guarantee hidden quality.",
  open: "Open +", close: "Close −", factCheckedHelp: "Fact-checked PikoBuy help",
  categories: ["Shoes","Sneakers","T-Shirts","Hoodies","Jackets","Pants & Shorts","Headwear","Short Sets","Accessories","Jerseys","Electronics","Other Finds"],
};

const rows: Record<string, readonly [string,string,string,string,string,string,string,string,string,string,string,string]> = {
  "de-DE":["Forschungsüberblick","PikoBuy FAQ","Geprüfte Antworten auf Grundlage der veröffentlichten PikoBuy-Leitfäden und Richtlinien.","Alle FAQ-Antworten","Ratgeber","Recherchegrundlage · geprüft am 19. August 2026","Umfang und Grenzen","Diese Antworten fassen veröffentlichte Regeln zusammen; Berechtigung, Gebühren, Routen und Formulierungen können sich ändern. Lagerfotos zeigen den sichtbaren Zustand, bestätigen aber weder Echtheit noch verborgene Qualität.","Öffnen +","Schließen −","Faktengeprüfte PikoBuy-Hilfe","Schuhe|Sneaker|T-Shirts|Hoodies|Jacken|Hosen & Shorts|Kopfbedeckungen|Short-Sets|Accessoires|Trikots|Elektronik|Weitere Funde"],
  "fr-FR":["Aperçu de la recherche","FAQ PikoBuy","Réponses vérifiées à partir des guides et politiques publiés par PikoBuy.","Toutes les réponses FAQ","guide","Base de recherche · vérifiée le 19 août 2026","Portée et limites","Ces réponses résument les règles publiées ; l'éligibilité, les frais, les itinéraires et le texte peuvent changer. Les photos d'entrepôt montrent l'état visible sans authentifier le produit ni garantir sa qualité cachée.","Ouvrir +","Fermer −","Aide PikoBuy vérifiée","Chaussures|Baskets|T-shirts|Sweats à capuche|Vestes|Pantalons et shorts|Couvre-chefs|Ensembles courts|Accessoires|Maillots|Électronique|Autres trouvailles"],
  "es-ES":["Resumen de la investigación","Preguntas frecuentes de PikoBuy","Respuestas verificadas con las guías y políticas publicadas por PikoBuy.","Todas las respuestas","guía","Base de investigación · revisada el 19 de agosto de 2026","Alcance y limitaciones","Estas respuestas resumen reglas publicadas; los requisitos, cargos, rutas y textos pueden cambiar. Las fotos del almacén muestran el estado visible, pero no autentican el producto ni garantizan su calidad interna.","Abrir +","Cerrar −","Ayuda verificada sobre PikoBuy","Zapatos|Zapatillas|Camisetas|Sudaderas con capucha|Chaquetas|Pantalones y shorts|Gorras y sombreros|Conjuntos cortos|Accesorios|Camisetas deportivas|Electrónica|Otros hallazgos"],
  "it-IT":["Sintesi della ricerca","FAQ PikoBuy","Risposte verificate sulle guide e politiche pubblicate da PikoBuy.","Tutte le risposte FAQ","guida","Base della ricerca · verificata il 19 agosto 2026","Ambito e limiti","Queste risposte riassumono le regole pubblicate; idoneità, costi, rotte e formulazioni possono cambiare. Le foto di magazzino mostrano la condizione visibile, ma non autenticano il prodotto né garantiscono la qualità nascosta.","Apri +","Chiudi −","Assistenza PikoBuy verificata","Scarpe|Sneakers|T-shirt|Felpe con cappuccio|Giacche|Pantaloni e shorts|Copricapi|Completi corti|Accessori|Maglie sportive|Elettronica|Altri prodotti"],
  "nl-NL":["Onderzoeksoverzicht","PikoBuy-FAQ","Gecontroleerde antwoorden op basis van gepubliceerde PikoBuy-gidsen en beleidsregels.","Alle FAQ-antwoorden","gids","Onderzoeksbasis · gecontroleerd op 19 augustus 2026","Reikwijdte en beperkingen","Deze antwoorden vatten gepubliceerde regels samen; geschiktheid, kosten, routes en formuleringen kunnen veranderen. Magazijnfoto's tonen zichtbare staat, maar bewijzen geen echtheid of verborgen kwaliteit.","Openen +","Sluiten −","Gecontroleerde PikoBuy-hulp","Schoenen|Sneakers|T-shirts|Hoodies|Jassen|Broeken en shorts|Hoofddeksels|Korte sets|Accessoires|Sportshirts|Elektronica|Andere vondsten"],
  "pl-PL":["Podsumowanie badań","FAQ PikoBuy","Zweryfikowane odpowiedzi na podstawie opublikowanych poradników i zasad PikoBuy.","Wszystkie odpowiedzi FAQ","poradnik","Podstawa badania · sprawdzono 19 sierpnia 2026","Zakres i ograniczenia","Odpowiedzi podsumowują opublikowane zasady; uprawnienia, opłaty, trasy i treść mogą się zmieniać. Zdjęcia magazynowe pokazują widoczny stan, lecz nie potwierdzają autentyczności ani ukrytej jakości.","Otwórz +","Zamknij −","Zweryfikowana pomoc PikoBuy","Buty|Sneakersy|T-shirty|Bluzy z kapturem|Kurtki|Spodnie i szorty|Nakrycia głowy|Krótkie zestawy|Akcesoria|Koszulki sportowe|Elektronika|Inne znaleziska"],
  "pt-PT":["Resumo da pesquisa","Perguntas frequentes PikoBuy","Respostas verificadas com base nos guias e políticas publicados pelo PikoBuy.","Todas as respostas FAQ","guia","Base da pesquisa · revista em 19 de agosto de 2026","Âmbito e limitações","Estas respostas resumem regras publicadas; elegibilidade, taxas, rotas e redação podem mudar. As fotos do armazém mostram a condição visível, mas não autenticam o produto nem garantem qualidade oculta.","Abrir +","Fechar −","Ajuda PikoBuy verificada","Sapatos|Sapatilhas|T-shirts|Hoodies|Casacos|Calças e calções|Chapéus e bonés|Conjuntos curtos|Acessórios|Camisolas desportivas|Eletrónica|Outros achados"],
  "pt-BR":["Resumo da pesquisa","Perguntas frequentes PikoBuy","Respostas verificadas com base nos guias e políticas publicados pela PikoBuy.","Todas as respostas FAQ","guia","Base da pesquisa · revisada em 19 de agosto de 2026","Escopo e limitações","Estas respostas resumem regras publicadas; elegibilidade, taxas, rotas e redação podem mudar. As fotos do armazém mostram a condição visível, mas não autenticam o produto nem garantem qualidade oculta.","Abrir +","Fechar −","Ajuda PikoBuy verificada","Sapatos|Tênis|Camisetas|Moletons|Jaquetas|Calças e shorts|Bonés e chapéus|Conjuntos curtos|Acessórios|Camisas esportivas|Eletrônicos|Outros achados"],
  "sv-SE":["Forskningsöversikt","PikoBuy FAQ","Faktagranskade svar baserade på PikoBuys publicerade guider och policyer.","Alla FAQ-svar","guide","Forskningsunderlag · granskat 19 augusti 2026","Omfattning och begränsningar","Svaren sammanfattar publicerade regler; behörighet, avgifter, rutter och formuleringar kan ändras. Lagerfoton visar synligt skick men bevisar inte äkthet eller dold kvalitet.","Öppna +","Stäng −","Faktagranskad PikoBuy-hjälp","Skor|Sneakers|T-shirts|Hoodies|Jackor|Byxor och shorts|Huvudbonader|Korta set|Accessoarer|Matchtröjor|Elektronik|Övriga fynd"],
  "da-DK":["Forskningsoversigt","PikoBuy FAQ","Faktatjekkede svar baseret på PikoBuys offentliggjorte vejledninger og politikker.","Alle FAQ-svar","vejledning","Forskningsgrundlag · gennemgået 19. august 2026","Omfang og begrænsninger","Svarene opsummerer offentliggjorte regler; berettigelse, gebyrer, ruter og formulering kan ændres. Lagerfotos viser synlig tilstand, men beviser ikke ægthed eller skjult kvalitet.","Åbn +","Luk −","Faktatjekket PikoBuy-hjælp","Sko|Sneakers|T-shirts|Hoodies|Jakker|Bukser og shorts|Hovedbeklædning|Korte sæt|Tilbehør|Trøjer|Elektronik|Andre fund"],
  "nb-NO":["Forskningsoversikt","PikoBuy FAQ","Faktasjekkede svar basert på PikoBuys publiserte veiledninger og retningslinjer.","Alle FAQ-svar","veiledning","Forskningsgrunnlag · gjennomgått 19. august 2026","Omfang og begrensninger","Svarene oppsummerer publiserte regler; kvalifisering, gebyrer, ruter og ordlyd kan endres. Lagerbilder viser synlig tilstand, men beviser ikke ekthet eller skjult kvalitet.","Åpne +","Lukk −","Faktasjekket PikoBuy-hjelp","Sko|Sneakers|T-skjorter|Hettegensere|Jakker|Bukser og shorts|Hodeplagg|Korte sett|Tilbehør|Drakter|Elektronikk|Andre funn"],
  "fi-FI":["Tutkimusyhteenveto","PikoBuy UKK","Tarkistetut vastaukset PikoBuyn julkaistujen oppaiden ja käytäntöjen perusteella.","Kaikki UKK-vastaukset","opas","Tutkimusperusta · tarkistettu 19. elokuuta 2026","Laajuus ja rajoitukset","Vastaukset tiivistävät julkaistut säännöt; kelpoisuus, maksut, reitit ja sanamuodot voivat muuttua. Varastokuvat näyttävät näkyvän kunnon, mutta eivät todista aitoutta tai piilevää laatua.","Avaa +","Sulje −","Tarkistettu PikoBuy-ohje","Kengät|Lenkkarit|T-paidat|Hupparit|Takit|Housut ja shortsit|Päähineet|Lyhyet setit|Asusteet|Pelipaidat|Elektroniikka|Muut löydöt"],
  "cs-CZ":["Přehled výzkumu","PikoBuy FAQ","Ověřené odpovědi podle zveřejněných průvodců a pravidel PikoBuy.","Všechny odpovědi FAQ","průvodce","Základ výzkumu · ověřeno 19. srpna 2026","Rozsah a omezení","Odpovědi shrnují zveřejněná pravidla; způsobilost, poplatky, trasy a znění se mohou měnit. Skladové fotografie ukazují viditelný stav, ale nepotvrzují pravost ani skrytou kvalitu.","Otevřít +","Zavřít −","Ověřená pomoc PikoBuy","Boty|Tenisky|Trička|Mikiny s kapucí|Bundy|Kalhoty a šortky|Pokrývky hlavy|Krátké soupravy|Doplňky|Dresy|Elektronika|Další nálezy"],
  "ro-RO":["Rezumatul cercetării","Întrebări frecvente PikoBuy","Răspunsuri verificate pe baza ghidurilor și politicilor publicate de PikoBuy.","Toate răspunsurile FAQ","ghid","Baza cercetării · verificată la 19 august 2026","Domeniu și limitări","Răspunsurile rezumă regulile publicate; eligibilitatea, taxele, rutele și formularea se pot schimba. Fotografiile din depozit arată starea vizibilă, dar nu autentifică produsul și nu garantează calitatea ascunsă.","Deschide +","Închide −","Ajutor PikoBuy verificat","Pantofi|Adidași|Tricouri|Hanorace|Jachete|Pantaloni și pantaloni scurți|Pălării și șepci|Seturi scurte|Accesorii|Tricouri sportive|Electronice|Alte produse"],
  "hu-HU":["Kutatási összefoglaló","PikoBuy GYIK","Ellenőrzött válaszok a PikoBuy közzétett útmutatói és szabályzatai alapján.","Minden GYIK-válasz","útmutató","Kutatási alap · ellenőrizve 2026. augusztus 19-én","Hatókör és korlátok","A válaszok a közzétett szabályokat foglalják össze; a jogosultság, díjak, útvonalak és szövegezés változhat. A raktári fotók a látható állapotot mutatják, de nem igazolják az eredetiséget vagy a rejtett minőséget.","Megnyitás +","Bezárás −","Ellenőrzött PikoBuy-segítség","Cipők|Sportcipők|Pólók|Kapucnis pulóverek|Dzsekik|Nadrágok és rövidnadrágok|Fejfedők|Rövid szettek|Kiegészítők|Mezek|Elektronika|Egyéb találatok"],
  "el-GR":["Σύνοψη έρευνας","Συχνές ερωτήσεις PikoBuy","Επαληθευμένες απαντήσεις βάσει των δημοσιευμένων οδηγών και πολιτικών του PikoBuy.","Όλες οι απαντήσεις FAQ","οδηγός","Βάση έρευνας · ελέγχθηκε στις 19 Αυγούστου 2026","Πεδίο και περιορισμοί","Οι απαντήσεις συνοψίζουν δημοσιευμένους κανόνες· η επιλεξιμότητα, τα τέλη, οι διαδρομές και η διατύπωση ενδέχεται να αλλάξουν. Οι φωτογραφίες αποθήκης δείχνουν την ορατή κατάσταση, αλλά δεν πιστοποιούν αυθεντικότητα ή κρυφή ποιότητα.","Άνοιγμα +","Κλείσιμο −","Επαληθευμένη βοήθεια PikoBuy","Παπούτσια|Αθλητικά παπούτσια|Μπλουζάκια|Φούτερ με κουκούλα|Μπουφάν|Παντελόνια και σορτς|Καπέλα|Κοντά σετ|Αξεσουάρ|Φανέλες|Ηλεκτρονικά|Άλλα ευρήματα"],
  "bg-BG":["Резюме на проучването","ЧЗВ за PikoBuy","Проверени отговори въз основа на публикуваните ръководства и правила на PikoBuy.","Всички отговори","ръководство","Основа на проучването · проверено на 19 август 2026 г.","Обхват и ограничения","Отговорите обобщават публикувани правила; допустимостта, таксите, маршрутите и текстът могат да се променят. Снимките от склада показват видимото състояние, но не доказват автентичност или скрито качество.","Отвори +","Затвори −","Проверена помощ за PikoBuy","Обувки|Маратонки|Тениски|Суитшърти|Якета|Панталони и шорти|Шапки|Къси комплекти|Аксесоари|Спортни фланелки|Електроника|Други находки"],
  "hr-HR":["Sažetak istraživanja","PikoBuy FAQ","Provjereni odgovori na temelju objavljenih vodiča i pravila PikoBuya.","Svi FAQ odgovori","vodič","Osnova istraživanja · provjereno 19. kolovoza 2026.","Opseg i ograničenja","Odgovori sažimaju objavljena pravila; prihvatljivost, naknade, rute i tekst mogu se promijeniti. Skladišne fotografije pokazuju vidljivo stanje, ali ne potvrđuju autentičnost ni skrivenu kvalitetu.","Otvori +","Zatvori −","Provjerena PikoBuy pomoć","Cipele|Tenisice|Majice|Hoodice|Jakne|Hlače i kratke hlače|Pokrivala za glavu|Kratki kompleti|Dodaci|Dresovi|Elektronika|Ostali nalazi"],
  "sk-SK":["Súhrn výskumu","PikoBuy FAQ","Overené odpovede podľa zverejnených príručiek a pravidiel PikoBuy.","Všetky odpovede FAQ","sprievodca","Základ výskumu · overené 19. augusta 2026","Rozsah a obmedzenia","Odpovede sumarizujú zverejnené pravidlá; oprávnenosť, poplatky, trasy a znenie sa môžu meniť. Skladové fotografie ukazujú viditeľný stav, ale nepotvrdzujú pravosť ani skrytú kvalitu.","Otvoriť +","Zavrieť −","Overená pomoc PikoBuy","Topánky|Tenisky|Tričká|Mikiny s kapucňou|Bundy|Nohavice a šortky|Pokrývky hlavy|Krátke súpravy|Doplnky|Dresy|Elektronika|Ďalšie nálezy"],
  "sl-SI":["Povzetek raziskave","PikoBuy FAQ","Preverjeni odgovori na podlagi objavljenih vodnikov in pravil PikoBuy.","Vsi odgovori FAQ","vodnik","Raziskovalna podlaga · preverjeno 19. avgusta 2026","Obseg in omejitve","Odgovori povzemajo objavljena pravila; upravičenost, pristojbine, poti in besedilo se lahko spremenijo. Skladiščne fotografije kažejo vidno stanje, vendar ne potrjujejo pristnosti ali skrite kakovosti.","Odpri +","Zapri −","Preverjena pomoč PikoBuy","Čevlji|Superge|Majice|Puloverji s kapuco|Jakne|Hlače in kratke hlače|Pokrivala|Kratki kompleti|Dodatki|Dresi|Elektronika|Drugi izdelki"],
  "et-EE":["Uuringu kokkuvõte","PikoBuy KKK","Kontrollitud vastused PikoBuy avaldatud juhendite ja eeskirjade põhjal.","Kõik KKK vastused","juhend","Uuringu alus · kontrollitud 19. augustil 2026","Ulatus ja piirangud","Vastused võtavad kokku avaldatud reeglid; sobivus, tasud, marsruudid ja sõnastus võivad muutuda. Laofotod näitavad nähtavat seisukorda, kuid ei tõenda ehtsust ega varjatud kvaliteeti.","Ava +","Sulge −","Kontrollitud PikoBuy abi","Kingad|Tossud|T-särgid|Pusad|Joped|Püksid ja lühikesed püksid|Peakatted|Lühikesed komplektid|Aksessuaarid|Spordisärgid|Elektroonika|Muud leiud"],
  "lt-LT":["Tyrimo santrauka","PikoBuy DUK","Patikrinti atsakymai pagal paskelbtus PikoBuy vadovus ir taisykles.","Visi DUK atsakymai","vadovas","Tyrimo pagrindas · patikrinta 2026 m. rugpjūčio 19 d.","Apimtis ir ribojimai","Atsakymai apibendrina paskelbtas taisykles; tinkamumas, mokesčiai, maršrutai ir formuluotės gali keistis. Sandėlio nuotraukos rodo matomą būklę, bet nepatvirtina autentiškumo ar paslėptos kokybės.","Atidaryti +","Uždaryti −","Patikrinta PikoBuy pagalba","Batai|Sportbačiai|Marškinėliai|Džemperiai|Striukės|Kelnės ir šortai|Galvos apdangalai|Trumpi komplektai|Aksesuarai|Sportiniai marškinėliai|Elektronika|Kiti radiniai"],
};

const localizedFaqLabels: Record<string, readonly [string,string]> = {
  "de-DE":["Häufige Fragen zu PikoBuy","Alle Antworten"],
  "fr-FR":["Questions fréquentes sur PikoBuy","Toutes les réponses"],
  "es-ES":["Preguntas frecuentes sobre PikoBuy","Todas las respuestas"],
  "it-IT":["Domande frequenti su PikoBuy","Tutte le risposte"],
  "nl-NL":["Veelgestelde vragen over PikoBuy","Alle antwoorden"],
  "pl-PL":["Najczęstsze pytania o PikoBuy","Wszystkie odpowiedzi"],
  "pt-PT":["Perguntas frequentes sobre PikoBuy","Todas as respostas"],
  "pt-BR":["Perguntas frequentes sobre a PikoBuy","Todas as respostas"],
  "sv-SE":["Vanliga frågor om PikoBuy","Alla svar"],
  "da-DK":["Ofte stillede spørgsmål om PikoBuy","Alle svar"],
  "nb-NO":["Vanlige spørsmål om PikoBuy","Alle svar"],
  "fi-FI":["Usein kysytyt kysymykset PikoBuysta","Kaikki vastaukset"],
  "cs-CZ":["Časté dotazy k PikoBuy","Všechny odpovědi"],
  "ro-RO":["Întrebări frecvente despre PikoBuy","Toate răspunsurile"],
  "hu-HU":["Gyakori kérdések a PikoBuyról","Minden válasz"],
  "el-GR":["Συχνές ερωτήσεις για το PikoBuy","Όλες οι απαντήσεις"],
  "bg-BG":["Често задавани въпроси за PikoBuy","Всички отговори"],
  "hr-HR":["Česta pitanja o PikoBuyu","Svi odgovori"],
  "sk-SK":["Časté otázky o PikoBuy","Všetky odpovede"],
  "sl-SI":["Pogosta vprašanja o PikoBuy","Vsi odgovori"],
  "et-EE":["Korduma kippuvad küsimused PikoBuy kohta","Kõik vastused"],
  "lt-LT":["Dažnai užduodami klausimai apie PikoBuy","Visi atsakymai"],
};

export function getLocalizedContent(locale: string): LocalizedContent {
  const row=rows[locale]; if(!row) return en;
  const faqLabels=localizedFaqLabels[locale]||[row[1],row[3]];
  return {researchSnapshot:row[0],faqTitle:faqLabels[0],faqIntro:row[2],allFaq:faqLabels[1],guide:row[4],researchBasis:row[5],scopeTitle:row[6],scopeText:row[7],open:row[8],close:row[9],factCheckedHelp:row[10],categories:row[11].split("|")};
}

const faqCompact: Record<string, readonly string[]> = {
  "de-DE":["Was macht PikoBuy?|Einkauf und internationale Weiterleitung; PikoBuy ist nicht der Hersteller.","Welche Quellplattformen?|Taobao, Tmall, 1688, Weidian und Yupoo.","Warum zwei Zahlungen?|Zuerst Artikel und Inlandsweg, danach internationaler Versand.","Ist der Artikelpreis der Endpreis?|Nein; Inlandsversand, Verpackung, internationaler Versand und mögliche Abgaben kommen hinzu.","Was passiert im Lager?|Einbuchung, Fotos und Prüfung auf sichtbare Mängel.","Werden Weiterleitungswaren geöffnet?|Ja, laut Weiterleitungsbedingungen werden sie ausgepackt und geprüft.","Beweisen Fotos die Echtheit?|Nein; sie zeigen nur sichtbaren Zustand, keine verborgene Qualität.","Welche Daten braucht der Rechner?|Ziel, Produkttyp, Gewicht sowie Länge, Breite und Höhe.","Wann erscheint Tracking?|Normalerweise innerhalb von drei Tagen nach Versand, ohne Liefergarantie.","Wie lang ist das Rückgabefenster?|Bei berechtigten Artikeln 120 Stunden ab Lagerstatus.","Ist alles rückgabefähig?|Nein; Ausschlüsse sowie Verkäufer- und Zustandsregeln gelten.","Was kostet eine Rückgabe?|Rückversand plus ursprünglicher Versand plus 5 RMB Servicegebühr.","Wer bearbeitet den Kundendienst?|Absender oder Verkäufer; PikoBuy kann bei der Rückgabe helfen.","Wer transportiert international?|Drittanbieter; Zoll, Schaden, Verlust und Verzögerung bleiben Risiken.","Was passiert bei Ausverkauf?|Die offizielle Anleitung nennt eine Rückerstattung."],
  "fr-FR":["Que fait PikoBuy ?|Achat et réexpédition internationale ; PikoBuy n'est pas le fabricant.","Quelles plateformes sources ?|Taobao, Tmall, 1688, Weidian et Yupoo.","Pourquoi deux paiements ?|D'abord l'article et le trajet national, puis la livraison internationale.","Le prix affiché est-il final ?|Non ; livraison nationale, emballage, fret international et taxes éventuelles s'ajoutent.","Que se passe-t-il à l'entrepôt ?|Enregistrement, photos et contrôle des défauts visibles.","Les produits réexpédiés sont-ils ouverts ?|Oui, les conditions prévoient déballage et inspection.","Les photos prouvent-elles l'authenticité ?|Non ; elles montrent l'état visible, pas la qualité cachée.","Que demande l'estimateur ?|Destination, type de produit, poids, longueur, largeur et hauteur.","Quand le suivi apparaît-il ?|Normalement sous trois jours après expédition, sans garantie de livraison.","Quel est le délai de retour ?|120 heures après le statut en entrepôt pour les articles éligibles.","Tout peut-il être retourné ?|Non ; exclusions et conditions du vendeur s'appliquent.","Quel coût de retour ?|Retour, livraison initiale et frais de service de 5 RMB.","Qui gère l'après-vente ?|L'expéditeur ou le vendeur ; PikoBuy peut aider au retour.","Qui transporte le colis ?|Des logisticiens tiers ; douane, dommage, perte et retard restent des risques.","Que se passe-t-il si l'article est épuisé ?|Le guide officiel prévoit un remboursement."],
  "es-ES":["¿Qué hace PikoBuy?|Compra y reenvío internacional; PikoBuy no es el fabricante.","¿Qué plataformas de origen admite?|Taobao, Tmall, 1688, Weidian y Yupoo.","¿Por qué hay dos pagos?|Primero producto y transporte nacional; después envío internacional.","¿El precio mostrado es el total?|No; se añaden transporte nacional, embalaje, envío internacional y posibles impuestos.","¿Qué ocurre en el almacén?|Registro, fotografías y revisión de defectos visibles.","¿Se abren los productos reenviados?|Sí; las condiciones indican desembalaje e inspección.","¿Las fotos prueban autenticidad?|No; muestran estado visible, no calidad interna.","¿Qué solicita el calculador?|Destino, tipo de producto, peso, largo, ancho y alto.","¿Cuándo aparece el seguimiento?|Normalmente en tres días tras el envío, sin garantizar la entrega.","¿Cuál es el plazo de devolución?|120 horas desde el estado En almacén para artículos aptos.","¿Todo se puede devolver?|No; existen exclusiones y condiciones del vendedor.","¿Cuánto cuesta devolver?|Envío de devolución, envío original y 5 RMB de servicio.","¿Quién gestiona la posventa?|Remitente o vendedor; PikoBuy puede ayudar con la devolución.","¿Quién transporta el paquete?|Logística externa; aduanas, daños, pérdidas y retrasos siguen siendo riesgos.","¿Qué pasa si no hay stock?|La guía oficial indica que se reembolsa."],
  "it-IT":["Cosa fa PikoBuy?|Acquisto e inoltro internazionale; PikoBuy non è il produttore.","Quali piattaforme di origine?|Taobao, Tmall, 1688, Weidian e Yupoo.","Perché due pagamenti?|Prima articolo e tratta nazionale, poi spedizione internazionale.","Il prezzo mostrato è finale?|No; si aggiungono trasporto nazionale, imballaggio, spedizione e possibili imposte.","Cosa avviene in magazzino?|Registrazione, foto e controllo dei difetti visibili.","Gli articoli inoltrati vengono aperti?|Sì; i termini prevedono apertura e ispezione.","Le foto provano l'autenticità?|No; mostrano lo stato visibile, non la qualità nascosta.","Cosa richiede il calcolatore?|Destinazione, tipo prodotto, peso, lunghezza, larghezza e altezza.","Quando appare il tracking?|Normalmente entro tre giorni dalla spedizione, senza garanzia di consegna.","Quanto dura la finestra di reso?|120 ore dallo stato In magazzino per articoli idonei.","Tutto è restituibile?|No; valgono esclusioni e condizioni del venditore.","Quanto costa il reso?|Spedizione di reso, spedizione originale e 5 RMB di servizio.","Chi gestisce il post-vendita?|Mittente o venditore; PikoBuy può aiutare nel reso.","Chi trasporta il pacco?|Logistica terza; dogana, danni, perdita e ritardi restano rischi.","Cosa succede se esaurito?|La guida ufficiale indica un rimborso."],
  "nl-NL":["Wat doet PikoBuy?|Inkoop en internationale doorzending; PikoBuy is niet de fabrikant.","Welke bronplatforms?|Taobao, Tmall, 1688, Weidian en Yupoo.","Waarom twee betalingen?|Eerst product en binnenlands vervoer, daarna internationale verzending.","Is de getoonde prijs het totaal?|Nee; binnenlands vervoer, verpakking, internationale vracht en mogelijke belasting komen erbij.","Wat gebeurt in het magazijn?|Inboeken, foto's en controle op zichtbare gebreken.","Worden doorgestuurde goederen geopend?|Ja; de voorwaarden noemen uitpakken en inspecteren.","Bewijzen foto's echtheid?|Nee; ze tonen zichtbare staat, niet verborgen kwaliteit.","Welke gegevens vraagt de calculator?|Bestemming, producttype, gewicht, lengte, breedte en hoogte.","Wanneer verschijnt tracking?|Normaal binnen drie dagen na verzending, zonder leveringsgarantie.","Hoe lang is het retourvenster?|120 uur na de magazijnstatus voor geschikte artikelen.","Kan alles retour?|Nee; uitsluitingen en verkopersvoorwaarden gelden.","Wat kost een retour?|Retourzending, oorspronkelijke verzending en 5 RMB servicekosten.","Wie behandelt nazorg?|Afzender of verkoper; PikoBuy kan bij retour helpen.","Wie vervoert internationaal?|Externe logistiek; douane, schade, verlies en vertraging blijven risico's.","Wat bij uitverkocht?|De officiële gids vermeldt terugbetaling."],
  "pl-PL":["Co robi PikoBuy?|Kupuje i przekazuje przesyłki międzynarodowe; nie jest producentem.","Jakie platformy źródłowe?|Taobao, Tmall, 1688, Weidian i Yupoo.","Dlaczego dwie płatności?|Najpierw produkt i transport krajowy, potem wysyłka międzynarodowa.","Czy pokazana cena jest końcowa?|Nie; dochodzą transport krajowy, pakowanie, fracht i możliwe podatki.","Co dzieje się w magazynie?|Przyjęcie, zdjęcia i kontrola widocznych wad.","Czy towary są otwierane?|Tak; warunki przewidują rozpakowanie i kontrolę.","Czy zdjęcia potwierdzają autentyczność?|Nie; pokazują stan widoczny, nie ukrytą jakość.","Jakich danych wymaga kalkulator?|Cel, typ produktu, waga, długość, szerokość i wysokość.","Kiedy pojawia się śledzenie?|Zwykle w ciągu trzech dni od wysyłki, bez gwarancji dostawy.","Jaki jest czas na zwrot?|120 godzin od statusu magazynowego dla kwalifikujących się produktów.","Czy wszystko można zwrócić?|Nie; obowiązują wyłączenia i warunki sprzedawcy.","Ile kosztuje zwrot?|Wysyłka zwrotna, pierwotna wysyłka i 5 RMB opłaty.","Kto obsługuje posprzedażowo?|Nadawca lub sprzedawca; PikoBuy może pomóc w zwrocie.","Kto przewozi paczkę?|Firmy zewnętrzne; cło, szkoda, utrata i opóźnienie pozostają ryzykiem.","Co przy braku towaru?|Oficjalny poradnik wskazuje zwrot pieniędzy."],
  "pt-PT":["O que faz o PikoBuy?|Compra e reencaminha internacionalmente; não é o fabricante.","Quais plataformas de origem?|Taobao, Tmall, 1688, Weidian e Yupoo.","Porquê dois pagamentos?|Primeiro produto e transporte interno; depois envio internacional.","O preço mostrado é final?|Não; somam-se transporte interno, embalagem, frete e possíveis impostos.","O que acontece no armazém?|Entrada, fotografias e verificação de defeitos visíveis.","Os produtos são abertos?|Sim; os termos indicam desembalagem e inspeção.","As fotos provam autenticidade?|Não; mostram condição visível, não qualidade oculta.","Que dados pede o estimador?|Destino, tipo de produto, peso, comprimento, largura e altura.","Quando aparece o rastreio?|Normalmente em três dias após envio, sem garantia de entrega.","Qual é o prazo de devolução?|120 horas após o estado no armazém para artigos elegíveis.","Tudo pode ser devolvido?|Não; existem exclusões e regras do vendedor.","Quanto custa devolver?|Envio de retorno, envio original e taxa de serviço de 5 RMB.","Quem trata do pós-venda?|Remetente ou vendedor; o PikoBuy pode ajudar no retorno.","Quem transporta a encomenda?|Logística terceira; alfândega, dano, perda e atraso continuam riscos.","E se estiver esgotado?|O guia oficial indica reembolso."],
  "pt-BR":["O que a PikoBuy faz?|Compra e encaminha internacionalmente; não é a fabricante.","Quais plataformas de origem?|Taobao, Tmall, 1688, Weidian e Yupoo.","Por que existem dois pagamentos?|Primeiro produto e transporte doméstico; depois frete internacional.","O preço mostrado é final?|Não; entram transporte doméstico, embalagem, frete e possíveis impostos.","O que ocorre no armazém?|Entrada, fotos e verificação de defeitos visíveis.","Os produtos são abertos?|Sim; os termos indicam desembalagem e inspeção.","As fotos provam autenticidade?|Não; mostram condição visível, não qualidade interna.","Quais dados o estimador pede?|Destino, tipo de produto, peso, comprimento, largura e altura.","Quando aparece o rastreio?|Normalmente em três dias após o envio, sem garantia de entrega.","Qual é o prazo de devolução?|120 horas após o status no armazém para itens elegíveis.","Tudo pode ser devolvido?|Não; há exclusões e condições do vendedor.","Quanto custa devolver?|Frete de retorno, frete original e taxa de 5 RMB.","Quem cuida do pós-venda?|Remetente ou vendedor; a PikoBuy pode ajudar na devolução.","Quem transporta o pacote?|Logística terceirizada; alfândega, dano, perda e atraso continuam riscos.","E se estiver sem estoque?|O guia oficial informa reembolso."],
  "sv-SE":["Vad gör PikoBuy?|Köper och vidarebefordrar internationellt; PikoBuy är inte tillverkaren.","Vilka källplattformar?|Taobao, Tmall, 1688, Weidian och Yupoo.","Varför två betalningar?|Först vara och inrikestransport, sedan internationell frakt.","Är visat pris slutpriset?|Nej; inrikesfrakt, emballage, internationell frakt och möjliga skatter tillkommer.","Vad sker på lagret?|Incheckning, foton och kontroll av synliga fel.","Öppnas vidarebefordrade varor?|Ja; villkoren anger uppackning och inspektion.","Bevisar foton äkthet?|Nej; de visar synligt skick, inte dold kvalitet.","Vilka uppgifter krävs?|Destination, produkttyp, vikt, längd, bredd och höjd.","När visas spårning?|Normalt inom tre dagar efter avsändning, utan leveransgaranti.","Hur långt är returfönstret?|120 timmar efter lagerstatus för godkända varor.","Kan allt returneras?|Nej; undantag och säljarvillkor gäller.","Vad kostar en retur?|Returfrakt, ursprunglig frakt och 5 RMB serviceavgift.","Vem sköter efterservice?|Avsändare eller säljare; PikoBuy kan hjälpa med retur.","Vem transporterar paketet?|Tredjepartslogistik; tull, skada, förlust och försening är risker.","Vad händer vid slutsålt?|Den officiella guiden anger återbetalning."],
  "da-DK":["Hvad gør PikoBuy?|Køber og videresender internationalt; PikoBuy er ikke producenten.","Hvilke kildeplatforme?|Taobao, Tmall, 1688, Weidian og Yupoo.","Hvorfor to betalinger?|Først vare og indenrigstransport, derefter international fragt.","Er den viste pris slutprisen?|Nej; indenrigsfragt, emballage, international fragt og mulige skatter kommer til.","Hvad sker på lageret?|Indtjekning, fotos og kontrol af synlige fejl.","Åbnes videresendte varer?|Ja; vilkårene angiver udpakning og inspektion.","Beviser fotos ægthed?|Nej; de viser synlig stand, ikke skjult kvalitet.","Hvilke data kræver beregneren?|Destination, produkttype, vægt, længde, bredde og højde.","Hvornår vises sporing?|Normalt inden tre dage efter afsendelse, uden leveringsgaranti.","Hvor langt er returvinduet?|120 timer efter lagerstatus for berettigede varer.","Kan alt returneres?|Nej; undtagelser og sælgerbetingelser gælder.","Hvad koster en retur?|Returfragt, oprindelig fragt og 5 RMB servicegebyr.","Hvem håndterer eftersalg?|Afsender eller sælger; PikoBuy kan hjælpe med retur.","Hvem transporterer pakken?|Tredjepartslogistik; told, skade, tab og forsinkelse er risici.","Hvad sker ved udsolgt?|Den officielle guide angiver tilbagebetaling."],
  "nb-NO":["Hva gjør PikoBuy?|Kjøper og videresender internasjonalt; PikoBuy er ikke produsenten.","Hvilke kildeplattformer?|Taobao, Tmall, 1688, Weidian og Yupoo.","Hvorfor to betalinger?|Først vare og innenrikstransport, deretter internasjonal frakt.","Er vist pris sluttprisen?|Nei; innenriksfrakt, emballasje, internasjonal frakt og mulige avgifter kommer i tillegg.","Hva skjer på lageret?|Innsjekking, bilder og kontroll av synlige feil.","Åpnes videresendte varer?|Ja; vilkårene angir utpakking og inspeksjon.","Beviser bilder ekthet?|Nei; de viser synlig tilstand, ikke skjult kvalitet.","Hvilke data kreves?|Destinasjon, produkttype, vekt, lengde, bredde og høyde.","Når vises sporing?|Normalt innen tre dager etter sending, uten leveringsgaranti.","Hvor langt er returvinduet?|120 timer etter lagerstatus for kvalifiserte varer.","Kan alt returneres?|Nei; unntak og selgervilkår gjelder.","Hva koster retur?|Returfrakt, opprinnelig frakt og 5 RMB servicegebyr.","Hvem håndterer ettersalg?|Avsender eller selger; PikoBuy kan hjelpe med retur.","Hvem transporterer pakken?|Tredjepartslogistikk; toll, skade, tap og forsinkelse er risikoer.","Hva skjer ved utsolgt?|Den offisielle guiden angir refusjon."],
  "fi-FI":["Mitä PikoBuy tekee?|Ostaa ja välittää kansainvälisesti; PikoBuy ei ole valmistaja.","Mitkä lähdealustat?|Taobao, Tmall, 1688, Weidian ja Yupoo.","Miksi kaksi maksua?|Ensin tuote ja kotimaan kuljetus, sitten kansainvälinen toimitus.","Onko näytetty hinta lopullinen?|Ei; kotimaan kuljetus, pakkaus, kansainvälinen rahti ja mahdolliset verot lisätään.","Mitä varastossa tapahtuu?|Kirjaus, kuvat ja näkyvien vikojen tarkastus.","Avataanko välitetyt tavarat?|Kyllä; ehdot edellyttävät purkamista ja tarkastusta.","Todistavatko kuvat aitouden?|Eivät; ne näyttävät näkyvän kunnon, eivät piilevää laatua.","Mitä laskuri tarvitsee?|Määränpää, tuotetyyppi, paino, pituus, leveys ja korkeus.","Milloin seuranta näkyy?|Tavallisesti kolmen päivän kuluessa lähetyksestä, ilman toimitustakuuta.","Kuinka pitkä palautusaika on?|120 tuntia varastotilasta kelpoisille tuotteille.","Voiko kaiken palauttaa?|Ei; poikkeukset ja myyjän ehdot pätevät.","Mitä palautus maksaa?|Palautusrahti, alkuperäinen rahti ja 5 RMB palvelumaksu.","Kuka hoitaa jälkipalvelun?|Lähettäjä tai myyjä; PikoBuy voi auttaa palautuksessa.","Kuka kuljettaa paketin?|Kolmannen osapuolen logistiikka; tulli, vaurio, katoaminen ja viive ovat riskejä.","Entä jos tuote loppuu?|Virallinen opas ilmoittaa hyvityksestä."],
  "cs-CZ":["Co dělá PikoBuy?|Nakupuje a mezinárodně přeposílá; není výrobcem.","Které zdrojové platformy?|Taobao, Tmall, 1688, Weidian a Yupoo.","Proč dvě platby?|Nejprve zboží a vnitrostátní přeprava, potom mezinárodní doprava.","Je zobrazená cena konečná?|Ne; přidává se domácí doprava, balení, mezinárodní přeprava a možné daně.","Co se děje ve skladu?|Příjem, fotografie a kontrola viditelných vad.","Otevírá se přeposílané zboží?|Ano; podmínky uvádějí rozbalení a kontrolu.","Prokazují fotografie pravost?|Ne; ukazují viditelný stav, ne skrytou kvalitu.","Jaké údaje vyžaduje kalkulátor?|Cíl, typ výrobku, hmotnost, délku, šířku a výšku.","Kdy se objeví sledování?|Obvykle do tří dnů od odeslání, bez záruky doručení.","Jak dlouhé je okno pro vrácení?|120 hodin od skladového stavu u způsobilého zboží.","Lze vrátit vše?|Ne; platí výjimky a podmínky prodejce.","Kolik stojí vrácení?|Zpáteční doprava, původní doprava a poplatek 5 RMB.","Kdo řeší poprodejní servis?|Odesílatel nebo prodejce; PikoBuy může pomoci s vrácením.","Kdo přepravuje zásilku?|Externí logistika; clo, poškození, ztráta a zpoždění jsou rizika.","Co když je vyprodáno?|Oficiální průvodce uvádí vrácení peněz."],
  "ro-RO":["Ce face PikoBuy?|Cumpără și redirecționează internațional; nu este producătorul.","Ce platforme sursă?|Taobao, Tmall, 1688, Weidian și Yupoo.","De ce două plăți?|Mai întâi produsul și transportul intern, apoi livrarea internațională.","Prețul afișat este final?|Nu; se adaugă transport intern, ambalare, transport internațional și posibile taxe.","Ce se întâmplă în depozit?|Recepție, fotografii și verificarea defectelor vizibile.","Produsele sunt deschise?|Da; termenii prevăd despachetarea și inspecția.","Fotografiile dovedesc autenticitatea?|Nu; arată starea vizibilă, nu calitatea ascunsă.","Ce date cere estimatorul?|Destinație, tip produs, greutate, lungime, lățime și înălțime.","Când apare urmărirea?|De regulă în trei zile după expediere, fără garanție de livrare.","Cât durează fereastra de retur?|120 de ore de la starea în depozit pentru articole eligibile.","Se poate returna orice?|Nu; se aplică excluderi și condițiile vânzătorului.","Cât costă returul?|Transport de retur, transport inițial și taxă de 5 RMB.","Cine gestionează post-vânzarea?|Expeditorul sau vânzătorul; PikoBuy poate ajuta la retur.","Cine transportă coletul?|Logistică terță; vama, daunele, pierderea și întârzierea sunt riscuri.","Ce se întâmplă fără stoc?|Ghidul oficial indică rambursarea."],
  "hu-HU":["Mit csinál a PikoBuy?|Vásárol és nemzetközileg továbbít; nem gyártó.","Mely forrásplatformok?|Taobao, Tmall, 1688, Weidian és Yupoo.","Miért van két fizetés?|Először a termék és belföldi szállítás, majd a nemzetközi fuvar.","A feltüntetett ár végleges?|Nem; belföldi szállítás, csomagolás, nemzetközi fuvar és adók jöhetnek hozzá.","Mi történik a raktárban?|Beérkeztetés, fotók és látható hibák ellenőrzése.","Felbontják a továbbított árut?|Igen; a feltételek kicsomagolást és ellenőrzést írnak le.","Bizonyítják a fotók az eredetiséget?|Nem; látható állapotot mutatnak, nem rejtett minőséget.","Milyen adatokat kér a kalkulátor?|Célország, terméktípus, súly, hossz, szélesség és magasság.","Mikor jelenik meg a követés?|Általában feladás után három napon belül, kézbesítési garancia nélkül.","Meddig kérhető visszaküldés?|Jogosult terméknél 120 óra a raktári állapottól.","Minden visszaküldhető?|Nem; kizárások és eladói feltételek érvényesek.","Mennyibe kerül a visszaküldés?|Visszaküldés, eredeti szállítás és 5 RMB szolgáltatási díj.","Ki intézi az utólagos ügyeket?|A feladó vagy eladó; a PikoBuy segíthet a visszaküldésben.","Ki szállítja a csomagot?|Külső logisztika; vám, sérülés, elvesztés és késés kockázat.","Mi történik készlethiánynál?|A hivatalos útmutató visszatérítést jelez."],
  "el-GR":["Τι κάνει το PikoBuy;|Αγοράζει και προωθεί διεθνώς· δεν είναι ο κατασκευαστής.","Ποιες πλατφόρμες προέλευσης;|Taobao, Tmall, 1688, Weidian και Yupoo.","Γιατί δύο πληρωμές;|Πρώτα προϊόν και εγχώρια μεταφορά, μετά διεθνής αποστολή.","Είναι τελική η εμφανιζόμενη τιμή;|Όχι· προστίθενται εγχώρια μεταφορά, συσκευασία, διεθνής αποστολή και πιθανοί φόροι.","Τι γίνεται στην αποθήκη;|Καταχώριση, φωτογραφίες και έλεγχος ορατών ελαττωμάτων.","Ανοίγονται τα προωθούμενα προϊόντα;|Ναι· οι όροι προβλέπουν αποσυσκευασία και έλεγχο.","Αποδεικνύουν οι φωτογραφίες αυθεντικότητα;|Όχι· δείχνουν ορατή κατάσταση, όχι κρυφή ποιότητα.","Τι ζητά ο υπολογιστής;|Προορισμό, τύπο προϊόντος, βάρος, μήκος, πλάτος και ύψος.","Πότε εμφανίζεται η παρακολούθηση;|Συνήθως εντός τριών ημερών από την αποστολή, χωρίς εγγύηση παράδοσης.","Πόσο διαρκεί το παράθυρο επιστροφής;|120 ώρες από την κατάσταση αποθήκης για επιλέξιμα προϊόντα.","Επιστρέφονται όλα;|Όχι· ισχύουν εξαιρέσεις και όροι πωλητή.","Πόσο κοστίζει η επιστροφή;|Μεταφορικά επιστροφής, αρχικά μεταφορικά και τέλος 5 RMB.","Ποιος χειρίζεται την υποστήριξη;|Αποστολέας ή πωλητής· το PikoBuy μπορεί να βοηθήσει στην επιστροφή.","Ποιος μεταφέρει το δέμα;|Τρίτοι μεταφορείς· τελωνείο, ζημιά, απώλεια και καθυστέρηση είναι κίνδυνοι.","Τι γίνεται όταν εξαντληθεί;|Ο επίσημος οδηγός αναφέρει επιστροφή χρημάτων."],
  "bg-BG":["Какво прави PikoBuy?|Купува и препраща международно; не е производителят.","Кои платформи източници?|Taobao, Tmall, 1688, Weidian и Yupoo.","Защо има две плащания?|Първо продукт и вътрешен транспорт, после международна доставка.","Показаната цена крайна ли е?|Не; добавят се вътрешен транспорт, опаковка, международен превоз и възможни данъци.","Какво става в склада?|Приемане, снимки и проверка за видими дефекти.","Отварят ли се стоките?|Да; условията предвиждат разопаковане и проверка.","Снимките доказват ли автентичност?|Не; показват видимо състояние, не скрито качество.","Какви данни иска калкулаторът?|Дестинация, тип продукт, тегло, дължина, ширина и височина.","Кога се появява проследяването?|Обикновено до три дни след изпращане, без гаранция за доставка.","Колко е срокът за връщане?|120 часа от складовия статус за допустими продукти.","Всичко ли може да се върне?|Не; важат изключения и условия на продавача.","Колко струва връщането?|Обратна доставка, първоначална доставка и такса 5 RMB.","Кой обслужва след продажбата?|Подателят или продавачът; PikoBuy може да помогне с връщане.","Кой превозва пратката?|Външна логистика; митница, щета, загуба и забавяне са рискове.","Какво става при изчерпване?|Официалното ръководство посочва възстановяване на сумата."],
  "hr-HR":["Što radi PikoBuy?|Kupuje i međunarodno prosljeđuje; nije proizvođač.","Koje izvorne platforme?|Taobao, Tmall, 1688, Weidian i Yupoo.","Zašto dva plaćanja?|Prvo proizvod i domaći prijevoz, zatim međunarodna dostava.","Je li prikazana cijena konačna?|Ne; dodaju se domaći prijevoz, pakiranje, međunarodni prijevoz i mogući porezi.","Što se događa u skladištu?|Prijem, fotografije i provjera vidljivih nedostataka.","Otvara li se proslijeđena roba?|Da; uvjeti predviđaju raspakiranje i pregled.","Dokazuju li fotografije autentičnost?|Ne; pokazuju vidljivo stanje, ne skrivenu kvalitetu.","Koje podatke traži kalkulator?|Odredište, vrstu proizvoda, težinu, duljinu, širinu i visinu.","Kada se pojavi praćenje?|Obično unutar tri dana nakon slanja, bez jamstva dostave.","Koliki je rok za povrat?|120 sati od skladišnog statusa za prihvatljive proizvode.","Može li se sve vratiti?|Ne; vrijede iznimke i uvjeti prodavača.","Koliko košta povrat?|Povratna dostava, izvorna dostava i naknada 5 RMB.","Tko rješava naknadnu podršku?|Pošiljatelj ili prodavač; PikoBuy može pomoći s povratom.","Tko prevozi paket?|Vanjska logistika; carina, šteta, gubitak i kašnjenje ostaju rizici.","Što ako nema zalihe?|Službeni vodič navodi povrat novca."],
  "sk-SK":["Čo robí PikoBuy?|Nakupuje a medzinárodne preposiela; nie je výrobcom.","Ktoré zdrojové platformy?|Taobao, Tmall, 1688, Weidian a Yupoo.","Prečo dve platby?|Najprv produkt a vnútroštátna preprava, potom medzinárodná doprava.","Je zobrazená cena konečná?|Nie; pripočíta sa domáca doprava, balenie, medzinárodná preprava a možné dane.","Čo sa deje v sklade?|Príjem, fotografie a kontrola viditeľných chýb.","Otvára sa preposielaný tovar?|Áno; podmienky uvádzajú rozbalenie a kontrolu.","Dokazujú fotografie pravosť?|Nie; ukazujú viditeľný stav, nie skrytú kvalitu.","Aké údaje potrebuje kalkulačka?|Cieľ, typ produktu, hmotnosť, dĺžku, šírku a výšku.","Kedy sa objaví sledovanie?|Zvyčajne do troch dní po odoslaní, bez záruky doručenia.","Aké dlhé je okno na vrátenie?|120 hodín od skladového stavu pri oprávnenom tovare.","Dá sa vrátiť všetko?|Nie; platia výnimky a podmienky predajcu.","Koľko stojí vrátenie?|Spätná doprava, pôvodná doprava a poplatok 5 RMB.","Kto rieši popredajný servis?|Odosielateľ alebo predajca; PikoBuy môže pomôcť s vrátením.","Kto prepravuje balík?|Externá logistika; clo, poškodenie, strata a oneskorenie sú riziká.","Čo pri vypredaní?|Oficiálny sprievodca uvádza vrátenie peňazí."],
  "sl-SI":["Kaj počne PikoBuy?|Kupuje in mednarodno posreduje; ni proizvajalec.","Katere izvorne platforme?|Taobao, Tmall, 1688, Weidian in Yupoo.","Zakaj dve plačili?|Najprej izdelek in domači prevoz, nato mednarodna dostava.","Je prikazana cena končna?|Ne; dodajo se domači prevoz, embalaža, mednarodni prevoz in možni davki.","Kaj se zgodi v skladišču?|Prevzem, fotografije in pregled vidnih napak.","Ali se posredovano blago odpre?|Da; pogoji določajo razpakiranje in pregled.","Ali fotografije dokazujejo pristnost?|Ne; kažejo vidno stanje, ne skrite kakovosti.","Katere podatke zahteva kalkulator?|Cilj, vrsto izdelka, težo, dolžino, širino in višino.","Kdaj se pojavi sledenje?|Običajno v treh dneh po odpremi, brez jamstva dostave.","Kako dolgo je okno za vračilo?|120 ur od skladiščnega statusa za upravičene izdelke.","Se lahko vrne vse?|Ne; veljajo izjeme in pogoji prodajalca.","Koliko stane vračilo?|Povratna poštnina, prvotna poštnina in 5 RMB pristojbine.","Kdo ureja poprodajne težave?|Pošiljatelj ali prodajalec; PikoBuy lahko pomaga pri vračilu.","Kdo prevaža paket?|Zunanja logistika; carina, škoda, izguba in zamuda so tveganja.","Kaj ob razprodaji?|Uradni vodnik navaja vračilo denarja."],
  "et-EE":["Mida PikoBuy teeb?|Ostab ja vahendab rahvusvaheliselt; ei ole tootja.","Millised lähteplatvormid?|Taobao, Tmall, 1688, Weidian ja Yupoo.","Miks kaks makset?|Esmalt toode ja riigisisene vedu, seejärel rahvusvaheline saatmine.","Kas näidatud hind on lõplik?|Ei; lisanduvad kohalik vedu, pakend, rahvusvaheline vedu ja võimalikud maksud.","Mis toimub laos?|Vastuvõtt, fotod ja nähtavate vigade kontroll.","Kas vahendatud kaup avatakse?|Jah; tingimused näevad ette lahtipakkimise ja kontrolli.","Kas fotod tõendavad ehtsust?|Ei; need näitavad nähtavat seisundit, mitte varjatud kvaliteeti.","Milliseid andmeid kalkulaator vajab?|Sihtkoht, tootetüüp, kaal, pikkus, laius ja kõrgus.","Millal jälgimine ilmub?|Tavaliselt kolme päeva jooksul pärast saatmist, ilma tarnegarantiita.","Kui pikk on tagastusaken?|Sobivatel toodetel 120 tundi laostaatuse algusest.","Kas kõike saab tagastada?|Ei; kehtivad erandid ja müüja tingimused.","Mida tagastus maksab?|Tagasisaatmine, algne saatmine ja 5 RMB teenustasu.","Kes tegeleb järelteenindusega?|Saatja või müüja; PikoBuy võib tagastamisel aidata.","Kes pakki veab?|Kolmanda osapoole logistika; toll, kahju, kaotus ja viivitus on riskid.","Mis juhtub laoseisu puudumisel?|Ametlik juhend märgib tagasimakse."],
  "lt-LT":["Ką daro PikoBuy?|Perka ir persiunčia tarptautiniu mastu; nėra gamintojas.","Kokios šaltinio platformos?|Taobao, Tmall, 1688, Weidian ir Yupoo.","Kodėl du mokėjimai?|Pirma produktas ir vietinis gabenimas, tada tarptautinis siuntimas.","Ar rodoma kaina galutinė?|Ne; pridedamas vietinis gabenimas, pakavimas, tarptautinis transportas ir galimi mokesčiai.","Kas vyksta sandėlyje?|Priėmimas, nuotraukos ir matomų defektų patikra.","Ar persiunčiamos prekės atidaromos?|Taip; sąlygose numatytas išpakavimas ir patikrinimas.","Ar nuotraukos įrodo autentiškumą?|Ne; jos rodo matomą būklę, ne paslėptą kokybę.","Kokių duomenų reikia skaičiuoklei?|Paskirties vietos, produkto tipo, svorio, ilgio, pločio ir aukščio.","Kada atsiranda sekimas?|Paprastai per tris dienas po išsiuntimo, be pristatymo garantijos.","Kiek trunka grąžinimo terminas?|Tinkamoms prekėms 120 valandų nuo sandėlio būsenos.","Ar viską galima grąžinti?|Ne; taikomos išimtys ir pardavėjo sąlygos.","Kiek kainuoja grąžinimas?|Grąžinimo siuntimas, pradinis siuntimas ir 5 RMB mokestis.","Kas tvarko aptarnavimą po pirkimo?|Siuntėjas arba pardavėjas; PikoBuy gali padėti grąžinti.","Kas gabena siuntą?|Trečiųjų šalių logistika; muitinė, žala, praradimas ir vėlavimas yra rizikos.","Kas nutinka, kai prekės nėra?|Oficialiame vadove nurodomas pinigų grąžinimas."],
};

export function getLocalizedFaq(locale: string, fallbackText: string) {
  if(locale==="en-US"||locale==="en-GB") return faqItems;
  const row=faqCompact[locale];
  if(row) return row.map((item)=>{const [question,answer]=item.split("|");return {question,answer};});
  return faqItems.map((item,index)=>({question:`${getLocalizedContent(locale).faqTitle} ${String(index+1).padStart(2,"0")}`,answer:`${fallbackText} ${index===7?"1 kg · cm":index===8?"3":index===9?"120":index===11?"5 RMB":"PikoBuy"}.`}));
}

const relatedFaq: ReadonlyArray<readonly number[]> = [
  [1,2], [0,2], [3,7], [2,7], [5,6], [4,6], [4,5], [3,13],
  [13,7], [10,11], [9,11], [9,10], [9,10], [8,7], [2,3],
];

/**
 * The homepage keeps concise answers, while the standalone FAQ retains the
 * same 15 questions with fuller, related policy context in the active locale.
 */
export function getLocalizedDetailedFaq(locale: string, fallbackText: string) {
  const items = getLocalizedFaq(locale, fallbackText);
  if(locale==="en-US"||locale==="en-GB") return items;
  const scope = getLocalizedContent(locale).scopeText;
  return items.map((item,index)=>({
    question:item.question,
    answer:[item.answer,...relatedFaq[index].map((related)=>items[related].answer),scope].join(" "),
  }));
}

type ArticleSectionPlan = { heading: number; facts: readonly number[] };

/**
 * These plans are the localized equivalents of the seven English sections.
 * Each position is stable across languages; FAQ facts only supply translated
 * wording for the subject assigned to that English section.
 */
const articleSectionPlans: Record<string, readonly ArticleSectionPlan[]> = {
  "how-pikobuy-works":[
    {heading:1,facts:[0,1]},
    {heading:2,facts:[2,3,14]},
    {heading:4,facts:[4,5,6]},
    {heading:9,facts:[9,10,11]},
    {heading:7,facts:[7,3,13]},
    {heading:13,facts:[13,12,7]},
    {heading:8,facts:[8,13,9]},
  ],
  "pikobuy-shipping-cost-guide":[
    {heading:3,facts:[3,2,11]},
    {heading:7,facts:[7,3,13]},
    {heading:7,facts:[4,7,5]},
    {heading:7,facts:[7,13,6]},
    {heading:13,facts:[13,8,7]},
    {heading:9,facts:[9,10,11,12]},
    {heading:7,facts:[3,7,8,13]},
  ],
  "pikobuy-qc-photo-checklist":[
    {heading:4,facts:[4,5,6]},
    {heading:0,facts:[4,6,1]},
    {heading:7,facts:[4,7,6]},
    {heading:6,facts:[6,4]},
    {heading:5,facts:[5,6,4]},
    {heading:9,facts:[9,10,11]},
    {heading:13,facts:[13,8,7]},
  ],
  "pikobuy-restricted-items-guide":[
    {heading:7,facts:[7,3,13]},
    {heading:7,facts:[7,13,3]},
    {heading:6,facts:[6,4,7]},
    {heading:13,facts:[13,7,3]},
    {heading:13,facts:[13,6,5]},
    {heading:7,facts:[7,13,3]},
    {heading:4,facts:[4,7,9]},
  ],
  "pikobuy-spain-guide":[
    {heading:0,facts:[0,2,3]},
    {heading:3,facts:[3,7,13]},
    {heading:7,facts:[7,13,3]},
    {heading:13,facts:[13,3,7]},
    {heading:4,facts:[4,9,10,11]},
    {heading:8,facts:[8,13,7]},
    {heading:7,facts:[3,4,8,13]},
  ],
  "pikobuy-usa-guide":[
    {heading:0,facts:[0,2,3]},
    {heading:3,facts:[3,7,13]},
    {heading:7,facts:[7,13,3]},
    {heading:13,facts:[13,3,7]},
    {heading:13,facts:[13,6,7]},
    {heading:4,facts:[4,9,10,11]},
    {heading:8,facts:[8,3,4,13]},
  ],
};

export type LocalizedSeoSection = {
  slot: string;
  heading: string;
  paragraphs: readonly string[];
};

/**
 * Return the same seven semantic content slots as the English master article.
 * Related facts add the long-form context without borrowing the next section,
 * which previously made a language switch produce a different article.
 */
export function getLocalizedSeoSections(locale: string, slug: string, fallbackText: string): readonly LocalizedSeoSection[] {
  const items=getLocalizedFaq(locale,fallbackText);
  const localized=getLocalizedContent(locale);
  const scope=localized.scopeText;
  const shipping=getShippingCopy(locale);
  const plans=articleSectionPlans[slug]||articleSectionPlans["how-pikobuy-works"];
  const headings:Record<string,readonly string[]>={
    "how-pikobuy-works":[items[1].question,items[2].question,items[4].question,items[9].question,shipping.inputsTitle,shipping.riskTitle,items[8].question],
    "pikobuy-shipping-cost-guide":[shipping.title,shipping.inputsTitle,shipping.calloutTitle,`${shipping.inputs[1].label}: ${shipping.inputs[1].description}`,shipping.riskTitle,items[9].question,`${shipping.inputs[4].label}: ${shipping.calloutBody}`],
    "pikobuy-qc-photo-checklist":[items[4].question,`${items[0].question} ${items[4].question}`,`${localized.categories.join(" · ")}`,items[6].question,items[5].question,items[9].question,`${items[13].question} ${items[8].question}`],
    "pikobuy-restricted-items-guide":[shipping.riskTitle,shipping.inputsTitle,`${localized.categories[10]} · ${shipping.inputs[1].label}`,shipping.calloutTitle,items[13].question,shipping.title,`${items[4].question} ${items[9].question}`],
    "pikobuy-spain-guide":[`${items[0].question} · España`,shipping.title,`${shipping.inputsTitle} · España`,`${shipping.riskTitle} · España`,items[4].question,items[8].question,`${shipping.calloutTitle} · España`],
    "pikobuy-usa-guide":[`${items[0].question} · USA`,shipping.title,`${shipping.inputsTitle} · USA`,`${shipping.riskTitle} · USA`,items[13].question,items[4].question,`${shipping.calloutTitle} · USA`],
  };
  const sectionHeadings=headings[slug]||headings["how-pikobuy-works"];
  return plans.map((plan,position)=>{
    const contextualParagraph=(indexes:readonly number[])=>indexes.map((index)=>{
      const context=[items[index].answer,...relatedFaq[index].map((related)=>items[related].answer)];
      return `${items[index].question} ${context.join(" ")}`;
    }).join(" ");
    const split=Math.max(1,Math.ceil(plan.facts.length/2));
    const firstFacts=plan.facts.slice(0,split);
    const secondFacts=plan.facts.slice(split);
    const shippingSupport=[
      `${shipping.intro} ${shipping.calloutBody}`,
      shipping.inputs.map((input)=>`${input.label}: ${input.description}`).join(" "),
      `${shipping.sampleBody} ${shipping.riskBody}`,
    ];
    return {
      slot:`${slug}:${position+1}`,
      heading:sectionHeadings[position]||items[plan.heading].question,
      paragraphs:[
        contextualParagraph(firstFacts),
        contextualParagraph(secondFacts.length?secondFacts:firstFacts),
        `${shippingSupport[position%shippingSupport.length]} ${fallbackText} ${scope}`,
      ],
    };
  });
}
