export type ArticleSection={heading:string;paragraphs:string[];bullets?:string[]};
export type ArticleRecord={slug:string;title:string;dek:string;label:string;readTime:string;updated:string;sections:ArticleSection[]};

export const articleRecords:ArticleRecord[]=[
 {
  slug:"read-pikobuy-qc-photos",
  title:"How to Read PikoBuy QC Photos Without Guessing",
  dek:"A practical, category-by-category method for checking visible details, confirming the ordered option and deciding when another photo is worth requesting.",
  label:"QC PHOTOS",readTime:"12 MIN READ",updated:"Fact-checked August 2026",
  sections:[
   {heading:"What PikoBuy officially promises—and what it does not",paragraphs:["PikoBuy’s beginner guide says that after an item reaches its China warehouse, the warehouse checks it in, takes photos for confirmation and performs a defect check. Its forwarding terms add that forwarded goods are unpacked and inspected, and that users can review inspection photos or purchase additional detailed photos. Those are useful services, but they should not be stretched into a promise that every hidden flaw, material issue or professional technical problem will be found.","The same forwarding terms specifically say that professional inspection cannot be provided for special or professional products. That matters. A warehouse photo can show visible condition, colour, shape and obvious damage. It usually cannot prove fabric composition, long-term durability, electrical safety, authenticity or whether a product will fit a particular person. Read the images as evidence of what is visible—not as a universal quality certificate."],bullets:["Official fact: check-in, photo confirmation and defect checking are part of the published warehouse flow.","Official fact: extra detailed photos may be available.","Practical limit: a photo only proves what the camera clearly shows."]},
   {heading:"Start with the order record, not the photograph",paragraphs:["The easiest QC mistake is opening the warehouse gallery without first checking what was actually ordered. Before judging the pictures, place the source listing, selected colour, selected size, quantity and any seller notes next to the warehouse record. PikoBuy’s guide tells shoppers to confirm specifications, colour and size before submitting the purchasing order. That comparison point is essential because a perfectly photographed item can still be the wrong option.","Look for simple identity signals first: the number of pieces, the colour family, the size label, the model or version, and included accessories. If the listing showed a detachable part, spare lace, cable or branded box, check whether it appears in the received set. Do not assume that an angle outside the frame contains the missing item. Mark it as unconfirmed and request clarification if it changes your decision."],bullets:["Compare ordered option with received option.","Count pieces and visible accessories.","Treat anything outside the frame as unknown."]},
   {heading:"Use a four-pass photo review",paragraphs:["A repeatable review is more reliable than zooming randomly. On the first pass, identify the complete item and confirm quantity. On the second, check the ordered option: colour, size label, design and model. On the third, inspect condition: stains, holes, scratches, cracks, broken hardware, poor alignment or shipping damage. On the fourth, look for missing evidence and decide whether another angle is necessary.","This order keeps small details from distracting you before the basic identity is confirmed. It also creates a short written record. Instead of writing “looks good,” note what the images actually establish: “one black jacket, size L label visible, front and back shown, zipper closed, cuffs not shown.” That sentence is much more useful if a later question arises."],bullets:["Pass 1: whole item and quantity.","Pass 2: selected option and labels.","Pass 3: visible condition and construction.","Pass 4: missing angles and unanswered questions."]},
   {heading:"Shoes: shape, pair consistency and packaging",paragraphs:["For shoes, begin with both shoes in one frame. Compare their overall shape, toe profile, colour and sole length. Then inspect the lateral and medial sides, heel counters, outsole, tongue labels and size labels. Look for obvious glue marks, separation, deep creases, uneven stitching or a pair that does not appear symmetrical. A label photo can confirm the printed size, but it cannot guarantee fit because sizing systems and internal dimensions vary.","Packaging is part of the shipping decision. A box may protect the shoes but can also add weight and volume. PikoBuy’s guide says packaging requests such as minimal or reinforced packaging may be added, while its shipping estimator asks for weight and parcel dimensions. Decide whether the box is important before submitting the parcel, not after international freight has been paid."],bullets:["Ask for both shoes together.","Check labels, outsoles, heel and toe from clear angles.","Decide early whether the retail box is worth shipping."]},
   {heading:"Clothing: measure the garment, not the model",paragraphs:["For T-shirts, hoodies, jackets and trousers, a size tag is only a starting point. Useful evidence includes the garment laid flat, the front and back, the neck or waist label, print or embroidery alignment, closures and category-specific measurements. Chest width and body length matter for tops; waist, rise and inseam matter for trousers; sleeve and shoulder measurements help with jackets and hoodies.","A warehouse image cannot tell you exactly how the fabric feels or how it will behave after washing. Colour can also shift under warehouse lighting. Use the photographs to find obvious mismatches and construction issues, then use measurements to reduce sizing uncertainty. If a measurement is central to your decision and no ruler or tape is visible, do not estimate it from the background tiles."],bullets:["Confirm the size label and requested measurements.","Inspect print, embroidery, seams, cuffs and closures.","Do not infer fabric feel or exact colour from one image."]},
   {heading:"Accessories and electronics need category-specific evidence",paragraphs:["Accessories often look simple but depend on small details: clasp type, hardware colour, chain length, dimensions, stitching and included parts. Ask for a close photo when a small component determines usability. For fragile items, inspect corners, edges and packaging. For electronics, confirm the visible model, plug type, voltage marking, ports and included cables, but remember PikoBuy says professional inspection may not be available for specialist products.","Do not interpret a powered-on screen as proof of long-term performance, battery health or regulatory compliance. Route restrictions may apply to batteries or other sensitive goods, and those rules can vary. Before paying international freight, confirm the current route options inside the account for the exact product type and destination."],bullets:["Check small hardware and included parts.","Confirm visible plug, model and voltage information.","Treat functional safety and route eligibility as separate checks."]},
   {heading:"When an extra photo is worth paying for",paragraphs:["An extra photo is useful when it can answer a specific yes-or-no question that affects return, shipping or use. Good requests are concrete: “photograph the size label,” “show the outsole of both shoes,” “measure chest width from seam to seam,” or “show the plug and voltage label.” A vague request such as “check quality” gives the photographer no clear target and may still leave the important point unresolved.","Prioritise requests by consequence. If the wrong size would make the item unusable, verify the size and key measurements. If a heavy box could change the shipping decision, confirm packaging dimensions or request suitable packing instructions. If a cosmetic detail is minor and the return cost would exceed its importance, record it and move on. The purpose of QC is a better decision, not an endless search for perfect photographs."],bullets:["Ask one question per requested angle.","Focus on details that change keep, return or shipping decisions.","Avoid vague requests for a general opinion."]},
   {heading:"Act quickly when return eligibility matters",paragraphs:["PikoBuy’s published returns policy says qualifying requests generally need to be submitted within five days after the status changes to “In Warehouse,” defined as 120 hours counted from the next hour. Eligibility still depends on the seller’s return guarantee, resale condition, category rules and seller consent. Some categories are excluded or have sealed-packaging requirements, and customer-responsible returns can include domestic shipping plus a service fee.","That makes QC timing practical, not cosmetic. Review photos soon after warehousing, compare them with the order and raise a focused question while the relevant window may still be open. Never promise yourself that every item can be returned. Check the order’s actual status and rules before making a decision."],bullets:["Review soon after the warehouse status appears.","Check eligibility; do not assume every item is returnable.","Keep enough account balance if return charges may apply."]},
   {heading:"The short QC decision checklist",paragraphs:["A sensible final record is brief: ordered option confirmed; quantity confirmed; main angles reviewed; category measurements checked; visible defects recorded; missing evidence listed; packaging decision made; return timing checked. If all decision-critical points are clear, proceed. If one important point is unknown, request evidence before submitting the international parcel.","A spreadsheet is helpful because it keeps the source, selected option, warehouse evidence and shipping decision together. It is not proof of seller quality or authenticity. Use FindSpreadsheet to organise discovery, then make the keep-or-return decision from the current order record, official account information and the photographs actually supplied."],bullets:["Confirmed, not assumed.","Visible evidence, not marketing language.","One documented decision before international shipping."]}
  ]
 },
 {
  slug:"pikobuy-shipping-cost-guide",
  title:"Why a Cheap PikoBuy Find Can Become an Expensive Parcel",
  dek:"A plain-English guide to item price, parcel dimensions, route selection and the costs that appear between a product listing and delivery.",
  label:"SHIPPING",readTime:"13 MIN READ",updated:"Fact-checked August 2026",
  sections:[
   {heading:"The listing price is only the first number",paragraphs:["A low product price can be attractive, but it is not the delivered cost. PikoBuy’s official beginner guide separates the process into a first payment for the purchasing order and a later payment for international shipping after the item reaches the warehouse. Its Terms of Service also say cross-border transactions may involve duties, taxes, brokerage fees or other charges that are the customer’s responsibility.","That means the useful question is not “Is this item cheap?” It is “Does this item still make sense after domestic movement, service-related costs, packing, international freight and possible import charges?” You may not know every number at the discovery stage, but you can identify which items are likely to create uncertainty."],bullets:["First payment: purchasing order.","Second payment: international parcel shipping.","Possible destination charges: duties, taxes or brokerage."]},
   {heading:"What the official shipping estimator asks for",paragraphs:["PikoBuy’s shipping estimate tool asks for the destination country or region, product type, weight in kilograms, and parcel length, width and height in centimetres. Those fields tell you why a price-only spreadsheet is incomplete. Two items with the same purchase price can produce very different shipping choices when one is dense and compact while the other is light but bulky.","Use the estimator as a planning tool, not a guaranteed invoice. The beginner guide says routes differ in delivery time and billing methods. Final packing, warehouse measurements, product restrictions and the route available to your destination can change the result. Save an estimate date and the inputs you used so you know what the number represented."],bullets:["Destination changes available routes.","Product type can affect eligibility.","Weight and all three dimensions matter."]},
   {heading:"Actual weight and parcel volume are different risks",paragraphs:["Actual weight is the measured mass of the packed parcel. Parcel volume describes how much space the package occupies. International carriers may use different billing methods, so a large lightweight parcel can be expensive even when its scale weight looks modest. PikoBuy does not publish one universal formula on the estimator page; the correct billing rule should therefore be checked for the route shown in the user’s account.","The practical lesson is simple. Shoes with boxes, padded jackets, large bags, rigid display packaging and fragile goods can occupy much more space than folded clothing. Record both expected weight and packaging shape. Do not calculate a precise landed cost from product weight alone."],bullets:["Dense item: actual weight may dominate.","Bulky item: dimensions may change the billed amount.","Use the current route’s own billing rule."]},
   {heading:"Packaging can protect value or consume the budget",paragraphs:["PikoBuy’s guide says users can add packaging requests, including minimal or reinforced packaging. These choices have a trade-off. Minimal packaging may reduce bulk, while reinforced packaging may be sensible for fragile or structured goods but can add size and weight. There is no single best choice for every category.","Make the packaging decision from the product’s risk. A T-shirt does not need the same protection as a fragile collectible. A shoe box may matter to one buyer and be unnecessary to another. A liquid, battery or sharp object may face route restrictions regardless of careful packing. Ask what must be protected, what can be removed and what evidence you need before the parcel is submitted."],bullets:["Protect fragile or structured items appropriately.","Remove unnecessary volume only when it does not damage value.","Confirm restricted-item rules before parcel submission."]},
   {heading:"Route choice is a service decision, not a race to the lowest quote",paragraphs:["The official guide says shipping routes differ in delivery time and billing methods. A useful comparison therefore includes more than price: estimated time, tracking, product eligibility, insurance options, size or weight limits and destination coverage. The cheapest displayed route is not automatically suitable for the product or the buyer’s deadline.","PikoBuy’s forwarding terms say parcels are carried by third-party logistics providers and describe unavoidable risks such as customs action, damage, loss and peak-season delay. The platform says it may provide risk alerts and logistics insurance options, but this is not a guarantee of delivery without incident. Read the current route description and insurance terms before paying."],bullets:["Compare route eligibility and limits.","Check timing and tracking expectations.","Understand what insurance does and does not cover."]},
   {heading:"Consolidation works best when the parcel has a plan",paragraphs:["Combining several purchases can spread some parcel costs across more items, but consolidation is not automatically cheaper. One bulky item can change the dimensions of the whole package. A restricted product can reduce available routes. Fragile and heavy goods may require additional protection. The right comparison is the expected total parcel cost divided by the useful items you actually want—not the number of products alone.","Before consolidation, group items by shipping behaviour. Foldable clothing often combines predictably. Shoe boxes, rigid bags and collectibles add shape. Batteries, liquids and electronics need route checks. If one item creates most of the risk, compare shipping it separately, returning it if eligible, or removing unnecessary packaging."],bullets:["Group products by weight, volume and restrictions.","Identify the item driving parcel size.","Compare combined and separate shipment options."]},
   {heading:"Build a landed-cost worksheet before paying freight",paragraphs:["A compact worksheet can prevent optimistic decisions. Record product price, China domestic shipping if shown, service or return-related charges, packed weight, package dimensions, selected route estimate, insurance choice and a placeholder for destination taxes or fees. Mark uncertain numbers rather than silently setting them to zero.","Run a simple stress test. What happens if the parcel is heavier or larger than expected? What if the preferred route is not available? What if a customer-responsible return requires domestic shipping and the published RMB 5 service fee? A purchase does not need perfect certainty, but it should survive a reasonable range of costs."],bullets:["Record the estimate inputs and date.","Keep unknown charges visible.","Test a higher-cost scenario before committing."]},
   {heading:"Know when each decision becomes available",paragraphs:["At discovery, you can judge likely size, weight and restrictions. After purchase, you know the actual ordered option and domestic order status. At warehouse arrival, you can review photos, confirm condition and obtain better weight or packaging information. Only then can you make a stronger route comparison and pay international shipping.","This staged approach matches PikoBuy’s published workflow. It also explains why one headline “shipping price” can be misleading. The parcel does not fully exist until the warehouse has the items and the user chooses how to pack and route them."],bullets:["Discovery: estimate risk.","Warehouse: verify item and parcel data.","Submission: choose route and pay international freight."]},
   {heading:"A short rule for deciding whether the find is still good",paragraphs:["A cheap find remains good when the item is useful, the ordered option is correct, the visible condition is acceptable, the parcel cost fits the budget and the route risk is understood. If the economics depend on an unrealistically low shipping assumption, it is not yet a good deal—it is an incomplete calculation.","Use FindSpreadsheet to discover and organise products, then move from listing price to landed-cost thinking. The goal is not to predict every customs or logistics event. It is to make the hidden variables visible before the second payment, when the international parcel decision becomes real."],bullets:["Judge delivered usefulness, not listing price.","Make weight, dimensions and restrictions visible.","Pay the second payment only after checking the complete parcel decision."]}
  ]
 },
 {
  slug:"pikobuy-spreadsheet-checklist",
  title:"PikoBuy Spreadsheet Checklist: From Source Link to Warehouse",
  dek:"A repeatable research workflow that keeps the source listing, selected option, warehouse evidence, return timing and shipping decision in one record.",
  label:"BEGINNER GUIDE",readTime:"14 MIN READ",updated:"Fact-checked August 2026",
  sections:[
   {heading:"Why a spreadsheet needs a workflow",paragraphs:["A product spreadsheet is useful when it helps a shopper make decisions, not when it simply collects attractive links. PikoBuy’s official beginner guide describes six stages: select an item, search by link or keyword, submit and pay for the purchasing order, review warehouse inspection, choose a route and pay international shipping, then wait for the parcel and tracking. A good spreadsheet should follow the same movement.","Each row should change as the order changes. At first it is a discovery record. After payment it becomes an order record. At warehouse arrival it becomes an evidence and return decision. At parcel submission it becomes a shipping record. Keeping those stages together reduces the chance that a title, price or screenshot is treated as permanently accurate."],bullets:["One row, several decision stages.","Update facts when the order status changes.","Separate discovery data from confirmed warehouse evidence."]},
   {heading:"Step 1: preserve the source before ordering",paragraphs:["PikoBuy tells users to find products on Taobao, Tmall, 1688, Weidian, Yupoo or other platforms and confirm specifications, colour and size. Save enough source information to recognise the item later: source URL, seller or store name, listing title, selected option, quantity, displayed price and the date checked. A screenshot can help when listings change, but it should not replace the live order record.","Write down the exact selection in plain language. “Blue / XL / two pieces” is more useful than an option code that may be hard to interpret later. Record the size-chart measurements that matter for the category. For regulated, restricted or potentially infringing goods, do not proceed simply because a link exists. PikoBuy’s Terms prohibit illegal and infringing products and describe a zero-tolerance anti-counterfeiting policy."],bullets:["Source URL and seller identity.","Exact colour, size, model and quantity.","Date checked and key measurements."]},
   {heading:"Step 2: search with the link, then verify the imported result",paragraphs:["The official guide says a user can paste a product link or keywords into the PikoBuy search box. Link search is usually the stronger starting point because it connects the request to a specific listing, but the imported title, image and options still need to be compared with the source. Keyword results can contain similar-looking products that are not the same model.","Before ordering, compare the selected option and quantity one more time. If the item cannot be found, the guide directs users to customer service. Do not fill gaps by guessing. A short question before payment is cheaper than solving a wrong-option problem after domestic shipping."],bullets:["Prefer a precise source link when available.","Compare imported options with the original listing.","Ask support when the item or option is unclear."]},
   {heading:"Step 3: understand the first payment",paragraphs:["PikoBuy’s guide describes the first payment as payment for the purchasing order after the user selects specifications, colour, size and quantity. It also says prices are subject to the actual purchase and that an out-of-stock order will be refunded. This first payment is not the final delivered cost because international parcel shipping comes later.","In the spreadsheet, separate the item purchase from the later parcel charge. Record the amount actually paid, not only the earlier listing price. Add domestic shipping or visible service-related charges when they appear. Mark the status as ordered, purchased, seller shipped or refunded rather than leaving every row labelled “available.”"],bullets:["Record actual payment, not only advertised price.","Keep international freight in a separate field.","Update stock and refund status when known."]},
   {heading:"Step 4: review warehouse evidence promptly",paragraphs:["The published workflow says the warehouse checks items in, provides photo confirmation and checks for defects. Forwarded goods are unpacked and inspected, while extra detailed photographs may be purchased. When the status changes to “In Warehouse,” compare the images with the row you built earlier: quantity, option, labels, visible condition, measurements and included parts.","Use category-specific checks. Shoes need pair consistency, size labels and sole views. Clothing needs size labels and key measurements. Accessories need dimensions and hardware. Electronics need visible model, plug and voltage information, while professional or specialist functionality may remain outside a normal warehouse inspection. Write what the photos establish and list anything still unknown."],bullets:["Compare warehouse evidence with the saved order.","Use checks appropriate to the category.","Request a specific extra angle only when it affects the decision."]},
   {heading:"Step 5: check return eligibility before time disappears",paragraphs:["PikoBuy’s returns policy says eligible return requests generally must be made within five days after the order becomes “In Warehouse,” calculated as 120 hours from the next hour. Eligibility is not universal. The seller must offer the relevant return guarantee, the item must remain in the required resale condition, category exclusions can apply, and the seller’s consent is still required.","For customer-responsible returns, the published policy lists return shipping to the seller, the seller’s original shipping fee and an RMB 5 service fee. It also says even an originally free-shipping purchase may require the first-delivery fee on return. Seller-responsible problems, such as a wrong option or verified quality issue, are handled differently, although the policy notes that the seller’s position can affect costs. Check the live order rather than assuming an outcome."],bullets:["Note the warehouse timestamp.","Check eligibility and packaging conditions.","Estimate return charges before deciding."]},
   {heading:"Step 6: prepare the parcel and second payment",paragraphs:["After inspection, PikoBuy’s guide says the user chooses a suitable route, submits the parcel and pays the international shipping fee. The shipping estimator uses destination, product type, weight and length, width and height. Record those inputs, the route name, the estimate date, packaging request and insurance choice if offered.","The forwarding terms say third-party logistics providers carry the parcels and identify risks including customs action, loss, damage and peak-season delays. The Terms of Service also place duties, taxes and brokerage charges on the customer. This does not mean every parcel will face a problem; it means a responsible record should not promise a guaranteed delivery time or a fixed final cost."],bullets:["Record packed weight and dimensions.","Compare route rules, time and billing method.","Keep possible import charges outside the product price."]},
   {heading:"Step 7: track the shipment without inventing a deadline",paragraphs:["PikoBuy’s beginner guide says tracking information will be available within three days after the parcel is shipped and reminds users that international shipping takes longer. Record the parcel submission date, dispatch date, tracking number, carrier or route and the latest verified event. Avoid turning an estimate into a promised arrival date.","If tracking pauses, first compare the event time with the route guidance and current account information. Cross-border parcels can have handovers between providers. Keep customer-service conversations and status evidence with the parcel record instead of creating multiple conflicting notes."],bullets:["Save dispatch and tracking details.","Use the latest verified event.","Treat delivery estimates as estimates."]},
   {heading:"The minimum useful spreadsheet fields",paragraphs:["A practical row does not need dozens of decorative columns. The minimum set is: source URL, seller, title, selected option, quantity, source check date, purchase amount, domestic order status, warehouse date, QC result, missing evidence, return deadline, packed weight, dimensions, packaging choice, route, international shipping amount, tracking number and latest status.","Add fields only when they change a decision. For clothing, measurements matter. For electronics, plug and voltage matter. For fragile goods, packaging matters. For every category, keep a short notes field that separates an official platform fact from your own observation. That separation prevents advice from being mistaken for a guarantee."],bullets:["Discovery fields identify the exact item.","Warehouse fields record visible evidence and timing.","Shipping fields record the real parcel decision."]},
   {heading:"A final pre-payment checklist",paragraphs:["Before the first payment, confirm the source, seller, option, quantity and current price. Before the second payment, confirm warehouse evidence, return decision, packaging, weight, dimensions, route rules and the available budget. After dispatch, record tracking rather than rewriting the earlier order row from memory.","This method is intentionally simple. It does not claim that a spreadsheet can guarantee authenticity, seller quality, customs clearance or delivery. It turns scattered information into a dated decision trail. Use FindSpreadsheet for product discovery, then verify each live order through the current PikoBuy account information before paying or shipping."],bullets:["Source verified before purchase.","Warehouse evidence reviewed before parcel submission.","Route and total cost checked before international payment."]}
  ]
 }
];

export const faqRecords=[
 {q:"Is this the official PikoBuy website?",a:"No. This is an independent research guide connected to FindSpreadsheet. Account, payment, return and shipment decisions must be confirmed in your current PikoBuy account."},
 {q:"What does PikoBuy’s published buying process include?",a:"PikoBuy describes six steps: select an item, search by link or keywords, submit and pay for the purchasing order, review warehouse inspection, choose a route and pay international shipping, then wait for the parcel and tracking."},
 {q:"Why are there two payments?",a:"The first payment covers the purchasing order. After warehouse arrival and inspection, the user submits a parcel and makes a separate international shipping payment."},
 {q:"What happens when an item reaches the warehouse?",a:"PikoBuy says the item is checked in, photographed for confirmation and checked for visible defects. Its forwarding terms also say forwarded goods are unpacked and inspected."},
 {q:"Can I request more inspection photos?",a:"PikoBuy’s forwarding terms say users can view inspection photos or purchase additional detailed photos. Ask for a specific label, measurement, angle or part rather than a general quality opinion."},
 {q:"How does PikoBuy estimate international shipping?",a:"The official estimator asks for destination, product type, weight, length, width and height. Routes can differ in timing and billing method, so an estimate should not be treated as a guaranteed final invoice."},
 {q:"Can every warehouse item be returned?",a:"No. Eligibility depends on seller rules, resale condition, category exclusions and seller consent. PikoBuy says eligible applications generally must be submitted within 120 hours after the order enters the warehouse."},
 {q:"What can a customer-responsible return cost?",a:"PikoBuy’s published policy lists return shipping to the seller, the seller’s original shipping fee and an RMB 5 service fee for an unconditional return after warehousing. Check the live order because responsibility and eligibility can change the result."},
 {q:"When should tracking appear?",a:"PikoBuy’s beginner guide says tracking information will be available within three days after dispatch. International delivery still takes time, and a route estimate is not a guaranteed arrival date."},
 {q:"Does a spreadsheet guarantee quality or authenticity?",a:"No. A spreadsheet is a discovery and organisation tool. PikoBuy states that it is not the manufacturer or normally the seller of record, and its terms prohibit counterfeit or infringing goods. Verify the source, order option and warehouse evidence yourself."}
];
