"use client";

import { useEffect, useState } from "react";
import { factualFaq } from "./editorial-content";
import { languageCopy, pageLabels } from "./i18n";
import { localizedArticleBodies } from "./localized-article-bodies";

type Language = "en" | "de" | "fr" | "es" | "it" | "pt" | "nl" | "pl" | "sv";

const categories = [
  ["01", "Shoes", "Footwear, sizing & visible QC", "https://findspreadsheet.com/shoes/"],
  ["02", "Hoodies", "Fabric, measurements & variants", "https://findspreadsheet.com/hoodies-sweaters/"],
  ["03", "T-Shirts", "Fit references & item details", "https://findspreadsheet.com/t-shirts/"],
  ["04", "Jackets", "Layers, hardware & sizing", "https://findspreadsheet.com/jackets/"],
  ["05", "Pants", "Length, waist & fabric notes", "https://findspreadsheet.com/pants-shorts/"],
  ["06", "Hats", "Headwear, measurements & finish", "https://findspreadsheet.com/headwear/"],
  ["07", "Watches", "Finish, dimensions & included parts", "https://findspreadsheet.com/accessories/"],
  ["08", "Electronics", "Compatibility & route restrictions", "https://findspreadsheet.com/electronics/"],
  ["09", "Socks", "Material, pack size & variants", "https://findspreadsheet.com/other-stuff/"],
  ["10", "Other Stuff", "Broader product research", "https://findspreadsheet.com/other-stuff/"],
] as const;

const content: Record<Language, { name: string; nav: string[]; eyebrow: string; title: string; intro: string; primary: string; secondary: string; search: string; searchLabel: string; research: string; categories: string; categoryIntro: string; method: string; regional: string; faq: string; footer: string }> = {
  en: { name:"English",nav:["Home","Categories","Product details","SEO articles","FAQ"],eyebrow:"Independent research edition · Europe & North America",title:"Product research, arranged like an editorial desk.",intro:"A clearer LoloBuy spreadsheet route: understand a listing, collect the right QC questions, then open the live FindSpreadsheet category when you are ready.",primary:"Open FindSpreadsheet",secondary:"Read the research method",search:"Search a product, brand or category",searchLabel:"Search the database",research:"Research before the click",categories:"Browse the research index",categoryIntro:"Ten focused entry points. Every category continues only to the matching FindSpreadsheet route.",method:"The decision path",regional:"Regional lens",faq:"Straight answers",footer:"Independent public inspection build · no formal domain deployment" },
  de: { name:"Deutsch",nav:["Start","Kategorien","Produktdetails","SEO-Artikel","FAQ"],eyebrow:"Unabhängige Recherche · Europa & Nordamerika",title:"Produktrecherche wie an einem Redaktionstisch.",intro:"Ein klarerer LoloBuy-Spreadsheet-Weg: Listing verstehen, die richtigen QC-Fragen sammeln und erst dann die passende FindSpreadsheet-Kategorie öffnen.",primary:"FindSpreadsheet öffnen",secondary:"Methode lesen",search:"Produkt, Marke oder Kategorie suchen",searchLabel:"Datenbank durchsuchen",research:"Recherche vor dem Klick",categories:"Rechercheindex",categoryIntro:"Zehn klare Einstiege. Jede Kategorie führt nur zur passenden FindSpreadsheet-Route.",method:"Der Entscheidungsweg",regional:"Regionaler Fokus",faq:"Klare Antworten",footer:"Öffentliche Prüffassung · keine formale Domain-Bereitstellung" },
  fr: { name:"Français",nav:["Accueil","Catégories","Détails produit","Articles SEO","FAQ"],eyebrow:"Recherche indépendante · Europe & Amérique du Nord",title:"La recherche produit, pensée comme un bureau éditorial.",intro:"Un parcours LoloBuy Spreadsheet plus clair : comprendre une fiche, préparer les bonnes questions QC, puis ouvrir la catégorie FindSpreadsheet utile.",primary:"Ouvrir FindSpreadsheet",secondary:"Lire la méthode",search:"Rechercher un produit, une marque ou une catégorie",searchLabel:"Rechercher dans la base",research:"Rechercher avant de cliquer",categories:"Index de recherche",categoryIntro:"Dix points d’entrée ciblés. Chaque catégorie mène uniquement vers la route FindSpreadsheet correspondante.",method:"Le chemin de décision",regional:"Perspective régionale",faq:"Réponses directes",footer:"Version publique de contrôle · aucun domaine officiel publié" },
  es: { name:"Español",nav:["Inicio","Categorías","Detalles","Artículos SEO","FAQ"],eyebrow:"Investigación independiente · Europa y Norteamérica",title:"Investigación de productos con criterio editorial.",intro:"Una ruta LoloBuy Spreadsheet más clara: entiende una ficha, reúne las preguntas QC adecuadas y abre la categoría de FindSpreadsheet cuando estés listo.",primary:"Abrir FindSpreadsheet",secondary:"Leer el método",search:"Buscar producto, marca o categoría",searchLabel:"Buscar en la base",research:"Investiga antes de hacer clic",categories:"Índice de investigación",categoryIntro:"Diez puntos de entrada. Cada categoría continúa únicamente hacia la ruta correspondiente de FindSpreadsheet.",method:"La ruta de decisión",regional:"Enfoque regional",faq:"Respuestas claras",footer:"Versión pública de revisión · sin despliegue formal de dominio" },
  it: { name:"Italiano",nav:["Home","Categorie","Dettagli prodotto","Articoli SEO","FAQ"],eyebrow:"Ricerca indipendente · Europa e Nord America",title:"Ricerca prodotto, come su una scrivania editoriale.",intro:"Un percorso LoloBuy Spreadsheet più chiaro: capisci una scheda, prepara le giuste domande QC e poi apri la categoria FindSpreadsheet utile.",primary:"Apri FindSpreadsheet",secondary:"Leggi il metodo",search:"Cerca prodotto, marchio o categoria",searchLabel:"Cerca nel database",research:"Ricerca prima del clic",categories:"Indice di ricerca",categoryIntro:"Dieci ingressi mirati. Ogni categoria porta solo alla relativa rotta FindSpreadsheet.",method:"Il percorso decisionale",regional:"Focus regionale",faq:"Risposte dirette",footer:"Versione pubblica di controllo · nessun dominio formale pubblicato" },
  pt: { name:"Português",nav:["Início","Categorias","Detalhes","Artigos SEO","FAQ"],eyebrow:"Pesquisa independente · Europa e América do Norte",title:"Pesquisa de produto como uma mesa editorial.",intro:"Um caminho LoloBuy Spreadsheet mais claro: compreenda a listagem, reúna as perguntas certas de QC e abra a categoria FindSpreadsheet quando estiver pronto.",primary:"Abrir FindSpreadsheet",secondary:"Ler o método",search:"Pesquisar produto, marca ou categoria",searchLabel:"Pesquisar a base",research:"Pesquise antes do clique",categories:"Índice de pesquisa",categoryIntro:"Dez pontos de entrada. Cada categoria segue apenas para a rota FindSpreadsheet correspondente.",method:"O caminho da decisão",regional:"Foco regional",faq:"Respostas diretas",footer:"Versão pública para inspeção · sem implantação de domínio formal" },
  nl: { name:"Nederlands",nav:["Home","Categorieën","Productdetails","SEO-artikelen","FAQ"],eyebrow:"Onafhankelijk onderzoek · Europa & Noord-Amerika",title:"Productonderzoek, opgezet als een redactie-bureau.",intro:"Een duidelijkere LoloBuy Spreadsheet-route: begrijp een listing, verzamel de juiste QC-vragen en open daarna de relevante FindSpreadsheet-categorie.",primary:"Open FindSpreadsheet",secondary:"Lees de methode",search:"Zoek een product, merk of categorie",searchLabel:"Zoek in de database",research:"Onderzoek vóór de klik",categories:"Onderzoeksindex",categoryIntro:"Tien gerichte ingangen. Elke categorie gaat alleen naar de juiste FindSpreadsheet-route.",method:"Het beslispad",regional:"Regionale focus",faq:"Duidelijke antwoorden",footer:"Openbare inspectieversie · geen formele domeinuitrol" },
  pl: { name:"Polski",nav:["Start","Kategorie","Szczegóły","Artykuły SEO","FAQ"],eyebrow:"Niezależny research · Europa i Ameryka Północna",title:"Research produktu ułożony jak redakcyjne biurko.",intro:"Czytelniejsza ścieżka LoloBuy Spreadsheet: poznaj ofertę, przygotuj właściwe pytania QC, a następnie przejdź do odpowiedniej kategorii FindSpreadsheet.",primary:"Otwórz FindSpreadsheet",secondary:"Poznaj metodę",search:"Szukaj produktu, marki lub kategorii",searchLabel:"Przeszukaj bazę",research:"Najpierw research, potem klik",categories:"Indeks researchu",categoryIntro:"Dziesięć konkretnych wejść. Każda kategoria prowadzi wyłącznie do pasującej trasy FindSpreadsheet.",method:"Ścieżka decyzji",regional:"Perspektywa regionalna",faq:"Proste odpowiedzi",footer:"Publiczna wersja kontrolna · bez wdrożenia właściwej domeny" },
  sv: { name:"Svenska",nav:["Hem","Kategorier","Produktdetaljer","SEO-artiklar","FAQ"],eyebrow:"Oberoende research · Europa & Nordamerika",title:"Produktresearch, organiserad som ett redaktionellt skrivbord.",intro:"En tydligare LoloBuy Spreadsheet-väg: förstå en annons, samla rätt QC-frågor och öppna sedan rätt FindSpreadsheet-kategori.",primary:"Öppna FindSpreadsheet",secondary:"Läs metoden",search:"Sök produkt, varumärke eller kategori",searchLabel:"Sök i databasen",research:"Research före klicket",categories:"Researchindex",categoryIntro:"Tio fokuserade ingångar. Varje kategori fortsätter endast till rätt FindSpreadsheet-rutt.",method:"Beslutsvägen",regional:"Regionalt fokus",faq:"Raka svar",footer:"Offentlig granskningsversion · ingen formell domändistribution" },
};

const verifiedGuide = [
  "LoloBuy Shopping Workflow: What to Check Before You Submit a Parcel",
  "Reviewed September 2026 · Independent guide",
  "LoloBuy presents its public service as a one-stop shopping workflow: select products that are stored in the warehouse, submit them, and use its global shipping service for delivery. That description is useful, but it should not be read as a promise about a particular seller, item, shipping line, customs result, delivery date, or product quality. A careful buyer treats each stage as a separate decision with its own evidence.",
  "Start with the listing, not the checkout. Record the item name, selected option, size information, seller images and displayed price. If the listing has variants, make the choice explicit rather than assuming the title covers every colour or version. Screenshots and a short note are practical because listings can change. This is also the point to decide what would make the item unsuitable: a missing measurement, an unclear material, a different visible detail, or a restricted destination.",
  "The warehouse stage is where the platform's public workflow becomes relevant. An item being stored is not the same as an item being approved. Check the visible record, option and quantity against the order you intended to make. When images or inspection information are available, use them to compare observable details with the listing. Photos can show a label, colour, stitching, shape or obvious damage; they cannot prove authenticity, long-term durability, correct fit, or a shipping outcome.",
  "Make QC questions narrow and answerable. Instead of asking whether an item is good, ask whether a logo is positioned as shown, whether a measurement can be confirmed, whether a visible mark is present, or whether the ordered option matches the warehouse record. A precise question produces evidence you can use. If a critical point remains unclear, pause before parcel submission. A faster decision is not necessarily a better decision.",
  "Parcel submission is a separate checkpoint. LoloBuy's public description says customers select products stored in the warehouse and submit them for global shipping. Before doing that, verify the complete contents, destination, available line description, declared options shown in the live flow, and any current restriction displayed for that route. Do not rely on an old screenshot, a social-media claim, or another buyer's experience as a guarantee for your own parcel.",
  "Consolidation can make a shipment easier to manage, but it does not erase differences between items. Consider actual dimensions, packaging, fragile elements and route restrictions before combining products. Keep an item-level list of what is included. That list is useful if you later need to compare a warehouse record, a parcel record and the received contents. Avoid treating estimates as final numbers until the live submission screen provides the applicable information.",
  "Shipping choices should be made for the destination, not for a slogan. A line may be available today and unavailable tomorrow; rules, costs and handling conditions can change. Read the current line details at the time of submission and choose based on what is displayed for your destination. Neither this guide nor a product spreadsheet can predict customs treatment, taxes, carrier delays, loss, or delivery time. Those are variables, not claims a responsible guide should make.",
  "Tracking is useful after the parcel enters the shipping process, but the first update may not mean the parcel is already moving through every part of the route. Keep the parcel number, submission date and a copy of the selected route details. When an update appears, interpret it as a status signal, not a forecast. If the status is unclear, use the platform's current support route and provide the exact parcel reference rather than a general description.",
  "Payment and checkout deserve the same discipline as the product and parcel steps. Use only the payment choices and order totals shown in the live LoloBuy flow, then keep the transaction reference with your listing and parcel notes. Do not treat a third-party screenshot as a current policy, and do not let a sale message replace a check of the actual item, destination and order fields. A record of what you selected is more useful than a memory if you later need to identify an inconsistency.",
  "A sensible research workflow also separates a platform's role from a seller's role. A platform may organize purchase, warehouse and shipping stages, while the listing's description, variants and product-specific evidence remain tied to the product source. That distinction helps avoid a common mistake: turning an ordinary listing claim into a platform guarantee. If an item depends on a precise measurement, material or visible feature, make that requirement explicit before warehouse submission rather than assuming a general workflow will answer it.",
  "For EU and North American buyers, destination remains part of the decision from the beginning. The platform's stated global shipping service does not remove the need to read current route information, import obligations or carrier notices applicable to the destination. Use the live checkout and official destination guidance for the current order. This guide intentionally does not estimate duty, VAT, delivery days or clearance probability, because those outcomes are not fixed product features and can change independently of a warehouse record.",
  "For research purposes, separate platform facts from personal judgments. The observable public facts are the warehouse-to-submission workflow and the platform's stated global shipping service. Your judgment about an individual item should come from the live listing, selected variant and visible evidence. Your judgment about a parcel should come from the current submission screen and destination-specific conditions. This division keeps a guide useful without turning uncertain outcomes into marketing claims.",
  "The practical checklist is simple: save the listing details; confirm option and quantity; review available visual evidence; ask focused questions; check destination and route information at submission; retain the parcel reference; and review tracking as it develops. When you are ready to research products, use the FindSpreadsheet search or a relevant category route. This independent site does not place orders, accept payments, or represent LoloBuy customer support."
];

export default function Home() {
  const [language, setLanguage] = useState<Language>("en");
  const [compactMobile, setCompactMobile] = useState(false);
  useEffect(() => {
    const requested = new URLSearchParams(window.location.search).get("lang") as Language | null;
    const remembered = window.localStorage.getItem("lolobuysheet-language") as Language | null;
    if (requested && content[requested]) setLanguage(requested);
    else if (remembered && content[remembered]) setLanguage(remembered);
    const media = window.matchMedia("(max-width: 500px)");
    const sync = () => setCompactMobile(media.matches);
    sync(); media.addEventListener("change", sync); return () => media.removeEventListener("change", sync);
  }, []);
  const t = content[language];
  const shared = languageCopy[language];
  const labels = pageLabels[language];
  const homeFaq = [...factualFaq[language], { question: shared.explore, answer: shared.independent }, { question: shared.focus, answer: shared.source }];
  const switchLanguage = (next: Language) => {
    window.localStorage.setItem("lolobuysheet-language", next);
    const destination = new URL(window.location.href);
    destination.searchParams.set("lang", next);
    window.location.assign(destination.toString());
  };
  const route = (path: string) => `${path}${path.includes("?") ? "&" : "?"}lang=${language}`;
  return <main translate="no">
    <header className="site-header">
      <a className="brand" href="#top" aria-label="LoloBuy Sheet Poland home"><img className="brand-logo" src="/lolobuy-logo.png" alt="LoloBuy"/><strong>Sheet<span className="brand-muted">.pl</span></strong></a>
      <nav>{t.nav.map((item, i) => <a key={item} href={route(["/", "/categories/", "/product-details/", "/seo-articles/", "/faq/"][i])}>{item}</a>)}</nav>
      <label className="language" translate="no"><span>Language</span><select value={language} onChange={e => switchLanguage(e.target.value as Language)}>{(Object.keys(content) as Language[]).map(key => <option key={key} value={key}>{key.toUpperCase()} · {content[key].name}</option>)}</select></label>
    </header>
    <section id="top" className="hero">
      <div className="hero-copy"><p className="eyebrow">{t.eyebrow}</p><h1>{t.title}</h1><p className="intro">{t.intro}</p><div className="hero-actions"><a className="button button-lime" href="https://findspreadsheet.com/">{t.primary}<span>↗</span></a><a className="button button-ghost" href="#section-2">{t.secondary}</a></div><form className="search" action="https://findspreadsheet.com/search.html" method="get"><label htmlFor="query">{t.search}</label><input type="hidden" name="channelid" value="2"/><div><input id="query" name="keywords" placeholder={t.search} required/><button type="submit">{t.searchLabel} <span>→</span></button></div></form></div>
      <div className="hero-art"><img src="/research-atlas.png" alt="Research desk"/><div className="art-stamp">{labels.check}<br/><b>09 / 2026</b></div><div className="art-caption">{shared.independent}</div></div>
    </section>
    <section className="signal-strip"><div><b>09</b><span>{shared.focus}</span></div><div><b>10</b><span>{labels.categoryCount}</span></div><div><b>01</b><span>{shared.explore}: FindSpreadsheet</span></div><p>{shared.note}</p></section>
    <section id="section-2" className="method-section"><div className="section-heading"><p className="eyebrow">01 / {labels.check}</p><h2>{shared.guide}</h2></div><div className="method-grid">{labels.guideSteps.map((step,index)=><article key={step}><span>{String(index+1).padStart(2,"0")}</span><h3>{step}</h3><p>{index===0?shared.sectionBody:index===1?shared.faqBody:shared.guideBody}</p></article>)}</div></section>
    <section id="section-1" className="category-section"><div className="section-heading split"><div><p className="eyebrow">02 / {labels.categoryCount}</p><h2>{t.categories}</h2></div><p>{t.categoryIntro}</p></div><div className="category-grid">{categories.map(([n,,description,href],index) => <a key={n} className="category-card" href={href}><span>{n}</span><div><h3>{labels.categoryNames[index]}</h3><p>{language==="en"?description:shared.explore}</p></div><i>↗</i></a>)}</div></section>
    <section id="section-3" className="details-section"><div className="section-heading"><p className="eyebrow">03 / {labels.buyerCheck}</p><h2>{shared.guide}</h2></div><div className="details-layout"><div className="checkerboard">{labels.detailCards.map(card=><span key={card}>{card}</span>)}</div><div><p className="large-copy">{shared.guideBody} {shared.faqBody}</p><a className="text-link" href="https://findspreadsheet.com/">{shared.explore} <span>↗</span></a></div></div></section>
    <section id="section-4" className="articles-section"><div className="section-heading split"><div><p className="eyebrow">04 / {labels.reading}</p><h2>{language==="en"?verifiedGuide[0]:labels.articleTitle}</h2></div><p>{language==="en"?verifiedGuide[1]:shared.source}</p></div><details className="long-article" open={!compactMobile}><summary>{language==="en"?"Read the complete practical guide":shared.article}</summary>{language==="en"?verifiedGuide.slice(2).map((paragraph,index)=><p key={index}>{paragraph}</p>):localizedArticleBodies[language][0].sections.flatMap(section=>[<h3 key={section.heading}>{section.heading}</h3>,...section.paragraphs.map((paragraph,index)=><p key={section.heading+index}>{paragraph}</p>)])}<a href="https://findspreadsheet.com/">{shared.explore} →</a></details></section>
    <section id="section-5" className="faq-section"><div className="section-heading"><p className="eyebrow">05 / {labels.answers}</p><h2>{t.faq}</h2></div><div className="faq-grid">{homeFaq.map((item,index)=><details key={item.question} open={index===0}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</div></section>
    <footer><div className="brand footer-brand"><img className="brand-logo" src="/lolobuy-logo.png" alt="LoloBuy"/><strong>Sheet<span className="brand-muted">.pl</span></strong></div><p>{t.footer}</p><a href="https://findspreadsheet.com/">FindSpreadsheet.com ↗</a></footer>
  </main>;
}
