import type { Metadata } from "next";
import { PageHero, PageShell, SourceNote } from "../components";
export const metadata: Metadata = { title: "LoloBuy Beginner Guide", description: "A source-grounded beginner workflow for discovering products, submitting links, reviewing warehouse QC and planning international shipping.", alternates: { canonical: "/guides" } };
export default function GuidesPage() { return <PageShell><div className="article-wrap"><PageHero eyebrow="Beginner guide · 12 min read" title="From a product link to a considered parcel." intro="A practical workflow for buyers who want to understand each decision before paying for international shipping."/><div className="article-layout"><article className="prose">
  <h2>1. Begin with the original listing, not the hype</h2><p>A spreadsheet is a discovery layer. Use it to narrow a large marketplace into a manageable shortlist, then open the product record and compare the visible images, seller price, options and original source link. A recognisable title or attractive cover image is not evidence that the item will match your expectations.</p>
  <h2>2. Submit a supported marketplace link</h2><p>LoloBuy’s current purchase guide describes two starting methods: paste a product link from supported Chinese marketplaces, or search by product name inside the platform. The guide names Taobao, Tmall, JD.com, Yupoo and Weidian among its examples. Some pages can be captured automatically; others may require manually supplied order details.</p>
  <SourceNote>This description is based on LoloBuy’s official “How to purchase” page. Interface wording and supported sources may change, so confirm the live order screen.</SourceNote>
  <h2>3. Separate product cost from parcel cost</h2><p>The product price is only one component. Buyers should expect domestic freight where applicable, optional services, packaging choices, international delivery and possible destination taxes. Do not treat a spreadsheet’s USD conversion as a complete landed-cost quote.</p>
  <h2>4. Use warehouse photos as a decision checkpoint</h2><p>LoloBuy’s public information confirms warehouse quality inspection with photos. Use those images to review visible identity, option, quantity, damage and details shown in the available views. Do not assume one fixed photo count or treat the images as a laboratory test: they cannot confirm hidden materials, authenticity, long-term durability or every measurement.</p>
  <h2>5. Build the parcel only after checking route rules</h2><p>Shipping availability depends on destination, item category, weight, dimensions and current route rules. Compare routes at the moment you submit the parcel. Read the declared-value instructions carefully and follow the laws and customs rules of your destination.</p>
  <h2>6. Keep a small audit trail</h2><p>Save the original listing URL, selected option, paid product price, warehouse photographs, parcel weight and tracking number. That record makes it easier to explain a mismatch, compare future orders and avoid confusing similarly named listings.</p>
</article><aside className="article-side"><strong>Buyer checklist</strong><ol><li>Open the source listing</li><li>Confirm style and size</li><li>Record the seller price</li><li>Review every QC image</li><li>Check route restrictions</li><li>Verify chargeable weight</li><li>Keep order evidence</li></ol><a href="https://findspreadsheet.com/AllProducts/" target="_blank" rel="noopener">Start in the database ↗</a></aside></div></div></PageShell> }
