"use client";

import { SiteHeader, useSiteLocale, type Locale } from "@/components/site-header";

const copy: Record<Locale, { title: string; intro: string; cards: [string, string, string]; detail: string; open: string }> = {
  en:{title:"Product details before you open the database.",intro:"Use these three checks to compare a listing with the evidence you can actually see.",cards:["Identity and option","Visible condition","Parcel readiness"],detail:"Record the exact style, size, colour and quantity before comparing photos.",open:"Open FindSpreadsheet"},
  de:{title:"Produktdetails vor der Datenbank.",intro:"Nutze diese drei Prüfungen, um ein Angebot mit sichtbaren Belegen zu vergleichen.",cards:["Identität und Option","Sichtbarer Zustand","Paketbereitschaft"],detail:"Notiere Stil, Größe, Farbe und Menge vor dem Fotovergleich.",open:"FindSpreadsheet öffnen"},
  fr:{title:"Les détails produit avant la base.",intro:"Utilisez ces trois contrôles pour comparer une annonce aux éléments visibles.",cards:["Identité et option","État visible","Préparation du colis"],detail:"Notez le style, la taille, la couleur et la quantité avant les photos.",open:"Ouvrir FindSpreadsheet"},
  es:{title:"Detalles del producto antes de la base.",intro:"Usa estas tres comprobaciones para comparar un anuncio con evidencia visible.",cards:["Identidad y opción","Estado visible","Preparación del paquete"],detail:"Anota estilo, talla, color y cantidad antes de comparar fotos.",open:"Abrir FindSpreadsheet"},
  it:{title:"Dettagli del prodotto prima del database.",intro:"Usa questi tre controlli per confrontare un annuncio con le prove visibili.",cards:["Identità e opzione","Condizione visibile","Prontezza del pacco"],detail:"Annota stile, taglia, colore e quantità prima delle foto.",open:"Apri FindSpreadsheet"},
  pt:{title:"Detalhes do produto antes da base.",intro:"Use estas três verificações para comparar um anúncio com evidência visível.",cards:["Identidade e opção","Condição visível","Preparação da encomenda"],detail:"Registe estilo, tamanho, cor e quantidade antes das fotos.",open:"Abrir FindSpreadsheet"},
  nl:{title:"Productdetails vóór de database.",intro:"Gebruik deze drie controles om een aanbieding met zichtbaar bewijs te vergelijken.",cards:["Identiteit en optie","Zichtbare staat","Pakketgereedheid"],detail:"Noteer stijl, maat, kleur en aantal vóór je foto's vergelijkt.",open:"Open FindSpreadsheet"},
  pl:{title:"Szczegóły produktu przed bazą.",intro:"Użyj tych trzech kontroli, aby porównać ofertę z widocznymi dowodami.",cards:["Tożsamość i wariant","Widoczny stan","Gotowość paczki"],detail:"Zapisz styl, rozmiar, kolor i liczbę przed porównaniem zdjęć.",open:"Otwórz FindSpreadsheet"},
  sv:{title:"Produktdetaljer före databasen.",intro:"Använd dessa tre kontroller för att jämföra en annons med synliga bevis.",cards:["Identitet och val","Synligt skick","Paketredo"],detail:"Skriv ner stil, storlek, färg och antal före bildjämförelsen.",open:"Öppna FindSpreadsheet"}
};
export default function ProductDetails(){const locale=useSiteLocale();const t=copy[locale];return <main className="min-h-screen bg-[#e8ebf4] text-[#10213b]"><SiteHeader/><section className="mx-auto max-w-7xl px-5 pb-16 pt-14 sm:px-8 lg:px-12"><p className="text-xs font-extrabold tracking-[.16em] text-[#ff6947]">PRODUCT RESEARCH</p><h1 className="mt-3 max-w-3xl text-4xl font-black tracking-[-.06em] sm:text-6xl">{t.title}</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-[#40506d]">{t.intro}</p><div className="mt-10 grid gap-4 md:grid-cols-3">{t.cards.map((card,i)=><article key={card} className="min-h-64 rounded-3xl border border-[#cbd3e6] bg-white p-7"><span className="text-4xl font-black text-[#ff6947]">0{i+1}</span><h2 className="mt-12 text-2xl font-extrabold">{card}</h2><p className="mt-4 leading-relaxed text-[#5b6680]">{t.detail}</p></article>)}</div><a href="https://findspreadsheet.com" className="mt-10 inline-flex min-h-12 items-center rounded-xl bg-[#1647cf] px-5 text-sm font-bold text-white">{t.open} <span className="ml-2">↗</span></a></section></main>}
