/* Localised, indexable topic-page renderer. All discovery actions stay on FindSpreadsheet. */
(function () {
  var topic = document.body.getAttribute('data-topic') || 'shoes';
  var page = {
    shoes: { slug: 'shoes-spreadsheet', external: 'https://findspreadsheet.com/shoes/' },
    hoodies: { slug: 'hoodies-jackets', external: 'https://findspreadsheet.com/hoodies-sweaters/' },
    budget: { slug: 'budget-finds', external: 'https://findspreadsheet.com/AllProducts/' },
    designer: { slug: 'designer-finds', external: 'https://findspreadsheet.com/AllProducts/' },
    qc: { slug: 'qc-guide', external: 'details.html' }
  }[topic];

  var catalogue = {
    en: {
      home: 'Home', categories: 'Product Categories', guide: 'Research guide', open: 'Open FindSpreadsheet',
      names: { shoes: 'Shoes research route', hoodies: 'Hoodies & jackets research route', budget: 'Budget product research', designer: 'Designer product research', qc: 'QC photo guide' },
      intro: {
        shoes: 'Use a focused shoes route to compare the original listing, selected size and visible product evidence before you continue.',
        hoodies: 'Use this clothing route to keep fit, fabric, colour and seller-listing details together before you continue.',
        budget: 'A budget route works best when every candidate has a visible price, exact variation and a short reason for being on your list.',
        designer: 'Use this route for careful product research. Confirm the seller, the exact listing and any authenticity or authorisation claims before purchase.',
        qc: 'QC photos are useful evidence of visible details. They are not a guarantee of specialised testing, delivery timing or customs outcomes.'
      },
      sections: ['What to record', 'How to compare', 'Next research step'],
      points: {
        shoes: ['Record the exact model, colourway, size system and requested variation from the original listing.', 'Compare only like-for-like listings: visible photos, measurements, materials, seller notes and the current shown price.', 'Open the shoes category and search with the exact model or feature that matters to you.'],
        hoodies: ['Record the garment type, colour, size chart, fabric claim and selected variation.', 'Compare measurements and visible details rather than assuming two similar-looking listings are equivalent.', 'Open the hoodies and sweaters category with the product, fabric or fit term you need.'],
        budget: ['Record the displayed item price, selected variation and the listing date you checked.', 'Keep item price separate from parcel, service, tax or shipping costs that may change later.', 'Open the database and compare current listings using the product and price-range words that matter.'],
        designer: ['Record the exact seller, product description, variation and any claim you need to verify.', 'Do not treat a name, image or category label as proof of authenticity, authorisation, quality or availability.', 'Continue in the database only after the original seller listing and product details are clear.'],
        qc: ['Check that photos match the requested variation and show the details that would affect your decision.', 'Use visible evidence for visible facts; ask for additional detail when a photo cannot answer a specific question.', 'When ready, return to the product details checklist and continue product discovery in FindSpreadsheet.']
      },
      related: 'Related research routes'
    },
    de: { home:'Startseite',categories:'Produktkategorien',guide:'Rechercheleitfaden',open:'FindSpreadsheet öffnen',names:{shoes:'Schuhrecherche',hoodies:'Hoodies- und Jackenrecherche',budget:'Preisbewusste Produktrecherche',designer:'Designer-Produktrecherche',qc:'QC-Fotoleitfaden'},intro:{shoes:'Nutzen Sie diese Schuhroute, um Originalanzeige, gewählte Größe und sichtbare Produktinformationen vor dem Fortfahren zu vergleichen.',hoodies:'Diese Bekleidungsroute hält Passform, Stoff, Farbe und Angaben der Verkäuferanzeige vor dem Fortfahren zusammen.',budget:'Eine preisbewusste Recherche funktioniert am besten mit sichtbarem Preis, exakter Variante und einem kurzen Grund für jeden Eintrag.',designer:'Nutzen Sie diese Route für sorgfältige Produktrecherche. Prüfen Sie Verkäufer, Originalanzeige sowie Angaben zu Echtheit oder Berechtigung vor einem Kauf.',qc:'QC-Fotos sind Nachweise sichtbarer Details. Sie garantieren keine Spezialprüfung, Lieferzeit oder Zollergebnis.'},sections:['Was notieren','Wie vergleichen','Nächster Schritt'],points:{shoes:['Modell, Farbe, Größensystem und gewählte Variante aus der Originalanzeige notieren.','Nur vergleichbare Anzeigen anhand sichtbarer Fotos, Maße, Materialien und aktuellem Preis vergleichen.','Die Schuhkategorie mit Modell oder gewünschtem Merkmal öffnen.'],hoodies:['Kleidungsart, Farbe, Größentabelle, Stoffangabe und Variante notieren.','Maße und sichtbare Details vergleichen, statt ähnliche Anzeigen gleichzusetzen.','Die Kategorie Hoodies und Pullover mit passendem Suchbegriff öffnen.'],budget:['Sichtbaren Artikelpreis, Variante und Prüfdaten notieren.','Artikelpreis von später veränderlichen Paket-, Service-, Steuer- oder Versandkosten trennen.','Die Datenbank mit Produkt- und Preisbereichsbegriffen durchsuchen.'],designer:['Verkäufer, Beschreibung, Variante und zu prüfende Angabe notieren.','Name, Bild oder Kategorie sind kein Beweis für Echtheit, Berechtigung, Qualität oder Verfügbarkeit.','Erst nach Prüfung der Originalanzeige in der Datenbank fortfahren.'],qc:['Prüfen, ob Fotos die gewählte Variante und entscheidungsrelevante Details zeigen.','Sichtbare Nachweise nur für sichtbare Fakten verwenden und bei Bedarf weitere Details anfragen.','Danach zur Produktdetails-Checkliste und zu FindSpreadsheet zurückkehren.']},related:'Verwandte Recherchewege'},
    fr: { home:'Accueil',categories:'Catégories',guide:'Guide de recherche',open:'Ouvrir FindSpreadsheet',names:{shoes:'Recherche chaussures',hoodies:'Recherche sweats et vestes',budget:'Recherche à petit budget',designer:'Recherche produits créateurs',qc:'Guide des photos QC'},intro:{shoes:'Cette route chaussures permet de comparer l’annonce d’origine, la taille choisie et les éléments visibles avant de continuer.',hoodies:'Cette route vêtements rassemble coupe, matière, couleur et détails de l’annonce avant de continuer.',budget:'Une recherche à petit budget est plus fiable lorsque chaque choix comporte un prix visible, une variante précise et une raison courte.',designer:'Utilisez cette route pour une recherche attentive. Vérifiez le vendeur, l’annonce exacte et toute affirmation d’authenticité ou d’autorisation avant achat.',qc:'Les photos QC montrent des détails visibles. Elles ne garantissent ni contrôle spécialisé, ni délai, ni résultat douanier.'},sections:['À noter','Comment comparer','Étape suivante'],points:{shoes:['Notez modèle, couleur, système de tailles et variante choisis dans l’annonce d’origine.','Comparez uniquement des annonces équivalentes : photos, mesures, matières, notes vendeur et prix affiché.','Ouvrez la catégorie chaussures avec le modèle ou le critère recherché.'],hoodies:['Notez type de vêtement, couleur, guide des tailles, matière et variante.','Comparez mesures et détails visibles au lieu de supposer que deux annonces se valent.','Ouvrez la catégorie sweats avec le terme produit, matière ou coupe utile.'],budget:['Notez le prix affiché, la variante et la date de vérification.','Séparez le prix de l’article des coûts de colis, service, taxes ou livraison susceptibles de changer.','Recherchez dans la base par produit et fourchette de prix.'],designer:['Notez vendeur, description, variante et affirmation à vérifier.','Un nom, une image ou une catégorie ne prouvent pas authenticité, autorisation, qualité ou disponibilité.','Continuez seulement après avoir vérifié l’annonce d’origine.'],qc:['Vérifiez que les photos correspondent à la variante et montrent les détails importants.','Utilisez une preuve visible pour un fait visible et demandez plus de détails si nécessaire.','Retournez ensuite à la liste de contrôle et à FindSpreadsheet.']},related:'Routes associées'},
    es: { home:'Inicio',categories:'Categorías',guide:'Guía de investigación',open:'Abrir FindSpreadsheet',names:{shoes:'Ruta de investigación de calzado',hoodies:'Ruta de sudaderas y chaquetas',budget:'Investigación de productos económicos',designer:'Investigación de productos de diseño',qc:'Guía de fotos QC'},intro:{shoes:'Usa esta ruta de calzado para comparar la ficha original, la talla elegida y la evidencia visible antes de continuar.',hoodies:'Esta ruta de ropa reúne ajuste, tejido, color y detalles de la ficha antes de continuar.',budget:'Una investigación económica funciona mejor si cada opción tiene precio visible, variante exacta y una razón breve.',designer:'Usa esta ruta para investigar con cuidado. Verifica vendedor, ficha exacta y cualquier afirmación de autenticidad o autorización antes de comprar.',qc:'Las fotos QC sirven como evidencia de detalles visibles. No garantizan pruebas especializadas, plazos ni resultados de aduana.'},sections:['Qué anotar','Cómo comparar','Siguiente paso'],points:{shoes:['Anota modelo, color, sistema de tallas y variante elegida de la ficha original.','Compara solo fichas equivalentes: fotos, medidas, materiales, notas y precio actual.','Abre la categoría de calzado con el modelo o rasgo que buscas.'],hoodies:['Anota tipo de prenda, color, tabla de tallas, tejido y variante.','Compara medidas y detalles visibles sin asumir que dos fichas parecidas son iguales.','Abre la categoría de sudaderas con el término de producto, tejido o ajuste.'],budget:['Anota precio mostrado, variante y fecha de revisión.','Separa el precio del artículo de posibles costes posteriores de paquete, servicio, impuestos o envío.','Busca en la base por producto y rango de precio.'],designer:['Anota vendedor, descripción, variante y la afirmación que deseas comprobar.','Un nombre, imagen o etiqueta no prueban autenticidad, autorización, calidad ni disponibilidad.','Continúa solo tras revisar la ficha original.'],qc:['Comprueba que las fotos coinciden con la variante y muestran los detalles relevantes.','Usa evidencia visible para hechos visibles y pide más detalle cuando sea necesario.','Después vuelve a la lista de detalles y a FindSpreadsheet.']},related:'Rutas relacionadas'},
    it: { home:'Home',categories:'Categorie',guide:'Guida alla ricerca',open:'Apri FindSpreadsheet',names:{shoes:'Ricerca scarpe',hoodies:'Ricerca felpe e giacche',budget:'Ricerca prodotti economici',designer:'Ricerca prodotti firmati',qc:'Guida alle foto QC'},intro:{shoes:'Usa questa pagina per confrontare annuncio originale, taglia scelta e prove visibili prima di proseguire.',hoodies:'Questa pagina riunisce vestibilità, tessuto, colore e dettagli dell’annuncio prima di proseguire.',budget:'La ricerca economica funziona meglio quando ogni scelta ha prezzo visibile, variante esatta e un breve motivo.',designer:'Usa questa pagina per una ricerca accurata. Verifica venditore, annuncio esatto e ogni dichiarazione di autenticità o autorizzazione prima dell’acquisto.',qc:'Le foto QC sono prove di dettagli visibili. Non garantiscono controlli specialistici, tempi o risultati doganali.'},sections:['Cosa annotare','Come confrontare','Passo successivo'],points:{shoes:['Annota modello, colore, sistema taglie e variante dall’annuncio originale.','Confronta solo annunci equivalenti: foto, misure, materiali, note e prezzo corrente.','Apri la categoria scarpe con modello o caratteristica cercata.'],hoodies:['Annota tipo, colore, tabella taglie, tessuto e variante.','Confronta misure e dettagli visibili senza presumere equivalenza.','Apri la categoria felpe con il termine utile.'],budget:['Annota prezzo mostrato, variante e data di controllo.','Separa il prezzo dell’articolo da costi futuri di pacco, servizio, tasse o spedizione.','Cerca nel database per prodotto e fascia di prezzo.'],designer:['Annota venditore, descrizione, variante e dichiarazione da verificare.','Nome, immagine o categoria non dimostrano autenticità, autorizzazione, qualità o disponibilità.','Prosegui solo dopo aver verificato l’annuncio originale.'],qc:['Verifica che le foto corrispondano alla variante e mostrino dettagli rilevanti.','Usa prove visibili per fatti visibili e chiedi dettagli aggiuntivi quando servono.','Poi torna alla checklist dettagli e a FindSpreadsheet.']},related:'Percorsi correlati'},
    pt: { home:'Início',categories:'Categorias',guide:'Guia de pesquisa',open:'Abrir FindSpreadsheet',names:{shoes:'Pesquisa de calçado',hoodies:'Pesquisa de hoodies e casacos',budget:'Pesquisa económica',designer:'Pesquisa de produtos de design',qc:'Guia de fotos QC'},intro:{shoes:'Use esta rota de calçado para comparar o anúncio original, o tamanho escolhido e provas visíveis antes de continuar.',hoodies:'Esta rota de roupa reúne corte, tecido, cor e detalhes do anúncio antes de continuar.',budget:'Uma pesquisa económica é mais útil quando cada opção tem preço visível, variante exata e uma razão curta.',designer:'Use esta rota para pesquisar com cuidado. Verifique vendedor, anúncio exato e qualquer alegação de autenticidade ou autorização antes da compra.',qc:'Fotos QC são provas de detalhes visíveis. Não garantem testes especializados, prazos ou resultados aduaneiros.'},sections:['O que registar','Como comparar','Próximo passo'],points:{shoes:['Registe modelo, cor, sistema de tamanhos e variante do anúncio original.','Compare apenas anúncios equivalentes: fotos, medidas, materiais, notas e preço atual.','Abra a categoria de calçado com o modelo ou critério desejado.'],hoodies:['Registe tipo de peça, cor, tabela de tamanhos, tecido e variante.','Compare medidas e detalhes visíveis sem assumir equivalência.','Abra a categoria de hoodies com o termo útil.'],budget:['Registe preço apresentado, variante e data de verificação.','Separe o preço do artigo de custos futuros de encomenda, serviço, impostos ou envio.','Pesquise na base por produto e faixa de preço.'],designer:['Registe vendedor, descrição, variante e alegação a verificar.','Nome, imagem ou categoria não comprovam autenticidade, autorização, qualidade ou disponibilidade.','Prossiga apenas depois de verificar o anúncio original.'],qc:['Verifique se as fotos correspondem à variante e mostram detalhes relevantes.','Use prova visível para factos visíveis e peça mais detalhe quando necessário.','Depois volte à lista de detalhes e ao FindSpreadsheet.']},related:'Rotas relacionadas'},
    nl: { home:'Home',categories:'Categorieën',guide:'Onderzoeksgids',open:'Open FindSpreadsheet',names:{shoes:'Schoenenonderzoek',hoodies:'Hoodie- en jassenonderzoek',budget:'Budgetonderzoek',designer:'Designerproductonderzoek',qc:'QC-fotogids'},intro:{shoes:'Gebruik deze schoenenroute om de oorspronkelijke listing, gekozen maat en zichtbare informatie te vergelijken voordat je verdergaat.',hoodies:'Deze kledingroute houdt pasvorm, stof, kleur en listingdetails samen voordat je verdergaat.',budget:'Budgetonderzoek werkt het beste wanneer elke keuze een zichtbare prijs, exacte variant en korte reden heeft.',designer:'Gebruik deze route voor zorgvuldig onderzoek. Controleer verkoper, exacte listing en claims over authenticiteit of toestemming vóór aankoop.',qc:'QC-foto’s vormen bewijs van zichtbare details. Ze garanderen geen specialistische test, levertijd of douane-uitkomst.'},sections:['Wat noteren','Hoe vergelijken','Volgende stap'],points:{shoes:['Noteer model, kleur, maatsysteem en gekozen variant uit de oorspronkelijke listing.','Vergelijk alleen gelijksoortige listings: foto’s, maten, materiaal, notities en actuele prijs.','Open de schoenencategorie met het gewenste model of kenmerk.'],hoodies:['Noteer kledingtype, kleur, maattabel, stof en variant.','Vergelijk maten en zichtbare details zonder aan te nemen dat listings gelijk zijn.','Open de hoodiecategorie met een passende term.'],budget:['Noteer getoonde prijs, variant en controledatum.','Houd artikelprijs apart van mogelijke latere pakket-, service-, belasting- of verzendkosten.','Zoek in de database op product en prijsklasse.'],designer:['Noteer verkoper, beschrijving, variant en claim die je wilt controleren.','Een naam, afbeelding of categorie bewijst geen authenticiteit, toestemming, kwaliteit of beschikbaarheid.','Ga pas verder na controle van de oorspronkelijke listing.'],qc:['Controleer dat foto’s bij de variant horen en relevante details tonen.','Gebruik zichtbaar bewijs voor zichtbare feiten en vraag zo nodig meer detail.','Ga daarna terug naar de detailchecklist en FindSpreadsheet.']},related:'Gerelateerde routes'},
    pl: { home:'Strona główna',categories:'Kategorie',guide:'Przewodnik badawczy',open:'Otwórz FindSpreadsheet',names:{shoes:'Badanie obuwia',hoodies:'Badanie bluz i kurtek',budget:'Badanie budżetowe',designer:'Badanie produktów designerskich',qc:'Przewodnik po zdjęciach QC'},intro:{shoes:'Użyj tej strony obuwia, aby porównać oryginalną ofertę, wybrany rozmiar i widoczne informacje przed przejściem dalej.',hoodies:'Ta strona odzieżowa łączy krój, materiał, kolor i szczegóły oferty przed dalszym krokiem.',budget:'Badanie budżetowe działa najlepiej, gdy każda pozycja ma widoczną cenę, dokładny wariant i krótki powód.',designer:'Użyj tej strony do starannego badania. Sprawdź sprzedawcę, dokładną ofertę i twierdzenia o autentyczności lub upoważnieniu przed zakupem.',qc:'Zdjęcia QC są dowodem widocznych szczegółów. Nie gwarantują specjalistycznego testu, terminu ani wyniku celnego.'},sections:['Co zapisać','Jak porównać','Następny krok'],points:{shoes:['Zapisz model, kolor, system rozmiarów i wariant z oryginalnej oferty.','Porównuj tylko podobne oferty: zdjęcia, wymiary, materiały, notatki i bieżącą cenę.','Otwórz kategorię obuwia z modelem lub cechą.'],hoodies:['Zapisz typ ubrania, kolor, tabelę rozmiarów, materiał i wariant.','Porównuj wymiary i widoczne szczegóły bez zakładania równoważności.','Otwórz kategorię bluz z potrzebnym terminem.'],budget:['Zapisz widoczną cenę, wariant i datę kontroli.','Oddziel cenę produktu od późniejszych kosztów paczki, usługi, podatków lub wysyłki.','Szukaj w bazie według produktu i przedziału cenowego.'],designer:['Zapisz sprzedawcę, opis, wariant i twierdzenie do sprawdzenia.','Nazwa, obraz lub kategoria nie dowodzą autentyczności, zgody, jakości ani dostępności.','Kontynuuj dopiero po sprawdzeniu oryginalnej oferty.'],qc:['Sprawdź, czy zdjęcia pasują do wariantu i pokazują ważne szczegóły.','Używaj widocznych dowodów dla widocznych faktów i proś o więcej szczegółów.','Następnie wróć do listy szczegółów i FindSpreadsheet.']},related:'Powiązane ścieżki'},
    sv: { home:'Hem',categories:'Kategorier',guide:'Researchguide',open:'Öppna FindSpreadsheet',names:{shoes:'Skoresearch',hoodies:'Hoodie- och jackresearch',budget:'Budgetresearch',designer:'Designerproduktresearch',qc:'Guide för QC-bilder'},intro:{shoes:'Använd denna skosida för att jämföra originalannons, vald storlek och synliga uppgifter innan du går vidare.',hoodies:'Denna klädsida samlar passform, material, färg och annonsdetaljer före nästa steg.',budget:'Budgetresearch fungerar bäst när varje val har synligt pris, exakt variant och en kort motivering.',designer:'Använd denna sida för noggrann research. Kontrollera säljare, exakt annons och påståenden om äkthet eller behörighet före köp.',qc:'QC-bilder är bevis på synliga detaljer. De garanterar inte specialtest, leveranstid eller tullresultat.'},sections:['Vad du noterar','Hur du jämför','Nästa steg'],points:{shoes:['Notera modell, färg, storlekssystem och vald variant från originalannonsen.','Jämför bara likvärdiga annonser: bilder, mått, material, anteckningar och aktuellt pris.','Öppna skokategorin med modell eller egenskap.'],hoodies:['Notera plaggtyp, färg, storlekstabell, material och variant.','Jämför mått och synliga detaljer utan att anta att annonser är likvärdiga.','Öppna hoodiekategorin med relevant term.'],budget:['Notera visat pris, variant och kontrolldatum.','Håll produktpriset skilt från möjliga senare kostnader för paket, service, skatt eller frakt.','Sök i databasen med produkt och prisintervall.'],designer:['Notera säljare, beskrivning, variant och påstående som ska kontrolleras.','Namn, bild eller kategori bevisar inte äkthet, behörighet, kvalitet eller tillgänglighet.','Fortsätt först efter att originalannonsen är kontrollerad.'],qc:['Kontrollera att bilder passar varianten och visar relevanta detaljer.','Använd synligt bevis för synliga fakta och begär mer detaljer vid behov.','Återgå sedan till detaljlistan och FindSpreadsheet.']},related:'Relaterade vägar'}
  };

  function render(language) {
    var data = catalogue[language] || catalogue.en;
    var name = data.names[topic];
    document.documentElement.lang = language;
    document.querySelector('[data-crumb-home]').textContent = data.home;
    var detailLabels = { en: 'Product Details', de: 'Produktdetails', fr: 'Détails du produit', es: 'Detalles del producto', it: 'Dettagli prodotto', pt: 'Detalhes do produto', nl: 'Productdetails', pl: 'Szczegóły produktu', sv: 'Produktdetaljer' };
    document.querySelector('[data-crumb-category]').textContent = topic === 'qc' ? detailLabels[language] || detailLabels.en : data.categories;
    document.querySelector('[data-crumb-current]').textContent = name;
    document.querySelector('[data-topic-eyebrow]').textContent = data.guide.toUpperCase();
    document.querySelector('[data-topic-title]').textContent = name;
    document.querySelector('[data-topic-intro]').textContent = data.intro[topic];
    document.querySelectorAll('[data-topic-section]').forEach(function (node, index) { node.textContent = data.sections[index]; });
    document.querySelectorAll('[data-topic-point]').forEach(function (node, index) { node.textContent = data.points[topic][index]; });
    document.querySelector('[data-topic-cta]').textContent = data.open;
    var relatedTitle = document.querySelector('[data-related-title]');
    if (relatedTitle) relatedTitle.textContent = data.related;
    document.title = name + ' | PikoBuy Research Guide';
  }

  function currentLanguage() { return localStorage.getItem('pikoLang') || 'en'; }
  document.addEventListener('DOMContentLoaded', function () { render(currentLanguage()); });
  document.addEventListener('change', function (event) { if (event.target.matches('.language')) render(event.target.value); });
  window.addEventListener('piko-language-render', function (event) { render((event.detail && event.detail.language) || currentLanguage()); });
}());
