import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ArticleLinks, ArticleSections, CategoryVisualCard, PageShell } from "../../components";
import { categories } from "../../data";
import { LocaleHome } from "../../locale-home";
import { common, getArticles, getPage, localizedCategories, localizedProducts, locales, type Locale } from "../../translations";

type Params={locale:string;path?:string[]};
const prefix=(locale:Locale,path="")=>`/${locale}${path}`;
function resolve({locale:raw,path=[]}:Params){const supported=locales.includes(raw as Locale);return {locale:(supported?raw:"en") as Locale,route:supported?path:[raw,...path]};}

const ui={
  en:{open:"Open independent page →",read:"Read full article →",sources:"PRIMARY SOURCES",sourceTitle:"Check the live source before acting.",official:"LoloBuy official homepage",database:"FindSpreadsheet product database",verify:"What to verify",parcel:"What affects the parcel",directory:"What the directory does",verifyText:"Confirm the live title, selected variant, seller price and China-side delivery. Then use evidence that answers this category’s specific questions—not a generic verified label.",parcelText:"Record dimensions, packed weight, fragile parts and route restrictions. Cost and eligibility can change with destination and packaging.",directoryText:"This page explains the research process. The live collection stays on FindSpreadsheet so one maintained source controls current records.",continue:"CONTINUE TO THE DATABASE",browse:"Browse the live collection.",browseText:"Review current details and keep only the finds that still make sense.",next:"NEXT STEP",continueResearch:"Continue with live product research.",articleText:"Use this guide to narrow the decision, then verify the current record and source listing."},
  de:{open:"Unabhängige Seite öffnen →",read:"Vollständigen Artikel lesen →",sources:"PRIMÄRQUELLEN",sourceTitle:"Vor einer Entscheidung die Live-Quelle prüfen.",official:"Offizielle LoloBuy-Startseite",database:"FindSpreadsheet-Produktdatenbank",verify:"Was zu prüfen ist",parcel:"Was das Paket beeinflusst",directory:"Aufgabe des Verzeichnisses",verifyText:"Live-Titel, Variante, Verkäuferpreis und Inlandslieferung prüfen. Danach kategoriespezifische Belege statt eines allgemeinen Prüfsiegels nutzen.",parcelText:"Maße, verpacktes Gewicht, empfindliche Teile und Routenbeschränkungen erfassen. Kosten und Eignung hängen von Ziel und Verpackung ab.",directoryText:"Diese Seite erklärt die Recherche. Die aktuelle Sammlung bleibt auf FindSpreadsheet, damit eine gepflegte Quelle die Datensätze steuert.",continue:"WEITER ZUR DATENBANK",browse:"Aktuelle Sammlung durchsuchen.",browseText:"Details prüfen und nur sinnvolle Funde behalten.",next:"NÄCHSTER SCHRITT",continueResearch:"Mit aktueller Produktrecherche fortfahren.",articleText:"Mit diesem Leitfaden eingrenzen und danach Datensatz und Quellangebot prüfen."},
  fr:{open:"Ouvrir la page indépendante →",read:"Lire l’article complet →",sources:"SOURCES PRIMAIRES",sourceTitle:"Vérifiez la source active avant d’agir.",official:"Accueil officiel LoloBuy",database:"Base produits FindSpreadsheet",verify:"Points à vérifier",parcel:"Impact sur le colis",directory:"Rôle du répertoire",verifyText:"Vérifiez titre, variante, prix vendeur et livraison intérieure, puis utilisez des preuves propres à la catégorie plutôt qu’un badge générique.",parcelText:"Notez dimensions, poids emballé, fragilité et restrictions. Coût et admissibilité varient selon destination et emballage.",directoryText:"Cette page explique la recherche. La collection active reste sur FindSpreadsheet afin qu’une seule source maintienne les fiches.",continue:"CONTINUER VERS LA BASE",browse:"Parcourir la collection active.",browseText:"Contrôlez les détails et ne gardez que les produits pertinents.",next:"ÉTAPE SUIVANTE",continueResearch:"Poursuivre la recherche produit active.",articleText:"Utilisez ce guide pour affiner le choix, puis vérifiez la fiche et l’annonce source."},
  es:{open:"Abrir página independiente →",read:"Leer artículo completo →",sources:"FUENTES PRIMARIAS",sourceTitle:"Revisa la fuente activa antes de actuar.",official:"Página oficial de LoloBuy",database:"Base de productos FindSpreadsheet",verify:"Qué revisar",parcel:"Qué afecta al paquete",directory:"Qué hace el directorio",verifyText:"Confirma título, variante, precio y entrega nacional. Usa después pruebas específicas de la categoría, no una insignia genérica.",parcelText:"Anota dimensiones, peso embalado, piezas frágiles y restricciones. Coste y elegibilidad cambian según destino y embalaje.",directoryText:"Esta página explica la investigación. La colección activa permanece en FindSpreadsheet para mantener una única fuente.",continue:"CONTINUAR A LA BASE",browse:"Explora la colección activa.",browseText:"Revisa los detalles y conserva solo los productos que tengan sentido.",next:"SIGUIENTE PASO",continueResearch:"Continuar con la investigación activa.",articleText:"Usa la guía para acotar la decisión y verifica después el registro y el anuncio fuente."},
  it:{open:"Apri pagina indipendente →",read:"Leggi l’articolo completo →",sources:"FONTI PRIMARIE",sourceTitle:"Controlla la fonte attiva prima di agire.",official:"Homepage ufficiale LoloBuy",database:"Database prodotti FindSpreadsheet",verify:"Cosa verificare",parcel:"Cosa influisce sul pacco",directory:"Cosa fa la directory",verifyText:"Conferma titolo, variante, prezzo e consegna nazionale. Usa poi prove specifiche per categoria, non un bollino generico.",parcelText:"Registra dimensioni, peso imballato, fragilità e restrizioni. Costi e idoneità variano con destinazione e imballo.",directoryText:"Questa pagina spiega la ricerca. La raccolta attiva resta su FindSpreadsheet per mantenere un’unica fonte.",continue:"CONTINUA AL DATABASE",browse:"Esplora la raccolta attiva.",browseText:"Controlla i dettagli e conserva solo i prodotti sensati.",next:"PASSO SUCCESSIVO",continueResearch:"Continua con la ricerca prodotti attiva.",articleText:"Usa la guida per restringere la scelta, poi verifica record e inserzione fonte."},
  pt:{open:"Abrir página independente →",read:"Ler artigo completo →",sources:"FONTES PRIMÁRIAS",sourceTitle:"Verifique a fonte ativa antes de agir.",official:"Página oficial da LoloBuy",database:"Base de produtos FindSpreadsheet",verify:"O que verificar",parcel:"O que afeta a encomenda",directory:"Função do diretório",verifyText:"Confirme título, variante, preço e entrega doméstica. Use depois provas específicas da categoria, não um selo genérico.",parcelText:"Registe dimensões, peso embalado, fragilidade e restrições. Custo e elegibilidade variam com destino e embalagem.",directoryText:"Esta página explica a pesquisa. A coleção ativa permanece no FindSpreadsheet para manter uma única fonte.",continue:"CONTINUAR PARA A BASE",browse:"Explore a coleção ativa.",browseText:"Reveja os detalhes e guarde apenas os produtos adequados.",next:"PRÓXIMO PASSO",continueResearch:"Continue com a pesquisa ativa.",articleText:"Use o guia para limitar a decisão e depois confirme o registo e o anúncio de origem."},
} as const;

export async function generateMetadata({params}:{params:Promise<Params>}):Promise<Metadata>{
  const resolved=resolve(await params), route=resolved.route, locale=resolved.locale;
  const page=route.length?getPage(locale,route[0]):undefined;
  const article=route[0]==="article"?getArticles(locale).find(a=>a.slug===route[1]):undefined;
  const category=route[0]==="category"?categories.find(c=>c.slug===route[1]):undefined;
  const title=article?.metaTitle??article?.title??page?.title??(category?`${localizedCategories(locale)[categories.indexOf(category)].name} spreadsheet finds`:"LoloBuy spreadsheet research");
  const description=article?.metaDescription??article?.excerpt??page?.intro??(category?localizedCategories(locale)[categories.indexOf(category)].note:homeDescription(locale));
  const suffix=route.length?`/${route.join("/")}`:"";
  const alternateLocales=article?.englishOnly?["en" as const]:locales;
  const languages=Object.fromEntries(alternateLocales.map(code=>[code,prefix(code,suffix)]));
  const resolvedTitle=article?.metaTitle?title:`${title} | FindSpreadsheet Agent Guide`;
  return {title:resolvedTitle,description,keywords:article?[article.primaryKeyword,...(article.secondaryKeywords??[])].filter(Boolean) as string[]:undefined,alternates:{canonical:prefix(locale,suffix),languages:{...languages,"x-default":prefix("en",suffix)}},openGraph:article?{title:resolvedTitle,description,type:"article",url:prefix(locale,suffix),publishedTime:article.published,modifiedTime:article.modified}:undefined,twitter:article?{card:"summary_large_image",title:resolvedTitle,description}:undefined};
}
function homeDescription(locale:Locale){return {en:"Independent LoloBuy spreadsheet research for Europe and North America.",de:"Unabhängige LoloBuy-Spreadsheet-Recherche für Europa und Nordamerika.",fr:"Recherche indépendante du spreadsheet LoloBuy pour l’Europe et l’Amérique du Nord.",es:"Investigación independiente del spreadsheet LoloBuy para Europa y Norteamérica.",it:"Ricerca indipendente sullo spreadsheet LoloBuy per Europa e Nord America.",pt:"Pesquisa independente do spreadsheet LoloBuy para a Europa e América do Norte."}[locale];}

export default async function LocalizedRoute({params}:{params:Promise<Params>}){
  const {locale,route}=resolve(await params), copy=ui[locale], cats=localizedCategories(locale), nav=common[locale], products=localizedProducts(locale);
  if(!route.length)return <LocaleHome locale={locale}/>;
  if(route[0]==="category"&&route[1]){const index=categories.findIndex(c=>c.slug===route[1]);if(index<0)notFound();const base=categories[index],cat=cats[index];return <PageShell locale={locale} eyebrow={`${nav.categories.toUpperCase()} ${base.icon}`} title={`${cat.name} — ${copy.verify.toLowerCase()}.`} intro={cat.note}><section className="category-detail"><div><h2>{copy.verify}</h2><p>{copy.verifyText}</p></div><div><h2>{copy.parcel}</h2><p>{copy.parcelText}</p></div><div><h2>{copy.directory}</h2><p>{copy.directoryText}</p></div></section><section className="category-cta"><p className="eyebrow">{copy.continue}</p><h2>{copy.browse}</h2><p>{copy.browseText}</p><a href={base.href} target="_blank" rel="noopener">{common[locale].database}</a></section></PageShell>;}
  if(route[0]==="article"&&route[1]){const article=getArticles(locale).find(a=>a.slug===route[1]);if(!article)notFound();const articleSchema=article.published?{"@context":"https://schema.org","@type":"Article",headline:article.title,description:article.excerpt,datePublished:article.published,dateModified:article.modified??article.published,inLanguage:locale,mainEntityOfPage:`https://lolobuy.id/${locale}/article/${article.slug}`,author:{"@type":"Organization",name:"FindSpreadsheet Agent Guide"},publisher:{"@type":"Organization",name:"FindSpreadsheet Agent Guide",url:"https://lolobuy.id/en"}}:null;return <>{articleSchema&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(articleSchema)}}/>}<PageShell locale={locale} eyebrow={`${article.label} • ${article.date} • ${article.read}`} title={article.title} intro={article.excerpt}><ArticleSections sections={article.sections}/>{article.relatedLinks?.length?<ArticleLinks links={article.relatedLinks}/>:<section className="article-action"><div><p className="eyebrow">{copy.next}</p><h2>{copy.continueResearch}</h2><p>{copy.articleText}</p></div><a href="https://findspreadsheet.com/" target="_blank" rel="noopener">{nav.database}</a></section>}</PageShell></>;}
  const slug=route[0],page=getPage(locale,slug);if(!page)notFound();const showProducts=slug==="products"||slug==="product-details";
  const faqSchema=slug==="faq"?{"@context":"https://schema.org","@type":"FAQPage",mainEntity:page.sections.map(([question,answer])=>({"@type":"Question",name:question,acceptedAnswer:{"@type":"Answer",text:answer}}))}:null;
  return <>{faqSchema&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}}/>}<PageShell locale={locale} eyebrow={page.eyebrow} title={page.title} intro={page.intro}>
    {slug==="categories"&&<section className="category-hub">{categories.map((c,i)=><CategoryVisualCard key={c.slug} slug={c.slug} icon={c.icon} name={cats[i].name} note={cats[i].note} href={c.href} action={nav.database}/>)}</section>}
    {showProducts&&<section className="inner-products">{products.map(item=><a className="product-card" href={item.href} target="_blank" rel="noopener" key={item.href}><div className="image-wrap"><img src={item.image} alt={item.name}/></div><div className="product-info"><small>{item.category}</small><h3>{item.name}</h3><div><b>{item.price}</b><span>{item.source}</span></div></div></a>)}</section>}
    {slug==="seo-articles"&&<section className="article-hub">{getArticles(locale).map((a,i)=><a href={prefix(locale,`/article/${a.slug}`)} className="article-card" key={a.slug}><span>{String(i+1).padStart(2,"0")}</span><div><small>{a.label} • {a.date}</small><h2>{a.title}</h2><p>{a.excerpt}</p><b>{copy.read}</b></div><em>{a.read}</em></a>)}</section>}
    <ArticleSections sections={page.sections}/><section className="source-panel"><div><p className="eyebrow">{copy.sources}</p><h2>{copy.sourceTitle}</h2></div><div><a href="https://findspreadsheet.com/" target="_blank" rel="noopener">{copy.database}<span>↗</span></a></div></section>
  </PageShell></>;
}
