const HOME='https://findspreadsheet.com/';
const SEARCH='https://findspreadsheet.com/search.html?channelid=2&keywords=';
const CATEGORY_SEARCH={
  shoes:'shoes',hoodies:'hoodies','t shirts':'t-shirts',jackets:'jackets',
  'pants shorts':'pants',headwear:'hats',accessories:'bracelets necklaces',jersey:'jerseys',
  electronics:'watches','other stuff':'socks'
};
function searchUrl(query){return SEARCH+encodeURIComponent(query);}
function categoryUrl(query){return searchUrl(CATEGORY_SEARCH[query.toLowerCase()]||query);}
document.querySelectorAll('.brand').forEach(a=>a.innerHTML='<img src="/pikobuy-logo.png" alt="PikoBuy">');
document.querySelectorAll(".navlinks").forEach(nav=>{if(!nav.querySelector("[href=\"/details.html\"]")){const a=document.createElement("a");a.href="/details.html";a.dataset.t="details";a.textContent="Product details";nav.insertBefore(a,nav.querySelector("[href=\"/qc-guide.html\"]"));}if(!nav.querySelector("[href=\"/articles.html\"]")){const a=document.createElement("a");a.href="/articles.html";a.dataset.t="articles";a.textContent="SEO articles";nav.insertBefore(a,nav.querySelector("[href=\"/qc-guide.html\"]"));}});
document.querySelectorAll('[data-search]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();const q=f.querySelector('input').value.trim();location.href=q?categoryUrl(q):HOME}));
document.querySelectorAll('[data-find]').forEach(a=>{const query=(a.dataset.find||'').trim();a.href=query?categoryUrl(query):HOME;});
document.querySelectorAll('[data-t="database"], [data-database], [data-find=""]').forEach(a=>a.href=HOME);
const translations={en:{home:'Home',categories:'Categories',details:'Product details',articles:'SEO articles',qc:'QC guide',shipping:'Shipping',faq:'FAQ',database:'Open database'},de:{home:'Startseite',categories:'Kategorien',details:'Produktdetails',articles:'SEO-Artikel',qc:'QC-Leitfaden',shipping:'Versand',faq:'FAQ',database:'Datenbank öffnen'},fr:{home:'Accueil',categories:'Catégories',details:'Détails du produit',articles:'Articles SEO',qc:'Guide QC',shipping:'Livraison',faq:'FAQ',database:'Ouvrir la base'},es:{home:'Inicio',categories:'Categorías',details:'Detalles del producto',articles:'Artículos SEO',qc:'Guía QC',shipping:'Envío',faq:'FAQ',database:'Abrir base'},it:{home:'Home',categories:'Categorie',details:'Dettagli prodotto',articles:'Articoli SEO',qc:'Guida QC',shipping:'Spedizione',faq:'FAQ',database:'Apri database'},pt:{home:'Início',categories:'Categorias',details:'Detalhes do produto',articles:'Artigos SEO',qc:'Guia QC',shipping:'Envio',faq:'FAQ',database:'Abrir base'},nl:{home:'Start',categories:'Categorieën',details:'Productdetails',articles:'SEO-artikelen',qc:'QC-gids',shipping:'Verzending',faq:'FAQ',database:'Database openen'},pl:{home:'Start',categories:'Kategorie',details:'Szczegóły produktu',articles:'Artykuły SEO',qc:'Przewodnik QC',shipping:'Wysyłka',faq:'FAQ',database:'Otwórz bazę'},sv:{home:'Start',categories:'Kategorier',details:'Produktdetaljer',articles:'SEO-artiklar',qc:'QC-guide',shipping:'Frakt',faq:'FAQ',database:'Öppna databas'}};
const translatableNodes=[];const sourceText=new Map();const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode:n=>/^(SCRIPT|STYLE|OPTION)$/.test(n.parentElement?.tagName||'')||!n.nodeValue.trim()?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT});while(walker.nextNode()){translatableNodes.push(walker.currentNode);sourceText.set(walker.currentNode,walker.currentNode.nodeValue);}
async function translateText(text,lang){if('Translator' in self){try{const availability=await Translator.availability({sourceLanguage:'en',targetLanguage:lang});if(availability!=='unavailable'){const translator=await Translator.create({sourceLanguage:'en',targetLanguage:lang});return await translator.translate(text);}}catch(_){}}const response=await fetch('https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl='+encodeURIComponent(lang)+'&dt=t&q='+encodeURIComponent(text));if(!response.ok)throw new Error('translation unavailable');const payload=await response.json();return payload[0].map(part=>part[0]).join('');}
const translationCachePrefix='ps-page-translation-v3:';const translationRequests=new Map();function translationKey(lang){return translationCachePrefix+location.pathname+':'+lang;}function cachedTranslation(lang){try{const value=JSON.parse(localStorage.getItem(translationKey(lang))||'null');return Array.isArray(value)&&value.length===translatableNodes.length?value:null;}catch(_){return null;}}
async function translationValues(lang){if(lang==='en')return translatableNodes.map(node=>sourceText.get(node));const cached=cachedTranslation(lang);if(cached)return cached;if(translationRequests.has(lang))return translationRequests.get(lang);const request=Promise.allSettled(translatableNodes.map(node=>translateText(sourceText.get(node),lang))).then(results=>{const values=results.map((result,index)=>result.status==='fulfilled'?result.value:sourceText.get(translatableNodes[index]));try{localStorage.setItem(translationKey(lang),JSON.stringify(values));}catch(_){}return values;}).finally(()=>translationRequests.delete(lang));translationRequests.set(lang,request);return request;}
async function translatePage(lang){const values=lang==='en'?translatableNodes.map(node=>sourceText.get(node)):await translationValues(lang);values.forEach((value,index)=>translatableNodes[index].nodeValue=value);}
async function applyLanguage(){const lang=document.getElementById('language').value;localStorage.setItem('ps-lang',lang);document.documentElement.lang=lang;const t=translations[lang];document.querySelectorAll('[data-t]').forEach(el=>{el.textContent=t[el.dataset.t]||el.textContent});await translatePage(lang);}
const select=document.getElementById('language');if(select){select.value=localStorage.getItem('ps-lang')||'en';select.addEventListener('change',applyLanguage);applyLanguage();setTimeout(()=>{Object.keys(translations).filter(lang=>lang!=='en'&&lang!==select.value).reduce((queue,lang)=>queue.then(()=>translationValues(lang)),Promise.resolve());},80)}
