export const languageOptions = [
  ["en", "English"],
  ["nl", "Nederlands"],
  ["de", "Deutsch"],
  ["fr", "Français"],
  ["es", "Español"],
  ["it", "Italiano"],
  ["pl", "Polski"],
  ["pt", "Português"],
  ["sv", "Svenska"],
] as const;
export type Lang = (typeof languageOptions)[number][0];
export const getLang = (v: string | null): Lang =>
  languageOptions.some(([x]) => x === v) ? (v as Lang) : "en";
const nav = {
  en: ["Home", "Categories", "Product details", "SEO articles", "FAQ"],
  nl: ["Start", "Categorieën", "Productdetails", "SEO-artikelen", "FAQ"],
  de: ["Start", "Kategorien", "Produktdetails", "SEO-Artikel", "FAQ"],
  fr: ["Accueil", "Catégories", "Détails produit", "Articles SEO", "FAQ"],
  es: ["Inicio", "Categorías", "Detalles del producto", "Artículos SEO", "FAQ"],
  it: ["Home", "Categorie", "Dettagli prodotto", "Articoli SEO", "FAQ"],
  pl: ["Start", "Kategorie", "Szczegóły produktu", "Artykuły SEO", "FAQ"],
  pt: ["Início", "Categorias", "Detalhes do produto", "Artigos SEO", "FAQ"],
  sv: ["Hem", "Kategorier", "Produktdetaljer", "SEO-artiklar", "FAQ"],
} as const;
const c = {
  en: [
    "Independent research preview",
    "Browse with better context.",
    "Explore a category first, then open its matching FindSpreadsheet result.",
    "Category guide",
    "What to check before opening results",
    "Refine your search words, then verify the current listing context, variants and notes.",
    "Open matching category",
    "Product discovery file",
    "Asterline Modular Overshirt",
    "Sample product profile — not a listing or availability claim.",
    "Research cues",
    "Check fit notes, fabric information, colour variants and current photos before deciding.",
    "Search this product idea",
    "Research topics built for real buyer questions.",
    "Useful answers before you search.",
  ],
  nl: [
    "Onafhankelijke onderzoeks-preview",
    "Zoek met meer context.",
    "Verken eerst een categorie en open daarna het bijpassende FindSpreadsheet-resultaat.",
    "Categoriegids",
    "Wat controleer je voordat je resultaten opent?",
    "Verfijn je zoekwoorden en controleer actuele context, varianten en notities.",
    "Open bijpassende categorie",
    "Product-onderzoeksdossier",
    "Asterline Modular Overshirt",
    "Voorbeeldprofiel voor onderzoek — geen aanbieding of beschikbaarheidsclaim.",
    "Onderzoekssignalen",
    "Controleer pasvorm, materiaal, kleurvarianten en actuele foto’s voordat je beslist.",
    "Zoek dit productidee",
    "Onderzoeksthema’s voor echte kopersvragen.",
    "Nuttige antwoorden vóór je zoekt.",
  ],
  de: [
    "Unabhängige Recherche-Vorschau",
    "Mit mehr Kontext suchen.",
    "Erkunden Sie zuerst eine Kategorie und öffnen Sie dann das passende FindSpreadsheet-Ergebnis.",
    "Kategorieleitfaden",
    "Was vor dem Öffnen der Ergebnisse prüfen?",
    "Präzisieren Sie Ihre Suchbegriffe und prüfen Sie aktuelle Angaben, Varianten und Hinweise.",
    "Passende Kategorie öffnen",
    "Produkt-Rechercheakte",
    "Asterline Modular Overshirt",
    "Beispielprofil zur Recherche — kein Angebot und keine Verfügbarkeitsaussage.",
    "Recherchehinweise",
    "Prüfen Sie Passform, Material, Farbvarianten und aktuelle Fotos vor der Entscheidung.",
    "Diese Produktidee suchen",
    "Recherchethemen für echte Käuferfragen.",
    "Nützliche Antworten vor der Suche.",
  ],
  fr: [
    "Aperçu de recherche indépendant",
    "Cherchez avec plus de contexte.",
    "Explorez d’abord une catégorie, puis ouvrez le résultat FindSpreadsheet correspondant.",
    "Guide de catégorie",
    "Que vérifier avant d’ouvrir les résultats ?",
    "Affinez vos mots-clés, puis vérifiez le contexte, les variantes et les notes.",
    "Ouvrir la catégorie correspondante",
    "Dossier de découverte produit",
    "Asterline Modular Overshirt",
    "Profil d’exemple pour la recherche — ni offre ni promesse de disponibilité.",
    "Repères de recherche",
    "Vérifiez coupe, matière, variantes de couleur et photos récentes avant de décider.",
    "Rechercher cette idée produit",
    "Sujets de recherche pour de vraies questions d’acheteurs.",
    "Réponses utiles avant votre recherche.",
  ],
  es: [
    "Vista previa de investigación independiente",
    "Busca con mejor contexto.",
    "Explora una categoría primero y abre después el resultado correspondiente de FindSpreadsheet.",
    "Guía de categoría",
    "¿Qué comprobar antes de abrir resultados?",
    "Refina las palabras clave y comprueba contexto, variantes y notas actuales.",
    "Abrir categoría correspondiente",
    "Ficha de descubrimiento",
    "Asterline Modular Overshirt",
    "Perfil de ejemplo para investigar; no es una oferta ni una promesa de disponibilidad.",
    "Pistas de investigación",
    "Comprueba ajuste, material, variantes de color y fotos actuales antes de decidir.",
    "Buscar esta idea de producto",
    "Temas de investigación para preguntas reales de compradores.",
    "Respuestas útiles antes de buscar.",
  ],
  it: [
    "Anteprima di ricerca indipendente",
    "Cerca con più contesto.",
    "Esplora prima una categoria, poi apri il risultato FindSpreadsheet corrispondente.",
    "Guida alla categoria",
    "Cosa controllare prima di aprire i risultati?",
    "Affina le parole chiave e verifica contesto, varianti e note aggiornate.",
    "Apri categoria corrispondente",
    "Scheda di scoperta prodotto",
    "Asterline Modular Overshirt",
    "Profilo di esempio per la ricerca: non è un’offerta né una promessa di disponibilità.",
    "Indizi di ricerca",
    "Controlla vestibilità, materiale, varianti colore e foto aggiornate prima di decidere.",
    "Cerca questa idea prodotto",
    "Temi di ricerca per domande reali degli acquirenti.",
    "Risposte utili prima della ricerca.",
  ],
  pl: [
    "Niezależny podgląd badań",
    "Szukaj z lepszym kontekstem.",
    "Najpierw poznaj kategorię, a potem otwórz dopasowany wynik FindSpreadsheet.",
    "Przewodnik po kategorii",
    "Co sprawdzić przed otwarciem wyników?",
    "Doprecyzuj słowa kluczowe i sprawdź aktualny kontekst, warianty oraz notatki.",
    "Otwórz pasującą kategorię",
    "Karta odkrywania produktu",
    "Asterline Modular Overshirt",
    "Przykładowy profil badawczy — nie oferta ani deklaracja dostępności.",
    "Wskazówki badawcze",
    "Sprawdź dopasowanie, materiał, warianty kolorów i aktualne zdjęcia przed decyzją.",
    "Szukaj tego pomysłu",
    "Tematy badań dla prawdziwych pytań kupujących.",
    "Przydatne odpowiedzi przed wyszukiwaniem.",
  ],
  pt: [
    "Prévia de pesquisa independente",
    "Pesquise com melhor contexto.",
    "Explore primeiro uma categoria e depois abra o resultado FindSpreadsheet correspondente.",
    "Guia da categoria",
    "O que verificar antes de abrir resultados?",
    "Refine as palavras-chave e verifique contexto, variantes e notas atuais.",
    "Abrir categoria correspondente",
    "Dossiê de descoberta do produto",
    "Asterline Modular Overshirt",
    "Perfil de exemplo para pesquisa — não é uma oferta nem promessa de disponibilidade.",
    "Pistas de pesquisa",
    "Verifique caimento, material, variantes de cor e fotos atuais antes de decidir.",
    "Pesquisar esta ideia",
    "Temas de pesquisa para perguntas reais de compradores.",
    "Respostas úteis antes de pesquisar.",
  ],
  sv: [
    "Oberoende forskningsförhandsvisning",
    "Sök med bättre sammanhang.",
    "Utforska först en kategori och öppna sedan det matchande FindSpreadsheet-resultatet.",
    "Kategoriguide",
    "Vad ska kontrolleras innan resultaten öppnas?",
    "Förfina sökorden och kontrollera aktuell kontext, varianter och anteckningar.",
    "Öppna matchande kategori",
    "Produktupptäcktsfil",
    "Asterline Modular Overshirt",
    "Exempelprofil för forskning – inget erbjudande eller tillgänglighetslöfte.",
    "Forskningsledtrådar",
    "Kontrollera passform, material, färgvarianter och aktuella foton innan du bestämmer dig.",
    "Sök efter denna produktidé",
    "Forskningsämnen för verkliga köparfrågor.",
    "Användbara svar före sökning.",
  ],
} as const;
export const t = (l: Lang) => ({ nav: nav[l], c: c[l] });
export const categories = [
  "Shoes",
  "Hoodies",
  "T-Shirts",
  "Jackets",
  "Pants",
  "Hats",
  "Watches",
  "Electronics",
  "Socks",
  "Other Stuff",
] as const;
export const slugify = (x: string) => x.toLowerCase().replace(/\s+/g, "-");

export type Category = (typeof categories)[number];

const categoryLabels: Record<Lang, Record<Category, string>> = {
  en: { Shoes: "Shoes", Hoodies: "Hoodies", "T-Shirts": "T-Shirts", Jackets: "Jackets", Pants: "Pants", Hats: "Hats", Watches: "Watches", Electronics: "Electronics", Socks: "Socks", "Other Stuff": "Other Stuff" },
  nl: { Shoes: "Schoenen", Hoodies: "Hoodies", "T-Shirts": "T-shirts", Jackets: "Jassen", Pants: "Broeken", Hats: "Hoeden", Watches: "Horloges", Electronics: "Elektronica", Socks: "Sokken", "Other Stuff": "Overig" },
  de: { Shoes: "Schuhe", Hoodies: "Hoodies", "T-Shirts": "T-Shirts", Jackets: "Jacken", Pants: "Hosen", Hats: "Mützen", Watches: "Uhren", Electronics: "Elektronik", Socks: "Socken", "Other Stuff": "Sonstiges" },
  fr: { Shoes: "Chaussures", Hoodies: "Sweats à capuche", "T-Shirts": "T-shirts", Jackets: "Vestes", Pants: "Pantalons", Hats: "Chapeaux", Watches: "Montres", Electronics: "Électronique", Socks: "Chaussettes", "Other Stuff": "Autres articles" },
  es: { Shoes: "Zapatos", Hoodies: "Sudaderas con capucha", "T-Shirts": "Camisetas", Jackets: "Chaquetas", Pants: "Pantalones", Hats: "Gorros", Watches: "Relojes", Electronics: "Electrónica", Socks: "Calcetines", "Other Stuff": "Otros artículos" },
  it: { Shoes: "Scarpe", Hoodies: "Felpe con cappuccio", "T-Shirts": "T-shirt", Jackets: "Giacche", Pants: "Pantaloni", Hats: "Cappelli", Watches: "Orologi", Electronics: "Elettronica", Socks: "Calze", "Other Stuff": "Altri articoli" },
  pl: { Shoes: "Buty", Hoodies: "Bluzy z kapturem", "T-Shirts": "T-shirty", Jackets: "Kurtki", Pants: "Spodnie", Hats: "Czapki", Watches: "Zegarki", Electronics: "Elektronika", Socks: "Skarpetki", "Other Stuff": "Pozostałe" },
  pt: { Shoes: "Sapatos", Hoodies: "Moletons com capuz", "T-Shirts": "Camisetas", Jackets: "Casacos", Pants: "Calças", Hats: "Chapéus", Watches: "Relógios", Electronics: "Eletrônicos", Socks: "Meias", "Other Stuff": "Outros itens" },
  sv: { Shoes: "Skor", Hoodies: "Hoodies", "T-Shirts": "T-shirts", Jackets: "Jackor", Pants: "Byxor", Hats: "Mössor", Watches: "Klockor", Electronics: "Elektronik", Socks: "Strumpor", "Other Stuff": "Övrigt" },
};

const labels: Record<Lang, {
  database: string;
  researchEdit: string;
  databaseSearch: string;
  categoryAction: string;
  categoryDetail: string;
  productBrief: string;
  sourceNote: string;
}> = {
  en: { database: "Database", researchEdit: "RESEARCH EDIT", databaseSearch: "Open database", categoryAction: "Open this category", categoryDetail: "Category details", productBrief: "Product research brief", sourceNote: "Source note: LoloBuy public homepage, reviewed September 2026. This is an independent research preview and does not claim affiliation with LoloBuy." },
  nl: { database: "Database", researchEdit: "ONDERZOEKSDOSSIER", databaseSearch: "Database openen", categoryAction: "Open deze categorie", categoryDetail: "Categoriedetails", productBrief: "Productonderzoek", sourceNote: "Bronvermelding: openbare LoloBuy-homepage, gecontroleerd in september 2026. Dit is een onafhankelijke onderzoeks-preview en beweert geen band met LoloBuy." },
  de: { database: "Datenbank", researchEdit: "RECHERCHEDOSSIER", databaseSearch: "Datenbank öffnen", categoryAction: "Diese Kategorie öffnen", categoryDetail: "Kategoriedetails", productBrief: "Produktrecherche", sourceNote: "Quellenhinweis: öffentliche LoloBuy-Startseite, geprüft im September 2026. Dies ist eine unabhängige Recherche-Vorschau und behauptet keine Verbindung zu LoloBuy." },
  fr: { database: "Base de données", researchEdit: "DOSSIER DE RECHERCHE", databaseSearch: "Ouvrir la base", categoryAction: "Ouvrir cette catégorie", categoryDetail: "Détails de la catégorie", productBrief: "Fiche de recherche produit", sourceNote: "Note de source : page d’accueil publique de LoloBuy, consultée en septembre 2026. Il s’agit d’un aperçu de recherche indépendant, sans affiliation revendiquée avec LoloBuy." },
  es: { database: "Base de datos", researchEdit: "DOSSIER DE INVESTIGACIÓN", databaseSearch: "Abrir base de datos", categoryAction: "Abrir esta categoría", categoryDetail: "Detalles de categoría", productBrief: "Ficha de investigación de producto", sourceNote: "Nota de fuente: página pública de inicio de LoloBuy, revisada en septiembre de 2026. Esta es una vista previa de investigación independiente y no reclama afiliación con LoloBuy." },
  it: { database: "Database", researchEdit: "DOSSIER DI RICERCA", databaseSearch: "Apri database", categoryAction: "Apri questa categoria", categoryDetail: "Dettagli della categoria", productBrief: "Scheda di ricerca prodotto", sourceNote: "Nota sulla fonte: homepage pubblica di LoloBuy, consultata a settembre 2026. Questa è un’anteprima di ricerca indipendente e non rivendica alcuna affiliazione con LoloBuy." },
  pl: { database: "Baza danych", researchEdit: "KARTA BADAŃ", databaseSearch: "Otwórz bazę", categoryAction: "Otwórz tę kategorię", categoryDetail: "Szczegóły kategorii", productBrief: "Karta badań produktu", sourceNote: "Informacja o źródle: publiczna strona główna LoloBuy, sprawdzona we wrześniu 2026 r. To niezależny podgląd badań i nie deklaruje powiązania z LoloBuy." },
  pt: { database: "Base de dados", researchEdit: "DOSSIÊ DE PESQUISA", databaseSearch: "Abrir base de dados", categoryAction: "Abrir esta categoria", categoryDetail: "Detalhes da categoria", productBrief: "Ficha de pesquisa do produto", sourceNote: "Nota de fonte: página pública da LoloBuy, revisada em setembro de 2026. Esta é uma prévia de pesquisa independente e não declara afiliação com a LoloBuy." },
  sv: { database: "Databas", researchEdit: "FORSKNINGSUNDERLAG", databaseSearch: "Öppna databasen", categoryAction: "Öppna denna kategori", categoryDetail: "Kategoridetaljer", productBrief: "Produktforskningsunderlag", sourceNote: "Källnotering: LoloBuys offentliga startsida, granskad i september 2026. Detta är en oberoende forskningsförhandsvisning och påstår ingen anknytning till LoloBuy." },
};

export const categoryLabel = (lang: Lang, category: Category) => categoryLabels[lang][category];
export const siteLabels = (lang: Lang) => labels[lang];
