export type Guide = {
  slug: string; eyebrow: string; title: string; seoTitle?: string; description: string;
  readTime: string; updated: string; intro: string[];
  sections: Array<{ heading: string; paragraphs: string[]; bullets?: string[] }>;
  internalLinks: Array<{ href: string; label: string; note: string }>;
  sources: Array<{ href: string; label: string }>; publishedDate: string; modifiedDate: string;
};

export const primaryLinks = { products: "https://findspreadsheet.com/AllProducts/", pikobuy: "https://findspreadsheet.com/pikobuy-spreadsheet/" };

export const categories = [
  ["Shoes", "SH", "Check seller measurements, outsole details and the exact variation before opening the live collection.", "https://findspreadsheet.com/shoes/"],
  ["Hoodies", "HD", "Compare chest, length, fabric notes and print placement instead of relying on a familiar size letter.", "https://findspreadsheet.com/hoodies-sweaters/"],
  ["T-Shirts", "TS", "Use the source size chart and check the selected colour, collar, print and garment measurements.", "https://findspreadsheet.com/t-shirts/"],
  ["Jackets", "JK", "Look at insulation, dimensions and packed volume before treating an item price as the final cost.", "https://findspreadsheet.com/jackets/"],
  ["Pants", "PT", "Review waist, rise, inseam and cut; label sizes are not a cross-brand fit guarantee.", "https://findspreadsheet.com/pants-shorts/"],
  ["Hats", "HT", "Confirm head circumference, adjustment range, colour and visible hardware.", "https://findspreadsheet.com/headwear/"],
  ["Watches", "WT", "Check diameter, strap size, functions and included parts; photos cannot prove long-term performance.", "https://findspreadsheet.com/AllProducts/"],
  ["Electronics", "EL", "Confirm compatibility, battery and route restrictions before adding any electronic item to a parcel plan.", "https://findspreadsheet.com/electronics/"],
  ["Socks", "SK", "Compare size range, fibre information and pack quantity with the live seller listing.", "https://findspreadsheet.com/AllProducts/"],
  ["Accessories", "AC", "Check dimensions, material notes, closure details and every included component.", "https://findspreadsheet.com/accessories/"],
].map(([name, icon, note, href]) => ({ name, icon, note, href }));

export const countryGroups = [
  { tier: "English core", countries: "United States · United Kingdom · Canada", rationale: "English discovery pages support the main database route and are not a claim about platform user totals." },
  { tier: "DACH & Benelux", countries: "Germany · Austria · Netherlands · Belgium", rationale: "Localised search intent should be served with full, reviewed pages rather than thin translated variants." },
  { tier: "Southern Europe", countries: "France · Spain · Italy · Portugal", rationale: "Parcel, customs and sizing questions need the same complete content structure in every language." },
  { tier: "Growth markets", countries: "Poland · Sweden", rationale: "Use current destination rules and live checkout information; do not infer availability from a country landing page." },
];

type Seed = Pick<Guide, "slug" | "eyebrow" | "title" | "seoTitle" | "description"> & { decision: string; evidence: string; limits: string; checklist: string[] };
const sources = [{ href: "/sources#pikobuy-sources", label: "PikoBuy platform source record" }, { href: "/sources#findspreadsheet-sources", label: "FindSpreadsheet product-source record" }];
const links = [
  { href: "/how-to-use-pikobuy-spreadsheet", label: "Read the research workflow", note: "Keep product selection, warehouse evidence and parcel planning as separate decisions." },
  { href: "/pikobuy-qc-photo-guide", label: "Use the QC-photo guide", note: "Turn a vague photo request into a visible, checkable question." },
  { href: "/pikobuy-shipping-europe", label: "Plan a parcel by destination", note: "Compare live route, weight and dimensions before treating an estimate as final." },
];

function makeGuide(seed: Seed): Guide {
  return {
    slug: seed.slug, eyebrow: seed.eyebrow, title: seed.title, seoTitle: seed.seoTitle, description: seed.description,
    readTime: "8 min read", updated: "Updated 11 September 2026", publishedDate: "2026-09-11", modifiedDate: "2026-09-11",
    intro: [
      `${seed.title} is an independent research guide for shoppers who use a product spreadsheet before deciding whether to continue with a buying platform. It is not a price promise, seller endorsement, warehouse service or delivery guarantee.`,
      "The useful question is not whether one screenshot or comment looks reassuring. It is whether you can compare the live listing, selected option, warehouse evidence and destination-specific parcel information in a way that still makes sense when conditions change.",
      "PikoBuy publicly describes a flow that can begin with product search or a submitted link, then moves through purchase assistance, warehouse inspection, repacking and international shipping. This guide focuses on the decision point that matters for this topic without presenting the independent site as the service connected to an order.",
    ],
    sections: [
      { heading: "Start with a record you can verify", paragraphs: [
        `Before acting on any recommendation, save the exact source link, product title, selected option, seller images and the date you checked them. ${seed.decision} A short label without the surrounding listing is not enough evidence to make a later comparison.`,
        "The live seller page is the reference for option names, availability and the information shown at the point of purchase. A spreadsheet entry can help discovery, but it cannot guarantee that a price, stock status, size option or seller response remains unchanged. Recheck the live listing at the moment you commit.",
        "Keep a simple two-column note: what the page visibly states, and what still needs confirmation. This prevents a common research mistake—turning a reasonable inference into a claim that the source never made. It also gives you a clear brief if you later need to ask the service a focused question.",
      ], bullets: seed.checklist },
      { heading: "Use evidence at the right stage", paragraphs: [
        "Different evidence answers different questions. Seller photos can help identify a listed variation; warehouse photos can show an item received by the warehouse; a packed-parcel estimate can help compare routes. None of those records alone proves long-term durability, authenticity, final customs treatment or delivery performance.",
        `${seed.evidence} When a record cannot answer the decision, ask one narrow question through the order service before parcel submission. A request for a labelled measurement, a missing angle or the actual packed dimensions is more useful than a general request to “check everything.”`,
        "PikoBuy’s public homepage says items undergo inspection and repacking after arrival at its China warehouse. Treat that workflow as an opportunity to compare visible details with your saved order record, not as a blanket promise that every feature of every item has been independently verified.",
      ] },
      { heading: "Compare cost, risk and reversibility", paragraphs: [
        "A product decision should include the next cost decision. International shipping can vary with destination, product type, actual weight, packed dimensions, route restrictions and optional services. A low item price may stop looking low once the parcel stage is known, especially when volume or repeated handling is involved.",
        "The most reversible moment is normally before international dispatch. Compare the correct variant, visible condition, measurements and parcel plan while the item is still in the warehouse. Save photos, order notes and message history so that a specific issue can be described with evidence rather than memory.",
        "Do not treat another buyer’s parcel, price or timeline as a transferable quote. It may use a different route, date, item category, declaration, packaging choice or destination. A useful guide makes the variables visible instead of promising a universal outcome.",
      ] },
      { heading: "What this guide cannot decide for you", paragraphs: [
        `${seed.limits} Platform policies, seller decisions, carrier availability and customs rules can change after an article is published. Confirm the live order page, current route information and destination requirements before payment or dispatch.`,
        "This independent site does not accept payments, place orders, inspect items, choose couriers, submit declarations or handle claims. Questions about an active order, payment, shipping line, refund, tracking or support ticket belong to the service connected to that order.",
        "The practical goal is modest but valuable: reduce avoidable mismatches by documenting the facts you can check, naming the uncertainty you cannot remove, and making the next decision while options are still open. That is more useful than a generic reassurance page.",
      ] },
      { heading: "Make the next decision traceable", paragraphs: [
        "A good research record makes a later decision easier to explain. Keep the source URL, chosen variation, date, seller screenshots, order details, warehouse images and parcel-screen details together. If a value changes, you can compare the new information with the saved record instead of relying on an impression of what the page used to say.",
        "Use a clear approval rule before you receive warehouse photos or a shipping quote. For example, decide whether a missing measurement, a visibly different option, a damaged component, an unavailable route or a higher packed-volume estimate would make you pause. Writing the rule first reduces pressure to rationalise a purchase after money or time has already been spent.",
        "When information remains incomplete, choose the smallest reversible next step: ask for a specific detail, wait for warehouse evidence, compare a second listing or keep the item out of the parcel. The aim is not to remove every uncertainty. It is to avoid treating uncertainty as proof that a product, seller, route or outcome is suitable.",
      ] },
    ], internalLinks: links.filter((item) => !item.href.endsWith(seed.slug)), sources,
  };
}

const seeds: Seed[] = [
  { slug: "pikobuy-fees-total-cost", eyebrow: "Cost planning", title: "PikoBuy Fees Explained: Build a Real Total-Cost Record", description: "Separate item price, domestic delivery, parcel choices and destination charges before relying on a headline cost.", decision: "Record the item price separately from domestic delivery, optional services and later international shipping.", evidence: "PikoBuy’s public estimator asks for destination, product type, weight and parcel dimensions, showing why one per-kilogram claim is incomplete.", limits: "No independent article can quote your final total or guarantee a tax, duty, exchange-rate or carrier outcome.", checklist: ["Source item price and selected option", "Domestic delivery and service charges shown", "Estimated and actual parcel measurements", "Destination-specific shipping quote"] },
  { slug: "pikobuy-seller-listing-verification", eyebrow: "Listing checks", title: "PikoBuy Seller and Listing Verification Checklist", description: "Match a spreadsheet find to its active seller listing, options and visible product evidence.", decision: "Match item ID, title, colour, size or variation text before treating two similar-looking listings as the same item.", evidence: "The best evidence is the current source listing plus saved option text, not a copied title or an old product image.", limits: "A listing review cannot prove seller reliability, stock, fulfilment speed or how an item will perform after delivery.", checklist: ["Exact product link", "Item ID or seller reference", "Selected colour and size text", "Current images and listing status"] },
  { slug: "how-to-use-pikobuy-spreadsheet", eyebrow: "Beginner workflow", title: "How to Use a PikoBuy Spreadsheet Without Skipping the Checks", description: "Move from discovery to an order-ready research record, QC review and realistic parcel plan.", decision: "Use the spreadsheet for discovery, then verify the active seller listing before deciding whether a product deserves a closer look.", evidence: "PikoBuy describes product search or submitted links, purchase assistance, warehouse inspection and international shipping as distinct stages.", limits: "A spreadsheet route does not replace the platform’s live terms, account information or support process.", checklist: ["Choose one focused product category", "Verify source listing and options", "Prepare QC questions before arrival", "Plan shipping after warehouse data"] },
  { slug: "pikobuy-qc-photo-guide", eyebrow: "Warehouse QC", title: "PikoBuy QC Photos: What a Warehouse Image Can and Cannot Prove", description: "A category-aware QC checklist for identity, measurements, visible condition and focused photo requests.", decision: "Check item identity and requested variation before spending time on fine visual details.", evidence: "Warehouse images are useful for visible labels, colour, quantity, measurements and damage when the relevant angle is shown.", limits: "Photos cannot prove authenticity, hidden construction, comfort, material composition, battery health or long-term durability.", checklist: ["Correct item and quantity", "Size label or requested measurement", "Colour and visible variation", "Visible damage or missing components"] },
  { slug: "pikobuy-shipping-europe", eyebrow: "Parcel planning", title: "PikoBuy Shipping to Europe: Questions to Ask Before You Submit a Parcel", description: "Plan around actual weight, dimensions, product restrictions and destination rules instead of fixed shipping promises.", decision: "Compare available routes only after the warehouse items, parcel dimensions and destination are known.", evidence: "PikoBuy’s public pages present international shipping and a shipping estimate tool, while route choices remain dependent on the parcel and destination.", limits: "This page cannot promise a route, customs result, delivery date, tax treatment or final courier charge.", checklist: ["Destination and postcode if required", "Product category restrictions", "Actual weight and dimensions", "Current route terms and tracking coverage"] },
  { slug: "pikobuy-eu-vat-customs-preparation", eyebrow: "EU customs", title: "PikoBuy EU VAT and Customs Preparation Guide for 2026", description: "A checklist for separating parcel planning from destination customs and tax obligations.", decision: "Treat customs preparation as part of the buying decision, not a detail to solve after the parcel has been paid.", evidence: "European import treatment can depend on classification, value, origin, transport and destination rules rather than an agent label.", limits: "No shopping guide can guarantee clearance, a tax amount or that a particular declaration approach is accepted.", checklist: ["Destination-country official guidance", "Accurate product and value record", "Route restrictions", "Saved order and parcel evidence"] },
  { slug: "pikobuy-tracking-delay-diagnosis", eyebrow: "Tracking", title: "PikoBuy Tracking Status After Shipping: Diagnose Parcel Delays", description: "Read tracking events as a sequence of hand-offs without assuming that a quiet scan means a lost parcel.", decision: "Record the shipping line, dispatch time and each visible scan before contacting support with a precise question.", evidence: "A first scan, export hand-off, arrival scan and delivery scan can be separated by carrier processing and destination logistics.", limits: "An article cannot locate a parcel, override a carrier, predict delivery or determine a claim outcome.", checklist: ["Parcel number and route", "Dispatch date and first scan", "Latest location and timestamp", "Order screenshots and messages"] },
  { slug: "is-pikobuy-safe-buyer-checklist", eyebrow: "Buyer safety", title: "Is PikoBuy Safe to Use? A 12-Point Buyer Checklist", description: "A practical risk-control list for account hygiene, listing records, payment evidence, QC and parcel choices.", decision: "Break a broad safety question into checks you can actually complete before and after a purchase.", evidence: "Useful evidence includes live terms, payment records, source listing, warehouse images and written route information for the exact order.", limits: "A checklist cannot certify a platform, seller, payment method, parcel or delivery outcome as risk-free.", checklist: ["Use unique account security", "Save source and payment records", "Check product restrictions", "Keep QC and parcel evidence"] },
  { slug: "pikobuy-reviews-customer-experience-evidence", eyebrow: "Public reviews", title: "PikoBuy Reviews and Customer Experiences: What the Evidence Shows", description: "Read small self-selected review samples without mistaking posts for a measured success rate.", decision: "Separate a reviewer’s experience from a general conclusion about products, shipping or support.", evidence: "Public reviews can identify questions to investigate, but sample size, incentives, dates and destination differences affect what they can prove.", limits: "This article does not calculate a platform rating, verify individual posts or guarantee that another shopper will have the same outcome.", checklist: ["Date and destination", "Order type and item category", "Evidence attached to the claim", "Whether feedback is promotional or independent"] },
  { slug: "pikobuy-parcel-insurance-claim", eyebrow: "Insurance", title: "PikoBuy Parcel Insurance: Coverage, Evidence and Claim Checklist", description: "Document a parcel before dispatch and check terms before relying on optional insurance.", decision: "Read the current route and insurance terms before paying, then save evidence before an issue occurs.", evidence: "Useful claim records can include order details, warehouse photos, packed-parcel information, tracking events and communications.", limits: "This guide cannot confirm eligibility, coverage, liability, compensation or the outcome of a claim.", checklist: ["Current route terms", "Coverage and exclusions shown", "Parcel contents and photos", "Tracking and claim deadlines"] },
  { slug: "pikobuy-volumetric-weight-packaging", eyebrow: "Packing", title: "PikoBuy Volumetric Weight and Packaging: A Practical Calculator Guide", description: "Understand scale weight and dimensional weight, then compare packaging choices with their protection trade-offs.", decision: "Measure the packed parcel rather than assuming a light item will always be charged only by its scale weight.", evidence: "The public estimator requests length, width and height as well as weight, which makes packed volume an important variable.", limits: "Only the active line and final packed parcel can determine the chargeable-weight rule and billed amount.", checklist: ["Actual parcel weight", "Length, width and height", "Protective packaging choice", "Current route calculation shown"] },
  { slug: "pikobuy-return-policy", eyebrow: "Returns", title: "PikoBuy Returns and Warehouse Decision Guide", description: "Act on a visible mismatch while the item is in the warehouse and keep the order record for a precise request.", decision: "Separate an obvious wrong item or visible defect from a later change of preference, because eligibility and costs can differ.", evidence: "PikoBuy publishes returns and exchanges information, including warehouse-stage timing and category conditions that should be checked on the live policy.", limits: "This guide cannot approve a return, quote a fee or override seller and platform eligibility conditions.", checklist: ["Order status and current deadline", "Specific issue and visible evidence", "Seller and platform conditions", "Possible domestic return charges"] },
  { slug: "pikobuy-size-guide-measurements", eyebrow: "Sizing guide", title: "How to Choose the Correct Size on PikoBuy: Measurements Before Labels", description: "Use centimetre measurements, seller charts and focused warehouse requests instead of assuming labels match.", decision: "Compare a garment or shoe measurement with an item you already own and know fits, rather than converting a label by habit.", evidence: "Seller charts and warehouse images can show the listed size, insole length, chest width or garment length when the requested measurement is visible.", limits: "No conversion chart or image can guarantee fit because cut, tolerance, material stretch and personal preference vary.", checklist: ["Seller chart in centimetres", "A known-fitting reference item", "Exact selected size", "Focused QC measurement request"] },
  { slug: "pikobuy-sneaker-batch-qc-context", eyebrow: "Sneaker research", title: "PikoBuy Sneaker Batch Labels and QC Context: Compare Evidence, Not Hype", description: "Treat batch names as seller descriptors, then compare the listing, photos, measurements and visible details.", decision: "Record the exact batch label as shown by the seller and avoid assuming one label has a fixed meaning across every listing or date.", evidence: "QC photos can support a visible comparison of size label, shape, colour, outsole, stitching and supplied accessories for the received item.", limits: "This guide does not rank batches, authenticate products, label goods as replicas or promise that a seller description is accurate.", checklist: ["Exact seller batch label", "Listing version and date", "Visible QC comparison points", "Specific missing-angle request"] },
  { slug: "pikobuy-parcel-consolidation-shipping-cost", eyebrow: "Consolidation", title: "PikoBuy Parcel Consolidation: Weight, Volume and Shipping Trade-Offs", description: "Decide whether to combine warehouse items after comparing weight, dimensions, restrictions and shared-parcel risk.", decision: "Compare one combined parcel with a split plan using the same destination, product restrictions and protection choices.", evidence: "Consolidation can reduce repeated handling, but bulky packaging and dimensional charging can change the result; warehouse measurements are more useful than guesses.", limits: "This guide cannot guarantee that consolidation lowers cost or reduces customs, delay or damage risk for every parcel.", checklist: ["Items ready in warehouse", "Combined actual and volumetric weight", "Protection and box-removal trade-off", "Current route eligibility"] },
];

export const guides = seeds.map(makeGuide);
export const getGuide = (slug: string) => guides.find((item) => item.slug === slug);
