"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { factualFaq, localizedArticleContinuations, localizedArticleDetailAdditions, localizedArticles, seoArticle } from "@/components/editorial-content";

type Page = "home" | "categories" | "details" | "guides" | "articles" | "faq";
type Copy = { name:string; code:string; nav:string[]; eyebrow:string; title:string; intro:string; explore:string; search:string; note:string; section:string; sectionBody:string; guide:string; guideBody:string; article:string; articleBody:string; faq:string; faqBody:string; source:string; independent:string; focus:string; countries:string[] };

const copy: Record<string, Copy> = {
en:{name:"English",code:"EN",nav:["Home","Categories","Product details","Guides","SEO Articles","FAQ"],eyebrow:"Independent discovery guide",title:"Find better items. Check before you buy.",intro:"A buyer-first route from product discovery to careful decisions. Explore categories, compare context, and open FindSpreadsheet when you are ready.",explore:"Explore the database",search:"Search FindSpreadsheet",note:"Preview edition · not the official LoloBuy website",section:"Browse by category",sectionBody:"Start broad, then open the database with a clear product intent.",guide:"A calmer way to plan an order",guideBody:"Compare the product context, check sizing and QC notes, then review delivery choices for your destination at checkout.",article:"Latest guide",articleBody:"LoloBuy workflow: product link, warehouse review, and international delivery—what to confirm at each step.",faq:"Before you open a product",faqBody:"Use the listing as your source of truth. Availability, price, shipping lines and delivery rules can change by destination.",source:"Research basis: LoloBuy publicly presents a global service with multi-language, multi-currency and international shipping support. This guide makes no shipping or customs promises.",independent:"An independent discovery site for FindSpreadsheet.",focus:"Priority locales",countries:["Netherlands","Germany","France","Spain","Italy","Poland","Portugal","Sweden","English markets"]},
nl:{name:"Nederlands",code:"NL",nav:["Home","Categorieën","Productdetails","Gidsen","SEO-artikelen","FAQ"],eyebrow:"Onafhankelijke ontdekkingsgids",title:"Vind betere items. Controleer vóór je koopt.",intro:"Een route die de koper vooropzet: van productontdekking naar weloverwogen keuzes. Verken categorieën, vergelijk context en open FindSpreadsheet wanneer je klaar bent.",explore:"Database verkennen",search:"Zoek in FindSpreadsheet",note:"Previewversie · geen officiële LoloBuy-website",section:"Bladeren per categorie",sectionBody:"Begin breed en open daarna de database met een duidelijk productdoel.",guide:"Rustiger een bestelling plannen",guideBody:"Vergelijk productcontext, controleer maat en QC-notities en bekijk bezorgopties voor jouw bestemming bij checkout.",article:"Nieuwste gids",articleBody:"LoloBuy-workflow: productlink, magazijncontrole en internationale levering—wat je in elke stap controleert.",faq:"Voordat je een product opent",faqBody:"Gebruik de listing als bron van waarheid. Beschikbaarheid, prijs, verzendlijnen en regels kunnen per bestemming veranderen.",source:"Onderzoeksbasis: LoloBuy positioneert zich publiekelijk als wereldwijde shoppingservice met talen, valuta en internationale verzending. Deze gids belooft geen levering of douane-uitkomst.",independent:"Een onafhankelijke ontdekkingssite voor FindSpreadsheet.",focus:"Prioriteitsmarkten",countries:["Nederland","Duitsland","Frankrijk","Spanje","Italië","Polen","Portugal","Zweden","Engelstalige markten"]},
de:{name:"Deutsch",code:"DE",nav:["Start","Kategorien","Produktdetails","Guides","Artikel","FAQ"],eyebrow:"Unabhängiger Einkaufsratgeber",title:"Bessere Artikel finden. Vor dem Kauf prüfen.",intro:"Ein käuferorientierter Weg von der Entdeckung bis zur sorgfältigen Entscheidung. Kategorien erkunden, Kontext vergleichen und bei Bedarf FindSpreadsheet öffnen.",explore:"Datenbank erkunden",search:"FindSpreadsheet durchsuchen",note:"Vorschau · keine offizielle LoloBuy-Website",section:"Nach Kategorie stöbern",sectionBody:"Breit beginnen und dann mit klarer Produktsuche zur Datenbank gehen.",guide:"Bestellungen ruhiger planen",guideBody:"Produktkontext vergleichen, Größe und QC-Hinweise prüfen und Versandoptionen für dein Ziel beim Checkout prüfen.",article:"Neuester Guide",articleBody:"LoloBuy-Ablauf: Produktlink, Lagerprüfung und internationaler Versand—was in jedem Schritt zu prüfen ist.",faq:"Bevor du ein Produkt öffnest",faqBody:"Die Produktseite ist die maßgebliche Quelle. Verfügbarkeit, Preis, Versandarten und Regeln können je Zielort variieren.",source:"Recherchebasis: LoloBuy beschreibt sich öffentlich als globalen Shoppingservice mit Sprachen, Währungen und internationalem Versand. Dieser Guide verspricht keine Liefer- oder Zollresultate.",independent:"Eine unabhängige Entdeckungsseite für FindSpreadsheet.",focus:"Prioritätsmärkte",countries:["Niederlande","Deutschland","Frankreich","Spanien","Italien","Polen","Portugal","Schweden","Englischsprachige Märkte"]},
fr:{name:"Français",code:"FR",nav:["Accueil","Catégories","Détails produit","Guides","Articles","FAQ"],eyebrow:"Guide de découverte indépendant",title:"Trouvez mieux. Vérifiez avant d’acheter.",intro:"Un parcours centré sur l’acheteur, de la découverte à une décision réfléchie. Explorez les catégories, comparez le contexte et ouvrez FindSpreadsheet lorsque vous êtes prêt.",explore:"Explorer la base",search:"Rechercher sur FindSpreadsheet",note:"Édition de prévisualisation · site non officiel de LoloBuy",section:"Parcourir par catégorie",sectionBody:"Commencez large, puis ouvrez la base avec une intention produit précise.",guide:"Planifier une commande sereinement",guideBody:"Comparez le contexte produit, vérifiez taille et notes QC, puis consultez les options de livraison au paiement.",article:"Dernier guide",articleBody:"Flux LoloBuy : lien produit, contrôle en entrepôt et livraison internationale—les vérifications à chaque étape.",faq:"Avant d’ouvrir un produit",faqBody:"La fiche produit est votre source de référence. Disponibilité, prix, lignes d’expédition et règles varient selon la destination.",source:"Base de recherche : LoloBuy se présente publiquement comme un service mondial avec langues, devises et livraison internationale. Ce guide ne promet aucun résultat de livraison ou de douane.",independent:"Un site de découverte indépendant pour FindSpreadsheet.",focus:"Marchés prioritaires",countries:["Pays-Bas","Allemagne","France","Espagne","Italie","Pologne","Portugal","Suède","Marchés anglophones"]},
es:{name:"Español",code:"ES",nav:["Inicio","Categorías","Detalles","Guías","Artículos","FAQ"],eyebrow:"Guía de descubrimiento independiente",title:"Encuentra mejores artículos. Revisa antes de comprar.",intro:"Un recorrido pensado para el comprador, desde descubrir productos hasta decidir con cuidado. Explora categorías, compara el contexto y abre FindSpreadsheet cuando estés listo.",explore:"Explorar la base",search:"Buscar en FindSpreadsheet",note:"Edición de vista previa · no es el sitio oficial de LoloBuy",section:"Explorar por categoría",sectionBody:"Empieza de forma amplia y abre después la base con una intención clara.",guide:"Planifica un pedido con calma",guideBody:"Compara el contexto, revisa talla y notas QC, y consulta las opciones de envío de tu destino al pagar.",article:"Guía reciente",articleBody:"Flujo de LoloBuy: enlace de producto, revisión en almacén y entrega internacional—qué confirmar en cada paso.",faq:"Antes de abrir un producto",faqBody:"La ficha del producto es la fuente principal. Disponibilidad, precio, líneas de envío y reglas cambian según el destino.",source:"Base de investigación: LoloBuy se presenta públicamente como un servicio global con idiomas, monedas y envío internacional. Esta guía no promete resultados de entrega ni aduanas.",independent:"Un sitio independiente de descubrimiento para FindSpreadsheet.",focus:"Mercados prioritarios",countries:["Países Bajos","Alemania","Francia","España","Italia","Polonia","Portugal","Suecia","Mercados en inglés"]},
it:{name:"Italiano",code:"IT",nav:["Home","Categorie","Dettagli prodotto","Guide","Articoli","FAQ"],eyebrow:"Guida indipendente alla scoperta",title:"Trova articoli migliori. Verifica prima di acquistare.",intro:"Un percorso pensato per l’acquirente, dalla scoperta a decisioni attente. Esplora le categorie, confronta il contesto e apri FindSpreadsheet quando sei pronto.",explore:"Esplora il database",search:"Cerca su FindSpreadsheet",note:"Edizione di anteprima · non è il sito ufficiale LoloBuy",section:"Sfoglia per categoria",sectionBody:"Inizia in modo ampio, poi apri il database con un intento chiaro.",guide:"Pianifica un ordine con calma",guideBody:"Confronta il contesto, controlla taglia e note QC, poi verifica le opzioni per la tua destinazione al checkout.",article:"Guida più recente",articleBody:"Flusso LoloBuy: link prodotto, controllo in magazzino e consegna internazionale—cosa verificare a ogni fase.",faq:"Prima di aprire un prodotto",faqBody:"La scheda è la fonte principale. Disponibilità, prezzo, linee di spedizione e regole possono cambiare per destinazione.",source:"Base di ricerca: LoloBuy si presenta pubblicamente come servizio globale con lingue, valute e spedizione internazionale. Questa guida non promette risultati di consegna o dogana.",independent:"Un sito indipendente di scoperta per FindSpreadsheet.",focus:"Mercati prioritari",countries:["Paesi Bassi","Germania","Francia","Spagna","Italia","Polonia","Portogallo","Svezia","Mercati anglofoni"]},
pl:{name:"Polski",code:"PL",nav:["Start","Kategorie","Szczegóły produktu","Poradniki","Artykuły","FAQ"],eyebrow:"Niezależny przewodnik odkrywania",title:"Znajdź lepsze produkty. Sprawdź przed zakupem.",intro:"Ścieżka skupiona na kupującym — od odkrycia produktu do rozsądnej decyzji. Przeglądaj kategorie, porównuj kontekst i otwórz FindSpreadsheet, gdy będziesz gotowy.",explore:"Przeglądaj bazę",search:"Szukaj w FindSpreadsheet",note:"Wersja podglądowa · nie jest oficjalną stroną LoloBuy",section:"Przeglądaj kategorie",sectionBody:"Zacznij szeroko, potem otwórz bazę z jasnym celem produktu.",guide:"Spokojniejsze planowanie zamówienia",guideBody:"Porównaj kontekst, sprawdź rozmiar i notatki QC, a potem opcje dla kraju dostawy przy płatności.",article:"Najnowszy poradnik",articleBody:"Proces LoloBuy: link do produktu, kontrola magazynowa i wysyłka międzynarodowa — co sprawdzić na każdym etapie.",faq:"Zanim otworzysz produkt",faqBody:"Oferta produktu jest źródłem podstawowym. Dostępność, cena, linie wysyłki i zasady mogą się różnić według kraju.",source:"Podstawa badawcza: LoloBuy publicznie przedstawia się jako globalna usługa zakupowa z językami, walutami i wysyłką międzynarodową. Ten przewodnik nie obiecuje wyników dostawy ani odprawy.",independent:"Niezależna strona odkrywania dla FindSpreadsheet.",focus:"Rynki priorytetowe",countries:["Holandia","Niemcy","Francja","Hiszpania","Włochy","Polska","Portugalia","Szwecja","Rynki anglojęzyczne"]},
pt:{name:"Português",code:"PT",nav:["Início","Categorias","Detalhes","Guias","Artigos","FAQ"],eyebrow:"Guia independente de descoberta",title:"Encontre melhores artigos. Verifique antes de comprar.",intro:"Um percurso centrado no comprador, da descoberta a decisões ponderadas. Explore categorias, compare contexto e abra o FindSpreadsheet quando estiver pronto.",explore:"Explorar a base",search:"Pesquisar no FindSpreadsheet",note:"Edição de pré-visualização · não é o site oficial da LoloBuy",section:"Explorar por categoria",sectionBody:"Comece de forma ampla e abra depois a base com uma intenção clara.",guide:"Planeie uma encomenda com calma",guideBody:"Compare o contexto, verifique tamanho e notas QC e consulte opções para o destino no checkout.",article:"Guia recente",articleBody:"Fluxo LoloBuy: link de produto, revisão no armazém e entrega internacional—o que confirmar em cada fase.",faq:"Antes de abrir um produto",faqBody:"A página do produto é a fonte principal. Disponibilidade, preço, linhas de envio e regras variam conforme o destino.",source:"Base de pesquisa: LoloBuy apresenta-se publicamente como serviço global com idiomas, moedas e envio internacional. Este guia não promete resultados de entrega ou alfândega.",independent:"Um site independente de descoberta para FindSpreadsheet.",focus:"Mercados prioritários",countries:["Países Baixos","Alemanha","França","Espanha","Itália","Polónia","Portugal","Suécia","Mercados de língua inglesa"]},
sv:{name:"Svenska",code:"SV",nav:["Hem","Kategorier","Produktdetaljer","Guider","Artiklar","FAQ"],eyebrow:"Oberoende upptäcktsguide",title:"Hitta bättre produkter. Kontrollera före köp.",intro:"En köparfokuserad väg från produktupptäckt till genomtänkta beslut. Utforska kategorier, jämför sammanhang och öppna FindSpreadsheet när du är redo.",explore:"Utforska databasen",search:"Sök i FindSpreadsheet",note:"Förhandsvisning · inte LoloBuys officiella webbplats",section:"Bläddra efter kategori",sectionBody:"Börja brett och öppna sedan databasen med en tydlig produktavsikt.",guide:"Planera en beställning lugnare",guideBody:"Jämför produktkontext, kontrollera storlek och QC-notiser och se alternativ för din destination i kassan.",article:"Senaste guiden",articleBody:"LoloBuy-flödet: produktlänk, lagerkontroll och internationell leverans—vad du ska bekräfta i varje steg.",faq:"Innan du öppnar en produkt",faqBody:"Produktsidan är din huvudsakliga källa. Tillgänglighet, pris, fraktlinjer och regler varierar per destination.",source:"Forskningsgrund: LoloBuy beskriver sig offentligt som en global shoppingtjänst med språk, valutor och internationell frakt. Den här guiden lovar inte leverans- eller tullresultat.",independent:"En oberoende upptäcktssida för FindSpreadsheet.",focus:"Prioriterade marknader",countries:["Nederländerna","Tyskland","Frankrike","Spanien","Italien","Polen","Portugal","Sverige","Engelskspråkiga marknader"]}
};
const routes = ["/","/categories","/details","/guides","/articles","/faq"];
const routeKeys: Page[] = ["home","categories","details","guides","articles","faq"];
const seoNavigation: Record<string,string> = {en:"SEO Articles",nl:"SEO-artikelen",de:"SEO-Artikel",fr:"Articles SEO",es:"Artículos SEO",it:"Articoli SEO",pl:"Artykuły SEO",pt:"Artigos SEO",sv:"SEO-artiklar"};
const categories = ["Shoes","Hoodies","T-Shirts","Jackets","Pants","Headwear","Bags","Watches","Electronics","Accessories"];
type PageLabels = { check:string; discover:string; plan:string; categoryCount:string; buyerCheck:string; workflow:string; reading:string; answers:string; categoryNames:string[]; detailCards:string[]; guideSteps:string[]; articleTitle:string; articleIntro:string; articleSource:string };
const pageLabels: Record<string,PageLabels> = {
  en:{check:"CHECK THE CONTEXT",discover:"DISCOVER",plan:"PLAN",categoryCount:"10 CATEGORIES",buyerCheck:"BUYER CHECK",workflow:"BUYER WORKFLOW",reading:"EVIDENCE-LED READING",answers:"CLEAR ANSWERS",categoryNames:["Shoes","Hoodies","T-Shirts","Jackets","Pants","Headwear","Bags","Watches","Electronics","Accessories"],detailCards:["Material & construction","Sizing context","QC prompts","Price & availability"],guideSteps:["Choose a product","Check warehouse information","Review destination choices"],articleTitle:seoArticle.title,articleIntro:seoArticle.intro,articleSource:"Research note: this independent article is based on the LoloBuy public homepage as reviewed in September 2026. Service details can change; use the current LoloBuy account and parcel screens for live information."},
  nl:{check:"CONTROLEER DE CONTEXT",discover:"ONTDEK",plan:"PLAN",categoryCount:"10 CATEGORIEËN",buyerCheck:"CONTROLE VOOR KOPERS",workflow:"KOOPROUTE",reading:"LEZEN OP BASIS VAN FEITEN",answers:"DUIDELIJKE ANTWOORDEN",categoryNames:["Schoenen","Hoodies","T-shirts","Jassen","Broeken","Hoofddeksels","Tassen","Horloges","Elektronica","Accessoires"],detailCards:["Materiaal en constructie","Maatcontext","QC-vragen","Prijs en beschikbaarheid"],guideSteps:["Kies een product","Controleer magazijninformatie","Bekijk opties voor je bestemming"],articleTitle:"LoloBuy gebruiken voor productonderzoek: een praktische route van bestelling tot pakket",articleIntro:"Een feitelijke, kopergerichte gids voor het vastleggen van productkeuzes, het beoordelen van magazijninformatie en het nemen van een weloverwogen verzendbeslissing.",articleSource:"Onderzoeksnotitie: dit onafhankelijke artikel is gebaseerd op de openbare LoloBuy-homepage, beoordeeld in september 2026. Servicedetails kunnen wijzigen; controleer actuele informatie in je LoloBuy-account en op het pakketscherm."},
  de:{check:"KONTEXT PRÜFEN",discover:"ENTDECKEN",plan:"PLANEN",categoryCount:"10 KATEGORIEN",buyerCheck:"KAUFCHECK",workflow:"KÄUFERABLAUF",reading:"FAKTENBASIERTE LEKTÜRE",answers:"KLARE ANTWORTEN",categoryNames:["Schuhe","Hoodies","T-Shirts","Jacken","Hosen","Kopfbedeckungen","Taschen","Uhren","Elektronik","Accessoires"],detailCards:["Material und Verarbeitung","Größenkontext","QC-Fragen","Preis und Verfügbarkeit"],guideSteps:["Produkt auswählen","Lagerinformationen prüfen","Optionen für das Ziel prüfen"],articleTitle:"LoloBuy für Produktrecherche nutzen: ein praktischer Ablauf von Bestellung bis Paket",articleIntro:"Ein faktenbasierter Leitfaden zum Festhalten der Produktauswahl, Prüfen von Lagerinformationen und Treffen einer fundierten Versandentscheidung.",articleSource:"Recherchehinweis: Dieser unabhängige Artikel basiert auf der öffentlichen LoloBuy-Startseite, geprüft im September 2026. Servicedetails können sich ändern; aktuelle Angaben stehen im LoloBuy-Konto und im Paketbildschirm."},
  fr:{check:"VÉRIFIER LE CONTEXTE",discover:"DÉCOUVRIR",plan:"PLANIFIER",categoryCount:"10 CATÉGORIES",buyerCheck:"VÉRIFICATION ACHETEUR",workflow:"PARCOURS ACHETEUR",reading:"LECTURE FONDÉE SUR DES FAITS",answers:"RÉPONSES CLAIRES",categoryNames:["Chaussures","Sweats à capuche","T-shirts","Vestes","Pantalons","Couvre-chefs","Sacs","Montres","Électronique","Accessoires"],detailCards:["Matière et fabrication","Contexte des tailles","Points QC","Prix et disponibilité"],guideSteps:["Choisir un produit","Vérifier les informations d’entrepôt","Examiner les options de destination"],articleTitle:"Utiliser LoloBuy pour la recherche produit : un parcours pratique de la commande au colis",articleIntro:"Un guide factuel centré sur l’acheteur pour consigner ses choix, examiner les informations d’entrepôt et décider de l’envoi avec méthode.",articleSource:"Note de recherche : cet article indépendant s’appuie sur la page d’accueil publique de LoloBuy, consultée en septembre 2026. Les détails du service peuvent évoluer ; vérifiez les écrans actuels du compte et du colis."},
  es:{check:"REVISA EL CONTEXTO",discover:"DESCUBRE",plan:"PLANIFICA",categoryCount:"10 CATEGORÍAS",buyerCheck:"COMPROBACIÓN DEL COMPRADOR",workflow:"FLUJO DEL COMPRADOR",reading:"LECTURA BASADA EN HECHOS",answers:"RESPUESTAS CLARAS",categoryNames:["Zapatos","Sudaderas con capucha","Camisetas","Chaquetas","Pantalones","Sombreros","Bolsos","Relojes","Electrónica","Accesorios"],detailCards:["Material y fabricación","Contexto de talla","Puntos de QC","Precio y disponibilidad"],guideSteps:["Elige un producto","Revisa la información de almacén","Evalúa las opciones de destino"],articleTitle:"Cómo usar LoloBuy para investigar productos: una ruta práctica del pedido al paquete",articleIntro:"Una guía factual y centrada en el comprador para registrar elecciones, revisar información de almacén y decidir el envío con criterio.",articleSource:"Nota de investigación: este artículo independiente se basa en la página pública de LoloBuy revisada en septiembre de 2026. Los detalles del servicio pueden cambiar; consulta las pantallas actuales de cuenta y paquete."},
  it:{check:"CONTROLLA IL CONTESTO",discover:"SCOPRI",plan:"PIANIFICA",categoryCount:"10 CATEGORIE",buyerCheck:"CONTROLLO ACQUIRENTE",workflow:"PERCORSO DELL’ACQUIRENTE",reading:"LETTURA BASATA SUI FATTI",answers:"RISPOSTE CHIARE",categoryNames:["Scarpe","Felpe con cappuccio","T-shirt","Giacche","Pantaloni","Copricapi","Borse","Orologi","Elettronica","Accessori"],detailCards:["Materiale e costruzione","Contesto delle taglie","Verifiche QC","Prezzo e disponibilità"],guideSteps:["Scegli un prodotto","Controlla le informazioni del magazzino","Valuta le opzioni di destinazione"],articleTitle:"Usare LoloBuy per la ricerca prodotto: un percorso pratico dall’ordine al pacco",articleIntro:"Una guida concreta e centrata sull’acquirente per annotare le scelte, esaminare le informazioni del magazzino e decidere la spedizione con cura.",articleSource:"Nota di ricerca: questo articolo indipendente si basa sulla homepage pubblica di LoloBuy, consultata nel settembre 2026. I dettagli del servizio possono cambiare; usa le schermate attuali dell’account e del pacco."},
  pl:{check:"SPRAWDŹ KONTEKST",discover:"ODKRYWAJ",plan:"ZAPLANUJ",categoryCount:"10 KATEGORII",buyerCheck:"KONTROLA KUPUJĄCEGO",workflow:"ŚCIEŻKA KUPUJĄCEGO",reading:"LEKTURA OPARTA NA FAKTACH",answers:"JASNE ODPOWIEDZI",categoryNames:["Buty","Bluzy z kapturem","T-shirty","Kurtki","Spodnie","Nakrycia głowy","Torby","Zegarki","Elektronika","Akcesoria"],detailCards:["Materiał i wykonanie","Kontekst rozmiaru","Pytania QC","Cena i dostępność"],guideSteps:["Wybierz produkt","Sprawdź informacje z magazynu","Przejrzyj opcje dla kraju docelowego"],articleTitle:"Jak używać LoloBuy do badania produktów: praktyczna droga od zamówienia do paczki",articleIntro:"Rzeczowy przewodnik dla kupującego: jak zapisać wybór produktu, ocenić informacje z magazynu i świadomie wybrać wysyłkę.",articleSource:"Uwaga badawcza: ten niezależny artykuł opiera się na publicznej stronie głównej LoloBuy, sprawdzonej we wrześniu 2026 r. Szczegóły usługi mogą się zmienić; sprawdzaj bieżące ekrany konta i paczki."},
  pt:{check:"VERIFIQUE O CONTEXTO",discover:"DESCUBRA",plan:"PLANEIE",categoryCount:"10 CATEGORIAS",buyerCheck:"VERIFICAÇÃO DO COMPRADOR",workflow:"PERCURSO DO COMPRADOR",reading:"LEITURA BASEADA EM FACTOS",answers:"RESPOSTAS CLARAS",categoryNames:["Sapatos","Camisolas com capuz","T-shirts","Casacos","Calças","Chapéus","Malas","Relógios","Eletrónica","Acessórios"],detailCards:["Material e construção","Contexto de tamanho","Pontos de QC","Preço e disponibilidade"],guideSteps:["Escolha um produto","Verifique informações do armazém","Analise opções de destino"],articleTitle:"Como usar a LoloBuy para pesquisar produtos: um percurso prático da encomenda ao pacote",articleIntro:"Um guia factual centrado no comprador para registar escolhas, analisar informações do armazém e decidir a expedição com cuidado.",articleSource:"Nota de pesquisa: este artigo independente baseia-se na página pública da LoloBuy, consultada em setembro de 2026. Os detalhes do serviço podem mudar; confirme nos ecrãs atuais de conta e pacote."},
  sv:{check:"KONTROLLERA SAMMANHANGET",discover:"UTFORSKA",plan:"PLANERA",categoryCount:"10 KATEGORIER",buyerCheck:"KÖPARKONTROLL",workflow:"KÖPARFLÖDE",reading:"FAKTABASERAD LÄSNING",answers:"TYDLIGA SVAR",categoryNames:["Skor","Hoodies","T-shirts","Jackor","Byxor","Huvudbonader","Väskor","Klockor","Elektronik","Tillbehör"],detailCards:["Material och konstruktion","Storlekssammanhang","QC-punkter","Pris och tillgänglighet"],guideSteps:["Välj en produkt","Kontrollera lagerinformation","Granska val för destinationen"],articleTitle:"Använd LoloBuy för produktresearch: ett praktiskt flöde från order till paket",articleIntro:"En saklig, köparcentrerad guide för att dokumentera produktval, granska lagerinformation och fatta ett genomtänkt fraktbeslut.",articleSource:"Forskningsnotering: denna oberoende artikel bygger på LoloBuys offentliga startsida, granskad i september 2026. Tjänstedetaljer kan ändras; kontrollera aktuella konto- och paketvyer."}
};
const categorySlug = (name:string) => name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
const categoryDestination: Record<string,string> = {
  shoes:"https://findspreadsheet.com/shoes/",
  hoodies:"https://findspreadsheet.com/hoodies-sweaters/",
  "t-shirts":"https://findspreadsheet.com/t-shirts/",
  jackets:"https://findspreadsheet.com/jackets/",
  pants:"https://findspreadsheet.com/pants-shorts/",
  headwear:"https://findspreadsheet.com/headwear/",
  bags:"https://findspreadsheet.com/search.html?keywords=Bags&channelid=2",
  watches:"https://findspreadsheet.com/electronics/",
  electronics:"https://findspreadsheet.com/electronics/",
  accessories:"https://findspreadsheet.com/accessories/"
};
const categoryDetailCopy: Record<string,{label:string;checks:string[];on:string;open:string}> = {
  en:{label:"Category detail",checks:["Check product notes before adding an item.","Compare measurements and available options.","Use the current listing for price and availability."],on:"on",open:"Open"},
  nl:{label:"Categoriedetails",checks:["Controleer productnotities voordat je een item toevoegt.","Vergelijk afmetingen en beschikbare opties.","Gebruik de actuele listing voor prijs en beschikbaarheid."],on:"op",open:"Open"},
  de:{label:"Kategoriedetails",checks:["Produktinformationen vor dem Hinzufügen prüfen.","Maße und verfügbare Optionen vergleichen.","Die aktuelle Produktseite für Preis und Verfügbarkeit nutzen."],on:"auf",open:"Öffnen"},
  fr:{label:"Détail de la catégorie",checks:["Vérifiez les notes produit avant d’ajouter un article.","Comparez les mesures et les options disponibles.","Utilisez la fiche actuelle pour le prix et la disponibilité."],on:"sur",open:"Ouvrir"},
  es:{label:"Detalle de categoría",checks:["Revisa las notas del producto antes de añadir un artículo.","Compara medidas y opciones disponibles.","Usa la ficha actual para precio y disponibilidad."],on:"en",open:"Abrir"},
  it:{label:"Dettaglio categoria",checks:["Controlla le note sul prodotto prima di aggiungere un articolo.","Confronta misure e opzioni disponibili.","Usa la scheda attuale per prezzo e disponibilità."],on:"su",open:"Apri"},
  pl:{label:"Szczegóły kategorii",checks:["Sprawdź notatki o produkcie przed dodaniem artykułu.","Porównaj wymiary i dostępne opcje.","Korzystaj z aktualnej oferty dla ceny i dostępności."],on:"na",open:"Otwórz"},
  pt:{label:"Detalhe da categoria",checks:["Verifique as notas do produto antes de adicionar um artigo.","Compare medidas e opções disponíveis.","Use a página atual para preço e disponibilidade."],on:"em",open:"Abrir"},
  sv:{label:"Kategoridetaljer",checks:["Kontrollera produktanteckningar innan du lägger till en artikel.","Jämför mått och tillgängliga alternativ.","Använd den aktuella produktsidan för pris och tillgänglighet."],on:"på",open:"Öppna"}
};

function Brand() {
  return <Link className="brand logo-brand notranslate" href="/" aria-label="LoloBuy home"><span className="reference-logo" aria-hidden="true" /></Link>;
}

export default function SiteExperience({page}:{page:Page}) {
  const [locale,setLocale]=useState("en"); const [query,setQuery]=useState(""); const t=copy[locale];
  const l=pageLabels[locale] ?? pageLabels.en;
  const article=localizedArticles[locale] ?? seoArticle;
  const articleContinuations=localizedArticleContinuations[locale] ?? [];
  const articleDetails=localizedArticleDetailAdditions[locale] ?? [];
  const pageIndex=routeKeys.indexOf(page);
  const navLabels=t.nav.map((label,index)=>index===4?(seoNavigation[locale] ?? seoNavigation.en):label);
  const title=page==="home"?t.title:navLabels[pageIndex]; const intro=page==="home"?t.intro:[t.sectionBody,t.guideBody,t.guideBody,t.articleBody,t.faqBody][pageIndex-1];
  const search=(event:FormEvent)=>{event.preventDefault();const term=query.trim();window.location.assign(term?`https://findspreadsheet.com/search.html?keywords=${encodeURIComponent(term)}&channelid=2`:"https://findspreadsheet.com/AllProducts/")};
  return <main className="site-shell" translate="no">
    <header className="nav"><Brand /><nav>{routes.map((r,i)=><a key={r} className={i===pageIndex?"active":""} href={r} aria-current={i===pageIndex?"page":undefined}>{navLabels[i]}</a>)}</nav><select aria-label="Language" value={locale} onChange={e=>setLocale(e.target.value)}>{Object.entries(copy).map(([k,v])=><option key={k} value={k}>{v.code} · {v.name}</option>)}</select></header>
    <section className={page==="home"?"hero":"hero compact"}>{page==="home"&&<div className="hero-visual" aria-hidden="true"/>}<div className="hero-copy"><p className="eyebrow">{t.eyebrow}</p><h1>{title}</h1><p className="lede">{intro}</p><div className="actions"><form className="hero-search" onSubmit={search}><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={t.search} aria-label={t.search}/><button type="submit">{t.search} →</button></form><a className="outline" href="https://findspreadsheet.com" target="_blank" rel="noopener noreferrer">FindSpreadsheet</a></div><small>{t.note}</small></div></section>
    {page==="home"&&<><section className="signal"><div><p className="kicker">01 / {l.check}</p><h2>{t.faq}</h2></div><p>{t.faqBody}</p></section><section className="section"><div className="head"><div><p className="kicker">02 / {l.discover}</p><h2>{t.section}</h2></div><p>{t.sectionBody}</p></div><CategoryGrid t={t} labels={l}/></section><section className="blue"><p className="kicker">03 / {l.plan}</p><h2>{t.guide}</h2><p>{t.guideBody}</p><Link href="/guides">{t.nav[3]} →</Link></section></>}
    {page==="categories"&&<section className="section"><div className="head"><div><p className="kicker">{l.categoryCount}</p><h2>{t.section}</h2></div><p>{t.sectionBody}</p></div><CategoryGrid t={t} labels={l}/></section>}
    {page==="details"&&<section className="section details"><div><p className="kicker">{l.buyerCheck}</p><h2>{t.faq}</h2><p>{t.faqBody}</p><a href="https://findspreadsheet.com" target="_blank" rel="noopener noreferrer">FindSpreadsheet →</a></div><div className="cards">{l.detailCards.map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3><p>{t.faqBody}</p></article>)}</div></section>}
    {page==="guides"&&<section className="section guides"><p className="kicker">{l.workflow}</p><h2>{t.guide}</h2><p className="wide">{t.guideBody}</p>{l.guideSteps.map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3><p>{i===2?t.source:t.faqBody}</p></article>)}</section>}
    {page==="articles"&&<section className="section articles article-page"><p className="kicker">{l.reading}</p><article className="seo-article"><span>{article.reviewed}</span><h2>{article.title}</h2><p className="article-intro">{article.intro}</p>{article.sections.map((section,index)=><section key={section.heading}><h3>{section.heading}</h3>{section.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}{articleContinuations[index]&&<p>{articleContinuations[index]} {articleDetails[index]}</p>}</section>)}<p className="article-source">{l.articleSource}</p></article></section>}
    {page==="faq"&&<section className="section faq"><p className="kicker">{l.answers}</p><h2>{t.faq}</h2>{(factualFaq[locale] ?? factualFaq.en).map((item,i)=><details key={item.question} open={i===0}><summary>{item.question}</summary><p>{item.answer}</p></details>)}</section>}
    <footer><Brand /><p>{t.source}</p><a href="https://findspreadsheet.com" target="_blank" rel="noopener noreferrer">FindSpreadsheet ↗</a></footer>
  </main>
}
function CategoryGrid({t,labels}:{t:Copy;labels:PageLabels}){return <div className="grid">{categories.map((x,i)=><Link key={x} href={`/categories/${categorySlug(x)}`}><span>0{i+1}</span><h3>{labels.categoryNames[i]}</h3><p>{t.sectionBody}</p><b>→</b></Link>)}</div>}

export function CategoryDetail({slug}:{slug:string}) {
  const [locale,setLocale]=useState("en"); const t=copy[locale];
  const l=pageLabels[locale] ?? pageLabels.en;
  const navLabels=t.nav.map((label,index)=>index===4?(seoNavigation[locale] ?? seoNavigation.en):label);
  const detail=categoryDetailCopy[locale];
  const categoryIndex=categories.findIndex(x=>categorySlug(x)===slug);
  const name=l.categoryNames[categoryIndex] ?? t.section;
  const destination=categoryDestination[slug] ?? "https://findspreadsheet.com/AllProducts/";
  return <main className="site-shell" translate="no">
    <header className="nav"><Brand /><nav>{routes.map((r,i)=><a key={r} className={i===1?"active":""} href={r} aria-current={i===1?"page":undefined}>{navLabels[i]}</a>)}</nav><select aria-label="Language" value={locale} onChange={e=>setLocale(e.target.value)}>{Object.entries(copy).map(([k,v])=><option key={k} value={k}>{v.code} · {v.name}</option>)}</select></header>
    <section className="category-hero"><p className="eyebrow">{t.section}</p><h1>{name}</h1><p>{t.sectionBody}</p></section>
    <section className="category-detail">
      <article className="category-copy"><p className="kicker">{detail.label}</p><h2>{name}</h2><p>{t.faqBody}</p><ul>{detail.checks.map(check=><li key={check}>{check}</li>)}</ul></article>
      <a className="category-action" href={destination} target="_blank" rel="noopener noreferrer" aria-label={`${detail.open} ${name}`}><p>{t.explore}</p><h3>{name} {detail.on} FindSpreadsheet</h3><span className="category-open">{detail.open} {name} →</span><small>{t.independent}</small></a>
    </section>
    <footer><Brand /><p>{t.source}</p><a href="https://findspreadsheet.com" target="_blank" rel="noopener noreferrer">FindSpreadsheet ↗</a></footer>
  </main>;
}
