"use client";

import { useEffect, useState } from "react";
import { SiteHeader } from "@/components/site-header";

type Locale = "en" | "de" | "fr" | "es" | "it" | "pt" | "nl" | "pl" | "sv";
type Content = { tag: string; kicker: string; title: string; body: string; open: string; search: string; verified: string; fact: string; route: string; routeBody: string; categories: string; categoryBody: string; proof: string; proofBody: string; read: string; note: string; steps: string[]; stepText: string[]; cats: string[] };

const text: Record<Locale, Content> = {
  en: { tag:"INDEPENDENT RESEARCH DESK · 2026", kicker:"Build a clearer buying route.", title:"A LoloBuy spreadsheet that starts with evidence.", body:"A calm research desk for product discovery, warehouse-photo checks and parcel planning — created for shoppers in Europe and North America.", open:"Open database", search:"Search the FindSpreadsheet database", verified:"What we verified", fact:"LoloBuy publicly describes warehouse quality inspection with feedback and global shipping. Country-by-country user totals are not published.", route:"Choose your route", routeBody:"Begin with the product question, then move through visible QC evidence before planning a parcel.", categories:"Browse by category", categoryBody:"Ten focused entry points. Each one leads to the maintained FindSpreadsheet database.", proof:"A better ranking should be earned", proofBody:"Useful editorial pages, crawlable category context and dated source notes matter more than recycled product lists.", read:"Read the research method", note:"Independent resource. Not operated by or affiliated with LoloBuy, sellers or marketplaces.", steps:["Find","Inspect","Plan"], stepText:["Start with a precise product question.","Compare the order record with visible warehouse evidence.","Confirm current shipping terms before paying."], cats:["Jackets","T-Shirts","Shoes","Hoodies","Pants","Sets","Bags & Wallets","Accessories","Electronics","Home"] },
  de: { tag:"UNABHÄNGIGE RECHERCHE · 2026", kicker:"Klarer einkaufen.", title:"Ein LoloBuy-Verzeichnis, das mit Belegen beginnt.", body:"Ein Recherchebereich für Produktfindung, Lagerfotos und Paketplanung — für Käufer in Europa und Nordamerika.", open:"Datenbank öffnen", search:"FindSpreadsheet-Datenbank durchsuchen", verified:"Was wir geprüft haben", fact:"LoloBuy beschreibt öffentlich Lagerprüfung mit Rückmeldung und globalen Versand. Nutzerzahlen nach Ländern werden nicht veröffentlicht.", route:"Deine Route wählen", routeBody:"Starte mit der Produktfrage, prüfe sichtbare QC-Belege und plane dann das Paket.", categories:"Nach Kategorie suchen", categoryBody:"Zehn klare Einstiege führen zur gepflegten FindSpreadsheet-Datenbank.", proof:"Besseres Ranking muss verdient sein", proofBody:"Hilfreiche Artikel, crawlbarer Kategorie-Kontext und datierte Quellen sind wichtiger als kopierte Listen.", read:"Recherche-Methode lesen", note:"Unabhängige Ressource. Nicht von LoloBuy, Verkäufern oder Marktplätzen betrieben.", steps:["Finden","Prüfen","Planen"], stepText:["Mit einer konkreten Produktfrage beginnen.","Bestellung mit sichtbaren Lagerbelegen vergleichen.","Aktuelle Versandbedingungen vor der Zahlung bestätigen."], cats:["Jacken","T-Shirts","Schuhe","Hoodies","Hosen","Sets","Taschen & Geldbörsen","Accessoires","Elektronik","Wohnen"] },
  fr: { tag:"BUREAU DE RECHERCHE INDÉPENDANT · 2026", kicker:"Un parcours d’achat plus clair.", title:"Un guide LoloBuy qui commence par les preuves.", body:"Un espace de recherche pour la découverte, les photos d’entrepôt et la préparation des colis — pour l’Europe et l’Amérique du Nord.", open:"Ouvrir la base", search:"Rechercher dans FindSpreadsheet", verified:"Ce que nous avons vérifié", fact:"LoloBuy indique publiquement une inspection en entrepôt avec retour et une expédition mondiale. Les chiffres par pays ne sont pas publiés.", route:"Choisir votre parcours", routeBody:"Commencez par la question produit, vérifiez les éléments QC visibles, puis préparez le colis.", categories:"Parcourir par catégorie", categoryBody:"Dix entrées ciblées vers la base FindSpreadsheet maintenue.", proof:"Un meilleur classement se mérite", proofBody:"Des guides utiles, du contexte indexable et des sources datées valent mieux que des listes recyclées.", read:"Lire la méthode", note:"Ressource indépendante, non affiliée à LoloBuy, aux vendeurs ou aux marketplaces.", steps:["Trouver","Vérifier","Planifier"], stepText:["Partir d’une question produit précise.","Comparer la commande avec les éléments visibles.","Confirmer les conditions d’expédition avant paiement."], cats:["Vestes","T-shirts","Chaussures","Sweats à capuche","Pantalons","Ensembles","Sacs & portefeuilles","Accessoires","Électronique","Maison"] },
  es: { tag:"MESA DE INVESTIGACIÓN INDEPENDIENTE · 2026", kicker:"Una ruta de compra más clara.", title:"Una guía LoloBuy que empieza con evidencia.", body:"Un espacio de investigación para descubrir productos, revisar fotos de almacén y planificar paquetes — para Europa y Norteamérica.", open:"Abrir base de datos", search:"Buscar en FindSpreadsheet", verified:"Lo que verificamos", fact:"LoloBuy describe públicamente inspección de almacén con comentarios y envío global. No publica cifras por país.", route:"Elige tu ruta", routeBody:"Empieza con la pregunta del producto, revisa la evidencia QC visible y después planifica el paquete.", categories:"Explorar por categoría", categoryBody:"Diez accesos claros hacia la base FindSpreadsheet mantenida.", proof:"Un mejor ranking se gana", proofBody:"Guías útiles, contexto rastreable y fuentes fechadas superan las listas recicladas.", read:"Leer el método", note:"Recurso independiente; no está operado ni afiliado con LoloBuy, vendedores o marketplaces.", steps:["Encontrar","Inspeccionar","Planificar"], stepText:["Empieza con una pregunta de producto precisa.","Compara el pedido con evidencia visible del almacén.","Confirma los términos de envío antes de pagar."], cats:["Chaquetas","Camisetas","Zapatos","Sudaderas","Pantalones","Conjuntos","Bolsos & carteras","Accesorios","Electrónica","Hogar"] },
  it: { tag:"DESK DI RICERCA INDIPENDENTE · 2026", kicker:"Un percorso d’acquisto più chiaro.", title:"Una guida LoloBuy che parte dalle prove.", body:"Uno spazio di ricerca per scoprire prodotti, controllare foto di magazzino e pianificare pacchi — per Europa e Nord America.", open:"Apri database", search:"Cerca in FindSpreadsheet", verified:"Cosa abbiamo verificato", fact:"LoloBuy descrive pubblicamente controlli in magazzino con feedback e spedizione globale. I dati per paese non sono pubblicati.", route:"Scegli il percorso", routeBody:"Parti dalla domanda sul prodotto, verifica le prove QC visibili e poi pianifica il pacco.", categories:"Sfoglia per categoria", categoryBody:"Dieci accessi mirati alla banca dati FindSpreadsheet.", proof:"Un ranking migliore va guadagnato", proofBody:"Guide utili, contesto indicizzabile e fonti datate valgono più di elenchi riciclati.", read:"Leggi il metodo", note:"Risorsa indipendente, non gestita né affiliata a LoloBuy, venditori o marketplace.", steps:["Trova","Ispeziona","Pianifica"], stepText:["Inizia con una domanda precisa.","Confronta l’ordine con le prove visibili.","Conferma le condizioni di spedizione prima del pagamento."], cats:["Giacche","T-shirt","Scarpe","Felpe","Pantaloni","Set","Borse & portafogli","Accessori","Elettronica","Casa"] },
  pt: { tag:"CENTRO DE PESQUISA INDEPENDENTE · 2026", kicker:"Uma rota de compra mais clara.", title:"Um guia LoloBuy que começa pela evidência.", body:"Um espaço de pesquisa para descoberta de produtos, fotos de armazém e planeamento de encomendas — para Europa e América do Norte.", open:"Abrir base de dados", search:"Pesquisar no FindSpreadsheet", verified:"O que verificámos", fact:"A LoloBuy descreve publicamente inspeção no armazém com feedback e envio global. Não publica números por país.", route:"Escolha a sua rota", routeBody:"Comece pela questão do produto, reveja evidência QC visível e planeie a encomenda.", categories:"Explorar por categoria", categoryBody:"Dez pontos de entrada para a base FindSpreadsheet.", proof:"Um melhor ranking tem de ser conquistado", proofBody:"Guias úteis, contexto rastreável e fontes datadas superam listas recicladas.", read:"Ler o método", note:"Recurso independente; não é operado nem afiliado à LoloBuy, vendedores ou marketplaces.", steps:["Encontrar","Inspecionar","Planear"], stepText:["Comece por uma questão precisa.","Compare o pedido com a evidência visível.","Confirme os termos de envio antes de pagar."], cats:["Casacos","T-shirts","Sapatos","Hoodies","Calças","Conjuntos","Bolsas & carteiras","Acessórios","Eletrónica","Casa"] },
  nl: { tag:"ONAFHANKELIJK ONDERZOEK · 2026", kicker:"Een duidelijkere kooproute.", title:"Een LoloBuy-gids die met bewijs begint.", body:"Een rustig onderzoeksplatform voor productontdekking, magazijnfoto’s en pakketplanning — voor Europa en Noord-Amerika.", open:"Database openen", search:"Zoek in FindSpreadsheet", verified:"Wat we hebben gecontroleerd", fact:"LoloBuy beschrijft publiekelijk magazijninspectie met feedback en wereldwijde verzending. Landcijfers zijn niet gepubliceerd.", route:"Kies je route", routeBody:"Begin met de productvraag, controleer zichtbaar QC-bewijs en plan daarna het pakket.", categories:"Bladeren op categorie", categoryBody:"Tien gerichte ingangen naar de onderhouden FindSpreadsheet-database.", proof:"Een betere ranking verdien je", proofBody:"Nuttige gidsen, crawlbare context en gedateerde bronnen zijn beter dan gerecyclede lijsten.", read:"Lees de methode", note:"Onafhankelijke bron; niet beheerd door of verbonden aan LoloBuy, verkopers of marktplaatsen.", steps:["Vind","Inspecteer","Plan"], stepText:["Begin met een gerichte productvraag.","Vergelijk de bestelling met zichtbaar bewijs.","Bevestig de verzendvoorwaarden vóór betaling."], cats:["Jassen","T-shirts","Schoenen","Hoodies","Broeken","Sets","Tassen & portemonnees","Accessoires","Elektronica","Wonen"] },
  pl: { tag:"NIEZALEŻNE CENTRUM BADAŃ · 2026", kicker:"Jaśniejsza ścieżka zakupu.", title:"Przewodnik LoloBuy zaczynający się od dowodów.", body:"Miejsce do badania produktów, zdjęć magazynowych i planowania paczek — dla Europy i Ameryki Północnej.", open:"Otwórz bazę", search:"Szukaj w FindSpreadsheet", verified:"Co sprawdziliśmy", fact:"LoloBuy publicznie opisuje inspekcję magazynową z informacją zwrotną i globalną wysyłkę. Dane krajowe nie są publikowane.", route:"Wybierz trasę", routeBody:"Zacznij od pytania o produkt, sprawdź widoczne dowody QC, a potem zaplanuj paczkę.", categories:"Przeglądaj kategorie", categoryBody:"Dziesięć wejść do aktualnej bazy FindSpreadsheet.", proof:"Lepsza pozycja musi być zasłużona", proofBody:"Przydatne poradniki, indeksowalny kontekst i datowane źródła są lepsze niż kopiowane listy.", read:"Przeczytaj metodę", note:"Niezależne źródło; nie jest prowadzone ani powiązane z LoloBuy, sprzedawcami lub marketplace’ami.", steps:["Znajdź","Sprawdź","Zaplanuj"], stepText:["Zacznij od precyzyjnego pytania.","Porównaj zamówienie z widocznymi dowodami.","Potwierdź warunki wysyłki przed płatnością."], cats:["Kurtki","T-shirty","Buty","Bluzy","Spodnie","Zestawy","Torby & portfele","Akcesoria","Elektronika","Dom"] },
  sv: { tag:"OBEROENDE RESEARCHDESK · 2026", kicker:"En tydligare köpresa.", title:"En LoloBuy-guide som börjar med bevis.", body:"En lugn researchyta för produktupptäckt, lagerfoton och paketplanering — för Europa och Nordamerika.", open:"Öppna databasen", search:"Sök i FindSpreadsheet", verified:"Det vi har kontrollerat", fact:"LoloBuy beskriver offentligt lagerinspektion med återkoppling och global frakt. Användarsiffror per land publiceras inte.", route:"Välj din väg", routeBody:"Börja med produktfrågan, kontrollera synliga QC-bevis och planera sedan paketet.", categories:"Bläddra efter kategori", categoryBody:"Tio tydliga ingångar till den uppdaterade FindSpreadsheet-databasen.", proof:"Bättre ranking ska förtjänas", proofBody:"Användbara guider, genomsökbar kontext och daterade källor är bättre än återanvända listor.", read:"Läs metoden", note:"Oberoende resurs; inte driven av eller ansluten till LoloBuy, säljare eller marknadsplatser.", steps:["Hitta","Granska","Planera"], stepText:["Börja med en exakt produktfråga.","Jämför ordern med synliga lagerbevis.","Bekräfta aktuella fraktvillkor före betalning."], cats:["Jackor","T-shirts","Skor","Hoodies","Byxor","Set","Väskor & plånböcker","Accessoarer","Elektronik","Hem"] }
};

const homeLabels: Record<Locale, string> = {
  en: "Home", de: "Startseite", fr: "Accueil", es: "Inicio", it: "Home",
  pt: "Início", nl: "Home", pl: "Strona główna", sv: "Hem",
};
const categoryQueries = [
  "Jackets", "T-Shirts", "Shoes", "Hoodies", "Pants",
  "Sets", "Bags & Wallets", "Accessories", "Electronics", "Home",
] as const;
const homeCards: Record<Locale, [string, string, string]> = {
  en:["Product details","SEO articles","FAQ"], de:["Produktdetails","SEO-Artikel","FAQ"], fr:["Détails produits","Articles SEO","FAQ"], es:["Detalles del producto","Artículos SEO","FAQ"], it:["Dettagli prodotto","Articoli SEO","FAQ"], pt:["Detalhes do produto","Artigos SEO","FAQ"], nl:["Productdetails","SEO-artikelen","FAQ"], pl:["Szczegóły produktu","Artykuły SEO","FAQ"], sv:["Produktdetaljer","SEO-artiklar","FAQ"]
};

export default function Home() {
  const [locale, setLocale] = useState<Locale>("en");
  const [query, setQuery] = useState("");
  useEffect(() => { const value = new URLSearchParams(window.location.search).get("lang") as Locale | null; if (value && value in text) setLocale(value); }, []);
  const t = text[locale];
  const cards = homeCards[locale];
  return <main className="min-h-screen overflow-x-hidden bg-[#e8ebf4] text-[#10213b]"><div className="mx-auto max-w-7xl px-5 pb-12 pt-5 sm:px-8 lg:px-12">
    <SiteHeader />
    <section id="atlas" className="relative mt-4 overflow-hidden rounded-[2rem] bg-[#072667] text-white shadow-[0_25px_70px_rgba(16,33,59,.22)]"><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(4,24,68,.96)_0%,rgba(4,24,68,.89)_42%,rgba(4,24,68,.15)_76%)]"/><div className="relative grid min-h-[560px] items-end px-7 py-9 sm:px-11 lg:min-h-[620px] lg:px-16 lg:py-16"><div className="max-w-xl"><p className="mb-5 text-xs font-bold tracking-[.16em] text-[#ff9b85]">{t.tag}</p><p className="mb-3 text-lg font-semibold text-[#c8d6ff]">{t.kicker}</p><h1 className="text-4xl font-black leading-[.94] tracking-[-.065em] sm:text-6xl lg:text-7xl">{t.title}</h1><p className="mt-6 max-w-lg text-base leading-relaxed text-[#d7e0fb] sm:text-lg">{t.body}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="https://findspreadsheet.com" className="inline-flex min-h-12 items-center justify-center rounded-xl bg-[#ff6947] px-5 text-sm font-extrabold text-[#10213b]">{t.open} <span className="ml-2">↗</span></a><a href="#method" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-white/35 bg-white/10 px-5 text-sm font-bold text-white backdrop-blur-sm">{t.read}</a></div></div></div></section>
    <form action="https://findspreadsheet.com/search.html" method="get" className="relative z-10 mx-auto -mt-7 grid max-w-5xl gap-3 rounded-2xl border border-[#cbd3e6] bg-[#f8f9fd] p-3 shadow-xl sm:grid-cols-[1fr_auto] sm:p-4"><input type="hidden" name="channelid" value="2"/><label className="flex min-h-12 items-center gap-3 rounded-xl bg-[#e8edf9] px-4 text-sm font-medium text-[#5b6680]"><span aria-hidden="true">⌕</span><span className="sr-only">{t.search}</span><input required name="keywords" value={query} onChange={event=>setQuery(event.target.value)} placeholder={t.search} className="w-full bg-transparent text-[#10213b] outline-none placeholder:text-[#5b6680]"/></label><button type="submit" className="inline-flex min-h-12 items-center justify-center rounded-xl bg-[#1647cf] px-5 text-sm font-bold text-white">{t.open}</button></form>
    <section className="grid gap-3 py-8 md:grid-cols-3">{["/product-details","/seo-articles","/faq"].map((path,index)=><a key={path} href={`${path}?lang=${locale}`} className="group min-h-36 rounded-2xl border border-[#cbd3e6] bg-white p-6 transition hover:-translate-y-1 hover:border-[#1647cf] hover:shadow-lg"><span className="text-xs font-bold text-[#ff6947]">0{index+1}</span><h2 className="mt-10 text-2xl font-black tracking-[-.04em] group-hover:text-[#1647cf]">{cards[index]}</h2><span className="mt-3 inline-block text-sm font-bold text-[#5b6680]">→</span></a>)}</section>
    <section className="grid gap-7 py-14 lg:grid-cols-[1.05fr_.95fr]"><div><p className="text-xs font-extrabold tracking-[.16em] text-[#ff6947]">01 / {t.verified.toUpperCase()}</p><h2 className="mt-3 max-w-xl text-3xl font-black leading-tight tracking-[-.045em] sm:text-4xl">{t.fact}</h2></div><div className="rounded-3xl border border-[#cbd3e6] bg-[#f8f9fd] p-6"><p className="text-xs font-bold tracking-[.12em] text-[#5b6680]">2026.09.12</p><p className="mt-4 text-base leading-relaxed text-[#40506d]">{t.proofBody}</p></div></section>
    <section id="method" className="rounded-[2rem] bg-[#10213b] p-6 text-white sm:p-9"><div className="flex justify-end"><p className="max-w-md text-sm leading-relaxed text-[#b9c6e4]">{t.routeBody}</p></div><div className="mt-8 grid gap-3 md:grid-cols-3">{t.steps.map((step,i)=><article key={step} className="rounded-2xl border border-white/15 bg-white/[.06] p-5"><span className="text-4xl font-black text-[#ff6947]">0{i+1}</span><h3 className="mt-7 text-xl font-extrabold">{step}</h3><p className="mt-2 leading-relaxed text-[#c8d3ea]">{t.stepText[i]}</p></article>)}</div></section>
    <section id="categories" className="py-14"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-extrabold tracking-[.16em] text-[#ff6947]">03</p><h2 className="mt-2 text-3xl font-black tracking-[-.05em]">{t.categories}</h2></div><p className="max-w-md text-sm leading-relaxed text-[#5b6680]">{t.categoryBody}</p></div><div className="mt-7 grid grid-cols-2 gap-3 md:grid-cols-5">{t.cats.map((category,i)=><a href={`https://findspreadsheet.com/search.html?keywords=${encodeURIComponent(categoryQueries[i])}&channelid=2`} key={category} className="group min-h-32 rounded-2xl border border-[#cbd3e6] bg-[#f8f9fd] p-4 transition hover:-translate-y-1 hover:border-[#1647cf] hover:shadow-lg"><span className="text-xs font-bold text-[#ff6947]">{String(i+1).padStart(2,"0")}</span><h3 className="mt-8 text-base font-extrabold leading-tight group-hover:text-[#1647cf]">{category}</h3></a>)}</div></section>
    <section id="guides" className="grid gap-6 border-t border-[#cbd3e6] py-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-extrabold tracking-[.16em] text-[#ff6947]">04</p><h2 className="mt-2 text-3xl font-black tracking-[-.05em]">{t.proof}</h2></div><div className="rounded-3xl bg-[#f8f9fd] p-7 shadow-sm"><p className="text-lg leading-relaxed text-[#40506d]">{t.proofBody}</p><a href="https://findspreadsheet.com" className="mt-6 inline-flex items-center font-extrabold text-[#1647cf]">{t.open} <span className="ml-2">→</span></a></div></section><footer className="border-t border-[#cbd3e6] py-8 text-sm leading-relaxed text-[#5b6680]"><span className="font-bold text-[#10213b]">atlas.</span> {t.note}</footer>
  </div></main>;
}
