export const categories = [
  { slug: "shoes", name: "Shoes", icon: "⌁", note: "Discover footwear finds from top spreadsheet sellers", detail: "Compare outsole shape, heel profile, side angles, material finish, size labels and current price context before opening a product row.", query: "Shoes" },
  { slug: "hoodies-sweaters", name: "Hoodies", icon: "♧", note: "Cozy hoodies and sweaters at unbeatable spreadsheet prices", detail: "Review fabric weight, print or embroidery placement, ribbing, sleeve length, measurements and seller photos.", query: "Hoodies" },
  { slug: "t-shirts", name: "T-Shirts", icon: "▣", note: "Trendy T-shirts from verified spreadsheet vendors", detail: "Check collar shape, print placement, measurements, fabric feel and the selected size before comparing listings.", query: "T-Shirts" },
  { slug: "jackets", name: "Jackets", icon: "◒", note: "Premium jackets and outerwear sourced through spreadsheet finds", detail: "Inspect panels, zippers, lining, cuffs, material texture, measurements and current listing photographs.", query: "Jackets" },
  { slug: "pants-shorts", name: "Pants", icon: "◱", note: "Stylish bottoms from curated spreadsheet collections", detail: "Compare waist and inseam measurements, fabric, pocket construction, logo placement and the chosen fit.", query: "Pants" },
  { slug: "headwear", name: "Hats", icon: "♙", note: "Caps, beanies and headwear from top spreadsheet sellers", detail: "Check crown shape, stitching, adjustable details, embroidery placement and size or fit notes.", query: "Hats" },
  { slug: "sets", name: "Watches", icon: "◇", note: "Complete outfit sets found through exclusive spreadsheets", detail: "Review every included piece together, then compare colour matching, measurements and current seller images.", query: "Watches" },
  { slug: "underwear-underpants", name: "Electronics", icon: "▤", note: "Essential undergarments at spreadsheet wholesale prices", detail: "Confirm material, sizing, pack quantity, visible finish and the exact variant selected in the live result.", query: "Electronics" },
  { slug: "jersey", name: "Socks", icon: "◉", note: "Sports jerseys and athletic wear from spreadsheet finds", detail: "Inspect name and number printing, badge placement, fabric panels, sizing chart and current listing details.", query: "Socks" },
  { slug: "accessories", name: "Accessories", icon: "▱", note: "Bags, wallets, jewelry and more spreadsheet accessories", detail: "Use close-ups for hardware, dimensions, material finish, packaging condition and compatibility information.", query: "Accessories" },
];
