(() => {
  const copy = {
    en:['From the reading room','QC, storage and parcel submission — read the full guide','A fact-led article that separates QC evidence, the eligible post-QC return window, warehouse storage and final parcel pricing.','Read the SEO guide','FAQ — the practical checks before paying','What should QC photos be used for?','Use them to check visible details against the exact variant ordered; they do not prove authenticity or electronic performance.','Why can the shipping amount change?','The estimate uses expected weight and route, while final billing follows the packed parcel’s actual size and weight.','Open all FAQ'],
    de:['Aus dem Leseraum','QC, Lagerung und Paketversand — den vollständigen Leitfaden lesen','Ein faktenbasierter Artikel, der QC-Nachweise, das mögliche Rückgabefenster nach QC, Lagerung und die endgültige Paketberechnung trennt.','SEO-Leitfaden lesen','FAQ — praktische Prüfungen vor der Zahlung','Wofür sollten QC-Fotos genutzt werden?','Prüfen Sie sichtbare Details gegen die bestellte Variante; sie beweisen weder Echtheit noch die Funktion von Elektronik.','Warum kann sich der Versandbetrag ändern?','Die Schätzung nutzt erwartetes Gewicht und Route; endgültig wird nach Größe und Gewicht des gepackten Pakets berechnet.','Alle FAQ öffnen'],
    fr:['Depuis la salle de lecture','QC, stockage et envoi du colis — lire le guide complet','Un article factuel qui distingue les preuves QC, la fenêtre de retour éventuellement disponible après QC, le stockage et le prix final du colis.','Lire le guide SEO','FAQ — vérifications utiles avant de payer','À quoi servent les photos QC ?','Elles permettent de comparer les détails visibles avec la variante commandée ; elles ne prouvent ni l’authenticité ni le fonctionnement électronique.','Pourquoi le montant d’expédition peut-il changer ?','L’estimation utilise le poids et la route prévus ; la facturation finale suit la taille et le poids réels du colis emballé.','Ouvrir toute la FAQ'],
    es:['Desde la sala de lectura','QC, almacenamiento y envío del paquete — leer la guía completa','Un artículo basado en hechos que separa la evidencia QC, la posible ventana de devolución tras QC, el almacenamiento y el precio final del paquete.','Leer la guía SEO','FAQ — comprobaciones prácticas antes de pagar','¿Para qué deben usarse las fotos QC?','Úsalas para contrastar detalles visibles con la variante pedida; no prueban autenticidad ni funcionamiento electrónico.','¿Por qué puede cambiar el importe de envío?','La estimación usa el peso y la ruta previstos; el cobro final sigue el tamaño y peso reales del paquete embalado.','Abrir todas las FAQ'],
    it:['Dalla sala di lettura','QC, deposito e invio del pacco — leggi la guida completa','Un articolo basato sui fatti che separa le prove QC, l’eventuale finestra di reso dopo QC, il deposito e il prezzo finale del pacco.','Leggi la guida SEO','FAQ — controlli pratici prima del pagamento','A cosa servono le foto QC?','Usale per confrontare i dettagli visibili con la variante ordinata; non provano autenticità o funzionamento elettronico.','Perché l’importo di spedizione può cambiare?','La stima usa peso e rotta previsti; l’addebito finale segue dimensioni e peso reali del pacco imballato.','Apri tutte le FAQ'],
    pt:['Da sala de leitura','QC, armazenamento e envio da encomenda — leia o guia completo','Um artigo baseado em factos que separa a evidência de QC, a possível janela de devolução após QC, o armazenamento e o preço final da encomenda.','Ler o guia SEO','FAQ — verificações práticas antes de pagar','Para que servem as fotos de QC?','Use-as para comparar detalhes visíveis com a variante encomendada; não comprovam autenticidade nem funcionamento eletrónico.','Porque é que o valor do envio pode mudar?','A estimativa usa peso e rota previstos; a cobrança final segue o tamanho e o peso reais da encomenda embalada.','Abrir todas as FAQ'],
    nl:['Uit de leesruimte','QC, opslag en pakketverzending — lees de volledige gids','Een feitelijk artikel dat QC-bewijs, het eventuele retourvenster na QC, opslag en de uiteindelijke pakketprijs van elkaar scheidt.','Lees de SEO-gids','FAQ — praktische controles vóór betaling','Waarvoor dienen QC-foto’s?','Gebruik ze om zichtbare details met de bestelde variant te vergelijken; ze bewijzen geen echtheid of elektronische werking.','Waarom kan het verzendbedrag veranderen?','De schatting gebruikt verwacht gewicht en route; de eindafrekening volgt de werkelijke afmetingen en het gewicht van het ingepakte pakket.','Open alle FAQ'],
    pl:['Z czytelni','QC, magazynowanie i wysyłka paczki — przeczytaj pełny przewodnik','Artykuł oparty na faktach, który rozdziela dowody QC, ewentualne okno zwrotu po QC, magazynowanie i ostateczną cenę paczki.','Przeczytaj przewodnik SEO','FAQ — praktyczne kontrole przed płatnością','Do czego służą zdjęcia QC?','Porównuj nimi widoczne szczegóły z zamówionym wariantem; nie potwierdzają autentyczności ani działania elektroniki.','Dlaczego kwota wysyłki może się zmienić?','Wycena używa przewidywanej wagi i trasy; końcowe rozliczenie opiera się na rzeczywistym rozmiarze i wadze zapakowanej paczki.','Otwórz pełne FAQ']
  };
  const mount=document.createElement('section');mount.className='home-reading';
  const target=document.querySelector('.outro');if(!target)return;target.before(mount);
  const style=document.createElement('style');style.textContent='.home-reading{padding:72px 0;border-top:1px solid var(--ink);display:grid;grid-template-columns:1fr 1fr;gap:34px}.home-reading article{border-top:3px solid var(--red);padding:18px 0}.home-reading h2{font:900 clamp(31px,3.8vw,55px)/.88 Arial,sans-serif;letter-spacing:-.075em;margin:13px 0 18px}.home-reading p{font-size:17px;line-height:1.45;max-width:610px}.home-reading details{border-top:1px solid var(--rule);padding:14px 0}.home-reading summary{font:800 18px/1.1 Arial,sans-serif;letter-spacing:-.035em;cursor:pointer;list-style:none}.home-reading summary:after{content:"+";float:right;color:var(--red)}.home-reading details p{margin:10px 26px 0 0;font-size:16px}.home-reading a{display:inline-block;margin-top:15px;border-bottom:2px solid var(--red);padding-bottom:5px;color:var(--red);font:800 11px Arial,sans-serif;letter-spacing:.1em;text-transform:uppercase}.home-reading .section-label{color:var(--red)}@media(max-width:850px){.home-reading{grid-template-columns:1fr;padding:54px 0;gap:28px}}';document.head.appendChild(style);
  function draw(lang){const d=copy[lang]||copy.en;mount.innerHTML='<article><div class="section-label">'+d[0]+'</div><h2>'+d[1]+'</h2><p>'+d[2]+'</p><a href="seo.html">'+d[3]+'</a></article><article><div class="section-label">'+d[0]+'</div><h2>'+d[4]+'</h2><details open><summary>'+d[5]+'</summary><p>'+d[6]+'</p></details><details><summary>'+d[7]+'</summary><p>'+d[8]+'</p></details><a href="faq.html">'+d[9]+'</a></article>';}
  document.addEventListener('joyagoo:language',event=>draw(event.detail.lang));draw(localStorage.getItem('joyagooLanguage')||'en');
})();
