export const UI_STRINGS = [
  "Primary navigation",
  "SEO Articles",
  "Shipping",
  "English",
  "Choose language",
  "24 localized paths",
  "All",
  "08 current records · source price retained",
  "Product carousel controls",
  "Previous products",
  "Next products",
  "Pause carousel",
  "Play carousel",
  "Latest and popular FindSpreadsheet products",
  "Latest",
  "Popular path",
  "Checked 12 Aug",
  "estimate · source",
  "Open record",
  "No matching preview record. Try a category or shorter term.",
  "Search opens matching results in the FindSpreadsheet product database.",
  "English routes",
  "language paths",
  "primary sources",
  "Official facts",
  "01 / ORDER",
  "Six stages",
  "Select → purchase → warehouse → ship",
  "Read the complete workflow",
  "02 / RETURNS",
  "120 hours",
  "Five-day window for eligible warehouse returns",
  "Read eligibility and fees",
  "03 / ESTIMATE",
  "6 inputs",
  "Destination, type, kg and three dimensions",
  "Read the shipping-cost guide",
  "Facts checked against pikobuy.com · 12 Aug 2026",
  "Official guide",
  "Warehouse photos",
  "Third-party carriers",
  "Five-day eligible return window",
  "Independent editorial layer",
  "Read before opening another tab",
  "See verification register",
  "Read field guide",
  "Complete SEO guides",
  "Complete research guides",
  "Each arrow opens its own evidence-led article, with official sources, practical checks and clearly stated limits.",
  "Different products need different evidence",
  "Each category opens the matching product collection on FindSpreadsheet.",
  "Open category on FindSpreadsheet",
  "Evidence register",
  "Material workflow and policy claims link to the exact official page. Product facts link to the corresponding FindSpreadsheet record. Advice is presented as editorial advice, not as an official promise.",
  "Open full source methodology",
  "Checked 12 Aug 2026",
  "Home",
  "Independent field guide",
  "Research desk",
  "Fact-checked 12 Aug 2026",
  "Primary source linked",
  "Quick answer",
  "00 / SOURCE BOUNDARY",
  "What the official source supports",
  "Start with the narrow claim the source can support. This avoids turning a useful policy or product detail into a promise that the source never made.",
  "Primary reference",
  "Last reviewed 12 August 2026. Open the official page for current wording and account-specific conditions.",
  "02 / PRACTICAL METHOD",
  "How to turn the source into a useful check",
  "A spreadsheet row is strongest when another person can repeat the check. Keep the raw destination, visible option, currency and date beside your notes; then write down what is known and what remains uncertain.",
  "03 / DECISION RULE",
  "Evidence first; the click comes last",
  "Open a product or agent route only after the row survives the relevant checks. A low price, familiar title or attractive first image is not enough. When details conflict, pause and resolve the source record instead of filling the gap with an assumption.",
  "Good research makes uncertainty visible. It does not hide uncertainty behind the word “verified.”",
  "04 / COMMON ERRORS",
  "Mistakes that make this topic less useful",
  "NEXT / PRODUCT RESEARCH",
  "Continue with a traceable product record",
  "Search the main database for a current product record, preserve the source URL and date, and keep official PikoBuy account actions separate from independent research.",
  "Browse the product database",
  "On this page",
  "Source boundary",
  "Practical method",
  "Decision rule",
  "Common errors",
  "Next step",
  "Editorial boundary",
  "This independent guide cannot inspect PikoBuy accounts, sellers, parcels, payments or refunds.",
  "Continue the research",
  "About",
  "Method",
  "Sources",
] as const;
