export const categories = [
  { slug: "shoes", name: "Shoes", icon: "01", note: "Sizing, sole details and packed-weight checks.", href: "https://findspreadsheet.com/shoes/" },
  { slug: "hoodies-sweaters", name: "Hoodies & Sweaters", icon: "02", note: "Fabric weight, measurements and seasonal layers.", href: "https://findspreadsheet.com/hoodies-sweaters/" },
  { slug: "t-shirts", name: "T-Shirts", icon: "03", note: "Print alignment, material notes and fit checks.", href: "https://findspreadsheet.com/t-shirts/" },
  { slug: "jackets", name: "Jackets", icon: "04", note: "Outerwear construction, volume and shipping weight.", href: "https://findspreadsheet.com/jackets/" },
  { slug: "pants-shorts", name: "Pants & Shorts", icon: "05", note: "Waist, inseam and fabric-reference checks.", href: "https://findspreadsheet.com/pants-shorts/" },
  { slug: "headwear", name: "Headwear", icon: "06", note: "Shape, circumference and packing protection.", href: "https://findspreadsheet.com/headwear/" },
  { slug: "accessories", name: "Accessories", icon: "07", note: "Dimensions, hardware and close-up photo checks.", href: "https://findspreadsheet.com/accessories/" },
  { slug: "jersey", name: "Jerseys", icon: "08", note: "Player print, badge placement and size guidance.", href: "https://findspreadsheet.com/jersey/" },
  { slug: "electronics", name: "Electronics", icon: "09", note: "Voltage, battery restrictions and compatibility.", href: "https://findspreadsheet.com/electronics/" },
  { slug: "other-stuff", name: "Other Finds", icon: "10", note: "Home, lifestyle and hard-to-classify discoveries.", href: "https://findspreadsheet.com/other-stuff/" },
];

export const products = [
  { name: "Gallery shorts", category: "Pants & Shorts", price: "$21.57", source: "¥145 source price", image: "/products/gallery-short.webp", href: "https://findspreadsheet.com/pants-shorts/gallery-short-3003.html" },
  { name: "Multi-style hoodie", category: "Hoodies", price: "$12.64", source: "¥85 source price", image: "/products/hoodie.webp", href: "https://findspreadsheet.com/hoodies-sweaters/dior-t-shirthoodie-39-style-top-3000.html" },
  { name: "Outdoor jacket", category: "Jackets", price: "$21.57", source: "¥145 source price", image: "/products/jacket.webp", href: "https://findspreadsheet.com/jackets/the-north-face-outdoorjacket-2998.html" },
  { name: "Mixed headwear find", category: "Headwear", price: "$7.44", source: "¥50 source price", image: "/products/headwear.webp", href: "https://findspreadsheet.com/headwear/prada-hatfendi-hatstone-island-hatbalenciaga-hatgucci-hat-2997.html" },
  { name: "Compact wallet", category: "Accessories", price: "$7.85", source: "¥52.8 source price", image: "/products/wallet.webp", href: "https://findspreadsheet.com/accessories/supreme-wallet-2995.html" },
];

export const markets = [
  { code: "US", name: "United States", language: "English", currency: "USD", priority: "Primary" },
  { code: "GB", name: "United Kingdom", language: "English", currency: "GBP", priority: "Primary" },
  { code: "DE", name: "Germany", language: "German", currency: "EUR", priority: "Primary" },
  { code: "FR", name: "France", language: "French", currency: "EUR", priority: "Primary" },
  { code: "ES", name: "Spain", language: "Spanish", currency: "EUR", priority: "Growth" },
  { code: "IT", name: "Italy", language: "Italian", currency: "EUR", priority: "Growth" },
  { code: "NL", name: "Netherlands", language: "Dutch", currency: "EUR", priority: "Growth" },
  { code: "PL", name: "Poland", language: "Polish", currency: "PLN", priority: "Growth" },
  { code: "CA", name: "Canada", language: "English / French", currency: "CAD", priority: "Growth" },
  { code: "AU", name: "Australia", language: "English", currency: "AUD", priority: "Growth" },
];

export const articles = [
  { slug:"how-to-use-lolobuy-spreadsheet", label:"BEGINNER GUIDE", date:"25 Aug 2026", read:"12–15 min read", title:"How to Use a LoloBuy Spreadsheet Without Treating Every Link as Verified", excerpt:"A practical, source-conscious workflow from product discovery to a live listing, warehouse evidence and an international parcel decision.", sections:[
    ["Treat the spreadsheet as an index, not a promise", "A useful spreadsheet shortens discovery; it does not certify the seller or the physical item. Begin with one category and compare a small group of genuinely similar products. Save the source URL, displayed price, chosen variation and the date you checked it. That simple record matters because marketplace listings can change after a directory card is published. A familiar product photo may later point to a different seller, a new variation set or an unavailable size. LoloBuy’s public workflow describes a service that helps users purchase from Chinese sales channels and receive goods at a China warehouse before global shipping. It does not turn a third-party listing into LoloBuy inventory. The seller still controls stock, description and domestic fulfilment. Your first job is therefore to identify a product worth investigating, not to assume that an attractive spreadsheet row has already completed the investigation for you."],
    ["Open the live source and rebuild the order in your own notes", "Before paying, compare the directory record with the live product page. Check the seller name, item title, colour, marked size, quantity, optional add-ons, domestic delivery charge and any seller-specific size chart. If the page is vague, capture the uncertainty instead of filling the gap with an assumption. LoloBuy’s purchasing guidance explains that shoppers can submit product links and that some purchases may require manual order information. Manual entry makes precision more important: a screenshot alone is not a reliable instruction, while a direct URL plus an exact variation and a short remark gives the purchasing agent something concrete to follow. Keep a screenshot of the final selection because it creates a time-stamped reference for the warehouse review. If the seller later changes the page, you can still compare the received record with what you intended to buy."],
    ["Understand what the first payment actually covers", "One of the easiest beginner mistakes is treating the product checkout as the complete delivered price. LoloBuy’s public help material separates the product purchase from the later international parcel. The first stage can include the item price and China-side delivery from the seller to the warehouse. International freight is calculated later, after goods arrive and you choose which stored items to submit. Read every line shown at checkout: product subtotal, domestic postage, currency conversion and any payment or service charge presented to your account. Do not rely on a payment method or fee quoted in an old video or another customer’s country, because availability can change by account, region and date. A spreadsheet can help you compare source prices, but a responsible budget also reserves money for warehouse services, packing choices, international freight and possible destination tax or duty."],
    ["Allow for the hand-off between seller and warehouse", "After purchase, the seller dispatches the item within China. Domestic tracking may show delivery before the product appears as a usable record in My Warehouse, because receipt, matching, opening, inspection and data entry are separate tasks. Watch the order status and platform messages rather than judging the process from one carrier scan. If the seller changes a price, variation or availability, answer the confirmation request clearly; silence can leave an order waiting. When the warehouse record appears, compare its identifier with your saved source and order details. This is the moment when an online listing becomes evidence about a particular physical item. The transition matters: your spreadsheet row described a buying lead, the order described what you requested, and the warehouse record now describes what arrived. Keeping those three records connected prevents a polished photo or familiar title from being mistaken for proof that the correct variation was received."],
    ["Read QC photos as limited evidence", "LoloBuy’s purchasing and inspection materials describe warehouse inspection and photos after arrival. That service is useful for visible questions such as style, quantity, colour, size label, model, obvious damage and noticeable defects. It is not a laboratory test or authentication certificate. Start with identity: is this the ordered model, colour, size and quantity? Then use a category-specific checklist. Apparel needs measurements, print placement, seams and visible marks. Footwear needs both shoes, size labels, heel shape and outsole views. Accessories need hardware, closures and included pieces. Electronics need model, plug and battery information, but a photograph usually cannot prove internal performance. If a required area is missing, decide whether an additional detail photo is worth requesting before the return window or parcel submission. The goal is to catch observable mismatches while the item is still in China, not to force certainty from images that cannot show hidden construction or long-term durability."],
    ["Make the keep-or-return decision before irreversible services", "Once the warehouse evidence is available, pause before consolidating. Decide whether the item is acceptable, needs more information or should be returned under the seller’s current conditions. LoloBuy has published value-added services that can remove original packaging or shoe boxes to reduce weight and volume. The same public notice warns that removing original packaging can affect return or exchange eligibility. That means packaging removal belongs after the quality and return decision, not before it. For a fragile item, the box may also be part of the protection. Record why you kept the product, what remained uncertain and whether you accepted a packing trade-off. This is more useful than a generic green “QC passed” label because the decision is tied to the actual evidence, your tolerance and the category. Another shopper could reasonably make a different choice from the same photos."],
    ["Build the international parcel as a separate project", "LoloBuy’s public homepage describes selecting products stored in the China warehouse and using global shipping. Treat parcel submission as a second planning stage. Confirm the destination address, choose only the accepted items, review their recorded weight and dimensions, and compare the live routes returned for that combination. The route list is parcel-specific: destination, size, weight and product category can all change eligibility or price. A large consolidated carton is not automatically better. It may reduce repeated opening charges, but it can also increase volumetric weight, cross a route limit or mix goods with different restrictions. Compare sensible parcel groupings and understand the displayed billing rule, protection terms, tracking level and restriction notes before paying. The international amount shown earlier in your research was an estimate; the packed measurements and live route screen are stronger evidence for the parcel you are actually sending."],
    ["Use a deliberately small first order", "The best first order is a controlled experiment, not a victory lap. Choose one or two products with readable listings, clear variations and measurements you understand. Save the source evidence, read the first payment, monitor seller dispatch, review the warehouse photos at full size, finish the keep-or-return decision and then test the shipping estimator with honest inputs. Keep screenshots of the final order, warehouse record, selected parcel services and tracking number. This slower approach teaches where the process changes hands: the seller controls the listing and China-side dispatch, LoloBuy facilitates purchasing and warehouse handling, the logistics provider carries the international parcel, and destination authorities make customs decisions. Most expensive errors come from collapsing those roles into one assumption. A spreadsheet is valuable precisely when it helps you ask the next question at the right stage, while leaving live prices, route terms and account rules to the current platform screens."],
  ]},
  { slug:"lolobuy-qc-photo-checklist", label:"QC RESEARCH", date:"25 Aug 2026", read:"12–15 min read", title:"LoloBuy QC Photo Checklist: What Warehouse Images Can—and Cannot—Show", excerpt:"A category-specific method for reading warehouse photos, separating visible evidence from assumptions and documenting a keep-or-return decision.", sections:[
    ["QC starts with identity, not perfection", "Warehouse quality control is most useful when it answers a narrow question: did the expected item arrive, and is there visible evidence that changes the decision? LoloBuy’s public purchasing guidance describes inspection and photos after goods reach the China warehouse. Its inspection material focuses on observable details such as style, quantity, colour, size, model, damage and obvious defects. Start there. Match the warehouse record to the order number and compare the received model, colour, marked size, quantity and visible options with the source evidence you saved. A sharp photograph of the wrong variation is still a failed identity check. Do not begin by hunting for microscopic flaws while ignoring a wrong colour or missing component. Identity is the foundation because every later measurement and appearance judgment is meaningless if the warehouse record is not the product you ordered."],
    ["Use the overview to understand the whole item", "Open every standard image at full size and establish the overall shape before zooming into details. Look for obvious asymmetry, crushing, stains, tears, missing pieces or packaging damage. Compare front, back and side views when available. The overview is also where you can notice whether a seller shipped a different edition, a wrong count or an unexpected accessory. Lighting and camera white balance can change colour, so compare several images rather than treating one frame as perfectly accurate. If the item appears substantially different from the listing, record the difference in plain language and mark the source image that shows what you expected. A useful support request says “the ordered variation was dark brown, while the warehouse record and size label show black,” not simply “colour looks wrong.” Specific observations are easier for an agent or seller to verify and respond to."],
    ["Apparel needs measurements and construction checks", "For T-shirts, hoodies, jackets and trousers, a size tag is only one piece of evidence. Compare any warehouse measurements with the seller’s chart and with clothing that already fits you. Prioritise the dimensions that determine usability: chest width and length for tops; shoulder and sleeve for structured outerwear; waist, rise and inseam for trousers. Then examine visible construction. Check whether prints are centred, panels align, zips sit straight, cuffs match and seams show obvious puckering or gaps. Fabric composition and weight can rarely be proven from a photo, so describe appearance without turning it into a material claim. A garment may photograph well and still fit poorly; another may show a small loose thread that does not affect use. Rank findings by consequence instead of treating every visual difference as equal."],
    ["Footwear and accessories require different evidence", "For shoes, confirm that both sides are present and match. Compare the marked size, general silhouette, toe shape, heel alignment, outsole pattern and visible glue or stitching. Ask for a label or insole measurement when the size evidence is unclear. A single glamour angle cannot show pair symmetry or outsole condition. Accessories need closer attention to the parts that move or carry load: zips, clasps, buckles, straps, hinges, wallet edges and included components. Count detachable pieces and compare hardware colour across images. With hats, check crown shape, brim alignment, circumference information and whether packing has distorted the structure. These checks do not authenticate a brand or prove long-term durability. They simply use the available warehouse record to identify visible mismatches before international shipping makes a return more complicated."],
    ["Electronics and sealed goods have stricter limits", "A photograph can confirm an electronics model label, plug type, visible ports, stated voltage, included cable and exterior condition. It usually cannot prove battery health, internal components, wireless compatibility or performance under use. Route eligibility can also depend on batteries and product classification, so a visually acceptable item can still create a shipping problem. Sealed products create another limitation: opening packaging for inspection may be impossible, undesirable or inconsistent with the seller’s return conditions. Treat unopened packaging as evidence of exterior condition only. If compatibility is essential, verify the exact model and specification against your destination before purchase and check the live route restrictions before parcel submission. Do not convert “no visible exterior defect” into “fully tested.” The wording of your decision should match the strength of the evidence."],
    ["Separate visible defects from unanswered questions", "Photos are strong evidence for some problems: the wrong item, missing quantity, a clear stain, a broken component, major asymmetry or an obvious measurement mismatch. They are weak evidence for authenticity, exact fabric composition, smell, long-term strength, waterproofing, internal electronics and future customs clearance. Keep two lists: confirmed observations and unresolved questions. This prevents uncertainty from being presented as either a defect or a guarantee. If a question could change your decision and can be answered visually, request a targeted image—for example, a ruler across the chest, a close-up of a clasp or a photograph of the model label. If the question cannot be answered at the warehouse, decide whether you can accept that risk. Honest QC is not the absence of uncertainty; it is knowing which uncertainty remains."],
    ["Finish returns before changing the packaging", "LoloBuy’s public value-added-services notice explains that packaging or shoe-box removal can reduce parcel size and weight. It also states that removing original packaging may make the product ineligible for return or exchange. This creates a clear order of operations. First, review the photos and measurements. Second, request any additional evidence. Third, decide whether to keep or return. Only then choose packaging removal, reinforcement or other parcel services. A shoe box may be expensive volume, but it can also protect shape. Retail packaging may be unimportant for a soft garment but useful for a fragile accessory. The cheapest packing option is not automatically the best; it is a trade-off between volume, protection and reversibility. Record the choice so the later shipping quote can be understood in context."],
    ["Create a decision record that survives delivery", "Save the source listing, chosen variation, order number, warehouse photos, measurements, questions and final acceptance or return decision together. Note the date because seller pages and platform rules can change. If you keep an item with a visible issue, state that you accepted it; if support confirms a detail, preserve the message. At delivery, photograph the parcel exterior before opening when it is damaged or resealed, and keep the tracking and parcel record until the order is complete. A decision trail helps distinguish a warehouse-visible issue from shipping damage or a later misunderstanding. It also improves future shortlists: you learn which seller descriptions were clear, which measurements mattered and which packing choices were worth the cost. QC becomes useful research when it changes a decision and leaves evidence—not when a directory places an unexplained badge next to a product. Use the same checklist across several orders, but do not force every category into identical standards. A two-millimetre print shift, a bent connector and a missing jacket belt have different consequences. Add a simple outcome field—accept, ask, return or accept with a noted limitation—and write the reason in one sentence. When the parcel arrives, compare the delivered item with the warehouse record and update the result. That feedback reveals whether your photo requests were useful and which uncertainties should be resolved before the next purchase. Over time, the record becomes a practical buying history rather than a collection of attractive images."],
  ]},
  { slug:"lolobuy-shipping-cost-guide", label:"SHIPPING GUIDE", date:"25 Aug 2026", read:"13–16 min read", title:"LoloBuy Shipping Cost Research: Weight, Volume, Routes and Consolidation", excerpt:"A practical way to estimate parcel cost using destination, real and volumetric weight, category restrictions, packing choices and the live route quote.", sections:[
    ["Product price is not landed cost", "A spreadsheet price answers only the first part of the budget. LoloBuy’s public workflow separates the product purchase from international parcel submission: goods travel from the seller to a China warehouse, the buyer selects stored items, and international freight is calculated for the later parcel. Build the budget in layers. Record the product price, China-side delivery, displayed payment or service charges, optional warehouse services, packing, international freight and any destination tax or duty separately. This prevents a cheap source item from looking like a cheap delivered item. It also makes comparisons fair: two products with similar prices may have very different packed size, route eligibility or protection needs. A static article cannot publish one permanent shipping rate for every buyer because the parcel and the destination determine the available options. The correct goal is a repeatable estimate whose assumptions can be checked."],
    ["Use the official estimator with honest inputs", "LoloBuy’s public freight-estimate page asks for destination, weight in grams, product categories and parcel length, width and height. Those fields reveal what matters before routes can be compared. Choose the real destination, enter the latest available warehouse weight, select truthful categories and include dimensions when you have a reasonable packing estimate. Early in the process, some inputs will be uncertain; note a range rather than inventing precision. Test a lighter compact scenario and a heavier or bulkier scenario, then save the inputs with the results. The estimator is planning evidence, not the final packed invoice. Once the warehouse combines the selected items and records the parcel, compare the new measurements with your assumptions. If the difference is large, look for a concrete explanation such as retained boxes, protective material, a previously missing weight or dimensional billing."],
    ["Read first weight and continued weight", "International routes may use billing blocks rather than one flat price per kilogram. LoloBuy’s estimate FAQ describes first weight as the opening billing amount up to a specified weight, with continued weight charged in later increments. This explains why adding or removing a small item does not always change the total: the parcel may remain inside the same block. It also explains why dividing one customer’s quote by kilograms and applying that number to your own haul can be misleading. Read the live route’s opening weight, continued increment, price, minimum and maximum. Compare complete quotes for the parcel you actually intend to send. If two routes are close in price, consider tracking, restrictions, estimated delivery range, protection and tax treatment rather than choosing from the headline number alone. Rates and route details can change, so the current account result is stronger evidence than an old screenshot."],
    ["Calculate volumetric weight before buying bulky goods", "A parcel can be light on a scale and still occupy expensive transport space. LoloBuy’s public estimator FAQ gives a common air-cargo volume calculation of length multiplied by width multiplied by height in centimetres, divided by 6,000 to produce kilograms. A carton measuring 40 × 30 × 20 cm has a volumetric result of 4 kg, even if the products weigh less. Treat the formula as a planning example, not a promise that every line uses the same divisor or billing rule. Shoe boxes, rigid presentation cases, puffer jackets and loose packing are common sources of extra volume. Estimate both scale and volume weight, then read how the live route defines chargeable weight. The practical lesson is simple: reducing empty space can matter as much as removing a few grams, but protection and return rights must be considered before packaging is altered."],
    ["Product category changes route eligibility", "The estimator asks for product category because contents affect more than weight. Batteries, electronics, liquids, pastes, food, medicine and other restricted goods can have narrower route choices or additional conditions. Select the closest truthful category instead of relabelling an item to make a cheaper option appear. When a route note is unclear, hold the parcel and ask official support before paying. A low quote is useless if the parcel does not meet the carrier or destination rules. Mixed parcels deserve extra attention because one restricted item can affect the options for ordinary clothing packed beside it. Test a sensible split when the categories have different requirements. This does not guarantee a lower total—two parcels may pay two opening charges—but it can create eligible, more understandable shipments. Destination customs rules remain separate from the agent’s route display and can change over time."],
    ["Consolidate because the numbers work, not by habit", "Combining several warehouse items can reduce repeated base charges and simplify tracking, but a larger carton is not automatically cheaper or safer. Consolidation can push the parcel into a higher weight block, create more volumetric weight, exceed a route ceiling or concentrate more value in one customs decision. Compare at least two reasonable groupings when the account allows it: for example, compact ordinary clothing together and a bulky or restricted item separately. Record the opening charge, continued weight, parcel dimensions, protection and route notes for each option. Splitting is valuable when it improves eligibility or manageability, not because it always saves money. Likewise, forcing every stored item into one carton simply because consolidation is available can be a costly habit. The best arrangement is the one supported by the live measurements and route terms for your destination."],
    ["Change packaging only after the return decision", "LoloBuy’s value-added-services announcement describes removing packaging or shoe boxes to reduce weight and volume, and says the warehouse updates the measurements after the service. The same notice warns that an item may no longer be returnable or exchangeable after its original packaging is removed. Finish the QC review first. Resolve wrong variations, visible defects and seller-return questions before requesting an irreversible service. Then balance volume savings against protection. A soft garment may need little original packaging, while a fragile electronic accessory or structured shoe may benefit from it. Reinforcement, corner protection and moisture barriers can add weight but reduce a different risk. Save the before-and-after warehouse measurements when available. That record shows whether the service materially improved the parcel instead of relying on the assumption that “no box” must always mean cheaper shipping."],
    ["Build an auditable quote before paying", "For every serious comparison, save the destination, date, currency, parcel weight, dimensions, product categories, route name, first and continued weight rules, restriction notes, selected services and quoted total. At submission, compare the packed figures with the estimate and keep the parcel number and final payment. After dispatch, preserve tracking until delivery is complete. This record lets you explain a cost difference instead of comparing isolated totals from different dates or countries. Before payment, confirm the recipient name, full address, phone number, truthful declaration, protection terms and the process for delay, loss or damage. Recheck the destination’s current import rules rather than copying another buyer’s declaration or tax experience. Keep a small contingency in the budget for measurement changes and destination-side charges. Use live account information as the final source because routes, rates and availability can change. A dependable shipping guide does not promise one cheapest line. It teaches a repeatable decision: estimate honestly, finish QC, choose packaging, compare eligible routes, verify packed measurements and pay only when the quote matches the parcel you intend to send."],
  ]},
];

export const pages = {
  categories: { eyebrow:"PRODUCT CATEGORIES", title:"Browse every category from one independent page.", intro:"Ten stable product groups keep discovery clear and connect each topic to its own research page and the matching FindSpreadsheet collection.", sections:[
    ["Why category pages matter", "Search intent differs by product type. Separate pages let footwear, apparel, accessories and electronics use the right listing, QC and shipping checks instead of repeating generic copy."],
    ["Two useful destinations", "Each category has an educational page on FindSpreadsheet Agent Guide and a clearly labelled path to the corresponding live FindSpreadsheet collection."],
  ]},
  "product-details": { eyebrow:"PRODUCT DETAILS", title:"Review product details before opening the order route.", intro:"This independent page brings together image, category, source-price reference, USD conversion and the matching FindSpreadsheet record for each featured find.", sections:[
    ["What the card confirms", "The card records what was visible when the source was checked: a product reference, category, image and price conversion. It does not promise current stock, seller performance or warehouse QC."],
    ["What to check next", "Open the matching detail record, review the source URL and then verify the live listing, selected variant, domestic delivery and current destination before submitting an order."],
  ]},
  "seo-articles": { eyebrow:"SEO ARTICLE CENTRE", title:"Original LoloBuy research organised by user intent.", intro:"Each article answers a different decision—product discovery, QC or shipping—using practical guidance, clear limits and source-aware language rather than repeated keyword filler.", sections:[
    ["Editorial standard", "Every article has a distinct target question, a real update date and a defined reader task. Facts and estimates are kept separate, and changing values are directed back to the live source."],
    ["Publishing sequence", "The first cluster covers how to use the spreadsheet, how to evaluate warehouse photos and how to calculate parcel cost. Country guides and platform updates follow without duplicating these core pages."],
  ]},
  products: { eyebrow: "DIRECTORY", title: "A product finder that leads somewhere useful.", intro: "Browse ten stable categories, review the source price and item page, then continue to the matching FindSpreadsheet record. Product availability, variants and seller terms can change, so every find remains a research lead—not a promise.", sections: [
    ["Start with category, not hype", "Shoes need sizing and sole checks. Jackets need measurements and packed weight. Electronics need voltage and battery-route checks. Treating every row the same is how a long spreadsheet becomes noisy."],
    ["What each record should show", "A useful record identifies the category, source price, current destination, image reference and last-check date. Before ordering, confirm the live listing, selected variant, domestic delivery charge and whether the item can use your intended international route."],
    ["Where the transaction happens", "FindSpreadsheet Agent Guide is an independent research layer. It does not take payment, operate a warehouse or ship parcels. Product discovery continues on FindSpreadsheet; any order workflow happens on the chosen shopping agent."],
  ]},
  guide: { eyebrow: "BEGINNER GUIDE", title: "From a product link to an international parcel.", intro: "LoloBuy publicly describes a shopping-agent workflow: products are purchased from Chinese channels, sent to a China warehouse, and selected warehouse items can be submitted together as a parcel for global shipping.", sections: [
    ["1. Find and re-check", "Use the directory to shortlist an item. Open the live record and check the current title, seller, variant, price and China-side shipping. A saved spreadsheet row may outlive the seller listing it references."],
    ["2. Submit the source link", "A shopping agent helps purchase from channels that may not offer a convenient overseas checkout. Keep the original product URL and order record together so later QC decisions refer to the correct variant."],
    ["3. Review warehouse evidence", "When the item reaches the warehouse, inspect the available photos and recorded details. Compare measurements, colour, construction and visible defects against the listing—not against an assumed retail standard."],
    ["4. Build the parcel", "Choose which stored items to combine. Final shipping depends on destination, route eligibility, actual or volumetric weight, packaging and current carrier rules. Re-check these values in the live account before payment."],
  ]},
  qc: { eyebrow: "QC CHECKLIST", title: "QC is a decision process, not a green badge.", intro: "A photo cannot prove everything about an item, but a disciplined checklist can reveal wrong variants, visible damage, measurement problems and missing parts before international shipping.", sections: [
    ["Identity check", "Match colour, size, model, quantity and visible options to the order record. Confirm that the photographed item is the one you selected."],
    ["Category-specific details", "For apparel, request or inspect measurement photos. For footwear, compare both shoes, outsole, heel and size tag. For bags and accessories, inspect hardware, stitching, closures and included pieces."],
    ["Shipping-readiness", "Look for damage, fragile parts, batteries, liquids or oversized packaging that may affect route eligibility. A good-looking item can still create a shipping problem."],
    ["What QC cannot prove", "Warehouse photos do not guarantee authenticity, long-term durability, exact material composition or customs clearance. Keep claims narrow and evidence-based."],
  ]},
  shipping: { eyebrow: "SHIPPING RESEARCH", title: "Estimate the parcel—not just the product price.", intro: "International cost is shaped by destination, route, chargeable weight, packaging and restrictions. The cheapest product can become the wrong choice when volume or route limits are ignored.", sections: [
    ["Actual vs volumetric weight", "Carriers may charge using the greater of scale weight and dimensional weight. Shoes, winter jackets and rigid packaging can cost more than their product weight suggests."],
    ["Consolidation", "Combining warehouse items may reduce repeated base charges, but it can also create a larger parcel or mix products with different route restrictions. Compare options before submission."],
    ["Country differences", "Customs thresholds, taxes, prohibited goods and carrier availability vary by destination and change over time. This site will publish country research pages, but the live route quote and current official rules control each shipment."],
    ["Before you pay", "Confirm destination, declared information, insurance terms, parcel photos, packaging options, route tracking and the process for delay or loss claims."],
  ]},
  updates: { eyebrow: "RESEARCH DESK", title: "Updates with a source and a reason.", intro: "The editorial plan prioritises changes that affect a real order: platform workflow, warehouse notices, payment changes, route availability, product-link health and destination rules.", sections: [
    ["Official-source updates", "Platform claims are checked against LoloBuy public pages or app listings. Each article should state when it was checked and separate confirmed facts from our interpretation."],
    ["Link-health reviews", "Product and category destinations should be tested on a schedule. A changed seller price or dead source link should update the record—not trigger a cosmetic 'fresh' date across the whole site."],
    ["Planned long-form series", "Beginner workflow, QC by category, parcel cost, tracking interpretation, US buying research, UK buying research and major EU destination guides form the first editorial cluster."],
  ]},
  faq: { eyebrow: "CLEAR ANSWERS", title: "Questions to settle before your first order.", intro: "Short answers are useful only when they make the limits clear. Live account information, seller listings and current destination rules override static guidance.", sections: [
    ["Is FindSpreadsheet Agent Guide the official LoloBuy website?", "No. It is an independent product-discovery and educational site created to help FindSpreadsheet users research a shopping-agent workflow."],
    ["Does this site sell, inspect or ship products?", "No. There is no checkout, warehouse or parcel service here. This site organises independent research and sends product discovery traffic to FindSpreadsheet. Any live order, warehouse or shipping decision must be made in the relevant account and current checkout."],
    ["Does a spreadsheet link guarantee stock, price or quality?", "No. A directory record shows what was visible when it was checked. Seller stock, variants, domestic delivery and price can change. A link cannot prove authenticity, seller performance, future availability or the condition of the physical item that may later reach a warehouse."],
    ["Why are product payment and international freight separate?", "LoloBuy’s published buying flow separates the item purchase and China-side delivery from the later international parcel. International freight is calculated after warehouse arrival, when the buyer selects stored goods and compares the routes available for the destination, weight, dimensions and categories."],
    ["What can warehouse QC photos confirm?", "They can help confirm visible identity details such as model, colour, marked size, quantity, obvious damage and noticeable defects. Photos usually cannot prove hidden construction, exact material composition, electronics performance, authenticity, durability or customs clearance."],
    ["How should I estimate LoloBuy shipping cost?", "Use the live freight estimator with the real destination, latest available weight, truthful product categories and reasonable dimensions. Compare actual and volumetric weight, then read the route’s first-weight, continued-weight, limit and restriction rules. An early estimate is planning evidence, not a permanent final price."],
    ["Is one consolidated parcel always cheaper?", "No. Consolidation may reduce repeated opening charges, but it can increase carton volume, cross a billing or route limit, mix restricted categories or concentrate more value in one shipment. Compare sensible parcel groupings using the live measurements and eligible routes."],
    ["Can removing packaging reduce cost?", "It can reduce weight or volume for bulky items. LoloBuy’s public value-added-services notice also warns that removing original packaging can affect return or exchange eligibility. Finish QC and the keep-or-return decision before requesting an irreversible packing service."],
    ["Which countries use LoloBuy?", "LoloBuy presents global shipping, but it does not publicly disclose a verified country-by-country user breakdown. The market table on this site shows editorial priorities for North America and Europe, not claimed platform usage statistics."],
    ["Are delivery time and customs clearance guaranteed?", "No. Route estimates, carrier tracking and warehouse photos do not guarantee a delivery date, tax outcome or customs clearance. Check the live route terms and current destination rules, declare goods truthfully, and keep order, parcel and delivery evidence until the shipment is complete."],
  ]},
  about: { eyebrow: "INDEPENDENT BY DESIGN", title: "A researched route from discovery to decision.", intro: "FindSpreadsheet Agent Guide is being developed as an independent companion to FindSpreadsheet for users researching product links, QC, warehouse handling and international parcel decisions.", sections: [
    ["Our role", "We organise discovery and explain the workflow. We do not represent LoloBuy, Chinese marketplaces, sellers, carriers or product brands."],
    ["Our evidence standard", "A claim should identify its source and check date. Estimates must be labelled. Missing public data stays missing—we do not turn assumptions into statistics."],
    ["Our commercial path", "Category and product links may send visitors to FindSpreadsheet. That relationship is disclosed so readers can judge the site with the right context."],
  ]},
} as const;
