export const supportedLanguages = [
  { code: "en", short: "EN", name: "English", markets: "US · UK · CA · AU" },
  { code: "de", short: "DE", name: "Deutsch", markets: "DE · AT · CH" },
  { code: "es", short: "ES", name: "Español", markets: "ES · LATAM" },
  { code: "fr", short: "FR", name: "Français", markets: "FR · BE · CA" },
  { code: "it", short: "IT", name: "Italiano", markets: "IT" },
  { code: "nl", short: "NL", name: "Nederlands", markets: "NL · BE" },
  { code: "pl", short: "PL", name: "Polski", markets: "PL" },
  { code: "pt", short: "PT", name: "Português", markets: "PT · BR" },
  { code: "cs", short: "CS", name: "Čeština", markets: "CZ" },
  { code: "ro", short: "RO", name: "Română", markets: "RO · MD" },
  { code: "hu", short: "HU", name: "Magyar", markets: "HU" },
  { code: "sv", short: "SV", name: "Svenska", markets: "SE" },
  { code: "da", short: "DA", name: "Dansk", markets: "DK" },
  { code: "no", short: "NO", name: "Norsk", markets: "NO" },
  { code: "fi", short: "FI", name: "Suomi", markets: "FI" },
  { code: "tr", short: "TR", name: "Türkçe", markets: "TR" },
  { code: "el", short: "EL", name: "Ελληνικά", markets: "GR · CY" },
  { code: "uk", short: "UK", name: "Українська", markets: "UA" },
  { code: "bg", short: "BG", name: "Български", markets: "BG" },
  { code: "ru", short: "RU", name: "Русский", markets: "EE · LV · LT · CIS" },
  { code: "ar", short: "AR", name: "العربية", markets: "MENA" },
  { code: "ja", short: "JA", name: "日本語", markets: "JP" },
  { code: "ko", short: "KO", name: "한국어", markets: "KR" },
  { code: "zh", short: "ZH", name: "简体中文", markets: "SG · MY · GLOBAL" },
] as const;

export type LanguageCode = (typeof supportedLanguages)[number]["code"];

export function normalizeLanguage(value?: string): LanguageCode {
  return supportedLanguages.some((item) => item.code === value) ? (value as LanguageCode) : "en";
}

export const uiText: Record<LanguageCode, {
  brandNote: string;
  finds: string;
  qc: string;
  guides: string;
  sources: string;
  articles: string;
  database: string;
  backHome: string;
  readFull: string;
  checked: string;
  disclaimer: string;
}> = {
  en: { brandNote: "Independent buyer research", finds: "Finds", qc: "QC method", guides: "Guides", sources: "Sources", articles: "SEO articles", database: "Open full database", backHome: "Home", readFull: "Read the full guide", checked: "Fact-checked 06 Aug 2026", disclaimer: "Independent informational site. We do not represent PikoBuy, process payments or guarantee third-party listings." },
  de: { brandNote: "Unabhängige Käuferrecherche", finds: "Funde", qc: "QC-Methode", guides: "Ratgeber", sources: "Quellen", articles: "SEO-Artikel", database: "Datenbank öffnen", backHome: "Start", readFull: "Vollständigen Ratgeber lesen", checked: "Geprüft am 06. Aug. 2026", disclaimer: "Unabhängige Informationsseite. Wir vertreten PikoBuy nicht, verarbeiten keine Zahlungen und garantieren keine Angebote Dritter." },
  es: { brandNote: "Investigación independiente", finds: "Hallazgos", qc: "Método QC", guides: "Guías", sources: "Fuentes", articles: "Artículos SEO", database: "Abrir la base", backHome: "Inicio", readFull: "Leer la guía completa", checked: "Verificado el 6 ago 2026", disclaimer: "Sitio informativo independiente. No representamos a PikoBuy, no procesamos pagos ni garantizamos anuncios de terceros." },
  fr: { brandNote: "Recherche d’achat indépendante", finds: "Trouvailles", qc: "Méthode QC", guides: "Guides", sources: "Sources", articles: "Articles SEO", database: "Ouvrir la base", backHome: "Accueil", readFull: "Lire le guide complet", checked: "Vérifié le 6 août 2026", disclaimer: "Site d’information indépendant. Nous ne représentons pas PikoBuy, ne traitons aucun paiement et ne garantissons aucune annonce tierce." },
  it: { brandNote: "Ricerca indipendente", finds: "Prodotti", qc: "Metodo QC", guides: "Guide", sources: "Fonti", articles: "Articoli SEO", database: "Apri il database", backHome: "Home", readFull: "Leggi la guida completa", checked: "Verificato il 6 ago 2026", disclaimer: "Sito informativo indipendente. Non rappresentiamo PikoBuy, non gestiamo pagamenti e non garantiamo inserzioni di terzi." },
  nl: { brandNote: "Onafhankelijk kooponderzoek", finds: "Vondsten", qc: "QC-methode", guides: "Gidsen", sources: "Bronnen", articles: "SEO-artikelen", database: "Open database", backHome: "Home", readFull: "Lees de volledige gids", checked: "Gecontroleerd 6 aug 2026", disclaimer: "Onafhankelijke informatiesite. Wij vertegenwoordigen PikoBuy niet, verwerken geen betalingen en garanderen geen aanbiedingen van derden." },
  pl: { brandNote: "Niezależne badania zakupowe", finds: "Znaleziska", qc: "Metoda QC", guides: "Poradniki", sources: "Źródła", articles: "Artykuły SEO", database: "Otwórz bazę", backHome: "Start", readFull: "Przeczytaj pełny poradnik", checked: "Sprawdzono 6 sie 2026", disclaimer: "Niezależna strona informacyjna. Nie reprezentujemy PikoBuy, nie obsługujemy płatności i nie gwarantujemy ofert stron trzecich." },
  pt: { brandNote: "Pesquisa independente", finds: "Descobertas", qc: "Método QC", guides: "Guias", sources: "Fontes", articles: "Artigos SEO", database: "Abrir a base", backHome: "Início", readFull: "Ler o guia completo", checked: "Verificado em 6 ago 2026", disclaimer: "Site informativo independente. Não representamos a PikoBuy, não processamos pagamentos nem garantimos anúncios de terceiros." },
  cs: { brandNote: "Nezávislý nákupní průzkum", finds: "Nálezy", qc: "Metoda QC", guides: "Průvodci", sources: "Zdroje", articles: "SEO články", database: "Otevřít databázi", backHome: "Domů", readFull: "Přečíst celý průvodce", checked: "Ověřeno 6. 8. 2026", disclaimer: "Nezávislý informační web. Nezastupujeme PikoBuy, nezpracováváme platby a neručíme za nabídky třetích stran." },
  ro: { brandNote: "Cercetare independentă pentru cumpărători", finds: "Produse", qc: "Metoda QC", guides: "Ghiduri", sources: "Surse", articles: "Articole SEO", database: "Deschide baza", backHome: "Acasă", readFull: "Citește ghidul complet", checked: "Verificat la 6 aug. 2026", disclaimer: "Site informativ independent. Nu reprezentăm PikoBuy, nu procesăm plăți și nu garantăm ofertele terților." },
  hu: { brandNote: "Független vásárlói kutatás", finds: "Találatok", qc: "QC-módszer", guides: "Útmutatók", sources: "Források", articles: "SEO-cikkek", database: "Adatbázis megnyitása", backHome: "Kezdőlap", readFull: "A teljes útmutató", checked: "Ellenőrizve: 2026. aug. 6.", disclaimer: "Független tájékoztató oldal. Nem képviseljük a PikoBuyt, nem kezelünk fizetéseket, és nem garantáljuk harmadik felek ajánlatait." },
  sv: { brandNote: "Oberoende köpresearch", finds: "Fynd", qc: "QC-metod", guides: "Guider", sources: "Källor", articles: "SEO-artiklar", database: "Öppna databasen", backHome: "Hem", readFull: "Läs hela guiden", checked: "Faktagranskad 6 aug 2026", disclaimer: "Oberoende informationssida. Vi representerar inte PikoBuy, hanterar inte betalningar och garanterar inte tredjepartsannonser." },
  da: { brandNote: "Uafhængig købsresearch", finds: "Fund", qc: "QC-metode", guides: "Guides", sources: "Kilder", articles: "SEO-artikler", database: "Åbn databasen", backHome: "Hjem", readFull: "Læs hele guiden", checked: "Faktatjekket 6. aug. 2026", disclaimer: "Uafhængig informationsside. Vi repræsenterer ikke PikoBuy, behandler ikke betalinger og garanterer ikke tredjepartstilbud." },
  no: { brandNote: "Uavhengig kjøpsresearch", finds: "Funn", qc: "QC-metode", guides: "Guider", sources: "Kilder", articles: "SEO-artikler", database: "Åpne databasen", backHome: "Hjem", readFull: "Les hele guiden", checked: "Faktasjekket 6. aug. 2026", disclaimer: "Uavhengig informasjonsside. Vi representerer ikke PikoBuy, behandler ikke betalinger og garanterer ikke tredjepartstilbud." },
  fi: { brandNote: "Riippumaton ostotutkimus", finds: "Löydöt", qc: "QC-menetelmä", guides: "Oppaat", sources: "Lähteet", articles: "SEO-artikkelit", database: "Avaa tietokanta", backHome: "Etusivu", readFull: "Lue koko opas", checked: "Tarkistettu 6.8.2026", disclaimer: "Riippumaton tietosivusto. Emme edusta PikoBuyta, käsittele maksuja tai takaa kolmansien osapuolten ilmoituksia." },
  tr: { brandNote: "Bağımsız alışveriş araştırması", finds: "Ürünler", qc: "QC yöntemi", guides: "Rehberler", sources: "Kaynaklar", articles: "SEO yazıları", database: "Veritabanını aç", backHome: "Ana sayfa", readFull: "Tam rehberi oku", checked: "6 Ağu 2026 tarihinde doğrulandı", disclaimer: "Bağımsız bilgilendirme sitesi. PikoBuy'u temsil etmeyiz, ödeme işlemi yapmayız ve üçüncü taraf ilanlarını garanti etmeyiz." },
  el: { brandNote: "Ανεξάρτητη έρευνα αγορών", finds: "Επιλογές", qc: "Μέθοδος QC", guides: "Οδηγοί", sources: "Πηγές", articles: "Άρθρα SEO", database: "Άνοιγμα βάσης", backHome: "Αρχική", readFull: "Διαβάστε τον πλήρη οδηγό", checked: "Επαληθεύτηκε 6 Αυγ 2026", disclaimer: "Ανεξάρτητος ενημερωτικός ιστότοπος. Δεν εκπροσωπούμε την PikoBuy, δεν επεξεργαζόμαστε πληρωμές και δεν εγγυόμαστε καταχωρίσεις τρίτων." },
  uk: { brandNote: "Незалежне дослідження покупок", finds: "Знахідки", qc: "Метод QC", guides: "Посібники", sources: "Джерела", articles: "SEO-статті", database: "Відкрити базу", backHome: "Головна", readFull: "Читати повний посібник", checked: "Перевірено 6 серп 2026", disclaimer: "Незалежний інформаційний сайт. Ми не представляємо PikoBuy, не обробляємо платежі та не гарантуємо пропозиції третіх сторін." },
  bg: { brandNote: "Независимо проучване за купувачи", finds: "Находки", qc: "QC метод", guides: "Ръководства", sources: "Източници", articles: "SEO статии", database: "Отвори базата", backHome: "Начало", readFull: "Прочети пълното ръководство", checked: "Проверено на 6 авг 2026", disclaimer: "Независим информационен сайт. Не представляваме PikoBuy, не обработваме плащания и не гарантираме оферти на трети страни." },
  ru: { brandNote: "Независимое исследование покупок", finds: "Находки", qc: "Метод QC", guides: "Руководства", sources: "Источники", articles: "SEO-статьи", database: "Открыть базу", backHome: "Главная", readFull: "Читать полное руководство", checked: "Проверено 6 авг 2026", disclaimer: "Независимый информационный сайт. Мы не представляем PikoBuy, не обрабатываем платежи и не гарантируем предложения третьих лиц." },
  ar: { brandNote: "بحث مستقل للمشترين", finds: "المنتجات", qc: "منهج الفحص", guides: "الأدلة", sources: "المصادر", articles: "مقالات SEO", database: "فتح قاعدة المنتجات", backHome: "الرئيسية", readFull: "اقرأ الدليل الكامل", checked: "تم التحقق في 6 أغسطس 2026", disclaimer: "موقع معلومات مستقل. لا نمثل PikoBuy ولا نعالج المدفوعات ولا نضمن قوائم الجهات الخارجية." },
  ja: { brandNote: "独立した購入リサーチ", finds: "商品候補", qc: "QC方法", guides: "ガイド", sources: "情報源", articles: "SEO記事", database: "商品データベース", backHome: "ホーム", readFull: "完全ガイドを読む", checked: "2026年8月6日確認", disclaimer: "独立した情報サイトです。PikoBuyを代表せず、決済を処理せず、第三者の商品情報を保証しません。" },
  ko: { brandNote: "독립 구매 리서치", finds: "상품 찾기", qc: "QC 방법", guides: "가이드", sources: "출처", articles: "SEO 기사", database: "상품 데이터베이스", backHome: "홈", readFull: "전체 가이드 읽기", checked: "2026년 8월 6일 확인", disclaimer: "독립 정보 사이트입니다. PikoBuy를 대표하지 않으며 결제를 처리하거나 제3자 상품 정보를 보증하지 않습니다." },
  zh: { brandNote: "独立买家研究", finds: "商品发现", qc: "质检方法", guides: "购买指南", sources: "资料来源", articles: "SEO文章", database: "打开商品库", backHome: "首页", readFull: "阅读完整指南", checked: "核查于2026年8月6日", disclaimer: "本站为独立信息网站，不代表PikoBuy，不处理付款，也不保证第三方商品信息。" },
};

export const homeText: Record<LanguageCode, {
  eyebrow: string;
  line1: string;
  line2: string;
  line3: string;
  intro: string;
  search: string;
  searchButton: string;
  categoryKicker: string;
  categoryTitle: string;
  categoryCopy: string;
  methodKicker: string;
  methodTitle: string;
  methodCopy: string;
  guideKicker: string;
  guideTitle: string;
  sourceTitle: string;
  sourceCopy: string;
}> = {
  en: { eyebrow: "Independent PikoBuy research", line1: "Find it.", line2: "Check it.", line3: "Then decide.", intro: "Search focused product categories, understand the evidence behind each find and use official platform information before you decide.", search: "Search shoes, jackets or electronics", searchButton: "Search the sheet", categoryKicker: "01 / PRODUCT INDEX", categoryTitle: "Choose the category before the product.", categoryCopy: "Different products leave different evidence. Start with what matters for that category.", methodKicker: "02 / THE METHOD", methodTitle: "A useful row answers three questions.", methodCopy: "The spreadsheet starts the investigation. It never replaces your own judgment.", guideKicker: "03 / BUYER GUIDES", guideTitle: "Useful before checkout.", sourceTitle: "Five days after warehousing.", sourceCopy: "PikoBuy’s published return policy currently describes five days (120 hours) for eligible requests after warehouse stock-in. Seller acceptance, item condition, domestic return shipping and service fees may still apply." },
  de: { eyebrow: "Unabhängige PikoBuy-Recherche", line1: "Finden.", line2: "Prüfen.", line3: "Dann entscheiden.", intro: "Durchsuche gezielte Kategorien, prüfe die Belege hinter jedem Fund und nutze offizielle Plattforminformationen vor deiner Entscheidung.", search: "Schuhe, Jacken oder Elektronik suchen", searchButton: "Tabelle durchsuchen", categoryKicker: "01 / PRODUKTINDEX", categoryTitle: "Erst die Kategorie, dann das Produkt.", categoryCopy: "Verschiedene Produkte liefern verschiedene Hinweise. Beginne mit den relevanten Prüfpunkten.", methodKicker: "02 / DIE METHODE", methodTitle: "Eine nützliche Zeile beantwortet drei Fragen.", methodCopy: "Die Tabelle startet die Recherche, ersetzt aber nie dein eigenes Urteil.", guideKicker: "03 / KÄUFERRATGEBER", guideTitle: "Nützlich vor dem Bezahlen.", sourceTitle: "Fünf Tage nach Einlagerung.", sourceCopy: "PikoBuys veröffentlichte Rückgaberichtlinie nennt derzeit fünf Tage (120 Stunden) für berechtigte Anträge nach der Einlagerung. Verkäuferzustimmung, Zustand, Rückversand und Gebühren können dennoch gelten." },
  es: { eyebrow: "Investigación independiente de PikoBuy", line1: "Encuéntralo.", line2: "Revísalo.", line3: "Luego decide.", intro: "Busca categorías concretas, entiende las pruebas de cada hallazgo y consulta la información oficial antes de decidir.", search: "Buscar zapatos, chaquetas o electrónica", searchButton: "Buscar en la hoja", categoryKicker: "01 / ÍNDICE", categoryTitle: "Elige la categoría antes del producto.", categoryCopy: "Cada producto deja pruebas distintas. Empieza por lo importante para su categoría.", methodKicker: "02 / EL MÉTODO", methodTitle: "Una fila útil responde tres preguntas.", methodCopy: "La hoja inicia la investigación; nunca sustituye tu criterio.", guideKicker: "03 / GUÍAS", guideTitle: "Útiles antes de pagar.", sourceTitle: "Cinco días desde el almacén.", sourceCopy: "La política publicada por PikoBuy describe cinco días (120 horas) para solicitudes elegibles tras el ingreso en almacén. También pueden aplicar aceptación del vendedor, estado, transporte interno y tarifas." },
  fr: { eyebrow: "Recherche PikoBuy indépendante", line1: "Trouvez.", line2: "Vérifiez.", line3: "Puis décidez.", intro: "Explorez des catégories ciblées, examinez les preuves derrière chaque trouvaille et consultez les informations officielles avant de décider.", search: "Chercher chaussures, vestes ou électronique", searchButton: "Rechercher", categoryKicker: "01 / INDEX PRODUITS", categoryTitle: "Choisissez la catégorie avant le produit.", categoryCopy: "Chaque produit laisse des indices différents. Commencez par les contrôles propres à sa catégorie.", methodKicker: "02 / LA MÉTHODE", methodTitle: "Une ligne utile répond à trois questions.", methodCopy: "Le tableur lance la recherche, sans remplacer votre jugement.", guideKicker: "03 / GUIDES D’ACHAT", guideTitle: "Utiles avant de payer.", sourceTitle: "Cinq jours après l’entrée en stock.", sourceCopy: "La politique publiée de PikoBuy indique actuellement cinq jours (120 heures) pour les demandes éligibles après l’entrée en entrepôt. L’accord du vendeur, l’état, le retour intérieur et les frais peuvent s’appliquer." },
  it: { eyebrow: "Ricerca PikoBuy indipendente", line1: "Trovalo.", line2: "Controllalo.", line3: "Poi decidi.", intro: "Cerca categorie mirate, valuta le prove dietro ogni proposta e consulta le informazioni ufficiali prima di decidere.", search: "Cerca scarpe, giacche o elettronica", searchButton: "Cerca nel foglio", categoryKicker: "01 / INDICE PRODOTTI", categoryTitle: "Scegli la categoria prima del prodotto.", categoryCopy: "Prodotti diversi lasciano prove diverse. Parti dai controlli importanti per la categoria.", methodKicker: "02 / IL METODO", methodTitle: "Una riga utile risponde a tre domande.", methodCopy: "Il foglio avvia la ricerca, ma non sostituisce il tuo giudizio.", guideKicker: "03 / GUIDE", guideTitle: "Utili prima del pagamento.", sourceTitle: "Cinque giorni dal magazzino.", sourceCopy: "La politica pubblicata da PikoBuy indica cinque giorni (120 ore) per le richieste idonee dopo l’ingresso in magazzino. Possono applicarsi approvazione del venditore, condizioni, spedizione interna e commissioni." },
  nl: { eyebrow: "Onafhankelijk PikoBuy-onderzoek", line1: "Vind het.", line2: "Controleer het.", line3: "Beslis daarna.", intro: "Doorzoek gerichte categorieën, begrijp het bewijs achter elke vondst en raadpleeg officiële platforminformatie voordat je beslist.", search: "Zoek schoenen, jassen of elektronica", searchButton: "Doorzoek de lijst", categoryKicker: "01 / PRODUCTINDEX", categoryTitle: "Kies eerst de categorie.", categoryCopy: "Elk product laat ander bewijs achter. Begin met de controles die bij de categorie horen.", methodKicker: "02 / DE METHODE", methodTitle: "Een nuttige rij beantwoordt drie vragen.", methodCopy: "De spreadsheet start het onderzoek, maar vervangt nooit je eigen oordeel.", guideKicker: "03 / KOOPGIDSEN", guideTitle: "Nuttig vóór het afrekenen.", sourceTitle: "Vijf dagen na opslag.", sourceCopy: "Het gepubliceerde retourbeleid van PikoBuy noemt vijf dagen (120 uur) voor in aanmerking komende aanvragen na opslag. Goedkeuring, staat, binnenlandse retourkosten en servicekosten kunnen gelden." },
  pl: { eyebrow: "Niezależne badania PikoBuy", line1: "Znajdź.", line2: "Sprawdź.", line3: "Potem zdecyduj.", intro: "Przeglądaj konkretne kategorie, oceniaj dowody przy każdym znalezisku i sprawdzaj oficjalne informacje przed decyzją.", search: "Szukaj butów, kurtek lub elektroniki", searchButton: "Przeszukaj arkusz", categoryKicker: "01 / INDEKS", categoryTitle: "Najpierw wybierz kategorię.", categoryCopy: "Różne produkty wymagają różnych dowodów. Zacznij od punktów ważnych dla kategorii.", methodKicker: "02 / METODA", methodTitle: "Przydatny wiersz odpowiada na trzy pytania.", methodCopy: "Arkusz rozpoczyna badanie, ale nie zastępuje własnej oceny.", guideKicker: "03 / PORADNIKI", guideTitle: "Przydatne przed płatnością.", sourceTitle: "Pięć dni od magazynowania.", sourceCopy: "Opublikowana polityka PikoBuy wskazuje pięć dni (120 godzin) na kwalifikujące się wnioski po przyjęciu do magazynu. Mogą obowiązywać zgoda sprzedawcy, stan produktu, przesyłka krajowa i opłaty." },
  pt: { eyebrow: "Pesquisa independente sobre PikoBuy", line1: "Encontre.", line2: "Verifique.", line3: "Depois decida.", intro: "Pesquise categorias específicas, entenda as evidências de cada item e consulte informações oficiais antes de decidir.", search: "Buscar calçados, casacos ou eletrônicos", searchButton: "Pesquisar na planilha", categoryKicker: "01 / ÍNDICE", categoryTitle: "Escolha a categoria antes do produto.", categoryCopy: "Produtos diferentes deixam evidências diferentes. Comece pelos pontos relevantes à categoria.", methodKicker: "02 / O MÉTODO", methodTitle: "Uma linha útil responde a três perguntas.", methodCopy: "A planilha inicia a pesquisa, mas não substitui seu julgamento.", guideKicker: "03 / GUIAS", guideTitle: "Úteis antes do pagamento.", sourceTitle: "Cinco dias após o armazenamento.", sourceCopy: "A política publicada da PikoBuy descreve cinco dias (120 horas) para solicitações elegíveis após a entrada no armazém. Aceitação do vendedor, estado, devolução doméstica e taxas ainda podem se aplicar." },
  cs: { eyebrow: "Nezávislý průzkum PikoBuy", line1: "Najděte.", line2: "Ověřte.", line3: "Pak se rozhodněte.", intro: "Procházejte cílené kategorie, ověřujte podklady u každého nálezu a před rozhodnutím použijte oficiální informace platformy.", search: "Hledat boty, bundy nebo elektroniku", searchButton: "Prohledat tabulku", categoryKicker: "01 / INDEX PRODUKTŮ", categoryTitle: "Nejprve kategorie, potom produkt.", categoryCopy: "Různé produkty vyžadují různé důkazy. Začněte kontrolami důležitými pro danou kategorii.", methodKicker: "02 / METODA", methodTitle: "Užitečný řádek odpovídá na tři otázky.", methodCopy: "Tabulka zahajuje průzkum, ale nikdy nenahrazuje vlastní úsudek.", guideKicker: "03 / PRŮVODCI", guideTitle: "Užitečné před zaplacením.", sourceTitle: "Pět dní od naskladnění.", sourceCopy: "Zveřejněné zásady PikoBuy uvádějí pět dní (120 hodin) pro způsobilé žádosti po naskladnění. Stále může být nutný souhlas prodejce a mohou platit podmínky, vnitrostátní doprava a poplatky." },
  ro: { eyebrow: "Cercetare PikoBuy independentă", line1: "Găsește.", line2: "Verifică.", line3: "Apoi decide.", intro: "Caută în categorii clare, înțelege dovezile din spatele fiecărui produs și consultă informațiile oficiale înainte de a decide.", search: "Caută pantofi, jachete sau electronice", searchButton: "Caută în tabel", categoryKicker: "01 / INDEX PRODUSE", categoryTitle: "Alege categoria înaintea produsului.", categoryCopy: "Produse diferite lasă dovezi diferite. Începe cu verificările relevante pentru categorie.", methodKicker: "02 / METODA", methodTitle: "Un rând util răspunde la trei întrebări.", methodCopy: "Tabelul pornește cercetarea, dar nu înlocuiește propria judecată.", guideKicker: "03 / GHIDURI", guideTitle: "Utile înainte de plată.", sourceTitle: "Cinci zile de la intrarea în depozit.", sourceCopy: "Politica publicată de PikoBuy descrie cinci zile (120 de ore) pentru cererile eligibile după intrarea în depozit. Acceptul vânzătorului, starea produsului, returul intern și taxele se pot aplica în continuare." },
  hu: { eyebrow: "Független PikoBuy-kutatás", line1: "Találd meg.", line2: "Ellenőrizd.", line3: "Aztán dönts.", intro: "Keress célzott kategóriákban, értsd meg az egyes találatok mögötti bizonyítékokat, és döntés előtt ellenőrizd a hivatalos információkat.", search: "Cipő, kabát vagy elektronika keresése", searchButton: "Keresés a táblában", categoryKicker: "01 / TERMÉKINDEX", categoryTitle: "Előbb a kategória, aztán a termék.", categoryCopy: "A különböző termékekhez más bizonyíték kell. Kezdd a kategória fontos ellenőrzéseivel.", methodKicker: "02 / A MÓDSZER", methodTitle: "Egy hasznos sor három kérdésre válaszol.", methodCopy: "A táblázat elindítja a kutatást, de nem helyettesíti a saját mérlegelést.", guideKicker: "03 / VÁSÁRLÁSI ÚTMUTATÓK", guideTitle: "Hasznos fizetés előtt.", sourceTitle: "Öt nap a raktárba érkezéstől.", sourceCopy: "A PikoBuy közzétett visszaküldési szabályzata öt napot (120 órát) ír le a jogosult kérelmekre a raktári bevételezés után. Az eladó jóváhagyása, az állapot, a belföldi visszaküldés és díjak továbbra is számíthatnak." },
  sv: { eyebrow: "Oberoende PikoBuy-research", line1: "Hitta.", line2: "Kontrollera.", line3: "Bestäm sedan.", intro: "Sök i tydliga kategorier, förstå underlaget bakom varje fynd och kontrollera officiell plattformsinformation innan du bestämmer dig.", search: "Sök skor, jackor eller elektronik", searchButton: "Sök i listan", categoryKicker: "01 / PRODUKTINDEX", categoryTitle: "Välj kategori före produkt.", categoryCopy: "Olika produkter lämnar olika bevis. Börja med kontrollerna som är viktiga för kategorin.", methodKicker: "02 / METODEN", methodTitle: "En användbar rad svarar på tre frågor.", methodCopy: "Kalkylbladet inleder undersökningen men ersätter aldrig ditt eget omdöme.", guideKicker: "03 / KÖPGUIDER", guideTitle: "Användbara före betalning.", sourceTitle: "Fem dagar efter lagerincheckning.", sourceCopy: "PikoBuys publicerade returpolicy beskriver fem dagar (120 timmar) för berättigade förfrågningar efter lagerincheckning. Säljarens godkännande, varans skick, inrikes returfrakt och avgifter kan fortfarande gälla." },
  da: { eyebrow: "Uafhængig PikoBuy-research", line1: "Find det.", line2: "Kontrollér det.", line3: "Beslut derefter.", intro: "Søg i fokuserede kategorier, forstå dokumentationen bag hvert fund, og brug officielle platformoplysninger før din beslutning.", search: "Søg efter sko, jakker eller elektronik", searchButton: "Søg i arket", categoryKicker: "01 / PRODUKTINDEKS", categoryTitle: "Vælg kategori før produkt.", categoryCopy: "Forskellige produkter kræver forskellig dokumentation. Start med kategoriens vigtigste kontroller.", methodKicker: "02 / METODEN", methodTitle: "En nyttig række besvarer tre spørgsmål.", methodCopy: "Regnearket starter undersøgelsen, men erstatter aldrig din egen vurdering.", guideKicker: "03 / KØBSGUIDER", guideTitle: "Nyttige før betaling.", sourceTitle: "Fem dage efter lagerregistrering.", sourceCopy: "PikoBuys offentliggjorte returpolitik beskriver fem dage (120 timer) for berettigede anmodninger efter lagerregistrering. Sælgeraccept, stand, indenrigs returfragt og gebyrer kan stadig gælde." },
  no: { eyebrow: "Uavhengig PikoBuy-research", line1: "Finn det.", line2: "Kontroller det.", line3: "Bestem deg så.", intro: "Søk i tydelige kategorier, forstå dokumentasjonen bak hvert funn, og bruk offisiell plattforminformasjon før du bestemmer deg.", search: "Søk etter sko, jakker eller elektronikk", searchButton: "Søk i arket", categoryKicker: "01 / PRODUKTINDEKS", categoryTitle: "Velg kategori før produkt.", categoryCopy: "Ulike produkter krever ulik dokumentasjon. Start med kontrollene som er viktige for kategorien.", methodKicker: "02 / METODEN", methodTitle: "En nyttig rad svarer på tre spørsmål.", methodCopy: "Regnearket starter undersøkelsen, men erstatter aldri din egen vurdering.", guideKicker: "03 / KJØPSGUIDER", guideTitle: "Nyttige før betaling.", sourceTitle: "Fem dager etter lagerregistrering.", sourceCopy: "PikoBuys publiserte returregler beskriver fem dager (120 timer) for kvalifiserte forespørsler etter lagerregistrering. Selgergodkjenning, varetilstand, innenlands returfrakt og gebyrer kan fortsatt gjelde." },
  fi: { eyebrow: "Riippumaton PikoBuy-tutkimus", line1: "Löydä.", line2: "Tarkista.", line3: "Päätä sitten.", intro: "Hae rajatuista tuoteryhmistä, ymmärrä jokaisen löydön taustalla oleva näyttö ja tarkista viralliset alustatiedot ennen päätöstä.", search: "Hae kenkiä, takkeja tai elektroniikkaa", searchButton: "Hae taulukosta", categoryKicker: "01 / TUOTEHAKEMISTO", categoryTitle: "Valitse kategoria ennen tuotetta.", categoryCopy: "Eri tuotteet vaativat erilaista näyttöä. Aloita kategorian tärkeistä tarkistuksista.", methodKicker: "02 / MENETELMÄ", methodTitle: "Hyödyllinen rivi vastaa kolmeen kysymykseen.", methodCopy: "Taulukko aloittaa selvityksen, mutta ei korvaa omaa harkintaa.", guideKicker: "03 / OSTO-OPPAAT", guideTitle: "Hyödyllisiä ennen maksua.", sourceTitle: "Viisi päivää varastoon kirjauksesta.", sourceCopy: "PikoBuyn julkaistu palautuskäytäntö kuvaa viiden päivän (120 tunnin) ajanjakson hyväksyttäville pyynnöille varastoon kirjauksen jälkeen. Myyjän hyväksyntä, tuotteen kunto, kotimaan palautus ja maksut voivat silti vaikuttaa." },
  tr: { eyebrow: "Bağımsız PikoBuy araştırması", line1: "Bul.", line2: "Kontrol et.", line3: "Sonra karar ver.", intro: "Odaklı kategorilerde ara, her ürünün arkasındaki kanıtı değerlendir ve karar vermeden önce resmi platform bilgilerini kontrol et.", search: "Ayakkabı, ceket veya elektronik ara", searchButton: "Listede ara", categoryKicker: "01 / ÜRÜN DİZİNİ", categoryTitle: "Üründen önce kategoriyi seç.", categoryCopy: "Farklı ürünler farklı kanıtlar bırakır. Kategori için önemli kontrollerle başla.", methodKicker: "02 / YÖNTEM", methodTitle: "Yararlı bir satır üç soruyu yanıtlar.", methodCopy: "Tablo araştırmayı başlatır, ancak kendi kararının yerini tutmaz.", guideKicker: "03 / ALIŞVERİŞ REHBERLERİ", guideTitle: "Ödeme öncesinde yararlı.", sourceTitle: "Depoya girişten sonra beş gün.", sourceCopy: "PikoBuy'un yayımlanan iade politikası, depoya girişten sonra uygun talepler için beş gün (120 saat) tanımlar. Satıcı onayı, ürün durumu, yurt içi iade kargosu ve ücretler yine de geçerli olabilir." },
  el: { eyebrow: "Ανεξάρτητη έρευνα PikoBuy", line1: "Βρείτε το.", line2: "Ελέγξτε το.", line3: "Μετά αποφασίστε.", intro: "Αναζητήστε σε στοχευμένες κατηγορίες, εξετάστε τα στοιχεία κάθε επιλογής και συμβουλευτείτε τις επίσημες πληροφορίες πριν αποφασίσετε.", search: "Αναζήτηση παπουτσιών, μπουφάν ή ηλεκτρονικών", searchButton: "Αναζήτηση", categoryKicker: "01 / ΕΥΡΕΤΗΡΙΟ ΠΡΟΪΟΝΤΩΝ", categoryTitle: "Επιλέξτε κατηγορία πριν από το προϊόν.", categoryCopy: "Κάθε κατηγορία απαιτεί διαφορετικά στοιχεία. Ξεκινήστε από τους ελέγχους που έχουν σημασία.", methodKicker: "02 / Η ΜΕΘΟΔΟΣ", methodTitle: "Μια χρήσιμη εγγραφή απαντά σε τρεις ερωτήσεις.", methodCopy: "Το φύλλο ξεκινά την έρευνα, αλλά δεν αντικαθιστά τη δική σας κρίση.", guideKicker: "03 / ΟΔΗΓΟΙ ΑΓΟΡΑΣ", guideTitle: "Χρήσιμοι πριν από την πληρωμή.", sourceTitle: "Πέντε ημέρες μετά την αποθήκευση.", sourceCopy: "Η δημοσιευμένη πολιτική επιστροφών της PikoBuy περιγράφει πέντε ημέρες (120 ώρες) για επιλέξιμα αιτήματα μετά την είσοδο στην αποθήκη. Ενδέχεται να ισχύουν έγκριση πωλητή, κατάσταση προϊόντος, εγχώρια επιστροφή και χρεώσεις." },
  uk: { eyebrow: "Незалежне дослідження PikoBuy", line1: "Знайдіть.", line2: "Перевірте.", line3: "Потім вирішуйте.", intro: "Шукайте у відповідних категоріях, перевіряйте докази для кожного товару та використовуйте офіційну інформацію перед рішенням.", search: "Пошук взуття, курток або електроніки", searchButton: "Шукати", categoryKicker: "01 / КАТАЛОГ ТОВАРІВ", categoryTitle: "Спочатку категорія, потім товар.", categoryCopy: "Різні товари потребують різних доказів. Почніть із перевірок, важливих для категорії.", methodKicker: "02 / МЕТОД", methodTitle: "Корисний рядок відповідає на три запитання.", methodCopy: "Таблиця починає дослідження, але не замінює вашого рішення.", guideKicker: "03 / ПОСІБНИКИ ПОКУПЦЯ", guideTitle: "Корисні до оплати.", sourceTitle: "П’ять днів після надходження на склад.", sourceCopy: "Опублікована політика PikoBuy описує п’ять днів (120 годин) для відповідних запитів після надходження на склад. Можуть діяти згода продавця, вимоги до стану, внутрішня доставка та збори." },
  bg: { eyebrow: "Независимо проучване на PikoBuy", line1: "Намерете.", line2: "Проверете.", line3: "После решете.", intro: "Търсете в конкретни категории, проверявайте доказателствата за всеки продукт и използвайте официалната информация преди решение.", search: "Търсене на обувки, якета или електроника", searchButton: "Търси", categoryKicker: "01 / ПРОДУКТОВ ИНДЕКС", categoryTitle: "Първо изберете категорията.", categoryCopy: "Различните продукти изискват различни проверки. Започнете с важните за категорията.", methodKicker: "02 / МЕТОДЪТ", methodTitle: "Полезният ред отговаря на три въпроса.", methodCopy: "Таблицата поставя начало на проучването, но не заменя собствената ви преценка.", guideKicker: "03 / РЪКОВОДСТВА ЗА КУПУВАЧИ", guideTitle: "Полезни преди плащане.", sourceTitle: "Пет дни след приемане в склада.", sourceCopy: "Публикуваната политика на PikoBuy описва пет дни (120 часа) за допустими заявки след приемане в склада. Одобрението на продавача, състоянието, вътрешното връщане и таксите може да продължат да важат." },
  ru: { eyebrow: "Независимое исследование PikoBuy", line1: "Найдите.", line2: "Проверьте.", line3: "Затем решайте.", intro: "Ищите по подходящим категориям, проверяйте данные по каждому товару и сверяйтесь с официальной информацией перед решением.", search: "Поиск обуви, курток или электроники", searchButton: "Искать", categoryKicker: "01 / КАТАЛОГ ТОВАРОВ", categoryTitle: "Сначала выберите категорию.", categoryCopy: "Разным товарам нужны разные проверки. Начните с того, что важно для этой категории.", methodKicker: "02 / МЕТОД", methodTitle: "Полезная строка отвечает на три вопроса.", methodCopy: "Таблица начинает исследование, но не заменяет ваше решение.", guideKicker: "03 / РУКОВОДСТВА ПОКУПАТЕЛЯ", guideTitle: "Полезно до оплаты.", sourceTitle: "Пять дней после поступления на склад.", sourceCopy: "Опубликованная политика PikoBuy описывает пять дней (120 часов) для допустимых запросов после поступления на склад. Могут применяться согласие продавца, требования к состоянию, внутренняя доставка и сборы." },
  ar: { eyebrow: "بحث مستقل حول PikoBuy", line1: "ابحث.", line2: "تحقق.", line3: "ثم قرر.", intro: "ابحث ضمن فئات محددة، وافحص الأدلة المتاحة لكل منتج، وراجع المعلومات الرسمية قبل اتخاذ القرار.", search: "ابحث عن أحذية أو سترات أو إلكترونيات", searchButton: "بحث", categoryKicker: "01 / فهرس المنتجات", categoryTitle: "اختر الفئة قبل المنتج.", categoryCopy: "تحتاج المنتجات المختلفة إلى أدلة مختلفة. ابدأ بالفحوص المهمة لكل فئة.", methodKicker: "02 / المنهج", methodTitle: "السجل المفيد يجيب عن ثلاثة أسئلة.", methodCopy: "تبدأ القائمة عملية البحث لكنها لا تستبدل حكمك الشخصي.", guideKicker: "03 / أدلة المشتري", guideTitle: "مفيدة قبل الدفع.", sourceTitle: "خمسة أيام بعد دخول المستودع.", sourceCopy: "تصف سياسة الإرجاع المنشورة لدى PikoBuy فترة خمسة أيام (120 ساعة) للطلبات المؤهلة بعد دخول المستودع. وقد تظل موافقة البائع وحالة المنتج والشحن المحلي والرسوم سارية." },
  ja: { eyebrow: "独立したPikoBuyリサーチ", line1: "見つける。", line2: "確認する。", line3: "それから決める。", intro: "商品カテゴリーから探し、各候補の根拠を確認し、決定前に公式情報を参照してください。", search: "靴、ジャケット、電子機器を検索", searchButton: "検索", categoryKicker: "01 / 商品インデックス", categoryTitle: "商品より先にカテゴリーを選ぶ。", categoryCopy: "商品によって確認すべき証拠は異なります。カテゴリー固有の確認点から始めてください。", methodKicker: "02 / 確認方法", methodTitle: "役立つ商品行は3つの質問に答えます。", methodCopy: "スプレッドシートは調査の出発点であり、購入者自身の判断に代わるものではありません。", guideKicker: "03 / 購入ガイド", guideTitle: "支払い前に役立つ情報。", sourceTitle: "倉庫入庫後5日間。", sourceCopy: "PikoBuyの公開返品ポリシーでは、対象となる申請は倉庫入庫後5日間（120時間）と説明されています。販売者の承認、商品状態、中国国内の返送費用、手数料が適用される場合があります。" },
  ko: { eyebrow: "독립 PikoBuy 리서치", line1: "찾고.", line2: "확인하고.", line3: "그다음 결정하세요.", intro: "상품 카테고리에서 검색하고 각 상품의 근거를 확인한 뒤 결정 전에 공식 정보를 검토하세요.", search: "신발, 재킷 또는 전자제품 검색", searchButton: "검색", categoryKicker: "01 / 상품 인덱스", categoryTitle: "상품보다 카테고리를 먼저 선택하세요.", categoryCopy: "상품마다 필요한 증거가 다릅니다. 해당 카테고리의 핵심 확인 항목부터 살펴보세요.", methodKicker: "02 / 확인 방법", methodTitle: "유용한 상품 행은 세 가지 질문에 답합니다.", methodCopy: "스프레드시트는 조사의 시작점일 뿐 구매자의 판단을 대신하지 않습니다.", guideKicker: "03 / 구매자 가이드", guideTitle: "결제 전에 확인하세요.", sourceTitle: "창고 입고 후 5일.", sourceCopy: "PikoBuy가 공개한 반품 정책은 창고 입고 후 적격 요청에 대해 5일(120시간)을 설명합니다. 판매자 승인, 상품 상태, 중국 내 반품 배송 및 수수료가 적용될 수 있습니다." },
  zh: { eyebrow: "独立PikoBuy购物研究", line1: "先找到。", line2: "再核对。", line3: "然后决定。", intro: "按商品类别查找，核对每个商品背后的证据，并在决定前查看平台公开信息。", search: "搜索鞋类、夹克或电子产品", searchButton: "搜索商品", categoryKicker: "01 / 商品分类", categoryTitle: "先选择类别，再选择商品。", categoryCopy: "不同商品需要不同的核对证据，请从该类别最重要的检查点开始。", methodKicker: "02 / 核对方法", methodTitle: "有用的商品条目应回答三个问题。", methodCopy: "表格只是调查的起点，不能代替你自己的判断。", guideKicker: "03 / 购买指南", guideTitle: "付款前值得查看。", sourceTitle: "入库后五天。", sourceCopy: "PikoBuy公开退货政策目前说明，符合条件的申请可在商品入库后五天（120小时）内提交；是否接受仍可能取决于卖家同意、商品状态、境内退货运费及相关费用。" },
};
