/*
 * These paragraphs retain the factual detail carried by the English source
 * article.  They are deliberately separate from the short opening copy in
 * seo-translations.ts so a locale cannot silently degrade into a summary.
 */
export const seoTranslationCoverage: Record<string, string[]> = {
  de: [
    "PikoBuy verbindet Käufer, Marktplatzverkäufer, das chinesische Lager und einen internationalen Transporteur. Deshalb sollte kein Schritt als Leistung des ursprünglichen Verkäufers oder als Zusage des Transporteurs ausgegeben werden: Der Verkäufer verantwortet Ware und Inlandssendung, PikoBuy Einkauf, Lager und Paketaufgabe, der externe Dienstleister den Auslandsweg.",
    "Nutze das Spreadsheet nur zum Aufbau einer kleinen Auswahlliste und gleiche jedes Ergebnis erneut mit dem Live-Angebot ab. Weder ein gespeichertes Bild noch ein Preis hält Bestand, Größenoptionen oder Rückgabebedingungen fest; eine Anzeige kann nach dem Speichern geändert oder entfernt werden.",
    "Vor der ersten Zahlung müssen die aktuelle Verkäuferpreisangabe, Inlandslieferung und Lagerbestand geprüft werden. Zusätzliche Dienste und Preisänderungen können den Betrag bis zum Lager verändern; der internationale Versand wird erst später bezahlt und hängt zusätzlich von Gewicht, Volumen und möglichen Beschränkungen ab.",
    "Lagerfotos sind ein Kontrollpunkt, keine umfassende Prüfung. Sie helfen, sichtbare Identität und Zustand zu vergleichen, beweisen aber weder Echtheit noch Faseranteil, langfristige Haltbarkeit, Batteriezustand oder Bildschirmfarbe und sagen nichts Verlässliches über eine Zollentscheidung aus.",
    "Auch eine scheinbar kostenlose erste Verkäuferlieferung kann bei einer bedingungslosen Rückgabe Kosten verursachen. Bei falscher Größe, falscher Farbe oder bestätigtem Mangel kann die Verantwortung anders liegen; bei selbst ins Lager weitergeleiteten Waren ersetzt das jedoch nicht den Kontakt mit Absender oder Verkäufer.",
    "Vergleiche bei der Paketaufgabe das gepackte Gewicht und alle drei Maße sowie verfügbare Routen, Versicherung und Warenwert. Die Zusammenfassung mehrerer Verkäuferartikel kann Grundkosten sparen, ist bei einem größeren Paket aber nicht automatisch günstiger; Batterien, Flüssigkeiten und ähnliche Waren können Routen ausschließen.",
    "Tracking innerhalb von drei Tagen nach der Aufgabe bedeutet nur, dass eine Sendungsnummer oder Aktualisierung bereitstehen kann. Internationale Drittanbieter, Zollmaßnahmen, Beschlagnahmung, Schäden, Verlust und Verzögerungen in der Hochsaison bleiben mögliche Risiken; eine zollfreie oder termingenaue Lieferung kann nicht versprochen werden."
  ],
  fr: [
    "PikoBuy relie l’acheteur, le vendeur de marketplace, l’entrepôt chinois et un transporteur international. Il faut donc distinguer les responsabilités : le vendeur gère l’article et l’envoi domestique, PikoBuy l’achat, l’entrepôt et la soumission du colis, puis un prestataire tiers effectue le transport international.",
    "Utilisez le spreadsheet pour créer une courte sélection, puis comparez chaque résultat avec l’annonce en direct. Une image enregistrée ou un prix indiqué ne bloque ni le stock, ni les options de taille, ni les conditions de retour : le vendeur peut modifier ou retirer une annonce après son enregistrement.",
    "Avant le premier paiement, vérifiez le prix actuel du vendeur, la livraison nationale et le stock. Des services facultatifs ou un changement de prix peuvent modifier le montant avant l’entrepôt ; l’expédition internationale est payée ensuite et dépend aussi du poids, du volume et des restrictions éventuelles.",
    "Les photos d’entrepôt sont un point de contrôle, pas une inspection complète. Elles aident à comparer l’identité et l’état visibles, mais ne prouvent ni l’authenticité, ni la composition, ni la durabilité, ni l’état d’une batterie, ni la couleur sur un autre écran, et ne prédisent pas la douane.",
    "Même une première livraison du vendeur annoncée gratuite peut entraîner un coût lors d’un retour sans motif. En cas de mauvaise taille, de mauvaise couleur ou de défaut confirmé, la responsabilité peut changer ; pour un article expédié directement à l’entrepôt, cela ne remplace pas le contact avec l’expéditeur ou le vendeur.",
    "Au moment du colis, comparez le poids emballé, les trois dimensions, les routes disponibles, l’assurance et la valeur déclarée. Regrouper plusieurs vendeurs peut réduire certains frais fixes, mais un colis plus grand n’est pas forcément moins cher ; batteries, liquides et produits sensibles peuvent exclure des routes.",
    "Un suivi disponible dans les trois jours après l’expédition signifie seulement qu’une mise à jour peut apparaître. Transporteurs tiers, douanes, confiscation, dommage, perte et retards de haute saison restent possibles ; aucun site ne peut promettre un passage en douane ou une date identique pour chaque pays."
  ],
  es: [
    "PikoBuy conecta al comprador, al vendedor del marketplace, al almacén chino y a un transportista internacional. Por eso conviene separar responsabilidades: el vendedor controla artículo y envío nacional, PikoBuy la compra, el almacén y la entrega del paquete al operador, y un tercero realiza el trayecto internacional.",
    "Usa el spreadsheet para crear una lista corta y después compara cada resultado con el anuncio en vivo. Una imagen guardada o un precio indicado no fija stock, opciones de talla ni reglas de devolución: el vendedor puede editar o eliminar un anuncio después de que se haya guardado.",
    "Antes del primer pago, revisa el precio actual del vendedor, el envío nacional y el stock. Los servicios opcionales o cambios de precio pueden modificar el importe previo al almacén; el envío internacional se paga después y también depende de peso, volumen y posibles restricciones.",
    "Las fotos de almacén son un punto de control, no una inspección completa. Sirven para comparar identidad y estado visibles, pero no demuestran autenticidad, composición, durabilidad, salud de batería o color en otra pantalla, ni anticipan el resultado de aduanas.",
    "Incluso un envío inicial del vendedor anunciado como gratuito puede generar un coste en una devolución sin motivo. Si hubo talla o color incorrectos, o defecto confirmado, la responsabilidad puede cambiar; en artículos enviados directamente al almacén esto no sustituye contactar al remitente o vendedor.",
    "Al enviar el paquete, compara peso embalado, las tres dimensiones, rutas disponibles, seguro y valor del contenido. Unir productos de varios vendedores puede reducir cargos repetidos, pero un paquete mayor no siempre cuesta menos; baterías, líquidos y otros bienes sensibles pueden excluir rutas.",
    "Que el seguimiento esté disponible dentro de tres días del despacho solo significa que puede aparecer una actualización. Siguen existiendo transportistas externos, aduanas, confiscación, daño, pérdida y retrasos de temporada; ninguna página puede garantizar aduana cero o una fecha fija en todos los países."
  ],
  it: [
    "PikoBuy collega l’acquirente, il venditore del marketplace, il magazzino cinese e un vettore internazionale. Le responsabilità restano separate: il venditore gestisce articolo e spedizione nazionale, PikoBuy acquisto, magazzino e consegna del pacco al vettore, mentre un operatore terzo cura il trasporto internazionale.",
    "Usa lo spreadsheet per creare una lista breve e confronta poi ogni risultato con l’inserzione dal vivo. Un’immagine salvata o un prezzo indicato non blocca disponibilità, opzioni di taglia o condizioni di reso: il venditore può modificare o rimuovere l’inserzione in seguito.",
    "Prima del primo pagamento verifica il prezzo corrente del venditore, la consegna nazionale e la disponibilità. Servizi opzionali o variazioni di prezzo possono cambiare l’importo prima del magazzino; la spedizione internazionale si paga dopo e dipende anche da peso, volume e restrizioni.",
    "Le foto del magazzino sono un controllo, non un’ispezione completa. Consentono di confrontare identità e condizioni visibili, ma non provano autenticità, composizione, durata, stato della batteria o colore su un altro schermo e non prevedono l’esito doganale.",
    "Anche una prima spedizione del venditore dichiarata gratuita può produrre un costo per un reso senza motivo. Per taglia o colore errati o difetto confermato la responsabilità può cambiare; per merci inoltrate direttamente al magazzino ciò non sostituisce il contatto con mittente o venditore.",
    "Quando invii il pacco confronta peso imballato, tutte e tre le dimensioni, rotte disponibili, assicurazione e valore del contenuto. Riunire articoli di venditori diversi può ridurre costi ripetuti, ma un pacco più grande non è automaticamente più economico; batterie, liquidi e beni sensibili possono escludere rotte.",
    "La disponibilità del tracking entro tre giorni dalla spedizione significa solo che può comparire un aggiornamento. Vettori terzi, dogana, confisca, danno, perdita e ritardi di alta stagione restano rischi possibili; nessun sito può garantire dogana zero o una data fissa per ogni paese."
  ],
  nl: [
    "PikoBuy verbindt de koper, de marketplaceverkoper, het Chinese magazijn en een internationale vervoerder. Houd de verantwoordelijkheden daarom apart: de verkoper beheert artikel en binnenlandse verzending, PikoBuy aankoop, magazijn en pakketaanmelding, en een externe vervoerder verzorgt het internationale traject.",
    "Gebruik het spreadsheet om een korte lijst te maken en vergelijk ieder resultaat daarna met de live aanbieding. Een opgeslagen afbeelding of prijs zet voorraad, maatopties of retourvoorwaarden niet vast: de verkoper kan een aanbieding later aanpassen of verwijderen.",
    "Controleer vóór de eerste betaling de actuele verkopersprijs, binnenlandse verzending en voorraad. Optionele diensten of prijswijzigingen kunnen het bedrag vóór het magazijn veranderen; internationale verzending betaal je later en hangt ook af van gewicht, volume en eventuele beperkingen.",
    "Magazijnfoto’s zijn een controlemoment, geen volledige inspectie. Ze helpen zichtbare identiteit en conditie te vergelijken, maar bewijzen geen authenticiteit, samenstelling, duurzaamheid, batterijconditie of kleur op een ander scherm en voorspellen geen douane-uitkomst.",
    "Zelfs een gratis genoemde eerste verzending van de verkoper kan kosten opleveren bij een onvoorwaardelijke retour. Bij verkeerde maat of kleur, of een bevestigd gebrek, kan de verantwoordelijkheid verschillen; bij zelf naar het magazijn doorgestuurde goederen vervangt dit geen contact met afzender of verkoper.",
    "Vergelijk bij pakketaanmelding het verpakte gewicht, alle drie de afmetingen, beschikbare routes, verzekering en inhoudswaarde. Artikelen van verschillende verkopers samenvoegen kan vaste kosten verminderen, maar een groter pakket is niet vanzelf goedkoper; batterijen, vloeistoffen en gevoelige goederen kunnen routes uitsluiten.",
    "Tracking binnen drie dagen na verzending betekent alleen dat een update kan verschijnen. Externe vervoerders, douane, inbeslagname, schade, verlies en vertraging in het hoogseizoen blijven mogelijke risico’s; geen website kan geen-douane of een vaste datum voor elk land garanderen."
  ],
  pl: [
    "PikoBuy łączy kupującego, sprzedawcę z marketplace, chiński magazyn i międzynarodowego przewoźnika. Trzeba więc rozdzielać odpowiedzialność: sprzedawca odpowiada za produkt i wysyłkę krajową, PikoBuy za zakup, magazyn i nadanie paczki, a zewnętrzny operator za drogę międzynarodową.",
    "Używaj spreadsheetu do stworzenia krótkiej listy, a potem porównuj każdy wynik z aktualną ofertą. Zapisane zdjęcie lub cena nie blokują stanu, opcji rozmiaru ani zasad zwrotu: sprzedawca może później zmienić lub usunąć ofertę.",
    "Przed pierwszą płatnością sprawdź aktualną cenę sprzedawcy, wysyłkę krajową i stan. Usługi dodatkowe lub zmiana ceny mogą zmienić kwotę przed magazynem; wysyłkę międzynarodową płaci się później, a jej koszt zależy również od wagi, objętości i ograniczeń.",
    "Zdjęcia magazynowe są punktem kontroli, nie pełną inspekcją. Pozwalają porównać widoczną tożsamość i stan, lecz nie potwierdzają autentyczności, składu, trwałości, kondycji baterii ani koloru na innym ekranie i nie przewidują decyzji celnej.",
    "Nawet pierwsza wysyłka sprzedawcy opisana jako darmowa może wygenerować koszt przy zwrocie bez powodu. Przy błędnym rozmiarze lub kolorze albo potwierdzonej wadzie odpowiedzialność może być inna; przy towarze samodzielnie przekazanym do magazynu nadal trzeba kontaktować się z nadawcą lub sprzedawcą.",
    "Przy nadaniu porównaj zapakowaną wagę, wszystkie trzy wymiary, dostępne trasy, ubezpieczenie i wartość zawartości. Łączenie artykułów od różnych sprzedawców może obniżyć powtarzalne opłaty, ale większa paczka nie zawsze jest tańsza; baterie, płyny i towary wrażliwe mogą wykluczać trasy.",
    "Tracking dostępny w ciągu trzech dni od wysyłki oznacza jedynie, że może pojawić się aktualizacja. Zewnętrzni przewoźnicy, cło, konfiskata, uszkodzenie, utrata i opóźnienia sezonowe pozostają ryzykiem; żadna strona nie może zagwarantować braku kontroli celnej ani stałej daty dla każdego kraju."
  ],
  sv: [
    "PikoBuy kopplar köparen, marknadsplatsens säljare, det kinesiska lagret och en internationell transportör. Ansvaren måste därför hållas isär: säljaren styr varan och inrikes försändelse, PikoBuy inköp, lager och paketöverlämning, medan en extern aktör sköter den internationella transporten.",
    "Använd kalkylbladet för en kort lista och jämför sedan varje resultat med den aktuella annonsen. En sparad bild eller ett angivet pris låser inte lager, storleksval eller returregler: säljaren kan senare ändra eller ta bort en annons.",
    "Före första betalningen ska aktuellt säljarpris, inrikes leverans och lagerstatus kontrolleras. Valfria tjänster eller prisförändringar kan ändra beloppet före lagret; internationell frakt betalas senare och beror även på vikt, volym och möjliga begränsningar.",
    "Lagerbilder är en kontrollpunkt, inte en fullständig inspektion. De hjälper till att jämföra synlig identitet och skick, men bevisar inte äkthet, materialsammansättning, hållbarhet, batterihälsa eller färg på en annan skärm och förutsäger inte tullutfallet.",
    "Även en första säljarleverans som anges som gratis kan ge en kostnad vid ovillkorlig retur. Vid fel storlek eller färg eller ett bekräftat fel kan ansvaret skilja sig; för varor som användaren själv skickat till lagret ersätter detta inte kontakt med avsändare eller säljare.",
    "Jämför vid paketinlämning packad vikt, alla tre mått, tillgängliga rutter, försäkring och innehållets värde. Att samla varor från olika säljare kan minska upprepade avgifter, men ett större paket är inte automatiskt billigare; batterier, vätskor och känsliga varor kan utesluta rutter.",
    "Spårning inom tre dagar efter avsändning betyder bara att en uppdatering kan visas. Externa transportörer, tull, beslag, skada, förlust och förseningar under högsäsong är fortfarande möjliga risker; ingen webbplats kan garantera tullfritt eller ett fast datum för varje land."
  ],
  pt: [
    "A PikoBuy liga o comprador, o vendedor do marketplace, o armazém chinês e um transportador internacional. Por isso, as responsabilidades devem manter-se separadas: o vendedor controla o artigo e a entrega nacional, a PikoBuy compra, armazém e submissão do pacote, e um operador externo faz o percurso internacional.",
    "Use a folha para criar uma lista curta e depois compare cada resultado com o anúncio em direto. Uma imagem guardada ou um preço indicado não fixa stock, opções de tamanho ou regras de devolução: o vendedor pode alterar ou remover um anúncio mais tarde.",
    "Antes do primeiro pagamento, confirme o preço atual do vendedor, entrega nacional e stock. Serviços opcionais ou alteração de preço podem mudar o valor antes do armazém; o envio internacional é pago depois e também depende de peso, volume e restrições possíveis.",
    "As fotos de armazém são um ponto de controlo, não uma inspeção completa. Ajudam a comparar identidade e estado visíveis, mas não provam autenticidade, composição, durabilidade, saúde da bateria ou cor noutro ecrã, nem prevêem o resultado aduaneiro.",
    "Mesmo uma primeira entrega do vendedor anunciada como gratuita pode gerar custo numa devolução sem motivo. Em caso de tamanho ou cor errados, ou defeito confirmado, a responsabilidade pode ser diferente; para mercadoria enviada diretamente ao armazém, isto não substitui contactar remetente ou vendedor.",
    "Ao submeter o pacote, compare peso embalado, as três dimensões, rotas disponíveis, seguro e valor do conteúdo. Juntar artigos de vários vendedores pode reduzir custos repetidos, mas um pacote maior não é automaticamente mais barato; baterias, líquidos e bens sensíveis podem excluir rotas.",
    "Tracking disponível dentro de três dias após o despacho significa apenas que pode surgir uma atualização. Transportadores externos, alfândega, apreensão, danos, perda e atrasos de época alta continuam possíveis; nenhum site pode garantir zero alfândega ou uma data fixa em todos os países."
  ]
};

const expectedLanguages = ["de", "fr", "es", "it", "nl", "pl", "sv", "pt"];
for (const language of expectedLanguages) {
  if (seoTranslationCoverage[language]?.length !== 7) {
    throw new Error(`Incomplete SEO fact coverage: ${language}`);
  }
}
