export type CategoryActionLabels={title:string;description:string;browse:string;allCategories:string};

export const categoryActionCopy:Record<string,CategoryActionLabels>={
  en:{title:"Use this category",description:"Continue to the main FindSpreadsheet database to compare current listings. Prices, options and availability must be checked live.",browse:"Browse on FindSpreadsheet:",allCategories:"All categories"},
  es:{title:"Usar esta categoría",description:"Continúa en la base de datos principal de FindSpreadsheet para comparar los listados actuales. Los precios, opciones y disponibilidad deben comprobarse en directo.",browse:"Ver en FindSpreadsheet:",allCategories:"Todas las categorías"},
  fr:{title:"Utiliser cette catégorie",description:"Continuez vers la base principale FindSpreadsheet pour comparer les annonces actuelles. Les prix, options et disponibilités doivent être vérifiés en direct.",browse:"Voir sur FindSpreadsheet :",allCategories:"Toutes les catégories"},
  de:{title:"Diese Kategorie verwenden",description:"Öffnen Sie die FindSpreadsheet-Hauptdatenbank, um aktuelle Angebote zu vergleichen. Preise, Optionen und Verfügbarkeit müssen live geprüft werden.",browse:"Auf FindSpreadsheet ansehen:",allCategories:"Alle Kategorien"},
  it:{title:"Usa questa categoria",description:"Continua nel database principale di FindSpreadsheet per confrontare le inserzioni attuali. Prezzi, opzioni e disponibilità devono essere verificati dal vivo.",browse:"Vedi su FindSpreadsheet:",allCategories:"Tutte le categorie"},
  pl:{title:"Użyj tej kategorii",description:"Przejdź do głównej bazy FindSpreadsheet, aby porównać aktualne oferty. Ceny, opcje i dostępność trzeba sprawdzić na żywo.",browse:"Zobacz w FindSpreadsheet:",allCategories:"Wszystkie kategorie"},
  nl:{title:"Gebruik deze categorie",description:"Ga naar de hoofddatabase van FindSpreadsheet om actuele aanbiedingen te vergelijken. Prijzen, opties en beschikbaarheid moeten live worden gecontroleerd.",browse:"Bekijk op FindSpreadsheet:",allCategories:"Alle categorieën"},
  sv:{title:"Använd den här kategorin",description:"Fortsätt till FindSpreadsheets huvuddatabas för att jämföra aktuella listningar. Priser, alternativ och tillgänglighet måste kontrolleras live.",browse:"Visa på FindSpreadsheet:",allCategories:"Alla kategorier"},
  no:{title:"Bruk denne kategorien",description:"Fortsett til hoveddatabasen i FindSpreadsheet for å sammenligne aktuelle oppføringer. Priser, valg og tilgjengelighet må sjekkes direkte.",browse:"Se på FindSpreadsheet:",allCategories:"Alle kategorier"},
  da:{title:"Brug denne kategori",description:"Fortsæt til FindSpreadsheets hoveddatabase for at sammenligne aktuelle annoncer. Priser, muligheder og tilgængelighed skal kontrolleres live.",browse:"Se på FindSpreadsheet:",allCategories:"Alle kategorier"},
  pt:{title:"Usar esta categoria",description:"Continue para a base de dados principal do FindSpreadsheet para comparar anúncios atuais. Preços, opções e disponibilidade devem ser verificados ao vivo.",browse:"Ver no FindSpreadsheet:",allCategories:"Todas as categorias"},
  cs:{title:"Použít tuto kategorii",description:"Pokračujte do hlavní databáze FindSpreadsheet a porovnejte aktuální nabídky. Ceny, možnosti a dostupnost je nutné ověřit živě.",browse:"Zobrazit na FindSpreadsheet:",allCategories:"Všechny kategorie"},
  ro:{title:"Folosește această categorie",description:"Continuă în baza principală FindSpreadsheet pentru a compara listările actuale. Prețurile, opțiunile și disponibilitatea trebuie verificate în direct.",browse:"Vezi pe FindSpreadsheet:",allCategories:"Toate categoriile"},
  hu:{title:"Használd ezt a kategóriát",description:"Folytasd a FindSpreadsheet fő adatbázisában az aktuális ajánlatok összehasonlítását. Az árakat, opciókat és elérhetőséget élőben kell ellenőrizni.",browse:"Megtekintés a FindSpreadsheeten:",allCategories:"Minden kategória"},
  fi:{title:"Käytä tätä kategoriaa",description:"Jatka FindSpreadsheetin päätietokantaan vertailemaan nykyisiä listauksia. Hinnat, vaihtoehdot ja saatavuus on tarkistettava reaaliajassa.",browse:"Näytä FindSpreadsheetissä:",allCategories:"Kaikki kategoriat"},
  el:{title:"Χρήση αυτής της κατηγορίας",description:"Συνεχίστε στην κύρια βάση δεδομένων FindSpreadsheet για να συγκρίνετε τις τρέχουσες καταχωρίσεις. Οι τιμές, οι επιλογές και η διαθεσιμότητα πρέπει να ελέγχονται ζωντανά.",browse:"Προβολή στο FindSpreadsheet:",allCategories:"Όλες οι κατηγορίες"},
  tr:{title:"Bu kategoriyi kullan",description:"Güncel ilanları karşılaştırmak için ana FindSpreadsheet veritabanına devam edin. Fiyatlar, seçenekler ve stok durumu canlı olarak kontrol edilmelidir.",browse:"FindSpreadsheet'te görüntüle:",allCategories:"Tüm kategoriler"},
  lt:{title:"Naudoti šią kategoriją",description:"Tęskite pagrindinėje FindSpreadsheet duomenų bazėje ir palyginkite dabartinius pasiūlymus. Kainas, parinktis ir prieinamumą reikia tikrinti tiesiogiai.",browse:"Žiūrėti FindSpreadsheet:",allCategories:"Visos kategorijos"},
  lv:{title:"Izmantot šo kategoriju",description:"Turpiniet galvenajā FindSpreadsheet datubāzē, lai salīdzinātu aktuālos piedāvājumus. Cenas, iespējas un pieejamība jāpārbauda tiešsaistē.",browse:"Skatīt FindSpreadsheet:",allCategories:"Visas kategorijas"},
  et:{title:"Kasuta seda kategooriat",description:"Jätka FindSpreadsheeti põhiandmebaasis, et võrrelda praeguseid pakkumisi. Hinnad, valikud ja saadavus tuleb reaalajas üle kontrollida.",browse:"Vaata FindSpreadsheetis:",allCategories:"Kõik kategooriad"},
  sk:{title:"Použiť túto kategóriu",description:"Pokračujte do hlavnej databázy FindSpreadsheet a porovnajte aktuálne ponuky. Ceny, možnosti a dostupnosť treba overiť naživo.",browse:"Zobraziť na FindSpreadsheet:",allCategories:"Všetky kategórie"},
  bg:{title:"Използвайте тази категория",description:"Продължете към основната база данни на FindSpreadsheet, за да сравните актуалните обяви. Цените, опциите и наличността трябва да се проверят на живо.",browse:"Вижте във FindSpreadsheet:",allCategories:"Всички категории"},
  hr:{title:"Koristi ovu kategoriju",description:"Nastavite do glavne baze FindSpreadsheet kako biste usporedili aktualne ponude. Cijene, opcije i dostupnost moraju se provjeriti uživo.",browse:"Pogledaj na FindSpreadsheetu:",allCategories:"Sve kategorije"},
  ga:{title:"Úsáid an chatagóir seo",description:"Lean ar aghaidh chuig príomhbhunachar FindSpreadsheet chun liostaí reatha a chur i gcomparáid. Ní mór praghsanna, roghanna agus infhaighteacht a sheiceáil beo.",browse:"Féach ar FindSpreadsheet:",allCategories:"Gach catagóir"}
};
