export type LocaleCopy = { articlesTitle:string; articlesIntro:string; faqTitle:string; faqIntro:string; read:string; allLanguages:string; verifiedLabel:string; fullArticleLabel:string; };

export const localeCopy: Record<string, LocaleCopy> = {
  en:{articlesTitle:"LoloBuy research articles",articlesIntro:"Long-form, evidence-led buying, QC and shipping guides.",faqTitle:"LoloBuy frequently asked questions",faqIntro:"Practical answers that separate confirmed platform facts from variables you must check live.",read:"Read",allLanguages:"All languages",verifiedLabel:"Fact-checked overview",fullArticleLabel:"Full verified article"},
  es:{articlesTitle:"Artículos de investigación sobre LoloBuy",articlesIntro:"Guías extensas y basadas en hechos sobre compras, control de calidad y envíos.",faqTitle:"Preguntas frecuentes sobre LoloBuy",faqIntro:"Respuestas prácticas que separan los hechos confirmados de lo que debes comprobar en directo.",read:"Leer",allLanguages:"Todos los idiomas",verifiedLabel:"Resumen verificado",fullArticleLabel:"Artículo completo verificado"},
  fr:{articlesTitle:"Articles de recherche sur LoloBuy",articlesIntro:"Guides détaillés et factuels sur l’achat, le contrôle qualité et l’expédition.",faqTitle:"Questions fréquentes sur LoloBuy",faqIntro:"Des réponses pratiques qui distinguent les faits confirmés des éléments à vérifier en direct.",read:"Lire",allLanguages:"Toutes les langues",verifiedLabel:"Résumé vérifié",fullArticleLabel:"Article complet vérifié"},
  de:{articlesTitle:"LoloBuy-Ratgeber und Recherchen",articlesIntro:"Ausführliche, faktenbasierte Leitfäden zu Einkauf, Qualitätskontrolle und Versand.",faqTitle:"Häufige Fragen zu LoloBuy",faqIntro:"Praktische Antworten, die bestätigte Fakten von live zu prüfenden Angaben trennen.",read:"Lesen",allLanguages:"Alle Sprachen",verifiedLabel:"Geprüfter Überblick",fullArticleLabel:"Vollständiger geprüfter Artikel"},
  it:{articlesTitle:"Articoli di ricerca su LoloBuy",articlesIntro:"Guide approfondite e basate sui fatti su acquisti, controllo qualità e spedizioni.",faqTitle:"Domande frequenti su LoloBuy",faqIntro:"Risposte pratiche che distinguono i fatti confermati dalle variabili da verificare dal vivo.",read:"Leggi",allLanguages:"Tutte le lingue",verifiedLabel:"Panoramica verificata",fullArticleLabel:"Articolo completo verificato"},
  pl:{articlesTitle:"Artykuły badawcze o LoloBuy",articlesIntro:"Szczegółowe, oparte na faktach poradniki o zakupach, kontroli jakości i wysyłce.",faqTitle:"Najczęstsze pytania o LoloBuy",faqIntro:"Praktyczne odpowiedzi oddzielające potwierdzone fakty od danych wymagających sprawdzenia na żywo.",read:"Czytaj",allLanguages:"Wszystkie języki",verifiedLabel:"Zweryfikowane podsumowanie",fullArticleLabel:"Pełny zweryfikowany artykuł"},
  nl:{articlesTitle:"Onderzoeksartikelen over LoloBuy",articlesIntro:"Uitgebreide, feitelijke gidsen over kopen, kwaliteitscontrole en verzending.",faqTitle:"Veelgestelde vragen over LoloBuy",faqIntro:"Praktische antwoorden die bevestigde feiten scheiden van gegevens die live moeten worden gecontroleerd.",read:"Lees",allLanguages:"Alle talen",verifiedLabel:"Geverifieerd overzicht",fullArticleLabel:"Volledig geverifieerd artikel"},
  sv:{articlesTitle:"Forskningsartiklar om LoloBuy",articlesIntro:"Utförliga, faktabaserade guider om köp, kvalitetskontroll och frakt.",faqTitle:"Vanliga frågor om LoloBuy",faqIntro:"Praktiska svar som skiljer bekräftade fakta från uppgifter som måste kontrolleras live.",read:"Läs",allLanguages:"Alla språk",verifiedLabel:"Verifierad översikt",fullArticleLabel:"Fullständig verifierad artikel"},
  no:{articlesTitle:"Forskningsartikler om LoloBuy",articlesIntro:"Grundige, faktabaserte guider om kjøp, kvalitetskontroll og frakt.",faqTitle:"Vanlige spørsmål om LoloBuy",faqIntro:"Praktiske svar som skiller bekreftede fakta fra opplysninger som må sjekkes live.",read:"Les",allLanguages:"Alle språk",verifiedLabel:"Verifisert oversikt",fullArticleLabel:"Fullstendig verifisert artikkel"},
  da:{articlesTitle:"Forskningsartikler om LoloBuy",articlesIntro:"Grundige, faktabaserede guider om køb, kvalitetskontrol og fragt.",faqTitle:"Ofte stillede spørgsmål om LoloBuy",faqIntro:"Praktiske svar der skelner mellem bekræftede fakta og oplysninger, som skal kontrolleres live.",read:"Læs",allLanguages:"Alle sprog",verifiedLabel:"Verificeret overblik",fullArticleLabel:"Fuld verificeret artikel"},
  pt:{articlesTitle:"Artigos de pesquisa sobre LoloBuy",articlesIntro:"Guias aprofundados e factuais sobre compras, controlo de qualidade e envio.",faqTitle:"Perguntas frequentes sobre LoloBuy",faqIntro:"Respostas práticas que separam factos confirmados de dados que devem ser verificados ao vivo.",read:"Ler",allLanguages:"Todos os idiomas",verifiedLabel:"Resumo verificado",fullArticleLabel:"Artigo completo verificado"},
  cs:{articlesTitle:"Výzkumné články o LoloBuy",articlesIntro:"Podrobné a věcně podložené průvodce nákupem, kontrolou kvality a dopravou.",faqTitle:"Časté otázky o LoloBuy",faqIntro:"Praktické odpovědi, které oddělují potvrzená fakta od údajů k ověření v reálném čase.",read:"Číst",allLanguages:"Všechny jazyky",verifiedLabel:"Ověřený přehled",fullArticleLabel:"Úplný ověřený článek"},
  ro:{articlesTitle:"Articole de cercetare despre LoloBuy",articlesIntro:"Ghiduri detaliate și bazate pe fapte despre cumpărare, controlul calității și livrare.",faqTitle:"Întrebări frecvente despre LoloBuy",faqIntro:"Răspunsuri practice care separă faptele confirmate de datele ce trebuie verificate în direct.",read:"Citește",allLanguages:"Toate limbile",verifiedLabel:"Prezentare verificată",fullArticleLabel:"Articol complet verificat"},
  hu:{articlesTitle:"LoloBuy kutatási cikkek",articlesIntro:"Részletes, tényalapú útmutatók vásárlásról, minőségellenőrzésről és szállításról.",faqTitle:"Gyakori kérdések a LoloBuy-ról",faqIntro:"Gyakorlati válaszok, amelyek elkülönítik a megerősített tényeket az élőben ellenőrzendő adatoktól.",read:"Olvasás",allLanguages:"Minden nyelv",verifiedLabel:"Ellenőrzött áttekintés",fullArticleLabel:"Teljes ellenőrzött cikk"},
  fi:{articlesTitle:"LoloBuy-tutkimusartikkelit",articlesIntro:"Laajat, faktoihin perustuvat oppaat ostamisesta, laaduntarkastuksesta ja toimituksesta.",faqTitle:"Usein kysyttyä LoloBuysta",faqIntro:"Käytännön vastaukset erottavat vahvistetut tiedot reaaliajassa tarkistettavista asioista.",read:"Lue",allLanguages:"Kaikki kielet",verifiedLabel:"Tarkistettu yleiskatsaus",fullArticleLabel:"Koko tarkistettu artikkeli"},
  el:{articlesTitle:"Ερευνητικά άρθρα για το LoloBuy",articlesIntro:"Αναλυτικοί οδηγοί βασισμένοι σε στοιχεία για αγορές, ποιοτικό έλεγχο και αποστολή.",faqTitle:"Συχνές ερωτήσεις για το LoloBuy",faqIntro:"Πρακτικές απαντήσεις που ξεχωρίζουν τα επιβεβαιωμένα στοιχεία από όσα χρειάζονται ζωντανό έλεγχο.",read:"Διαβάστε",allLanguages:"Όλες οι γλώσσες",verifiedLabel:"Επαληθευμένη σύνοψη",fullArticleLabel:"Πλήρες επαληθευμένο άρθρο"},
  tr:{articlesTitle:"LoloBuy araştırma makaleleri",articlesIntro:"Satın alma, kalite kontrolü ve gönderim hakkında ayrıntılı, kanıta dayalı rehberler.",faqTitle:"LoloBuy hakkında sık sorulan sorular",faqIntro:"Doğrulanmış bilgileri canlı olarak kontrol edilmesi gereken ayrıntılardan ayıran pratik yanıtlar.",read:"Oku",allLanguages:"Tüm diller",verifiedLabel:"Doğrulanmış özet",fullArticleLabel:"Tam doğrulanmış makale"},
  lt:{articlesTitle:"LoloBuy tyrimų straipsniai",articlesIntro:"Išsamūs, faktais pagrįsti pirkimo, kokybės tikrinimo ir siuntimo vadovai.",faqTitle:"Dažniausi klausimai apie LoloBuy",faqIntro:"Praktiniai atsakymai atskiria patvirtintus faktus nuo duomenų, kuriuos reikia tikrinti tiesiogiai.",read:"Skaityti",allLanguages:"Visos kalbos",verifiedLabel:"Patikrinta apžvalga",fullArticleLabel:"Visas patikrintas straipsnis"},
  lv:{articlesTitle:"LoloBuy izpētes raksti",articlesIntro:"Detalizēti, faktos balstīti ceļveži par pirkšanu, kvalitātes pārbaudi un piegādi.",faqTitle:"Biežākie jautājumi par LoloBuy",faqIntro:"Praktiskas atbildes, kas nošķir apstiprinātus faktus no tiešsaistē pārbaudāmiem datiem.",read:"Lasīt",allLanguages:"Visas valodas",verifiedLabel:"Pārbaudīts pārskats",fullArticleLabel:"Pilns pārbaudīts raksts"},
  et:{articlesTitle:"LoloBuy uurimisartiklid",articlesIntro:"Põhjalikud ja faktipõhised juhendid ostmise, kvaliteedikontrolli ja saatmise kohta.",faqTitle:"Korduma kippuvad küsimused LoloBuy kohta",faqIntro:"Praktilised vastused eristavad kinnitatud faktid reaalajas kontrollitavatest andmetest.",read:"Loe",allLanguages:"Kõik keeled",verifiedLabel:"Kontrollitud ülevaade",fullArticleLabel:"Täielik kontrollitud artikkel"},
  sk:{articlesTitle:"Výskumné články o LoloBuy",articlesIntro:"Podrobné a faktami podložené návody na nákup, kontrolu kvality a dopravu.",faqTitle:"Časté otázky o LoloBuy",faqIntro:"Praktické odpovede oddeľujú potvrdené fakty od údajov, ktoré treba overiť naživo.",read:"Čítať",allLanguages:"Všetky jazyky",verifiedLabel:"Overený prehľad",fullArticleLabel:"Úplný overený článok"},
  bg:{articlesTitle:"Изследователски статии за LoloBuy",articlesIntro:"Подробни ръководства, основани на факти, за покупки, контрол на качеството и доставка.",faqTitle:"Често задавани въпроси за LoloBuy",faqIntro:"Практични отговори, които отделят потвърдените факти от данните за проверка на живо.",read:"Прочети",allLanguages:"Всички езици",verifiedLabel:"Проверен преглед",fullArticleLabel:"Пълна проверена статия"},
  hr:{articlesTitle:"Istraživački članci o LoloBuyu",articlesIntro:"Detaljni vodiči utemeljeni na činjenicama o kupnji, kontroli kvalitete i dostavi.",faqTitle:"Česta pitanja o LoloBuyu",faqIntro:"Praktični odgovori koji odvajaju potvrđene činjenice od podataka koje treba provjeriti uživo.",read:"Pročitaj",allLanguages:"Svi jezici",verifiedLabel:"Provjereni pregled",fullArticleLabel:"Cijeli provjereni članak"},
  ga:{articlesTitle:"Ailt taighde faoi LoloBuy",articlesIntro:"Treoracha mionsonraithe bunaithe ar fhíricí faoi cheannach, seiceáil cáilíochta agus loingseoireacht.",faqTitle:"Ceisteanna coitianta faoi LoloBuy",faqIntro:"Freagraí praiticiúla a scarann fíricí deimhnithe ó shonraí nach mór a sheiceáil beo.",read:"Léigh",allLanguages:"Gach teanga",verifiedLabel:"Forbhreathnú fíoraithe",fullArticleLabel:"Alt iomlán fíoraithe"}
};
