import type { Metadata } from "next";
import { ContentLayout, PageSearchParams, SourceNote } from "../content-layout";
import { normalizeLanguage } from "../i18n";

export const metadata: Metadata = {
  title: "PikoBuy QC Method: Listing, Warehouse Photo & Return Checks",
  description: "A practical PikoBuy QC workflow covering source listings, order options, warehouse photos, inspection limits, returns and shipping readiness.",
};

const categoryChecks = [
  { title: "Clothing", copy: "Readable chest, length, sleeve or waist measurements; seams; print alignment; fabric appearance; zippers and buttons.", href: "https://findspreadsheet.com/t-shirts/", cta: "Browse clothing products" },
  { title: "Footwear", copy: "Both side profiles, outsole, heel alignment, toe shape, insole length, size label and visible construction defects.", href: "https://findspreadsheet.com/shoes/", cta: "Browse footwear products" },
  { title: "Bags & accessories", copy: "Dimensions, closures, hardware finish, edge paint, strap attachment, lining and surface marks.", href: "https://findspreadsheet.com/accessories/", cta: "Browse accessory products" },
  { title: "Electronics", copy: "Model label, plug, voltage, included accessories, seal condition and visible damage—without treating photos as a functional test.", href: "https://findspreadsheet.com/electronics/", cta: "Browse electronics products" },
  { title: "Fragile goods", copy: "Corners, edges, glass or ceramic surfaces, protective packaging and a plan for reinforcement before dispatch.", href: "shipping-risk", cta: "Open fragile-shipping guidance" },
];

export default async function QcMethodPage({ searchParams }: PageSearchParams) {
  const language = normalizeLanguage((await searchParams).lang);
  const suffix = language === "en" ? "" : `?lang=${language}`;
  return <ContentLayout language={language} kicker="QC METHOD / FIVE DECISION PASSES" title="Read PikoBuy warehouse photos like evidence." intro="PikoBuy publishes a warehouse inspection and photo stage, but the buyer still has to decide whether the evidence answers the risk of the exact product." tone="lime">
    <section className="content-section prose-grid">
      <aside className="sticky-index"><span>FIVE PASSES</span><a href="#listing">01 · Listing</a><a href="#order">02 · Order</a><a href="#photos">03 · Photos</a><a href="#return">04 · Return clock</a><a href="#landed">05 · Parcel</a><a href={`/guides/qc-photos${suffix}`}>Detailed photo guide ↗</a></aside>
      <div className="prose-body">
        <article id="listing"><span>01 / ORIGINAL LISTING</span><h2>Confirm the exact item before judging quality.</h2><p>Open the current seller page and compare the selected color, size, quantity and variant with the spreadsheet row. PikoBuy’s beginner guide tells buyers to confirm those details before ordering and recommends saving the product or store information. If an older row and the live source disagree, investigate the live listing rather than trusting the cleaner-looking record.</p><p>PikoBuy’s user agreement explains that its search and display service can surface seller links from platforms such as Taobao and 1688, while PikoBuy itself is not the seller. That distinction matters. A link appearing inside an agent workflow does not prove that the merchant, product claim, material, authenticity or current stock has been independently verified. Treat the live seller page as evidence to inspect, not as a platform endorsement.</p><p>Price also needs context. The beginner guide says the final amount is based on the actual purchase, so a spreadsheet price is a research reference rather than a permanent quote. Check whether the lowest displayed option is the complete product, a deposit, an accessory or a different variant. If the seller page is unavailable or materially changed, mark the row for rechecking instead of quietly preserving an outdated description.</p><ul><li>Match the seller, title and current product photographs.</li><li>Check whether the cheapest option is the pictured item or only an accessory.</li><li>Save the product and store details before the seller changes the page.</li><li>Record the date and variant you actually verified.</li></ul></article>
        <article id="order"><span>02 / ORDER SUBMISSION</span><h2>Compare the options a second time before the first payment.</h2><p>PikoBuy says the buyer pastes a link or keywords into its search box, chooses the product options and completes a first payment. The final price is based on the actual purchase. QC begins after the seller has sent something, so it is too late to discover that the wrong option was intentionally selected at checkout.</p><p>A useful record therefore keeps two references: what the seller listing showed and what the submitted PikoBuy order requested. If they do not agree, pause before paying. Save the color name, seller size code, quantity, any manual note and the order total together. This is especially important when a seller uses images rather than words for variants, or when several options share similar names.</p><p>The official guide also says an out-of-stock order will be refunded, but that does not make every seller delay or listing change an automatic quality claim. Keep availability separate from condition: stock is checked during purchasing, while visible condition is assessed after arrival. A clean timeline makes later support conversations much easier to explain.</p></article>
        <article id="photos"><span>03 / WAREHOUSE PHOTOS</span><h2>Ask whether the photographs answer the real risk.</h2><p>The official guide says warehouse staff check items in, take confirmation photos and look for defects. The transfer policy adds that buyers can use inspection photographs or purchase extra detailed photographs. More images are not automatically better: the right angle, measurement or close-up is what changes a decision.</p><p>Start by naming the rejection condition. If a pair of shoes would be unusable below a certain insole length, request a removable insole beside a readable tape. If print placement matters, request a straight-on view with the garment laid flat. If a bag’s scale is uncertain, ask for width, height and depth with the measurement endpoints visible. Requests written around a decision are easier to evaluate than “please inspect carefully.”</p><p>A front view of a shoe cannot confirm insole length. A folded hoodie cannot confirm chest width. A sealed electronic box cannot prove that the device works. PikoBuy’s shipping policy says special and professional goods cannot receive professional inspection, and its user agreement says some specialist or sealed products may receive only an exterior and accessory check. Treat QC as evidence of visible condition, not certification of authenticity, safety or performance.</p><p>Preserve the original images and any added-photo request. When an issue is subtle, identify the exact photograph and visible area rather than making a broad conclusion. A photograph can document a stain, hole, wrong color, missing visible part or measurable mismatch; it usually cannot establish fibre chemistry, battery health, waterproofing or future durability.</p></article>
        <article id="return"><span>04 / RETURN WINDOW</span><h2>Good evidence loses value if it is reviewed too late.</h2><p>PikoBuy’s current returns page says an eligible request can be submitted within five days after the order status becomes “Warehoused,” counted as 120 hours beginning from the next hour. Requests after that point might not be accepted. The same page says PikoBuy can return an item only when the seller agrees.</p><p>Timing is only one condition. The published page says the seller must offer the relevant guarantee and the item must remain marketable under the seller’s rules. It lists customized goods, second-hand goods, undergarments, food, some overseas-origin products and seller-defined exceptions among the categories that may not qualify. Category-specific standards also protect seals, tags and packaging.</p><p>Keep tags, seals, accessories and protective packaging intact until the decision is made. Do not ask the warehouse to remove or test something destructively merely to satisfy curiosity: a request made by the buyer can alter return eligibility. For an unconditional return, PikoBuy currently publishes a formula combining shipping back to the seller, the seller’s original domestic shipping and a 5 RMB service fee. The fee and responsibility may differ when the seller sent the wrong product or a verified quality issue exists.</p></article>
        <article id="landed"><span>05 / LANDED CONTEXT</span><h2>Approve the product and the parcel plan together.</h2><p>An item can look acceptable while making little sense after packaging, chargeable weight, route restrictions and international freight are considered. The official beginner guide allows requests such as minimal or reinforced packaging and says live routes differ by delivery time and price. Fragile products may benefit from reinforcement; bulky low-value packaging may justify reduction. Neither choice is universal.</p><p>PikoBuy’s official estimator asks for destination country or region, product type, weight, length, width and height. Those inputs are a useful reminder that the product price alone does not describe landed value. Estimate before buying, then compare again after the warehouse has the actual item and a packing plan. An estimate is not a guaranteed quote, and route availability can change with destination, goods type and live operating conditions.</p><p>For batteries, liquids, powders, glue, food, medicines and other sensitive products, confirm route eligibility before assuming the item can travel. PikoBuy’s user agreement says customs clearance is not guaranteed and describes higher risks for sensitive goods. It also currently states that the package-forwarding platform service fee is calculated at 8% of freight, subject to small settlement or exchange-rate differences. Verify the live checkout rather than copying that percentage into a fixed promise.</p><p>The shipping policy says international parcels are carried by third-party logistics providers and names customs action, damage, loss and peak delays among risks the buyer must evaluate. Insurance may change the compensation path, but its exclusions and insured value still matter. The final decision is therefore not only “does the item look good?” It is “does this exact item, in this packaging, on an available route, still justify the total cost and risk?”</p></article>
        <SourceNote><a href="https://www.pikobuy.com/guide" target="_blank" rel="noopener noreferrer">PikoBuy Beginner’s Guide</a>, <a href="https://www.pikobuy.com/protocol/shipping" target="_blank" rel="noopener noreferrer">Shipping Policy</a>, <a href="https://www.pikobuy.com/protocol/returns" target="_blank" rel="noopener noreferrer">Returns & Exchanges</a> and <a href="https://www.pikobuy.com/protocol/user" target="_blank" rel="noopener noreferrer">User Agreement</a>, checked 06 August 2026.</SourceNote>
      </div>
    </section>

    <section className="content-section">
      <div className="content-section-heading"><span>CATEGORY EVIDENCE</span><h2>Different products need different photographs.</h2><p>This checklist is our practical interpretation of the official photo stage. It does not claim PikoBuy will provide every view automatically.</p></div>
      <div className="evidence-table clickable-evidence-grid">{categoryChecks.map((item, index) => {
        const internal = item.href === "shipping-risk";
        const href = internal ? `/guides/shipping${suffix}#risk` : item.href;
        return <article key={item.title}><a className="evidence-card-link" href={href} {...(!internal ? { target: "_blank", rel: "noopener noreferrer" } : {})} aria-label={`${item.cta}: ${item.title}`}><span>{String(index + 1).padStart(2, "0")}</span><h3>{item.title}</h3><p>{item.copy}</p><b>{item.cta} ↗</b></a></article>;
      })}</div>
    </section>

    <section className="split-callout"><div><span>THE LIMIT</span><h2>QC can reduce uncertainty. It cannot remove it.</h2></div><div><p>Photographs can reveal measurements, alignment, finish, missing accessories and visible damage. They cannot prove authenticity, internal electronics, material chemistry or future durability.</p><a href={`/guides/qc-photos${suffix}`}>Open the detailed photo-request guide ↗</a></div></section>
  </ContentLayout>;
}
