import type { Metadata } from "next";
import { ContentLayout, PageSearchParams, SourceNote } from "../../content-layout";
import { normalizeLanguage } from "../../i18n";
import { ProductShowcase } from "../../product-showcase";

export const metadata: Metadata = {
  title: "PikoBuy Shipping Guide 2026: Weight, Fees, Routes & Risks",
  description: "Plan PikoBuy shipping with destination, product type, weight, dimensions, packaging, current fee wording, route restrictions and logistics risks.",
};

const estimatorInputs = [
  { title: "Destination", field: "Country / region", official: "Required by PikoBuy's public estimator before route comparison.", action: "Use the actual delivery destination because route availability and destination conditions differ.", mistake: "Reusing another buyer's quote for a different country or region." },
  { title: "Product type", field: "Goods category", official: "The estimator asks the buyer to select a product type.", action: "Classify ordinary, battery-powered, liquid, fragile or other sensitive contents honestly before comparing routes.", mistake: "Treating every product as ordinary goods to obtain a lower-looking estimate." },
  { title: "Weight", field: "Kilograms", official: "Weight is a required numeric field in the estimator.", action: "Use a realistic packed weight when known; include packaging rather than relying only on a seller's bare-item claim.", mistake: "Entering zero or a guessed item-only weight and treating the result as a parcel quote." },
  { title: "Length", field: "Centimetres", official: "Length is requested separately from width and height.", action: "Measure the packed parcel's longest side consistently and keep the unit in centimetres.", mistake: "Entering product dimensions while planning to keep a much larger retail box." },
  { title: "Width", field: "Centimetres", official: "Width is a separate estimator input.", action: "Use the second packed side and include space created by reinforcement or consolidation.", mistake: "Swapping units or leaving the field empty because the parcel feels light." },
  { title: "Height", field: "Centimetres", official: "Height completes the three requested parcel dimensions.", action: "Use the remaining packed side, including protective material or a retained shoe box.", mistake: "Assuming only scale weight matters on every route." },
];

const riskRows = [
  ["Third-party carriage", "PikoBuy states that international parcels are carried by third-party logistics providers."],
  ["Customs", "The platform does not guarantee customs clearance and names detention, confiscation and destination rules as buyer risks."],
  ["Sensitive goods", "The user agreement specifically mentions liquids, powders, batteries, food, medicine, glue and similar items as higher-risk."],
  ["Fragile goods", "Ceramics, glass and irregular shapes may be damaged across multiple transport stages; reinforcement reduces but does not erase risk."],
  ["Insurance", "The agreement says compensation for an insured loss follows the insurer and route rules, with exclusions that must be read before purchase."],
  ["Tracking", "The beginner guide says tracking information should be available within three days after dispatch; that is not a delivery-time guarantee."],
];

export default async function ShippingPage({ searchParams }: PageSearchParams) {
  const language = normalizeLanguage((await searchParams).lang);
  return <ContentLayout language={language} kicker="FULL GUIDE / SHIPPING" title="Plan the parcel, not only the product price." intro="PikoBuy separates item payment from international shipping. Destination, goods type, packed weight, dimensions, packaging, route rules and current fees belong in the decision." tone="lime">
    <section className="content-section prose-grid"><aside className="sticky-index"><span>PARCEL PLAN</span><a href="#before">01 · Before buying</a><a href="#warehouse">02 · Warehouse</a><a href="#estimate">03 · Estimate</a><a href="#route">04 · Live route</a><a href="#risk">05 · Risk</a><a href="#after">06 · After dispatch</a></aside><div className="prose-body">
      <article id="before"><span>01 / BEFORE BUYING</span><h2>Estimate the shape and restrictions of the parcel.</h2><p>Heavy, bulky, fragile, liquid, battery-powered or oddly shaped items can have fewer route options or a higher chargeable weight. A low item price does not cancel those constraints. Before building a haul around one product, record its approximate dimensions, weight, packaging needs and whether it belongs to a sensitive category.</p><p>PikoBuy’s user agreement makes the buyer responsible for understanding prohibited items and destination laws. It also warns that some liquids, powders, batteries, food, medicine and similar goods may face higher customs or delivery risk. A spreadsheet should flag these characteristics rather than hide them behind a cheap product price.</p><p>The agreement also states that cross-border transactions may create duties, taxes, brokerage fees or other costs for the user. Those amounts depend on the destination and shipment and cannot be responsibly converted into one universal percentage here. Check the destination’s current import rules and use PikoBuy support for route-specific questions before committing to goods that are expensive, regulated or difficult to return.</p><p>PikoBuy’s beginner flow separates the first product payment from later international shipping. That means an affordable order is not yet an affordable delivered purchase. Set a maximum landed budget before paying for the item, and reserve part of it for packing, freight, the live platform charge, destination costs and a contingency for changed measurements or routes.</p></article>
      <article id="warehouse"><span>02 / AT THE WAREHOUSE</span><h2>Use the inspection stage to reduce surprises.</h2><p>PikoBuy says transferred goods are unpacked, photographed and stored. The beginner guide says buyers can add requests such as minimal packaging or reinforced packaging. Those choices solve different problems: removing unnecessary packaging may reduce volume, while reinforcement may help protect fragile contents.</p><p>Do not apply one rule to every haul. Keeping a shoe box may protect shape but increase volume. Removing retail packaging may affect a return or collectible value. Glass and ceramics may justify extra protection even when the packed dimensions increase. Decide from the contents and route, not from a social-media slogan.</p><p>Before submitting the parcel, reconcile the warehouse inventory with what you intend to ship. Confirm the product count, visible condition and any accessories, then decide which items belong together. Consolidation can reduce duplicated outer packaging, but it can also create a larger or more complex parcel. PikoBuy does not publish one consolidation rule that is cheapest for every route.</p><p>Keep return timing separate from shipping preparation. The published return window can expire while a buyer waits for other products to arrive. Review each item when it becomes Warehoused; do not postpone a quality decision until the whole parcel is ready.</p></article>
      <article id="estimate"><span>03 / SHIPPING ESTIMATE</span><h2>Use the inputs PikoBuy actually asks for.</h2><p>The official shipping-cost page asks for destination country or region, product type, weight, length, width and height. That is the correct starting set for an estimate. It does not turn an estimate into a quote: the live parcel may have different packed measurements, available routes or restrictions when it is ready.</p><p>Our practical advice is to run a low and high case if you are still shopping. Use a realistic packed weight and dimensions, then repeat with a buffer for packaging. This is an independent planning method; PikoBuy does not publish a universal buffer percentage.</p><p>Do not insert a volumetric-weight formula from a social post into every comparison. Carriers and routes can use different billing rules and divisors, and the official public estimator does not publish a single universal formula on the page we checked. Enter all six requested inputs and read the live route result. If a route refers to actual, volumetric or chargeable weight, use that route’s own explanation.</p><p>When the estimate changes dramatically after a small dimension increase, investigate the packaging shape rather than assuming an error. Large, light goods can be sensitive to dimensional billing; dense goods may be governed mainly by scale weight. The useful action is to compare the packed parcel, not to force every item into the same rule.</p></article>
      <article id="route"><span>04 / ROUTE SELECTION</span><h2>Compare live options at parcel submission.</h2><p>The official guide says the buyer chooses a suitable route, submits the parcel and pays international shipping. It explicitly says routes differ in delivery time and pricing. Compare what is available for the actual destination and goods at that moment rather than copying a route recommendation from an older guide.</p><p>PikoBuy’s current user agreement states that the package-forwarding platform service fee is calculated at 8% of freight. The same wording notes that exchange-rate and settlement timing may create small differences. Verify the current agreement and checkout total before payment; this page is not a permanent price quote.</p><p>Compare more than the headline freight. Read the eligible product types, parcel limits, insurance terms, tracking method and any destination conditions shown for the route. A cheaper option is not equivalent when it excludes the actual contents or leaves a risk you are unwilling to carry. Likewise, a faster estimate is not a delivery guarantee when customs, weather, capacity or other uncontrollable events intervene.</p><p>Verify the recipient name, address, postcode and contact information before generating the shipping label. The user agreement puts responsibility on users to provide accurate and current shipping information and warns that an overseas return caused by no recipient, an incorrect address or failed delivery can create a redelivery cost.</p></article>
      <article id="risk"><span>05 / LOGISTICS RISK</span><h2>Third-party carriage changes the risk boundary.</h2><p>The shipping policy says PikoBuy integrates third-party international logistics providers and identifies customs policy, confiscation, damage, loss and peak-period delay as cross-border risks. The user agreement says PikoBuy may assist as a communication agent for a claim, while compensation follows the relevant logistics provider or insurance rules.</p><p>Insurance is not a magic guarantee. The agreement says insured loss compensation depends on the insured value and the insurer’s exclusions; prohibited items and certain causes may remain outside coverage. Read the actual route insurance terms before paying.</p></article>
      <article id="after"><span>06 / AFTER DISPATCH</span><h2>Tracking availability is not delivery time.</h2><p>PikoBuy’s beginner guide says tracking information will be available within three days after the parcel ships. That published expectation concerns the appearance of tracking, not arrival at the destination. Keep the parcel record, route, declared address and any insurance details. Inspect the outer package when receiving it and document visible damage promptly.</p><p>If tracking is not yet visible, first distinguish “label or handover data has not appeared” from “the parcel is late.” Do not invent a delivery deadline from the three-day tracking statement. Use the parcel page and route support channel, and preserve screenshots when a status or address needs investigation.</p><p>At delivery, examine the outer packaging before or while signing when local practice allows. Photograph crushing, tears, moisture, resealing or other visible damage and keep the packaging until the claim path is clear. The user agreement says compensation for logistics problems follows the third-party provider and any insurance rules, so timely evidence can matter even though it does not guarantee a successful claim.</p></article>
      <SourceNote><a href="https://www.pikobuy.com/shipping-cost" target="_blank" rel="noopener noreferrer">PikoBuy Shipping Estimate</a>, <a href="https://www.pikobuy.com/protocol/shipping" target="_blank" rel="noopener noreferrer">Shipping Policy</a>, <a href="https://www.pikobuy.com/guide" target="_blank" rel="noopener noreferrer">Beginner’s Guide</a> and <a href="https://www.pikobuy.com/protocol/user" target="_blank" rel="noopener noreferrer">User Agreement</a>, checked 06 August 2026.</SourceNote>
    </div></section>

    <section className="content-section">
      <div className="content-section-heading"><div><span>OFFICIAL ESTIMATOR</span><h2>Six fields before you compare routes.</h2></div><p>PikoBuy&apos;s current calculator asks for destination, product type, weight, length, width and height. These cards explain what each field means, what to enter and which shortcut usually makes the estimate misleading.</p></div>
      <div className="evidence-table estimator-grid clickable-estimator-grid">{estimatorInputs.map((input, index) => <article key={input.title}><a className="evidence-card-link" href="https://www.pikobuy.com/shipping-cost" target="_blank" rel="noopener noreferrer" aria-label={`Open PikoBuy's live shipping estimator for the ${input.title} field`}><span>{String(index + 1).padStart(2, "0")} · {input.field}</span><h3>{input.title}</h3><dl><div><dt>OFFICIAL FIELD</dt><dd>{input.official}</dd></div><div><dt>ENTER</dt><dd>{input.action}</dd></div><div><dt>AVOID</dt><dd>{input.mistake}</dd></div></dl><b className="card-destination">Use this field in the live estimator ↗</b></a></article>)}</div>
      <a className="big-source-link" href="https://www.pikobuy.com/shipping-cost" target="_blank" rel="noopener noreferrer">Open PikoBuy’s live shipping estimator ↗</a>
    </section>

    <section className="content-section guide-product-section">
      <div className="content-section-heading"><div><span>PRODUCT-TO-PARCEL CHECK</span><h2>Test the shipping plan against real products.</h2></div><p>A product page supplies the starting item and source price, not a delivered-cost promise. Open the exact FindSpreadsheet row, then check product type, likely packed shape, packaging decision and route eligibility in PikoBuy&apos;s live tools.</p></div>
      <ProductShowcase />
      <p className="guide-product-note">Every card opens its exact FindSpreadsheet product detail page. USD references use the verified CNY source price and the 06 August 2026 reference rate of 1 CNY = $0.14817; freight, options, exchange rates and checkout totals can change.</p>
    </section>

    <section className="content-section">
      <div className="content-section-heading"><span>RISK REGISTER</span><h2>What should stay visible before dispatch.</h2><p>These are not reasons to assume failure. They are the boundaries the official policies ask the buyer to evaluate.</p></div>
      <div className="evidence-table">{riskRows.map(([title, copy], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{copy}</p></article>)}</div>
    </section>
  </ContentLayout>;
}
