const navLabels=['Home','Categories','Product details','SEO articles','FAQ'];
const languages={en:'English',de:'Deutsch',fr:'Français',es:'Español',it:'Italiano',nl:'Nederlands',pl:'Polski',sv:'Svenska',fi:'Suomi'};
const categories={shoes:['Shoes','Compare pairs by shape, outsole, listed sizing and images before you open a product.','https://findspreadsheet.com/shoes/','⌁'],sneakers:['Sneakers','Search the dedicated shoe category for sneakers, trainers and slides.','https://findspreadsheet.com/shoes/','⌁'],shirts:['Shirts','Compare T-shirt listings by material, measurements, print and current product photos.','https://findspreadsheet.com/t-shirts/','◫'],hoodies:['Hoodies','Review fabric, print placement, sleeve length and sizing before continuing.','https://findspreadsheet.com/hoodies-sweaters/','◈'],jackets:['Jackets','Compare outerwear material, lining, bulk and visible construction details.','https://findspreadsheet.com/jackets/','⌂'],pants:['Pants','Check waist, inseam, cut and material notes in the pants and shorts category.','https://findspreadsheet.com/pants-shorts/','║'],bags:['Bags','Search current bag finds inside the main database before reviewing the active listing.','https://findspreadsheet.com/search.html?channelid=2&keywords=bags','□'],shorts:['Shorts','Open the dedicated pants and shorts category to compare current product rows.','https://findspreadsheet.com/pants-shorts/','╚'],accessories:['Accessories','Compare dimensions, finish and close-up images from the accessories category.','https://findspreadsheet.com/accessories/','⊏'],jewelry:['Jewelry','Search jewelry inside the current accessories database and check visible details.','https://findspreadsheet.com/search.html?channelid=2&keywords=jewelry','◇'],watches:['Watches','Search current watch product rows in the main database before opening a listing.','https://findspreadsheet.com/search.html?channelid=2&keywords=watches','◉'],sweaters:['Sweaters','Use the hoodies and sweaters category for knit texture, fit and material checks.','https://findspreadsheet.com/hoodies-sweaters/','▱']};
let requestedLanguage=localStorage.pbfLang||'en';
let translating=false;
let queuedLanguage=null;
function escapeHTML(value){return value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function getTextNodes(){const blocked=new Set(['SCRIPT','STYLE','OPTION','TEXTAREA','CODE','PRE']);const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode(node){const parent=node.parentElement;if(!parent||blocked.has(parent.tagName)||parent.closest('[data-no-translate]'))return NodeFilter.FILTER_REJECT;return node.nodeValue.trim()?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT}});const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);return nodes}
function sourceFor(node){if(!node.__pbfSource)node.__pbfSource=node.nodeValue;return node.__pbfSource}
function fingerprint(nodes){let hash=5381;nodes.forEach(node=>{const text=sourceFor(node);for(let i=0;i<text.length;i++)hash=((hash<<5)+hash)^text.charCodeAt(i)});return nodes.length+'-'+(hash>>>0)}
function cacheKey(target){return 'pbf.lang.cache.'+location.pathname+'.'+target}
function readCache(nodes,target){try{const cached=JSON.parse(localStorage.getItem(cacheKey(target)));if(!cached||cached.fingerprint!==fingerprint(nodes)||cached.text.length!==nodes.length)return false;nodes.forEach((node,index)=>node.nodeValue=cached.text[index]);return true}catch{return false}}
function saveCache(nodes,target){try{localStorage.setItem(cacheKey(target),JSON.stringify({fingerprint:fingerprint(nodes),text:nodes.map(node=>node.nodeValue)}))}catch{}}
function createChunks(nodes){const chunks=[];let current=[];let size=0;nodes.forEach(node=>{const source=sourceFor(node);const projected=size+source.length+42;if(current.length&&projected>3600){chunks.push(current);current=[];size=0}current.push({node,source});size+=source.length+42});if(current.length)chunks.push(current);return chunks}
async function translateChunk(chunk,target){const payload=chunk.map((item,index)=>'<span data-pbf-node="'+index+'">'+escapeHTML(item.source)+'</span>').join('');const url='https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl='+encodeURIComponent(target)+'&dt=t&q='+encodeURIComponent(payload);const response=await fetch(url,{credentials:'omit'});if(!response.ok)throw new Error('translation request failed');const data=await response.json();const translatedHTML=data[0].map(part=>part[0]).join('');const box=document.createElement('div');box.innerHTML=translatedHTML;chunk.forEach((item,index)=>{const translated=box.querySelector('[data-pbf-node="'+index+'"]');if(translated&&translated.textContent.trim())item.node.nodeValue=translated.textContent})}
function restoreEnglish(){getTextNodes().forEach(node=>{if(node.__pbfSource)node.nodeValue=node.__pbfSource});document.documentElement.lang='en'}
function setBusy(active){document.documentElement.classList.toggle('translating',active)}
async function translateWholePage(target){if(translating){queuedLanguage=target;return}if(target==='en'){restoreEnglish();return}translating=true;setBusy(true);restoreEnglish();const nodes=getTextNodes();try{if(!readCache(nodes,target)){const chunks=createChunks(nodes);await Promise.all(chunks.map(chunk=>translateChunk(chunk,target)));saveCache(nodes,target)}document.documentElement.lang=target}catch(error){restoreEnglish();requestedLanguage='en';localStorage.pbfLang='en';const select=document.querySelector('#lang');if(select)select.value='en'}finally{translating=false;setBusy(false);if(queuedLanguage&&queuedLanguage!==target){const next=queuedLanguage;queuedLanguage=null;translateWholePage(next)}else queuedLanguage=null}}
function selectLanguage(code){requestedLanguage=code;localStorage.pbfLang=code;translateWholePage(code)}
function foldLongArticlesOnMobile(){if(!window.matchMedia('(max-width:600px)').matches)return;document.querySelectorAll('.prose').forEach(article=>{if(article.dataset.folded)return;article.dataset.folded='true';let section=null;[...article.children].forEach(node=>{if(node.tagName==='H2'){section=document.createElement('details');section.className='mobile-article-fold';const summary=document.createElement('summary');summary.textContent=node.textContent;section.appendChild(summary);node.replaceWith(section);return}if(section&&node.tagName!=='ASIDE')section.appendChild(node)})})}
function setup(n){const select=document.querySelector('#lang');if(!select)return;select.innerHTML='';Object.entries(languages).forEach(([code,label])=>select.add(new Option(label,code)));select.value=requestedLanguage;document.querySelectorAll('[data-nav]').forEach((link,index)=>{link.textContent=navLabels[index];if(index===n)link.classList.add('active')});select.onchange=()=>selectLanguage(select.value);foldLongArticlesOnMobile();if(requestedLanguage!=='en')window.addEventListener('load',()=>setTimeout(()=>translateWholePage(requestedLanguage),80),{once:true})}
function search(e){e.preventDefault();const q=document.querySelector('#q').value.trim();if(!q)return location.href='https://findspreadsheet.com/';const key=q.toLowerCase().replace(/[^a-z]/g,'');const hit=Object.entries(categories).find(([k])=>key.includes(k)||k.includes(key));location.href=hit?hit[1][2]:'https://findspreadsheet.com/search.html?channelid=2&keywords='+encodeURIComponent(q)}
