/* Static editions: all text is supplied in this file; no translation service is used. */
(()=>{
const codes=['en','de','fr','es','it','pt','nl','pl'],key='joy-sheet-static-language';let syncing=false;
const nav={en:['Language','Home','Categories','Product detail','SEO articles','QC','FAQ'],de:['Sprache','Startseite','Kategorien','Produktdetails','SEO-Artikel','QC','FAQ'],fr:['Langue','Accueil','Catégories','Détails produit','Articles SEO','QC','FAQ'],es:['Idioma','Inicio','Categorías','Detalle del producto','Artículos SEO','QC','Preguntas frecuentes'],it:['Lingua','Home','Categorie','Dettaglio prodotto','Articoli SEO','QC','FAQ'],pt:['Idioma','Início','Categorias','Detalhes do produto','Artigos SEO','QC','Perguntas frequentes'],nl:['Taal','Home','Categorieën','Productdetails','SEO-artikelen','QC','Veelgestelde vragen'],pl:['Język','Strona główna','Kategorie','Szczegóły produktu','Artykuły SEO','QC','FAQ']};
const N={en:'Shoes|T-Shirts|Hoodies|Jackets|Pants & Shorts|Bags|Accessories|Headwear|Electronics|Jerseys',de:'Schuhe|T-Shirts|Hoodies|Jacken|Hosen & Shorts|Taschen|Accessoires|Kopfbedeckung|Elektronik|Trikots',fr:'Chaussures|T-shirts|Sweats à capuche|Vestes|Pantalons & shorts|Sacs|Accessoires|Couvre-chefs|Électronique|Maillots',es:'Zapatos|Camisetas|Sudaderas|Chaquetas|Pantalones y shorts|Bolsos|Accesorios|Sombreros|Electrónica|Camisetas deportivas',it:'Scarpe|T-shirt|Felpe|Giacche|Pantaloni e shorts|Borse|Accessori|Copricapi|Elettronica|Maglie',pt:'Sapatos|Camisetas|Moletons|Jaquetas|Calças e shorts|Bolsas|Acessórios|Chapéus|Eletrônicos|Camisetas esportivas',nl:'Schoenen|T-shirts|Hoodies|Jassen|Broeken & shorts|Tassen|Accessoires|Hoofddeksels|Elektronica|Shirts',pl:'Buty|T-shirty|Bluzy z kapturem|Kurtki|Spodnie i szorty|Torby|Akcesoria|Nakrycia głowy|Elektronika|Koszulki sportowe'};
const L={
en:{cat:'Browse by fashion direction.|Choose a category to open its corresponding live page on FindSpreadsheet.',prod:'Ten current product records.|Scroll through ten different high-resolution product records. Every card opens the matching live detail page on FindSpreadsheet.',qc:'Read the photos. Then decide.|QC photos are reference material after warehouse arrival, not a guarantee of final product condition, eligibility, or shipping outcome.',faq:'Clear boundaries. Better decisions.',seo:'JoyaGoo workflow: what to check, when.',note:'Independent research note. Check the current JoyaGoo terms before acting. Public guidance describes QC photos after warehouse arrival, a 5-day (120-hour) eligible request window after QC Completed, 90 free storage days from Stored, a separate submitted-parcel storage period, and destination-dependent shipping calculated from actual or estimated weight. These are planning facts, not a promise of quality, seller conduct, customs clearance or delivery.'},
de:{cat:'Nach Modestil suchen.|Wähle eine Kategorie, um die passende aktuelle Seite auf FindSpreadsheet zu öffnen.',prod:'Zehn aktuelle Produktdatensätze.|Durchsuche zehn hochauflösende Produktdatensätze; jede Karte öffnet die passende Detailseite auf FindSpreadsheet.',qc:'Fotos prüfen. Dann entscheiden.|QC-Fotos sind Referenzmaterial nach Wareneingang, keine Garantie für Zustand, Anspruch oder Versandresultat.',faq:'Klare Grenzen. Bessere Entscheidungen.',seo:'JoyaGoo-Ablauf: was wann zu prüfen ist.',note:'Unabhängiger Recherchehinweis. Prüfe die aktuellen JoyaGoo-Bedingungen vor einer Handlung. Öffentliche Hinweise nennen QC-Fotos nach Lagerzugang, ein mögliches berechtigtes 5-Tage- bzw. 120-Stunden-Fenster nach QC Completed, 90 kostenlose Lagertage ab Stored, eine getrennte Frist für eingereichte Pakete und zielabhängige Versandkosten nach tatsächlichem oder geschätztem Gewicht. Das sind Planungsfakten, keine Zusage zu Qualität, Verkäuferverhalten, Zoll oder Zustellung.'},
fr:{cat:'Explorer par direction mode.|Choisissez une catégorie pour ouvrir la page actuelle correspondante sur FindSpreadsheet.',prod:'Dix fiches produit actuelles.|Faites défiler dix fiches haute définition ; chaque carte ouvre la page correspondante sur FindSpreadsheet.',qc:'Lire les photos. Puis décider.|Les photos QC sont des références après l’arrivée en entrepôt, et non une garantie de l’état final ou de l’expédition.',faq:'Des limites claires. De meilleures décisions.',seo:'Parcours JoyaGoo : quoi vérifier, et quand.',note:'Note de recherche indépendante. Vérifiez les conditions JoyaGoo actuelles avant d’agir. Les informations publiques évoquent des photos QC après arrivée, une fenêtre de demande éligible de 5 jours ou 120 heures après QC Completed, 90 jours de stockage gratuit à partir de Stored, une période distincte pour un colis soumis et des frais selon le pays et le poids réel ou estimé. Ce sont des éléments de planification, non une promesse de qualité, de vendeur, de douane ou de livraison.'},
es:{cat:'Explora por dirección de moda.|Elige una categoría para abrir su página actual correspondiente en FindSpreadsheet.',prod:'Diez registros de producto actuales.|Desplázate por diez registros de producto distintos en alta resolución. Cada tarjeta abre la ficha actual correspondiente en FindSpreadsheet.',qc:'Lee las fotos. Después decide.|Las fotos de QC son material de referencia tras la llegada al almacén; no garantizan el estado final, la elegibilidad ni el resultado del envío.',faq:'Límites claros. Mejores decisiones.',seo:'Flujo de JoyaGoo: qué revisar y cuándo.',note:'Nota de investigación independiente. Consulta los términos actuales de JoyaGoo antes de actuar. La guía pública describe fotos de QC tras llegar al almacén, una ventana elegible de 5 días o 120 horas después de QC Completed, 90 días de almacenamiento gratis desde Stored, un plazo independiente para un paquete enviado y tarifas por destino y peso real o estimado. Son datos de planificación, no una promesa de calidad, vendedor, aduanas o entrega.'},
it:{cat:'Sfoglia per direzione moda.|Scegli una categoria per aprire la pagina attuale corrispondente su FindSpreadsheet.',prod:'Dieci record prodotto attuali.|Scorri dieci record ad alta risoluzione; ogni scheda apre la pagina corrispondente su FindSpreadsheet.',qc:'Leggi le foto. Poi decidi.|Le foto QC sono materiale di riferimento dopo l’arrivo in magazzino, non una garanzia di condizione finale o spedizione.',faq:'Confini chiari. Decisioni migliori.',seo:'Flusso JoyaGoo: cosa controllare e quando.',note:'Nota di ricerca indipendente. Verifica i termini JoyaGoo aggiornati prima di agire. Le indicazioni pubbliche citano foto QC dopo l’arrivo, una finestra di richiesta idonea di 5 giorni o 120 ore dopo QC Completed, 90 giorni gratuiti da Stored, una scadenza separata per il pacco inviato e costi dipendenti da destinazione e peso reale o stimato. Sono dati di pianificazione, non una promessa su qualità, venditore, dogana o consegna.'},
pt:{cat:'Navegue por direção de moda.|Escolha uma categoria para abrir a página atual correspondente no FindSpreadsheet.',prod:'Dez registros de produto atuais.|Percorra dez registros em alta resolução; cada cartão abre a página correspondente no FindSpreadsheet.',qc:'Leia as fotos. Depois decida.|As fotos de QC são referência após a chegada ao armazém, não garantia de condição final ou envio.',faq:'Limites claros. Decisões melhores.',seo:'Fluxo da JoyaGoo: o que verificar e quando.',note:'Nota de pesquisa independente. Confira os termos atuais da JoyaGoo antes de agir. As informações públicas citam fotos de QC após a chegada, janela elegível de 5 dias ou 120 horas após QC Completed, 90 dias gratuitos desde Stored, prazo separado para pacote enviado e taxas por destino e peso real ou estimado. São dados para planejar, não promessa de qualidade, vendedor, alfândega ou entrega.'},
nl:{cat:'Blader op moderichting.|Kies een categorie om de overeenkomstige actuele pagina op FindSpreadsheet te openen.',prod:'Tien actuele productrecords.|Blader door tien records in hoge resolutie; elke kaart opent de bijbehorende pagina op FindSpreadsheet.',qc:'Lees de foto’s. Beslis daarna.|QC-foto’s zijn referentiemateriaal na aankomst in het magazijn, geen garantie voor eindconditie of verzending.',faq:'Duidelijke grenzen. Betere beslissingen.',seo:'JoyaGoo-proces: wat wanneer te controleren.',note:'Onafhankelijke onderzoeksnotitie. Controleer actuele JoyaGoo-voorwaarden voordat je handelt. Openbare informatie noemt QC-foto’s na aankomst, een mogelijk geschikt venster van 5 dagen of 120 uur na QC Completed, 90 gratis opslagdagen vanaf Stored, een aparte termijn voor een ingediend pakket en kosten per bestemming en werkelijk of geschat gewicht. Dit zijn planningsfeiten, geen belofte over kwaliteit, verkoper, douane of bezorging.'},
pl:{cat:'Przeglądaj według kierunku mody.|Wybierz kategorię, aby otworzyć odpowiadającą jej aktualną stronę w FindSpreadsheet.',prod:'Dziesięć aktualnych rekordów produktów.|Przewiń dziesięć rekordów wysokiej rozdzielczości; każda karta otwiera odpowiednią stronę w FindSpreadsheet.',qc:'Przeczytaj zdjęcia. Potem zdecyduj.|Zdjęcia QC są materiałem referencyjnym po przybyciu do magazynu, a nie gwarancją stanu końcowego ani wysyłki.',faq:'Jasne granice. Lepsze decyzje.',seo:'Proces JoyaGoo: co i kiedy sprawdzać.',note:'Niezależna notatka badawcza. Przed działaniem sprawdź aktualne warunki JoyaGoo. Publiczne informacje wskazują zdjęcia QC po przybyciu, możliwe kwalifikujące się pięć dni lub 120 godzin po QC Completed, 90 bezpłatnych dni przechowywania od Stored, osobny termin dla zgłoszonej paczki oraz opłaty zależne od kraju i wagi rzeczywistej lub szacowanej. To fakty do planowania, nie obietnica jakości, sprzedawcy, odprawy ani dostawy.'}
};
function split(s){return s.split('|')} function el(s){return document.querySelector(s)} function put(e,v,html=false){if(e){html?e.innerHTML=v:e.textContent=v}} function title(s){let i=s.indexOf('. ');return i<0?s:s.slice(0,i+1)+'<br><em>'+s.slice(i+2)+'</em>'}
function links(lang){document.querySelectorAll('header nav a,main a[href^="."]').forEach(a=>{const u=new URL(a.href,location.href);if(u.origin!==location.origin)return;lang==='en'?u.searchParams.delete('lang'):u.searchParams.set('lang',lang);a.href=u.pathname+u.search+u.hash})}
function listText(lang){return lang==='en'?['Compare shape, colour and visible construction to the current listing.','Ask for measurable details when sizing or placement matters.','Review the platform’s current request period and item conditions before taking action.','Open current QC references on FindSpreadsheet ↗']:Array(4).fill(L[lang].note)}
function renderHome(lang){const select=document.getElementById('language');if(!select)return;select.value=lang;syncing=true;select.dispatchEvent(new Event('change'));syncing=false;split(N[lang]).forEach((v,i)=>put(document.querySelectorAll('.home-category span')[i],v));document.querySelectorAll('.quick-grid strong').forEach((e,i)=>put(e,nav[lang][i+1]));document.querySelectorAll('.quick-grid span').forEach((e,i)=>put(e,nav[lang][i+1]+' ↗'))}
function render(lang){const d=L[lang],p=location.pathname;document.documentElement.lang=lang;document.querySelectorAll('.language span').forEach(e=>put(e,nav[lang][0]));document.querySelectorAll('.language select').forEach(e=>e.value=lang);document.querySelectorAll('header nav a').forEach((e,i)=>put(e,nav[lang][i+1]));links(lang);
 if(!/categories|product-detail|seo-articles|\/qc|\/faq/.test(p)){renderHome(lang);return}
 if(lang==='en')return;
 if(p.includes('categories')){const a=split(d.cat);put(el('.category-page h1'),title(a[0]),true);put(el('.category-page>p:not(.eyebrow)'),a[1]);split(N[lang]).forEach((v,i)=>put(document.querySelectorAll('.category-tile strong')[i],v));document.querySelectorAll('.category-tile small').forEach(e=>put(e,nav[lang][2].toUpperCase()+' ↗'))}
 if(p.includes('product-detail')){const a=split(d.prod);put(el('.detail-intro h1'),title(a[0]),true);put(el('.detail-intro p:last-child'),a[1]);document.querySelectorAll('.product-index').forEach((e,i)=>put(e,String(i+1).padStart(2,'0')+' / '+split(N[lang])[i]));document.querySelectorAll('.product-copy>p:not(.product-index)').forEach(e=>put(e,d.note));document.querySelectorAll('.open-detail').forEach(e=>put(e,nav[lang][3].toUpperCase()+' ↗'))}
 if(p.includes('/qc')){const a=split(d.qc);put(el('.detail h1'),title(a[0]),true);put(el('.detail>div p:last-child'),a[1]);listText(lang).forEach((v,i)=>put(document.querySelectorAll('.detail ol span')[i],v))}
 if(p.includes('/faq')){put(el('.faq>h1'),title(d.faq),true);document.querySelectorAll('.faq-item').forEach((x,i)=>{put(x.querySelector('summary'),nav[lang][6]+' '+String(i+1));put(x.querySelector('p'),d.note)})}
 if(p.includes('seo-articles')){put(el('.journal>h1'),title(d.seo),true);document.querySelectorAll('.journal .article h2').forEach((e,i)=>put(e,(i+1)+'. '+d.seo));document.querySelectorAll('.journal .article>p').forEach(e=>put(e,d.note))}
}
function choose(lang){if(!codes.includes(lang))lang='en';localStorage.setItem(key,lang);const u=new URL(location.href);lang==='en'?u.searchParams.delete('lang'):u.searchParams.set('lang',lang);history.replaceState(null,'',u);render(lang)}
document.addEventListener('DOMContentLoaded',()=>{const q=new URLSearchParams(location.search).get('lang');const lang=codes.includes(q)?q:(codes.includes(localStorage.getItem(key))?localStorage.getItem(key):'en');document.querySelectorAll('.language select').forEach(e=>e.addEventListener('change',x=>{if(!syncing)choose(x.target.value)}));render(lang)});
})();
