import type { Locale } from "./site-i18n";

export type ToolId = "find-system" | "shipping-calculator";

type ToolCopy = {
  tools: string;
  home: string;
  categories: string;
  articles: string;
  searchLabel: string;
  searchPlaceholder: string;
  searchButton: string;
  shippingLabel: string;
  shippingTitle: string;
  shippingLead: string;
  destination: string;
  parcel: string;
  planButton: string;
  planTitle: string;
  planEmpty: string;
  findTitle: string;
  findLead: string;
  findSteps: readonly [string, string][];
  shippingSteps: readonly [string, string][];
  related: string;
  shoes: string;
  hoodies: string;
  accessories: string;
  openDatabase: string;
  accessoriesTitle: string;
  accessoriesLead: string;
  accessoriesGroups: readonly [string, string][];
};

const en: ToolCopy = {
  tools: "Research tools", home: "Home", categories: "Categories", articles: "SEO articles", searchLabel: "Find system", searchPlaceholder: "Search a brand, item, or category", searchButton: "Search FindSpreadsheet",
  shippingLabel: "Shipping planner", shippingTitle: "LoloBuy shipping estimate planner", shippingLead: "Prepare the details that affect a live parcel estimate before you compare delivery options. This page does not quote a price or promise a route.", destination: "Delivery country", parcel: "Items ready for a parcel", planButton: "Build my checklist", planTitle: "Your parcel-research checklist", planEmpty: "Add a destination and the number of items to create a planning checklist.",
  findTitle: "LoloBuy find system: compare before you search", findLead: "Use one clear research path: save the listing, compare the variation and measurements, then search the destination database with the terms you verified.",
  findSteps: [["Save the exact listing", "Keep the product link, chosen variation, visible measurements and seller notes together. A title alone is not enough to compare two listings."], ["Compare like with like", "Check the same colour, size or version across listings. Separate the item price from any later warehouse or parcel choices."], ["Search with the facts", "Use the saved product name, model or category in FindSpreadsheet. Recheck the live listing before any purchase decision."]],
  shippingSteps: [["Start with destination", "Available routes and restrictions are destination-sensitive, so name the country before comparing parcel options."], ["Record the parcel inputs", "Write down how many items are ready, which are still pending, and any details that may affect the parcel's size or handling."], ["Compare the live estimate", "A freight estimate is not a final price. Review the current parcel, available line and destination before submission."]],
  related: "Continue your research", shoes: "Shoes research", hoodies: "Hoodies research", accessories: "Accessories research", openDatabase: "Open FindSpreadsheet", accessoriesTitle: "LoloBuy accessories spreadsheet: research by item type", accessoriesLead: "A practical cluster for bags, watches and electronics. Compare the details that matter for each item type before moving to a database search.", accessoriesGroups: [["Bags", "Check material, capacity, hardware and the selected colour or size before comparing listings."], ["Watches", "Compare the visible specifications, images and seller notes; do not infer performance from a listing photo."], ["Electronics", "Check model, compatibility, condition and plug or regional details before searching."]]
};

const localized: Record<Exclude<Locale, "en">, ToolCopy> = {
  fr: { ...en, tools:"Outils de recherche", home:"Accueil", categories:"Catégories", articles:"Articles SEO", searchLabel:"Système de recherche", searchPlaceholder:"Rechercher une marque, un article ou une catégorie", searchButton:"Rechercher sur FindSpreadsheet", shippingLabel:"Planificateur d’expédition", shippingTitle:"Planificateur d’estimation d’expédition LoloBuy", shippingLead:"Préparez les informations qui influencent une estimation de colis en direct avant de comparer les options. Cette page ne donne ni prix ni promesse de trajet.", destination:"Pays de livraison", parcel:"Articles prêts pour un colis", planButton:"Créer ma liste", planTitle:"Votre liste de préparation du colis", planEmpty:"Ajoutez une destination et le nombre d’articles pour créer une liste de préparation.", findTitle:"Système de recherche LoloBuy : comparer avant de chercher", findLead:"Suivez une méthode claire : enregistrez l’annonce, comparez la variante et les mesures, puis cherchez avec les termes vérifiés.", findSteps:[["Enregistrez l’annonce exacte","Conservez le lien, la variante choisie, les mesures visibles et les notes du vendeur. Un titre seul ne suffit pas."],["Comparez des éléments comparables","Vérifiez la même couleur, taille ou version. Distinguez le prix de l’article des choix ultérieurs."],["Cherchez avec les faits","Utilisez le nom, le modèle ou la catégorie enregistrés dans FindSpreadsheet et revérifiez l’annonce en direct."]], shippingSteps:[["Commencez par la destination","Les lignes et restrictions dépendent du pays ; indiquez-le avant de comparer les options."],["Notez les données du colis","Inscrivez les articles prêts, ceux en attente et les détails pouvant influencer la taille ou le traitement."],["Comparez l’estimation en direct","Une estimation n’est pas un prix final. Vérifiez le colis, la ligne disponible et la destination avant soumission."]], related:"Poursuivez votre recherche", shoes:"Recherche chaussures", hoodies:"Recherche sweats", accessories:"Recherche accessoires", openDatabase:"Ouvrir FindSpreadsheet", accessoriesTitle:"Tableau accessoires LoloBuy : recherche par type d’article", accessoriesLead:"Un cluster pratique pour sacs, montres et électronique. Comparez les détails utiles avant une recherche dans la base.", accessoriesGroups:[["Sacs","Vérifiez matière, capacité, quincaillerie et couleur ou taille choisie."],["Montres","Comparez spécifications visibles, images et notes du vendeur sans déduire la performance d’une photo."],["Électronique","Vérifiez modèle, compatibilité, état et détails de prise ou région avant de chercher."]]},
  de: { ...en, tools:"Recherchewerkzeuge", home:"Startseite", categories:"Kategorien", articles:"SEO-Artikel", searchLabel:"Findesystem", searchPlaceholder:"Marke, Artikel oder Kategorie suchen", searchButton:"FindSpreadsheet durchsuchen", shippingLabel:"Versandplaner", shippingTitle:"LoloBuy Versand-Schätzplaner", shippingLead:"Bereiten Sie die Angaben vor, die eine Live-Paketschätzung beeinflussen. Diese Seite nennt keinen Preis und verspricht keine Route.", destination:"Lieferland", parcel:"Paketbereite Artikel", planButton:"Checkliste erstellen", planTitle:"Ihre Paket-Checkliste", planEmpty:"Fügen Sie Zielort und Artikelanzahl hinzu, um eine Checkliste zu erstellen.", findTitle:"LoloBuy Findesystem: vor der Suche vergleichen", findLead:"Nutzen Sie einen klaren Weg: Listing speichern, Variante und Maße vergleichen und dann mit geprüften Begriffen suchen.", findSteps:[["Genaues Listing speichern","Bewahren Sie Link, gewählte Variante, sichtbare Maße und Verkäuferhinweise zusammen auf."],["Vergleichbares vergleichen","Prüfen Sie dieselbe Farbe, Größe oder Version und trennen Sie Artikelpreis von späteren Paketoptionen."],["Mit Fakten suchen","Nutzen Sie Produktname, Modell oder Kategorie in FindSpreadsheet und prüfen Sie das Live-Listing erneut."]], shippingSteps:[["Mit dem Zielort beginnen","Linien und Einschränkungen sind zielortabhängig; nennen Sie zuerst das Land."],["Paketdaten notieren","Notieren Sie fertige und ausstehende Artikel sowie Angaben zu Größe oder Behandlung."],["Live-Schätzung vergleichen","Eine Schätzung ist kein Endpreis. Prüfen Sie Paket, verfügbare Linie und Ziel vor der Einreichung."]], related:"Recherche fortsetzen", shoes:"Schuhrecherche", hoodies:"Hoodie-Recherche", accessories:"Accessoire-Recherche", openDatabase:"FindSpreadsheet öffnen", accessoriesTitle:"LoloBuy Accessoire-Spreadsheet: Recherche nach Artikeltyp", accessoriesLead:"Ein praktischer Cluster für Taschen, Uhren und Elektronik. Vergleichen Sie relevante Details vor der Datenbanksuche.", accessoriesGroups:[["Taschen","Prüfen Sie Material, Kapazität, Beschläge sowie gewählte Farbe oder Größe."],["Uhren","Vergleichen Sie sichtbare Daten, Bilder und Verkäuferhinweise; leiten Sie Leistung nicht aus einem Bild ab."],["Elektronik","Prüfen Sie Modell, Kompatibilität, Zustand und Stecker- oder Regionaldetails."]]},
  es: { ...en, tools:"Herramientas de investigación", home:"Inicio", categories:"Categorías", articles:"Artículos SEO", searchLabel:"Sistema de búsqueda", searchPlaceholder:"Buscar marca, producto o categoría", searchButton:"Buscar en FindSpreadsheet", shippingLabel:"Planificador de envío", shippingTitle:"Planificador de estimación de envío LoloBuy", shippingLead:"Prepara los datos que afectan una estimación de paquete en directo antes de comparar opciones. Esta página no cotiza un precio ni promete una ruta.", destination:"País de entrega", parcel:"Artículos listos para paquete", planButton:"Crear mi lista", planTitle:"Tu lista de investigación del paquete", planEmpty:"Añade destino y número de artículos para crear una lista.", findTitle:"Sistema de búsqueda LoloBuy: compara antes de buscar", findLead:"Usa un camino claro: guarda el anuncio, compara variante y medidas y luego busca con términos verificados.", findSteps:[["Guarda el anuncio exacto","Conserva el enlace, variante, medidas visibles y notas del vendedor juntos."],["Compara lo equivalente","Revisa el mismo color, talla o versión y separa el precio del artículo de decisiones posteriores."],["Busca con los hechos","Usa nombre, modelo o categoría guardados en FindSpreadsheet y revisa el anuncio en directo."]], shippingSteps:[["Empieza por el destino","Las rutas y restricciones dependen del destino; indica el país primero."],["Registra los datos del paquete","Anota artículos listos, pendientes y detalles que puedan afectar tamaño o manejo."],["Compara la estimación en directo","Una estimación no es precio final. Revisa paquete, línea disponible y destino antes de enviar."]], related:"Continúa la investigación", shoes:"Investigación de calzado", hoodies:"Investigación de sudaderas", accessories:"Investigación de accesorios", openDatabase:"Abrir FindSpreadsheet", accessoriesTitle:"Spreadsheet de accesorios LoloBuy: investigación por tipo", accessoriesLead:"Un grupo práctico para bolsos, relojes y electrónica. Compara detalles relevantes antes de buscar en la base.", accessoriesGroups:[["Bolsos","Revisa material, capacidad, herrajes y color o talla seleccionados."],["Relojes","Compara especificaciones visibles, imágenes y notas del vendedor; no deduzcas rendimiento de una foto."],["Electrónica","Revisa modelo, compatibilidad, estado y detalles regionales o de enchufe."]]},
  it: { ...en, tools:"Strumenti di ricerca", home:"Home", categories:"Categorie", articles:"Articoli SEO", searchLabel:"Sistema di ricerca", searchPlaceholder:"Cerca marchio, articolo o categoria", searchButton:"Cerca su FindSpreadsheet", shippingLabel:"Pianificatore spedizione", shippingTitle:"Pianificatore stima spedizione LoloBuy", shippingLead:"Prepara i dati che incidono su una stima del pacco in tempo reale prima di confrontare le opzioni. Questa pagina non quota un prezzo né promette una rotta.", destination:"Paese di consegna", parcel:"Articoli pronti per il pacco", planButton:"Crea la mia lista", planTitle:"La tua lista di ricerca del pacco", planEmpty:"Aggiungi destinazione e numero di articoli per creare una lista.", findTitle:"Sistema di ricerca LoloBuy: confronta prima di cercare", findLead:"Segui un percorso chiaro: salva l’annuncio, confronta variante e misure, poi cerca con termini verificati.", findSteps:[["Salva l’annuncio esatto","Conserva link, variante scelta, misure visibili e note del venditore."],["Confronta elementi equivalenti","Controlla colore, taglia o versione uguali e separa il prezzo da scelte successive."],["Cerca con i fatti","Usa nome, modello o categoria salvati in FindSpreadsheet e ricontrolla l’annuncio live."]], shippingSteps:[["Inizia dalla destinazione","Linee e restrizioni dipendono dal paese: indicalo prima."],["Registra i dati del pacco","Annota articoli pronti, in attesa e dettagli che possono influire su dimensioni o gestione."],["Confronta la stima live","Una stima non è un prezzo finale. Verifica pacco, linea disponibile e destinazione prima dell’invio."]], related:"Continua la ricerca", shoes:"Ricerca scarpe", hoodies:"Ricerca felpe", accessories:"Ricerca accessori", openDatabase:"Apri FindSpreadsheet", accessoriesTitle:"Spreadsheet accessori LoloBuy: ricerca per tipo", accessoriesLead:"Un cluster pratico per borse, orologi ed elettronica. Confronta dettagli importanti prima della ricerca nel database.", accessoriesGroups:[["Borse","Controlla materiale, capienza, ferramenta e colore o taglia selezionati."],["Orologi","Confronta specifiche visibili, immagini e note del venditore; non dedurre prestazioni da una foto."],["Elettronica","Controlla modello, compatibilità, condizioni e dettagli di spina o regione."]]},
  pt: { ...en, tools:"Ferramentas de pesquisa", home:"Início", categories:"Categorias", articles:"Artigos SEO", searchLabel:"Sistema de pesquisa", searchPlaceholder:"Pesquisar marca, artigo ou categoria", searchButton:"Pesquisar no FindSpreadsheet", shippingLabel:"Planeador de envio", shippingTitle:"Planeador de estimativa de envio LoloBuy", shippingLead:"Prepare os dados que afetam uma estimativa de encomenda em direto antes de comparar opções. Esta página não apresenta preço nem promete rota.", destination:"País de entrega", parcel:"Artigos prontos para encomenda", planButton:"Criar a minha lista", planTitle:"A sua lista de pesquisa da encomenda", planEmpty:"Adicione destino e número de artigos para criar uma lista.", findTitle:"Sistema de pesquisa LoloBuy: compare antes de pesquisar", findLead:"Siga um caminho claro: guarde o anúncio, compare variante e medidas e depois pesquise com termos verificados.", findSteps:[["Guarde o anúncio exato","Mantenha link, variante, medidas visíveis e notas do vendedor juntos."],["Compare equivalentes","Verifique a mesma cor, tamanho ou versão e separe o preço das decisões posteriores."],["Pesquise com factos","Use o nome, modelo ou categoria guardados no FindSpreadsheet e confirme o anúncio ao vivo."]], shippingSteps:[["Comece pelo destino","Linhas e restrições dependem do destino; indique o país primeiro."],["Registe os dados da encomenda","Anote artigos prontos, pendentes e detalhes que podem afetar tamanho ou manuseamento."],["Compare a estimativa ao vivo","Uma estimativa não é preço final. Verifique encomenda, linha disponível e destino antes do envio."]], related:"Continue a pesquisa", shoes:"Pesquisa de calçado", hoodies:"Pesquisa de camisolas", accessories:"Pesquisa de acessórios", openDatabase:"Abrir FindSpreadsheet", accessoriesTitle:"Spreadsheet de acessórios LoloBuy: pesquisa por tipo", accessoriesLead:"Um cluster prático para malas, relógios e eletrónica. Compare detalhes importantes antes da pesquisa na base.", accessoriesGroups:[["Malas","Verifique material, capacidade, ferragens e cor ou tamanho escolhidos."],["Relógios","Compare especificações visíveis, imagens e notas do vendedor; não deduza desempenho por uma foto."],["Eletrónica","Verifique modelo, compatibilidade, condição e detalhes de tomada ou região."]]},
  nl: { ...en, tools:"Onderzoekstools", home:"Home", categories:"Categorieën", articles:"SEO-artikelen", searchLabel:"Vindsysteem", searchPlaceholder:"Zoek merk, artikel of categorie", searchButton:"Zoek in FindSpreadsheet", shippingLabel:"Verzendplanner", shippingTitle:"LoloBuy verzendschattingsplanner", shippingLead:"Bereid de gegevens voor die een live pakketschatting beïnvloeden voordat je opties vergelijkt. Deze pagina geeft geen prijs of routebelofte.", destination:"Land van bezorging", parcel:"Artikelen klaar voor pakket", planButton:"Mijn lijst maken", planTitle:"Jouw pakketonderzoekschecklist", planEmpty:"Voeg bestemming en aantal artikelen toe om een checklist te maken.", findTitle:"LoloBuy vindsysteem: vergelijk vóór je zoekt", findLead:"Gebruik een helder pad: bewaar de listing, vergelijk variant en maten en zoek daarna met geverifieerde termen.", findSteps:[["Bewaar de exacte listing","Bewaar link, gekozen variant, zichtbare maten en verkopersnotities samen."],["Vergelijk gelijke items","Controleer dezelfde kleur, maat of versie en scheid artikelprijs van latere keuzes."],["Zoek met feiten","Gebruik opgeslagen naam, model of categorie in FindSpreadsheet en controleer de live-listing opnieuw."]], shippingSteps:[["Begin met bestemming","Lijnen en beperkingen zijn bestemmingsafhankelijk; noem eerst het land."],["Noteer pakketgegevens","Noteer klaarstaande en wachtende artikelen plus details over grootte of behandeling."],["Vergelijk live-schatting","Een schatting is geen eindprijs. Controleer pakket, beschikbare lijn en bestemming vóór verzending."]], related:"Ga verder met onderzoek", shoes:"Schoenenonderzoek", hoodies:"Hoodie-onderzoek", accessories:"Accessoire-onderzoek", openDatabase:"Open FindSpreadsheet", accessoriesTitle:"LoloBuy accessoire-spreadsheet: onderzoek per type", accessoriesLead:"Een praktisch cluster voor tassen, horloges en elektronica. Vergelijk relevante details voor je in de database zoekt.", accessoriesGroups:[["Tassen","Controleer materiaal, inhoud, hardware en gekozen kleur of maat."],["Horloges","Vergelijk zichtbare specificaties, beelden en verkopersnotities; leid geen prestaties uit één foto af."],["Elektronica","Controleer model, compatibiliteit, staat en stekker- of regiodetails."]]},
  pl: { ...en, tools:"Narzędzia badawcze", home:"Strona główna", categories:"Kategorie", articles:"Artykuły SEO", searchLabel:"System wyszukiwania", searchPlaceholder:"Szukaj marki, produktu lub kategorii", searchButton:"Szukaj w FindSpreadsheet", shippingLabel:"Planer wysyłki", shippingTitle:"Planer wyceny wysyłki LoloBuy", shippingLead:"Przygotuj dane wpływające na wycenę paczki na żywo przed porównaniem opcji. Ta strona nie podaje ceny ani nie obiecuje trasy.", destination:"Kraj dostawy", parcel:"Produkty gotowe do paczki", planButton:"Utwórz moją listę", planTitle:"Twoja lista badania paczki", planEmpty:"Dodaj miejsce docelowe i liczbę produktów, aby utworzyć listę.", findTitle:"System wyszukiwania LoloBuy: porównaj przed wyszukaniem", findLead:"Użyj jasnej ścieżki: zapisz ofertę, porównaj wariant i wymiary, a potem szukaj zweryfikowanymi hasłami.", findSteps:[["Zapisz dokładną ofertę","Trzymaj razem link, wybrany wariant, widoczne wymiary i uwagi sprzedawcy."],["Porównuj porównywalne","Sprawdź ten sam kolor, rozmiar lub wersję i oddziel cenę produktu od późniejszych decyzji."],["Szukaj według faktów","Użyj zapisanej nazwy, modelu lub kategorii w FindSpreadsheet i ponownie sprawdź ofertę live."]], shippingSteps:[["Zacznij od kraju","Linie i ograniczenia zależą od kraju; wskaż go najpierw."],["Zapisz dane paczki","Zanotuj gotowe i oczekujące produkty oraz szczegóły wpływające na rozmiar lub obsługę."],["Porównaj wycenę live","Wycena nie jest ceną końcową. Sprawdź paczkę, dostępną linię i kraj przed wysłaniem."]], related:"Kontynuuj badanie", shoes:"Badanie obuwia", hoodies:"Badanie bluz", accessories:"Badanie akcesoriów", openDatabase:"Otwórz FindSpreadsheet", accessoriesTitle:"Spreadsheet akcesoriów LoloBuy: badanie według typu", accessoriesLead:"Praktyczny klaster dla toreb, zegarków i elektroniki. Porównaj ważne szczegóły przed wyszukiwaniem w bazie.", accessoriesGroups:[["Torby","Sprawdź materiał, pojemność, okucia oraz wybrany kolor lub rozmiar."],["Zegarki","Porównaj widoczne specyfikacje, zdjęcia i uwagi sprzedawcy; nie wyciągaj wniosków o działaniu ze zdjęcia."],["Elektronika","Sprawdź model, zgodność, stan oraz szczegóły wtyczki lub regionu."]]},
  sv: { ...en, tools:"Researchverktyg", home:"Hem", categories:"Kategorier", articles:"SEO-artiklar", searchLabel:"Hittasystem", searchPlaceholder:"Sök varumärke, artikel eller kategori", searchButton:"Sök i FindSpreadsheet", shippingLabel:"Fraktplanerare", shippingTitle:"LoloBuy planeringsverktyg för fraktuppskattning", shippingLead:"Förbered uppgifter som påverkar en live-uppskattning av paketet innan du jämför alternativ. Sidan ger inget pris eller ruttlöfte.", destination:"Leveransland", parcel:"Artiklar redo för paket", planButton:"Skapa min lista", planTitle:"Din checklista för paketresearch", planEmpty:"Lägg till destination och antal artiklar för att skapa en checklista.", findTitle:"LoloBuy hittasystem: jämför innan du söker", findLead:"Använd en tydlig väg: spara annonsen, jämför variant och mått och sök sedan med verifierade termer.", findSteps:[["Spara exakt annons","Spara länk, vald variant, synliga mått och säljarens anteckningar tillsammans."],["Jämför likvärdigt","Kontrollera samma färg, storlek eller version och skilj produktpriset från senare val."],["Sök med fakta","Använd sparat namn, modell eller kategori i FindSpreadsheet och kontrollera live-annonsen igen."]], shippingSteps:[["Börja med destinationen","Linjer och begränsningar beror på destination; ange landet först."],["Notera paketuppgifter","Skriv ner klara och väntande artiklar samt detaljer som kan påverka storlek eller hantering."],["Jämför live-uppskattningen","En uppskattning är inget slutpris. Kontrollera paket, tillgänglig linje och destination före inlämning."]], related:"Fortsätt research", shoes:"Skoresearch", hoodies:"Hoodie-research", accessories:"Accessoar-research", openDatabase:"Öppna FindSpreadsheet", accessoriesTitle:"LoloBuy accessoar-spreadsheet: research per artikeltyp", accessoriesLead:"Ett praktiskt kluster för väskor, klockor och elektronik. Jämför viktiga detaljer före databassökning.", accessoriesGroups:[["Väskor","Kontrollera material, kapacitet, beslag och vald färg eller storlek."],["Klockor","Jämför synliga specifikationer, bilder och säljarens anteckningar; dra inte slutsatser om prestanda från en bild."],["Elektronik","Kontrollera modell, kompatibilitet, skick samt kontakt- eller regionsdetaljer."]]}
};

export const getClusterContent = (locale: Locale): ToolCopy => locale === "en" ? en : localized[locale];
