/* eslint-disable @next/next/no-html-link-for-pages */
"use client";

import { useEffect, useState } from "react";
import { ArrowRight, ArrowUpRight, Check, ChevronDown, Globe2, Menu, PackageCheck, Search, ShieldCheck, Sparkles, X } from "lucide-react";
import { content as routeContent, getCategory } from "./site-i18n";
import { databaseImageData, logoData } from "./assets";

type Locale = "en" | "fr" | "de" | "es" | "it" | "pt" | "nl" | "pl" | "sv";
const languages: { id: Locale; label: string; short: string; market: string }[] = [
  { id:"en",label:"English",short:"EN",market:"US · UK · IE" }, { id:"fr",label:"Français",short:"FR",market:"France · Belgium" }, { id:"de",label:"Deutsch",short:"DE",market:"Germany · Austria" }, { id:"es",label:"Español",short:"ES",market:"Spain" }, { id:"it",label:"Italiano",short:"IT",market:"Italy" }, { id:"pt",label:"Português",short:"PT",market:"Portugal" }, { id:"nl",label:"Nederlands",short:"NL",market:"Netherlands" }, { id:"pl",label:"Polski",short:"PL",market:"Poland" }, { id:"sv",label:"Svenska",short:"SV",market:"Sweden" },
];
const copy: Record<Locale, { find:string; guide:string; notes:string; faq:string; open:string; language:string; eyebrow:string; title1:string; title2:string; lead:string; search:string; searchButton:string; route:string; routeTitle:string; routeText:string; destination:string; verify:string; database:string; research:string; researchTitle:string; researchText:string; categories:string; journal:string; journalTitle:string; question:string; disclosure:string; updated:string }> = {
  en:{find:"Finds",guide:"How it works",notes:"Research notes",faq:"FAQ",open:"Open database",language:"Language",eyebrow:"Independent research hub · 2026",title1:"Find smarter.",title2:"Ship with fewer surprises.",lead:"A clear starting point for people researching LoloBuy-style shopping from Europe and North America. Compare a find, check the route, then continue to the searchable database.",search:"Search a brand, item or category",searchButton:"Search database",route:"Route-aware research",routeTitle:"One clear path from a saved find to your next search.",routeText:"LoloBuy’s public interface includes shopping from Chinese channels, destination selection, freight estimation and parcel tracking. Availability and pricing depend on the destination and live checkout result.",destination:"Choose destination",verify:"Check the details",database:"Search the database",research:"Built for real research",researchTitle:"Information first. No invented promises.",researchText:"This inspection version separates what can be checked from what must be confirmed during an order.",categories:"Start with a category",journal:"Research journal",journalTitle:"Useful guides for a first order",question:"Questions before you search",disclosure:"Independent discovery experience. Verify product, payment and shipping details at checkout.",updated:"Inspection version · 02 September 2026"},
  fr:{find:"Trouver",guide:"Fonctionnement",notes:"Notes",faq:"FAQ",open:"Ouvrir la base",language:"Langue",eyebrow:"Hub de recherche indépendant · 2026",title1:"Cherchez mieux.",title2:"Expédiez avec moins de surprises.",lead:"Un point de départ clair pour étudier les achats de type LoloBuy depuis l’Europe et l’Amérique du Nord. Comparez un article, vérifiez l’itinéraire, puis ouvrez la base consultable.",search:"Rechercher une marque, un article ou une catégorie",searchButton:"Chercher dans la base",route:"Recherche selon la destination",routeTitle:"Un chemin clair entre un article repéré et votre prochaine recherche.",routeText:"L’interface publique de LoloBuy propose des achats via des canaux chinois, le choix de la destination, une estimation du fret et le suivi des colis. La disponibilité et les prix dépendent de la destination et du paiement en direct.",destination:"Choisir la destination",verify:"Vérifier les détails",database:"Chercher dans la base",research:"Conçu pour une vraie recherche",researchTitle:"Les informations d’abord. Aucune promesse inventée.",researchText:"Cette version sépare les faits vérifiables de ceux à confirmer lors d’une commande.",categories:"Commencez par une catégorie",journal:"Journal de recherche",journalTitle:"Guides utiles pour une première commande",question:"Questions avant votre recherche",disclosure:"Expérience indépendante. Vérifiez produit, paiement et expédition lors du paiement.",updated:"Version de vérification · 02 septembre 2026"},
  de:{find:"Funde",guide:"Ablauf",notes:"Recherche",faq:"FAQ",open:"Datenbank öffnen",language:"Sprache",eyebrow:"Unabhängiger Recherche-Hub · 2026",title1:"Besser finden.",title2:"Mit weniger Überraschungen versenden.",lead:"Ein klarer Einstieg für Menschen in Europa und Nordamerika, die LoloBuy-ähnliche Einkäufe recherchieren. Fund vergleichen, Route prüfen und dann die durchsuchbare Datenbank öffnen.",search:"Marke, Artikel oder Kategorie suchen",searchButton:"Datenbank durchsuchen",route:"Recherche nach Zielort",routeTitle:"Ein klarer Weg vom gespeicherten Fund zur nächsten Suche.",routeText:"Die öffentliche LoloBuy-Oberfläche umfasst Einkäufe aus chinesischen Kanälen, Zielortwahl, Frachtkalkulation und Sendungsverfolgung. Verfügbarkeit und Preis hängen vom Zielort und Live-Checkout ab.",destination:"Zielort wählen",verify:"Details prüfen",database:"Datenbank durchsuchen",research:"Für echte Recherche",researchTitle:"Information zuerst. Keine erfundenen Versprechen.",researchText:"Diese Prüffassung trennt überprüfbare Fakten von Punkten, die bei einer Bestellung bestätigt werden müssen.",categories:"Mit einer Kategorie beginnen",journal:"Recherche-Journal",journalTitle:"Hilfreiche Guides für die erste Bestellung",question:"Fragen vor der Suche",disclosure:"Unabhängige Entdeckungsseite. Prüfen Sie Produkt-, Zahlungs- und Versanddetails beim Checkout.",updated:"Prüfversion · 02. September 2026"},
  es:{find:"Productos",guide:"Cómo funciona",notes:"Notas",faq:"Preguntas",open:"Abrir base de datos",language:"Idioma",eyebrow:"Centro de investigación independiente · 2026",title1:"Encuentra mejor.",title2:"Envía con menos sorpresas.",lead:"Un punto de partida claro para investigar compras tipo LoloBuy desde Europa y Norteamérica. Compara un producto, revisa la ruta y abre la base de datos.",search:"Buscar marca, producto o categoría",searchButton:"Buscar en la base",route:"Investigación según destino",routeTitle:"Un camino claro desde un producto guardado hasta tu próxima búsqueda.",routeText:"La interfaz pública de LoloBuy incluye compras desde canales chinos, selección de destino, cálculo de flete y seguimiento. La disponibilidad y el precio dependen del destino y del pago en directo.",destination:"Elegir destino",verify:"Revisar detalles",database:"Buscar en la base",research:"Creado para investigar",researchTitle:"Información primero. Sin promesas inventadas.",researchText:"Esta versión separa lo comprobable de lo que debe confirmarse al hacer un pedido.",categories:"Empieza por una categoría",journal:"Diario de investigación",journalTitle:"Guías útiles para un primer pedido",question:"Preguntas antes de buscar",disclosure:"Experiencia independiente. Verifica producto, pago y envío en el checkout.",updated:"Versión de inspección · 02 septiembre 2026"},
  it:{find:"Trova",guide:"Come funziona",notes:"Note",faq:"FAQ",open:"Apri database",language:"Lingua",eyebrow:"Hub di ricerca indipendente · 2026",title1:"Trova meglio.",title2:"Spedisci con meno sorprese.",lead:"Un punto di partenza chiaro per chi ricerca acquisti in stile LoloBuy dall’Europa e dal Nord America. Confronta un articolo, controlla il percorso e apri il database.",search:"Cerca marca, articolo o categoria",searchButton:"Cerca nel database",route:"Ricerca per destinazione",routeTitle:"Un percorso chiaro da un articolo salvato alla prossima ricerca.",routeText:"L’interfaccia pubblica di LoloBuy include acquisti da canali cinesi, scelta della destinazione, stima del trasporto e tracciamento. Disponibilità e prezzo dipendono dalla destinazione e dal checkout in tempo reale.",destination:"Scegli destinazione",verify:"Controlla i dettagli",database:"Cerca nel database",research:"Per una ricerca reale",researchTitle:"Prima le informazioni. Nessuna promessa inventata.",researchText:"Questa versione separa i fatti verificabili da ciò che va confermato in un ordine.",categories:"Inizia da una categoria",journal:"Diario di ricerca",journalTitle:"Guide utili per il primo ordine",question:"Domande prima della ricerca",disclosure:"Esperienza indipendente. Verifica prodotto, pagamento e spedizione al checkout.",updated:"Versione di ispezione · 02 settembre 2026"},
  pt:{find:"Encontrar",guide:"Como funciona",notes:"Notas",faq:"FAQ",open:"Abrir base",language:"Idioma",eyebrow:"Centro de pesquisa independente · 2026",title1:"Encontre melhor.",title2:"Envie com menos surpresas.",lead:"Um ponto de partida claro para pesquisar compras ao estilo LoloBuy na Europa e na América do Norte. Compare um item, confirme a rota e abra a base pesquisável.",search:"Pesquisar marca, item ou categoria",searchButton:"Pesquisar base",route:"Pesquisa por destino",routeTitle:"Um caminho claro entre um item guardado e a próxima pesquisa.",routeText:"A interface pública da LoloBuy inclui compras em canais chineses, escolha do destino, estimativa de frete e acompanhamento de encomendas. Disponibilidade e preço dependem do destino e do checkout ao vivo.",destination:"Escolher destino",verify:"Confirmar detalhes",database:"Pesquisar base",research:"Feito para pesquisa real",researchTitle:"Informação primeiro. Sem promessas inventadas.",researchText:"Esta versão separa factos verificáveis do que deve ser confirmado num pedido.",categories:"Comece por uma categoria",journal:"Diário de pesquisa",journalTitle:"Guias úteis para a primeira encomenda",question:"Perguntas antes da pesquisa",disclosure:"Experiência independente. Confirme produto, pagamento e envio no checkout.",updated:"Versão de inspeção · 02 setembro 2026"},
  nl:{find:"Vondsten",guide:"Werkwijze",notes:"Notities",faq:"FAQ",open:"Database openen",language:"Taal",eyebrow:"Onafhankelijke onderzoekshub · 2026",title1:"Vind slimmer.",title2:"Verzend met minder verrassingen.",lead:"Een helder vertrekpunt voor mensen in Europa en Noord-Amerika die LoloBuy-achtige aankopen onderzoeken. Vergelijk een vondst, controleer de route en open de database.",search:"Zoek een merk, item of categorie",searchButton:"Zoek database",route:"Onderzoek per bestemming",routeTitle:"Een helder pad van een bewaarde vondst naar je volgende zoekopdracht.",routeText:"De openbare LoloBuy-interface bevat aankopen via Chinese kanalen, bestemmingskeuze, vrachtberekening en pakkettracking. Beschikbaarheid en prijs hangen af van bestemming en live checkout.",destination:"Kies bestemming",verify:"Controleer details",database:"Zoek database",research:"Gemaakt voor echt onderzoek",researchTitle:"Eerst informatie. Geen verzonnen beloften.",researchText:"Deze inspectieversie scheidt controleerbare feiten van punten die bij een bestelling moeten worden bevestigd.",categories:"Begin met een categorie",journal:"Onderzoeksjournal",journalTitle:"Handige gidsen voor een eerste bestelling",question:"Vragen voor je zoekt",disclosure:"Onafhankelijke ontdekervaring. Controleer product-, betaal- en verzenddetails bij checkout.",updated:"Inspectieversie · 02 september 2026"},
  pl:{find:"Znaleziska",guide:"Jak działa",notes:"Notatki",faq:"FAQ",open:"Otwórz bazę",language:"Język",eyebrow:"Niezależne centrum badań · 2026",title1:"Szukaj mądrzej.",title2:"Wysyłaj bez niespodzianek.",lead:"Jasny punkt startowy dla osób z Europy i Ameryki Północnej badających zakupy w stylu LoloBuy. Porównaj produkt, sprawdź trasę, a następnie otwórz wyszukiwalną bazę.",search:"Szukaj marki, produktu lub kategorii",searchButton:"Szukaj w bazie",route:"Badanie według kraju",routeTitle:"Jasna droga od zapisanego produktu do kolejnego wyszukiwania.",routeText:"Publiczny interfejs LoloBuy obejmuje zakupy z chińskich kanałów, wybór kraju, wycenę frachtu i śledzenie przesyłki. Dostępność i cena zależą od kraju oraz wyniku płatności na żywo.",destination:"Wybierz kraj",verify:"Sprawdź szczegóły",database:"Szukaj w bazie",research:"Do rzetelnych badań",researchTitle:"Najpierw informacje. Bez wymyślonych obietnic.",researchText:"Ta wersja rozdziela sprawdzalne fakty od elementów wymagających potwierdzenia przy zamówieniu.",categories:"Zacznij od kategorii",journal:"Dziennik badań",journalTitle:"Przydatne poradniki dla pierwszego zamówienia",question:"Pytania przed wyszukiwaniem",disclosure:"Niezależne doświadczenie. Zweryfikuj produkt, płatność i wysyłkę przy finalizacji.",updated:"Wersja kontrolna · 02 września 2026"},
  sv:{find:"Fynd",guide:"Så fungerar det",notes:"Anteckningar",faq:"FAQ",open:"Öppna databasen",language:"Språk",eyebrow:"Oberoende researchhub · 2026",title1:"Hitta smartare.",title2:"Skicka med färre överraskningar.",lead:"En tydlig startpunkt för personer i Europa och Nordamerika som undersöker LoloBuy-liknande köp. Jämför ett fynd, kontrollera vägen och öppna sedan databasen.",search:"Sök efter varumärke, artikel eller kategori",searchButton:"Sök i databasen",route:"Research efter destination",routeTitle:"En tydlig väg från ett sparat fynd till nästa sökning.",routeText:"LoloBuys publika gränssnitt omfattar köp via kinesiska kanaler, val av destination, fraktberäkning och paketspårning. Tillgänglighet och pris beror på destinationen och livekassan.",destination:"Välj destination",verify:"Kontrollera detaljer",database:"Sök i databasen",research:"Skapad för riktig research",researchTitle:"Information först. Inga påhittade löften.",researchText:"Den här granskningsversionen skiljer verifierbara fakta från sådant som ska bekräftas i en order.",categories:"Börja med en kategori",journal:"Researchjournal",journalTitle:"Användbara guider för en första order",question:"Frågor före sökning",disclosure:"Oberoende upplevelse. Kontrollera produkt-, betalnings- och leveransdetaljer i kassan.",updated:"Granskningsversion · 02 september 2026"},
};
const categories=["Shoes","Hoodies","T-Shirts","Jackets","Pants","Bags","Watches","Electronics"];

export default function Home() {
  const [locale,setLocaleState]=useState<Locale>(()=>(typeof window!=="undefined" && (localStorage.getItem("lolobuy-locale") as Locale)) || "en"), [showLanguages,setShowLanguages]=useState(false), [menu,setMenu]=useState(false), [query,setQuery]=useState("");
  const setLocale=(next:Locale)=>{setLocaleState(next);localStorage.setItem("lolobuy-locale",next)};
  const t=copy[locale], current=languages.find(x=>x.id===locale)!;
  const all=routeContent[locale];
  useEffect(()=>{document.documentElement.lang=locale},[locale]);
  const database="https://findspreadsheet.com/";
  // This is FindSpreadsheet's live product-search route (verified from its own All Products search form).
  const search=(term:string)=>`https://findspreadsheet.com/search.html?keywords=${encodeURIComponent(term)}&channelid=2`;
  const categoryUrl=(name:string)=>({
    Shoes:"https://findspreadsheet.com/shoes/", Hoodies:"https://findspreadsheet.com/hoodies-sweaters/",
    "T-Shirts":"https://findspreadsheet.com/t-shirts/", Jackets:"https://findspreadsheet.com/jackets/",
    Pants:"https://findspreadsheet.com/pants-shorts/", Electronics:"https://findspreadsheet.com/electronics/",
  } as Record<string,string>)[name] ?? search(name);
  const steps=[
    {n:"01",Icon:Globe2,title:all.home.steps[0][0],text:all.home.steps[0][1]},
    {n:"02",Icon:ShieldCheck,title:all.home.steps[1][0],text:all.home.steps[1][1]},
    {n:"03",Icon:Search,title:all.home.steps[2][0],text:all.home.steps[2][1]},
  ];
  function submit(e:React.FormEvent){e.preventDefault();window.location.assign(search(query.trim()))}
  return <main className="page">
    <div className="announcement"><Sparkles size={14}/>{all.announcement}</div>
    <header className="shell nav-shell"><div className="nav-card"><a href="/" className="brand"><img src={logoData} alt="LoloBuy"/></a><nav><a href="/">{all.nav.home}</a><a href="/categories">{all.nav.categories}</a><a href="/products">{all.nav.products}</a><a href="/articles">{all.nav.articles}</a><a href="/faq">{all.nav.faq}</a></nav><div className="nav-actions"><div className="language-wrap"><button aria-label={all.nav.language} className="language-button" onClick={()=>setShowLanguages(!showLanguages)}><Globe2 size={16}/>{current.short}<ChevronDown size={14}/></button>{showLanguages&&<div className="language-menu"><p>{all.nav.language}</p>{languages.map(item=><button className={item.id===locale?"selected":""} key={item.id} onClick={()=>{setLocale(item.id);setShowLanguages(false)}}><span>{item.label}<small>{item.market}</small></span>{item.id===locale&&<Check size={15}/>}</button>)}</div>}</div><a className="button compact" href={database}>{t.open}<ArrowUpRight size={16}/></a><button aria-label="Menu" className="menu-button" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></div>{menu&&<div className="mobile-nav"><a href="/">{all.nav.home}</a><a href="/categories">{all.nav.categories}</a><a href="/products">{all.nav.products}</a><a href="/articles">{all.nav.articles}</a><a href="/faq">{all.nav.faq}</a></div>}</header>
    <section className="shell hero" id="top"><div><p className="eyebrow"><i/>{t.eyebrow}</p><h1>{t.title1}<br/><em>{t.title2}</em></h1><p className="lead">{t.lead}</p><form className="search" onSubmit={submit}><Search size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search}/><button>{t.searchButton}<ArrowRight size={16}/></button></form><a className="open-image" href={database}><img src={databaseImageData} alt={t.open}/></a><p className="trust"><span><Check size={15}/>{all.home.trust[0]}</span><span><Check size={15}/>{all.home.trust[1]}</span></p></div><div className="route-art"><div className="circle one"/><div className="circle two"/><span className="region eu">EUROPE</span><span className="region us">NORTH<br/>AMERICA</span><div className="dashed"/><article className="route-card first"><b><Search size={18}/></b><span><small>01 · {all.home.routeCards[0]}</small>{all.home.routeCards[0]}</span></article><article className="route-card second"><b><PackageCheck size={18}/></b><span><small>02 · {all.home.routeCards[1]}</small>{all.home.routeCards[1]}</span></article><article className="route-card third"><b><ArrowUpRight size={18}/></b><span><small>03 · {all.home.routeCards[2]}</small>{all.home.routeCards[2]}</span></article></div></section>
    <section className="shell section" id="guide"><div className="heading"><div><p className="eyebrow"><i/>{t.route}</p><h2>{t.routeTitle}</h2></div><p>{t.routeText}</p></div><div className="steps">{steps.map(({n,Icon,title,text})=><article key={n}><header><small>{n}</small><Icon/></header><h3>{title}</h3><p>{text}</p><a href={database}>{t.open}<ArrowRight size={16}/></a></article>)}</div></section>
    <section className="shell research" id="finds"><div className="research-card"><div className="heading inverse"><div><p className="eyebrow"><i/>{t.research}</p><h2>{t.researchTitle}</h2></div><p>{t.researchText}</p></div><div className="facts">{all.home.facts.map(([title,text],index)=><article key={title}><b>{String.fromCharCode(65+index)}</b><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="shell section cats" id="categories"><div className="heading"><div><p className="eyebrow"><i/>{t.database}</p><h2>{t.categories}</h2></div><p>{all.home.categoryBlurb}</p></div><div className="category-grid">{categories.map((category,index)=><a href={categoryUrl(category)} key={category} className={`cat c${index}`}><small>0{index+1}</small><b>{getCategory(locale,category as Parameters<typeof getCategory>[1]).name}</b><ArrowUpRight size={19}/></a>)}</div></section>
    <section className="shell section details-section" id="details"><div className="heading"><div><p className="eyebrow"><i/>{all.nav.products}</p><h2>{all.productLead}</h2></div><p>{all.categoryLead}</p></div><div className="detail-grid">{categories.map((category,index)=>{const item=getCategory(locale,category as Parameters<typeof getCategory>[1]);return <a href={categoryUrl(category)} className="detail-card" key={category}><span>{all.productPrefix} 0{index+1}</span><h3>{item.name}</h3><p>{item.description}</p><b>{all.openDetails} <ArrowUpRight size={16}/></b></a>})}</div></section>
    <section className="shell section journal" id="articles"><div className="heading"><div><p className="eyebrow"><i/>{all.nav.articles}</p><h2>{t.journalTitle}</h2></div><a className="plain-link" href="/articles">{all.openArticles}<ArrowRight size={16}/></a></div><div className="journal-grid"><article className="guide g0"><small>01</small><div><b>{all.home.articleTag}</b><h3>{all.home.articleTitle}</h3><p>{all.home.articleText}</p><a href="/articles/lolobuy-first-order-research-guide">{all.readArticle}<ArrowRight size={16}/></a></div></article></div></section>
    <section className="shell faq" id="faq"><div><p className="eyebrow"><i/>{all.nav.faq}</p><h2>{t.question}</h2></div><div>{all.home.homeFaq.map(([q,a],i)=><details open={i===0} key={q}><summary><small>0{i+1}</small>{q}<ChevronDown size={18}/></summary><p>{a}</p></details>)}</div></section>
    <footer className="shell"><div className="footer-card"><a href="/" className="brand"><img src={logoData} alt="LoloBuy"/></a><p>{t.disclosure}</p><a className="button" href={database}>{t.open}<ArrowUpRight size={16}/></a></div></footer>
  </main>;
}
