YªçŠx-®éÜj×¢ëiºÚ+Š§j[h‘éÜ¢éíïÞ4N‹Z–‹­¦ëeŠw¬Ô¼¨•Í±¥¹Ðµ‘¥Í…‰±”¹•áÐ½¹•áÐ½¹¼µ¡Ñµ°µ±¥¹¬µ™½ÈµÁ…•Ì€¨¼(‰ÕÍ”±¥•¹Ðˆì()¥µÁ½ÉÐìÕÍ•™™•Ð°ÕÍ•MÑ…Ñ”ô™É½´€‰É•…Ðˆì)¥µÁ½ÉÐìÉÉ½ÝI¥¡Ð°ÉÉ½ÝUÁI¥¡Ð°¡•¬°¡•ÙÉ½¹½Ý¸°±½‰”È°5•¹Ô°A…­…•¡•¬°M•…É °M¡¥•±‘¡•¬°MÁ…É­±•Ì°`ô™É½´€‰±Õ¥‘”µÉ•…Ðˆì)¥µÁ½ÉÐì½¹Ñ•¹Ð…ÌÉ½ÕÑ•½¹Ñ•¹Ð°•Ñ…Ñ•½Éäô™É½´€ˆ¸½Í¥Ñ”µ¤Äá¸ˆì)¥µÁ½ÉÐì‘…Ñ…‰…Í•%µ…•…Ñ„°±½½…Ñ„ô™É½´€ˆ¸½…ÍÍ•ÑÌˆì()ÑåÁ”1½…±”€ô€‰•¸ˆð€‰™Èˆð€‰‘”ˆð€‰•Ìˆð€‰¥Ðˆð€‰ÁÐˆð€‰¹°ˆð€‰Á°ˆð€‰ÍØˆì)½¹ÍÐ±…¹Õ…•Ìèì¥è1½…±”ì±…‰•°èÍÑÉ¥¹œìÍ¡½ÉÐèÍÑÉ¥¹œìµ…É­•ÐèÍÑÉ¥¹œõmt€ôl(€ì¥è‰•¸ˆ±±…‰•°è‰¹±¥Í ˆ±Í¡½ÉÐè‰8ˆ±µ…É­•Ðè‰ULƒ
ÜU,ƒ
Ü%ˆô°ì¥è‰™Èˆ±±…‰•°è‰É…»…¥Ìˆ±Í¡½ÉÐè‰Hˆ±µ…É­•Ðè‰É…¹”ƒ
Ü	•±¥Õ´ˆô°ì¥è‰‘”ˆ±±…‰•°è‰•ÕÑÍ ˆ±Í¡½ÉÐè‰ˆ±µ…É­•Ðè‰•Éµ…¹äƒ
ÜÕÍÑÉ¥„ˆô°ì¥è‰•Ìˆ±±…‰•°è‰ÍÁ‡Å½°ˆ±Í¡½ÉÐè‰Lˆ±µ…É­•Ðè‰MÁ…¥¸ˆô°ì¥è‰¥Ðˆ±±…‰•°è‰%Ñ…±¥…¹¼ˆ±Í¡½ÉÐè‰%Pˆ±µ…É­•Ðè‰%Ñ…±äˆô°ì¥è‰ÁÐˆ±±…‰•°è‰A½ÉÑÕ×©Ìˆ±Í¡½ÉÐè‰APˆ±µ…É­•Ðè‰A½ÉÑÕ…°ˆô°ì¥è‰¹°ˆ±±…‰•°è‰9•‘•É±…¹‘Ìˆ±Í¡½ÉÐè‰90ˆ±µ…É­•Ðè‰9•Ñ¡•É±…¹‘Ìˆô°ì¥è‰Á°ˆ±±…‰•°è‰A½±Í­¤ˆ±Í¡½ÉÐè‰A0ˆ±µ…É­•Ðè‰A½±…¹ˆô°ì¥è‰ÍØˆ±±…‰•°è‰MÙ•¹Í­„ˆ±Í¡½ÉÐè‰MXˆ±µ…É­•Ðè‰MÝ•‘•¸ˆô°)tì)½¹ÍÐ½ÁäèI•½Éñ1½…±”°ì™¥¹éÍÑÉ¥¹œìÕ¥‘”éÍÑÉ¥¹œì¹½Ñ•ÌéÍÑÉ¥¹œì™…ÄéÍÑÉ¥¹œì½Á•¸éÍÑÉ¥¹œì±…¹Õ…”éÍÑÉ¥¹œì•å•‰É½ÜéÍÑÉ¥¹œìÑ¥Ñ±”ÄéÍÑÉ¥¹œìÑ¥Ñ±”ÈéÍÑÉ¥¹œì±•…éÍÑÉ¥¹œìÍ•…É éÍÑÉ¥¹œìÍ•…É¡	ÕÑÑ½¸éÍÑÉ¥¹œìÉ½ÕÑ”éÍÑÉ¥¹œìÉ½ÕÑ•Q¥Ñ±”éÍÑÉ¥¹œìÉ½ÕÑ•Q•áÐéÍÑÉ¥¹œì‘•ÍÑ¥¹…Ñ¥½¸éÍÑÉ¥¹œìÙ•É¥™äéÍÑÉ¥¹œì‘…Ñ…‰…Í”éÍÑÉ¥¹œìÉ•Í•…É éÍÑÉ¥¹œìÉ•Í•…É¡Q¥Ñ±”éÍÑÉ¥¹œìÉ•Í•…É¡Q•áÐéÍÑÉ¥¹œì…Ñ•½É¥•ÌéÍÑÉ¥¹œì©½ÕÉ¹…°éÍÑÉ¥¹œì©½ÕÉ¹…±Q¥Ñ±”éÍÑÉ¥¹œìÅÕ•ÍÑ¥½¸éÍÑÉ¥¹œì‘¥Í±½ÍÕÉ”éÍÑÉ¥¹œìÕÁ‘…Ñ•éÍÑÉ¥¹œôø€ôì(€•¸éí™¥¹è‰¥¹‘Ìˆ±Õ¥‘”è‰!½Ü¥ÐÝ½É­Ìˆ±¹½Ñ•Ìè‰I•Í•…É ¹½Ñ•Ìˆ±™…Äè‰Dˆ±½Á•¸è‰=Á•¸‘…Ñ…‰…Í”ˆ±±…¹Õ…”è‰1…¹Õ…”ˆ±•å•‰É½Üè‰%¹‘•Á•¹‘•¹ÐÉ•Í•…É ¡Õˆƒ
Ü€ÈÀÈØˆ±Ñ¥Ñ±”Äè‰¥¹Íµ…ÉÑ•È¸ˆ±Ñ¥Ñ±”Èè‰M¡¥ÀÝ¥Ñ ™•Ý•ÈÍÕÉÁÉ¥Í•Ì¸ˆ±±•…è‰±•…ÈÍÑ…ÉÑ¥¹œÁ½¥¹Ð™½ÈÁ•½Á±”É•Í•…É¡¥¹œ1½±½	ÕäµÍÑå±”Í¡½ÁÁ¥¹œ™É½´ÕÉ½Á”…¹9½ÉÑ µ•É¥„¸½µÁ…É”„™¥¹°¡•¬Ñ¡”É½ÕÑ”°Ñ¡•¸½¹Ñ¥¹Õ”Ñ¼Ñ¡”Í•…É¡…‰±”‘…Ñ…‰…Í”¸ˆ±Í•…É è‰M•…É „‰É…¹°¥Ñ•´½È…Ñ•½Éäˆ±Í•…É¡	ÕÑÑ½¸è‰M•…É ‘…Ñ…‰…Í”ˆ±É½ÕÑ”è‰I½ÕÑ”µ…Ý…É”É•Í•…É ˆ±É½ÕÑ•Q¥Ñ±”è‰=¹”±•…ÈÁ…Ñ ™É½´„Í…Ù•™¥¹Ñ¼å½ÕÈ¹•áÐÍ•…É ¸ˆ±É½ÕÑ•Q•áÐè‰1½±½	ÕçŠeÌÁÕ‰±¥Œ¥¹Ñ•É™…”¥¹±Õ‘•ÌÍ¡½ÁÁ¥¹œ™É½´¡¥¹•Í”¡…¹¹•±Ì°‘•ÍÑ¥¹…Ñ¥½¸Í•±•Ñ¥½¸°™É•¥¡Ð•ÍÑ¥µ…Ñ¥½¸…¹Á…É•°ÑÉ…­¥¹œ¸Ù…¥±…‰¥±¥Ñä…¹ÁÉ¥¥¹œ‘•Á•¹½¸Ñ¡”‘•ÍÑ¥¹…Ñ¥½¸…¹±¥Ù”¡•­½ÕÐÉ•ÍÕ±Ð¸ˆ±‘•ÍÑ¥¹…Ñ¥½¸è‰¡½½Í”‘•ÍÑ¥¹…Ñ¥½¸ˆ±Ù•É¥™äè‰¡•¬Ñ¡”‘•Ñ…¥±Ìˆ±‘…Ñ…‰…Í”è‰M•…É Ñ¡”‘…Ñ…‰…Í”ˆ±É•Í•…É è‰	Õ¥±Ð™½ÈÉ•…°É•Í•…É ˆ±É•Í•…É¡Q¥Ñ±”è‰%¹™½Éµ…Ñ¥½¸™¥ÉÍÐ¸9¼¥¹Ù•¹Ñ•ÁÉ½µ¥Í•Ì¸ˆ±É•Í•…É¡Q•áÐè‰Q¡¥Ì¥¹ÍÁ•Ñ¥½¸Ù•ÉÍ¥½¸Í•Á…É…Ñ•ÌÝ¡…Ð…¸‰”¡•­•™É½´Ý¡…ÐµÕÍÐ‰”½¹™¥Éµ•‘ÕÉ¥¹œ…¸½É‘•È¸ˆ±…Ñ•½É¥•Ìè‰MÑ…ÉÐÝ¥Ñ „…Ñ•½Éäˆ±©½ÕÉ¹…°è‰I•Í•…É ©½ÕÉ¹…°ˆ±©½ÕÉ¹…±Q¥Ñ±”è‰UÍ•™Õ°Õ¥‘•Ì™½È„™¥ÉÍÐ½É‘•Èˆ±ÅÕ•ÍÑ¥½¸è‰EÕ•ÍÑ¥½¹Ì‰•™½É”å½ÔÍ•…É ˆ±‘¥Í±½ÍÕÉ”è‰%¹‘•Á•¹‘•¹Ð‘¥Í½Ù•Éä•áÁ•É¥•¹”¸Y•É¥™äÁÉ½‘ÕÐ°Á…åµ•¹Ð…¹Í¡¥ÁÁ¥¹œ‘•Ñ…¥±Ì…Ð¡•­½ÕÐ¸ˆ±ÕÁ‘…Ñ•è‰%¹ÍÁ•Ñ¥½¸Ù•ÉÍ¥½¸ƒ
Ü€ÀÈM•ÁÑ•µ‰•È€ÈÀÈØ‰ô°(€™Èéí™¥¹è‰QÉ½ÕÙ•Èˆ±Õ¥‘”è‰½¹ŸxÒÚ$z{-®éÜj×en}<ArrowRight size={16}/></a></article>)}</div></section>
    <section className="shell research" id="finds"><div className="research-card"><div className="heading inverse"><div><p className="eyebrow"><i/>{t.research}</p><h2>{t.researchTitle}</h2></div><p>{t.researchText}</p></div><div className="facts">{all.home.facts.map(([title,text],index)=><article key={title}><b>{String.fromCharCode(65+index)}</b><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="shell section cats" id="categories"><div className="heading"><div><p className="eyebrow"><i/>{t.database}</p><h2>{t.categories}</h2></div><p>{all.home.categoryBlurb}</p></div><div className="category-grid">{categories.map((category,index)=><a href={categoryPath(category)} key={category} className={`cat c${index}`}><small>0{index+1}</small><b>{getCategory(locale,category as Parameters<typeof getCategory>[1]).name}</b><ArrowUpRight size={19}/></a>)}<a href="/accessories" className="cat c5"><small>09</small><b>{locale==="en"?"Accessories":locale==="fr"?"Accessoires":locale==="de"?"Accessoires":locale==="es"?"Accesorios":locale==="it"?"Accessori":locale==="pt"?"AcessÃ³rios":locale==="nl"?"Accessoires":locale==="pl"?"Akcesoria":"Accessoarer"}</b><ArrowUpRight size={19}/></a></div></section>
    <section className="shell section details-section" id="details"><div className="heading"><div><p className="eyebrow"><i/>{all.nav.products}</p><h2>{all.productLead}</h2></div><p>{all.categoryLead}</p></div><div className="detail-grid">{categories.map((category,index)=>{const item=getCategory(locale,category as Parameters<typeof getCategory>[1]);return <a href={categoryUrl(category)} className="detail-card" key={category}><span>{all.productPrefix} 0{index+1}</span><h3>{item.name}</h3><p>{item.description}</p><b>{all.openDetails} <ArrowUpRight size={16}/></b></a>})}</div></section>
    <section className="shell section journal" id="articles"><div className="heading"><div><p className="eyebrow"><i/>{all.nav.articles}</p><h2>{t.journalTitle}</h2></div><a className="plain-link" href="/articles">{all.openArticles}<ArrowRight size={16}/></a></div><div className="journal-grid"><article className="guide g0"><small>01</small><div><b>{all.home.articleTag}</b><h3>{all.home.articleTitle}</h3><p>{all.home.articleText}</p><a href="/articles/lolobuy-first-order-research-guide">{all.readArticle}<ArrowRight size={16}/></a></div></article></div></section>
    <section className="shell faq" id="faq"><div><p className="eyebrow"><i/>{all.nav.faq}</p><h2>{t.question}</h2></div><div>{all.home.homeFaq.map(([q,a],i)=><details open={i===0} key={q}><summary><small>0{i+1}</small>{q}<ChevronDown size={18}/></summary><p>{a}</p></details>)}</div></section>
    <footer className="shell"><div className="footer-card"><a href="/" className="brand"><img src={logoData} alt="LoloBuy"/></a><p>{t.disclosure}</p><a className="button" href={database}>{t.open}<ArrowUpRight size={16}/></a></div></footer>
  </main>;
}
