const C={en:['Shoes','Hoodies & Sweaters','T-Shirts','Jackets','Pants & Shorts','Headwear','Accessories','Jerseys','Electronics','Other Stuff'],de:['Schuhe','Hoodies & Pullover','T-Shirts','Jacken','Hosen & Shorts','Kopfbedeckung','Accessoires','Trikots','Elektronik','Sonstiges'],fr:['Chaussures','Sweats & pulls','T-shirts','Vestes','Pantalons & shorts','Couvre-chefs','Accessoires','Maillots','Électronique','Autres articles'],es:['Zapatos','Sudaderas y jerséis','Camisetas','Chaquetas','Pantalones y shorts','Gorras y sombreros','Accesorios','Camisetas de fútbol','Electrónica','Otros artículos'],it:['Scarpe','Felpe e maglioni','T-shirt','Giacche','Pantaloni e pantaloncini','Cappelli','Accessori','Maglie sportive','Elettronica','Altri articoli'],pt:['Calçados','Moletons e suéteres','Camisetas','Jaquetas','Calças e shorts','Chapéus','Acessórios','Camisas esportivas','Eletrônicos','Outros itens'],nl:['Schoenen','Hoodies en truien','T-shirts','Jassen','Broeken en shorts','Hoofddeksels','Accessoires','Shirts','Elektronica','Overige items'],pl:['Buty','Bluzy i swetry','T-shirty','Kurtki','Spodnie i szorty','Nakrycia głowy','Akcesoria','Koszulki sportowe','Elektronika','Pozostałe'],sv:['Skor','Hoodies och tröjor','T-shirts','Jackor','Byxor och shorts','Huvudbonader','Accessoarer','Matchtröjor','Elektronik','Övrigt']};
const T={en:{home:'Home',categories:'Categories',product:'Product Details',articles:'SEO Articles',faq:'FAQ',kicker:'FindSpreadsheet / USFans',hero:'A clearer way to discover.',intro:'Independent category, product and shipping research for international shoppers.',search:'Search shoes, bags, apparel…',go:'Search ↗',hint:'Search continues on FindSpreadsheet',scene:'Independent guide — not an official store',catTitle:'Browse the category index.',catLead:'Ten starting points, with every result continuing to the main site.',all:'Open categories ↗',productTitle:'One considered capsule.',productLead:'An original product-detail format with a complete visual, plain specs and a transparent reference price.',view:'View product details ↗',item:'Technical Day Capsule',desc:'A slate overshirt, low-profile trainer, compact shoulder bag and a steel watch selected as one easy-to-check set.',material:'Materials',price:'Reference price',status:'Availability',details:'See on main site ↗',artTitle:'SEO articles that answer real buying questions.',artLead:'Practical reading before quality checks, warehouse decisions and shipping.',read:'Read SEO articles ↗',tag:'SEO article',a1:'How to compare quality-check photos before shipping',a2:'What warehouse timing changes in a buying plan',a3:'A sensible way to compare shipping options',faqTitle:'Clear answers before you browse.',faqLead:'Independent information, written for shoppers.',faq1:'What is this guide for?',faqA1:'It gives shoppers a multilingual starting point. Searches, categories and product actions continue to FindSpreadsheet.',faq2:'Is this an official USFans site?',faqA2:'No. This is an independent research page and is not affiliated with USFans.',foot:'Open FindSpreadsheet ↗',pageCat:'Product categories',pageProd:'Product details',pageArt:'SEO articles',pageFaq:'Frequently asked questions',back:'Back to home ↗'},
de:{home:'Startseite',categories:'Kategorien',product:'Produktdetails',articles:'SEO-Artikel',faq:'FAQ',kicker:'FindSpreadsheet / USFans',hero:'Klarer entdecken.',intro:'Unabhängige Kategorien-, Produkt- und Versandforschung für internationale Käufer.',search:'Schuhe, Taschen, Kleidung suchen…',go:'Suchen ↗',hint:'Die Suche geht bei FindSpreadsheet weiter',scene:'Unabhängiger Leitfaden — kein offizieller Shop',catTitle:'Kategorieindex durchsuchen.',catLead:'Zehn Startpunkte; jedes Ergebnis führt zur Hauptseite.',all:'Kategorien öffnen ↗',productTitle:'Eine durchdachte Auswahl.',productLead:'Ein originäres Produktformat mit Bild, klaren Daten und Referenzpreis.',view:'Produktdetails ansehen ↗',item:'Technisches Tages-Set',desc:'Overshirt, flacher Trainer, kompakte Schultertasche und Stahluhr als einfach prüfbares Set.',material:'Materialien',price:'Referenzpreis',status:'Verfügbarkeit',details:'Auf Hauptseite sehen ↗',artTitle:'SEO-Artikel zu echten Kaufentscheidungen.',artLead:'Praktische Lektüre vor Prüfung, Lager und Versand.',read:'SEO-Artikel lesen ↗',tag:'SEO-Artikel',a1:'Qualitätsfotos vor dem Versand vergleichen',a2:'Wie Lagerzeiten den Kaufplan ändern',a3:'Versandoptionen sinnvoll vergleichen',faqTitle:'Klare Antworten vor dem Stöbern.',faqLead:'Unabhängige Informationen für Käufer.',faq1:'Wofür ist dieser Leitfaden?',faqA1:'Er ist ein mehrsprachiger Startpunkt. Suche, Kategorien und Produktaktionen führen zu FindSpreadsheet.',faq2:'Ist dies eine offizielle USFans-Seite?',faqA2:'Nein. Diese unabhängige Forschungsseite ist nicht mit USFans verbunden.',foot:'FindSpreadsheet öffnen ↗',pageCat:'Produktkategorien',pageProd:'Produktdetails',pageArt:'SEO-Artikel',pageFaq:'Häufige Fragen',back:'Zur Startseite ↗'},
fr:{home:'Accueil',categories:'Catégories',product:'Détails produit',articles:'Articles SEO',faq:'FAQ',kicker:'FindSpreadsheet / USFans',hero:'Découvrir plus clairement.',intro:'Recherche indépendante sur les catégories, produits et expéditions pour acheteurs internationaux.',search:'Rechercher chaussures, sacs, vêtements…',go:'Rechercher ↗',hint:'La recherche continue sur FindSpreadsheet',scene:'Guide indépendant — pas une boutique officielle',catTitle:'Parcourir l’index des catégories.',catLead:'Dix points de départ; chaque résultat continue vers le site principal.',all:'Ouvrir les catégories ↗',productTitle:'Une sélection réfléchie.',productLead:'Un format original avec visuel, caractéristiques simples et prix de référence.',view:'Voir les détails produit ↗',item:'Capsule technique du jour',desc:'Surchemise, baskets fines, sac épaule compact et montre acier dans un ensemble facile à vérifier.',material:'Matières',price:'Prix de référence',status:'Disponibilité',details:'Voir sur le site principal ↗',artTitle:'Des articles SEO pour de vraies décisions.',artLead:'Lecture pratique avant contrôle, entrepôt et expédition.',read:'Lire les articles SEO ↗',tag:'Article SEO',a1:'Comparer les photos de contrôle avant expédition',a2:'Ce que les délais d’entrepôt changent',a3:'Comparer les options d’expédition',faqTitle:'Des réponses claires avant de parcourir.',faqLead:'Informations indépendantes pour acheteurs.',faq1:'À quoi sert ce guide ?',faqA1:'C’est un point de départ multilingue. Recherche, catégories et actions mènent à FindSpreadsheet.',faq2:'Est-ce un site USFans officiel ?',faqA2:'Non. Cette page indépendante n’est pas affiliée à USFans.',foot:'Ouvrir FindSpreadsheet ↗',pageCat:'Catégories produit',pageProd:'Détails produit',pageArt:'Articles SEO',pageFaq:'Questions fréquentes',back:'Retour à l’accueil ↗'},
es:{home:'Inicio',categories:'Categorías',product:'Detalles producto',articles:'Artículos SEO',faq:'FAQ',kicker:'FindSpreadsheet / USFans',hero:'Descubre con más claridad.',intro:'Investigación independiente de categorías, productos y envíos para compradores internacionales.',search:'Busca zapatos, bolsos, ropa…',go:'Buscar ↗',hint:'La búsqueda continúa en FindSpreadsheet',scene:'Guía independiente — no tienda oficial',catTitle:'Explora el índice de categorías.',catLead:'Diez puntos de partida; cada resultado sigue al sitio principal.',all:'Abrir categorías ↗',productTitle:'Una selección cuidada.',productLead:'Un formato original con imagen, datos claros y precio de referencia.',view:'Ver detalles producto ↗',item:'Cápsula técnica del día',desc:'Sobrecamisa, zapatilla baja, bolso compacto y reloj de acero en un conjunto fácil de revisar.',material:'Materiales',price:'Precio de referencia',status:'Disponibilidad',details:'Ver en sitio principal ↗',artTitle:'Artículos SEO para decisiones reales.',artLead:'Lectura práctica antes de control, almacén y envío.',read:'Leer artículos SEO ↗',tag:'Artículo SEO',a1:'Comparar fotos de control antes del envío',a2:'Qué cambia el tiempo de almacén',a3:'Cómo comparar opciones de envío',faqTitle:'Respuestas claras antes de explorar.',faqLead:'Información independiente para compradores.',faq1:'¿Para qué sirve esta guía?',faqA1:'Es un punto de partida multilingüe. Búsqueda, categorías y acciones van a FindSpreadsheet.',faq2:'¿Es una web oficial de USFans?',faqA2:'No. Esta página independiente no está afiliada con USFans.',foot:'Abrir FindSpreadsheet ↗',pageCat:'Categorías de producto',pageProd:'Detalles de producto',pageArt:'Artículos SEO',pageFaq:'Preguntas frecuentes',back:'Volver a inicio ↗'}};
for(const l of ['it','pt','nl','pl','sv'])T[l]={...T.en,...((window.usfansLocaleContent||{})[l]||{})};
const page=document.body.dataset.page,app=document.getElementById('app'),sl=s=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function header(d){const n=[['index.html','home'],['categories.html','categories'],['product-detail.html','product'],['seo-articles.html','articles'],['faq.html','faq']];return `<header class="shell"><div class="top"><a class="brand" href="index.html"><img src="usfans-logo.webp" alt="USFans"></a><nav class="nav">${n.map(x=>`<a href="${x[0]}" class="${page===x[1]?'active':''}">${d[x[1]]}</a>`).join('')}</nav><select class="locale" id="locale" aria-label="Language"><option value="en">EN</option><option value="de">DE</option><option value="fr">FR</option><option value="es">ES</option><option value="it">IT</option><option value="pt">PT</option><option value="nl">NL</option><option value="pl">PL</option><option value="sv">SV</option></select></div></header>`}
const categoryRoutes=['shoes/','hoodies-sweaters/','t-shirts/','jackets/','pants-shorts/','headwear/','accessories/','jersey/','electronics/','other-stuff/'];
const productFinds=[
  {name:'Black Suede Casual Sneakers TT',category:'Shoes',price:'$150.14',note:'Product record available',href:'https://findspreadsheet.com/shoes/black-suede-casual-sneakers-tt-collection-3945.html',image:'https://findspreadsheet.com/uploads/allimg/20260907/1-260ZG54110318.jpg'},
  {name:'Casual Graphic Short Sleeve T-Shirt',category:'Clothing',price:'$31.13',note:'Product record available',href:'https://findspreadsheet.com/t-shirts/casual-graphic-short-sleeve-t-shirt-collection-4965.html',image:'https://findspreadsheet.com/uploads/allimg/20260912/1-26091213513V25.jpg'},
  {name:'Monogram Messenger Bag 9110',category:'Bags',price:'$30.30',note:'Product record available',href:'https://findspreadsheet.com/accessories/monogram-messenger-bag-9110-7735.html',image:'https://findspreadsheet.com/uploads/allimg/20261004/1-261004111150P6.jpg'},
  {name:'White Strap Smartwatch',category:'Watches',price:'$58.95',note:'Product record available',href:'https://findspreadsheet.com/accessories/white-strap-smartwatch-7428.html',image:'https://findspreadsheet.com/uploads/allimg/20261002/1-2610021220024Y.png'},
  {name:'Air Max Headset',category:'Headphones',price:'$39.39',note:'Product record available',href:'https://findspreadsheet.com/electronics/air-max-headset-7028.html',image:'https://findspreadsheet.com/uploads/allimg/20260924/1-26092413160D00.jpg'},
  {name:'Tom Ford Sunglasses',category:'Glasses',price:'$29.61',note:'Product record available',href:'https://findspreadsheet.com/accessories/tom-ford-sunglasses-2976.html',image:'https://findspreadsheet.com/uploads/allimg/20260319/1-260319143934Z2.webp'},
  {name:'HD001 Classic Hooded Jacket',category:'Jackets',price:'$61.43',note:'Product record available',href:'https://findspreadsheet.com/jackets/hd001-classic-hooded-jacket-6180.html',image:'https://findspreadsheet.com/uploads/allimg/20260919/1-260919143540152.jpg'},
  {name:'GCDS Logo Band Hoodie',category:'Hoodies',price:'$34.16',note:'Product record available',href:'https://findspreadsheet.com/hoodies-sweaters/gcds-logo-band-hoodiessweaters-40-styles-1523.html',image:'https://findspreadsheet.com/uploads/allimg/20260211/1-2602110U444610.webp'},
  {name:'Streetwear Top and Shorts Set',category:'Sets',price:'$34.16',note:'Product record available',href:'https://findspreadsheet.com/ShortSets/streetwear-top-and-shorts-set-006-6757.html',image:'https://findspreadsheet.com/uploads/allimg/20260923/1-2609231G104946.jpg'}
];
window.productFinds=productFinds;
const categoryVisuals=[['0%','0%'],['25%','0%'],['50%','0%'],['75%','0%'],['100%','0%'],['0%','100%'],['25%','100%'],['50%','100%'],['75%','100%'],['100%','100%']];
const serviceSteps=[
  {title:'Place an order',copy:'Start from a product link, then check the selected variant in the live order record.',x:'0%',y:'0%'},
  {title:'Warehouse storage',copy:'USFans publicly advertises 90-day free storage; confirm the current account terms.',x:'33.333%',y:'0%'},
  {title:'QC review',copy:'Use the advertised 3–5 QC photos to compare visible size, colour and condition.',x:'66.666%',y:'0%'},
  {title:'Consolidate',copy:'Select reviewed warehouse items intentionally before they become one parcel.',x:'100%',y:'0%'},
  {title:'Estimate shipping',copy:'Compare the live destination, line and parcel information before final payment.',x:'0%',y:'100%'},
  {title:'Track the parcel',copy:'Use the live tracking information after dispatch; timing and events can change.',x:'33.333%',y:'100%'},
  {title:'After-sales',copy:'Read the current return, refund and support rules for the specific order before assuming an outcome.',x:'66.666%',y:'100%'}
];
function cats(l){return `<div class="category-list category-cards" aria-label="Product categories">${C[l].map((x,i)=>`<a href="https://findspreadsheet.com/${categoryRoutes[i]}" aria-label="Browse ${x} on FindSpreadsheet"><span class="category-visual" role="img" aria-label="${x}" style="--category-x:${categoryVisuals[i][0]};--category-y:${categoryVisuals[i][1]}"></span><span class="category-name">${x}</span></a>`).join('')}</div>`}
function serviceFlow(l){const localized=((window.usfansLocaleContent||{})[l]||{}).steps;const steps=localized?serviceSteps.map((step,i)=>({...step,title:localized[i][0],copy:localized[i][1]})):serviceSteps;return `<div class="service-flow">${steps.map((step,i)=>`<article class="service-step"><span class="service-visual" role="img" aria-label="${step.title}" style="--service-x:${step.x};--service-y:${step.y}"></span><div class="service-step-copy"><span class="service-number">${String(i+1).padStart(2,'0')}</span><h3>${step.title}</h3><p>${step.copy}</p></div></article>`).join('')}</div>`}
function product(d){const p=productFinds[0];return `<div class="product product-carousel" data-product-carousel><div class="product-info"><span class="pill" data-product-pill>${d.productPill||'Curated main-site finds'} / <b data-product-number>01</b></span><h2 data-product-name>${p.name}</h2><p data-product-description>${d.productDesc||'Select a product image to update this card with its matching category, live reference price and product record.'}</p></div><div class="product-gallery" aria-label="${d.productGallery||'Selected FindSpreadsheet product images'}"><div class="carousel-window"><div class="carousel-track">${productFinds.map((item,i)=>`<button class="carousel-slide${i===0?' is-active':''}" type="button" data-product-index="${i}" aria-label="${d.productSelect||'Select'} ${item.name}"><img src="${item.image}" alt="${item.name}"><span>${String(i+1).padStart(2,'0')}</span></button>`).join('')}</div></div><div class="carousel-dots">${productFinds.map((item,i)=>`<button type="button" class="carousel-dot${i===0?' is-active':''}" data-product-index="${i}" aria-label="${d.productSelect||'Select'} ${item.name}"></button>`).join('')}</div></div><div class="product-meta"><div class="specs"><div><small>${d.material}</small><b data-product-category>${p.category}</b></div><div><small>${d.price}</small><a class="price product-price-link" data-product-price href="${p.href}">${p.price}</a></div><div><small>${d.status}</small><b data-product-status>${p.note}</b></div></div><a class="product-action" data-product-action href="${p.href}">${d.productAction||'View details & price'} ↗</a></div></div>`}
function articles(d){const e=window.usfansEditorial||{articles:[],sourceNote:''};const label=(a,i)=>d[`article${i+1}`]||d[`a${i+1}`]||a.title;if(page!=='articles')return `<div class="article-list">${e.articles.map((a,i)=>`<a href="seo-articles.html#article-${i+1}"><small>${d.tag}</small><span>${label(a,i)}</span><b>→</b></a>`).join('')}</div>`;return `<div class="editorial-note">${e.sourceNote}</div><div class="editorial-articles">${e.articles.map((a,i)=>`<article class="editorial-article" id="article-${i+1}"><header><p class="eyebrow">USFans research / ${String(i+1).padStart(2,'0')}</p><h2>${label(a,i)}</h2><p class="editorial-dek">${a.dek}</p></header><div class="editorial-body">${a.body}</div></article>`).join('')}</div>`}
function faqs(d){const e=window.usfansEditorial||{faqs:[]};return `<div class="faq-list researched-faq">${e.faqs.map(item=>`<details><summary>${item.q}</summary><p>${item.a}</p></details>`).join('')}</div>`}
function section(id,title,lead,body,link){return `<section class="section" id="${id}"><div class="section-head"><div><p class="eyebrow">${id}</p><h2>${title}</h2></div><div><p>${lead}</p>${link||''}</div></div>${body}</section>`}
function homeCta(d){return `<section class="home-bottom-cta" aria-label="${d.ctaTitle}"><div class="home-bottom-cta-inner"><h2>${d.ctaTitle}</h2><p>${d.ctaLead}</p><div class="home-bottom-cta-actions"><a class="home-cta-primary" href="https://findspreadsheet.com/">${d.ctaPrimary} <span>↗</span></a><a class="home-cta-secondary" href="seo-articles.html#article-1">${d.ctaSecondary} <span>↗</span></a></div></div></section>`}
function render(l){const d={...(T[l]||T.en),...((window.usfansLocaleContent||{})[l]||{})};window.usfansActiveLocale=l;window.usfansActiveCopy=d;document.documentElement.lang=l;const foot=`<footer class="shell footer"><span>© 2026 FindSpreadsheet</span><a href="https://findspreadsheet.com/">${d.foot}</a></footer>`;let body='';
if(page==='home')body=`<main class="shell"><section class="hero"><div class="hero-copy"><p class="eyebrow">${d.kicker}</p><h1>${d.hero}</h1><p class="lead">${d.intro}</p><form class="search" id="search"><input id="q" placeholder="${d.search}" required><button>${d.go}</button></form><p class="hint">${d.hint}</p></div><div class="scene"><span>${d.scene}</span></div></section>${section('categories',d.catTitle,d.catLead,cats(l),`<a class="text-link" href="categories.html">${d.all}</a>`)}${section('product',d.productTitle,d.productLead,product(d),`<a class="text-link" href="product-detail.html">${d.view}</a>`)}${section('service-flow',d.serviceTitle,d.serviceLead,serviceFlow(l))}${section('articles',d.artTitle,d.artLead,articles(d),`<a class="text-link" href="seo-articles.html">${d.read}</a>`)}${section('faq',d.faqTitle,d.faqLead,faqs(d),`<a class="text-link" href="faq.html">${d.faq}</a>`)}${homeCta(d)}</main>`;
else{const key={categories:'cat',product:'product',articles:'art',faq:'faq'}[page],title={cat:d.pageCat,product:d.pageProd,art:d.pageArt,faq:d.pageFaq}[key],lead={cat:d.catLead,product:d.productLead,art:d.artLead,faq:d.faqLead}[key],content={cat:cats(l),product:product(d),art:articles(d),faq:faqs(d)}[key];body=`<main class="shell detail-page"><div class="page-head"><p class="eyebrow">${d.kicker}</p><h1>${title}</h1><p class="lead">${lead}</p></div><section class="section">${content}</section><a class="text-link" href="index.html">${d.back}</a></main>`};app.innerHTML=header(d)+body+foot;document.dispatchEvent(new Event('usfans-rendered'));const sel=document.getElementById('locale');sel.value=l;window.usfansTranslatePage?.(l);sel.onchange=e=>{localStorage.setItem('usfans-lang',e.target.value);render(e.target.value)};const f=document.getElementById('search');if(f)f.onsubmit=e=>{e.preventDefault();const q=document.getElementById('q').value.trim();if(q)location.href='https://findspreadsheet.com/search.html?keywords='+encodeURIComponent(q)+'&channelid=2'}}
const saved=localStorage.getItem('usfans-lang'),initial=T[saved]?saved:(T[(navigator.language||'en').slice(0,2)]?(navigator.language||'en').slice(0,2):'en');render(initial);
