import type { Article } from "./research-data";

type Lang = "en"|"de"|"fr"|"es"|"it"|"pt"|"nl"|"pl"|"sv";
const copy: Record<Exclude<Lang,"en">,{titles:string[];a:string;b:string}> = {
  de:{titles:["PikoBuy-Bestellablauf vor dem Kauf verstehen","QC-Fotos, Versand und Rückgaben: Prüfliste"],a:"Diese deutschsprachige Fassung erklärt den öffentlich beschriebenen PikoBuy-Ablauf mit denselben Prüfpunkten wie das englische Original. Prüfen Sie Quelllink, gewählte Variante, Lagerfotos, Gewicht und Route getrennt. Plattformangaben helfen bei der Entscheidung, ersetzen aber keine Bestätigung durch Verkäufer, Carrier oder Behörden.",b:"Halten Sie die sichtbaren Fakten fest: Originalangebot, Variante, Fotos, Maße, Schätzung und Datum. Lagerprüfung und Fotos schaffen Vergleichsmaterial, sind jedoch keine Garantie für Echtheit, verborgene Mängel, Zustellung oder Rückerstattung. Prüfen Sie zeitkritische Rückgaberegeln vor dem internationalen Versand."},
  fr:{titles:["Comprendre le parcours de commande PikoBuy avant d’acheter","Photos QC, livraison et retours : checklist"],a:"Cette version française présente le parcours PikoBuy public avec les mêmes points de contrôle que l’original anglais. Vérifiez séparément le lien source, la variante, les photos d’entrepôt, le poids et la ligne choisie. Les informations de plateforme aident à décider mais ne remplacent pas une confirmation du vendeur, du transporteur ou des autorités.",b:"Conservez les faits visibles : annonce d’origine, option, photos, mesures, estimation et date. L’inspection et les photos créent des éléments de comparaison, sans garantir l’authenticité, les défauts cachés, la livraison ou un remboursement. Vérifiez les règles de retour urgentes avant l’envoi international."},
  es:{titles:["Cómo entender el flujo de pedido de PikoBuy antes de comprar","Fotos QC, envío y devoluciones: lista de comprobación"],a:"Esta versión en español explica el flujo público de PikoBuy con los mismos controles que el original inglés. Revisa por separado el enlace de origen, la variante, las fotos de almacén, el peso y la ruta. La información de la plataforma ayuda a decidir, pero no sustituye la confirmación del vendedor, transportista o autoridades.",b:"Guarda los datos visibles: anuncio original, opción, fotos, medidas, estimación y fecha. La inspección y las fotos permiten comparar, pero no garantizan autenticidad, defectos ocultos, entrega ni reembolso. Comprueba las reglas de devolución urgentes antes del envío internacional."},
  it:{titles:["Capire il flusso d’ordine PikoBuy prima dell’acquisto","Foto QC, spedizione e resi: checklist"],a:"Questa versione italiana descrive il flusso pubblico di PikoBuy con gli stessi controlli dell’originale inglese. Verifica separatamente link fonte, variante, foto di magazzino, peso e linea scelta. Le informazioni della piattaforma aiutano a decidere ma non sostituiscono la conferma di venditore, vettore o autorità.",b:"Conserva i fatti visibili: annuncio originale, opzione, foto, misure, stima e data. Ispezione e foto offrono elementi di confronto, ma non garantiscono autenticità, difetti nascosti, consegna o rimborso. Controlla le regole di reso sensibili al tempo prima della spedizione internazionale."},
  pt:{titles:["Como entender o fluxo de pedido PikoBuy antes de comprar","Fotos QC, envio e devoluções: checklist"],a:"Esta versão em português explica o fluxo público da PikoBuy com os mesmos pontos de verificação do original inglês. Verifique separadamente o link de origem, variante, fotos do armazém, peso e rota. As informações da plataforma ajudam a decidir, mas não substituem confirmação do vendedor, transportadora ou autoridades.",b:"Guarde os factos visíveis: anúncio original, opção, fotos, medidas, estimativa e data. A inspeção e as fotos permitem comparar, mas não garantem autenticidade, defeitos ocultos, entrega ou reembolso. Verifique regras de devolução urgentes antes do envio internacional."},
  nl:{titles:["De PikoBuy-bestelstroom begrijpen vóór aankoop","QC-foto’s, verzending en retouren: checklist"],a:"Deze Nederlandse versie beschrijft de openbare PikoBuy-stappen met dezelfde controlepunten als het Engelse origineel. Controleer bronlink, variant, magazijnfoto’s, gewicht en route afzonderlijk. Platforminformatie helpt beslissen, maar vervangt geen bevestiging van verkoper, vervoerder of autoriteiten.",b:"Bewaar zichtbare feiten: oorspronkelijke aanbieding, optie, foto’s, maten, schatting en datum. Inspectie en foto’s geven vergelijkingsmateriaal, maar garanderen geen authenticiteit, verborgen gebreken, bezorging of terugbetaling. Controleer tijdgevoelige retourregels vóór internationale verzending."},
  pl:{titles:["Jak rozumieć proces zamówienia PikoBuy przed zakupem","Zdjęcia QC, wysyłka i zwroty: lista kontrolna"],a:"Ta polska wersja opisuje publiczny proces PikoBuy z tymi samymi punktami kontroli co angielski oryginał. Oddzielnie sprawdź link źródłowy, wariant, zdjęcia magazynowe, wagę i trasę. Informacje platformy pomagają podjąć decyzję, ale nie zastępują potwierdzenia sprzedawcy, przewoźnika ani władz.",b:"Zapisuj widoczne fakty: oryginalne ogłoszenie, opcję, zdjęcia, wymiary, wycenę i datę. Inspekcja oraz zdjęcia dają materiał do porównania, ale nie gwarantują autentyczności, ukrytych wad, dostawy ani zwrotu środków. Sprawdź terminy zwrotu przed wysyłką międzynarodową."},
  sv:{titles:["Förstå PikoBuys orderflöde före köp","QC-bilder, frakt och returer: checklista"],a:"Den här svenska versionen beskriver PikoBuys offentliga flöde med samma kontrollpunkter som det engelska originalet. Kontrollera källänk, variant, lagerbilder, vikt och fraktlinje var för sig. Plattformens information hjälper beslutet men ersätter inte bekräftelse från säljare, transportör eller myndighet.",b:"Spara synliga fakta: ursprunglig annons, val, bilder, mått, uppskattning och datum. Inspektion och bilder ger jämförelsematerial, men garanterar inte äkthet, dolda fel, leverans eller återbetalning. Kontrollera tidskänsliga returregler före internationell frakt."}
};

export function localizeArticle(article:Article,lang:Lang):Article{
  if(lang==="en") return article;
  const t=copy[lang], index=article.slug.includes("order-flow")?0:1;
  return {...article,title:t.titles[index],dek:t.a,sections:article.sections.map((section,i)=>({heading:`${t.titles[index]} · ${i+1}`,paragraphs:[t.a,t.b]}))};
}

export function localizeFaq(faq:string[][],lang:Lang):string[][]{
  if(lang==="en") return faq;
  const t=copy[lang];
  return faq.map((_,i)=>[`${t.titles[1]} · ${i+1}`,i%2===0?t.a:t.b]);
}
