export const supportedLocales = ["en", "de", "fr", "es", "it", "pt", "nl", "pl"] as const;
export type SiteLocale = (typeof supportedLocales)[number];

export const categorySlugs = ["shoes", "t-shirts", "hoodies-sweaters", "jackets", "pants-shorts", "bags", "accessories", "electronics"] as const;
export type CategorySlug = (typeof categorySlugs)[number];

type CategoryCopy = { title: string; focus: string; destination: string };
type UiCopy = {
  eyebrow: string; title: (category: string) => string; intro: (category: string, focus: string) => string;
  home: string; categories: string; evidence: string; evidenceIntro: string; source: string; sourceText: string;
  option: string; optionText: string; qc: string; qcText: (focus: string) => string; parcel: string; parcelText: string;
  checklist: string; checklistItems: string[]; boundary: string; boundaryText: string; related: string;
  cta: (category: string) => string; faq: string; questions: [string, string][];
};

const categories: Record<SiteLocale, Record<CategorySlug, CategoryCopy>> = {
  en: {
    shoes:{title:"Shoes",focus:"side profile, toe shape, heel alignment, outsole, size label and packed volume",destination:"shoes"},
    "t-shirts":{title:"T-shirts",focus:"chest and length measurements, fabric, seams, print placement and colour",destination:"t-shirts"},
    "hoodies-sweaters":{title:"Hoodies & sweaters",focus:"chest, length, sleeves, fabric weight, lining, cuffs and hood",destination:"hoodies-sweaters"},
    jackets:{title:"Jackets",focus:"shell, lining, closures, pockets, measurements and parcel volume",destination:"jackets"},
    "pants-shorts":{title:"Pants & shorts",focus:"waist, rise, inseam, leg opening, fabric and wash",destination:"pants-shorts"},
    bags:{title:"Bags",focus:"dimensions, interior, hardware, straps, closures and protective packaging",destination:"accessories"},
    accessories:{title:"Accessories",focus:"scale, stated material, fastening, finish and an exact source match",destination:"accessories"},
    electronics:{title:"Electronics",focus:"model, specifications, plug, included accessories, battery and route eligibility",destination:"electronics"},
  },
  de: {
    shoes:{title:"Schuhe",focus:"Profil, Zehenform, Fersenausrichtung, Sohle, Größenetikett und Paketvolumen",destination:"shoes"},"t-shirts":{title:"T-Shirts",focus:"Brust- und Längenmaße, Stoff, Nähte, Druckposition und Farbe",destination:"t-shirts"},"hoodies-sweaters":{title:"Hoodies & Pullover",focus:"Brustweite, Länge, Ärmel, Stoffgewicht, Futter, Bündchen und Kapuze",destination:"hoodies-sweaters"},jackets:{title:"Jacken",focus:"Außenstoff, Futter, Verschlüsse, Taschen, Maße und Paketvolumen",destination:"jackets"},"pants-shorts":{title:"Hosen & Shorts",focus:"Bund, Leibhöhe, Innenbein, Beinöffnung, Stoff und Waschung",destination:"pants-shorts"},bags:{title:"Taschen",focus:"Maße, Innenraum, Beschläge, Riemen, Verschlüsse und Schutzverpackung",destination:"accessories"},accessories:{title:"Accessoires",focus:"Größe, angegebenes Material, Befestigung, Finish und genaue Quellenübereinstimmung",destination:"accessories"},electronics:{title:"Elektronik",focus:"Modell, technische Daten, Stecker, Zubehör, Akku und Routenzulassung",destination:"electronics"},
  },
  fr: {
    shoes:{title:"Chaussures",focus:"profil, forme de l’avant, talon, semelle, étiquette de taille et volume emballé",destination:"shoes"},"t-shirts":{title:"T-shirts",focus:"mesures poitrine et longueur, tissu, coutures, placement de l’impression et couleur",destination:"t-shirts"},"hoodies-sweaters":{title:"Sweats & pulls",focus:"poitrine, longueur, manches, poids du tissu, doublure, poignets et capuche",destination:"hoodies-sweaters"},jackets:{title:"Vestes",focus:"extérieur, doublure, fermetures, poches, mesures et volume du colis",destination:"jackets"},"pants-shorts":{title:"Pantalons & shorts",focus:"taille, fourche, entrejambe, ouverture, tissu et lavage",destination:"pants-shorts"},bags:{title:"Sacs",focus:"dimensions, intérieur, pièces métalliques, sangles, fermetures et protection",destination:"accessories"},accessories:{title:"Accessoires",focus:"échelle, matière annoncée, fixation, finition et correspondance exacte de la source",destination:"accessories"},electronics:{title:"Électronique",focus:"modèle, caractéristiques, prise, accessoires, batterie et admissibilité de la route",destination:"electronics"},
  },
  es: {
    shoes:{title:"Calzado",focus:"perfil, puntera, talón, suela, etiqueta de talla y volumen embalado",destination:"shoes"},"t-shirts":{title:"Camisetas",focus:"medidas de pecho y largo, tejido, costuras, posición del estampado y color",destination:"t-shirts"},"hoodies-sweaters":{title:"Sudaderas & suéteres",focus:"pecho, largo, mangas, peso del tejido, forro, puños y capucha",destination:"hoodies-sweaters"},jackets:{title:"Chaquetas",focus:"exterior, forro, cierres, bolsillos, medidas y volumen del paquete",destination:"jackets"},"pants-shorts":{title:"Pantalones & shorts",focus:"cintura, tiro, entrepierna, abertura, tejido y lavado",destination:"pants-shorts"},bags:{title:"Bolsos",focus:"dimensiones, interior, herrajes, correas, cierres y embalaje protector",destination:"accessories"},accessories:{title:"Accesorios",focus:"escala, material declarado, sujeción, acabado y coincidencia exacta de la fuente",destination:"accessories"},electronics:{title:"Electrónica",focus:"modelo, especificaciones, enchufe, accesorios, batería y admisión de la ruta",destination:"electronics"},
  },
  it: {
    shoes:{title:"Scarpe",focus:"profilo, punta, tallone, suola, etichetta taglia e volume imballato",destination:"shoes"},"t-shirts":{title:"T-shirt",focus:"misure di torace e lunghezza, tessuto, cuciture, posizione della stampa e colore",destination:"t-shirts"},"hoodies-sweaters":{title:"Felpe & maglioni",focus:"torace, lunghezza, maniche, peso del tessuto, fodera, polsini e cappuccio",destination:"hoodies-sweaters"},jackets:{title:"Giacche",focus:"esterno, fodera, chiusure, tasche, misure e volume del pacco",destination:"jackets"},"pants-shorts":{title:"Pantaloni & shorts",focus:"vita, cavallo, interno gamba, apertura, tessuto e lavaggio",destination:"pants-shorts"},bags:{title:"Borse",focus:"dimensioni, interno, metalli, tracolle, chiusure e imballaggio protettivo",destination:"accessories"},accessories:{title:"Accessori",focus:"scala, materiale dichiarato, fissaggio, finitura e corrispondenza esatta della fonte",destination:"accessories"},electronics:{title:"Elettronica",focus:"modello, specifiche, spina, accessori, batteria e idoneità della rotta",destination:"electronics"},
  },
  pt: {
    shoes:{title:"Calçado",focus:"perfil, biqueira, calcanhar, sola, etiqueta de tamanho e volume embalado",destination:"shoes"},"t-shirts":{title:"T-shirts",focus:"medidas de peito e comprimento, tecido, costuras, posição da impressão e cor",destination:"t-shirts"},"hoodies-sweaters":{title:"Hoodies & camisolas",focus:"peito, comprimento, mangas, peso do tecido, forro, punhos e capuz",destination:"hoodies-sweaters"},jackets:{title:"Casacos",focus:"exterior, forro, fechos, bolsos, medidas e volume do pacote",destination:"jackets"},"pants-shorts":{title:"Calças & calções",focus:"cintura, gancho, entreperna, abertura, tecido e lavagem",destination:"pants-shorts"},bags:{title:"Malas",focus:"dimensões, interior, ferragens, alças, fechos e embalagem protetora",destination:"accessories"},accessories:{title:"Acessórios",focus:"escala, material declarado, fixação, acabamento e correspondência exata da fonte",destination:"accessories"},electronics:{title:"Eletrónica",focus:"modelo, especificações, ficha, acessórios, bateria e elegibilidade da rota",destination:"electronics"},
  },
  nl: {
    shoes:{title:"Schoenen",focus:"zijprofiel, neus, hiel, zool, maatlabel en verpakt volume",destination:"shoes"},"t-shirts":{title:"T-shirts",focus:"borst- en lengtematen, stof, naden, printplaatsing en kleur",destination:"t-shirts"},"hoodies-sweaters":{title:"Hoodies & truien",focus:"borst, lengte, mouwen, stofgewicht, voering, boorden en capuchon",destination:"hoodies-sweaters"},jackets:{title:"Jassen",focus:"buitenstof, voering, sluitingen, zakken, maten en pakketvolume",destination:"jackets"},"pants-shorts":{title:"Broeken & shorts",focus:"taille, kruis, binnenbeen, pijpopening, stof en wassing",destination:"pants-shorts"},bags:{title:"Tassen",focus:"afmetingen, binnenkant, beslag, riemen, sluitingen en beschermende verpakking",destination:"accessories"},accessories:{title:"Accessoires",focus:"schaal, opgegeven materiaal, bevestiging, afwerking en exacte bronmatch",destination:"accessories"},electronics:{title:"Elektronica",focus:"model, specificaties, stekker, accessoires, batterij en routetoelating",destination:"electronics"},
  },
  pl: {
    shoes:{title:"Buty",focus:"profil, nosek, pięta, podeszwa, etykieta rozmiaru i objętość paczki",destination:"shoes"},"t-shirts":{title:"Koszulki",focus:"wymiary klatki i długości, materiał, szwy, położenie nadruku i kolor",destination:"t-shirts"},"hoodies-sweaters":{title:"Bluzy & swetry",focus:"klatka, długość, rękawy, gramatura, podszewka, ściągacze i kaptur",destination:"hoodies-sweaters"},jackets:{title:"Kurtki",focus:"materiał zewnętrzny, podszewka, zapięcia, kieszenie, wymiary i objętość",destination:"jackets"},"pants-shorts":{title:"Spodnie & szorty",focus:"pas, stan, nogawka wewnętrzna, otwór nogawki, materiał i spranie",destination:"pants-shorts"},bags:{title:"Torby",focus:"wymiary, wnętrze, okucia, paski, zapięcia i opakowanie ochronne",destination:"accessories"},accessories:{title:"Akcesoria",focus:"skala, deklarowany materiał, mocowanie, wykończenie i zgodność źródła",destination:"accessories"},electronics:{title:"Elektronika",focus:"model, specyfikacja, wtyczka, akcesoria, bateria i dopuszczenie trasy",destination:"electronics"},
  },
};

const enUi: UiCopy = {
  eyebrow:"CATEGORY RESEARCH",title:c=>`${c} PikoBuy spreadsheet guide`,intro:(c,f)=>`Use this ${c.toLowerCase()} category page to narrow your research before opening a product result. Verify ${f}; then recheck the live listing and order details before payment.`,home:"Home",categories:"Categories",evidence:"Evidence to check first",evidenceIntro:"A useful category page organizes the questions. It does not certify a seller, product or current availability.",source:"Source match",sourceText:"Open the original listing and compare its images, options and current details with the saved result.",option:"Exact option",optionText:"Record the intended colour, size, model and quantity exactly as the live listing shows them.",qc:"Category-specific QC",qcText:f=>`Ask for views or measurements that show ${f}. A general photo cannot answer every question.`,parcel:"Parcel impact",parcelText:"Replace early estimates with warehouse weight, packed dimensions and the routes currently offered for the exact destination.",checklist:"Before you open a result",checklistItems:["Start with the correct category and a live source link.","Write down the exact option before the first payment.","Compare warehouse evidence with the saved source and order.","Check return eligibility and parcel impact before the deadline."],boundary:"What this page cannot promise",boundaryText:"Prices, stock, seller listings, warehouse outcomes, route eligibility and final freight can change. This independent page cannot see an account or guarantee quality, authenticity, delivery or a return.",related:"Related category guides",cta:c=>`Browse ${c.toLowerCase()} results`,faq:"Quick questions",questions:[["Does this page list live stock?","No. Open the current result and source listing to check availability and options."],["Are products or sellers verified here?","No. The page provides a repeatable research checklist, not an endorsement."],["Can a spreadsheet price be treated as the final cost?","No. Recheck the purchase price and add current parcel, route and destination costs."]]
};

const ui: Record<SiteLocale, UiCopy> = {
  en: enUi,
  de:{...enUi,eyebrow:"KATEGORIE-RECHERCHE",title:c=>`${c}: PikoBuy-Spreadsheet-Ratgeber`,intro:(c,f)=>`Nutzen Sie diese ${c}-Seite zur Eingrenzung Ihrer Recherche. Prüfen Sie ${f} und gleichen Sie vor der Zahlung das aktuelle Angebot und die Bestellung ab.`,home:"Startseite",categories:"Kategorien",evidence:"Diese Belege zuerst prüfen",evidenceIntro:"Eine gute Kategorieseite ordnet Fragen. Sie bestätigt weder Verkäufer noch Produkt oder Bestand.",source:"Quelle abgleichen",sourceText:"Öffnen Sie das Originalangebot und vergleichen Sie Bilder, Optionen und aktuelle Angaben.",option:"Genaue Option",optionText:"Notieren Sie Farbe, Größe, Modell und Menge genau wie im aktuellen Angebot.",qc:"Kategoriebezogene QC",qcText:f=>`Fordern Sie Ansichten oder Maße zu ${f} an. Ein allgemeines Foto beantwortet nicht jede Frage.`,parcel:"Paketauswirkung",parcelText:"Ersetzen Sie Schätzungen durch Lagergewicht, Paketmaße und aktuell verfügbare Routen.",checklist:"Vor dem Öffnen eines Ergebnisses",checklistItems:["Mit passender Kategorie und aktueller Quelle beginnen.","Genaue Option vor der ersten Zahlung notieren.","Lagerbelege mit Quelle und Bestellung vergleichen.","Rückgabe und Paketauswirkung rechtzeitig prüfen."],boundary:"Was diese Seite nicht verspricht",boundaryText:"Preis, Bestand, Angebot, Lagerergebnis, Route und Endfracht können sich ändern. Diese unabhängige Seite garantiert weder Qualität, Echtheit, Lieferung noch Rückgabe.",related:"Verwandte Kategorien",cta:c=>`${c}-Ergebnisse durchsuchen`,faq:"Kurze Fragen",questions:[["Zeigt diese Seite Live-Bestand?","Nein. Prüfen Sie Verfügbarkeit und Optionen im aktuellen Angebot."],["Sind Produkte oder Verkäufer hier verifiziert?","Nein. Dies ist eine Checkliste, keine Empfehlung."],["Ist der Tabellenpreis der Endpreis?","Nein. Prüfen Sie Kaufpreis, Paket, Route und Ziel erneut."]]},
  fr:{...enUi,eyebrow:"RECHERCHE PAR CATÉGORIE",title:c=>`Guide PikoBuy Spreadsheet : ${c}`,intro:(c,f)=>`Utilisez cette page ${c.toLowerCase()} pour cibler la recherche. Vérifiez ${f}, puis contrôlez l’annonce et la commande actuelles avant paiement.`,home:"Accueil",categories:"Catégories",evidence:"Preuves à vérifier d’abord",evidenceIntro:"Une page de catégorie organise les questions; elle ne certifie ni vendeur, ni produit, ni stock.",source:"Correspondance de la source",sourceText:"Ouvrez l’annonce d’origine et comparez images, options et informations actuelles.",option:"Option exacte",optionText:"Notez couleur, taille, modèle et quantité exactement comme sur l’annonce actuelle.",qc:"QC propre à la catégorie",qcText:f=>`Demandez des vues ou mesures montrant ${f}. Une photo générale ne suffit pas.`,parcel:"Impact sur le colis",parcelText:"Remplacez l’estimation par le poids, les dimensions emballées et les routes proposées actuellement.",checklist:"Avant d’ouvrir un résultat",checklistItems:["Commencer par la bonne catégorie et une source active.","Noter l’option exacte avant le premier paiement.","Comparer les preuves d’entrepôt avec la source et la commande.","Vérifier retour et impact colis avant l’échéance."],boundary:"Ce que cette page ne promet pas",boundaryText:"Prix, stock, annonce, résultat d’entrepôt, route et fret final peuvent changer. Cette page indépendante ne garantit ni qualité, authenticité, livraison ou retour.",related:"Catégories associées",cta:c=>`Parcourir les résultats ${c.toLowerCase()}`,faq:"Questions rapides",questions:[["Cette page affiche-t-elle le stock en direct ?","Non. Vérifiez disponibilité et options sur l’annonce actuelle."],["Les produits ou vendeurs sont-ils vérifiés ici ?","Non. Il s’agit d’une méthode de recherche, pas d’une recommandation."],["Le prix du tableau est-il le coût final ?","Non. Revérifiez achat, colis, route et destination."]]},
  es:{...enUi,eyebrow:"INVESTIGACIÓN POR CATEGORÍA",title:c=>`Guía PikoBuy Spreadsheet de ${c}`,intro:(c,f)=>`Usa esta página de ${c.toLowerCase()} para enfocar la búsqueda. Comprueba ${f} y vuelve a revisar el anuncio y pedido actuales antes de pagar.`,home:"Inicio",categories:"Categorías",evidence:"Pruebas que debes comprobar",evidenceIntro:"Una página de categoría ordena preguntas; no certifica vendedores, productos ni existencias.",source:"Coincidencia de fuente",sourceText:"Abre el anuncio original y compara imágenes, opciones y datos actuales.",option:"Opción exacta",optionText:"Anota color, talla, modelo y cantidad tal como aparecen en el anuncio actual.",qc:"QC por categoría",qcText:f=>`Pide vistas o medidas que muestren ${f}. Una foto general no basta.`,parcel:"Impacto del paquete",parcelText:"Sustituye estimaciones por peso, medidas embaladas y rutas ofrecidas para el destino exacto.",checklist:"Antes de abrir un resultado",checklistItems:["Empieza con la categoría correcta y una fuente activa.","Anota la opción exacta antes del primer pago.","Compara las pruebas de almacén con fuente y pedido.","Revisa devolución e impacto del paquete a tiempo."],boundary:"Lo que esta página no promete",boundaryText:"Precio, stock, anuncio, almacén, ruta y flete final pueden cambiar. Esta página independiente no garantiza calidad, autenticidad, entrega ni devolución.",related:"Categorías relacionadas",cta:c=>`Ver resultados de ${c.toLowerCase()}`,faq:"Preguntas rápidas",questions:[["¿Muestra stock en tiempo real?","No. Comprueba disponibilidad y opciones en el anuncio actual."],["¿Verifica productos o vendedores?","No. Es una lista de investigación, no un aval."],["¿El precio de la hoja es el coste final?","No. Revisa compra, paquete, ruta y destino."]]},
  it:{...enUi,eyebrow:"RICERCA PER CATEGORIA",title:c=>`Guida PikoBuy Spreadsheet: ${c}`,intro:(c,f)=>`Usa questa pagina ${c.toLowerCase()} per restringere la ricerca. Verifica ${f}, poi ricontrolla annuncio e ordine attuali prima del pagamento.`,home:"Home",categories:"Categorie",evidence:"Prove da controllare",evidenceIntro:"Una pagina di categoria organizza le domande; non certifica venditore, prodotto o disponibilità.",source:"Corrispondenza della fonte",sourceText:"Apri l’annuncio originale e confronta immagini, opzioni e dati attuali.",option:"Opzione esatta",optionText:"Annota colore, taglia, modello e quantità come mostrati nell’annuncio attuale.",qc:"QC per categoria",qcText:f=>`Richiedi viste o misure che mostrino ${f}. Una foto generica non basta.`,parcel:"Impatto sul pacco",parcelText:"Sostituisci le stime con peso, misure imballate e rotte attualmente disponibili.",checklist:"Prima di aprire un risultato",checklistItems:["Inizia dalla categoria corretta e da una fonte attiva.","Registra l’opzione esatta prima del primo pagamento.","Confronta prove di magazzino, fonte e ordine.","Controlla reso e impatto del pacco in tempo."],boundary:"Cosa non promette questa pagina",boundaryText:"Prezzo, stock, annuncio, magazzino, rotta e nolo finale possono cambiare. Questa pagina indipendente non garantisce qualità, autenticità, consegna o reso.",related:"Categorie correlate",cta:c=>`Sfoglia risultati ${c.toLowerCase()}`,faq:"Domande rapide",questions:[["Mostra stock in tempo reale?","No. Verifica disponibilità e opzioni nell’annuncio attuale."],["Prodotti o venditori sono verificati?","No. È una checklist, non un’approvazione."],["Il prezzo del foglio è il costo finale?","No. Ricontrolla acquisto, pacco, rotta e destinazione."]]},
  pt:{...enUi,eyebrow:"PESQUISA POR CATEGORIA",title:c=>`Guia PikoBuy Spreadsheet: ${c}`,intro:(c,f)=>`Use esta página de ${c.toLowerCase()} para focar a pesquisa. Confirme ${f} e volte a verificar anúncio e pedido atuais antes do pagamento.`,home:"Início",categories:"Categorias",evidence:"Provas a verificar primeiro",evidenceIntro:"Uma página de categoria organiza perguntas; não certifica vendedor, produto ou stock.",source:"Correspondência da fonte",sourceText:"Abra o anúncio original e compare imagens, opções e dados atuais.",option:"Opção exata",optionText:"Registe cor, tamanho, modelo e quantidade tal como aparecem no anúncio atual.",qc:"QC por categoria",qcText:f=>`Peça vistas ou medidas que mostrem ${f}. Uma foto geral não basta.`,parcel:"Impacto no pacote",parcelText:"Substitua estimativas por peso, dimensões embaladas e rotas atuais para o destino exato.",checklist:"Antes de abrir um resultado",checklistItems:["Comece pela categoria certa e uma fonte ativa.","Registe a opção exata antes do primeiro pagamento.","Compare provas do armazém com fonte e pedido.","Verifique devolução e impacto no pacote a tempo."],boundary:"O que esta página não promete",boundaryText:"Preço, stock, anúncio, armazém, rota e frete final podem mudar. Esta página independente não garante qualidade, autenticidade, entrega ou devolução.",related:"Categorias relacionadas",cta:c=>`Ver resultados de ${c.toLowerCase()}`,faq:"Perguntas rápidas",questions:[["Mostra stock em tempo real?","Não. Verifique disponibilidade e opções no anúncio atual."],["Produtos ou vendedores são verificados?","Não. É uma checklist de pesquisa, não uma recomendação."],["O preço da folha é o custo final?","Não. Reveja compra, pacote, rota e destino."]]},
  nl:{...enUi,eyebrow:"ONDERZOEK PER CATEGORIE",title:c=>`${c} PikoBuy-spreadsheetgids`,intro:(c,f)=>`Gebruik deze ${c.toLowerCase()}pagina om je onderzoek te richten. Controleer ${f} en vergelijk vóór betaling de actuele advertentie en bestelling.`,home:"Start",categories:"Categorieën",evidence:"Bewijs om eerst te controleren",evidenceIntro:"Een categoriepagina ordent vragen; ze certificeert geen verkoper, product of voorraad.",source:"Bron vergelijken",sourceText:"Open de originele advertentie en vergelijk afbeeldingen, opties en actuele gegevens.",option:"Exacte optie",optionText:"Noteer kleur, maat, model en aantal precies zoals de actuele advertentie ze toont.",qc:"QC per categorie",qcText:f=>`Vraag beelden of maten die ${f} tonen. Een algemene foto is niet genoeg.`,parcel:"Pakketimpact",parcelText:"Vervang schattingen door magazijngewicht, verpakte maten en actuele routes voor de bestemming.",checklist:"Voordat je een resultaat opent",checklistItems:["Begin met de juiste categorie en een actieve bron.","Noteer de exacte optie vóór de eerste betaling.","Vergelijk magazijnbewijs met bron en bestelling.","Controleer retour en pakketimpact op tijd."],boundary:"Wat deze pagina niet belooft",boundaryText:"Prijs, voorraad, advertentie, magazijnuitkomst, route en vracht kunnen wijzigen. Deze onafhankelijke pagina garandeert geen kwaliteit, echtheid, levering of retour.",related:"Gerelateerde categorieën",cta:c=>`Bekijk ${c.toLowerCase()}resultaten`,faq:"Korte vragen",questions:[["Toont deze pagina live voorraad?","Nee. Controleer beschikbaarheid en opties in de actuele advertentie."],["Zijn producten of verkopers geverifieerd?","Nee. Dit is een onderzoeksmethode, geen aanbeveling."],["Is de spreadsheetprijs de eindprijs?","Nee. Controleer aankoop, pakket, route en bestemming opnieuw."]]},
  pl:{...enUi,eyebrow:"BADANIE KATEGORII",title:c=>`${c} — poradnik PikoBuy Spreadsheet`,intro:(c,f)=>`Użyj strony ${c.toLowerCase()}, aby zawęzić badanie. Sprawdź ${f}, a przed płatnością ponownie porównaj aktualną ofertę i zamówienie.`,home:"Strona główna",categories:"Kategorie",evidence:"Dowody do sprawdzenia",evidenceIntro:"Strona kategorii porządkuje pytania; nie certyfikuje sprzedawcy, produktu ani stanu.",source:"Zgodność źródła",sourceText:"Otwórz oryginalną ofertę i porównaj zdjęcia, opcje oraz bieżące dane.",option:"Dokładna opcja",optionText:"Zapisz kolor, rozmiar, model i liczbę dokładnie tak jak w aktualnej ofercie.",qc:"QC dla kategorii",qcText:f=>`Poproś o ujęcia lub wymiary pokazujące ${f}. Ogólne zdjęcie nie wystarczy.`,parcel:"Wpływ na paczkę",parcelText:"Zastąp szacunki wagą magazynową, wymiarami paczki i bieżącymi trasami dla celu.",checklist:"Przed otwarciem wyniku",checklistItems:["Zacznij od właściwej kategorii i aktywnego źródła.","Zapisz dokładną opcję przed pierwszą płatnością.","Porównaj dowody magazynowe ze źródłem i zamówieniem.","Sprawdź zwrot i wpływ na paczkę przed terminem."],boundary:"Czego ta strona nie obiecuje",boundaryText:"Cena, stan, oferta, magazyn, trasa i fracht mogą się zmieniać. Niezależna strona nie gwarantuje jakości, autentyczności, dostawy ani zwrotu.",related:"Powiązane kategorie",cta:c=>`Przeglądaj wyniki: ${c.toLowerCase()}`,faq:"Krótkie pytania",questions:[["Czy strona pokazuje stan na żywo?","Nie. Sprawdź dostępność i opcje w aktualnej ofercie."],["Czy produkty lub sprzedawcy są zweryfikowani?","Nie. To metoda badania, nie rekomendacja."],["Czy cena z arkusza jest końcowa?","Nie. Sprawdź zakup, paczkę, trasę i cel ponownie."]]}
};

export function getCategory(locale: SiteLocale, slug: CategorySlug) { return categories[locale][slug]; }
export function getCategoryUi(locale: SiteLocale) { return ui[locale]; }
export function categoryPath(locale: SiteLocale, slug: CategorySlug) { return locale === "en" ? `/categories/${slug}` : `/${locale}/categories/${slug}`; }
export function categoryAlternates(slug: CategorySlug) { return Object.fromEntries(supportedLocales.map(locale => [locale, `https://pikobuyspreadsheet.me${categoryPath(locale, slug)}`])); }
