import { CheckCircle2 } from "lucide-react";

type Locale="en"|"de"|"fr"|"es"|"it"|"pt"|"nl"|"pl";
const copy:Record<Locale,{pathK:string;pathH:string;pathP:string;steps:string[];coverK:string;coverH:string;cards:Array<[string,string]>}>={
 en:{pathK:"COMPLETE RESEARCH PATH",pathH:"The same five stages in every language.",pathP:"Changing language never removes a stage, article card or supporting section.",steps:["Understand the platform process","Match the live source and option","Review category-specific QC evidence","Plan weight, dimensions and route","Record a keep, question or stop decision"],coverK:"FULL CONTENT COVERAGE",coverH:"Useful detail before opening a result.",cards:[["Source evidence","Keep the current URL, seller, selected option, visible price and date checked."],["QC decisions","Match photos and measurements to the category instead of trusting one attractive image."],["Parcel context","Separate product price from packaging, billable weight, destination and the live route."],["Current limits","Treat stock, price, returns and shipping choices as changeable live data."]]},
 de:{pathK:"VOLLSTÄNDIGER RECHERCHEWEG",pathH:"Dieselben fünf Stufen in jeder Sprache.",pathP:"Ein Sprachwechsel entfernt keine Stufe, Artikelkarte oder ergänzende Sektion.",steps:["Plattformablauf verstehen","Aktuelle Quelle und Variante abgleichen","Kategoriespezifische QC-Belege prüfen","Gewicht, Maße und Route planen","Behalten-, Nachfragen- oder Stoppentscheidung dokumentieren"],coverK:"VOLLSTÄNDIGE INHALTE",coverH:"Nützliche Details vor dem Öffnen eines Ergebnisses.",cards:[["Quellenbelege","Aktuelle URL, Verkäufer, gewählte Variante, sichtbaren Preis und Prüfdatum festhalten."],["QC-Entscheidungen","Fotos und Maße an der Kategorie ausrichten, statt nur einem attraktiven Bild zu vertrauen."],["Paketkontext","Produktpreis von Verpackung, abrechenbarem Gewicht, Ziel und Live-Route trennen."],["Aktuelle Grenzen","Bestand, Preis, Rückgabe und Versandoptionen als veränderliche Live-Daten behandeln."]]},
 fr:{pathK:"PARCOURS DE RECHERCHE COMPLET",pathH:"Les cinq mêmes étapes dans chaque langue.",pathP:"Changer de langue ne supprime aucune étape, carte d’article ou section complémentaire.",steps:["Comprendre le fonctionnement","Comparer la source et l’option actuelles","Examiner les preuves QC par catégorie","Planifier poids, dimensions et itinéraire","Noter une décision : conserver, questionner ou arrêter"],coverK:"CONTENU COMPLET",coverH:"Des détails utiles avant d’ouvrir un résultat.",cards:[["Preuves de source","Conserver l’URL, le vendeur, l’option choisie, le prix visible et la date de contrôle."],["Décisions QC","Adapter photos et mesures à la catégorie plutôt que se fier à une seule belle image."],["Contexte du colis","Séparer prix, emballage, poids facturable, destination et itinéraire actuel."],["Limites actuelles","Considérer stock, prix, retour et livraison comme des données en direct susceptibles de changer."]]},
 es:{pathK:"RUTA DE INVESTIGACIÓN COMPLETA",pathH:"Las mismas cinco etapas en todos los idiomas.",pathP:"Cambiar de idioma no elimina ninguna etapa, tarjeta de artículo ni sección de apoyo.",steps:["Entender el proceso","Comparar fuente y variante actuales","Revisar pruebas QC según la categoría","Planificar peso, medidas y ruta","Registrar una decisión: guardar, preguntar o parar"],coverK:"CONTENIDO COMPLETO",coverH:"Detalles útiles antes de abrir un resultado.",cards:[["Prueba de origen","Guarda URL, vendedor, opción elegida, precio visible y fecha de revisión."],["Decisiones QC","Adapta fotos y medidas a la categoría en vez de confiar en una sola imagen atractiva."],["Contexto del paquete","Separa precio, embalaje, peso facturable, destino y ruta actual."],["Límites actuales","Trata stock, precio, devolución y envío como datos vivos que pueden cambiar."]]},
 it:{pathK:"PERCORSO DI RICERCA COMPLETO",pathH:"Le stesse cinque fasi in ogni lingua.",pathP:"Cambiare lingua non elimina fasi, schede articolo o sezioni di supporto.",steps:["Capire il processo","Confrontare fonte e variante attuali","Esaminare prove QC per categoria","Pianificare peso, dimensioni e rotta","Registrare una decisione: tenere, chiedere o fermarsi"],coverK:"CONTENUTO COMPLETO",coverH:"Dettagli utili prima di aprire un risultato.",cards:[["Prove della fonte","Salva URL, venditore, opzione scelta, prezzo visibile e data del controllo."],["Decisioni QC","Adatta foto e misure alla categoria invece di fidarti di una sola immagine attraente."],["Contesto del pacco","Separa prezzo, imballaggio, peso fatturabile, destinazione e rotta attuale."],["Limiti attuali","Considera stock, prezzo, reso e spedizione come dati live modificabili."]]},
 pt:{pathK:"PERCURSO COMPLETO DE PESQUISA",pathH:"As mesmas cinco etapas em todos os idiomas.",pathP:"Mudar de idioma não remove etapas, cartões de artigos ou secções de apoio.",steps:["Compreender o processo","Comparar fonte e opção atuais","Rever provas QC por categoria","Planear peso, dimensões e rota","Registar uma decisão: guardar, perguntar ou parar"],coverK:"CONTEÚDO COMPLETO",coverH:"Detalhes úteis antes de abrir um resultado.",cards:[["Prova da fonte","Guarde URL, vendedor, opção escolhida, preço visível e data de verificação."],["Decisões QC","Adapte fotos e medidas à categoria em vez de confiar numa única imagem atraente."],["Contexto do pacote","Separe preço, embalagem, peso faturável, destino e rota atual."],["Limites atuais","Trate stock, preço, devolução e envio como dados atuais que podem mudar."]]},
 nl:{pathK:"VOLLEDIGE ONDERZOEKSROUTE",pathH:"Dezelfde vijf stappen in elke taal.",pathP:"Een taalwissel verwijdert geen stap, artikelkaart of ondersteunende sectie.",steps:["Het proces begrijpen","Actuele bron en optie vergelijken","Categoriegericht QC-bewijs controleren","Gewicht, afmetingen en route plannen","Een bewaren-, vragen- of stopbeslissing vastleggen"],coverK:"VOLLEDIGE INHOUD",coverH:"Nuttige details voordat je een resultaat opent.",cards:[["Bronbewijs","Bewaar URL, verkoper, gekozen optie, zichtbare prijs en controledatum."],["QC-beslissingen","Stem foto's en maten af op de categorie in plaats van één aantrekkelijke foto te vertrouwen."],["Pakketcontext","Scheid prijs van verpakking, factureerbaar gewicht, bestemming en actuele route."],["Actuele grenzen","Behandel voorraad, prijs, retour en verzending als veranderlijke livegegevens."]]},
 pl:{pathK:"PEŁNA ŚCIEŻKA BADAŃ",pathH:"Te same pięć etapów w każdym języku.",pathP:"Zmiana języka nie usuwa etapu, karty artykułu ani sekcji pomocniczej.",steps:["Zrozumieć proces","Porównać aktualne źródło i wariant","Sprawdzić dowody QC dla kategorii","Zaplanować wagę, wymiary i trasę","Zapisać decyzję: zachować, zapytać lub zatrzymać"],coverK:"PEŁNA ZAWARTOŚĆ",coverH:"Przydatne szczegóły przed otwarciem wyniku.",cards:[["Dowód źródłowy","Zapisz URL, sprzedawcę, wariant, widoczną cenę i datę sprawdzenia."],["Decyzje QC","Dopasuj zdjęcia i wymiary do kategorii zamiast ufać jednemu atrakcyjnemu obrazowi."],["Kontekst paczki","Oddziel cenę od opakowania, wagi rozliczeniowej, celu i aktualnej trasy."],["Aktualne granice","Traktuj stan, cenę, zwrot i wysyłkę jako zmienne dane na żywo."]]}
};

export default function SeoParitySections({lang}:{lang:Locale}){const t=copy[lang];return <>
 <section className="section seo-path"><div className="section-heading"><div><p className="kicker">{t.pathK}</p><h2>{t.pathH}</h2></div><p>{t.pathP}</p></div><ol>{t.steps.map((step,i)=><li key={step}><span>{String(i+1).padStart(2,"0")}</span><b>{step}</b></li>)}</ol></section>
 <section className="section seo-coverage"><div className="section-heading"><div><p className="kicker">{t.coverK}</p><h2>{t.coverH}</h2></div></div><div>{t.cards.map(([heading,body])=><article key={heading}><CheckCircle2/><h3>{heading}</h3><p>{body}</p></article>)}</div></section>
 </>}
