"use client";

import { useEffect, useState } from "react";
import { ArrowRight, BookOpen, Box, Check, ChevronRight, CircleDollarSign, ExternalLink, FileCheck2, Globe2, PackageCheck, Search, ShieldCheck, Shirt, ShoppingBag, Sparkles, Truck, Weight } from "lucide-react";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import type { ArticleRecord } from "@/components/article-data";
import { localizedFaqs } from "@/components/localized-content";
import { extrasByLocale, localizedArticleRecords } from "@/components/full-locales";

const langs=[["en","English"],["es","Español"],["de","Deutsch"],["fr","Français"],["it","Italiano"],["pt","Português"],["nl","Nederlands"],["pl","Polski"],["sv","Svenska"]] as const;
const LANGUAGE_STORAGE_KEY="pikobuy-preferred-language";
const pageKeys=["home","categories","products","guides","shipping","articles","faq","sources"] as const;
type Lang=typeof langs[number][0]; type Page=typeof pageKeys[number];

const ui:Record<string,any>={
 en:{nav:["Home","Categories","Product details","Guides","Shipping","SEO articles","FAQ"],pages:["PikoBuy Spreadsheet 2026","PikoBuy product categories","Product detail research","PikoBuy buying guides","Shipping, weight and routes","PikoBuy research articles","Frequently asked questions","Sources and editorial policy"],sub:["A useful spreadsheet is not just a list of links. It helps shoppers move from discovery to source checks, warehouse QC and a realistic shipping decision.","Ten focused routes into the FindSpreadsheet product database, each with its own inspection priorities.","Use product pages as research leads. Recheck the source, option, measurements, warehouse photos and shipping context before paying freight.","A practical workflow based on PikoBuy’s published purchase, warehouse inspection and forwarding process.","Understand the difference between item price and landed cost before building an international parcel.","Evidence-led articles for users comparing PikoBuy finds, QC photographs, sizing, returns and international shipping.","Direct answers without invented guarantees, fake reviews or unsupported platform claims.","How this independent guide checks, dates and separates official platform facts from editorial advice."],search:"Search products or paste a source link",button:"Search FindSpreadsheet",database:"Open the FindSpreadsheet product database",browse:"Browse all products",independent:"Independent guide · Not an official PikoBuy website",updated:"Official facts checked August 2026",read:"Read full guide",check:"What to check",official:"Officially documented",editorial:"Editorial advice",cta:"Open the PikoBuy spreadsheet hub",ctasub:"Browse the product database on FindSpreadsheet, then verify the source and warehouse details before shipping."},
 es:{nav:["Inicio","Categorías","Detalles","Guías","Envíos","Artículos SEO","Preguntas"],pages:["Hoja PikoBuy 2026","Categorías de productos PikoBuy","Investigación de productos","Guías de compra PikoBuy","Envíos, peso y rutas","Artículos de investigación PikoBuy","Preguntas frecuentes","Fuentes y política editorial"],sub:["Una buena hoja no es solo una lista de enlaces: ayuda a pasar del descubrimiento a la fuente, el control de almacén y el envío.","Diez rutas a la base de FindSpreadsheet, cada una con controles propios.","Usa las páginas como pistas. Comprueba fuente, opción, medidas, fotos QC y envío.","Flujo práctico basado en el proceso publicado de compra, inspección y reenvío de PikoBuy.","Distingue entre el precio del artículo y el coste final antes de crear un paquete.","Artículos con fuentes sobre productos, fotos QC, tallas, devoluciones y envíos.","Respuestas directas sin garantías inventadas ni reseñas falsas.","Cómo verificamos, fechamos y separamos hechos oficiales de consejos editoriales."],search:"Buscar productos o pegar un enlace",button:"Buscar en FindSpreadsheet",browse:"Ver todos los productos",independent:"Guía independiente · No es la web oficial de PikoBuy",updated:"Datos oficiales revisados en agosto de 2026",read:"Leer guía completa",check:"Qué comprobar",official:"Documentado oficialmente",editorial:"Consejo editorial",cta:"Abrir el centro de PikoBuy",ctasub:"Explora FindSpreadsheet y verifica la fuente y el almacén antes del envío."},
 de:{nav:["Start","Kategorien","Produktdetails","Ratgeber","Versand","SEO-Artikel","FAQ"],pages:["PikoBuy Spreadsheet 2026","PikoBuy-Produktkategorien","Produktrecherche","PikoBuy-Kaufratgeber","Versand, Gewicht und Routen","PikoBuy-Fachartikel","Häufige Fragen","Quellen und Redaktion"],sub:["Eine gute Tabelle ist mehr als eine Linkliste: Sie führt von der Suche über Quellenprüfung und Lager-QC zur Versandentscheidung.","Zehn klare Wege in die FindSpreadsheet-Datenbank mit passenden Prüfpunkten.","Produktseiten sind Recherchehinweise. Quelle, Variante, Maße, Lagerfotos und Versand erneut prüfen.","Ein Ablauf auf Grundlage des veröffentlichten Kauf-, Prüf- und Weiterleitungsprozesses von PikoBuy.","Artikelpreis und Gesamtkosten vor dem Paketbau unterscheiden.","Quellenbasierte Beiträge zu Finds, QC-Fotos, Größen, Rückgaben und Versand.","Direkte Antworten ohne erfundene Garantien oder Bewertungen.","So trennen wir offizielle Fakten von redaktionellen Empfehlungen."],search:"Produkte suchen oder Quelllink einfügen",button:"FindSpreadsheet durchsuchen",browse:"Alle Produkte",independent:"Unabhängiger Ratgeber · Keine offizielle PikoBuy-Website",updated:"Offizielle Angaben geprüft: August 2026",read:"Vollständigen Ratgeber lesen",check:"Prüfpunkte",official:"Offiziell dokumentiert",editorial:"Redaktioneller Hinweis",cta:"PikoBuy-Spreadsheet öffnen",ctasub:"Produkte auf FindSpreadsheet ansehen und Quelle sowie Lagerdaten vor dem Versand prüfen."},
 fr:{nav:["Accueil","Catégories","Détails","Guides","Livraison","Articles SEO","FAQ"],pages:["PikoBuy Spreadsheet 2026","Catégories PikoBuy","Recherche produit","Guides d’achat PikoBuy","Livraison, poids et lignes","Articles PikoBuy","Questions fréquentes","Sources et méthode éditoriale"],sub:["Une bonne liste ne se limite pas aux liens : elle accompagne la recherche, la vérification, le QC et la décision d’expédition.","Dix accès ciblés à FindSpreadsheet avec des contrôles adaptés.","Traitez les pages produit comme des pistes et revérifiez source, option, mesures, photos et livraison.","Un processus pratique fondé sur le parcours d’achat, de contrôle et d’expédition publié par PikoBuy.","Distinguez le prix de l’article du coût rendu avant de créer le colis.","Des articles sourcés sur les produits, photos QC, tailles, retours et expédition.","Des réponses directes sans promesses ni avis inventés.","Notre méthode pour séparer les faits officiels des conseils éditoriaux."],search:"Rechercher un produit ou coller un lien",button:"Rechercher sur FindSpreadsheet",browse:"Voir tous les produits",independent:"Guide indépendant · Ce n’est pas le site officiel PikoBuy",updated:"Sources officielles vérifiées en août 2026",read:"Lire le guide complet",check:"Points à vérifier",official:"Documenté officiellement",editorial:"Conseil éditorial",cta:"Ouvrir le hub PikoBuy",ctasub:"Explorez FindSpreadsheet puis vérifiez la source et le QC avant l’expédition."},
 it:{nav:["Home","Categorie","Dettagli","Guide","Spedizione","Articoli SEO","FAQ"],pages:["PikoBuy Spreadsheet 2026","Categorie PikoBuy","Ricerca prodotto","Guide all’acquisto PikoBuy","Spedizione, peso e linee","Articoli PikoBuy","Domande frequenti","Fonti e metodo editoriale"],sub:["Un buon foglio non è solo un elenco di link: collega ricerca, fonte, QC in magazzino e decisione di spedizione.","Dieci percorsi nel database FindSpreadsheet con controlli specifici.","Tratta le pagine prodotto come spunti e ricontrolla fonte, opzione, misure, foto e spedizione.","Un flusso pratico basato sul processo pubblicato di acquisto, ispezione e inoltro PikoBuy.","Distingui il prezzo dal costo finale prima di creare il pacco.","Articoli con fonti su prodotti, foto QC, taglie, resi e spedizioni.","Risposte dirette senza garanzie o recensioni inventate.","Come separiamo fatti ufficiali e consigli editoriali."],search:"Cerca prodotti o incolla un link",button:"Cerca su FindSpreadsheet",browse:"Vedi tutti i prodotti",independent:"Guida indipendente · Non è il sito ufficiale PikoBuy",updated:"Fonti ufficiali verificate ad agosto 2026",read:"Leggi la guida completa",check:"Cosa controllare",official:"Documentato ufficialmente",editorial:"Consiglio editoriale",cta:"Apri l’hub PikoBuy",ctasub:"Esplora FindSpreadsheet e verifica fonte e magazzino prima della spedizione."},
 pt:{nav:["Início","Categorias","Detalhes","Guias","Envio","Artigos SEO","FAQ"],pages:["Planilha PikoBuy 2026","Categorias PikoBuy","Pesquisa de produtos","Guias de compra PikoBuy","Envio, peso e rotas","Artigos PikoBuy","Perguntas frequentes","Fontes e política editorial"],sub:["Uma boa planilha não é apenas uma lista de links: conecta descoberta, fonte, QC no armazém e decisão de envio.","Dez caminhos para a base FindSpreadsheet com verificações próprias.","Use páginas de produto como pistas e confira fonte, opção, medidas, fotos e envio.","Fluxo prático baseado no processo publicado de compra, inspeção e encaminhamento da PikoBuy.","Separe preço do produto e custo final antes de montar o pacote.","Artigos com fontes sobre produtos, fotos QC, tamanhos, devoluções e envio.","Respostas diretas sem garantias ou avaliações inventadas.","Como separamos fatos oficiais de orientação editorial."],search:"Pesquisar produtos ou colar um link",button:"Pesquisar no FindSpreadsheet",browse:"Ver todos os produtos",independent:"Guia independente · Não é o site oficial da PikoBuy",updated:"Fontes oficiais verificadas em agosto de 2026",read:"Ler o guia completo",check:"O que verificar",official:"Documentado oficialmente",editorial:"Orientação editorial",cta:"Abrir o hub PikoBuy",ctasub:"Explore o FindSpreadsheet e verifique fonte e armazém antes do envio."},
 nl:{nav:["Home","Categorieën","Details","Gidsen","Verzending","SEO-artikelen","FAQ"],pages:["PikoBuy Spreadsheet 2026","PikoBuy-categorieën","Productonderzoek","PikoBuy-gidsen","Verzending, gewicht en routes","PikoBuy-artikelen","Veelgestelde vragen","Bronnen en redactiebeleid"],sub:["Een goede spreadsheet is meer dan een linklijst: hij verbindt zoeken, broncontrole, magazijn-QC en verzending.","Tien routes naar FindSpreadsheet met eigen controlepunten.","Gebruik productpagina’s als onderzoek en controleer bron, optie, maten, foto’s en verzending opnieuw.","Een praktische workflow op basis van PikoBuy’s gepubliceerde aankoop-, inspectie- en doorstuurproces.","Maak onderscheid tussen artikelprijs en totale kosten vóór pakketbouw.","Brongebaseerde artikelen over finds, QC-foto’s, maten, retouren en verzending.","Duidelijke antwoorden zonder verzonnen garanties of reviews.","Hoe wij officiële feiten scheiden van redactioneel advies."],search:"Zoek producten of plak een bronlink",button:"Zoek op FindSpreadsheet",browse:"Alle producten",independent:"Onafhankelijke gids · Geen officiële PikoBuy-site",updated:"Officiële bronnen gecontroleerd in augustus 2026",read:"Lees de volledige gids",check:"Wat controleren",official:"Officieel vastgelegd",editorial:"Redactioneel advies",cta:"Open de PikoBuy-hub",ctasub:"Bekijk FindSpreadsheet en controleer bron en magazijn vóór verzending."},
 pl:{nav:["Start","Kategorie","Szczegóły","Poradniki","Wysyłka","Artykuły SEO","FAQ"],pages:["PikoBuy Spreadsheet 2026","Kategorie PikoBuy","Analiza produktu","Poradniki PikoBuy","Wysyłka, waga i trasy","Artykuły PikoBuy","Najczęstsze pytania","Źródła i zasady redakcyjne"],sub:["Dobry arkusz to nie tylko linki: łączy wyszukiwanie, kontrolę źródła, QC w magazynie i decyzję o wysyłce.","Dziesięć ścieżek do FindSpreadsheet z właściwymi kontrolami.","Traktuj strony produktów jako wskazówki i sprawdzaj źródło, wariant, wymiary, zdjęcia oraz wysyłkę.","Praktyczny proces oparty na opublikowanych zasadach zakupu, kontroli i przekazywania PikoBuy.","Oddziel cenę produktu od kosztu końcowego przed złożeniem paczki.","Artykuły ze źródłami o produktach, QC, rozmiarach, zwrotach i wysyłce.","Konkretne odpowiedzi bez wymyślonych gwarancji i opinii.","Jak oddzielamy oficjalne fakty od porad redakcyjnych."],search:"Szukaj produktów lub wklej link",button:"Szukaj w FindSpreadsheet",browse:"Wszystkie produkty",independent:"Niezależny poradnik · To nie jest oficjalna strona PikoBuy",updated:"Oficjalne źródła sprawdzone w sierpniu 2026",read:"Czytaj pełny poradnik",check:"Co sprawdzić",official:"Oficjalnie opisane",editorial:"Porada redakcyjna",cta:"Otwórz centrum PikoBuy",ctasub:"Przeglądaj FindSpreadsheet i sprawdź źródło oraz QC przed wysyłką."},
 sv:{nav:["Hem","Kategorier","Detaljer","Guider","Frakt","SEO-artiklar","FAQ"],pages:["PikoBuy Spreadsheet 2026","PikoBuy-kategorier","Produktkontroll","PikoBuy-guider","Frakt, vikt och rutter","PikoBuy-artiklar","Vanliga frågor","Källor och redaktionell policy"],sub:["Ett bra kalkylblad är mer än länkar: det kopplar sökning, källkontroll, lager-QC och fraktbeslut.","Tio vägar till FindSpreadsheet med relevanta kontroller.","Använd produktsidor som ledtrådar och kontrollera källa, val, mått, foton och frakt.","Ett praktiskt flöde baserat på PikoBuys publicerade köp-, kontroll- och fraktprocess.","Skilj artikelpris från total kostnad innan paketet byggs.","Källbaserade artiklar om finds, QC-foton, storlek, returer och frakt.","Tydliga svar utan påhittade garantier eller recensioner.","Så skiljer vi officiella fakta från redaktionella råd."],search:"Sök produkter eller klistra in en länk",button:"Sök på FindSpreadsheet",browse:"Alla produkter",independent:"Oberoende guide · Inte PikoBuys officiella webbplats",updated:"Officiella källor kontrollerade augusti 2026",read:"Läs hela guiden",check:"Vad ska kontrolleras",official:"Officiellt dokumenterat",editorial:"Redaktionellt råd",cta:"Öppna PikoBuy-hubben",ctasub:"Bläddra på FindSpreadsheet och kontrollera källa samt lagerinfo före frakt."}
};

const facts:Record<Lang,Array<[string,string]>>={
 en:[["Source first","PikoBuy’s guide tells users to find products on Taobao, Tmall, 1688, Weidian, Yupoo or other platforms, then paste a link or keywords into its search."],["Two-payment workflow","The first payment covers the purchase order. After warehouse arrival and inspection, the user selects a route and makes a separate international shipping payment."],["Warehouse inspection","PikoBuy says items are checked in, photographed and inspected after arrival. Extra photo requests and packaging instructions may be available."],["Shipping estimate","The official estimate asks for destination, product type, weight and parcel dimensions. The final amount can change with packing and route rules."],["Return conditions","The published policy describes a five-day warehouse application period for eligible returns, plus possible domestic shipping and service costs."],["Independent verification","A spreadsheet row is a discovery lead, not proof of stock, seller quality, legality, authenticity or safe delivery."]],
 es:[["Primero la fuente","La guía de PikoBuy indica buscar en Taobao, Tmall, 1688, Weidian, Yupoo u otras plataformas y enviar el enlace o palabras clave."],["Dos pagos","El primer pago cubre la compra. Tras la llegada e inspección se elige la ruta y se paga el envío internacional."],["Inspección de almacén","PikoBuy indica que registra, fotografía e inspecciona los artículos. Pueden solicitarse fotos o instrucciones adicionales."],["Estimación de envío","El cálculo oficial usa destino, tipo, peso y dimensiones; el importe final puede cambiar."],["Condiciones de devolución","La política describe cinco días en almacén para solicitar devoluciones elegibles y posibles costes."],["Verificación independiente","Una fila es una pista, no una garantía de stock, vendedor, autenticidad o entrega."]],
 de:[["Quelle zuerst","Laut PikoBuy werden Artikel auf Taobao, Tmall, 1688, Weidian oder Yupoo gesucht und per Link oder Suchwort eingereicht."],["Zwei Zahlungen","Zuerst wird der Artikel bezahlt. Nach Lagereingang und Prüfung folgen Routenauswahl und internationale Versandzahlung."],["Lagerprüfung","PikoBuy beschreibt Check-in, Fotos und Sichtprüfung. Zusätzliche Fotos oder Verpackungswünsche können möglich sein."],["Versandschätzung","Das offizielle Tool nutzt Ziel, Produkttyp, Gewicht und Maße; der Endpreis kann abweichen."],["Rückgabebedingungen","Die Richtlinie nennt für berechtigte Rückgaben ein fünftägiges Antragsfenster im Lager und mögliche Kosten."],["Unabhängig prüfen","Eine Tabellenzeile ist ein Recherchehinweis, keine Garantie für Bestand, Verkäufer, Echtheit oder Zustellung."]],
 fr:[["Vérifier la source","Le guide PikoBuy propose de chercher sur Taobao, Tmall, 1688, Weidian ou Yupoo puis de soumettre un lien ou des mots-clés."],["Deux paiements","Le premier paie l’article. Après réception et contrôle au dépôt, l’utilisateur choisit la ligne et paie l’expédition internationale."],["Contrôle au dépôt","PikoBuy décrit l’enregistrement, les photos et l’inspection visuelle. Des photos ou consignes supplémentaires peuvent être disponibles."],["Estimation d’envoi","L’outil officiel utilise destination, type, poids et dimensions; le montant final peut varier."],["Conditions de retour","La politique décrit une demande sous cinq jours au dépôt pour les articles éligibles et des frais possibles."],["Vérification indépendante","Une ligne est une piste, pas une garantie de stock, vendeur, authenticité ou livraison."]],
 it:[["Prima la fonte","La guida PikoBuy invita a cercare su Taobao, Tmall, 1688, Weidian o Yupoo e inviare link o parole chiave."],["Due pagamenti","Il primo copre l’acquisto. Dopo arrivo e ispezione si sceglie la linea e si paga la spedizione internazionale."],["Controllo in magazzino","PikoBuy descrive registrazione, fotografie e ispezione. Possono essere disponibili foto o richieste di imballaggio extra."],["Stima di spedizione","Lo strumento ufficiale usa destinazione, tipo, peso e dimensioni; il totale può cambiare."],["Condizioni di reso","La politica descrive cinque giorni in magazzino per richiedere resi idonei e possibili costi."],["Verifica indipendente","Una riga è un indizio, non una garanzia di disponibilità, venditore, autenticità o consegna."]],
 pt:[["Primeiro a fonte","O guia da PikoBuy orienta buscar em Taobao, Tmall, 1688, Weidian ou Yupoo e enviar link ou palavras-chave."],["Dois pagamentos","O primeiro cobre a compra. Após chegada e inspeção, o usuário escolhe a rota e paga o frete internacional."],["Inspeção no armazém","A PikoBuy descreve entrada, fotos e inspeção visual. Fotos extras e pedidos de embalagem podem estar disponíveis."],["Estimativa de envio","A ferramenta oficial usa destino, tipo, peso e dimensões; o valor final pode mudar."],["Condições de devolução","A política descreve cinco dias no armazém para solicitar devoluções elegíveis e possíveis custos."],["Verificação independente","Uma linha é uma pista, não garantia de estoque, vendedor, autenticidade ou entrega."]],
 nl:[["Eerst de bron","Volgens PikoBuy zoek je op Taobao, Tmall, 1688, Weidian of Yupoo en dien je een link of zoekwoord in."],["Twee betalingen","De eerste betaling is voor het artikel. Na aankomst en inspectie kies je de route en betaal je internationale verzending."],["Magazijncontrole","PikoBuy beschrijft inchecken, fotograferen en visuele inspectie. Extra foto’s of verpakkingswensen kunnen mogelijk zijn."],["Verzendraming","De officiële tool gebruikt bestemming, producttype, gewicht en maten; het eindbedrag kan veranderen."],["Retourvoorwaarden","Het beleid beschrijft vijf dagen in het magazijn voor een aanvraag bij geschikte retouren en mogelijke kosten."],["Onafhankelijk controleren","Een rij is een onderzoeksspoor, geen garantie voor voorraad, verkoper, echtheid of levering."]],
 pl:[["Najpierw źródło","PikoBuy zaleca wyszukanie produktu na Taobao, Tmall, 1688, Weidian lub Yupoo i przesłanie linku albo słów kluczowych."],["Dwie płatności","Pierwsza obejmuje zakup. Po przyjęciu i kontroli wybierana jest trasa i opłacana wysyłka międzynarodowa."],["Kontrola magazynowa","PikoBuy opisuje przyjęcie, zdjęcia i oględziny. Mogą być dostępne dodatkowe zdjęcia lub zalecenia pakowania."],["Szacunek wysyłki","Oficjalne narzędzie używa kraju, typu, wagi i wymiarów; końcowa kwota może się zmienić."],["Warunki zwrotu","Polityka opisuje pięć dni na wniosek o kwalifikujący się zwrot i możliwe koszty."],["Niezależna kontrola","Wiersz arkusza jest wskazówką, a nie gwarancją stanu, sprzedawcy, autentyczności lub dostawy."]],
 sv:[["Källan först","PikoBuy beskriver sökning på Taobao, Tmall, 1688, Weidian eller Yupoo och att länken eller sökorden skickas in."],["Två betalningar","Första betalningen gäller varan. Efter lagerankomst och kontroll väljs rutt och internationell frakt betalas."],["Lagerkontroll","PikoBuy beskriver incheckning, fotografering och visuell kontroll. Extra foton eller packningsönskemål kan finnas."],["Fraktuppskattning","Det officiella verktyget använder destination, typ, vikt och mått; slutbeloppet kan ändras."],["Returvillkor","Policyn beskriver fem dagar i lagret för ansökan om berättigad retur och möjliga kostnader."],["Oberoende kontroll","En kalkylbladsrad är ett researchspår, inte garanti för lager, säljare, äkthet eller leverans."]]
};

const categoryRoutes=[["/shoes/","👟"],["/hoodies-sweaters/","◫"],["/t-shirts/","◩"],["/jackets/","▣"],["/pants-shorts/","▥"],["/headwear/","◒"],["/accessories/","◇"],["/jersey/","◈"],["/electronics/","⌁"],["/AllProducts/","⌕"]] as const;
const articleRoute=(lang:Lang,slug:string)=>lang==="en"?`/articles/${slug}`:`/${lang}/articles/${slug}`;
const languageRoute=(lang:Lang,page:Page,articleSlug?:string)=>articleSlug&&page==="articles"?articleRoute(lang,articleSlug):route(lang,page);
const languageSwitchRoute=(lang:Lang,page:Page,articleSlug?:string)=>articleSlug&&page==="articles"?`/${lang}/articles/${articleSlug}`:page==="home"?`/${lang}`:`/${lang}/${page}`;

function route(lang:Lang,page:Page){if(lang==="en")return page==="home"?"/":`/${page}`;return page==="home"?`/${lang}`:`/${lang}/${page}`}

export function SiteExperience({lang:rawLang,page:rawPage,articleSlug}:{lang:string,page:string,articleSlug?:string}){
 const lang=(langs.some(x=>x[0]===rawLang)?rawLang:"en") as Lang; const page=(pageKeys.includes(rawPage as Page)?rawPage:"home") as Page; const t=ui[lang]; const x=extrasByLocale[lang]; const localizedArticles=localizedArticleRecords[lang]; const [query,setQuery]=useState("");
 const article=articleSlug?localizedArticles.find(item=>item.slug===articleSlug):undefined;
 useEffect(()=>{
  document.documentElement.lang=lang;
  const stored=window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
  const storedIsValid=langs.some(([code])=>code===stored);
  const firstSegment=window.location.pathname.split("/").filter(Boolean)[0];
  const hasLanguagePrefix=langs.some(([code])=>code===firstSegment);
  if(!hasLanguagePrefix&&lang==="en"&&storedIsValid&&stored!=="en"){
   window.location.replace(languageRoute(stored as Lang,page,articleSlug));
   return;
  }
  window.localStorage.setItem(LANGUAGE_STORAGE_KEY,lang);
 },[lang,page,articleSlug]);
 const search=()=>window.open(query.trim()?`https://findspreadsheet.com/search.html?keywords=${encodeURIComponent(query.trim())}&channelid=2`:"https://findspreadsheet.com/AllProducts/","_blank","noopener,noreferrer");
 return <main className={page==="home"&&!article?"home-page":"inner-page"}>
  <div className="notice"><span>{t.independent}</span><span>{t.updated}</span></div>
  <header className="main-header"><a className="logo" href={route(lang,"home")}><img src="/pikobuy-logo.png" alt="PikoBuy"/></a><nav>{pageKeys.slice(0,7).map((p,i)=><a className={page===p?"active":""} key={p} href={route(lang,p)}>{t.nav[i]}</a>)}</nav><Select key={`${lang}-${page}-${articleSlug||"index"}`} value={lang} onValueChange={v=>{const nextLang=v as Lang;window.localStorage.setItem(LANGUAGE_STORAGE_KEY,nextLang);window.location.href=languageSwitchRoute(nextLang,page,articleSlug)}}><SelectTrigger className="locale" aria-label={x.selectLanguage||"Select language"}><Globe2 size={15}/><SelectValue/></SelectTrigger><SelectContent position="popper" sideOffset={8} align="end">{langs.map(([c,l])=><SelectItem key={c} value={c}>{l}</SelectItem>)}</SelectContent></Select></header>
  {article?<ArticlePage article={article} t={t} x={x} lang={lang}/>:page==="home"?<Home t={t} x={x} articles={localizedArticles} lang={lang} query={query} setQuery={setQuery} search={search}/>:<Inner page={page} t={t} x={x} articles={localizedArticles} lang={lang}/>}<Footer t={t} x={x} lang={lang}/>
 </main>
}

function Home({t,x,articles,lang,query,setQuery,search}:{t:any,x:any,articles:ArticleRecord[],lang:Lang,query:string,setQuery:(s:string)=>void,search:()=>void}){return <>
 <section className="new-hero"><div className="hero-main"><p className="eyebrow"><Sparkles size={15}/> PIKOBUY SPREADSHEET · 2026</p><h1>{t.pages[0]}</h1><p>{t.sub[0]}</p><div className="finder"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search()} placeholder={t.search}/><button onClick={search}>{t.button}<ArrowRight size={17}/></button></div><a className="database-link" href="https://findspreadsheet.com/" target="_blank" rel="noreferrer"><ShoppingBag size={16}/>{t.browse}<ArrowRight size={15}/></a><div className="trust"><span><Check/>{t.pages[1]}</span><span><Check/>{t.official}</span><span><Check/>{t.editorial}</span></div></div><div className="hero-photo"><img src="/pikobuy-editorial-still-life.png" alt={x.heroAlt}/><div className="photo-caption"><b>{t.check}</b><span>{t.sub[2]}</span></div></div></section>
 <section className="home-categories"><div className="section-title"><div><span>01 · {x.sections[0]}</span><h2>{t.pages[1]}</h2><p>{t.sub[1]}</p></div><a href={route(lang,"categories")}>{t.browse}<ArrowRight/></a></div><div className="category-list">{x.categories.map((c:[string,string],i:number)=><a href={`https://findspreadsheet.com${categoryRoutes[i][0]}`} target="_blank" rel="noreferrer" key={c[0]}><span className="cat-symbol">{categoryRoutes[i][1]}</span><span><b>{c[0]}</b><small>{c[1]}</small></span><em>{String(i+1).padStart(2,"0")}</em></a>)}</div></section>
 <section className="official-band"><div><span>02 · {x.sections[1]}</span><h2>{t.pages[3]}</h2><p>{t.sub[3]}</p><a href={route(lang,"guides")}>{t.read}<ArrowRight/></a></div><div className="workflow">{facts[lang].slice(0,4).map(([h,p],i)=><article key={h}><strong>{String(i+1).padStart(2,"0")}</strong><h3>{h}</h3><p>{p}</p></article>)}</div></section>
 <section className="articles-block"><div className="section-title"><div><span>03 · {x.sections[2]}</span><h2>{t.pages[5]}</h2><p>{t.sub[5]}</p></div><a href={route(lang,"articles")}>{t.read}<ArrowRight/></a></div><div className="article-grid">{articles.map((a,i)=><a href={articleRoute(lang,a.slug)} key={a.slug}><span>{a.label}</span><b>{a.title}</b><p>{a.dek}</p><em>0{i+1}<ArrowRight/></em></a>)}</div></section>
 <section className="comparison"><div><span>{x.comparisonTag}</span><h2>{x.comparisonTitle}</h2></div><ul>{x.comparisonItems.map((item:string)=><li key={item}><Check/>{item}</li>)}</ul></section>
 <Cta t={t}/></>}

function Inner({page,t,x,articles,lang}:{page:Page,t:any,x:any,articles:ArticleRecord[],lang:Lang}){const title=t.pages[pageKeys.indexOf(page)],sub=t.sub[pageKeys.indexOf(page)];return <>
 <section className="inner-hero"><div><p><a href={route(lang,"home")}>{t.nav[0]}</a><ChevronRight/> {title}</p><h1>{title}</h1><div className="inner-lead">{sub}</div></div><aside><span>{t.updated}</span><b>{x.evidenceLine}</b></aside></section>
 {page==="categories"&&<section className="content-section categories-page"><div className="category-list">{x.categories.map((c:[string,string],i:number)=><a href={`https://findspreadsheet.com${categoryRoutes[i][0]}`} target="_blank" rel="noreferrer" key={c[0]}><span className="cat-symbol">{categoryRoutes[i][1]}</span><span><b>{c[0]}</b><small>{c[1]}</small></span><em>{String(i+1).padStart(2,"0")}<ExternalLink/></em></a>)}</div><EditorialNote t={t}/></section>}
 {page==="products"&&<section className="content-section"><h2>{t.pages[2]}</h2><p className="wide-copy">{t.sub[2]}</p><div className="check-grid">{[Search,Shirt,PackageCheck,Weight,CircleDollarSign,ShieldCheck].map((Icon,i)=><article key={facts[lang][i][0]}><Icon/><h3>{facts[lang][i][0]}</h3><p>{facts[lang][i][1]}</p></article>)}</div><Cta t={t}/></section>}
 {(page==="guides"||page==="shipping")&&<section className="content-section"><div className="fact-layout">{facts[lang].map(([h,p],i)=><article key={h}><span>{i<5?t.official:t.editorial}</span><h2>{h}</h2><p>{p}</p><ul>{x.guideBullets.map((item:string)=><li key={item}><CheckCircle/>{item}</li>)}</ul></article>)}</div><Cta t={t}/></section>}
 {page==="articles"&&<section className="content-section"><div className="article-index">{articles.map((a,i)=><a href={articleRoute(lang,a.slug)} key={a.slug}><article><div><span>{a.label} · {a.readTime}</span><h2>{a.title}</h2><p>{a.dek}</p><em>{t.read} <ArrowRight/></em></div><strong>0{i+1}</strong></article></a>)}</div><EditorialNote t={t}/></section>}
 {page==="faq"&&<section className="content-section faq-page"><Accordion type="single" collapsible>{localizedFaqs[lang].map((item,i)=><AccordionItem value={`q${i}`} key={item.q}><AccordionTrigger>{item.q}</AccordionTrigger><AccordionContent>{item.a}</AccordionContent></AccordionItem>)}</Accordion><aside><BookOpen/><h2>{t.pages[1]}</h2><p>{t.ctasub}</p><a href="https://findspreadsheet.com/" target="_blank" rel="noreferrer">{t.cta}<ArrowRight/></a></aside></section>}
 {page==="sources"&&<section className="content-section"><div className="source-grid">{facts[lang].slice(0,5).map(([h,p])=><article key={h}><FileCheck2/><div><h2>{h}</h2><p>{p}</p></div><span>{t.updated}</span></article>)}</div><EditorialNote t={t}/></section>}
 </>}

function ArticlePage({article,t,x,lang}:{article:ArticleRecord,t:any,x:any,lang:Lang}){return <>
 <section className="inner-hero article-hero"><div><p><a href={route(lang,"home")}>{t.nav[0]}</a><ChevronRight/><a href={route(lang,"articles")}>{t.nav[5]}</a><ChevronRight/>{article.label}</p><h1>{article.title}</h1><div className="inner-lead">{article.dek}</div></div><aside><span>{article.updated}</span><b>{article.readTime} · {t.independent}</b></aside></section>
 <article className="long-article"><div className="article-fact-note"><FileCheck2/><div><b>{x.factBasisTitle}</b><p>{x.factBasisBody}</p></div></div>
  {article.sections.map(section=><section key={section.heading}><h2>{section.heading}</h2>{section.paragraphs.map(p=><p key={p}>{p}</p>)}{section.bullets&&<ul>{section.bullets.map(item=><li key={item}><Check/>{item}</li>)}</ul>}</section>)}
 </article><Cta t={t}/>
 </>}

function CheckCircle(){return <Check size={15}/>}
function EditorialNote({t}:{t:any}){return <div className="editorial-note"><ShieldCheck/><div><b>{t.editorial}</b><p>{t.independent}. {t.sub[7]}</p></div></div>}
function Cta({t}:{t:any}){return <section className="final-cta"><div><span>FINDSPREADSHEET.COM</span><h2>{t.cta}</h2><p>{t.ctasub}</p></div><a href="https://findspreadsheet.com/" target="_blank" rel="noreferrer">{t.button}<ArrowRight/></a></section>}
function Footer({t,x,lang}:{t:any,x:any,lang:Lang}){return <footer><div><a className="logo" href={route(lang,"home")}><img src="/pikobuy-logo.png" alt="PikoBuy"/></a><p>{t.independent}. {x.footerDescription}</p></div><div><b>{x.footerResearch}</b><a href={route(lang,"guides")}>{t.nav[3]}</a><a href={route(lang,"shipping")}>{t.nav[4]}</a><a href={route(lang,"sources")}>{t.pages[7]}</a></div><div><b>{x.footerBrowse}</b><a href={route(lang,"categories")}>{t.nav[1]}</a><a href={route(lang,"products")}>{t.nav[2]}</a><a href="https://findspreadsheet.com/pikobuy-spreadsheet/">FindSpreadsheet</a></div><small>{x.footerCopyright}</small></footer>}
