"use client";

import { ArrowRight, BaggageClaim, Boxes, Check, ChevronDown, CircleAlert, ExternalLink, FileText, Footprints, Gem, Globe2, LayoutGrid, PackageCheck, Search, ShieldCheck, Shirt, Sparkles, Truck, Warehouse, Watch } from "lucide-react";
import { useState } from "react";
import { seoArticles, type SeoArticle } from "./seo-content";
import localized from "./localized.generated.json";

type Lang = "en"|"fr"|"de"|"es"|"it"|"pt"|"nl"|"pl"|"ro";
const languages:{code:Lang;name:string;market:string}[]=[
  {code:"en",name:"English",market:"UK · US · Canada"},{code:"fr",name:"Français",market:"France · Belgium"},{code:"de",name:"Deutsch",market:"Germany · Austria"},{code:"es",name:"Español",market:"Spain · US"},{code:"it",name:"Italiano",market:"Italy"},{code:"pt",name:"Português",market:"Portugal"},{code:"nl",name:"Nederlands",market:"Netherlands · Belgium"},{code:"pl",name:"Polski",market:"Poland"},{code:"ro",name:"Română",market:"Romania"},
];

export const en={
 nav:["Home","Product categories","Product details","Guide","QC checks","Shipping","Research","FAQ","SEO articles"], kicker:"Independent PikoBuy research hub", title:"Search fewer links. Keep better finds.", intro:"A practical PikoBuy spreadsheet companion for shoppers in Europe and North America. Search the live FindSpreadsheet catalog, verify the source listing, check warehouse evidence and plan the parcel before you commit.", search:"Search products or paste a source link", button:"Search FindSpreadsheet", trust:"Independent guide — not PikoBuy support or checkout.",
 facts:["Officially described as a China purchasing and forwarding platform","Supports buying from Taobao, Weidian and 1688","International delivery is presented as worldwide; exact lines and prices require a live account check"],
 browse:"Browse the catalog by category", browseIntro:"Each card opens the matching category on FindSpreadsheet. No competitor directories or unrelated outbound links.", workflow:"A safer spreadsheet workflow", workflowIntro:"Treat every row as a lead, not a guarantee. Five checks turn a long list into a shortlist you can explain.",
 steps:[["Define the item","Choose one category and size requirement before opening links."],["Check the source","Match the title, options, seller page and current listing."],["Review QC","Inspect colour, size tag, visible defects and included parts after warehouse arrival."],["Plan the parcel","Consider actual weight, volumetric weight, restrictions and route availability."],["Decide calmly","Ship, return or replace only after the evidence matches the order."]],
 evidence:"What this site will — and will not — claim", yes:"Evidence we can use", no:"Claims we will avoid", yesItems:["PikoBuy's own published platform description","The live listing and option selected","Warehouse photos and measured parcel data","Country-specific route information shown at checkout"], noItems:["Invented user counts by country","Guaranteed delivery dates or customs outcomes","Calling every spreadsheet seller verified","Fabricated customer reviews or outdated prices"],
 sourceNote:"Language choice note", sourceText:"PikoBuy does not publish a reliable public country-by-country user breakdown. These nine languages were selected for the UK domain and priority European/North American market coverage — not presented as official PikoBuy usage statistics.", cta:"Start with the live product database", ctaText:"Use the guide to narrow the question, then move to FindSpreadsheet for current product rows and category pages.", ctaButton:"Browse all products", footer:"Independent informational website. Not affiliated with or endorsed by PikoBuy.", back:"Back to overview", database:"Open product database",
 pageTitles:{categories:"Browse PikoBuy finds by product category",products:"Read the product details before opening a listing",guide:"How to use a PikoBuy spreadsheet without guessing",qc:"Warehouse QC: what to inspect before shipping",shipping:"Plan the parcel before a cheap item becomes expensive",articles:"Evidence-led PikoBuy research",faq:"Straight answers to common spreadsheet questions",seo:"PikoBuy spreadsheet SEO articles and practical buyer guides"},
 pageIntros:{categories:"Start with one product type, compare like with like, and move to the matching FindSpreadsheet category only when you are ready to inspect live rows.",products:"A spreadsheet row is only a summary. Use the source listing, selected option, photos, measurements and parcel information to understand what you may actually receive.",guide:"A spreadsheet is a discovery tool. It organises possible finds, but cannot confirm stock, seller reliability, fit or the final delivered cost.",qc:"QC photos are a decision checkpoint after warehouse arrival. Compare what arrived with the exact option you ordered.",shipping:"International shipping depends on destination, dimensions, weight, restrictions and routes currently offered. Treat estimates as context, not quotes.",articles:"The editorial plan concentrates on questions real buyers need answered, with facts separated from opinions and user reports.",faq:"This page separates spreadsheet discovery from platform support, seller decisions and shipping promises.",seo:"Long-form articles are organised around real search questions, but each one must add practical value, distinguish verified facts from judgement and avoid invented reviews or promises."},
 categoryNames:["Shoes","Sneakers","Shirts","Hoodies","Jackets","Pants","Bags","Shorts","Accessories","Jewelry","Watches","Sweaters"],
 ui:{preview:"Independent PikoBuy research guide",factTitle:"What PikoBuy publicly says",readEvidence:"Read the evidence standard",priorityLanguages:"priority languages",focusedCategories:"focused categories",decisionChecks:"decision checks",exploreSite:"Explore the site",threeWays:"Three direct ways to continue",threeWaysText:"Each card opens its own page. Product discovery links lead only to FindSpreadsheet.",featureCategories:"Browse twelve focused product groups and open the matching live category.",featureProducts:"Understand options, source listings, images, measurements and parcel factors.",featureSeo:"Read practical, evidence-led PikoBuy spreadsheet and buyer research topics.",liveDatabase:"Live database",decisionSystem:"Decision system",factCheck:"Fact check",calloutFlow:"Finds → checks → decision",evidenceStandard:"Evidence standard",evidenceText:"Platform facts come from PikoBuy public pages. Product rows come from FindSpreadsheet. Route availability, prices and account outcomes must be checked live.",seoEyebrow:"PikoBuy spreadsheet / SEO articles",seoIntro:"Seven complete guides based on PikoBuy's public Home, About, Beginner's Guide, product pages, Shipping Terms, Shipping Estimate, Returns & Exchanges and Terms of Service pages. Claims that cannot be verified are left out.",wordRange:"1,200–1,800 words",updated:"Updated",readFull:"Read full article",backSeo:"Back to SEO articles",articleEyebrow:"Evidence-led PikoBuy guide",independent:"Independent guide",factCheckStandard:"Fact-check standard",factCheckText:"Checked against PikoBuy's public Home, About Us, Beginner's Guide, Shipping Terms, Shipping Estimate, Returns & Exchanges and Terms of Service pages. No invented user numbers, delivery guarantees, customs promises or fabricated reviews."},
 sections:{
  categories:[["Choose one category first","Narrowing the search makes price, material, sizing and photo quality easier to compare. The category links on this site lead only to the matching pages on FindSpreadsheet."],["Compare equivalent items","Compare the same product type and similar specifications. A cheap price is not meaningful when the material, option or included parts are different."],["Open the live category","Use the category page to inspect current rows, then return to the source listing before making a purchase decision."],["Keep a short list","Save only rows with a clear title, useful images, an identifiable source and enough information to support the next check."]],
  products:[["Read the full title and option","Confirm model, colour, size, quantity and included parts. Do not assume the first image represents every selectable option."],["Check the source listing","A product card can become outdated. Verify the live seller page, current options and any notices before paying."],["Separate listing images from QC","Seller images describe an offer; warehouse QC photos show the item received for an order. They answer different questions."],["Estimate the delivered decision","Item price is only one part of cost. Packaging, actual or volumetric weight, route and destination affect the parcel decision."]],
  guide:[["Start category-first","Compare shoes with shoes and jackets with jackets. Missing measurements, weak photos and odd price differences become easier to see."],["Preserve the original source","Keep the Taobao, Weidian or 1688 source clue beside the row. Confirm the current listing still matches before paying."],["Separate two payments","The product purchase and international parcel are separate decisions. A low item price says nothing about final delivered value."],["Keep a decision note","Save a row only when the source matches, the option is clear, the photos help and the likely parcel cost makes sense."]],
  qc:[["Identity and option","Check item count, colour, model, selected size and included parts. A correct-looking product can still be the wrong option."],["Shape and construction","Look for symmetry, seams, fastenings, sole shape, prints and obvious damage. Request detail photos when needed."],["Measurements","A label is not a measurement. Compare warehouse measurements with an item that already fits you."],["Decision window","Raise an issue before approving international shipment, while return or replacement may still be possible."]],
  shipping:[["Actual vs volumetric weight","Carriers may price by scale weight or space occupied. Bulky packaging can change the charge."],["Route restrictions","Batteries, liquids, magnets, branded goods and oversized parcels may have fewer eligible lines."],["Consolidation","Combining items may reduce repeated base charges, but a larger parcel concentrates value and can change available routes."],["Before submission","Confirm destination, declaration, insurance, packaging requests and tracking expectations in the active account."]],
  articles:[["Beginner's PikoBuy spreadsheet workflow","Pillar guide · source checks · category-first browsing · 1,400–1,700 words"],["How to read warehouse QC photos","Practical guide · apparel, footwear and accessory examples · 1,300–1,600 words"],["Actual weight vs volumetric weight","Shipping guide · worked parcel examples · 1,200–1,500 words"],["PikoBuy review research: a fair method","Separate verified facts, user reports and unresolved claims · 1,400–1,800 words"]],
  faq:[["Is this the official PikoBuy website?","No. This is an independent FindSpreadsheet guide. Account, payment and order issues should be handled through PikoBuy's support inside the relevant account."],["What does PikoBuy do?","PikoBuy describes itself as a China purchasing and forwarding platform that supports product sourcing, purchasing assistance, warehouse inspection and international shipping."],["Which shopping sources are named by PikoBuy?","Its beginner guide names Taobao, Tmall, 1688, Weidian and Yupoo, while its About page specifically highlights Taobao, 1688 and Weidian."],["How do I submit a product?","PikoBuy says users can paste a product link or keywords into its search box. Its home page also mentions images and sourcing requests."],["Why are there two payment stages?","PikoBuy's guide places the first payment at the purchasing-order stage. After warehouse inspection, the user selects a route, submits a parcel and pays international shipping."],["What happens at the warehouse?","The published guide says warehouse processing includes check-in, photo confirmation and a defect check. Standard photos cannot prove every hidden or specialist issue."],["Can I request more detailed photographs?","PikoBuy's forwarding terms say users can review inspection photos or purchase additional detailed photos. Check the live account for availability and price."],["What information does the shipping estimator need?","Destination country or region, product type, weight, length, width and height. The result is an estimate, not a guaranteed final charge or delivery date."],["How long is the published warehouse return window?","For eligible products, the returns policy describes five days after the status changes to In Warehouse, defined as 120 hours from the next hour. Seller rules and product condition still apply."],["Are returns always free?","No. Customer-choice returns may include return shipping, the seller's original shipping charge and a service fee. Seller-responsibility cases follow the evidence and final seller response."],["When should tracking appear?","PikoBuy's beginner guide says tracking information should be available within three days after shipment. International delivery time still depends on the selected route and logistics conditions."],["Can PikoBuy guarantee customs clearance or delivery?","No such guarantee is published. Its shipping terms identify third-party logistics, customs action, damage, loss and peak-season delays as cross-border risks."]],
  seo:[["PikoBuy spreadsheet beginner guide","A structured introduction to finding rows, verifying source listings and building a shortlist without treating the sheet as a guarantee."],["PikoBuy QC photo checklist","A practical inspection article covering identity, option, construction, measurements, visible defects and the decision before international shipping."],["PikoBuy shipping weight explained","A plain-language guide to actual weight, volumetric weight, packaging, consolidation and why a cheap item can become an expensive parcel."],["How PikoBuy review research should be written","A transparent method that separates platform-published facts, verifiable order evidence, attributed user reports and claims that remain unresolved."]],
 }
};
export type Copy=typeof en;
const articleRoutes=seoArticles.map(article=>article.slug);
const routes=["home","categories","products","guide","qc","shipping","articles","faq","seo",...articleRoutes];
type CatIcon="shoe"|"shirt"|"bag"|"pants"|"accessory"|"jewelry"|"watch";
const cats:{name:string;icon:CatIcon;url:string}[]=[
 {name:"Shoes",icon:"shoe",url:"https://findspreadsheet.com/search.html?keywords=Shoes&channelid=2"},
 {name:"Sneakers",icon:"shoe",url:"https://findspreadsheet.com/search.html?keywords=Sneakers&channelid=2"},
 {name:"Shirts",icon:"shirt",url:"https://findspreadsheet.com/t-shirts/"},
 {name:"Hoodies",icon:"shirt",url:"https://findspreadsheet.com/search.html?keywords=Hoodies&channelid=2"},
 {name:"Jackets",icon:"shirt",url:"https://findspreadsheet.com/search.html?keywords=Jackets&channelid=2"},
 {name:"Pants",icon:"pants",url:"https://findspreadsheet.com/search.html?keywords=Pants&channelid=2"},
 {name:"Bags",icon:"bag",url:"https://findspreadsheet.com/search.html?keywords=Bags&channelid=2"},
 {name:"Shorts",icon:"pants",url:"https://findspreadsheet.com/search.html?keywords=Shorts&channelid=2"},
 {name:"Accessories",icon:"accessory",url:"https://findspreadsheet.com/accessories/"},
 {name:"Jewelry",icon:"jewelry",url:"https://findspreadsheet.com/search.html?keywords=Jewelry&channelid=2"},
 {name:"Watches",icon:"watch",url:"https://findspreadsheet.com/search.html?keywords=Watches&channelid=2"},
 {name:"Sweaters",icon:"shirt",url:"https://findspreadsheet.com/search.html?keywords=Sweaters&channelid=2"},
];
const href=(l:Lang,r:string)=>`/${l}${r==="home"?"":`/${r}`}`;

export function Site({lang,route}:{lang:string;route:string}){
 const code=(languages.some(x=>x.code===lang)?lang:"en") as Lang;
 const bundle=code==="en"?null:(localized as Record<string,{copy:Copy;articles:SeoArticle[]}>)[code];
 const t=(bundle?.copy??en) as Copy;
 const articles=seoArticles.map(base=>{const translated=bundle?.articles.find(article=>article.slug===base.slug);return translated?{...translated,updated:base.updated,published:base.published,author:base.author,primaryKeyword:base.primaryKeyword,secondaryKeywords:base.secondaryKeywords,methodology:base.methodology}:base});
 const [menu,setMenu]=useState(false),[query,setQuery]=useState("");
 const current=routes.includes(route)?route:"home", active=languages.find(x=>x.code===code)!;
 const submit=(e:React.FormEvent)=>{e.preventDefault();window.location.href=`https://findspreadsheet.com/search.html?keywords=${encodeURIComponent(query.trim())}&channelid=2`};
 const nav=t.nav;
 return <div className="site-shell"><div className="preview-bar"><Sparkles size={14}/>{t.ui.preview}</div><header className="topbar"><a className="brand" href={href(code,"home")}><img src="/pikobuy.png" alt="PikoBuy"/></a><nav>{nav.map((n,i)=><a key={`${routes[i]}-${n}`} className={current===routes[i]?"active":""} href={href(code,routes[i])}>{n}</a>)}</nav><div className="language-wrap"><button className="language-button" onClick={()=>setMenu(!menu)}><Globe2 size={17}/><span>{active.name}</span><ChevronDown size={15}/></button>{menu&&<div className="language-menu">{languages.map(l=><a key={l.code} href={href(l.code,current)} className={l.code===code?"selected":""}><b>{l.name}</b><small>{l.market}</small></a>)}</div>}</div></header>{current==="home"?<Home t={t} code={code} query={query} setQuery={setQuery} submit={submit}/>:<Inner t={t} code={code} route={current} articles={articles}/>}<footer><a className="brand footer-brand" href={href(code,"home")}><img src="/pikobuy.png" alt="PikoBuy"/></a><p>{t.footer}</p><div><a href={href(code,"categories")}>{nav[1]}</a><a href={href(code,"products")}>{nav[2]}</a><a href={href(code,"seo")}>{nav[8]}</a><a href="https://findspreadsheet.com/">FindSpreadsheet <ExternalLink size={12}/></a></div></footer></div>
}

function Home({t,code,query,setQuery,submit}:{t:Copy;code:Lang;query:string;setQuery:(x:string)=>void;submit:(e:React.FormEvent)=>void}){return <main><section className="hero"><div className="hero-copy"><p className="eyebrow"><span/>{t.kicker}</p><h1>{t.title}</h1><p className="lead">{t.intro}</p><form className="search-box" onSubmit={submit}><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search} required/><button>{t.button}<ArrowRight size={17}/></button></form><a className="hero-database" href="https://findspreadsheet.com/"><LayoutGrid size={17}/>{t.database}<ExternalLink size={14}/></a><p className="micro"><ShieldCheck size={15}/>{t.trust}</p></div><aside className="fact-card"><div className="fact-head"><span>01</span><PackageCheck/></div><h2>{t.ui.factTitle}</h2>{t.facts.map(x=><p key={x}><Check size={16}/><span>{x}</span></p>)}<a href={href(code,"guide")}>{t.ui.readEvidence} <ArrowRight size={15}/></a></aside></section><section className="stats"><div><strong>9</strong><span>{t.ui.priorityLanguages}</span></div><div><strong>12</strong><span>{t.ui.focusedCategories}</span></div><div><strong>5</strong><span>{t.ui.decisionChecks}</span></div><p>{t.sourceText}</p></section><section className="section new-pages"><Heading eyebrow={t.ui.exploreSite} title={t.ui.threeWays} text={t.ui.threeWaysText}/><div className="feature-grid"><a href={href(code,"categories")}><LayoutGrid/><span>01</span><h3>{t.nav[1]}</h3><p>{t.ui.featureCategories}</p><ArrowRight/></a><a href={href(code,"products")}><Boxes/><span>02</span><h3>{t.nav[2]}</h3><p>{t.ui.featureProducts}</p><ArrowRight/></a><a href={href(code,"seo")}><FileText/><span>03</span><h3>{t.nav[8]}</h3><p>{t.ui.featureSeo}</p><ArrowRight/></a></div></section><section className="section categories"><Heading eyebrow={t.ui.liveDatabase} title={t.browse} text={t.browseIntro}/><CategoryGrid t={t}/></section><section className="section workflow"><Heading eyebrow={t.ui.decisionSystem} title={t.workflow} text={t.workflowIntro}/><div className="steps">{t.steps.map(([h,p],i)=><article key={h}><span>0{i+1}</span>{i===0?<Search/>:i===1?<ShieldCheck/>:i===2?<Warehouse/>:i===3?<Truck/>:<PackageCheck/>}<h3>{h}</h3><p>{p}</p></article>)}</div></section><section className="evidence"><div><p className="eyebrow">{t.ui.factCheck}</p><h2>{t.evidence}</h2></div><article className="positive"><h3><Check/>{t.yes}</h3>{t.yesItems.map(x=><p key={x}>{x}</p>)}</article><article className="negative"><h3><CircleAlert/>{t.no}</h3>{t.noItems.map(x=><p key={x}>{x}</p>)}</article></section><section className="language-note"><Globe2/><div><h3>{t.sourceNote}</h3><p>{t.sourceText}</p></div></section><Callout t={t}/></main>}
function CategoryIcon({kind}:{kind:CatIcon}){return kind==="shoe"?<Footprints/>:kind==="shirt"?<Shirt/>:kind==="bag"?<BaggageClaim/>:kind==="jewelry"?<Gem/>:kind==="watch"?<Watch/>:kind==="accessory"?<Boxes/>:<PackageCheck/>}
function CategoryGrid({t}:{t:Copy}){return <div className="category-grid">{cats.map((cat,i)=>{const label=t.categoryNames[i];return <a key={cat.name} href={cat.url} aria-label={`${label} — FindSpreadsheet`}><span><CategoryIcon kind={cat.icon}/></span><b>{label}</b></a>})}</div>}
function Heading({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></div><p>{text}</p></div>}
function Callout({t}:{t:Copy}){return <section className="cta"><div><p className="eyebrow">{t.ui.calloutFlow}</p><h2>{t.cta}</h2><p>{t.ctaText}</p></div><a href="https://findspreadsheet.com/">{t.ctaButton}<ExternalLink/></a></section>}
function Inner({t,code,route,articles}:{t:Copy;code:Lang;route:string;articles:SeoArticle[]}){const article=articles.find(item=>item.slug===route);if(article)return <ArticlePage article={article} t={t} code={code}/>;if(route==="seo")return <SeoIndex t={t} code={code} articles={articles}/>;const key=route as keyof Copy["pageTitles"],sections=t.sections[route as keyof Copy["sections"]]??t.sections.guide;return <main className="inner"><a className="back" href={href(code,"home")}>← {t.back}</a><section className="inner-hero"><p className="eyebrow">PIKOBUY / {t.nav[routes.indexOf(route)]}</p><h1>{t.pageTitles[key]??t.pageTitles.guide}</h1><p>{t.pageIntros[key]??t.pageIntros.guide}</p></section>{route==="categories"?<><section className="inner-category-panel"><CategoryGrid t={t}/></section><div className="article-grid category-notes"><article className="article-body">{sections.map(([h,p],i)=><section key={h}><span>0{i+1}</span><div><h2>{h}</h2><p>{p}</p></div></section>)}</article><aside><a className="database-button" href="https://findspreadsheet.com/">{t.database}<ExternalLink/></a></aside></div></>:<div className="article-grid"><article className="article-body">{sections.map(([h,p],i)=><section key={h}><span>0{i+1}</span><div><h2>{h}</h2><p>{p}</p></div></section>)}</article><aside><div className="aside-card"><ShieldCheck/><h3>{t.ui.evidenceStandard}</h3><p>{t.ui.evidenceText}</p></div><a className="database-button" href="https://findspreadsheet.com/">{t.database}<ExternalLink/></a></aside></div>}<Callout t={t}/></main>}

function SeoIndex({t,code,articles}:{t:Copy;code:Lang;articles:SeoArticle[]}){return <main className="inner"><a className="back" href={href(code,"home")}>← {t.back}</a><section className="inner-hero"><p className="eyebrow">{t.ui.seoEyebrow}</p><h1>{t.pageTitles.seo}</h1><p>{t.ui.seoIntro}</p></section><section className="seo-index">{articles.map((article,i)=><a className="seo-card" key={article.slug} href={href(code,article.slug)}><span>0{i+1}</span><FileText/><h2>{article.title}</h2><p>{article.description}</p><small>{t.ui.wordRange} · {t.ui.updated} {article.updated}</small><b>{t.ui.readFull} <ArrowRight/></b></a>)}</section><Callout t={t}/></main>}

function ArticlePage({article,t,code}:{article:SeoArticle;t:Copy;code:Lang}){
 const canonical=`https://pikobuyspreadsheet.uk/${code}/${article.slug}/`;
 const author=article.author??"FindSpreadsheet Editorial Team";
 const published=article.published??article.updated;
 const toIso=(value:string)=>new Date(`${value} UTC`).toISOString();
 const relatedLinks=article.slug==="compare-pikobuy-spreadsheet-items"?[["Browse product categories","categories"],["Assess product-page details","products"],["Search with links, images or keywords","pikobuy-product-search-submit-links-images"],["Review warehouse QC evidence","pikobuy-qc-photo-checklist"]]:[["PikoBuy QC photo checklist","pikobuy-qc-photo-checklist"],["Returns and buyer-risk guide","pikobuy-returns-risks-guide"],["Shipping cost-planning guide","pikobuy-shipping-planning-guide"],["PikoBuy spreadsheet workflow","guide"]];
 const articleSchema={"@context":"https://schema.org","@type":"Article",headline:article.title,description:article.description,datePublished:toIso(published),dateModified:toIso(article.updated),author:{"@type":"Organization",name:author},publisher:{"@type":"Organization",name:"FindSpreadsheet"},mainEntityOfPage:{"@type":"WebPage","@id":canonical},keywords:[article.primaryKeyword,...(article.secondaryKeywords??[])].filter(Boolean).join(", ")};
 const breadcrumbSchema={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:`https://pikobuyspreadsheet.uk/${code}/`},{"@type":"ListItem",position:2,name:"SEO Articles",item:`https://pikobuyspreadsheet.uk/${code}/seo/`},{"@type":"ListItem",position:3,name:article.title,item:canonical}]};
 return <main className="inner long-article">
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(articleSchema)}}/>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbSchema)}}/>
  <nav className="article-breadcrumbs" aria-label="Breadcrumb"><a href={href(code,"home")}>Home</a><span>/</span><a href={href(code,"seo")}>SEO Articles</a><span>/</span><span aria-current="page">Guide</span></nav>
  <article><header className="inner-hero"><p className="eyebrow">{t.ui.articleEyebrow}</p><h1>{article.title}</h1><p>{article.description}</p><div className="article-meta"><span>By {author}</span><span>Published {published}</span><span>Reviewed {article.updated}</span><span>{t.ui.independent}</span></div></header>
  <aside className="article-source"><ShieldCheck/><div><h2>How this guide was fact-checked</h2><p>{article.methodology??"Our editorial team reviewed PikoBuy's public platform, policy and guidance pages. Platform statements are identified as official claims; practical checks are our independent editorial analysis. No order, customer quote, price promise or personal experience has been invented."}</p></div></aside>
  {article.slug==="pikobuy-product-search-submit-links-images"&&<figure className="decision-path" aria-labelledby="search-path-title"><div><span>01</span><b>Define</b><small>Write the product and essential specification.</small></div><div><span>02</span><b>Submit</b><small>Use a direct link, focused keywords or an image.</small></div><div><span>03</span><b>Verify</b><small>Match the seller, option, price and included parts.</small></div><div><span>04</span><b>Record</b><small>Save the exact selection before payment.</small></div><figcaption id="search-path-title">The evidence path: turn a discovery result into a listing that can be checked later.</figcaption></figure>}
  {article.slug==="pikobuy-warehouse-consolidation-parcel-preparation"&&<figure className="decision-path" aria-labelledby="warehouse-path-title"><div><span>01</span><b>Receive</b><small>Match each check-in record to the expected item.</small></div><div><span>02</span><b>Resolve</b><small>Review photos and settle any return question.</small></div><div><span>03</span><b>Configure</b><small>Group compatible items and choose packaging.</small></div><div><span>04</span><b>Submit</b><small>Compare live routes using the final parcel data.</small></div><figcaption id="warehouse-path-title">The warehouse decision path: do not repack or consolidate an unresolved item.</figcaption></figure>}
  {article.slug==="compare-pikobuy-spreadsheet-items"&&<figure className="decision-path" aria-labelledby="comparison-path-title"><div><span>01</span><b>Filter</b><small>Choose one category and a non-negotiable requirement.</small></div><div><span>02</span><b>Record</b><small>Capture the source, exact option, cost fields and date.</small></div><div><span>03</span><b>Score evidence</b><small>Mark each fact confirmed, unclear or missing.</small></div><div><span>04</span><b>Verify live</b><small>Move only the strongest candidates to PikoBuy.</small></div><figcaption id="comparison-path-title">The shortlist path: compare evidence before price or visual appeal.</figcaption></figure>}
  <div className="long-copy">{article.sections.map((section,i)=><section key={section.heading}><span>{String(i+1).padStart(2,"0")}</span><div><h2>{section.heading}</h2>{section.paragraphs.map(paragraph=><p key={paragraph}>{paragraph}</p>)}</div></section>)}</div>
  <aside className="related-guides"><h2>Continue with the next practical check</h2><div>{relatedLinks.map(([label,route])=><a key={route} href={href(code,route)}>{label} <ArrowRight/></a>)}</div></aside>
  </article><Callout t={t}/></main>
}
