import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Header, Footer } from "../../components";
import { markets } from "../../data";
import { pageMetadata } from "../../seo";

export function generateStaticParams(){return markets.map((m)=>({slug:m.slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const market=markets.find((m)=>m.slug===slug);return market?pageMetadata({title:`LoloBuy Shipping to ${market.name}: Research Guide`,description:`Public LoloBuy usage signals and shipping research priorities for ${market.name}.`,path:`/markets/${market.slug}`}):{title:"Market not found",robots:{index:false,follow:false}};}

export default async function MarketPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const market=markets.find((m)=>m.slug===slug);if(!market)notFound();return <><Header/><main className="article-page"><header className="market-hero shell"><Link href="/markets">← All markets</Link><div className="country-code big">{market.flag}</div><p className="eyebrow"><span></span>{market.tier} · {market.confidence}</p><h1>LoloBuy research<br/>for {market.name}.</h1><p>{market.summary}</p></header><section className="country-content shell"><article><small>01 / WHAT THE EVIDENCE SAYS</small><h2>A signal—not a customer count</h2><p>The public evidence supports creating a country-specific research page for {market.name}. It does not disclose LoloBuy’s customer total, market share or success rate. This distinction is why the site describes evidence strength instead of publishing a made-up popularity score.</p></article><article><small>02 / WHAT BUYERS NEED</small><h2>Questions that change by destination</h2><p>Buyers should check the live route list, billable weight method, expected handoff carrier, protection terms and current estimate. Customs, tax and restricted-goods rules come from the destination’s official authorities—not a spreadsheet or community comment.</p></article><article><small>03 / SEO CONTENT PLAN</small><h2>Useful pages before translated volume</h2><p>The formal country section should cover shipping variables, tracking handoffs, parcel planning and local terminology. Translation should preserve the full English layout and sources; thin machine-translated pages should remain out of the index until reviewed.</p></article><div className="evidence-panel"><small>PUBLIC SIGNALS USED</small>{market.evidence.map((e)=><p key={e}>✓ {e}</p>)}<Link href="/sources">Review the source library →</Link></div></section></main><Footer/></>}
