const navLabels={en:['Home','Product categories','Product details','SEO articles'],de:['Startseite','Produktkategorien','Produktdetails','SEO-Artikel'],fr:['Accueil','Catégories','Fiches produit','Articles SEO'],es:['Inicio','Categorías','Detalles del producto','Artículos SEO'],it:['Home','Categorie prodotto','Dettagli prodotto','Articoli SEO'],pt:['Início','Categorias','Detalhes do produto','Artigos SEO'],nl:['Home','Productcategorieën','Productdetails','SEO-artikelen'],pl:['Strona główna','Kategorie produktów','Szczegóły produktu','Artykuły SEO'],sv:['Hem','Produktkategorier','Produktdetaljer','SEO-artiklar']};
const originalLabels={en:['Questions','Research paths','Official flow','Regions'],de:['Fragen','Recherchewege','Offizieller Ablauf','Regionen'],fr:['Questions','Parcours','Parcours officiel','Régions'],es:['Preguntas','Rutas de investigación','Flujo oficial','Regiones'],it:['Domande','Percorsi di ricerca','Flusso ufficiale','Regioni'],pt:['Perguntas','Caminhos de pesquisa','Fluxo oficial','Regiões'],nl:['Vragen','Onderzoekspaden','Officiële stroom','Regio’s'],pl:['Pytania','Ścieżki','Oficjalny proces','Regiony'],sv:['Frågor','Forskningsvägar','Officiellt flöde','Regioner']};
const pageUrls=['index.html','categories.html','product-details.html','pikobuy-order-research.html'];
const savedLanguage=(()=>{try{return localStorage.getItem('piko-guide-language');}catch{return null;}})();
const requestedLang=new URLSearchParams(location.search).get('lang')||savedLanguage;
const lang=navLabels[requestedLang]?requestedLang:'en';
document.querySelector('nav').innerHTML=navLabels[lang].map((label,index)=>`<a href="${pageUrls[index]}?lang=${lang}">${label}</a>`).join('')+`<a href="faq.html?lang=${lang}">FAQ</a><a href="research-paths.html?lang=${lang}">${originalLabels[lang][1]}</a>`;
const languageNames={en:'English',de:'Deutsch',fr:'Français',es:'Español',it:'Italiano',pt:'Português',nl:'Nederlands',pl:'Polski',sv:'Svenska'};
const languageWrap=document.createElement('label');languageWrap.className='lang-wrap';languageWrap.innerHTML=`<span class="visually-hidden">Language</span><select aria-label="Language">${Object.entries(languageNames).map(([code,name])=>`<option value="${code}">${name}</option>`).join('')}</select>`;document.querySelector('.site-header').append(languageWrap);const languageSelect=languageWrap.querySelector('select');languageSelect.value=lang;languageSelect.addEventListener('change',()=>{if(typeof window.__applyGuideLocale==='function'){window.__applyGuideLocale(languageSelect.value);return;}try{localStorage.setItem('piko-guide-language',languageSelect.value);}catch{}const destination=new URL(location.href);destination.searchParams.set('lang',languageSelect.value);location.href=destination.pathname+destination.search+destination.hash;});
function directSearch(form){form.addEventListener('submit',event=>{event.preventDefault();const input=form.querySelector('input');const query=input.value.trim();if(query)location.href=`https://findspreadsheet.com/search.html?keywords=${encodeURIComponent(query)}&channelid=2`;});}
document.querySelectorAll('.database-search').forEach(directSearch);
const category=new URLSearchParams(location.search).get('category');
if(category){document.querySelectorAll('[data-category]').forEach(node=>node.textContent=category);const query=document.querySelector('#detail-search');if(query)query.value=category;}
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="compact.css">');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="compact-3cm.css">');
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="article-hero.css">');
const categoryGrid=document.querySelector('.category-grid');
const loadedGuidePage=(()=>{const name=location.pathname.split('/').pop();return !name||name==='index'?'index.html':name.endsWith('.html')?name:`${name}.html`;})();
if(loadedGuidePage==='seo-articles.html'){const firstArticle=document.querySelector('.article-card h3');if(firstArticle){firstArticle.innerHTML='<a href="pikobuy-order-research.html?lang='+lang+'">How to research a Pikobuy order before paying</a>';}}
if(loadedGuidePage==='faq.html'){const list=document.querySelector('.article-list');if(list)list.innerHTML=[['Can I search with a product link?','Pikobuy’s public homepage says users can search products directly or submit links, images or sourcing requests. Check the source listing, selected option and price before submitting anything.'],['What does quality inspection mean?','Pikobuy says items undergo inspection and repacking at its China warehouse. Treat this as an opportunity to compare available evidence with your selected item, not as a guarantee of quality.'],['What should I check for clothing?','Record measurements, material notes, colour and the selected variation first. Use any available warehouse information to compare obvious details with that record.'],['When should I plan shipping?','Pikobuy describes shipping after warehouse handling. Compare route, packed weight, dimensions and destination factors when the parcel is ready; do not treat a listing price as the final cost.'],['Can an estimate guarantee a delivery date or total cost?','No. Estimates and policies can help planning, but routes, packaging, carrier conditions, tax and customs requirements can change. Check current destination information before paying.'],['Where can I search live product results?','Use the search box on this page. It sends your exact keyword directly to FindSpreadsheet’s live product-search results.']].map(([q,a])=>`<article class="article-card"><h3>${q}</h3><p>${a}</p></article>`).join('');}
if(categoryGrid){const icon='<span class="category-icon"><svg viewBox="0 0 24 24" fill="none" stroke-width="1.8"><path d="M5 8h14l-1 11H6L5 8Z"/><path d="M9 8V6a3 3 0 0 1 6 0v2"/></svg></span>';const categories=['Shoes','Hoodies / Sweaters','T-Shirts','Jackets','Pants / Shorts','Headwear','Sets','Underwear / Underpants','Jersey','Accessories'];categoryGrid.innerHTML=categories.map(name=>`<a href="product-details.html?category=${encodeURIComponent(name)}&lang=${lang}">${icon}<strong>${name}</strong></a>`).join('');}
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="category-rows.css">');
if(categoryGrid){const categoryInfo=[['Shoes','Compare fit, materials and photo evidence'],['Hoodies / Sweaters','Review sizing, fabric and print placement'],['T-Shirts','Check measurements and product variation'],['Jackets','Compare outerwear details before searching'],['Pants / Shorts','Review fit, length and material notes'],['Headwear','Compare caps, hats and accessory details'],['Sets','Check each included item and size context'],['Underwear / Underpants','Review material and sizing information'],['Jersey','Compare sportswear sizing and details'],['Accessories','Check product type and current listing context']];const icon='<span class="category-icon"><svg viewBox="0 0 24 24" fill="none" stroke-width="1.8"><path d="M5 8h14l-1 11H6L5 8Z"/><path d="M9 8V6a3 3 0 0 1 6 0v2"/></svg></span>';categoryGrid.innerHTML=categoryInfo.map(([name,detail])=>`<a href="product-details.html?category=${encodeURIComponent(name)}"><span class="category-copy">${icon}<span><strong>${name}</strong><small>${detail}</small></span></span><span class="category-arrow" aria-hidden="true">→</span></a>`).join('');}
document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="category-tiles.css">');
if(categoryGrid){const mainCategories=['Shoes','Hoodies / Sweaters','T-Shirts','Jackets','Pants / Shorts','Headwear','Sets','Underwear / Underpants','Jersey','Accessories'];const icon='<span class="category-icon"><svg viewBox="0 0 24 24" fill="none" stroke-width="1.8"><path d="M5 8h14l-1 11H6L5 8Z"/><path d="M9 8V6a3 3 0 0 1 6 0v2"/></svg></span>';categoryGrid.innerHTML=mainCategories.map(name=>`<a href="https://findspreadsheet.com/search.html?keywords=${encodeURIComponent(name)}&channelid=2"><span class="category-copy">${icon}<span><strong>${name}</strong></span></span></a>`).join('');}
