import { LanguageSelect } from "../../components/language-select";

const questions = [
  ["What can PikoBuy help a shopper do?", "PikoBuy says shoppers can search directly on its platform or submit product links, images or sourcing requests. It describes a buy-for-me service, warehouse inspection and international shipping from its China warehouse. These are platform services; the shopper should still confirm the exact product variant and seller conditions before payment."],
  ["Which source platforms does PikoBuy’s beginner guide mention?", "Its public beginner guide specifically names Taobao, Tmall, 1688, Weidian and Yupoo, alongside other platforms. The guide instructs shoppers to find the item, confirm its specification, colour and size, then paste a product link or use keywords in the PikoBuy search box."],
  ["Does an item price shown in a listing guarantee the final purchase price?", "No. PikoBuy’s guide says prices are subject to the actual purchase. It also says that if an item is out of stock, the order will be refunded. Keep item cost and international shipping as separate budget decisions."],
  ["What happens when an order reaches the warehouse?", "PikoBuy says warehouse staff check the item in, provide photo confirmation and check for defects. The homepage also states that items receive quality inspection and repacking upon arrival. Use photos to compare visible details with the ordered item, not as a guarantee of authenticity, fit or durability."],
  ["Can I request packaging changes or extra photos?", "PikoBuy’s guide says users can add requests such as minimal or reinforced packaging. Its shipping terms say inspection photos are available and that customers can purchase additional detailed photos. Make requests precise—for example, ask for a size label or a close-up of one visible area."],
  ["How long do I have to request an eligible return?", "PikoBuy’s returns policy says a request can be made within five days (120 hours) after an order becomes “In Warehouse,” counted from the following hour. Eligibility also depends on the seller’s guarantee, the item’s condition and the product category."],
  ["Are all products eligible for the five-day return service?", "No. The published policy lists exclusions and restrictions. Examples include customised goods, second-hand goods, intimate apparel, food and certain products whose packaging, labels or seals no longer meet the seller’s resale requirements. Always check the current policy and the individual seller’s rules."],
  ["Who pays when I return an item for personal reasons?", "PikoBuy’s policy states that an unconditional return can include return shipping to the seller, the seller’s original shipping fee and an RMB 5 service fee. The actual outcome is subject to the seller’s consent and relevant third-party platform rules."],
  ["What determines the international shipping estimate?", "The shipping-estimate interface asks for the destination country or region, product type, weight, length, width and height. That is why the product price alone is not a reliable estimate of the delivered cost."],
  ["Are shipping routes interchangeable?", "No. PikoBuy’s guide says routes differ in delivery time and billing methods. Choose only after the parcel contents, destination, measured size and available route conditions are known."],
  ["When should tracking appear after dispatch?", "PikoBuy’s beginner guide says tracking information will be available within three days after the parcel is shipped. If that window has passed, check the order information and contact PikoBuy support with the parcel details."],
  ["Can PikoBuy guarantee delivery or customs clearance?", "No. Its shipping terms state that parcels are carried by third-party logistics providers and that customs policies and uncontrollable cross-border risks—such as delays, loss or damage—must be assessed by the customer. Plan with that risk in mind and review the route’s current conditions before paying."],
];

export default function Faq(){return <main className="route-shell"><Header/><section className="route-hero"><p className="eyebrow"><span></span> FACT-BASED FAQ</p><h1>Clear answers before<br /><em>the next payment.</em></h1><p>Answers below summarise PikoBuy’s public guides and policies; read the live policy before acting on a time-sensitive order.</p></section><section className="route-content faq-section"><div className="faq-list">{questions.map(([question,answer],index)=><details key={question} open={index===0}><summary><span>{String(index+1).padStart(2,"0")}</span>{question}<b>+</b></summary><p>{answer}</p></details>)}</div><p className="faq-basis">Policy basis reviewed September 5, 2026: PikoBuy’s public Beginner’s Guide, Shipping Terms and Returns &amp; Exchanges policy. Platform terms can change.</p></section><Footer/></main>}
function Header(){return <header className="site-header"><a className="brand" href="/"><img className="brand-logo" src="/pikobuy-logo.png" alt="PikoBuy" /></a><nav aria-label="Main navigation"><a href="/">Home</a><a href="/product-categories">Product Categories</a><a href="/product-details">Product Details</a><a href="/seo-articles">SEO Articles</a><a href="/faq">FAQ</a><a href="/qc-guide">QC Method</a><a href="/regions">Regions</a></nav><LanguageSelect /></header>}
function Footer(){return <footer className="route-footer"><a className="brand" href="/"><img className="brand-logo" src="/pikobuy-logo.png" alt="PikoBuy" /></a><p>Independent product-research preview. Not affiliated with PikoBuy.</p><span>© 2026</span></footer>}
