export type CategoryRecord = {
  slug: string; name: string; note: string; checks: string[]; destination: string;
};

export const categoryRecords: CategoryRecord[] = [
  {slug:"shoes",name:"Shoes",note:"Profile, sole, heel, size label and box condition.",checks:["Compare the selected size with the warehouse label.","Inspect both side profiles, heel alignment and outsole.","Keep protective packaging in mind when estimating parcel size."],destination:"https://findspreadsheet.com/shoes/"},
  {slug:"hoodies",name:"Hoodies & sweaters",note:"Measurements, fabric, print placement and likely weight.",checks:["Request chest and length measurements when fit matters.","Check seams, cuffs, print edges and visible marks.","Allow for bulky fabric in a consolidated parcel."],destination:"https://findspreadsheet.com/hoodies-sweaters/"},
  {slug:"t-shirts",name:"T-shirts",note:"Fit, material description, print placement and source match.",checks:["Compare the source size chart with warehouse measurements.","Review front, back, collar, seams and print close-ups.","Do not infer fabric composition from a photograph alone."],destination:"https://findspreadsheet.com/t-shirts/"},
  {slug:"jackets",name:"Jackets",note:"Lining, hardware, measurements and packaging volume.",checks:["Inspect closures, cuffs, pockets and visible lining.","Confirm measurements because labelled sizes vary.","Expect structure or padding to affect parcel dimensions."],destination:"https://findspreadsheet.com/jackets/"},
  {slug:"pants-shorts",name:"Pants & shorts",note:"Waist, inseam, rise, fabric and estimated weight.",checks:["Confirm waist and inseam against the selected option.","Inspect seams, pockets, fasteners and leg shape.","Use measured weight rather than a category guess for shipping."],destination:"https://findspreadsheet.com/pants-shorts/"},
  {slug:"headwear",name:"Headwear",note:"Shape, circumference, stitching and crush protection.",checks:["Check size or adjuster details and overall shape.","Inspect embroidery, seams, brim and visible marks.","Decide whether protective packaging is worth added volume."],destination:"https://findspreadsheet.com/headwear/"},
  {slug:"accessories",name:"Accessories",note:"Dimensions, close-ups, included pieces and restrictions.",checks:["Confirm every included part shown in the listing.","Request close-ups for fasteners, connectors and markings.","Check whether batteries, liquids or magnets affect routes."],destination:"https://findspreadsheet.com/accessories/"},
  {slug:"jerseys",name:"Jerseys",note:"Sizing, badges, print, fabric and customisation status.",checks:["Match name, number, patches and selected size.","Inspect print placement, seams and visible fabric texture.","Remember that customised goods may have stricter return limits."],destination:"https://findspreadsheet.com/jersey/"},
  {slug:"electronics",name:"Electronics",note:"Exact model, visible state, included parts and route limits.",checks:["Match model and connector details to the source listing.","Photos cannot verify internal condition or long-term performance.","Check battery and electronic-product shipping restrictions early."],destination:"https://findspreadsheet.com/electronics/"},
  {slug:"all-products",name:"All products",note:"Search the complete FindSpreadsheet product database.",checks:["Filter by product type before comparing rows.","Open the original product record and verify live options.","Use category-specific evidence before keeping a shortlist item."],destination:"https://findspreadsheet.com/AllProducts/"},
];

export type ProductRecord = {
  slug: string; name: string; category: string; recordedPrice: string; sourcePriceCny: string; observed: string;
  summary: string; evidence: string[]; image: string; mainUrl: string;
};

export const productRecords: ProductRecord[] = [
  {slug:"gallery-short",name:"Gallery Short",category:"Pants & shorts",recordedPrice:"$21.51",sourcePriceCny:"¥145",observed:"USD reference conversion from ¥145 · 1 USD = 6.74 CNY · checked 18 Aug 2026",summary:"A multi-style denim-short listing recorded by FindSpreadsheet as item 7711437541. Its first image and CNY source price match the main-site product page; the USD amount is a dated reference conversion and current variants still need to be reopened before ordering.",evidence:["Match the selected wash and distress pattern to the source gallery.","Confirm waist, rise and length for the chosen option.","Inspect hems, pockets, hardware and visible marks in warehouse photos."],image:"/products/gallery-short.webp",mainUrl:"https://findspreadsheet.com/pants-shorts/gallery-short-3003.html"},
  {slug:"high-quality-burberry-jacket",name:"High quality Burberry Jacket",category:"Jackets",recordedPrice:"$21.96",sourcePriceCny:"¥148",observed:"USD reference conversion from ¥148 · 1 USD = 6.74 CNY · checked 18 Aug 2026",summary:"A denim-style jacket listing recorded by FindSpreadsheet as item 7714490692. Its first image and CNY source price match the main-site detail page; the USD amount is a dated reference conversion, while live size and style options remain source-dependent.",evidence:["Confirm the exact colour, size and back design before purchase.","Inspect collar, cuffs, front closure, embroidery and seams.","Request chest and length measurements because labelled sizes vary."],image:"/products/burberry-jacket.webp",mainUrl:"https://findspreadsheet.com/jackets/high-quality-burberry-jacket-3131.html"},
  {slug:"cp-company-t-shirt",name:"cp company t-shirt",category:"T-shirts",recordedPrice:"$17.51",sourcePriceCny:"¥118",observed:"USD reference conversion from ¥118 · 1 USD = 6.74 CNY · checked 18 Aug 2026",summary:"A multi-style T-shirt listing recorded by FindSpreadsheet as item 7714478764. The card uses the same lead image and CNY source price as the main-site record; the USD amount is a dated reference conversion and the exact print and colour must still be selected deliberately.",evidence:["Identify the exact print and colour shown in the selected variant.","Compare measured chest width and length with a known garment.","Inspect collar, print edges, seams and visible surface marks."],image:"/products/cp-company-tshirt.webp",mainUrl:"https://findspreadsheet.com/t-shirts/cp-company-t-shirt-2999.html"},
  {slug:"the-north-face-outdoorjacket",name:"The North Face Outdoorjacket",category:"Jackets",recordedPrice:"$21.51",sourcePriceCny:"¥145",observed:"USD reference conversion from ¥145 · 1 USD = 6.74 CNY · checked 18 Aug 2026",summary:"A colour-block outdoor jacket listing recorded by FindSpreadsheet as item 7711524403. The same first image and CNY source price are used here and on its main-site page; the USD amount is a dated reference conversion and photographs do not establish waterproofing.",evidence:["Confirm colour, size, lining and whether every pictured piece is included.","Inspect closures, cuffs, hood, pockets, seams and visible marks.","Do not infer waterproof performance from an exterior photograph."],image:"/products/tnf-outdoor-jacket.webp",mainUrl:"https://findspreadsheet.com/jackets/the-north-face-outdoorjacket-2998.html"},
  {slug:"lacoste-swim-shorts",name:"Lacoste Swim Shorts",category:"Pants & shorts",recordedPrice:"$17.95",sourcePriceCny:"¥121",observed:"USD reference conversion from ¥121 · 1 USD = 6.74 CNY · checked 18 Aug 2026",summary:"A patterned swim-short listing recorded by FindSpreadsheet as item 7714520304. The product name, first image and CNY source price match the main-site record; the USD amount is a dated reference conversion and the selected pattern still needs live confirmation.",evidence:["Confirm pattern, colour, size and included lining for the chosen option.","Request waist and length measurements if they are not visible.","Inspect drawstrings, waistband, hems, pockets and embroidery."],image:"/products/lacoste-swim-shorts.webp",mainUrl:"https://findspreadsheet.com/pants-shorts/lacoste-swim-shorts-2996.html"},
  {slug:"qatar-short-sleeve-suits",name:"Qatar Short Sleeve Suits",category:"Jerseys",recordedPrice:"$14.69",sourcePriceCny:"¥99",observed:"USD reference conversion from ¥99 · 1 USD = 6.74 CNY · checked 18 Aug 2026",summary:"A football top-and-shorts set recorded by FindSpreadsheet as item 7704304729. Its first image and CNY source price match the main-site product page; the USD amount is a dated reference conversion and the set contents should be checked against the live option.",evidence:["Confirm that the selected option includes both the top and shorts.","Match colour, badge, sponsor treatment and size to the source listing.","Inspect print placement, seams, hems and measured garment dimensions."],image:"/products/qatar-jersey.webp",mainUrl:"https://findspreadsheet.com/jersey/qatar-short-sleeve-suits-2249.html"},
];

export type SeoArticle = {
  slug: string; title: string; deck: string; readTime: string; wordTarget: string;
  sources: string[]; sections: {heading:string; paragraphs:string[]}[];
};

export const seoArticles: SeoArticle[] = [
  {
    slug:"pikobuy-spreadsheet-guide",
    title:"How to Use a PikoBuy Spreadsheet Without Treating It as Proof",
    deck:"A practical, evidence-led workflow from a product row to warehouse review, parcel planning and a defensible keep-or-remove decision.",
    readTime:"11 min read",wordTarget:"1,200–1,800 words",
    sources:["PikoBuy public homepage","PikoBuy Beginner's Guide","PikoBuy Returns & Exchanges","PikoBuy Shipping Estimate","PikoBuy Shipping Terms"],
    sections:[
      {heading:"A spreadsheet is a starting point, not a verdict",paragraphs:[
        "A PikoBuy spreadsheet is most useful when it reduces search friction. It can group product links, rough categories, observed prices and research notes in one place. That is valuable, but the convenience creates a common mistake: a clean row can look more trustworthy than the evidence behind it. A row does not prove that the seller still has stock, that the selected variant matches the title, that a photograph represents the delivered item, or that an international route will accept the parcel. Treat every row as an invitation to verify, not as a recommendation that has already done the verification for you.",
        "The best way to use a spreadsheet is therefore to ask what decision it supports. At the discovery stage, it should help you compare similar items. Before purchase, it should help you reopen the source and confirm specifications. At the warehouse stage, it should help you remember which visible details matter. Before parcel submission, it should remind you that product price and delivered cost are different numbers. This evidence-first role is less exciting than a list of supposedly perfect finds, but it is far more useful when money, returns and cross-border logistics are involved."
      ]},
      {heading:"Start with the six stages PikoBuy actually publishes",paragraphs:[
        "PikoBuy's public beginner material describes six stages: select an item on a source platform, search with a product link or keywords, choose specifications and complete the first payment, review the warehouse inspection, choose a shipping route and pay international freight, then wait for parcel tracking. That sequence matters because different facts become available at different moments. A source page can describe colour and size before purchase, but warehouse weight is not yet known. Warehouse photos can show visible condition later, but they cannot promise customs clearance or a delivery date.",
        "Use the published sequence as the spine of your spreadsheet workflow. Add a source-check column before the purchase stage, an option-confirmation column for size and colour, an evidence column for warehouse photographs, and a shipping-planning column for destination, product type, weight and dimensions. Do not collapse those stages into one confidence score. A product may look convincing at the listing stage and still become unattractive when its measured weight, route restrictions or return deadline are known. Good research changes as the order moves."
      ]},
      {heading:"Reopen the source listing and save the exact option",paragraphs:[
        "The beginner guide tells users to confirm specifications, colour and size on the source platform and recommends saving item or store information. This is a simple instruction with large practical value. Product titles are often broad, while the purchasable variants may differ in colour, bundle contents, size system or price. Before preserving a spreadsheet row, write down the exact option you mean. If the source page changes later, that note helps you recognise whether the current listing still matches the find that attracted you.",
        "Avoid using price as the first filter without context. A low displayed amount may belong to an accessory, deposit or smallest option rather than the pictured product. A higher amount may include a bundle. The official guide also says prices are subject to the actual purchase and that an out-of-stock order will be refunded. That is a reminder that spreadsheet values are time-sensitive. Record the check date, reopen the live product record before payment and remove rows that cannot be matched to a clear, purchasable option."
      ]},
      {heading:"Turn warehouse photos into category-specific evidence",paragraphs:[
        "PikoBuy says warehouse inspection includes check-in, photo confirmation and a defect check. Its forwarding terms add that users can review inspection photos or buy additional detailed photos, while professional inspection cannot be provided for some special or professional products. Those statements establish a useful boundary: photographs are evidence of visible details, not a laboratory test or an authenticity certificate. A good spreadsheet should never mark an item verified merely because several images exist.",
        "Instead, define the photographs you need by category. Shoes benefit from side profiles, heel alignment, outsole and size-label images. Clothing benefits from measured width and length, seams, print placement and close-ups of visible defects. Bags need dimensions, interior, straps and hardware. Electronics need exact model markings and included parts, but even clear photographs cannot prove internal condition or long-term performance. Add a short question to the row—what could change my decision?—and request another angle only when the answer is genuinely visible."
      ]},
      {heading:"Use the return window before it uses you",paragraphs:[
        "PikoBuy's Returns & Exchanges page describes a five-day warehouse application window, counted as 120 hours from the next hour after the order status changes to In Warehouse. It also distinguishes items that are eligible from categories and conditions that may not qualify, and it says seller agreement, resale condition and packaging rules matter. This is why warehouse review should be scheduled, not postponed. Record the check-in time as soon as it appears and inspect the evidence while there is still time to act.",
        "The same page lists an unconditional-return formula that includes return shipping to the seller, the seller's original shipping charge and an RMB 5 service fee. It notes that even an originally free-shipping order may involve the first-delivery charge during a return. These are published rules, not a promise that every case will be accepted. Your spreadsheet can include a return-deadline field and a reason field, but it cannot decide responsibility. Choose the actual reason, preserve packaging and labels, and use the official order interface for any request."
      ]},
      {heading:"Plan delivered cost with measured inputs",paragraphs:[
        "PikoBuy's public shipping estimator asks for destination, product type, weight, length, width and height. The form itself is a useful checklist. If several of those values are still guesses, the result is planning context rather than a final quote. A spreadsheet that displays only product price encourages the wrong comparison. Add separate fields for domestic seller shipping, optional services, estimated international freight and possible destination charges, then replace estimates with warehouse data when it becomes available.",
        "Dimensions deserve the same attention as weight because bulky packaging can affect chargeable weight. Consolidation may reduce duplicate packaging, but a large combined carton can also change the available routes or volumetric calculation. The beginner guide says routes differ in delivery time and billing methods. Compare at least two eligible options, read the current restrictions and decide whether speed, predictability, protection or price matters most. The cheapest displayed route is not automatically the best route for the parcel you actually have."
      ]},
      {heading:"Separate tracking from guarantees",paragraphs:[
        "The beginner guide says tracking information will be available within three days after a parcel is shipped. That statement applies after dispatch; it should not be confused with the domestic movement of an item toward the warehouse. A spreadsheet status such as purchased, seller shipped, in warehouse, parcel submitted and parcel dispatched helps prevent that confusion. When tracking appears, use the number shown in the account and allow for the first carrier scan before assuming something is wrong.",
        "PikoBuy's shipping terms also state that parcels use third-party logistics providers and describe risks including customs action, damage, loss and peak-season delay. The platform says it can provide risk alerts and improve insurance options, but it does not assume risks caused by customs policy or uncontrollable cross-border factors. That is why phrases such as guaranteed arrival or seizure-proof should never appear in responsible spreadsheet copy. Record the chosen route and insurance decision, then keep expectations aligned with the published risk boundary."
      ]},
      {heading:"A repeatable keep-or-remove decision",paragraphs:[
        "At the end of the workflow, a row should earn its place. Keep it when the source still matches, the exact option is clear, category-specific evidence answers the visible questions, the return status is understood and the shipping inputs are plausible. Mark it research more when one fixable question remains. Remove it when the option cannot be identified, the source has changed, required evidence is unavailable, the return deadline has passed or the delivered-cost range defeats the original reason for choosing it.",
        "This method is intentionally conservative. It will not produce the longest spreadsheet, but it produces a more explainable one. Every saved row carries a reason, a check date and a next action. That structure is useful for readers and for search engines because it replaces vague hype with a genuine decision process. The goal is not to claim that every find is safe. The goal is to show exactly what has been checked, what remains uncertain and where the reader must use the live platform before acting."
      ]}
    ]
  },
  {
    slug:"pikobuy-qc-photo-guide",
    title:"PikoBuy QC Photos: A Category-by-Category Warehouse Inspection Guide",
    deck:"How to read warehouse images, request useful angles and act before the published return window closes.",
    readTime:"10 min read",wordTarget:"1,200–1,800 words",
    sources:["PikoBuy Beginner's Guide","PikoBuy Shipping Terms","PikoBuy Returns & Exchanges"],
    sections:[
      {heading:"What the official material actually promises",paragraphs:[
        "PikoBuy's beginner guide describes warehouse inspection as check-in, photo confirmation and a defect check. Its forwarding terms say forwarded goods are unpacked and inspected, that inspection photographs can be viewed and that additional detailed photographs can be purchased. The same terms warn that professional inspection is unavailable for some special and professional products. Read together, those statements support a clear expectation: warehouse images can document visible condition and option details, but the scope is not unlimited.",
        "A responsible QC guide starts with that boundary. It does not call a product authentic because a label appears in a photograph. It does not promise fabric composition from colour and texture, or electronic performance from an exterior view. Images can answer questions about what is visible: selected colour, obvious stains, large scratches, print position, size labels, measured dimensions and included pieces. The job is to ask precise questions that a camera can answer, then avoid conclusions that require testing, expertise or information outside the frame."
      ]},
      {heading:"Prepare the checklist before warehouse arrival",paragraphs:[
        "The easiest time to define evidence is before the item reaches the warehouse. Reopen the source listing, save the chosen size, colour and bundle, and note any feature that would make the order unacceptable if it were visibly different. This might be a graphic on the back of a shirt, the connector type on an accessory, the number of pieces in a set or the exact colour of a shoe. A generic note such as check quality is too vague to guide a useful review.",
        "Create a short category checklist and rank each item by importance. Critical checks decide whether you keep or return the product. Helpful checks improve confidence but are not decisive. Curiosity checks may not justify an extra photograph. This ranking matters because the return clock can be short and additional evidence takes time. PikoBuy's return material describes a 120-hour warehouse application period for eligible requests. Arriving with a prepared checklist helps you use that time on visible facts rather than inventing questions after the deadline approaches."
      ]},
      {heading:"Shoes: symmetry, labels and construction",paragraphs:[
        "For shoes, begin with a pair-level view. Confirm that both shoes are present, appear to be the same model and colour, and show no obvious mismatch. Then inspect each side profile, heel alignment and outsole. A top-down view can reveal shape differences, while a close view of toe boxes, seams and glue areas can show visible construction issues. If a box matters, review its condition separately because packaging can be damaged even when the product appears intact.",
        "Size needs its own evidence. Compare the warehouse size label with the option recorded from the source. If fit is uncertain, an insole or outsole measurement may be more useful than another beauty shot, although measurement methods can vary. Do not use a photograph to claim authenticity, material grade or comfort. Also remember that retaining a box or adding protection can increase parcel volume. The QC decision and the shipping decision are connected, so record whether packaging is essential before the parcel is built."
      ]},
      {heading:"Clothing: measurements beat size names",paragraphs:[
        "For T-shirts, hoodies, jackets, jerseys and pants, labelled sizes are only a starting point. Compare visible measurements with a garment that already fits. Chest width, body length, sleeve length, waist, rise and inseam are more useful when the cut or regional sizing is unfamiliar. Ask how the warehouse places the tape and allow for small measurement variation. A single number should not be treated as laboratory precision, but it is still more actionable than a vague S, M or L.",
        "Next inspect construction and placement. Look at collar shape, cuffs, seams, hems, pockets, closures and the alignment of prints or embroidery. Front and back images are both important when the design appears on more than one side. Close-ups can show obvious marks or loose stitching. They cannot prove fibre content, colourfastness, warmth or durability. If the listing describes a particular fabric, preserve that as seller information rather than relabelling it as a warehouse-confirmed fact."
      ]},
      {heading:"Accessories and bags: contents and scale",paragraphs:[
        "Accessory listings often combine several variations, so the first task is to confirm what is included. Count pieces, compare colours and match visible connectors, straps, cases or attachments to the selected bundle. For bags, request dimensions, interior views, pockets, strap hardware, closures and the base. A product can look correct from the front while an important interior or attachment remains unverified.",
        "Scale is easy to misread in a clean photograph. Measurements help distinguish a small accessory from the larger item suggested by styled listing images. For metal, plastic or coated surfaces, close-ups can document visible scratches, dents or peeling but cannot establish long-term wear. If magnets, batteries, liquids or other restricted characteristics may be involved, flag them before shipping selection. QC answers what arrived visibly; route eligibility is a separate logistics question."
      ]},
      {heading:"Electronics: exact model, limited conclusions",paragraphs:[
        "Electronics require disciplined wording. Confirm the exact model, colour, connector, voltage information and included components that are visible. Request clear photographs of labels and ports when those details determine compatibility. Check for obvious exterior damage and whether sealed packaging remains intact when return rules depend on it. Do not ask an ordinary warehouse photograph to prove battery health, storage capacity, internal parts or reliable operation.",
        "PikoBuy's return standards list special packaging and condition requirements for digital products, cameras and electronic components. For example, the public return page mentions intact access licensing, no water-damage signs, camera shutter limits and no soldering or installation for certain components. Those details show why opening, testing or altering an item can affect eligibility. Before requesting any handling, read the current rule for the product class and decide whether the information gained is worth the return consequence."
      ]},
      {heading:"Use the return deadline as an operating rule",paragraphs:[
        "The Returns & Exchanges page states that the application period is five days, counted as 120 hours from the next hour after the status becomes In Warehouse. It also says qualification depends on seller participation, resale condition and category-specific restrictions. Build a review routine around that clock: note the check-in time, open standard photographs promptly, compare them with the saved option, request only necessary additional views and make a decision while the official interface still allows action.",
        "When a problem appears, describe the visible mismatch accurately. Wrong size, wrong colour, a hole, a stain and domestic-shipping damage may lead to different responsibility discussions. The return page says customers normally bear costs for no-quality-issue returns, while seller responsibility may apply when the wrong item or a quality issue is confirmed. The seller's agreement still matters. Photos support the explanation; they do not decide the case by themselves."
      ]},
      {heading:"A concise evidence record for every product",paragraphs:[
        "A useful spreadsheet QC record can fit in five fields: expected option, photographs reviewed, visible result, unanswered question and decision deadline. Add a link to the product detail page in FindSpreadsheet and keep the original source information separate. If an additional image changes the decision, record why. If it merely makes the card look more complete, it probably does not belong in the critical workflow.",
        "The final language should be modest and exact. Say visible size label matches, not size is guaranteed. Say no obvious exterior damage seen in supplied images, not perfect condition. Say model marking appears consistent, not genuine or fully functional. This precision makes the guide more credible and more helpful. QC is not a ceremony that turns uncertainty into certainty; it is a structured opportunity to catch visible mismatches before the return window closes and before several items become one international parcel."
      ]}
    ]
  },
  {
    slug:"pikobuy-shipping-cost-guide",
    title:"PikoBuy Shipping Cost: How Weight, Dimensions, Routes and Risk Change the Total",
    deck:"A fact-checked method for moving from a rough product-price comparison to a realistic parcel plan.",
    readTime:"11 min read",wordTarget:"1,200–1,800 words",
    sources:["PikoBuy Shipping Estimate","PikoBuy Beginner's Guide","PikoBuy Shipping Terms","PikoBuy Returns & Exchanges"],
    sections:[
      {heading:"Product price is not delivered cost",paragraphs:[
        "A spreadsheet often begins with the product price because it is the easiest number to collect. It is also the number most likely to distort the decision when shown alone. The amount paid to acquire an item can be followed by domestic seller shipping, optional warehouse services, packaging, international freight and destination taxes or customs charges. A cheap product may be expensive to move, while a higher-priced compact item may remain reasonable after shipping.",
        "Build comparisons around a cost path rather than a single price. Keep separate fields for the observed product amount, domestic charge, optional services, estimated international freight and destination-side uncertainty. Do not add invented precision: if a value is unknown, label it unknown or use a range with a clear reason. The purpose is not to predict checkout exactly. It is to recognise when shipping could overturn the apparent advantage that made a spreadsheet row attractive."
      ]},
      {heading:"Use the six inputs in PikoBuy's estimator",paragraphs:[
        "PikoBuy's public shipping-estimate page asks where the parcel will go, what product type it contains, its weight in kilograms and its length, width and height in centimetres. Those six inputs are a practical minimum dataset. Destination and product type affect eligible routes. Weight and dimensions affect how a logistics provider may calculate the charge. If the warehouse has not measured the parcel yet, any result should remain a planning estimate.",
        "Do not fill unknown dimensions with zeros simply to produce a result. Use a reasonable category range only for early screening and mark it as assumed. Replace assumptions with warehouse measurements after items arrive and packaging choices are known. This is especially important for shoes with boxes, padded jackets, headwear that needs crush protection and multi-item parcels. A row should show whether its weight and dimensions are observed, seller-stated or estimated, because those are different levels of confidence."
      ]},
      {heading:"Actual weight and volumetric weight answer different questions",paragraphs:[
        "Actual weight tells you how heavy the parcel is on a scale. Volumetric or dimensional weight represents the space it occupies in a transport network. Different routes and providers can apply different divisors, rounding rules and billing methods, so this guide does not publish one universal formula as if it controlled every quote. The beginner guide itself warns that routes differ in delivery time and billing methods. The current route result is the place to confirm the applicable calculation.",
        "The practical lesson is simple: dense products and bulky products behave differently. Several lightweight boxes can create more chargeable volume than expected, while compact clothing may be closer to actual weight. Removing unnecessary seller packaging can reduce size, but protective packaging may prevent damage. Record the reason for each packaging request. Minimal packaging is not automatically best, and reinforced packaging is not automatically worth the added size. The right choice depends on fragility, replacement difficulty and the routes available to the destination."
      ]},
      {heading:"Consolidation can save or surprise",paragraphs:[
        "Combining warehouse items can reduce duplicated outer packaging and turn several shipments into one international parcel. That can be efficient, but it is not a guaranteed saving. The combined carton may enter a different weight bracket, create more volumetric weight or remove a route from consideration. Fragile and heavy items may also need separation. Estimate consolidation only after you know what has arrived, what packaging must stay and which items have restrictions.",
        "Use a parcel worksheet with item weight, approximate dimensions, keep-or-remove packaging choice and compatibility notes. Then compare a consolidated plan with a split plan when the difference matters. Consider the risk of placing every item in one parcel as well as the price. If one shipment is delayed or damaged, the concentration is larger. There is no universal correct parcel count; a good spreadsheet makes the trade-off visible instead of treating consolidation as a magic discount."
      ]},
      {heading:"Route selection is more than the lowest number",paragraphs:[
        "The public beginner guide instructs users to choose a suitable shipping route, submit the parcel and pay international shipping. It says routes differ in delivery time and billing methods. Suitability can also depend on product type, batteries, liquids, magnets, branded characteristics or destination restrictions. A low quote is not useful if the route does not accept the contents or if its service profile conflicts with the buyer's priorities.",
        "Compare eligible routes on at least four dimensions: estimated cost, published time range, billing method and restrictions. Add insurance or compensation terms when they are available and relevant. Decide which factor matters before sorting the list. A buyer with a fixed event date may value predictability, while a buyer with a low-value, non-urgent parcel may prefer price. Avoid describing a displayed delivery range as a guaranteed arrival date, because customs, carrier hand-offs and peak periods sit outside a simple estimate."
      ]},
      {heading:"Returns can become a shipping-cost decision",paragraphs:[
        "PikoBuy's Returns & Exchanges page recognises that international shipping may exceed a buyer's budget and lists that situation among customer-responsibility examples. The page describes an unconditional-return cost consisting of shipping back to the seller, the seller's original shipping fee and an RMB 5 service fee. It also notes that an originally free-shipping item may still involve the first-delivery charge during a return. These rules make early freight planning important.",
        "The same page gives a warehouse application window of 120 hours for eligible returns. If a measured item is far heavier or bulkier than expected, waiting until the parcel stage may remove the practical return option. Review weight and dimensions as soon as the warehouse provides them, compare the likely freight range and decide before the deadline. Do not promise acceptance: seller agreement, item condition, eligibility and responsibility still control the actual case."
      ]},
      {heading:"Understand the published logistics risk boundary",paragraphs:[
        "PikoBuy's shipping terms say parcels are carried by third-party logistics providers and that cross-border risks are unavoidable. The terms specifically mention customs policy, confiscation, damage, loss and peak-season delays among factors for which the platform does not assume risk, while saying it will assist with alerts and continued insurance improvements. This language should shape every responsible shipping page. No spreadsheet can guarantee customs clearance, no seizure, no damage or an exact delivery date.",
        "Risk planning is still possible. Check destination rules, avoid restricted products, describe parcel contents accurately, preserve evidence, compare insurance choices and choose packaging suited to the item. Save the route name, submitted weight, dimensions and dispatch date in the record. If tracking later stalls, that history helps separate a normal wait for the first scan from a parcel that has exceeded the published expectation. It also gives official support the account-specific facts it needs."
      ]},
      {heading:"A realistic shipping checklist",paragraphs:[
        "Before paying international freight, confirm the destination, product type, measured weight, parcel dimensions, packaging choice and route eligibility. Compare more than one route when available. Read the current billing method, restrictions, estimated time and insurance terms. Make sure the parcel contents and declared information are accurate. If the price is unexpectedly high, revisit packaging and consolidation, but do not remove necessary protection merely to force the quote downward.",
        "Finally, keep estimates and outcomes separate. Record what you expected, what the submitted parcel measured, what the platform charged and when tracking became available. Over time, that history improves future spreadsheet planning without pretending that one past parcel predicts every new one. A strong PikoBuy shipping guide does not advertise a secret cheapest route. It teaches readers to use measured inputs, current eligibility and a visible risk decision so that the delivered-cost estimate becomes more honest at every stage."
      ]}
    ]
  }
];

export function getCategoryRecord(slug:string){return categoryRecords.find(item=>item.slug===slug);}
export function getProductRecord(slug:string){return productRecords.find(item=>item.slug===slug);}
export function getSeoArticle(slug:string){return seoArticles.find(item=>item.slug===slug);}

const localizedArticleTitles: Record<string,string[]> = {
  en:["How to Use a PikoBuy Spreadsheet Without Treating It as Proof","PikoBuy QC Photos: A Category-by-Category Warehouse Inspection Guide","PikoBuy Shipping Cost: How Weight, Dimensions, Routes and Risk Change the Total"],
  de:["Eine PikoBuy-Tabelle nutzen, ohne sie als Beweis zu behandeln","PikoBuy QC-Fotos: Lagerprüfung nach Produktkategorie","PikoBuy Versandkosten: Gewicht, Maße, Routen und Risiken"],
  fr:["Utiliser un tableau PikoBuy sans le confondre avec une preuve","Photos QC PikoBuy : contrôle en entrepôt par catégorie","Frais PikoBuy : poids, dimensions, itinéraires et risques"],
  es:["Cómo usar una hoja PikoBuy sin tratarla como una prueba","Fotos QC de PikoBuy: inspección de almacén por categoría","Envío PikoBuy: peso, dimensiones, rutas y riesgos"],
  pl:["Jak korzystać z arkusza PikoBuy, nie uznając go za dowód","Zdjęcia QC PikoBuy: kontrola magazynowa według kategorii","Wysyłka PikoBuy: waga, wymiary, trasy i ryzyko"],
  it:["Come usare un foglio PikoBuy senza considerarlo una prova","Foto QC PikoBuy: controllo in magazzino per categoria","Spedizione PikoBuy: peso, dimensioni, rotte e rischi"],
  pt:["Como usar uma planilha PikoBuy sem tratá-la como prova","Fotos QC PikoBuy: inspeção por categoria no armazém","Envio PikoBuy: peso, dimensões, rotas e riscos"],
  nl:["Een PikoBuy-spreadsheet gebruiken zonder die als bewijs te zien","PikoBuy QC-foto's: magazijncontrole per categorie","PikoBuy-verzending: gewicht, afmetingen, routes en risico"],
  cs:["Jak používat tabulku PikoBuy, aniž byste ji považovali za důkaz","QC fotografie PikoBuy: kontrola skladu podle kategorií","Doprava PikoBuy: hmotnost, rozměry, trasy a rizika"],
  sk:["Ako používať tabuľku PikoBuy bez toho, aby bola dôkazom","QC fotografie PikoBuy: skladová kontrola podľa kategórie","Doprava PikoBuy: hmotnosť, rozmery, trasy a riziká"],
  ro:["Cum să folosești un tabel PikoBuy fără a-l considera dovadă","Fotografii QC PikoBuy: inspecție în depozit pe categorii","Transport PikoBuy: greutate, dimensiuni, rute și riscuri"],
  hu:["A PikoBuy táblázat használata bizonyítékként való kezelés nélkül","PikoBuy QC-fotók: raktári ellenőrzés kategóriánként","PikoBuy szállítás: súly, méretek, útvonalak és kockázat"],
  sv:["Så använder du ett PikoBuy-kalkylblad utan att se det som bevis","PikoBuy QC-bilder: lagerkontroll per kategori","PikoBuy-frakt: vikt, mått, rutter och risk"],
  da:["Sådan bruges et PikoBuy-regneark uden at betragte det som bevis","PikoBuy QC-fotos: lagerkontrol efter kategori","PikoBuy-fragt: vægt, mål, ruter og risiko"],
  no:["Slik bruker du et PikoBuy-regneark uten å se det som bevis","PikoBuy QC-bilder: lagerkontroll etter kategori","PikoBuy-frakt: vekt, mål, ruter og risiko"],
  fi:["PikoBuy-taulukon käyttö ilman että sitä pidetään todisteena","PikoBuy QC-kuvat: varastotarkastus tuoteryhmittäin","PikoBuy-toimitus: paino, mitat, reitit ja riskit"],
  el:["Χρήση φύλλου PikoBuy χωρίς να θεωρείται απόδειξη","Φωτογραφίες QC PikoBuy: έλεγχος αποθήκης ανά κατηγορία","Αποστολή PikoBuy: βάρος, διαστάσεις, διαδρομές και κίνδυνοι"],
  tr:["Bir PikoBuy tablosunu kanıt olarak görmeden kullanmak","PikoBuy QC fotoğrafları: kategoriye göre depo kontrolü","PikoBuy kargo: ağırlık, ölçüler, rotalar ve risk"],
  hr:["Kako koristiti PikoBuy tablicu bez tretiranja kao dokaza","PikoBuy QC fotografije: skladišna kontrola po kategoriji","PikoBuy dostava: težina, dimenzije, rute i rizik"],
  bg:["Как да използвате таблица PikoBuy, без да я приемате за доказателство","QC снимки PikoBuy: складова проверка по категории","Доставка PikoBuy: тегло, размери, маршрути и риск"],
  uk:["Як користуватися таблицею PikoBuy, не вважаючи її доказом","QC-фото PikoBuy: складська перевірка за категоріями","Доставка PikoBuy: вага, розміри, маршрути й ризики"],
  lt:["Kaip naudoti PikoBuy lentelę nelaikant jos įrodymu","PikoBuy QC nuotraukos: sandėlio patikra pagal kategoriją","PikoBuy siuntimas: svoris, matmenys, maršrutai ir rizika"],
  sl:["Kako uporabljati preglednico PikoBuy, ne da bi jo imeli za dokaz","PikoBuy QC fotografije: pregled skladišča po kategorijah","Pošiljanje PikoBuy: teža, mere, poti in tveganje"],
  et:["Kuidas kasutada PikoBuy tabelit ilma seda tõendiks pidamata","PikoBuy QC-fotod: laokontroll kategooriate kaupa","PikoBuy saatmine: kaal, mõõdud, marsruudid ja risk"],
};

export function getLocalizedArticleTitle(code:string,slug:string){
  const index=seoArticles.findIndex(item=>item.slug===slug);
  return localizedArticleTitles[code]?.[index] ?? seoArticles[index]?.title ?? slug;
}
