export type UiText = {
  review: string; language: string; contentRoutes: string; choosePage: string;
  open: string; originalEnglish: string; evidence: string; mainRecord: string;
  recheck: string; officialMaterial: string; editorialBoundary: string;
  factChecked: string; updated: string; completeDatabase: string; question: string;
  readMore: string; usdNote: string;
};

const rows: Record<string, string[]> = {
  en:["Review edition","Language","Content routes","Choose the page that matches the decision.","Open","Original English research","Evidence checklist","Main-site record","Re-check before acting.","Official public material reviewed","Editorial boundary","Fact-checked editorial","Updated","Open the complete product database","Question","Read more","USD reference conversion; excludes fees and shipping."],
  de:["Prüfversion","Sprache","Inhaltswege","Wähle die Seite, die zur Entscheidung passt.","Öffnen","Englische Originalrecherche","Prüfliste","Eintrag der Hauptseite","Vor einer Entscheidung erneut prüfen.","Geprüfte öffentliche Originalquellen","Redaktionelle Abgrenzung","Faktengeprüfter Beitrag","Aktualisiert","Komplette Produktdatenbank öffnen","Frage","Mehr lesen","USD-Referenzumrechnung; Gebühren und Versand sind nicht enthalten."],
  fr:["Version de contrôle","Langue","Parcours de contenu","Choisissez la page adaptée à votre décision.","Ouvrir","Recherche originale en anglais","Liste de vérification","Fiche du site principal","Vérifiez à nouveau avant d’agir.","Documents publics officiels examinés","Limite éditoriale","Article vérifié","Mis à jour","Ouvrir la base complète de produits","Question","Lire la suite","Conversion indicative en USD, hors frais et livraison."],
  es:["Versión de revisión","Idioma","Rutas de contenido","Elige la página que corresponda a la decisión.","Abrir","Investigación original en inglés","Lista de comprobación","Registro del sitio principal","Vuelve a comprobar antes de actuar.","Material público oficial revisado","Límite editorial","Artículo verificado","Actualizado","Abrir la base de productos completa","Pregunta","Leer más","Conversión orientativa a USD; no incluye comisiones ni envío."],
  pl:["Wersja kontrolna","Język","Ścieżki treści","Wybierz stronę pasującą do decyzji.","Otwórz","Oryginalne badanie po angielsku","Lista kontrolna","Rekord strony głównej","Sprawdź ponownie przed działaniem.","Sprawdzone oficjalne materiały publiczne","Granica redakcyjna","Artykuł zweryfikowany","Zaktualizowano","Otwórz pełną bazę produktów","Pytanie","Czytaj więcej","Orientacyjne przeliczenie na USD; bez opłat i wysyłki."],
  it:["Versione di controllo","Lingua","Percorsi dei contenuti","Scegli la pagina adatta alla decisione.","Apri","Ricerca originale in inglese","Elenco di verifica","Scheda del sito principale","Ricontrolla prima di procedere.","Materiale pubblico ufficiale verificato","Limite editoriale","Articolo verificato","Aggiornato","Apri il database completo dei prodotti","Domanda","Leggi altro","Conversione indicativa in USD; commissioni e spedizione escluse."],
  pt:["Versão de revisão","Idioma","Percursos de conteúdo","Escolha a página adequada à decisão.","Abrir","Pesquisa original em inglês","Lista de verificação","Registo do site principal","Verifique novamente antes de agir.","Material público oficial revisto","Limite editorial","Artigo verificado","Atualizado","Abrir a base completa de produtos","Pergunta","Ler mais","Conversão de referência em USD; não inclui taxas nem envio."],
  nl:["Controleversie","Taal","Inhoudsroutes","Kies de pagina die bij de beslissing past.","Openen","Origineel Engels onderzoek","Controlelijst","Record van de hoofdsite","Controleer opnieuw voordat je handelt.","Beoordeeld officieel openbaar materiaal","Redactionele grens","Feitelijk gecontroleerd artikel","Bijgewerkt","Volledige productdatabase openen","Vraag","Meer lezen","Indicatieve USD-omrekening; exclusief kosten en verzending."],
  cs:["Kontrolní verze","Jazyk","Obsahové cesty","Vyberte stránku odpovídající rozhodnutí.","Otevřít","Původní anglický výzkum","Kontrolní seznam","Záznam hlavního webu","Před akcí vše znovu ověřte.","Ověřené oficiální veřejné materiály","Redakční hranice","Fakticky ověřený článek","Aktualizováno","Otevřít úplnou databázi produktů","Otázka","Číst více","Orientační převod na USD; bez poplatků a dopravy."],
  sk:["Kontrolná verzia","Jazyk","Obsahové cesty","Vyberte stránku zodpovedajúcu rozhodnutiu.","Otvoriť","Pôvodný anglický výskum","Kontrolný zoznam","Záznam hlavnej stránky","Pred konaním všetko znovu overte.","Overené oficiálne verejné materiály","Redakčná hranica","Fakticky overený článok","Aktualizované","Otvoriť úplnú databázu produktov","Otázka","Čítať viac","Orientačný prepočet na USD; bez poplatkov a dopravy."],
  ro:["Versiune de verificare","Limbă","Trasee de conținut","Alege pagina potrivită deciziei.","Deschide","Cercetare originală în engleză","Listă de verificare","Înregistrarea site-ului principal","Verifică din nou înainte de a acționa.","Material public oficial verificat","Limită editorială","Articol verificat factual","Actualizat","Deschide baza completă de produse","Întrebare","Citește mai mult","Conversie orientativă în USD; fără taxe și transport."],
  hu:["Ellenőrző változat","Nyelv","Tartalmi útvonalak","Válaszd a döntéshez illő oldalt.","Megnyitás","Eredeti angol kutatás","Ellenőrzőlista","A főoldal rekordja","Döntés előtt ellenőrizd újra.","Ellenőrzött hivatalos nyilvános anyag","Szerkesztői korlát","Tényellenőrzött cikk","Frissítve","A teljes termékadatbázis megnyitása","Kérdés","Tovább","Tájékoztató USD-átváltás; díjak és szállítás nélkül."],
  sv:["Granskningsversion","Språk","Innehållsvägar","Välj sidan som passar beslutet.","Öppna","Ursprunglig engelsk research","Kontrollista","Post på huvudwebbplatsen","Kontrollera igen innan du agerar.","Granskat officiellt offentligt material","Redaktionell gräns","Faktagranskad artikel","Uppdaterad","Öppna hela produktdatabasen","Fråga","Läs mer","Vägledande USD-omräkning; avgifter och frakt ingår inte."],
  da:["Kontrolversion","Sprog","Indholdsruter","Vælg siden, der passer til beslutningen.","Åbn","Original engelsk research","Kontrolliste","Post på hovedsiden","Kontrollér igen før du handler.","Gennemgået officielt offentligt materiale","Redaktionel grænse","Faktatjekket artikel","Opdateret","Åbn hele produktdatabasen","Spørgsmål","Læs mere","Vejledende USD-omregning; gebyrer og fragt er ikke medregnet."],
  no:["Kontrollversjon","Språk","Innholdsruter","Velg siden som passer til beslutningen.","Åpne","Opprinnelig engelsk research","Kontrolliste","Oppføring på hovedsiden","Kontroller på nytt før du handler.","Gjennomgått offisielt offentlig materiale","Redaksjonell grense","Faktasjekket artikkel","Oppdatert","Åpne hele produktdatabasen","Spørsmål","Les mer","Veiledende USD-omregning; gebyrer og frakt er ikke inkludert."],
  fi:["Tarkistusversio","Kieli","Sisältöpolut","Valitse päätökseen sopiva sivu.","Avaa","Alkuperäinen englanninkielinen tutkimus","Tarkistuslista","Pääsivuston tietue","Tarkista uudelleen ennen toimintaa.","Tarkistettu virallinen julkinen aineisto","Toimituksellinen rajaus","Faktantarkistettu artikkeli","Päivitetty","Avaa koko tuotetietokanta","Kysymys","Lue lisää","Ohjeellinen USD-muunnos; ei sisällä maksuja eikä toimitusta."],
  el:["Έκδοση ελέγχου","Γλώσσα","Διαδρομές περιεχομένου","Επιλέξτε τη σελίδα που ταιριάζει στην απόφαση.","Άνοιγμα","Αρχική έρευνα στα αγγλικά","Λίστα ελέγχου","Καταχώριση κύριου ιστότοπου","Ελέγξτε ξανά πριν ενεργήσετε.","Ελεγμένο επίσημο δημόσιο υλικό","Συντακτικό όριο","Άρθρο με έλεγχο στοιχείων","Ενημερώθηκε","Άνοιγμα πλήρους βάσης προϊόντων","Ερώτηση","Διαβάστε περισσότερα","Ενδεικτική μετατροπή USD· δεν περιλαμβάνει τέλη ή αποστολή."],
  tr:["İnceleme sürümü","Dil","İçerik yolları","Karara uygun sayfayı seçin.","Aç","Özgün İngilizce araştırma","Kontrol listesi","Ana site kaydı","İşlem yapmadan önce tekrar kontrol edin.","İncelenen resmî kamu materyali","Editoryal sınır","Doğrulanmış makale","Güncellendi","Tam ürün veritabanını aç","Soru","Devamını oku","Gösterge niteliğinde USD dönüşümü; ücretler ve kargo hariçtir."],
  hr:["Kontrolna verzija","Jezik","Putovi sadržaja","Odaberite stranicu koja odgovara odluci.","Otvori","Izvorno istraživanje na engleskom","Kontrolni popis","Zapis glavne stranice","Ponovno provjerite prije postupanja.","Pregledani službeni javni materijali","Urednička granica","Članak s provjerenim činjenicama","Ažurirano","Otvori potpunu bazu proizvoda","Pitanje","Pročitaj više","Orijentacijska pretvorba u USD; bez naknada i dostave."],
  bg:["Контролна версия","Език","Пътища на съдържанието","Изберете страницата, подходяща за решението.","Отвори","Оригинално проучване на английски","Контролен списък","Запис от основния сайт","Проверете отново преди действие.","Проверени официални публични материали","Редакционна граница","Статия с проверени факти","Актуализирано","Отвори пълната продуктова база","Въпрос","Прочети още","Ориентировъчно преобразуване в USD; без такси и доставка."],
  uk:["Контрольна версія","Мова","Маршрути вмісту","Виберіть сторінку відповідно до рішення.","Відкрити","Оригінальне дослідження англійською","Контрольний список","Запис основного сайту","Перевірте ще раз перед дією.","Перевірені офіційні публічні матеріали","Редакційна межа","Стаття з перевіреними фактами","Оновлено","Відкрити повну базу товарів","Питання","Читати далі","Орієнтовний перерахунок у USD; без комісій і доставки."],
  lt:["Kontrolinė versija","Kalba","Turinio keliai","Pasirinkite sprendimui tinkamą puslapį.","Atidaryti","Originalus tyrimas anglų kalba","Kontrolinis sąrašas","Pagrindinės svetainės įrašas","Prieš veikdami patikrinkite dar kartą.","Patikrinta oficiali vieša medžiaga","Redakcinė riba","Faktų patikrintas straipsnis","Atnaujinta","Atidaryti visą produktų duomenų bazę","Klausimas","Skaityti daugiau","Orientacinis perskaičiavimas į USD; be mokesčių ir siuntimo."],
  sl:["Kontrolna različica","Jezik","Vsebinske poti","Izberite stran, ki ustreza odločitvi.","Odpri","Izvirna raziskava v angleščini","Kontrolni seznam","Zapis glavnega spletnega mesta","Pred dejanjem ponovno preverite.","Pregledano uradno javno gradivo","Uredniška meja","Članek s preverjenimi dejstvi","Posodobljeno","Odpri celotno zbirko izdelkov","Vprašanje","Preberi več","Okvirna pretvorba v USD; brez pristojbin in dostave."],
  et:["Kontrollversioon","Keel","Sisu teekonnad","Valige otsusele sobiv leht.","Ava","Algne ingliskeelne uurimus","Kontrollnimekiri","Põhisaidi kirje","Kontrollige enne tegutsemist uuesti.","Kontrollitud ametlik avalik materjal","Toimetuslik piir","Faktikontrollitud artikkel","Uuendatud","Ava täielik tooteandmebaas","Küsimus","Loe edasi","Näidiskonversioon USD-sse; tasud ja saatmine ei sisaldu."],
};

export function getUi(code: string): UiText {
  const a = rows[code] ?? rows.en;
  return {review:a[0],language:a[1],contentRoutes:a[2],choosePage:a[3],open:a[4],originalEnglish:a[5],evidence:a[6],mainRecord:a[7],recheck:a[8],officialMaterial:a[9],editorialBoundary:a[10],factChecked:a[11],updated:a[12],completeDatabase:a[13],question:a[14],readMore:a[15],usdNote:a[16]};
}

const categoryNames: Record<string,string[]> = {
  en:["Shoes","Hoodies","T-shirts","Jackets","Pants & shorts","Headwear","Accessories","Jerseys","Electronics","All products"],
  de:["Schuhe","Hoodies","T-Shirts","Jacken","Hosen und Shorts","Kopfbedeckungen","Accessoires","Trikots","Elektronik","Alle Produkte"],
  fr:["Chaussures","Sweats à capuche","T-shirts","Vestes","Pantalons et shorts","Couvre-chefs","Accessoires","Maillots","Électronique","Tous les produits"],
  es:["Calzado","Sudaderas","Camisetas","Chaquetas","Pantalones y shorts","Sombreros","Accesorios","Camisetas deportivas","Electrónica","Todos los productos"],
  pl:["Buty","Bluzy z kapturem","T-shirty","Kurtki","Spodnie i szorty","Nakrycia głowy","Akcesoria","Koszulki sportowe","Elektronika","Wszystkie produkty"],
  it:["Scarpe","Felpe con cappuccio","T-shirt","Giacche","Pantaloni e shorts","Copricapi","Accessori","Maglie sportive","Elettronica","Tutti i prodotti"],
  pt:["Calçado","Moletons","Camisetas","Casacos","Calças e shorts","Chapéus","Acessórios","Camisolas desportivas","Eletrónica","Todos os produtos"],
  nl:["Schoenen","Hoodies","T-shirts","Jassen","Broeken en shorts","Hoofddeksels","Accessoires","Sportshirts","Elektronica","Alle producten"],
  cs:["Boty","Mikiny","Trička","Bundy","Kalhoty a šortky","Pokrývky hlavy","Doplňky","Dresy","Elektronika","Všechny produkty"],
  sk:["Topánky","Mikiny","Tričká","Bundy","Nohavice a šortky","Pokrývky hlavy","Doplnky","Dresy","Elektronika","Všetky produkty"],
  ro:["Încălțăminte","Hanorace","Tricouri","Jachete","Pantaloni și șorturi","Articole pentru cap","Accesorii","Tricouri sportive","Electronice","Toate produsele"],
  hu:["Cipők","Kapucnis felsők","Pólók","Kabátok","Nadrágok és rövidnadrágok","Fejfedők","Kiegészítők","Mezek","Elektronika","Minden termék"],
  sv:["Skor","Hoodies","T-shirts","Jackor","Byxor och shorts","Huvudbonader","Accessoarer","Matchtröjor","Elektronik","Alla produkter"],
  da:["Sko","Hættetrøjer","T-shirts","Jakker","Bukser og shorts","Hovedbeklædning","Tilbehør","Trøjer","Elektronik","Alle produkter"],
  no:["Sko","Hettegensere","T-skjorter","Jakker","Bukser og shorts","Hodeplagg","Tilbehør","Drakter","Elektronikk","Alle produkter"],
  fi:["Kengät","Hupparit","T-paidat","Takit","Housut ja shortsit","Päähineet","Asusteet","Pelipaidat","Elektroniikka","Kaikki tuotteet"],
  el:["Παπούτσια","Φούτερ","Μπλουζάκια","Μπουφάν","Παντελόνια και σορτς","Καπέλα","Αξεσουάρ","Φανέλες","Ηλεκτρονικά","Όλα τα προϊόντα"],
  tr:["Ayakkabılar","Kapüşonlular","Tişörtler","Ceketler","Pantolon ve şortlar","Şapkalar","Aksesuarlar","Formalar","Elektronik","Tüm ürünler"],
  hr:["Cipele","Majice s kapuljačom","Majice","Jakne","Hlače i kratke hlače","Pokrivala za glavu","Dodaci","Dresovi","Elektronika","Svi proizvodi"],
  bg:["Обувки","Суитшърти","Тениски","Якета","Панталони и шорти","Шапки","Аксесоари","Екипи","Електроника","Всички продукти"],
  uk:["Взуття","Худі","Футболки","Куртки","Штани та шорти","Головні убори","Аксесуари","Форми","Електроніка","Усі товари"],
  lt:["Batai","Džemperiai","Marškinėliai","Striukės","Kelnės ir šortai","Galvos apdangalai","Aksesuarai","Marškinėliai","Elektronika","Visi produktai"],
  sl:["Čevlji","Puloverji s kapuco","Majice","Jakne","Hlače in kratke hlače","Pokrivala","Dodatki","Dresi","Elektronika","Vsi izdelki"],
  et:["Jalatsid","Pusad","T-särgid","Joped","Püksid ja lühikesed püksid","Peakatted","Aksessuaarid","Särgid","Elektroonika","Kõik tooted"],
};

export function getLocalizedCategoryName(code:string,index:number){return categoryNames[code]?.[index] ?? categoryNames.en[index] ?? "";}
