import type { Metadata } from "next";
import ArticleShell from "../article-shell";

export const metadata: Metadata = { title: "Official Sources and Evidence Limits | LoloBuy Spreadsheet", description: "A dated ledger of LoloBuy official public statements, independent FindSpreadsheet observations and claims excluded without evidence." };

export default function SourcesPage() {
  return (
    <ArticleShell eyebrow="Source ledger · Version 1.1 · Reviewed 13 August 2026" title="What this site can verify—and what it deliberately does not claim" lead="A transparent ledger makes the site easier to maintain and harder to misread. Each LoloBuy-specific statement should have a source, a review date and a clear boundary." ctaTitle="Inspect current product data" ctaText="The product database is maintained separately on FindSpreadsheet.">
      <h2>Open the complete evidence files</h2>
      <p>The homepage ledger is an index, not the evidence itself. These three files contain the observation record, the reasoning behind each conclusion and the practical limits readers should carry into a purchase decision.</p>
      <div className="article-index">
        <a href="/sources/lolobuy-official-evidence/"><small>Official platform</small><strong>What LoloBuy’s current public application confirms</strong><span>Read →</span><p className="article-summary">A route-by-route audit of ordering, warehouse, photo, estimate, rehearsal and parcel-submission surfaces, including facts that cannot be inferred from them.</p></a>
        <a href="/sources/findspreadsheet-database-evidence/"><small>Database observation</small><strong>How to read a FindSpreadsheet row as dated evidence</strong><span>Read →</span><p className="article-summary">A field-level guide to titles, images, prices, destinations and review dates—and the checks required before an order is submitted.</p></a>
        <a href="/sources/product-freshness/"><small>Product freshness</small><strong>Homepage link, image and price observation record</strong><span>Audit →</span><p className="article-summary">Twelve source product pages, twenty-three tested destinations, original CNY observations and the dated benchmark used for editorial USD estimates.</p></a>
        <a href="/method/"><small>Editorial standard</small><strong>How claims are classified, checked and corrected</strong><span>Audit →</span><p className="article-summary">The reproducible method used to separate official facts, changing observations, independent advice and unsupported claims.</p></a>
        <a href="/editorial-policy/"><small>Corrections policy</small><strong>How independence, corrections and changing claims are handled</strong><span>Read →</span><p className="article-summary">The public rule for material corrections, product-image evidence, translations and commercial claims.</p></a>
      </div>
      <h2>Primary source: LoloBuy official website</h2><p><a href="https://www.lolobuy.com/" target="_blank" rel="noopener noreferrer"><strong>lolobuy.com ↗</strong></a></p><p><strong>Reviewed:</strong> 13 August 2026. The official homepage and current production application present this high-level sequence:</p>
      <ol><li>LoloBuy says it assists users purchasing products from online and offline channels in China.</li><li>It says a user can paste a product link to complete an order.</li><li>It describes products being stored in a warehouse.</li><li>It says users can select stored products and submit them as a single parcel, and promotes a global shipping service.</li></ol>
      <div className="article-note">These statements verify a general purchasing and parcel-submission workflow. They do not, by themselves, verify a specific shipping discount, warehouse period, insurance rule, compensation amount, delivery time, stock status, route divisor, refund outcome or universal QC service. Each detailed commercial claim needs its own current official source.</div>
      <h2>Current official interface evidence</h2><p>The public production application was reviewed in addition to the homepage copy. On the review date, the homepage identified the release as version 1.0.1 with a build timestamp of 3 August 2026. Interface routes and labels can confirm that a feature surface exists; they do not prove that every account, country, product or route receives the same option.</p>
      <table className="evidence-table"><thead><tr><th>Official surface observed</th><th>What it supports</th><th>What it does not prove</th></tr></thead><tbody>
        <tr><td>Product detail, keyword search, image search and manual order</td><td>LoloBuy provides several paths for identifying or entering a product request</td><td>That every third-party product is purchasable or can be returned</td></tr>
        <tr><td>Manual-order fields for link, title, specification, price, domestic freight, quantity and images</td><td>A complete order request can require more detail than a URL alone</td><td>That a spreadsheet price or option remains current</td></tr>
        <tr><td>Order states including ordering, shipped, warehouse arrival, return and submitted package</td><td>The workflow separates domestic purchasing, warehouse receipt and parcel submission</td><td>A guaranteed processing or international delivery time</td></tr>
        <tr><td>Stored-items page, quality-information component, normal and detailed photo labels</td><td>Warehouse and photo-related evidence is represented in the application</td><td>That every item receives identical inspection coverage or that photos prove authenticity</td></tr>
        <tr><td>Freight estimate with destination, weight, dimensions, restrictions and route results</td><td>Shipping comparison depends on parcel and route inputs</td><td>One permanent rate, divisor or eligible line for all parcels</td></tr>
        <tr><td>Rehearsal interface described as simulated pre-packing</td><td>A user can obtain a packed-weight and size result before real parcel submission when available</td><td>That rehearsal dispatches the goods or removes route restrictions</td></tr>
        <tr><td>Parcel address, packaging, route, declaration, notices and fee-detail fields</td><td>Parcel submission requires several decisions and can expose component charges</td><td>That every charge label applies to every shipment</td></tr>
      </tbody></table>
      <h2>How interface evidence is used</h2><p>We use official interface evidence conservatively. A route name or field proves that the current production application contains that route or field. A conditional button proves only that the application can expose the action under some conditions. A translated help message can explain the intended function, but it does not establish universal eligibility, price or outcome.</p><p>When the interface changes, page claims must be reviewed again. A build label or screenshot is not a permanent policy document. This is why every guide records a review date and avoids fixed commercial promises unless the live official source states them clearly.</p>
      <h2>Shipping evidence now has its own decision library</h2><p>The <a href="/shipping/">shipping research centre</a> separates estimate inputs, route eligibility, rehearsal packing, customs declarations and tracking exceptions. This prevents one broad article from repeating the same weight explanation while leaving declarations or delivery handling underexplained.</p><p>Each page names the official surface reviewed and preserves the same boundary: a current route or field proves that the application can support that stage, not that every user receives the same option, price or outcome.</p>
      <h2>Database source: FindSpreadsheet</h2><p><a href="https://findspreadsheet.com/" target="_blank" rel="noopener noreferrer"><strong>findspreadsheet.com ↗</strong></a></p><p><strong>Reviewed:</strong> 13 August 2026. The public site presents category pages and product-detail routes for T-shirts, shoes, hoodies, jackets, pants and shorts, headwear, accessories, jerseys, electronics and other finds. Twelve homepage product pages and eleven category or all-product destinations were also tested successfully on that date.</p>
      <p>FindSpreadsheet is used as a product-discovery source, not as evidence for a LoloBuy policy. A database row can establish what title, image, category, price observation and destination link were displayed when reviewed. It cannot prove current seller stock, product authenticity, permanent pricing, purchase acceptance or the final condition of a warehouse item.</p>
      <h2>Editorial guidance</h2><p>The QC and shipping-weight articles on this site are independent educational frameworks. They do not represent a LoloBuy promise or policy. Every such page carries an evidence-boundary note.</p>
      <h2>Three evidence classes used on this site</h2><div className="checklist-grid"><div className="checklist-card"><h3>Official platform fact</h3><p>A dated statement or interface feature visible on LoloBuy’s own current website. Wording is limited to what the source actually supports.</p></div><div className="checklist-card"><h3>Dated database observation</h3><p>A product row, link, option or price displayed by FindSpreadsheet or the underlying seller at a recorded time.</p></div><div className="checklist-card"><h3>Independent guidance</h3><p>A repeatable checking method for links, measurements, photographs or shipping comparisons, clearly separated from platform policy.</p></div><div className="checklist-card"><h3>Unverified claim</h3><p>A statement that lacks a current primary source. It is excluded, qualified or listed as an open question rather than published as fact.</p></div></div>
      <h2>Claims excluded without stronger evidence</h2><ul><li>“Every item is manually QC verified.”</li><li>“Out-of-stock products are removed every day.”</li><li>“Only the best batches are listed.”</li><li>A guaranteed discount, coupon value or shipping saving.</li><li>A guaranteed delivery speed, refund or compensation outcome.</li></ul>
      <h2>Questions still requiring a current page-level source</h2><ul><li>Universal free-storage duration and any extension pricing.</li><li>Exact inspection coverage included with every order.</li><li>Country- and line-specific insurance or compensation conditions.</li><li>Seller and platform after-sales eligibility for a particular item.</li><li>Current coupons, freight promotions, tax handling and route surcharges.</li></ul><p>These questions may have answers inside an account, order, parcel quote or current agreement. Until a stable official source can be attached to a public claim, the site directs readers to check the live transaction-specific information.</p>
      <h2>Update rule</h2><p>When a source changes, retain the prior review date in the update log, revise the affected page and avoid silently presenting an old policy as current. Material commercial claims should be rechecked more often than evergreen educational guidance. If an interface feature disappears, any guide that relied on it must be rewritten or marked as an archived observation.</p>
    </ArticleShell>
  );
}
