export const localeCodes = [
  "en", "de", "fr", "es", "it", "pt", "pl", "nl", "sv", "da", "no", "fi",
  "cs", "ro", "hu", "el", "uk", "tr", "ru", "bg", "ja", "ko", "ar", "zh",
] as const;

export type LocaleCode = (typeof localeCodes)[number];

export const languageNames: Record<LocaleCode, string> = {
  en: "English", de: "Deutsch", fr: "Français", es: "Español", it: "Italiano", pt: "Português",
  pl: "Polski", nl: "Nederlands", sv: "Svenska", da: "Dansk", no: "Norsk", fi: "Suomi",
  cs: "Čeština", ro: "Română", hu: "Magyar", el: "Ελληνικά", uk: "Українська", tr: "Türkçe",
  ru: "Русский", bg: "Български", ja: "日本語", ko: "한국어", ar: "العربية", zh: "中文",
};

export const categories = [
  { key: "shoes", href: "https://findspreadsheet.com/shoes/", mark: "SH" },
  { key: "hoodies", href: "https://findspreadsheet.com/hoodies-sweaters/", mark: "HD" },
  { key: "tshirts", href: "https://findspreadsheet.com/t-shirts/", mark: "TS" },
  { key: "jackets", href: "https://findspreadsheet.com/jackets/", mark: "JK" },
  { key: "pants", href: "https://findspreadsheet.com/pants-shorts/", mark: "PS" },
  { key: "headwear", href: "https://findspreadsheet.com/headwear/", mark: "HW" },
  { key: "accessories", href: "https://findspreadsheet.com/accessories/", mark: "AC" },
  { key: "jerseys", href: "https://findspreadsheet.com/Jersey/", mark: "JR" },
  { key: "electronics", href: "https://findspreadsheet.com/electronics/", mark: "EL" },
  { key: "other", href: "https://findspreadsheet.com/other-stuff/", mark: "OT" },
] as const;

export const products = [
  {
    slug: "gallery-short",
    name: "Gallery Short",
    itemId: "7711437541",
    category: "Pants / Shorts",
    categoryIndex: 4,
    usd: "$19.97",
    cny: "¥145",
    image: "https://findspreadsheet.com/uploads/allimg/20260319/1-260319153159600.webp",
    href: "https://findspreadsheet.com/pants-shorts/gallery-short-3003.html",
  },
  {
    slug: "high-quality-burberry-jacket",
    name: "High quality Burberry Jacket",
    itemId: "7714490692",
    category: "Jackets",
    categoryIndex: 3,
    usd: "$20.39",
    cny: "¥148",
    image: "https://findspreadsheet.com/uploads/allimg/20260401/1-260401093931395.webp",
    href: "https://findspreadsheet.com/jackets/high-quality-burberry-jacket-3131.html",
  },
  {
    slug: "sock-37-colores-top",
    name: "sock(37 colores TOP)",
    itemId: "7714498572",
    category: "Other Finds",
    categoryIndex: 9,
    usd: "$2.75",
    cny: "¥20",
    image: "https://findspreadsheet.com/uploads/allimg/20260319/1-260319152Z2T0.webp",
    href: "https://findspreadsheet.com/other-stuff/sock-37-colores-top-3001.html",
  },
  {
    slug: "dior-t-shirthoodie-39-style-top",
    name: "Dior T-shirtHoodie（39 style TOP",
    itemId: "7711391539",
    category: "Hoodies",
    categoryIndex: 1,
    usd: "$11.71",
    cny: "¥85",
    image: "https://findspreadsheet.com/uploads/allimg/20260319/1-260319152I0Q1.webp",
    href: "https://findspreadsheet.com/hoodies-sweaters/dior-t-shirthoodie-39-style-top-3000.html",
  },
  {
    slug: "cp-company-t-shirt",
    name: "cp company t-shirt",
    itemId: "7714478764",
    category: "T-Shirts",
    categoryIndex: 2,
    usd: "$16.25",
    cny: "¥118",
    image: "https://findspreadsheet.com/uploads/allimg/20260319/1-26031915254QX.webp",
    href: "https://findspreadsheet.com/t-shirts/cp-company-t-shirt-2999.html",
  },
  {
    slug: "the-north-face-outdoorjacket",
    name: "The North Face Outdoorjacket",
    itemId: "7711524403",
    category: "Jackets",
    categoryIndex: 3,
    usd: "$19.97",
    cny: "¥145",
    image: "https://findspreadsheet.com/uploads/allimg/20260319/1-260319152350518.webp",
    href: "https://findspreadsheet.com/jackets/the-north-face-outdoorjacket-2998.html",
  },
] as const;

export type Product = (typeof products)[number];

export type Copy = {
  nav: [string, string, string, string, string, string, string];
  heroTitle: string; heroLede: string; explore: string; beginner: string; byline: string;
  source: string; checks: string; updated: string; researchNote: string;
  categoryTitle: string; browse: string; spreadsheetTitle: string; spreadsheetIntro: string;
  guidesTitle: string; guidesIntro: string; reviewTitle: string; reviewIntro: string;
  seoTitle: string; seoIntro: string; faqTitle: string; faqIntro: string;
  qcBody: string; shippingBody: string; beginnerBody: string; open: string; verify: string; footer: string;
};

const en: Copy = {
  nav: ["Spreadsheet", "Categories", "Guides", "QC Guide", "Shipping", "Reviews", "SEO Articles"],
  heroTitle: "The LoloBuy Spreadsheet, researched—not recycled.",
  heroLede: "Product discovery, QC checklists, and shipping research for shoppers in Europe and North America.",
  explore: "Explore the spreadsheet", beginner: "Read the beginner guide", byline: "Independent guide by the FindSpreadsheet team",
  source: "Official sources", checks: "Independent checks", updated: "Updated Aug 2026",
  researchNote: "We verify destination links, separate confirmed platform workflow from estimates, and flag details that can change at checkout.",
  categoryTitle: "Popular LoloBuy finds", browse: "Browse 10 categories",
  spreadsheetTitle: "A product index with a research layer", spreadsheetIntro: "Open a verified category or product page on FindSpreadsheet, then review the original seller link, visible details, and live checkout information before ordering.",
  guidesTitle: "LoloBuy buyer guides", guidesIntro: "Short, evidence-led guides for the steps between finding a product and submitting an international parcel.",
  reviewTitle: "LoloBuy review: what can be verified", reviewIntro: "We separate the public workflow from variable prices, promotions, route availability, and individual experiences. No invented scores and no permanent promises.",
  seoTitle: "Research articles", seoIntro: "Long-form English articles built around real buyer questions, official sources, and dated verification notes.",
  faqTitle: "LoloBuy frequently asked questions", faqIntro: "Concise answers, with variable details clearly marked.",
  qcBody: "QC photos can help you inspect visible color, shape, logos, stitching, measurements, and obvious damage. They cannot prove material composition, long-term durability, authenticity, or fit. Compare every visible detail with the seller listing before shipping.",
  shippingBody: "International shipping depends on parcel weight and dimensions, destination, route restrictions, carrier rules, customs, and optional services. Treat any calculator result as an estimate and confirm the live total in your account before submitting a parcel.",
  beginnerBody: "Paste a supported product link, confirm the item details, pay for the item, wait for domestic delivery to the warehouse, review the available inspection information, and only then choose an international route. Screens and terms can change, so verify each live step.",
  open: "Open verified page", verify: "Verify live price and availability", footer: "Independent educational and product-discovery site operated by the FindSpreadsheet team. Not owned, operated, or endorsed by LoloBuy.",
};

export const copy: Record<LocaleCode, Copy> = {
  en,
  de: { nav: ["Tabelle", "Kategorien", "Ratgeber", "QC-Ratgeber", "Versand", "Bewertungen", "SEO-Artikel"], heroTitle: "Die LoloBuy-Tabelle: recherchiert, nicht recycelt.", heroLede: "Produktsuche, QC-Checklisten und Versandinformationen für Käufer in Europa und Nordamerika.", explore: "Tabelle entdecken", beginner: "Einsteiger-Ratgeber lesen", byline: "Unabhängiger Ratgeber des FindSpreadsheet-Teams", source: "Offizielle Quellen", checks: "Unabhängige Prüfungen", updated: "Aktualisiert Aug. 2026", researchNote: "Wir prüfen Ziellinks, trennen bestätigte Abläufe von Schätzungen und kennzeichnen Angaben, die sich beim Checkout ändern können.", categoryTitle: "Beliebte LoloBuy-Funde", browse: "10 Kategorien ansehen", spreadsheetTitle: "Produktindex mit Recherche-Ebene", spreadsheetIntro: "Öffne eine geprüfte Kategorie- oder Produktseite bei FindSpreadsheet und kontrolliere danach Verkäuferlink, sichtbare Details und Live-Checkout.", guidesTitle: "LoloBuy-Kaufratgeber", guidesIntro: "Kurze, quellenbasierte Hilfen von der Produktsuche bis zum internationalen Paket.", reviewTitle: "LoloBuy-Bewertung: Was ist belegbar?", reviewIntro: "Wir trennen den öffentlichen Ablauf von variablen Preisen, Aktionen, Routen und Einzelerfahrungen. Keine erfundenen Bewertungen.", seoTitle: "Rechercheartikel", seoIntro: "Ausführliche englische Artikel zu echten Käuferfragen mit Quellen und Prüfdatum.", faqTitle: "Häufige Fragen zu LoloBuy", faqIntro: "Kurze Antworten mit klar gekennzeichneten veränderlichen Angaben.", qcBody: "QC-Fotos helfen bei sichtbaren Farben, Formen, Logos, Nähten, Maßen und Schäden. Material, Haltbarkeit, Echtheit oder Passform beweisen sie nicht. Vergleiche jedes Detail vor dem Versand.", shippingBody: "Der internationale Versand hängt von Gewicht, Abmessungen, Ziel, Routenregeln, Zoll und Zusatzdiensten ab. Rechnerwerte sind Schätzungen; bestätige die Live-Summe vor dem Absenden.", beginnerBody: "Füge einen unterstützten Produktlink ein, prüfe die Artikeldaten, bezahle, warte auf die Lagerzustellung, kontrolliere die Inspektionsdaten und wähle erst dann eine internationale Route.", open: "Geprüfte Seite öffnen", verify: "Live-Preis und Verfügbarkeit prüfen", footer: "Unabhängige Informations- und Produktsuchseite des FindSpreadsheet-Teams. Nicht Eigentum von LoloBuy und nicht von LoloBuy betrieben oder unterstützt." },
  fr: { nav: ["Tableur", "Catégories", "Guides", "Guide QC", "Livraison", "Avis", "Articles SEO"], heroTitle: "Le tableur LoloBuy, recherché — pas recyclé.", heroLede: "Découverte de produits, listes QC et recherches d’expédition pour l’Europe et l’Amérique du Nord.", explore: "Explorer le tableur", beginner: "Lire le guide débutant", byline: "Guide indépendant de l’équipe FindSpreadsheet", source: "Sources officielles", checks: "Vérifications indépendantes", updated: "Mis à jour août 2026", researchNote: "Nous vérifions les liens, séparons le processus confirmé des estimations et signalons les données variables au paiement.", categoryTitle: "Trouvailles LoloBuy populaires", browse: "Voir 10 catégories", spreadsheetTitle: "Un index produit enrichi par la recherche", spreadsheetIntro: "Ouvrez une catégorie ou un produit vérifié sur FindSpreadsheet, puis contrôlez le lien vendeur, les détails visibles et les informations en direct avant de commander.", guidesTitle: "Guides d’achat LoloBuy", guidesIntro: "Des guides courts et sourcés entre la découverte d’un produit et l’envoi international.", reviewTitle: "Avis LoloBuy : ce qui est vérifiable", reviewIntro: "Nous distinguons le processus public des prix, promotions, routes et expériences variables. Aucun score inventé.", seoTitle: "Articles de recherche", seoIntro: "Articles longs en anglais fondés sur de vraies questions, des sources officielles et une date de vérification.", faqTitle: "Questions fréquentes LoloBuy", faqIntro: "Réponses concises avec les éléments variables clairement indiqués.", qcBody: "Les photos QC aident à contrôler couleur, forme, logos, coutures, mesures et défauts visibles. Elles ne prouvent ni matière, ni durabilité, ni authenticité, ni taille. Comparez tout avant l’envoi.", shippingBody: "L’expédition dépend du poids, des dimensions, de la destination, des restrictions, de la douane et des options. Un calculateur reste une estimation : confirmez le total en direct.", beginnerBody: "Collez un lien compatible, vérifiez l’article, payez, attendez l’arrivée à l’entrepôt, examinez l’inspection disponible puis choisissez une route internationale.", open: "Ouvrir la page vérifiée", verify: "Vérifier prix et disponibilité", footer: "Site indépendant d’information et de découverte exploité par l’équipe FindSpreadsheet. Ni détenu, ni géré, ni approuvé par LoloBuy." },
  es: { nav: ["Hoja", "Categorías", "Guías", "Guía QC", "Envío", "Reseñas", "Artículos SEO"], heroTitle: "La hoja de LoloBuy, investigada — no reciclada.", heroLede: "Descubrimiento de productos, controles QC e investigación de envíos para Europa y Norteamérica.", explore: "Explorar la hoja", beginner: "Leer la guía inicial", byline: "Guía independiente del equipo FindSpreadsheet", source: "Fuentes oficiales", checks: "Comprobaciones independientes", updated: "Actualizado ago. 2026", researchNote: "Verificamos enlaces, separamos procesos confirmados de estimaciones y marcamos datos que pueden cambiar al pagar.", categoryTitle: "Hallazgos LoloBuy populares", browse: "Ver 10 categorías", spreadsheetTitle: "Índice de productos con investigación", spreadsheetIntro: "Abre una categoría o producto verificado en FindSpreadsheet y revisa el enlace original, los detalles visibles y la información en vivo antes de comprar.", guidesTitle: "Guías de compra LoloBuy", guidesIntro: "Guías breves basadas en fuentes desde el hallazgo hasta el paquete internacional.", reviewTitle: "Reseña de LoloBuy: lo verificable", reviewIntro: "Separamos el flujo público de precios, promociones, rutas y experiencias variables. Sin puntuaciones inventadas.", seoTitle: "Artículos de investigación", seoIntro: "Artículos extensos en inglés basados en preguntas reales, fuentes oficiales y fecha de verificación.", faqTitle: "Preguntas frecuentes sobre LoloBuy", faqIntro: "Respuestas breves con los detalles variables bien señalados.", qcBody: "Las fotos QC ayudan a revisar color, forma, logotipos, costuras, medidas y daños visibles. No prueban material, duración, autenticidad ni ajuste. Compara todo antes del envío.", shippingBody: "El envío depende del peso, dimensiones, destino, restricciones, aduanas y servicios opcionales. Los cálculos son estimaciones; confirma el total en vivo.", beginnerBody: "Pega un enlace compatible, confirma el artículo, paga, espera su llegada al almacén, revisa la inspección disponible y después elige una ruta internacional.", open: "Abrir página verificada", verify: "Verificar precio y disponibilidad", footer: "Sitio independiente educativo y de descubrimiento operado por FindSpreadsheet. No pertenece a LoloBuy ni está gestionado o respaldado por LoloBuy." },
  it: { nav: ["Foglio", "Categorie", "Guide", "Guida QC", "Spedizione", "Recensioni", "Articoli SEO"], heroTitle: "Il foglio LoloBuy, studiato — non riciclato.", heroLede: "Ricerca prodotti, checklist QC e informazioni sulla spedizione per Europa e Nord America.", explore: "Esplora il foglio", beginner: "Leggi la guida iniziale", byline: "Guida indipendente del team FindSpreadsheet", source: "Fonti ufficiali", checks: "Controlli indipendenti", updated: "Aggiornato ago 2026", researchNote: "Verifichiamo i link, separiamo i processi confermati dalle stime e segnaliamo i dati variabili al checkout.", categoryTitle: "Prodotti LoloBuy popolari", browse: "Vedi 10 categorie", spreadsheetTitle: "Indice prodotti con livello di ricerca", spreadsheetIntro: "Apri una categoria o pagina verificata su FindSpreadsheet, poi controlla link venditore, dettagli visibili e dati live prima dell’ordine.", guidesTitle: "Guide all’acquisto LoloBuy", guidesIntro: "Guide brevi e documentate dalla scoperta del prodotto al pacco internazionale.", reviewTitle: "Recensione LoloBuy: cosa è verificabile", reviewIntro: "Separiamo il flusso pubblico da prezzi, promozioni, rotte ed esperienze variabili. Nessun punteggio inventato.", seoTitle: "Articoli di ricerca", seoIntro: "Articoli lunghi in inglese basati su domande reali, fonti ufficiali e date di verifica.", faqTitle: "Domande frequenti LoloBuy", faqIntro: "Risposte concise con i dettagli variabili chiaramente indicati.", qcBody: "Le foto QC aiutano a controllare colore, forma, loghi, cuciture, misure e danni visibili. Non provano materiale, durata, autenticità o vestibilità. Confronta tutto prima della spedizione.", shippingBody: "La spedizione dipende da peso, dimensioni, destinazione, restrizioni, dogana e servizi. I calcoli sono stime: conferma il totale live.", beginnerBody: "Incolla un link supportato, conferma l’articolo, paga, attendi l’arrivo in magazzino, controlla l’ispezione e poi scegli una rotta internazionale.", open: "Apri pagina verificata", verify: "Verifica prezzo e disponibilità", footer: "Sito indipendente educativo e di scoperta gestito dal team FindSpreadsheet. Non è di proprietà, gestito o approvato da LoloBuy." },
  pt: { nav: ["Planilha", "Categorias", "Guias", "Guia QC", "Envio", "Avaliações", "Artigos SEO"], heroTitle: "A planilha LoloBuy, pesquisada — não reciclada.", heroLede: "Descoberta de produtos, listas QC e pesquisa de envio para Europa e América do Norte.", explore: "Explorar a planilha", beginner: "Ler o guia inicial", byline: "Guia independente da equipe FindSpreadsheet", source: "Fontes oficiais", checks: "Verificações independentes", updated: "Atualizado ago. 2026", researchNote: "Verificamos links, separamos processos confirmados de estimativas e sinalizamos dados que podem mudar no checkout.", categoryTitle: "Achados LoloBuy populares", browse: "Ver 10 categorias", spreadsheetTitle: "Índice de produtos com pesquisa", spreadsheetIntro: "Abra uma categoria ou produto verificado no FindSpreadsheet e confira o link do vendedor, detalhes visíveis e dados ao vivo antes de comprar.", guidesTitle: "Guias de compra LoloBuy", guidesIntro: "Guias curtos e baseados em fontes entre encontrar um produto e enviar o pacote internacional.", reviewTitle: "Avaliação LoloBuy: o que é verificável", reviewIntro: "Separamos o fluxo público de preços, promoções, rotas e experiências variáveis. Sem notas inventadas.", seoTitle: "Artigos de pesquisa", seoIntro: "Artigos longos em inglês baseados em dúvidas reais, fontes oficiais e data de verificação.", faqTitle: "Perguntas frequentes sobre LoloBuy", faqIntro: "Respostas curtas com detalhes variáveis claramente marcados.", qcBody: "Fotos QC ajudam a revisar cor, formato, logos, costura, medidas e danos visíveis. Não provam material, durabilidade, autenticidade ou ajuste. Compare tudo antes do envio.", shippingBody: "O envio depende de peso, dimensões, destino, restrições, alfândega e serviços. Calculadoras são estimativas; confirme o total ao vivo.", beginnerBody: "Cole um link compatível, confirme o item, pague, aguarde o armazém, revise a inspeção disponível e só então escolha a rota internacional.", open: "Abrir página verificada", verify: "Verificar preço e disponibilidade", footer: "Site independente de educação e descoberta operado pela equipe FindSpreadsheet. Não pertence, não é operado nem endossado pela LoloBuy." },
  pl: { nav: ["Arkusz", "Kategorie", "Poradniki", "Kontrola QC", "Wysyłka", "Recenzje", "Artykuły SEO"], heroTitle: "Arkusz LoloBuy oparty na badaniach, nie na kopiowaniu.", heroLede: "Wyszukiwanie produktów, listy QC i informacje o wysyłce dla Europy i Ameryki Północnej.", explore: "Otwórz arkusz", beginner: "Przeczytaj poradnik", byline: "Niezależny poradnik zespołu FindSpreadsheet", source: "Oficjalne źródła", checks: "Niezależne kontrole", updated: "Aktualizacja: sierpień 2026", researchNote: "Sprawdzamy linki, oddzielamy potwierdzone procesy od szacunków i oznaczamy dane zmienne przy płatności.", categoryTitle: "Popularne znaleziska LoloBuy", browse: "Zobacz 10 kategorii", spreadsheetTitle: "Indeks produktów z warstwą badawczą", spreadsheetIntro: "Otwórz sprawdzoną kategorię lub produkt w FindSpreadsheet, a następnie zweryfikuj link sprzedawcy, widoczne szczegóły i dane na żywo.", guidesTitle: "Poradniki zakupowe LoloBuy", guidesIntro: "Krótkie, oparte na źródłach poradniki od znalezienia produktu po wysyłkę międzynarodową.", reviewTitle: "Recenzja LoloBuy: co można potwierdzić", reviewIntro: "Oddzielamy publiczny proces od zmiennych cen, promocji, tras i doświadczeń. Bez wymyślonych ocen.", seoTitle: "Artykuły badawcze", seoIntro: "Długie artykuły po angielsku o realnych pytaniach, z oficjalnymi źródłami i datą weryfikacji.", faqTitle: "Najczęstsze pytania o LoloBuy", faqIntro: "Krótkie odpowiedzi z wyraźnie oznaczonymi danymi zmiennymi.", qcBody: "Zdjęcia QC pomagają ocenić kolor, kształt, logo, szwy, wymiary i widoczne uszkodzenia. Nie potwierdzają materiału, trwałości, autentyczności ani dopasowania.", shippingBody: "Wysyłka zależy od wagi, wymiarów, kraju, ograniczeń, cła i usług dodatkowych. Kalkulator daje szacunek; potwierdź kwotę na żywo.", beginnerBody: "Wklej obsługiwany link, potwierdź dane, zapłać, poczekaj na magazyn, sprawdź inspekcję i dopiero potem wybierz trasę międzynarodową.", open: "Otwórz sprawdzoną stronę", verify: "Sprawdź cenę i dostępność", footer: "Niezależna strona edukacyjna i produktowa zespołu FindSpreadsheet. Nie należy do LoloBuy ani nie jest przez nią obsługiwana lub wspierana." },
  nl: { nav: ["Spreadsheet", "Categorieën", "Gidsen", "QC-gids", "Verzending", "Reviews", "SEO-artikelen"], heroTitle: "De LoloBuy-spreadsheet, onderzocht — niet hergebruikt.", heroLede: "Productvondsten, QC-controles en verzendonderzoek voor Europa en Noord-Amerika.", explore: "Bekijk de spreadsheet", beginner: "Lees de beginnersgids", byline: "Onafhankelijke gids van het FindSpreadsheet-team", source: "Officiële bronnen", checks: "Onafhankelijke controles", updated: "Bijgewerkt aug. 2026", researchNote: "We controleren links, scheiden bevestigde stappen van schattingen en markeren gegevens die bij afrekenen kunnen veranderen.", categoryTitle: "Populaire LoloBuy-vondsten", browse: "Bekijk 10 categorieën", spreadsheetTitle: "Een productindex met onderzoek", spreadsheetIntro: "Open een gecontroleerde categorie of productpagina op FindSpreadsheet en controleer daarna verkoperslink, zichtbare details en live gegevens.", guidesTitle: "LoloBuy-koopgidsen", guidesIntro: "Korte, brongebaseerde gidsen van productvondst tot internationaal pakket.", reviewTitle: "LoloBuy-review: wat is verifieerbaar", reviewIntro: "We scheiden de publieke workflow van wisselende prijzen, acties, routes en ervaringen. Geen verzonnen scores.", seoTitle: "Onderzoeksartikelen", seoIntro: "Lange Engelse artikelen rond echte vragen, officiële bronnen en controledatums.", faqTitle: "Veelgestelde vragen over LoloBuy", faqIntro: "Korte antwoorden met duidelijk gemarkeerde variabele details.", qcBody: "QC-foto’s helpen kleur, vorm, logo’s, stiksels, maten en zichtbare schade te beoordelen. Ze bewijzen geen materiaal, duurzaamheid, echtheid of pasvorm.", shippingBody: "Verzending hangt af van gewicht, afmetingen, bestemming, beperkingen, douane en diensten. Een calculator is een schatting; bevestig het live totaal.", beginnerBody: "Plak een ondersteunde link, controleer het artikel, betaal, wacht op het magazijn, bekijk de inspectie en kies daarna pas een internationale route.", open: "Gecontroleerde pagina openen", verify: "Live prijs en voorraad controleren", footer: "Onafhankelijke educatieve en productzoeksite van het FindSpreadsheet-team. Niet eigendom van, beheerd of ondersteund door LoloBuy." },
  sv: { nav: ["Kalkylblad", "Kategorier", "Guider", "QC-guide", "Frakt", "Recensioner", "SEO-artiklar"], heroTitle: "LoloBuy-kalkylbladet, undersökt — inte återanvänt.", heroLede: "Produktupptäckt, QC-listor och fraktforskning för Europa och Nordamerika.", explore: "Utforska kalkylbladet", beginner: "Läs nybörjarguiden", byline: "Oberoende guide av FindSpreadsheet-teamet", source: "Officiella källor", checks: "Oberoende kontroller", updated: "Uppdaterad aug 2026", researchNote: "Vi verifierar länkar, skiljer bekräftade processer från uppskattningar och markerar uppgifter som kan ändras i kassan.", categoryTitle: "Populära LoloBuy-fynd", browse: "Visa 10 kategorier", spreadsheetTitle: "Produktindex med forskning", spreadsheetIntro: "Öppna en verifierad kategori eller produktsida på FindSpreadsheet och kontrollera säljarens länk, synliga detaljer och liveuppgifter.", guidesTitle: "LoloBuy-köpguider", guidesIntro: "Korta, källbaserade guider från produktfynd till internationellt paket.", reviewTitle: "LoloBuy-recension: vad kan verifieras", reviewIntro: "Vi skiljer det offentliga flödet från varierande priser, kampanjer, rutter och upplevelser. Inga påhittade betyg.", seoTitle: "Forskningsartiklar", seoIntro: "Långa engelska artiklar om riktiga frågor, officiella källor och verifieringsdatum.", faqTitle: "Vanliga frågor om LoloBuy", faqIntro: "Korta svar där varierande detaljer är tydligt markerade.", qcBody: "QC-foton hjälper dig granska färg, form, logotyper, sömmar, mått och synliga skador. De bevisar inte material, hållbarhet, äkthet eller passform.", shippingBody: "Frakt beror på vikt, mått, destination, begränsningar, tull och tjänster. Kalkylatorer är uppskattningar; bekräfta totalsumman live.", beginnerBody: "Klistra in en stödd länk, bekräfta varan, betala, vänta på lagret, granska inspektionen och välj sedan internationell rutt.", open: "Öppna verifierad sida", verify: "Verifiera pris och lager", footer: "Oberoende informations- och produktsajt som drivs av FindSpreadsheet-teamet. Ägs, drivs eller stöds inte av LoloBuy." },
  da: { nav: ["Regneark", "Kategorier", "Guider", "QC-guide", "Forsendelse", "Anmeldelser", "SEO-artikler"], heroTitle: "LoloBuy-regnearket, undersøgt — ikke genbrugt.", heroLede: "Produktopdagelse, QC-tjeklister og forsendelsesresearch for Europa og Nordamerika.", explore: "Udforsk regnearket", beginner: "Læs begynderguiden", byline: "Uafhængig guide fra FindSpreadsheet-teamet", source: "Officielle kilder", checks: "Uafhængige kontroller", updated: "Opdateret aug. 2026", researchNote: "Vi kontrollerer links, skelner bekræftede processer fra estimater og markerer oplysninger, der kan ændre sig ved checkout.", categoryTitle: "Populære LoloBuy-fund", browse: "Se 10 kategorier", spreadsheetTitle: "Produktindeks med research", spreadsheetIntro: "Åbn en verificeret kategori eller produktside på FindSpreadsheet, og kontroller derefter sælgerlink, synlige detaljer og liveoplysninger.", guidesTitle: "LoloBuy-købsguider", guidesIntro: "Korte, kildebaserede guider fra produktfund til international pakke.", reviewTitle: "LoloBuy-anmeldelse: hvad kan verificeres", reviewIntro: "Vi skelner det offentlige flow fra skiftende priser, tilbud, ruter og erfaringer. Ingen opdigtede bedømmelser.", seoTitle: "Researchartikler", seoIntro: "Lange engelske artikler om virkelige spørgsmål, officielle kilder og kontroldato.", faqTitle: "Ofte stillede spørgsmål om LoloBuy", faqIntro: "Korte svar med tydeligt markerede variable detaljer.", qcBody: "QC-fotos hjælper med farve, form, logoer, syninger, mål og synlige skader. De beviser ikke materiale, holdbarhed, ægthed eller pasform.", shippingBody: "Forsendelse afhænger af vægt, mål, destination, restriktioner, told og tjenester. Beregninger er estimater; bekræft liveprisen.", beginnerBody: "Indsæt et understøttet link, bekræft varen, betal, vent på lageret, gennemgå inspektionen og vælg derefter international rute.", open: "Åbn verificeret side", verify: "Kontroller pris og lager", footer: "Uafhængigt informations- og produktwebsted drevet af FindSpreadsheet-teamet. Ikke ejet, drevet eller godkendt af LoloBuy." },
  no: { nav: ["Regneark", "Kategorier", "Guider", "QC-guide", "Frakt", "Anmeldelser", "SEO-artikler"], heroTitle: "LoloBuy-regnearket, undersøkt — ikke resirkulert.", heroLede: "Produktfunn, QC-sjekklister og fraktresearch for Europa og Nord-Amerika.", explore: "Utforsk regnearket", beginner: "Les nybegynnerguiden", byline: "Uavhengig guide fra FindSpreadsheet-teamet", source: "Offisielle kilder", checks: "Uavhengige kontroller", updated: "Oppdatert aug. 2026", researchNote: "Vi sjekker lenker, skiller bekreftede prosesser fra estimater og markerer opplysninger som kan endres i kassen.", categoryTitle: "Populære LoloBuy-funn", browse: "Se 10 kategorier", spreadsheetTitle: "Produktindeks med research", spreadsheetIntro: "Åpne en verifisert kategori eller produktside på FindSpreadsheet, og kontroller selgerlenke, synlige detaljer og liveinformasjon.", guidesTitle: "LoloBuy-kjøpsguider", guidesIntro: "Korte, kildebaserte guider fra produktfunn til internasjonal pakke.", reviewTitle: "LoloBuy-anmeldelse: hva kan bekreftes", reviewIntro: "Vi skiller offentlig arbeidsflyt fra variable priser, kampanjer, ruter og erfaringer. Ingen oppdiktede poeng.", seoTitle: "Researchartikler", seoIntro: "Lange engelske artikler om ekte spørsmål, offisielle kilder og kontrollert dato.", faqTitle: "Vanlige spørsmål om LoloBuy", faqIntro: "Korte svar med tydelig merkede variable detaljer.", qcBody: "QC-bilder hjelper med farge, form, logoer, sømmer, mål og synlige skader. De beviser ikke materiale, holdbarhet, ekthet eller passform.", shippingBody: "Frakt avhenger av vekt, mål, destinasjon, begrensninger, toll og tjenester. Kalkulatorer er estimater; bekreft totalsummen live.", beginnerBody: "Lim inn en støttet lenke, bekreft varen, betal, vent på lageret, gjennomgå inspeksjonen og velg så internasjonal rute.", open: "Åpne verifisert side", verify: "Sjekk pris og lager", footer: "Uavhengig informasjons- og produktfinnerside drevet av FindSpreadsheet-teamet. Ikke eid, drevet eller godkjent av LoloBuy." },
  fi: { nav: ["Taulukko", "Kategoriat", "Oppaat", "QC-opas", "Toimitus", "Arviot", "SEO-artikkelit"], heroTitle: "LoloBuy-taulukko, tutkittu — ei kierrätetty.", heroLede: "Tuotelöydöt, QC-tarkistuslistat ja toimitustutkimus Eurooppaan ja Pohjois-Amerikkaan.", explore: "Tutustu taulukkoon", beginner: "Lue aloittelijan opas", byline: "FindSpreadsheet-tiimin riippumaton opas", source: "Viralliset lähteet", checks: "Riippumattomat tarkistukset", updated: "Päivitetty 8/2026", researchNote: "Tarkistamme linkit, erotamme vahvistetut vaiheet arvioista ja merkitsemme kassalla muuttuvat tiedot.", categoryTitle: "Suositut LoloBuy-löydöt", browse: "Katso 10 kategoriaa", spreadsheetTitle: "Tuotehakemisto tutkimuskerroksella", spreadsheetIntro: "Avaa tarkistettu kategoria tai tuotesivu FindSpreadsheetissä ja varmista myyjän linkki, näkyvät tiedot ja ajantasainen checkout.", guidesTitle: "LoloBuy-osto-oppaat", guidesIntro: "Lyhyet lähteisiin perustuvat oppaat tuotelöydöstä kansainväliseen pakettiin.", reviewTitle: "LoloBuy-arvio: mitä voidaan varmistaa", reviewIntro: "Erotamme julkisen prosessin muuttuvista hinnoista, kampanjoista, reiteistä ja kokemuksista. Ei keksittyjä pisteitä.", seoTitle: "Tutkimusartikkelit", seoIntro: "Pitkät englanninkieliset artikkelit todellisista kysymyksistä, virallisista lähteistä ja tarkistuspäivistä.", faqTitle: "Usein kysyttyä LoloBuysta", faqIntro: "Lyhyet vastaukset, joissa muuttuvat tiedot on merkitty selvästi.", qcBody: "QC-kuvat auttavat tarkistamaan värin, muodon, logot, ompeleet, mitat ja näkyvät vauriot. Ne eivät todista materiaalia, kestävyyttä, aitoutta tai istuvuutta.", shippingBody: "Toimitus riippuu painosta, mitoista, kohteesta, rajoituksista, tullista ja palveluista. Laskurit ovat arvioita; varmista loppusumma.", beginnerBody: "Liitä tuettu linkki, vahvista tuote, maksa, odota varastoa, tarkista tarkastustiedot ja valitse vasta sitten kansainvälinen reitti.", open: "Avaa tarkistettu sivu", verify: "Tarkista hinta ja saatavuus", footer: "FindSpreadsheet-tiimin riippumaton tieto- ja tuotehakusivusto. Ei LoloBuyn omistama, ylläpitämä tai tukema." },
  cs: { nav: ["Tabulka", "Kategorie", "Průvodci", "QC průvodce", "Doprava", "Recenze", "SEO články"], heroTitle: "Tabulka LoloBuy, ověřená — ne recyklovaná.", heroLede: "Vyhledávání produktů, QC seznamy a informace o dopravě pro Evropu a Severní Ameriku.", explore: "Prozkoumat tabulku", beginner: "Číst průvodce", byline: "Nezávislý průvodce týmu FindSpreadsheet", source: "Oficiální zdroje", checks: "Nezávislé kontroly", updated: "Aktualizováno 8/2026", researchNote: "Ověřujeme odkazy, oddělujeme potvrzené postupy od odhadů a označujeme údaje, které se mohou změnit při platbě.", categoryTitle: "Oblíbené nálezy LoloBuy", browse: "Zobrazit 10 kategorií", spreadsheetTitle: "Produktový index s výzkumem", spreadsheetIntro: "Otevřete ověřenou kategorii nebo produkt na FindSpreadsheet a zkontrolujte odkaz prodejce, viditelné detaily a živé údaje.", guidesTitle: "Nákupní průvodci LoloBuy", guidesIntro: "Krátké průvodce založené na zdrojích od nalezení produktu po mezinárodní zásilku.", reviewTitle: "Recenze LoloBuy: co lze ověřit", reviewIntro: "Oddělujeme veřejný proces od proměnlivých cen, akcí, tras a zkušeností. Žádná vymyšlená hodnocení.", seoTitle: "Výzkumné články", seoIntro: "Dlouhé anglické články o skutečných otázkách, oficiálních zdrojích a datu ověření.", faqTitle: "Časté otázky o LoloBuy", faqIntro: "Stručné odpovědi s jasně označenými proměnlivými údaji.", qcBody: "QC fotografie pomáhají zkontrolovat barvu, tvar, loga, šití, rozměry a viditelné vady. Nedokazují materiál, životnost, pravost ani velikost.", shippingBody: "Doprava závisí na hmotnosti, rozměrech, cíli, omezeních, clu a službách. Kalkulace jsou odhady; potvrďte živou cenu.", beginnerBody: "Vložte podporovaný odkaz, potvrďte produkt, zaplaťte, počkejte na sklad, zkontrolujte inspekci a poté vyberte mezinárodní trasu.", open: "Otevřít ověřenou stránku", verify: "Ověřit cenu a dostupnost", footer: "Nezávislý vzdělávací a produktový web týmu FindSpreadsheet. Není vlastněn, provozován ani podporován LoloBuy." },
  ro: { nav: ["Foaie", "Categorii", "Ghiduri", "Ghid QC", "Livrare", "Recenzii", "Articole SEO"], heroTitle: "Foaia LoloBuy, cercetată — nu reciclată.", heroLede: "Descoperire de produse, liste QC și cercetare de livrare pentru Europa și America de Nord.", explore: "Explorează foaia", beginner: "Citește ghidul", byline: "Ghid independent al echipei FindSpreadsheet", source: "Surse oficiale", checks: "Verificări independente", updated: "Actualizat aug. 2026", researchNote: "Verificăm linkurile, separăm procesele confirmate de estimări și marcăm datele care se pot schimba la plată.", categoryTitle: "Descoperiri LoloBuy populare", browse: "Vezi 10 categorii", spreadsheetTitle: "Index de produse cu cercetare", spreadsheetIntro: "Deschide o categorie sau un produs verificat pe FindSpreadsheet, apoi controlează linkul vânzătorului, detaliile vizibile și datele live.", guidesTitle: "Ghiduri de cumpărare LoloBuy", guidesIntro: "Ghiduri scurte bazate pe surse, de la produs la coletul internațional.", reviewTitle: "Recenzie LoloBuy: ce poate fi verificat", reviewIntro: "Separăm fluxul public de prețuri, promoții, rute și experiențe variabile. Fără scoruri inventate.", seoTitle: "Articole de cercetare", seoIntro: "Articole lungi în engleză bazate pe întrebări reale, surse oficiale și data verificării.", faqTitle: "Întrebări frecvente LoloBuy", faqIntro: "Răspunsuri scurte cu detaliile variabile marcate clar.", qcBody: "Fotografiile QC ajută la verificarea culorii, formei, logo-urilor, cusăturilor, măsurilor și defectelor vizibile. Nu dovedesc materialul, durabilitatea, autenticitatea sau potrivirea.", shippingBody: "Livrarea depinde de greutate, dimensiuni, destinație, restricții, vamă și servicii. Calculatoarele oferă estimări; confirmă totalul live.", beginnerBody: "Lipește un link acceptat, confirmă produsul, plătește, așteaptă depozitul, verifică inspecția și apoi alege ruta internațională.", open: "Deschide pagina verificată", verify: "Verifică prețul și stocul", footer: "Site independent de educație și descoperire operat de echipa FindSpreadsheet. Nu este deținut, operat sau susținut de LoloBuy." },
  hu: { nav: ["Táblázat", "Kategóriák", "Útmutatók", "QC útmutató", "Szállítás", "Vélemények", "SEO cikkek"], heroTitle: "A LoloBuy táblázat: kutatott, nem újrahasznosított.", heroLede: "Termékkeresés, QC ellenőrzőlisták és szállítási kutatás Európának és Észak-Amerikának.", explore: "Táblázat megnyitása", beginner: "Kezdő útmutató", byline: "A FindSpreadsheet csapat független útmutatója", source: "Hivatalos források", checks: "Független ellenőrzések", updated: "Frissítve: 2026. aug.", researchNote: "Ellenőrizzük a linkeket, elválasztjuk a megerősített lépéseket a becslésektől, és jelöljük a fizetéskor változó adatokat.", categoryTitle: "Népszerű LoloBuy találatok", browse: "10 kategória", spreadsheetTitle: "Termékindex kutatási réteggel", spreadsheetIntro: "Nyiss meg egy ellenőrzött kategóriát vagy terméket a FindSpreadsheeten, majd ellenőrizd az eladó linkjét, a látható részleteket és az élő adatokat.", guidesTitle: "LoloBuy vásárlási útmutatók", guidesIntro: "Rövid, forrásalapú útmutatók a terméktalálattól a nemzetközi csomagig.", reviewTitle: "LoloBuy vélemény: mi ellenőrizhető", reviewIntro: "A nyilvános folyamatot elkülönítjük a változó áraktól, akcióktól, útvonalaktól és tapasztalatoktól. Nincs kitalált pontszám.", seoTitle: "Kutatási cikkek", seoIntro: "Hosszú angol cikkek valós kérdésekről, hivatalos forrásokkal és ellenőrzési dátummal.", faqTitle: "Gyakori LoloBuy kérdések", faqIntro: "Rövid válaszok, jól jelölt változó részletekkel.", qcBody: "A QC-fotók segítenek ellenőrizni a színt, formát, logókat, varrást, méreteket és látható hibákat. Nem igazolják az anyagot, tartósságot, eredetiséget vagy illeszkedést.", shippingBody: "A szállítás függ a súlytól, mérettől, céltól, korlátozásoktól, vámtól és szolgáltatásoktól. A kalkulátor becslés; erősítsd meg az élő összeget.", beginnerBody: "Illessz be egy támogatott linket, erősítsd meg a terméket, fizess, várd meg a raktárt, nézd át az ellenőrzést, majd válassz nemzetközi útvonalat.", open: "Ellenőrzött oldal megnyitása", verify: "Ár és készlet ellenőrzése", footer: "A FindSpreadsheet csapat független oktatási és termékkereső oldala. Nem a LoloBuy tulajdona, nem az üzemelteti vagy támogatja." },
  el: { nav: ["Φύλλο", "Κατηγορίες", "Οδηγοί", "Οδηγός QC", "Αποστολή", "Κριτικές", "Άρθρα SEO"], heroTitle: "Το φύλλο LoloBuy, ερευνημένο — όχι ανακυκλωμένο.", heroLede: "Ανακάλυψη προϊόντων, λίστες QC και έρευνα αποστολής για Ευρώπη και Βόρεια Αμερική.", explore: "Άνοιγμα φύλλου", beginner: "Οδηγός αρχαρίων", byline: "Ανεξάρτητος οδηγός της ομάδας FindSpreadsheet", source: "Επίσημες πηγές", checks: "Ανεξάρτητοι έλεγχοι", updated: "Ενημέρωση Αύγ. 2026", researchNote: "Ελέγχουμε τους συνδέσμους, ξεχωρίζουμε τις επιβεβαιωμένες διαδικασίες από εκτιμήσεις και σημειώνουμε όσα αλλάζουν στο checkout.", categoryTitle: "Δημοφιλή ευρήματα LoloBuy", browse: "10 κατηγορίες", spreadsheetTitle: "Κατάλογος προϊόντων με έρευνα", spreadsheetIntro: "Ανοίξτε επαληθευμένη κατηγορία ή προϊόν στο FindSpreadsheet και ελέγξτε τον σύνδεσμο πωλητή, τις ορατές λεπτομέρειες και τα ζωντανά στοιχεία.", guidesTitle: "Οδηγοί αγορών LoloBuy", guidesIntro: "Σύντομοι οδηγοί με πηγές, από την εύρεση έως το διεθνές δέμα.", reviewTitle: "Κριτική LoloBuy: τι επαληθεύεται", reviewIntro: "Ξεχωρίζουμε τη δημόσια ροή από μεταβλητές τιμές, προσφορές, διαδρομές και εμπειρίες. Χωρίς επινοημένες βαθμολογίες.", seoTitle: "Ερευνητικά άρθρα", seoIntro: "Εκτενή αγγλικά άρθρα με πραγματικές ερωτήσεις, επίσημες πηγές και ημερομηνία ελέγχου.", faqTitle: "Συχνές ερωτήσεις LoloBuy", faqIntro: "Σύντομες απαντήσεις με σαφή σήμανση μεταβλητών στοιχείων.", qcBody: "Οι φωτογραφίες QC βοηθούν στον έλεγχο χρώματος, σχήματος, λογοτύπων, ραφών, μετρήσεων και ορατών ζημιών. Δεν αποδεικνύουν υλικό, αντοχή, γνησιότητα ή εφαρμογή.", shippingBody: "Η αποστολή εξαρτάται από βάρος, διαστάσεις, προορισμό, περιορισμούς, τελωνείο και υπηρεσίες. Οι υπολογισμοί είναι εκτιμήσεις· επιβεβαιώστε το ζωντανό σύνολο.", beginnerBody: "Επικολλήστε υποστηριζόμενο σύνδεσμο, επιβεβαιώστε το προϊόν, πληρώστε, περιμένετε την αποθήκη, ελέγξτε την επιθεώρηση και μετά επιλέξτε διεθνή διαδρομή.", open: "Άνοιγμα επαληθευμένης σελίδας", verify: "Έλεγχος τιμής και διαθεσιμότητας", footer: "Ανεξάρτητος εκπαιδευτικός ιστότοπος της ομάδας FindSpreadsheet. Δεν ανήκει, δεν λειτουργεί και δεν υποστηρίζεται από τη LoloBuy." },
  uk: { nav: ["Таблиця", "Категорії", "Посібники", "QC-посібник", "Доставка", "Огляди", "SEO-статті"], heroTitle: "Таблиця LoloBuy: досліджена, а не скопійована.", heroLede: "Пошук товарів, QC-списки та дослідження доставки для Європи й Північної Америки.", explore: "Відкрити таблицю", beginner: "Посібник для новачків", byline: "Незалежний посібник команди FindSpreadsheet", source: "Офіційні джерела", checks: "Незалежні перевірки", updated: "Оновлено: серпень 2026", researchNote: "Ми перевіряємо посилання, відокремлюємо підтверджені процеси від оцінок і позначаємо дані, що можуть змінитися під час оплати.", categoryTitle: "Популярні знахідки LoloBuy", browse: "10 категорій", spreadsheetTitle: "Індекс товарів із дослідженням", spreadsheetIntro: "Відкрийте перевірену категорію або товар на FindSpreadsheet, потім перевірте посилання продавця, видимі деталі й дані наживо.", guidesTitle: "Посібники покупця LoloBuy", guidesIntro: "Короткі посібники з джерелами — від пошуку товару до міжнародної посилки.", reviewTitle: "Огляд LoloBuy: що можна перевірити", reviewIntro: "Ми відокремлюємо публічний процес від змінних цін, акцій, маршрутів і досвіду. Без вигаданих оцінок.", seoTitle: "Дослідницькі статті", seoIntro: "Розгорнуті англомовні статті про реальні питання, з офіційними джерелами й датою перевірки.", faqTitle: "Поширені запитання про LoloBuy", faqIntro: "Короткі відповіді з чітко позначеними змінними даними.", qcBody: "QC-фото допомагають перевірити колір, форму, логотипи, шви, розміри та видимі пошкодження. Вони не доводять матеріал, довговічність, автентичність або посадку.", shippingBody: "Доставка залежить від ваги, розмірів, країни, обмежень, митниці та послуг. Калькулятор дає оцінку; підтвердьте суму наживо.", beginnerBody: "Вставте підтримуване посилання, підтвердьте товар, сплатіть, дочекайтеся складу, перегляньте інспекцію та лише тоді оберіть міжнародний маршрут.", open: "Відкрити перевірену сторінку", verify: "Перевірити ціну й наявність", footer: "Незалежний освітній і пошуковий сайт команди FindSpreadsheet. Не належить LoloBuy, не керується й не схвалюється нею." },
  tr: { nav: ["Tablo", "Kategoriler", "Rehberler", "QC Rehberi", "Kargo", "İncelemeler", "SEO Yazıları"], heroTitle: "LoloBuy tablosu: araştırılmış, kopyalanmamış.", heroLede: "Avrupa ve Kuzey Amerika için ürün keşfi, QC listeleri ve kargo araştırması.", explore: "Tabloyu keşfet", beginner: "Başlangıç rehberi", byline: "FindSpreadsheet ekibinden bağımsız rehber", source: "Resmî kaynaklar", checks: "Bağımsız kontroller", updated: "Ağustos 2026 güncellemesi", researchNote: "Bağlantıları doğrular, onaylanmış süreci tahminlerden ayırır ve ödeme sırasında değişebilecek bilgileri işaretleriz.", categoryTitle: "Popüler LoloBuy buluntuları", browse: "10 kategori", spreadsheetTitle: "Araştırma katmanlı ürün dizini", spreadsheetIntro: "FindSpreadsheet’de doğrulanmış kategori veya ürün sayfasını açın; satıcı bağlantısını, görünür ayrıntıları ve canlı bilgileri kontrol edin.", guidesTitle: "LoloBuy alışveriş rehberleri", guidesIntro: "Ürün bulmaktan uluslararası pakete kadar kısa, kaynaklı rehberler.", reviewTitle: "LoloBuy incelemesi: ne doğrulanabilir", reviewIntro: "Kamuya açık iş akışını değişken fiyat, promosyon, rota ve deneyimlerden ayırırız. Uydurma puan yok.", seoTitle: "Araştırma yazıları", seoIntro: "Gerçek sorulara, resmî kaynaklara ve doğrulama tarihine dayalı uzun İngilizce yazılar.", faqTitle: "LoloBuy sık sorulan sorular", faqIntro: "Değişken ayrıntıların açıkça belirtildiği kısa yanıtlar.", qcBody: "QC fotoğrafları renk, biçim, logo, dikiş, ölçü ve görünür hasarı kontrol etmeye yardımcı olur. Malzeme, dayanıklılık, özgünlük veya kalıbı kanıtlamaz.", shippingBody: "Kargo; ağırlık, ölçü, hedef, kısıtlamalar, gümrük ve hizmetlere bağlıdır. Hesaplayıcı tahmindir; canlı toplamı doğrulayın.", beginnerBody: "Desteklenen bağlantıyı yapıştırın, ürünü doğrulayın, ödeyin, depoya gelişi bekleyin, incelemeyi kontrol edin ve sonra uluslararası rota seçin.", open: "Doğrulanmış sayfayı aç", verify: "Fiyatı ve stok durumunu doğrula", footer: "FindSpreadsheet ekibi tarafından işletilen bağımsız eğitim ve ürün keşif sitesi. LoloBuy’a ait değildir; LoloBuy tarafından işletilmez veya desteklenmez." },
  ru: { nav: ["Таблица", "Категории", "Гайды", "QC-гайд", "Доставка", "Обзоры", "SEO-статьи"], heroTitle: "Таблица LoloBuy: исследовано, а не скопировано.", heroLede: "Поиск товаров, QC-списки и анализ доставки для Европы и Северной Америки.", explore: "Открыть таблицу", beginner: "Гайд для новичков", byline: "Независимый гайд команды FindSpreadsheet", source: "Официальные источники", checks: "Независимые проверки", updated: "Обновлено в августе 2026", researchNote: "Мы проверяем ссылки, отделяем подтвержденный процесс от оценок и отмечаем данные, которые меняются при оплате.", categoryTitle: "Популярные находки LoloBuy", browse: "10 категорий", spreadsheetTitle: "Индекс товаров с исследовательским слоем", spreadsheetIntro: "Откройте проверенную категорию или товар на FindSpreadsheet, затем проверьте ссылку продавца, видимые детали и живые данные.", guidesTitle: "Гайды покупателя LoloBuy", guidesIntro: "Короткие гайды с источниками — от поиска товара до международной посылки.", reviewTitle: "Обзор LoloBuy: что можно проверить", reviewIntro: "Мы отделяем публичный процесс от переменных цен, акций, маршрутов и опыта. Без выдуманных оценок.", seoTitle: "Исследовательские статьи", seoIntro: "Подробные англоязычные статьи по реальным вопросам с официальными источниками и датой проверки.", faqTitle: "Частые вопросы о LoloBuy", faqIntro: "Краткие ответы с явной пометкой переменных данных.", qcBody: "QC-фото помогают проверить цвет, форму, логотипы, швы, размеры и видимые повреждения. Они не подтверждают материал, долговечность, подлинность или посадку.", shippingBody: "Доставка зависит от веса, размеров, страны, ограничений, таможни и услуг. Калькулятор дает оценку; подтвердите сумму в реальном времени.", beginnerBody: "Вставьте поддерживаемую ссылку, подтвердите товар, оплатите, дождитесь склада, изучите инспекцию и только затем выберите международный маршрут.", open: "Открыть проверенную страницу", verify: "Проверить цену и наличие", footer: "Независимый образовательный и поисковый сайт команды FindSpreadsheet. Не принадлежит LoloBuy, не управляется и не поддерживается ею." },
  bg: { nav: ["Таблица", "Категории", "Ръководства", "QC ръководство", "Доставка", "Отзиви", "SEO статии"], heroTitle: "Таблицата LoloBuy: проучена, не копирана.", heroLede: "Откриване на продукти, QC списъци и проучване на доставката за Европа и Северна Америка.", explore: "Отвори таблицата", beginner: "Ръководство за начинаещи", byline: "Независимо ръководство на екипа FindSpreadsheet", source: "Официални източници", checks: "Независими проверки", updated: "Обновено авг. 2026", researchNote: "Проверяваме връзките, отделяме потвърдения процес от прогнозите и отбелязваме данните, които може да се променят при плащане.", categoryTitle: "Популярни находки LoloBuy", browse: "10 категории", spreadsheetTitle: "Продуктов индекс с проучване", spreadsheetIntro: "Отворете проверена категория или продукт във FindSpreadsheet и прегледайте връзката на продавача, видимите детайли и данните на живо.", guidesTitle: "Ръководства за LoloBuy", guidesIntro: "Кратки ръководства с източници — от продукта до международната пратка.", reviewTitle: "Отзив за LoloBuy: какво се потвърждава", reviewIntro: "Отделяме публичния процес от променливи цени, промоции, маршрути и опит. Без измислени оценки.", seoTitle: "Проучвателни статии", seoIntro: "Дълги английски статии по реални въпроси с официални източници и дата на проверка.", faqTitle: "Чести въпроси за LoloBuy", faqIntro: "Кратки отговори с ясно отбелязани променливи подробности.", qcBody: "QC снимките помагат за проверка на цвят, форма, лога, шевове, размери и видими повреди. Не доказват материал, издръжливост, автентичност или прилягане.", shippingBody: "Доставката зависи от тегло, размери, държава, ограничения, митници и услуги. Калкулаторите са ориентировъчни; потвърдете живата сума.", beginnerBody: "Поставете поддържана връзка, потвърдете продукта, платете, изчакайте склада, прегледайте инспекцията и после изберете международен маршрут.", open: "Отвори проверената страница", verify: "Провери цена и наличност", footer: "Независим образователен и продуктов сайт на екипа FindSpreadsheet. Не е собственост, управляван или подкрепян от LoloBuy." },
  ja: { nav: ["スプレッドシート", "カテゴリー", "ガイド", "QCガイド", "配送", "レビュー", "SEO記事"], heroTitle: "LoloBuyスプレッドシート。転載ではなく、調査済み。", heroLede: "欧州・北米向けの商品検索、QCチェック、配送調査。", explore: "シートを見る", beginner: "初心者ガイド", byline: "FindSpreadsheetチームによる独立ガイド", source: "公式情報源", checks: "独立確認", updated: "2026年8月更新", researchNote: "リンクを確認し、公式に確認できる流れと推定を分け、決済時に変わる情報を明記します。", categoryTitle: "人気のLoloBuy商品", browse: "10カテゴリーを見る", spreadsheetTitle: "調査情報付きの商品インデックス", spreadsheetIntro: "FindSpreadsheetの確認済みカテゴリーまたは商品ページを開き、出品者リンク、見える詳細、最新の決済情報を注文前に確認してください。", guidesTitle: "LoloBuy購入ガイド", guidesIntro: "商品を見つけてから国際配送を申し込むまでを、情報源に基づいて短く解説します。", reviewTitle: "LoloBuyレビュー：確認できること", reviewIntro: "公開された手順と、変動する価格・キャンペーン・配送ルート・個人の体験を分けます。根拠のない点数は使いません。", seoTitle: "調査記事", seoIntro: "実際の購入者の疑問、公式情報、確認日に基づく長文英語記事。", faqTitle: "LoloBuy よくある質問", faqIntro: "変動する項目を明示した簡潔な回答です。", qcBody: "QC写真では色、形、ロゴ、縫製、寸法、目立つ損傷を確認できます。ただし素材、耐久性、真贋、フィット感を証明するものではありません。発送前に販売ページと比較してください。", shippingBody: "国際送料は重量、サイズ、配送先、ルート制限、税関、追加サービスで変わります。計算結果は目安として、提出前にアカウント上の金額を確認してください。", beginnerBody: "対応する商品リンクを貼り、内容を確認して支払い、倉庫到着を待ち、検品情報を確認してから国際配送ルートを選びます。", open: "確認済みページを開く", verify: "価格と在庫を確認", footer: "FindSpreadsheetチームが運営する独立した教育・商品検索サイトです。LoloBuyの所有・運営・承認によるものではありません。" },
  ko: { nav: ["스프레드시트", "카테고리", "가이드", "QC 가이드", "배송", "리뷰", "SEO 글"], heroTitle: "LoloBuy 스프레드시트, 복사가 아닌 조사.", heroLede: "유럽과 북미 구매자를 위한 상품 탐색, QC 체크리스트, 배송 조사.", explore: "스프레드시트 보기", beginner: "초보자 가이드", byline: "FindSpreadsheet 팀의 독립 가이드", source: "공식 출처", checks: "독립 확인", updated: "2026년 8월 업데이트", researchNote: "링크를 확인하고, 공식적으로 확인된 절차와 추정치를 구분하며, 결제 시 달라질 수 있는 정보를 표시합니다.", categoryTitle: "인기 LoloBuy 상품", browse: "10개 카테고리", spreadsheetTitle: "조사 정보가 더해진 상품 인덱스", spreadsheetIntro: "FindSpreadsheet의 확인된 카테고리나 상품 페이지를 열고 판매자 링크, 보이는 세부 정보, 실시간 결제 정보를 주문 전에 확인하세요.", guidesTitle: "LoloBuy 구매 가이드", guidesIntro: "상품을 찾은 뒤 국제 소포를 제출하기까지의 과정을 출처에 기반해 짧게 설명합니다.", reviewTitle: "LoloBuy 리뷰: 확인 가능한 내용", reviewIntro: "공개 절차와 변동 가격, 프로모션, 배송 경로, 개인 경험을 구분합니다. 근거 없는 점수는 사용하지 않습니다.", seoTitle: "조사 글", seoIntro: "실제 구매자 질문, 공식 출처, 확인 날짜를 바탕으로 한 장문 영어 글입니다.", faqTitle: "LoloBuy 자주 묻는 질문", faqIntro: "변동 가능 정보를 명확히 표시한 간결한 답변입니다.", qcBody: "QC 사진은 색상, 형태, 로고, 봉제, 치수, 눈에 보이는 손상을 확인하는 데 도움이 됩니다. 소재, 내구성, 진위, 핏을 증명하지는 않습니다. 배송 전 판매 페이지와 비교하세요.", shippingBody: "국제 배송은 무게, 부피, 목적지, 경로 제한, 세관, 선택 서비스에 따라 달라집니다. 계산값은 추정치이므로 제출 전 실시간 총액을 확인하세요.", beginnerBody: "지원되는 상품 링크를 붙여 넣고, 상품 정보를 확인하고 결제한 뒤 창고 도착과 검사 정보를 확인한 다음 국제 배송 경로를 선택합니다.", open: "확인된 페이지 열기", verify: "가격과 재고 확인", footer: "FindSpreadsheet 팀이 운영하는 독립 교육·상품 탐색 사이트입니다. LoloBuy가 소유, 운영 또는 보증하지 않습니다." },
  ar: { nav: ["الجدول", "الفئات", "الأدلة", "دليل الجودة", "الشحن", "المراجعات", "مقالات SEO"], heroTitle: "جدول LoloBuy مبني على البحث، لا على النسخ.", heroLede: "اكتشاف المنتجات وقوائم فحص الجودة وبحث الشحن لأوروبا وأمريكا الشمالية.", explore: "استكشف الجدول", beginner: "اقرأ دليل المبتدئ", byline: "دليل مستقل من فريق FindSpreadsheet", source: "مصادر رسمية", checks: "فحوص مستقلة", updated: "محدّث أغسطس 2026", researchNote: "نتحقق من الروابط ونفصل الإجراءات المؤكدة عن التقديرات ونوضح المعلومات التي قد تتغير عند الدفع.", categoryTitle: "اكتشافات LoloBuy الشائعة", browse: "عرض 10 فئات", spreadsheetTitle: "فهرس منتجات مع طبقة بحث", spreadsheetIntro: "افتح فئة أو صفحة منتج موثقة على FindSpreadsheet ثم تحقق من رابط البائع والتفاصيل الظاهرة والمعلومات المباشرة قبل الطلب.", guidesTitle: "أدلة الشراء عبر LoloBuy", guidesIntro: "أدلة قصيرة تستند إلى مصادر من العثور على المنتج حتى إرسال الطرد الدولي.", reviewTitle: "مراجعة LoloBuy: ما الذي يمكن التحقق منه", reviewIntro: "نفصل مسار العمل العام عن الأسعار والعروض والمسارات والتجارب المتغيرة. لا تقييمات مختلقة.", seoTitle: "مقالات البحث", seoIntro: "مقالات إنجليزية مطولة تستند إلى أسئلة حقيقية ومصادر رسمية وتاريخ تحقق.", faqTitle: "الأسئلة الشائعة عن LoloBuy", faqIntro: "إجابات مختصرة مع توضيح التفاصيل المتغيرة.", qcBody: "تساعد صور QC في مراجعة اللون والشكل والشعارات والخياطة والقياسات والتلف الظاهر. لكنها لا تثبت الخامة أو المتانة أو الأصالة أو المقاس. قارن التفاصيل قبل الشحن.", shippingBody: "يعتمد الشحن الدولي على الوزن والأبعاد والوجهة والقيود والجمارك والخدمات. نتائج الحاسبة تقديرية؛ أكد المبلغ المباشر قبل الإرسال.", beginnerBody: "الصق رابط منتج مدعومًا، تحقق من التفاصيل، ادفع، انتظر وصوله إلى المستودع، راجع معلومات الفحص ثم اختر مسار الشحن الدولي.", open: "فتح الصفحة الموثقة", verify: "تحقق من السعر والتوفر", footer: "موقع مستقل للتعليم واكتشاف المنتجات يديره فريق FindSpreadsheet. ليس مملوكًا أو مُدارًا أو معتمدًا من LoloBuy." },
  zh: { nav: ["商品表", "分类", "指南", "质检指南", "运输", "评测", "SEO文章"], heroTitle: "LoloBuy 商品表：以调研为基础，不做简单搬运。", heroLede: "面向欧洲和北美买家的商品发现、质检清单与运输调研。", explore: "查看商品表", beginner: "阅读新手指南", byline: "FindSpreadsheet 团队运营的独立指南", source: "官方来源", checks: "独立核验", updated: "更新于2026年8月", researchNote: "我们核对目标链接，将已确认的平台流程与估算信息分开，并标明可能在结账时变化的内容。", categoryTitle: "热门 LoloBuy 商品发现", browse: "浏览10个分类", spreadsheetTitle: "增加调研层的商品索引", spreadsheetIntro: "先打开 FindSpreadsheet 上已核验的分类或商品页，下单前再检查原卖家链接、可见细节以及实时结账信息。", guidesTitle: "LoloBuy 买家指南", guidesIntro: "从发现商品到提交国际包裹，以公开来源为依据的简明指南。", reviewTitle: "LoloBuy 评测：哪些信息可以核实", reviewIntro: "我们将公开流程与会变化的价格、活动、路线和个人体验分开，不使用虚构评分。", seoTitle: "调研文章", seoIntro: "围绕真实买家问题、官方来源与核验日期撰写的英文长篇文章。", faqTitle: "LoloBuy 常见问题", faqIntro: "简明回答，并清楚标注会变化的细节。", qcBody: "质检照片可以帮助查看颜色、外形、标识、走线、尺寸和明显破损，但不能证明材质、耐用度、真伪或上身效果。国际发货前请逐项与卖家页面对照。", shippingBody: "国际运费会受包裹重量与体积、目的地、路线限制、海关和可选服务影响。计算器结果只作估算，提交包裹前请在账户中确认实时总价。", beginnerBody: "粘贴支持的商品链接，确认商品信息并付款，等待国内物流送达仓库，查看可用的质检信息，最后再选择国际运输路线。页面和条款可能变化，请逐步以实时页面为准。", open: "打开已核验页面", verify: "核对实时价格与库存", footer: "由 FindSpreadsheet 团队运营的独立资讯及商品发现网站；并非 LoloBuy 所有、运营或认可。" },
};

// Localized category names in the same order as `categories`.
export const categoryNames: Record<LocaleCode, string[]> = {
  en: ["Shoes", "Hoodies", "T-Shirts", "Jackets", "Pants / Shorts", "Headwear", "Accessories", "Jerseys", "Electronics", "Other Finds"],
  de: ["Schuhe", "Hoodies", "T-Shirts", "Jacken", "Hosen / Shorts", "Kopfbedeckung", "Accessoires", "Trikots", "Elektronik", "Weitere Funde"],
  fr: ["Chaussures", "Sweats", "T-shirts", "Vestes", "Pantalons / Shorts", "Couvre-chefs", "Accessoires", "Maillots", "Électronique", "Autres trouvailles"],
  es: ["Calzado", "Sudaderas", "Camisetas", "Chaquetas", "Pantalones / Shorts", "Gorras", "Accesorios", "Camisetas deportivas", "Electrónica", "Otros hallazgos"],
  it: ["Scarpe", "Felpe", "T-shirt", "Giacche", "Pantaloni / Shorts", "Copricapo", "Accessori", "Maglie", "Elettronica", "Altri prodotti"],
  pt: ["Calçados", "Moletons", "Camisetas", "Jaquetas", "Calças / Shorts", "Chapéus", "Acessórios", "Camisas", "Eletrônicos", "Outros achados"],
  pl: ["Buty", "Bluzy", "T-shirty", "Kurtki", "Spodnie / Szorty", "Nakrycia głowy", "Akcesoria", "Koszulki sportowe", "Elektronika", "Inne"],
  nl: ["Schoenen", "Hoodies", "T-shirts", "Jassen", "Broeken / Shorts", "Hoofddeksels", "Accessoires", "Shirts", "Elektronica", "Andere vondsten"],
  sv: ["Skor", "Huvtröjor", "T-shirts", "Jackor", "Byxor / Shorts", "Huvudbonader", "Accessoarer", "Matchtröjor", "Elektronik", "Övrigt"],
  da: ["Sko", "Hættetrøjer", "T-shirts", "Jakker", "Bukser / Shorts", "Hovedbeklædning", "Tilbehør", "Trøjer", "Elektronik", "Andet"],
  no: ["Sko", "Hettegensere", "T-skjorter", "Jakker", "Bukser / Shorts", "Hodeplagg", "Tilbehør", "Drakter", "Elektronikk", "Andre funn"],
  fi: ["Kengät", "Hupparit", "T-paidat", "Takit", "Housut / Shortsit", "Päähineet", "Asusteet", "Pelipaidat", "Elektroniikka", "Muut löydöt"],
  cs: ["Boty", "Mikiny", "Trička", "Bundy", "Kalhoty / Šortky", "Pokrývky hlavy", "Doplňky", "Dresy", "Elektronika", "Ostatní"],
  ro: ["Încălțăminte", "Hanorace", "Tricouri", "Jachete", "Pantaloni / Șorturi", "Articole cap", "Accesorii", "Tricouri sport", "Electronice", "Alte produse"],
  hu: ["Cipők", "Kapucnis felsők", "Pólók", "Kabátok", "Nadrágok / Rövidnadrágok", "Fejfedők", "Kiegészítők", "Mezek", "Elektronika", "Egyéb"],
  el: ["Παπούτσια", "Φούτερ", "Μπλουζάκια", "Μπουφάν", "Παντελόνια / Σορτς", "Καπέλα", "Αξεσουάρ", "Φανέλες", "Ηλεκτρονικά", "Άλλα"],
  uk: ["Взуття", "Худі", "Футболки", "Куртки", "Штани / Шорти", "Головні убори", "Аксесуари", "Джерсі", "Електроніка", "Інше"],
  tr: ["Ayakkabı", "Kapüşonlu", "Tişört", "Ceket", "Pantolon / Şort", "Şapka", "Aksesuar", "Forma", "Elektronik", "Diğer"],
  ru: ["Обувь", "Худи", "Футболки", "Куртки", "Брюки / Шорты", "Головные уборы", "Аксессуары", "Джерси", "Электроника", "Другое"],
  bg: ["Обувки", "Суитшърти", "Тениски", "Якета", "Панталони / Шорти", "Шапки", "Аксесоари", "Екипи", "Електроника", "Други"],
  ja: ["シューズ", "パーカー", "Tシャツ", "ジャケット", "パンツ / ショーツ", "帽子", "アクセサリー", "ユニフォーム", "電子機器", "その他"],
  ko: ["신발", "후디", "티셔츠", "재킷", "바지 / 반바지", "모자", "액세서리", "저지", "전자제품", "기타"],
  ar: ["أحذية", "هودي", "قمصان", "سترات", "بناطيل / شورت", "أغطية الرأس", "إكسسوارات", "قمصان رياضية", "إلكترونيات", "منتجات أخرى"],
  zh: ["鞋类", "连帽衫", "T恤", "夹克", "长裤 / 短裤", "帽类", "配饰", "球衣", "电子产品", "其他发现"],
};

export const faqQuestions: Record<LocaleCode, readonly string[]> = {
  en: ["How does LoloBuy work for beginners?", "What can LoloBuy QC photos confirm?", "How is international shipping calculated?", "How do I verify live prices and availability?", "Can multiple warehouse items be consolidated?", "How do I track a LoloBuy order and international parcel?", "What should I check before submitting an order?", "Can product prices and availability change?"],
  de: ["Wie funktioniert LoloBuy für Anfänger?", "Was können LoloBuy-QC-Fotos bestätigen?", "Wie werden internationale Versandkosten berechnet?", "Wie prüfe ich aktuelle Preise und Verfügbarkeit?", "Können mehrere Lagerartikel in einem Paket zusammengefasst werden?", "Wie verfolge ich eine LoloBuy-Bestellung und das internationale Paket?", "Was sollte ich vor dem Absenden einer Bestellung prüfen?", "Können sich Produktpreise und Verfügbarkeit ändern?"],
  fr: ["Comment fonctionne LoloBuy pour un débutant ?", "Que peuvent confirmer les photos QC de LoloBuy ?", "Comment l’expédition internationale est-elle calculée ?", "Comment vérifier les prix et la disponibilité en direct ?", "Peut-on regrouper plusieurs articles de l’entrepôt ?", "Comment suivre une commande LoloBuy et son colis international ?", "Que faut-il vérifier avant de soumettre une commande ?", "Les prix et la disponibilité peuvent-ils changer ?"],
  es: ["¿Cómo funciona LoloBuy para principiantes?", "¿Qué pueden confirmar las fotos QC de LoloBuy?", "¿Cómo se calcula el envío internacional?", "¿Cómo verifico precios y disponibilidad en vivo?", "¿Se pueden consolidar varios artículos del almacén?", "¿Cómo sigo un pedido de LoloBuy y su paquete internacional?", "¿Qué debo revisar antes de enviar un pedido?", "¿Pueden cambiar los precios y la disponibilidad?"],
  it: ["Come funziona LoloBuy per chi inizia?", "Cosa possono confermare le foto QC di LoloBuy?", "Come viene calcolata la spedizione internazionale?", "Come verifico prezzi e disponibilità in tempo reale?", "È possibile consolidare più articoli in magazzino?", "Come seguo un ordine LoloBuy e il pacco internazionale?", "Cosa devo controllare prima di inviare un ordine?", "Prezzi e disponibilità possono cambiare?"],
  pt: ["Como o LoloBuy funciona para iniciantes?", "O que as fotos QC do LoloBuy podem confirmar?", "Como o envio internacional é calculado?", "Como verificar preço e disponibilidade em tempo real?", "É possível consolidar vários itens do armazém?", "Como rastrear um pedido LoloBuy e o pacote internacional?", "O que devo verificar antes de enviar um pedido?", "Preços e disponibilidade podem mudar?"],
  pl: ["Jak LoloBuy działa dla początkujących?", "Co mogą potwierdzić zdjęcia QC LoloBuy?", "Jak obliczana jest wysyłka międzynarodowa?", "Jak sprawdzić aktualną cenę i dostępność?", "Czy można połączyć kilka produktów z magazynu w jedną paczkę?", "Jak śledzić zamówienie LoloBuy i przesyłkę międzynarodową?", "Co sprawdzić przed złożeniem zamówienia?", "Czy ceny i dostępność produktów mogą się zmienić?"],
  nl: ["Hoe werkt LoloBuy voor beginners?", "Wat kunnen QC-foto’s van LoloBuy bevestigen?", "Hoe worden internationale verzendkosten berekend?", "Hoe controleer ik live prijzen en beschikbaarheid?", "Kunnen meerdere magazijnartikelen worden samengevoegd?", "Hoe volg ik een LoloBuy-bestelling en internationaal pakket?", "Wat moet ik controleren voordat ik een bestelling indien?", "Kunnen prijzen en beschikbaarheid veranderen?"],
  sv: ["Hur fungerar LoloBuy för nybörjare?", "Vad kan LoloBuys QC-foton bekräfta?", "Hur beräknas internationell frakt?", "Hur kontrollerar jag aktuellt pris och lagersaldo?", "Kan flera lagervaror samlas i ett paket?", "Hur spårar jag en LoloBuy-beställning och det internationella paketet?", "Vad bör jag kontrollera innan jag skickar in en beställning?", "Kan produktpriser och lagersaldo ändras?"],
  da: ["Hvordan fungerer LoloBuy for begyndere?", "Hvad kan LoloBuy QC-billeder bekræfte?", "Hvordan beregnes international fragt?", "Hvordan kontrollerer jeg aktuelle priser og lagerstatus?", "Kan flere lagervarer samles i én pakke?", "Hvordan sporer jeg en LoloBuy-ordre og den internationale pakke?", "Hvad skal jeg kontrollere, før jeg indsender en ordre?", "Kan priser og lagerstatus ændre sig?"],
  no: ["Hvordan fungerer LoloBuy for nybegynnere?", "Hva kan LoloBuy QC-bilder bekrefte?", "Hvordan beregnes internasjonal frakt?", "Hvordan sjekker jeg gjeldende pris og tilgjengelighet?", "Kan flere lagervarer samles i én pakke?", "Hvordan sporer jeg en LoloBuy-bestilling og den internasjonale pakken?", "Hva bør jeg kontrollere før jeg sender inn en bestilling?", "Kan priser og tilgjengelighet endres?"],
  fi: ["Miten LoloBuy toimii aloittelijalle?", "Mitä LoloBuyn QC-kuvista voi varmistaa?", "Miten kansainvälinen toimitus lasketaan?", "Miten tarkistan ajantasaisen hinnan ja saatavuuden?", "Voiko useita varastotuotteita yhdistää yhdeksi paketiksi?", "Miten seuraan LoloBuy-tilausta ja kansainvälistä pakettia?", "Mitä pitäisi tarkistaa ennen tilauksen lähettämistä?", "Voivatko hinnat ja saatavuus muuttua?"],
  cs: ["Jak LoloBuy funguje pro začátečníky?", "Co mohou potvrdit QC fotografie LoloBuy?", "Jak se počítá mezinárodní doprava?", "Jak ověřím aktuální cenu a dostupnost?", "Lze spojit více položek ze skladu do jednoho balíku?", "Jak sledovat objednávku LoloBuy a mezinárodní zásilku?", "Co zkontrolovat před odesláním objednávky?", "Mohou se ceny a dostupnost změnit?"],
  ro: ["Cum funcționează LoloBuy pentru începători?", "Ce pot confirma fotografiile QC LoloBuy?", "Cum se calculează transportul internațional?", "Cum verific prețul și disponibilitatea în timp real?", "Pot fi consolidate mai multe articole din depozit?", "Cum urmăresc o comandă LoloBuy și coletul internațional?", "Ce trebuie verificat înainte de trimiterea unei comenzi?", "Se pot schimba prețurile și disponibilitatea?"],
  hu: ["Hogyan működik a LoloBuy kezdőknek?", "Mit igazolhatnak a LoloBuy QC-fotói?", "Hogyan számítják a nemzetközi szállítást?", "Hogyan ellenőrizhetem az aktuális árat és készletet?", "Összevonható több raktári termék egy csomagba?", "Hogyan követhetem a LoloBuy-rendelést és a nemzetközi csomagot?", "Mit ellenőrizzek a rendelés elküldése előtt?", "Változhatnak az árak és a készletadatok?"],
  el: ["Πώς λειτουργεί το LoloBuy για αρχάριους;", "Τι μπορούν να επιβεβαιώσουν οι φωτογραφίες QC του LoloBuy;", "Πώς υπολογίζονται τα διεθνή μεταφορικά;", "Πώς ελέγχω ζωντανά τιμές και διαθεσιμότητα;", "Μπορούν να ενοποιηθούν πολλά είδη αποθήκης;", "Πώς παρακολουθώ μια παραγγελία LoloBuy και το διεθνές δέμα;", "Τι πρέπει να ελέγξω πριν υποβάλω παραγγελία;", "Μπορούν να αλλάξουν οι τιμές και η διαθεσιμότητα;"],
  uk: ["Як працює LoloBuy для початківців?", "Що можуть підтвердити QC-фото LoloBuy?", "Як розраховується міжнародна доставка?", "Як перевірити актуальну ціну та наявність?", "Чи можна об’єднати кілька товарів зі складу в одну посилку?", "Як відстежувати замовлення LoloBuy і міжнародну посилку?", "Що перевірити перед оформленням замовлення?", "Чи можуть змінюватися ціни та наявність?"],
  tr: ["LoloBuy yeni başlayanlar için nasıl çalışır?", "LoloBuy QC fotoğrafları neyi doğrulayabilir?", "Uluslararası kargo nasıl hesaplanır?", "Güncel fiyatı ve stok durumunu nasıl doğrularım?", "Birden fazla depo ürünü tek pakette birleştirilebilir mi?", "LoloBuy siparişini ve uluslararası paketi nasıl takip ederim?", "Sipariş göndermeden önce neyi kontrol etmeliyim?", "Ürün fiyatları ve stok durumu değişebilir mi?"],
  ru: ["Как работает LoloBuy для новичков?", "Что могут подтвердить QC-фото LoloBuy?", "Как рассчитывается международная доставка?", "Как проверить актуальную цену и наличие?", "Можно ли объединить несколько товаров со склада в одну посылку?", "Как отследить заказ LoloBuy и международную посылку?", "Что проверить перед оформлением заказа?", "Могут ли измениться цены и наличие?"],
  bg: ["Как работи LoloBuy за начинаещи?", "Какво могат да потвърдят QC снимките на LoloBuy?", "Как се изчислява международната доставка?", "Как да проверя актуалната цена и наличност?", "Могат ли няколко складови артикула да се обединят в една пратка?", "Как да проследя поръчка LoloBuy и международната пратка?", "Какво да проверя преди изпращане на поръчка?", "Могат ли цените и наличността да се променят?"],
  ja: ["初心者はLoloBuyをどのように利用しますか？", "LoloBuyのQC写真で何を確認できますか？", "国際送料はどのように計算されますか？", "最新の価格と在庫をどう確認しますか？", "倉庫内の複数商品を一つの荷物にまとめられますか？", "LoloBuyの注文と国際小包をどう追跡しますか？", "注文を送信する前に何を確認すべきですか？", "商品価格と在庫は変わることがありますか？"],
  ko: ["초보자는 LoloBuy를 어떻게 이용하나요?", "LoloBuy QC 사진으로 무엇을 확인할 수 있나요?", "국제 배송비는 어떻게 계산되나요?", "실시간 가격과 재고를 어떻게 확인하나요?", "창고의 여러 상품을 한 소포로 합칠 수 있나요?", "LoloBuy 주문과 국제 소포를 어떻게 추적하나요?", "주문을 제출하기 전에 무엇을 확인해야 하나요?", "상품 가격과 재고는 바뀔 수 있나요?"],
  ar: ["كيف يعمل LoloBuy للمبتدئين؟", "ما الذي يمكن أن تؤكده صور فحص الجودة في LoloBuy؟", "كيف تُحسب تكلفة الشحن الدولي؟", "كيف أتحقق من السعر والتوفر مباشرة؟", "هل يمكن دمج عدة منتجات في المستودع في طرد واحد؟", "كيف أتتبع طلب LoloBuy والطرد الدولي؟", "ما الذي يجب التحقق منه قبل إرسال الطلب؟", "هل يمكن أن تتغير الأسعار والتوفر؟"],
  zh: ["新手如何使用 LoloBuy？", "LoloBuy 质检照片可以确认什么？", "国际运费是如何计算的？", "如何核对实时价格与库存？", "仓库中的多个商品可以合并发货吗？", "如何追踪 LoloBuy 订单和国际包裹？", "提交订单前应该检查什么？", "商品价格和库存会发生变化吗？"],
};

export const faqExtraAnswers: Record<LocaleCode, readonly [string, string]> = {
  en: ["LoloBuy states that products stored in the warehouse can be selected and submitted as one parcel. Confirm item eligibility, route restrictions, parcel details, and the live total before submission.", "Use the order or parcel status shown in your LoloBuy account and the carrier tracking number when one is issued. Status wording and scan timing can vary, so use the live account and carrier record as the source of truth."],
  de: ["LoloBuy gibt an, dass im Lager befindliche Produkte ausgewählt und als ein Paket eingereicht werden können. Prüfe vor dem Absenden Eignung, Routenbeschränkungen, Paketdaten und Live-Gesamtsumme.", "Nutze den Bestell- oder Paketstatus im LoloBuy-Konto und nach Ausgabe die Sendungsnummer des Transporteurs. Bezeichnungen und Scan-Zeitpunkte können variieren; maßgeblich sind Konto und Transporteur."],
  fr: ["LoloBuy indique que les produits stockés à l’entrepôt peuvent être sélectionnés et soumis dans un même colis. Vérifiez l’éligibilité, les restrictions, les détails du colis et le total en direct.", "Consultez le statut de la commande ou du colis dans votre compte LoloBuy puis le numéro du transporteur lorsqu’il est émis. Les libellés et délais de scan varient ; fiez-vous aux données en direct."],
  es: ["LoloBuy indica que los productos almacenados pueden seleccionarse y enviarse como un solo paquete. Confirma la elegibilidad, las restricciones de ruta, los datos del paquete y el total en vivo.", "Usa el estado del pedido o paquete en tu cuenta LoloBuy y el número del transportista cuando se emita. Los textos y tiempos de escaneo pueden variar; toma como referencia los registros en vivo."],
  it: ["LoloBuy dichiara che i prodotti presenti in magazzino possono essere selezionati e inviati come un unico pacco. Verifica idoneità, restrizioni, dati del pacco e totale live.", "Usa lo stato dell’ordine o del pacco nel tuo account LoloBuy e il numero del corriere quando disponibile. Testi e tempi delle scansioni possono variare: fanno fede i dati live."],
  pt: ["O LoloBuy informa que produtos armazenados podem ser selecionados e enviados em um único pacote. Confirme elegibilidade, restrições de rota, dados do pacote e total ao vivo.", "Use o status do pedido ou pacote na conta LoloBuy e o código da transportadora quando emitido. Os nomes e horários de leitura podem variar; considere os registros ao vivo."],
  pl: ["LoloBuy podaje, że produkty w magazynie można wybrać i wysłać jako jedną paczkę. Przed wysłaniem potwierdź kwalifikację, ograniczenia trasy, dane paczki i aktualną kwotę.", "Sprawdzaj status zamówienia lub paczki na koncie LoloBuy oraz numer przewoźnika po jego nadaniu. Nazwy statusów i czas skanów mogą się różnić; liczą się dane na żywo."],
  nl: ["LoloBuy vermeldt dat producten in het magazijn kunnen worden geselecteerd en als één pakket ingediend. Controleer geschiktheid, routebeperkingen, pakketgegevens en het live totaal.", "Gebruik de bestel- of pakketstatus in je LoloBuy-account en het nummer van de vervoerder zodra dit is uitgegeven. Benamingen en scantijden kunnen verschillen; volg de live gegevens."],
  sv: ["LoloBuy uppger att produkter i lagret kan väljas och skickas som ett paket. Kontrollera behörighet, ruttbegränsningar, paketuppgifter och aktuellt totalbelopp.", "Använd order- eller paketstatusen i ditt LoloBuy-konto och transportörens spårningsnummer när det har utfärdats. Statusnamn och skanningstider kan variera; följ liveuppgifterna."],
  da: ["LoloBuy oplyser, at produkter på lager kan vælges og indsendes som én pakke. Kontroller berettigelse, ruterestriktioner, pakkedata og livebeløbet.", "Brug ordre- eller pakkestatus i din LoloBuy-konto og transportørens sporingsnummer, når det udstedes. Statusnavne og scanningstider kan variere; følg de aktuelle data."],
  no: ["LoloBuy opplyser at produkter på lager kan velges og sendes som én pakke. Kontroller kvalifisering, ruterestriksjoner, pakkedata og totalsummen live.", "Bruk ordre- eller pakkestatusen i LoloBuy-kontoen og transportørens sporingsnummer når det utstedes. Statusnavn og skannetider kan variere; følg liveinformasjonen."],
  fi: ["LoloBuy kertoo, että varastossa olevat tuotteet voidaan valita ja lähettää yhtenä pakettina. Tarkista kelpoisuus, reittirajoitukset, pakettitiedot ja ajantasainen loppusumma.", "Seuraa tilauksen tai paketin tilaa LoloBuy-tilillä ja kuljetusyhtiön seurantatunnusta, kun se annetaan. Tilanimet ja skannausajat vaihtelevat; käytä ajantasaisia tietoja."],
  cs: ["LoloBuy uvádí, že produkty ve skladu lze vybrat a odeslat jako jeden balík. Před odesláním ověřte způsobilost, omezení trasy, údaje balíku a aktuální částku.", "Použijte stav objednávky nebo balíku v účtu LoloBuy a po vydání číslo dopravce. Názvy stavů a časy skenů se mohou lišit; rozhodují živé záznamy."],
  ro: ["LoloBuy precizează că produsele din depozit pot fi selectate și trimise într-un singur colet. Confirmați eligibilitatea, restricțiile, detaliile coletului și totalul în timp real.", "Folosiți starea comenzii sau coletului din contul LoloBuy și numărul transportatorului când este emis. Denumirile și timpii scanărilor pot varia; consultați datele live."],
  hu: ["A LoloBuy szerint a raktárban lévő termékek kiválaszthatók és egy csomagként feladhatók. Beküldés előtt ellenőrizd a jogosultságot, korlátozásokat, csomagadatokat és az élő végösszeget.", "A LoloBuy-fiók rendelési vagy csomagállapotát, majd a kiadott fuvarozói követési számot használd. Az állapotnevek és frissítési idők változhatnak; az élő adatok az irányadók."],
  el: ["Το LoloBuy αναφέρει ότι προϊόντα στην αποθήκη μπορούν να επιλεγούν και να υποβληθούν ως ένα δέμα. Επιβεβαιώστε καταλληλότητα, περιορισμούς, στοιχεία δέματος και ζωντανό σύνολο.", "Χρησιμοποιήστε την κατάσταση παραγγελίας ή δέματος στον λογαριασμό LoloBuy και τον αριθμό μεταφορέα όταν εκδοθεί. Οι ονομασίες και οι χρόνοι σάρωσης διαφέρουν· βασιστείτε στα ζωντανά δεδομένα."],
  uk: ["LoloBuy зазначає, що товари на складі можна вибрати й надіслати однією посилкою. Перед відправленням перевірте допустимість, обмеження маршруту, дані посилки й актуальну суму.", "Використовуйте статус замовлення або посилки в акаунті LoloBuy і номер перевізника після його видачі. Назви статусів і час сканування можуть різнитися; орієнтуйтеся на живі дані."],
  tr: ["LoloBuy, depodaki ürünlerin seçilip tek paket olarak gönderilebildiğini belirtir. Göndermeden önce uygunluğu, rota kısıtlarını, paket ayrıntılarını ve güncel toplamı doğrulayın.", "LoloBuy hesabındaki sipariş veya paket durumunu ve verildiğinde taşıyıcı takip numarasını kullanın. Durum adları ve tarama zamanları değişebilir; canlı kayıtları esas alın."],
  ru: ["LoloBuy указывает, что товары на складе можно выбрать и отправить одной посылкой. Перед отправкой проверьте допустимость, ограничения маршрута, данные посылки и актуальную сумму.", "Используйте статус заказа или посылки в аккаунте LoloBuy и номер перевозчика после его выдачи. Названия статусов и сроки сканирования могут различаться; ориентируйтесь на живые данные."],
  bg: ["LoloBuy посочва, че продуктите в склада могат да се изберат и изпратят като една пратка. Преди подаване проверете допустимостта, ограниченията, данните и актуалната сума.", "Използвайте статуса на поръчката или пратката в профила LoloBuy и номера на превозвача, когато бъде издаден. Имената и времето на сканиране може да се различават; следвайте данните на живо."],
  ja: ["LoloBuyは、倉庫内の商品を選択して一つの荷物として提出できると案内しています。対象条件、配送制限、荷物情報、最新の合計額を提出前に確認してください。", "LoloBuyアカウントの注文・荷物状況と、発行後の配送業者の追跡番号を利用してください。表示名や反映時間は変わるため、最新記録を基準にしてください。"],
  ko: ["LoloBuy는 창고 상품을 선택해 한 소포로 제출할 수 있다고 안내합니다. 제출 전에 대상 여부, 경로 제한, 소포 정보와 실시간 총액을 확인하세요.", "LoloBuy 계정의 주문·소포 상태와 발급된 운송사 추적 번호를 사용하세요. 상태 이름과 스캔 반영 시간은 달라질 수 있으므로 실시간 기록을 기준으로 확인하세요."],
  ar: ["يوضح LoloBuy أنه يمكن اختيار المنتجات الموجودة في المستودع وإرسالها في طرد واحد. تحقق قبل الإرسال من الأهلية وقيود المسار وبيانات الطرد والمجموع المباشر.", "استخدم حالة الطلب أو الطرد في حساب LoloBuy ورقم تتبع شركة النقل عند صدوره. قد تختلف أسماء الحالات وأوقات المسح؛ اعتمد على السجلات المباشرة."],
  zh: ["LoloBuy 说明可选择仓库内的商品并合并提交为一个包裹。提交前请核对商品是否符合要求、路线限制、包裹信息及实时总价。", "请先查看 LoloBuy 账户中的订单或包裹状态，获得承运商单号后再结合物流记录查询。状态名称和扫描时间可能不同，应以账户及承运商实时记录为准。"],
};

export function isLocale(value: string | undefined): value is LocaleCode {
  return Boolean(value && (localeCodes as readonly string[]).includes(value));
}
