"use client";
import { SiteHeader, useSiteLocale, type Locale } from "@/components/site-header";
const copy: Record<Locale,{title:string; intro:string; categories:string[]}>={
en:{title:"Product categories",intro:"Choose a focused starting point, then continue in the FindSpreadsheet database.",categories:["Jackets","T-Shirts","Shoes","Hoodies","Pants","Sets","Bags & Wallets","Accessories","Electronics","Home"]},
de:{title:"Produktkategorien",intro:"Wähle einen Einstieg und fahre in der FindSpreadsheet-Datenbank fort.",categories:["Jacken","T-Shirts","Schuhe","Hoodies","Hosen","Sets","Taschen & Geldbörsen","Accessoires","Elektronik","Wohnen"]},
fr:{title:"Catégories de produits",intro:"Choisissez un point de départ, puis continuez dans FindSpreadsheet.",categories:["Vestes","T-shirts","Chaussures","Sweats","Pantalons","Ensembles","Sacs & portefeuilles","Accessoires","Électronique","Maison"]},
es:{title:"Categorías de productos",intro:"Elige un punto de partida y continúa en FindSpreadsheet.",categories:["Chaquetas","Camisetas","Zapatos","Sudaderas","Pantalones","Conjuntos","Bolsos & carteras","Accesorios","Electrónica","Hogar"]},
it:{title:"Categorie di prodotti",intro:"Scegli un punto di partenza e continua in FindSpreadsheet.",categories:["Giacche","T-shirt","Scarpe","Felpe","Pantaloni","Set","Borse & portafogli","Accessori","Elettronica","Casa"]},
pt:{title:"Categorias de produtos",intro:"Escolha um ponto de partida e continue no FindSpreadsheet.",categories:["Casacos","T-shirts","Sapatos","Hoodies","Calças","Conjuntos","Bolsas & carteiras","Acessórios","Eletrónica","Casa"]},
nl:{title:"Productcategorieën",intro:"Kies een vertrekpunt en ga verder in FindSpreadsheet.",categories:["Jassen","T-shirts","Schoenen","Hoodies","Broeken","Sets","Tassen & portemonnees","Accessoires","Elektronica","Wonen"]},
pl:{title:"Kategorie produktów",intro:"Wybierz punkt startowy i kontynuuj w FindSpreadsheet.",categories:["Kurtki","T-shirty","Buty","Bluzy","Spodnie","Zestawy","Torby & portfele","Akcesoria","Elektronika","Dom"]},
sv:{title:"Produktkategorier",intro:"Välj en startpunkt och fortsätt i FindSpreadsheet.",categories:["Jackor","T-shirts","Skor","Hoodies","Byxor","Set","Väskor & plånböcker","Accessoarer","Elektronik","Hem"]}
};
export default function ProductCategories(){const locale=useSiteLocale();const t=copy[locale];return <main className="min-h-screen bg-[#e8ebf4] text-[#10213b]"><SiteHeader/><section className="mx-auto max-w-7xl px-5 pb-16 pt-14 sm:px-8 lg:px-12"><p className="text-xs font-extrabold tracking-[.16em] text-[#ff6947]">PRODUCT DIRECTORY</p><h1 className="mt-3 text-4xl font-black tracking-[-.06em] sm:text-6xl">{t.title}</h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-[#40506d]">{t.intro}</p><div className="mt-10 grid grid-cols-2 gap-3 md:grid-cols-5">{t.categories.map((category,i)=><a href="https://findspreadsheet.com" key={category} className="min-h-36 rounded-2xl border border-[#cbd3e6] bg-white p-5 transition hover:-translate-y-1 hover:border-[#1647cf] hover:shadow-lg"><span className="text-xs font-bold text-[#ff6947]">{String(i+1).padStart(2,"0")}</span><h2 className="mt-12 text-lg font-extrabold">{category}</h2></a>)}</div></section></main>}
